### ISSUE TITLE
continue adding openapi tests to specs

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#10062]
continuation of https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9776.

This is taking longer then anticipated as running the specs only shows the first error and everytime you make a change to the docs the generation script re-run. I spent some time trying to figure out a way to aggregate errors but with no luck. Going from top-down of the openapi.yaml, start after appointment check-in endpoint

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/10062?planning-poker) with Zenhub @aherzberg @Tonksthebear

**Comment by aherzberg** [comment]
continued here: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/10221
