### ISSUE TITLE
Update First Sign-in page Content

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#10064]
Acceptance Criteria:

- Update the copy first-time users see when they sign-in to the following:

> **Sign in with a verified account**
> You’ll need to sign in with an identity-verified account through one of our account providers. Identity verification helps us protect all Veterans’ information and prevent scammers from stealing your benefits.
> 
> **Don't yet have a verified account?** Continue to the sign-in page. Follow the instructions to create a Login.gov or ID.me account. Then come back here and sign in. We’ll help you verify your identity for your account.
> 
> **Not sure if your account is verified?** Sign in now. We’ll tell you if you need to verify.
> 
> [button] Continue to sign in
- Ticket has undergone VQA by Misty

**Comment by rbontrager** [comment]
@cadibemma The content looks good but there seems to be an abnormally large amount of spacing between the end of the new content and the 'Continue to sign in' button.  Would it be possible to make the spacing more in line with the rest of the app.

**Comment by rbontrager** [comment]
Verified that the sign-in page content has been changed to match above.  Verified that the spacing between the end of the wording and the button is in line with the rest of the app.  Approved by QA.
