### ISSUE TITLE
Content for downtime message for 2024 COLA updates

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#10114]
Create content related to https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10091

**Comment by mistymg** [comment]
Confirm from [CAIA/Laura W.](https://dsva.slack.com/archives/C01K37HRUAH/p1730828622840329?thread_ts=1730826771.853899&cid=C01K37HRUAH) that VA.gov will use same copy from last year with just new dates.

**Comment by mistymg** [comment]
Will sync with Binny on implementation.

**Comment by mistymg** [comment]
Today: Async collab in [DSVA Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1730994995667789)

**Comment by mistymg** [comment]
Today: Shared [mocks of our messaging](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1456-891&node-type=canvas&t=df6z2djeLiSz0cnu-0) with Laura (CAIA). Will update [DSVA Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1730994995667789) on Monday.

**Comment by mistymg** [comment]
Final, approved copy

_**v1 AF alert - before downtime**_

**header**: Upcoming maintenance: November 16 to 17, 2024

**body copy**: On Saturday, November 16, 2024, 4:00 a.m. ET, we’ll update our systems to add the 2024 cost-of-living increase for VA benefits. This update will end Sunday, November 17, 2024, 7:00 p.m. ET. During this time, you may have trouble signing in or using parts of the app. If you need help getting your VA health care and benefits information, call us. Thank you for your patience.

**phone**: 800-698-2411

**tty**: TTY: 711



_**v1 AF alert - during downtime**_

**header**: Maintenance: November 16 to 17, 2024

**body**: We’re updating our systems to add the 2024 cost-of-living increase for VA benefits. If you  have trouble signing in or using parts of the app, check back after Sunday, November 17, 2024, 7:00 p.m. ET. If you need help getting your VA health care and benefits information, you can also call us. Thank you for your patience.

**phone**: 800-698-2411

**tty**: TTY: 711


_**v2 AF alert - before downtime**_

**header**: Upcoming maintenance: November 16 to 17, 2024

**body (note paragraph spacing)**: We need to update our systems to add the 2024 cost-of-living increase for VA benefits. As we do this work, you may have trouble signing in or using parts of the app. 

Start: Saturday, November 16, 2024, 4:00 a.m. ET
End: Sunday, November 17, 2024, 7:00 p.m. ET

If you need help getting your VA health care and benefits information, call us. Thank you for your patience.

**phone**: 800-698-2411

**tty**: TTY: 711


_**v2 AF alert - during downtime**_

**header**: Maintenance: November 16 to 17, 2024

**body copy**: We’re updating our systems to add the 2024 cost-of-living increase for VA benefits. 

If you  have trouble signing in or using parts of the app, check back after Sunday, November 17, 2024, 7:00 p.m. ET. 

If you need help getting your VA health care and benefits information, you can also call us. Thank you for your patience.

**phone**: 800-698-2411

**tty**: TTY: 711

**Comment by mistymg** [comment]
Today: Passed along final copy to Eng in their ticket

**Comment by mistymg** [comment]
[Figma mockup](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1456-891&node-type=canvas&t=TqMJBYdc6sJ2LF6Q-0)

**Comment by mistymg** [comment]
Content for this is done and has been passed off to Eng in their ticket. Closing.
