### ISSUE TITLE
CU - Fix Rx Refill Confirmation Checkmark References to match Alertbox

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#10113]
## Proposed Change

Match design system component.
![Image](https://github.com/user-attachments/assets/ff4639b8-5ff4-418b-9064-f159de524704)
Green remains, checkmark should be transparent.

## Why Should We Prioritize?

To match. Matchy matchy.

## Coding Time Estimation

2
	
## Testing Considerations

VQA Through Lauren in H+B channel.

## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by DJUltraTom** [comment]
Karsyn currently has no rx with refills available and demo mode is not showing the updated design.
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZGQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fa4597ce5338a42cb40e787205dbf690e1d516b/unnamed%20%281%29.png" alt="unnamed (1).png" />

**Comment by dumathane** [comment]
That is actually the updated design I believe @DJUltraTom. You can see the Amlodipine checkmark is transparent vs the old white.

**Comment by DJUltraTom** [comment]
gotcha, misinterpreted the "To match. Matchy matchy." with the screenshot as the what we were going for, vs what we were needing to change.
This ticket requires VQA, I'm good to sign off after we get thumbs up/down from

**Comment by wavelaurenrussell** [comment]
Looks great!

**Comment by DJUltraTom** [comment]
based on design comment above, QA approves this change

**Comment by DJUltraTom** [comment]
verified the checkmarks "matchy matchy" in the RC build, closing as deployed
