### ISSUE TITLE
CU - Create a way to bypass phone number display with Availability Framework

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#10138]
## Proposed Change

There are times when supplying a contact phone number is not appropriate when using availability framework. Create a way to bypass the default display when desired.

## Why Should We Prioritize?

There are times when supplying a contact phone number is not appropriate when using availability framework. Also, to make content people happy.

## Coding Time Estimation

1
	
## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by rbontrager** [comment]
Verified that if no phone number is typed in, then no phone number is displayed and that if a phone number is typed in then a phone number is displayed. Ran the AF detox tests and verified that everything passed.  Approved by QA.
