### ISSUE TITLE
Content - Create popup for users when PII detected

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#10234]
When PII is detected in a users freetext response to In App Feedback, we will want to present the user with a native alert asking the user if they are sure they aren't including PII. The native alert will allow the user to continue but we will replace any detected PII with dummy data.

Please create the content for the Native Alert regarding the pii detection warning.

**Comment by mistymg** [comment]
@dumathane @ajsarkar28 

Questions:

1. Does @danielleoppendike agree this message should be served in a native alert? Just wanted to make sure UX has approved of the interaction piece.
2. Does VA.gov do any kind of messaging for their feedback interaction when PII is detected? If so, can you please get that for me?

**Comment by dumathane** [comment]
1. Yes, she has been sourced and approved.
2. If they do, it's through medallia, so no I'm afraid I can't do so.

**Comment by mistymg** [comment]
Confirmed with Ameet no need to tell users at this point we'll replace their PII with dummy data.

**Comment by ajsarkar28** [comment]
@mistymg 
I like it!

**Comment by mistymg** [comment]
@dumathane Need anything else from on me this or you all set?

**Comment by danielleoppendike** [comment]
![Image](https://github.com/user-attachments/assets/6bd7b49e-b0bb-4b2d-bca7-691815a24933)
@mistymg Here is the draft you proposed in the mock - I'm fine with this. Are there any tweaks you'd like to make?

**Comment by mistymg** [comment]
@danielleoppendike Looks good to me!
