### ISSUE TITLE
More Icon conversions again

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#10313]
Form Attachments(start new message, reply message screens after attaching an image) - paperclip
Collapsible message(messages in threads) - paperclip
Attachment LInk(view message screen) - paperclip
LabelTag - Info icon on prescriptions
Photo Preview - The cancel, and highlighted icons in the claims upload photo screen
Large Nav button - right arrow in circle

**Comment by rbontrager** [comment]
Verified that the app icons above match the design system library app icons.  Approved by QA.
