### ISSUE TITLE
Appt Request Flow- Define, Discover, Usability Test

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va-mobile-app#1918]
# Epic
  

## User Story
As a user, I want to make a request for an appointment in the app so that I can quickly complete tasks on my phone. 

## Discovery Outcomes
- Shared understanding of how scheduling works for VAOS currently
- Define recommendations for how we could build scheduling within the mobile app 
- Create UI designs
- Usability Testing

### Key Takeaways
 
See [Appointment Request/Schedule kickoff doc ](https://docs.google.com/document/d/1KOaN11SqKjIh_xooXWSdFN4d744nsFAiqqTBV15iQP0/edit?usp=sharing)

### Staging test accounts used to do discovery research

- Judy Morrison

**Comment by MekoHong** [comment]
Epic is no longer being worked at this time.  Closing; a new epic to be created if picked up in the future
