### ISSUE TITLE
Enable DebugView for Signed Releases (QA)

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#2775]
## Description 
As part of https://github.com/department-of-veterans-affairs/va-mobile-app/issues/2589, we added a flag to enable performance and analytics in staging.  This enables us to see analytics in real time in Firebase's DebugView, however it only works for unsigned builds. We want to determine if there is a solution to this so that QA can more easily test analytics events. Some potential ideas:
- Figure out if DebugView is possible on signed builds
- If not, can we provide unsigned .apk's or .aab's to QA?
  - Can we automate this somehow?

## Acceptance Criteria
  

-  [ ] Investigate options to allow QA to use DebugView
-  [ ] Implement this solution
-  [ ] Inform QA on the process

**Comment by TKDickson** [comment]
See notes in #7226, closing this ticket as well.
