### ISSUE TITLE
BUG - sev-3 - All - Cancel button on message submission waiting screen doesn't work, maybe we should respect it

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#2810]
## What happened?
In secure messaging, after tapping "send" on a message/reply, then tapping "send message" again on the confirmation screen to actually send it -- I'm brought to a "we're sending your message" waiting/loading screen, that has the usual "Cancel" button in the header.

That Cancel button doesn't work/is just ignored -- see video in the screenshots section of me hitting that button, the message composition page starting to load, and then immediately being overwritten by the "message sent successfully" page.

## Specs:

- Device:
- OS:
- User Account: +41 has messaging
- Accessibility State:

## Steps to Reproduce
1. Log in. Health > Messaging > (get into message drafting - can either be a reply to a message that's newer than 45 days old, or 'compose a new message')
2. Fill out the required fields, then tap "send" at the bottom of the composition screen. Tap "send message" again on the message send confirmation screen.
3. Wait a tiny smidge of time but not a lot (like 1 second), then tap 'cancel' on the message sending waiting screen in the header, per the video
4. Message appears to send anyways, as the message sent successfully screen appears

## Desired behavior 
Determined based on comments discussions between Holly / Binny 

- The best way to handle this is to implement the abort controller in every instance where the user can save or submit data.
- As a result, we can keep all of the Cancel buttons, and they actually cancel the action (this means no inaccurate actions or "dead" buttons).
- This also means users won't get stuck on a screen forever or have to force quit if there's a delay (because they can cancel out of the flow).
- All of our loader states are restricted to occurring in the content area, so no issues with top bar buttons becoming unavailable if the loader gets hung up

.

## Screen shot(s) and additional information
Google Drive sometimes thinks my iOS screen recordings are word documents, so [a link to the video](https://drive.google.com/file/d/1pOWqXZbOFSpVcTqVhTh0sP8losLd5IeX/view?usp=sharing) is the best I can do.

## Additional Tasks
- [ ] Add additional labels (i.e. front-end, back-end)
- [ ] Make sure to add ticket to the Bug Backlog on the VA-Mobile-Eng board

**Comment by bischoffa** [comment]
@dumathane I added this to Pending Handoff to see if we can size the desired state which seems would be bigger than 1 point. If you deem differently let me know.

**Comment by dumathane** [comment]
This ticket can probably be closed and pointed at https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5583.

**Comment by bischoffa** [comment]
Work to be done in ticket 5583. Closing this ticket
