### ISSUE TITLE
UX TLC - Segmented controller vs tabs

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va-mobile-app#3040]
## Description 
We're currently using segmented controllers incorrectly in a few places—to show peer data sets rather than alternate views of the same data set (ex: Status Details)
Segmented controllers should be used to show alternate views of the same data set (ex: Claims list, Appointments list). 

-  [ ] Identify places where we use [segmented controllers](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=3876-7640&mode=design&t=GfZ3i16ThQ2UXUrt-4) & determine if they should be changed to [tabs](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=3876-7638&mode=design&t=GfZ3i16ThQ2UXUrt-4)
    - Example: Claim & Appeal Details screen

## Acceptance Criteria 
-  [ ] List of locations using segmented controller
-  [ ] Recommendation for whether it should stay or change to tabs 
-  [ ] Design comps if necessary

**Accessibility Requirements**

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by jessicawoodin** [comment]
Tabs component was deprecated in February 2024.
