### ISSUE TITLE
UX TLC - Pagination a11y

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va-mobile-app#3046]
## Description 

In list views, our pagination (ex: Messages, Vaccines), shows up after 10 list items, but below the visible screen, requiring scrolling to see.
A11y Issue: Per WCAG 2.0: "3.3 Positioning important page information so it is visible without requiring scrolling can assist users with low vision and users with cognitive impairments."

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by jessicawoodin** [comment]
Will be addressed with Pagination component in design system.
