### ISSUE TITLE
UX TLC - Lack of consistency in use of alert modal

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va-mobile-app#3061]
## Description 
For the following screens, we need to 1. determine if an alert is needed and if yes, update the border to align with correct pattern or if no, remove the alert. 
List of screens:
1. Profile>Settings>Notification Settings
2. Profile> Personal & Contact Info> Adresses > Home, Mailing
3. Profile> Personal & Contact Info> Contact > Home, Work, Mobile, Fax
4. Profile> Personal & Contact Info> Contact Email Address > Email Address
5. Health Care>Messages  (applies to reply and compose message screens).
6. Claims: Determine if the partial alert should include call info and a refresh button? If so, update to include this.
## Acceptance Criteria
  

-  [ ] Determine if alert is needed
-  [ ] Create rule
-  [ ] Delete unneeded alerts. 

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by jessicawoodin** [comment]
Will be addressed with #6912
