### ISSUE TITLE
CU - Use ClickToCallPhoneNumber App Wide

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#3198]
## Proposed Change

ClickToCallPhoneNumber is a pre-existing component that should be supplied to all locations we are providing a phone link. Currently there are three examples that are not: NeedHelpData, VeteransCrisisLineScreen, and IncorrectServiceInfo. 

## Why Should We Prioritize?

For clarity, bug-avoidance, and theme consistency we should reduce the amount of components accomplishing the same/similar outcomes.

## Coding Time Estimation

(1 - cup of coffee, 2 - morning, 3 - afternoon, 5 - day, 8 - day and half to 2 days, 13 - a few days or more, 21 - a week +)
3

**Comment by rbontrager** [comment]
Verified that the phone numbers in veteran crisis line and need help data are the same as they were before the change on iOS and Android.  Approved by QA.
