### ISSUE TITLE
Common Component Ticket: Loading Component

### ISSUE THREAD

**Issue by kidlaurenpeace** [department-of-veterans-affairs/va-mobile-app#3281]
# Common Component Ticket
Goal: To document the Loading component used in many places of the app.

### Purpose
The Loading Component is used to indicate ongoing activity  or an action is being processed. It provides the status of an indeterminate loading time.

### Usage
Used to notify users that their requested action is being processed or there is an ongoing activity that must process before they can move on to another screen. 

### Component
[Loading Indicator Light Mode](https://www.sketch.com/s/dc5da595-7a22-4cdd-a850-bd91a80dd377/a/ag8pJOP)
[Loading Indicator Dark Mode](https://www.sketch.com/s/dc5da595-7a22-4cdd-a850-bd91a80dd377/a/7yr9Dm2)

### Accessibility
 - [ ] Discuss with group: _Assume we do something with announcements and aria labels_ ([see VA.gov recs](https://design.va.gov/components/loading-indicator#accessibility-considerations))

### Best Practices
The loading component should:
- Notify users that their request processing and the action will soon complete.
- Use [VA.gov loading indicator component for animations](https://design.va.gov/components/loading-indicator)

### Content Guideline
See [content spreadsheet](https://docs.google.com/spreadsheets/d/1vSpeZj0c1V_OnQZTp3FolyUb_H0H66z4ETXJLUXjxKs/edit#gid=0) for strings in use.
Accurately explain the state of the requested action, begin with a verb. For example, “Loading”, “Submitting”, “Processing”.
Use as few words to describe the state as possible.

### Example
![light loading-component-in-appointments](https://user-images.githubusercontent.com/53520623/172468955-33b2a716-9cef-48bf-bd77-83a20ec3ce64.png) ![dark loading-component-in-appointments](https://user-images.githubusercontent.com/53520623/172468946-bbaaeb08-c96c-48e8-8974-287ce7d68a6d.png) 
![load sign-in](https://user-images.githubusercontent.com/53520623/172674200-1aeb5580-d880-4189-91a0-102e67733366.png) ![load sign-out](https://user-images.githubusercontent.com/53520623/172684064-fe4d723c-b6bf-4a10-92f5-b1def19c1a57.png)

### Related Components/Resources
- Spinner icon?
- Reference [Loading Indicator](https://design.va.gov/components/loading-indicator#accessibility-considerations) on VA.gov

#### After filling out the ticket
- [x] Tag Jen Ecker, Narin Ratana, and Therese Dickson in a comment on this ticket, and one of them will be in touch to book a walkthrough with you.

#### After component committee review is finished
- [ ] PR submitted to add the component to the Front End > Components section of the documentation site
- [ ] UX, QA, and FE reps on the component committee have socialized the new component with their respective teams
- [ ] Moved ticket to the 'Ready to hand off to Eng' column on the VA-Mobile-UX board

**Comment by jessicawoodin** [comment]
Will be addressed with DS ticket #7602
