### ISSUE TITLE
TLC - Last two (probably) loading components without strings need attention

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3296]
## What happened?

Patrick Saxton says:
> String less loaders can be assumed to be an oversight 

(First one is part of some really random stuff and got moved to its own ticket, #3332, so ignore it for this ticket)

Second one: if there’s a problem loading military service info during initial login, then you [attempt to open the military info page](https://drive.google.com/file/d/1d4tgE684KbazvbXmX0xfK8H3G-UcqRxa/view?usp=sharing)

## Specs:

- User Account: +41 has messages with attachments (please try the already-read messages first)

## Desired behavior

Misty has already provided the new strings for these.
For string 2 I'd suggest the string should be "Loading your military information..."

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Linked to an Epic (General Tech/Design Debt & Maintenance)

**Comment by dumathane** [comment]
I think this ticket is no longer reproducible. @TKDickson could you confirm?

**Comment by TKDickson** [comment]
Can confirm - military history screen is showing a "Loading your military information" string under the loading indicator, closing.
