### ISSUE TITLE
TLC - Messages: smart component loading UX decisions to make

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3332]
## What happened?

Loading message details, when there are attachments, has some undesirable loading behavior.

Problem one (ticket #3331 ): _The full-page loading screen for opening an attachment is missing_

Problem two (this ticket): The spinner style for opening up a message and awaiting attachments filling in ('smart component' spinner, video below) seems to have gotten mixed up with opening an attachment (second spinner, which is being brought back to a loading page rather than loading indicator in the ticket above). This is the only place we have a smart component (once the message is opened, the component is calling to get the attachment info). 

 [(Spinner for attachment filling in)](https://drive.google.com/file/d/1AUrxN6OYJbXv0lgG4VUo3K3Y9w8uBsRX/view?usp=sharing)

## Specs:

- Device:
- OS:
- User Account: +41 or anyone else with messages with attachments (please open UNREAD messages when possible to preserve testing data, thanks!)
- Accessibility State:

## Steps to Reproduce

1. Log in.
2. Health > Messages > [pick an (ideally unread) message from the list, that has an attachment] > EXPAND THE MESSAGE WITH THE ATTACHMENT IN IT to get the 'smart component' spinner that this ticket is about 
3. Notice that the smart spinner a) is too big and b) isn't accessible
4.  Now tap the attachment name to open the attachment -> get teeny tiny spinner right next to the attachment link/name while you're waiting for the attachment to open, which is the original desired size for the smart component spinner

## Desired behavior

Smart components may feature more heavily in personalization attempts, so we should figure out what we want to do with them from a UX perspective, and then work with Eng to see if it's feasible.

Decisions that UX needs to make/things that need more investigation:
- [x] What's the behavior that we want for this smart component? (Should it be custom or native spinner? Does it have a string while it's loading? Etc) **A: Use custom component – indicated in the Figma mockup**
- [x] How should accessibility work for this component? (Right now it's not recognized/read out by screen readers, for example; also needs to work for Switch/Voice access, etc) **A: See A11y guidance outlined below**

**UPDATES 10/19/23:**
Design solution outlined in the comments. [Link to Figma here](https://www.figma.com/file/B3cMgZxUlawJhbK7ltDbco/Lauren's-Sandbox?type=design&node-id=1116-549&mode=design&t=J8tYHehkdNQI7FRO-4).

**A11y guidance**
- Label: "Loading"
- Role: Loading indicator
- Hint: "Loading your attachment"
- Status: Active (if this makes sense here?)
- Value: 1 of X (number of attachments that need to load)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Linked to an Epic (General Tech/Design Debt & Maintenance)

**Comment by kidlaurenpeace** [comment]
Solution as outlined: 
- Apply string below spinner, referenced in #3331
- Localize the spinner to Attachments area

[Figma reference link](https://www.figma.com/file/B3cMgZxUlawJhbK7ltDbco/Lauren's-Sandbox?type=design&node-id=1107-13&mode=design)

Solution screenshot
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fec9175e71a7d42de44d2317b80ea3361f373f0/TLC%20-%20Messages%20-%20Solution%20-%20Smart%20component%20UX%20bug%203332.png)

**Comment by bischoffa** [comment]
@drjecker Lauren has worked this ticket. Thus its ready for your consideration for UX initiatives for future sprint planning.

**Comment by bischoffa** [comment]
Per convo on 10/23, we will be closing out this ticket and PM will make a FE ticket for this UX initiative. Adam / Jen to meet to discuss how to handle this in the future.

**Comment by bischoffa** [comment]
FE ticket for this work [7096 ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7096)
