### ISSUE TITLE
Common Component Ticket: Out of app link

### ISSUE THREAD

**Issue by melissa-lefevre** [department-of-veterans-affairs/va-mobile-app#3402]
# Common Component Ticket

### Purpose
Consistently using the the out of app icon with link gives users a cue that they will be leaving the app if they follow the link. 

### Usage

In general it is best to keep users in the app. As we saw in usability testing, users can experience difficulty tying moving around their phone to find and open the app once they leave. However, if they are trying to complete a task that involves signing in to their account on [va.gov](http://va.gov/) for more extensive tasks, it is best to have them use the out of app browser.

 **Proposed rule for keeping user in the app:** Webpages that does not need a separate sign-in in order to access the content. For example, the "find a location tool" does not need the user to sign in, so we can keep them in the app in a webview.

**Proposed rule for sending the user out of the app with a "you are leaving alert":** If the user needs to sign into their account on the website in order to access tools, complete tasks, and read details about their account that are not in the app.
I added a [column in this spreadsheet](https://docs.google.com/spreadsheets/d/14cw_2K-uLrUL-m4ATHsBEjC4tOsDNklWOlN2DdsbJDQ/edit#gid=1283894560) for the recommended change from opening the out of app web view to keeping the user in the app with the in-app webview using the rules above. There are 4 instances where we would see the change.
### Component

Primary and secondary use it up to the discretion of the designer. When the link requires more visual prominence, the primary can be used and in a situation where the link should be more subtle, the secondary can be used. Here is a [link to the mural ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1653404508550/be65976dc28bb3d98641f4d20f5b777d299454d1?wid=0-1653586197684)for more examples. 

## Next Steps

Clean-up for this documentation ticket,
- add sections that are missing (UX)
- Remove/move to different spot in ticket the implementation details from here
- bring back to the Component Committee for review

#### After filling out the ticket
- [x] Tag Jen Ecker, Narin Ratana, and Therese Dickson in a comment on this ticket, and one of them will be in touch to book a walkthrough with you.

#### After component committee review is finished
- [ ] PR submitted to add the component to the Front End > Components section of the documentation site
- [ ] UX, QA, and FE reps on the component committee have socialized the new component with their respective teams
- [ ] Moved ticket to the 'Ready to hand off to Eng' column on the VA-Mobile-UX board

**Comment by jessicawoodin** [comment]
Addressed with DS ticket #6747
