### ISSUE TITLE
Test Plan for New OS Versions

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va-mobile-app#3563]
## Task
Each year in the fall, both iOS and Android release new versions.

In order to maintain compatibility, the teams will need to test against release candidates of the new versions and raise any issues to be fixed prior to the new OS rolling out.

In order to accomplish this and to maintain a baseline for how we test these in the future, we will need to create the process for how the team with test, review and mitigate for new OS versions. 

The output of this ticket should be the first draft of a testing plan, as well as an outline of a documentation page on how to load OS RC's and plan overview.
## Questions
- How many different devices/form factors do we need to test on?
- When should we pick up an OS to test?
- How do bugs get tracked and resolved? 
- Is there a process for this?

### Outcomes
- [x] First draft of testing plan for Android and iOS upcomming versions
- [x] Outline of documentation page on downloading RCs

**Comment by TKDickson** [comment]
@bischoffa yes still relevant and it's home team work. Will add to the general QA home team epic. (I also put it on the epic that I created for the OS version sprint 0, a bit back)

**Comment by bischoffa** [comment]
@DJUltraTom any updates on this ticket?

**Comment by DJUltraTom** [comment]
https://docs.google.com/document/d/12edey_A85yTlOfEVRo1UAY2Lims9NSH2ewjIHBpR4Ec/edit
Started a file to address questions and a proposal, will continue on this monday

**Comment by DJUltraTom** [comment]
above linked document has been updated. emails sent to QART team for feedback

**Comment by bischoffa** [comment]
@DJUltraTom given this is continuing into this sprint can you update the sprints to include the current one its in?

**Comment by DJUltraTom** [comment]
created [9182](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9182) for the next step of this process
closing this ticket as both outcomes of this ticket have been met.
