### ISSUE TITLE
Detox UI test: Sign in

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3709]
## Description 
As a QA automation engineer, I want to automate regression testing the VA mobile app where possible/meaningful, to free up QA time for areas that benefit the most from manual testing, or on non-testing initiatives that benefit the team.

As part of this story we want to:
- Create a detox test that replaces the [sign in cases](https://dsvavsp.testrail.io/index.php?/cases/view/8534) in the RC suite   

## Acceptance Criteria
  

-  [ ] Create detox test that covers all cases for this section
-  [ ] Evaluate this section in app (if there are *additional* cases that could be added to the detox test, not currently covered in RC, because it'll be faster/easier/valuable for automated testing to have them and perhaps that wasn't true for manual testing) <-- the conclusions from this evaluation must be documented in this ticket
-  [ ] If additional cases could be added, create a new ticket for those & link it in this ticket

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed? UI/nav test only --> can be accomplished meaningfully via demo mode
- Does this require QA? n/a
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic <-- n/a for detox automation tickets right now

**Comment by bischoffa** [comment]
@jennb33 @cadibemma What is the status of this ticket? I see it was in code review a month ago but no comments since and no movement.

**Comment by cadibemma** [comment]
This is the ticket that im wrapping up today

**Comment by bischoffa** [comment]
I added Sprint 79 to this ticket since working is happening this sprint on it.
