### ISSUE TITLE
Detox UI test: Onboarding

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3710]
## Description 
As a QA automation engineer, I want to automate regression testing the VA mobile app where possible/meaningful, to free up QA time for areas that benefit the most from manual testing, or on non-testing initiatives that benefit the team.

As part of this story we want to:
- Create a detox test that replaces the [onboarding cases](https://dsvavsp.testrail.io/index.php?/cases/view/8535) in the RC suite   

## Acceptance Criteria
  

-  [ ] Create detox test that covers all cases for this section
-  [ ] Evaluate this section in app (if there are *additional* cases that could be added to the detox test, not currently covered in RC, because it'll be faster/easier/valuable for automated testing to have them and perhaps that wasn't true for manual testing) <-- the conclusions from this evaluation must be documented in this ticket
-  [ ] If additional cases could be added, create a new ticket for those & link it in this ticket

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed? UI/nav test only --> can be accomplished meaningfully via demo mode
- Does this require QA? n/a
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic <-- n/a for detox automation tickets right now

**Comment by bischoffa** [comment]
@rbontrager was this ticket planned for this sprint? I see its being worked on but does not have the sprint tag. If planned for this sprint can you add the sprint to it? 

CC @jennb33

**Comment by bischoffa** [comment]
@rbontrager please add the sprint tag to this ticket.

**Comment by timwright12** [comment]
Closing this because it was merged quite a while ago
