### ISSUE TITLE
Spike - detox & PDFs

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3719]
## Description 
As a QA automation engineer, I want to automate regression testing the VA mobile app where possible/meaningful, to free up QA time for areas that benefit the most from manual testing, or on non-testing initiatives that benefit the team.

As part of this story we want to:
- Investigate how well detox handles PDFs.

This is both checking how easy it is to navigate to and from screens in the app that are essentially just PDF downloads, and what elements (if any) detox can actually check for on those pages (or while attempting to navigate to those pages). If detox can't locate any of the elements on these pages, we'll need to continue to check them through manual testing. If detox can handle them, I can set up UI automation for Letters.

## Acceptance Criteria
  

-  [ ] Experiment/investigate if there are options to have detox check/navigate PDF pages
-  [ ] Document the conclusions from this evaluation in this ticket
-  [ ] If there's subsequent work to be done based off of the spike investigation, create new ticket(s) & link in this ticket

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed? 
- Does this require QA? n/a
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic <-- n/a for detox automation tickets right now

**Comment by bischoffa** [comment]
Without a DevOpsv person this ticket will have to be worked by a Flagship App team

**Comment by TKDickson** [comment]
Closing as outdated
