### ISSUE TITLE
Rx: Dynamic fill date name (past or future)

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va-mobile-app#3764]
## Description
The "last fill date" on a prescription can refer to either a past or future date. In order to make that clear, dynamic copy should be added. 

## Acceptance Criteria

- [ ] Add logic that changes the last fill date copy depending on the current date
  - When it's a date prior to the current date the copy should say: "Last fill date"
  - When it's the current date or a date in the future of the current date the copy should say: "Scheduled fill date"

### Links

[Last Fill Date](https://www.figma.com/file/8q57m5iLjpaBRcU8ozX8f4/Sprint-Icebox?node-id=128%3A2147)
[Current or Future Fill Date](https://www.figma.com/file/8q57m5iLjpaBRcU8ozX8f4/Sprint-Icebox?node-id=128%3A2259)

### Screenshots
![image.png](https://images.zenhubusercontent.com/5f7bb216620a259ab7e50d60/169bc863-9699-4605-9bb4-3d60844ea7b1)

**Comment by Sparowhawk** [comment]
@ala-yna do we want to close this one out?
