### ISSUE TITLE
Our error messaging for EVSS v1 user service down is not consistent

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#3815]
## What happened?

Quick definitions:
**v1 user call:** happens at login, and is what we use to figure out which features a veteran has access to (among other things returned by that service)
**v1 user call doesn't succeed:** would be a "something is wrong unexpectedly" -- like the call to the service timed out, or EVSS is down in production. (Should not happen for a planned maintenance window, we have different ways of handling that when we get that info from the service(s))

If the initial v1 user call doesn't succeed, our error messaging is pretty inconsistent across the app for the features a veteran can attempt to load.

Some screens (profile and claims) are displaying a "your internet is broken" error. Some screens (messaging and appointments) are treating it like the app knows FOR SURE that the veteran doesn't have access to that feature. And some screens are a more generic error message (vaccines, payments and letters) that straddles a middle ground between 'there's a problem' and 'you probably truly don't have any data', leaning more heavily towards one or the other depending on the feature. 

We also have generic error screens that can pop up in the app when services go down, but maybe those only show up for less fundamental service failures than this one? 

_All screenshots below._

It'd be nice to.... neaten these up a little. Presenting an error message that accurately states what's happening/doesn't lead the veteran to attempt to do something they don't need to do (like calling a help line to get access to messaging when it's actually a "try again later" type of issue)

## Screen shot(s) and additional information

Type 1 "internet broken"
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/99dcc7a1-737a-4288-88ec-8e3f934148d1)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/54cb1cfa-ba65-42ef-a8f9-fe19bb69ee33)

Type 2 "you don't have access"
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/98d9b539-b29c-4488-b141-469cd77ae528)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/351977e1-413c-4c6e-81c0-0d1e3b2b688e)

Type 3 "idk, but something is wrong... maybe"
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/9ed260c7-b1cb-4c86-8709-2e53b4efb1fe)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/1f689578-8248-4cba-b602-9763f8e5b890)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/99f63a25-f7df-4ed0-a960-aedbdcf0c321)

Type 4 "generic error for other? smaller? service"
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/1aa99336-ea16-4671-839d-42ee78f3a719)

**Comment by TKDickson** [comment]
With the v2/user transition (back in October 2023), a lot of the screenshots/situations described in this ticket are no longer happening. IDK @mistymg if you want to keep this open as part of a broader "error handling content could be better" initiative, but FYI either way.

**Comment by mistymg** [comment]
Nice! Good to know that the v2/user transition helped with some of these errors. Let's close this but I can link it in a comment in the [Error Documentation and Improvements epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6751) because I think that's where the real work will happen.
