### ISSUE TITLE
Rx: Update styling on sort/ filter buttons 

### ISSUE THREAD

**Issue by b-rocha** [department-of-veterans-affairs/va-mobile-app#3876]
## Description
Now that the chip styling has been updated, the status label chip looks a lot like the sort/ filter buttons. This ticket is meant to update the styling on the sort/ filter so that there is more visual distinction between the status label and the sort/ filter buttons

#### Screenshot
![Screen Shot 2022-09-28 at 5.32.45 PM.png](https://images.zenhubusercontent.com/5f525ae2ab6cf147e86d2047/3e0d0477-71ed-4f5d-aa93-414e1ec46a34)

**Comment by Sparowhawk** [comment]
this one is no longer relevant
