### ISSUE TITLE
CU - Retire halfPanelCardStyleInterpolator function in common utils

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#3959]
## Proposed Change

Depending on the findings in ticket [3793](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/3793) we should retire or start using halfPanels in their intended location.

## Why Should We Prioritize?

Continued code accuracy and not leaving orphaned code.

## Coding Time Estimation

1

**Comment by timwright12** [comment]
updated the issue link to use github instead of zenhub so it doesn't disappear again

@dumathane could this be a good first issue?

**Comment by TKDickson** [comment]
Built, logged in (judy on iOS, +226 on Android), and opened VCL. No further testing required.
