### ISSUE TITLE
Nav - Apply design style changes webview

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#3970]

**Comment by timwright12** [comment]
@htcollier can this be closed or do we need to fill out the description and push it forward?

**Comment by htcollier** [comment]
This ticket is about updating the webview screen styling as a part of the IA/Nav project, which was done as a UX task in [6139](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6139) and a FE task in [3969](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/3969). Closing as duplicate.
