### ISSUE TITLE
Claims Detail: Provide the webview for Find a VA location. 

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4050]
## Description 
As a Veteran, I want to have a clear and consistent way of finding a VA location from within the app, so that I do not get confused about where I am in the app.

Claims Detail: Provide the webview for Find a VA location.
Current pattern causes users to leave the app. Potentially match to Find a VA location evergreen link behavior on the startup screen, though we need a better understanding of why this link currently goes to a different place than the Facility Finder.

- 

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by Sparowhawk** [comment]
@ala-yna Also fairly simple to change this to just a native webview as opposed to leaving the app.
