### ISSUE TITLE
Spike - Transparent Page Tap Dismiss Option

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4061]
## Description 
As a Veteran, I want to easily close panel screens based on what is common on my device while keeping an idea of where I am in the app, so that I can easily navigate the app.

As part of this story we want to look into closing a panel by clicking on the transparent page above (behind?) the launched panel.

## Acceptance Criteria
  

-  [ ] Determine if we can easily implement a 'tap above to dismiss' type feature for large panels and what such code would include.

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by Sparowhawk** [comment]
@kellylein is this something still desired or can this ticket be closed?

**Comment by kellylein** [comment]
> @kellylein is this something still desired or can this ticket be closed?

We can probably close this, though @ajsarkar28 can have the final say.
