### ISSUE TITLE
Rx: Add a disclaimer in "Profile" that changing the address there won’t affect the Rx address

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va-mobile-app#4090]
## Description
Rx addresses are stored on the pharmacy/ facility systems (VISTA) and require a pharmacist or hospital admin to view/update the address. Currently, this information cannot be ingested by the MHV API. From the 9/2/22 Rx synthesis working session, the team discussed a couple of ideas on how we can handle this:
1. Disclaimer on the profile page that changing the address there won’t affect the Rx address
2. Revisit the operational constraints for not providing addresses with the Pharmacy team and in documentation (covered in #4093)

## Acceptance Criteria
- [ ] Content and designs for a disclaimer in "Profile" that explains that changing the address won't affect the address prescriptions are mailed to

**Comment by Sparowhawk** [comment]
@ala-yna this probably isn't necessary, but wanted to get thoughts as this should be fairly simple to do. If it isn't we can go ahead and close this ticket.

**Comment by mistymg** [comment]
After confirming with some team members, closing this ticket as it's almost 2 years old.
