### ISSUE TITLE
Rx: Investigate creating Rx alerts

### ISSUE THREAD

**Issue by esther-k** [department-of-veterans-affairs/va-mobile-app#4095]
## Description
Rx research from [6/2022 ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/rx-refill/usability-testing/june-2022/research-findings.md#tracking)and [8/2022](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/rx-refill/usability-testing/august-2022/research-findings.md#detailed-findings) revealed that participants desired certain Rx alerts in order to stay on top of their prescriptions. 

The alerts mentioned were: 
- A refill alert to notify when a prescription is eligible to be refilled so that users know when to put in a refill request
- A refill alert to notify when there is a problem refilling a prescription so that users can reach out to their provider to resolve the issue
- A shipping alert to notify when a prescription has been shipped and delivered so that users know when to look for their meds (especially for temperature-sensitive meds)

**Comment by Sparowhawk** [comment]
@ala-yna @ajsarkar28 I think this is mostly solved by HSP especially if for prescriptions you also add the details of all the shipped/trackable prescriptions in the RX card
