### ISSUE TITLE
Major Update Dependency Update (1/4)

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#4145]
## Proposed Change

Investigate the code requirements for updating the following major updates to dependencies:

Major Updates
----------------
@expo/react-native-action-sheet
@react-native-community/datetimepicker
@react-native-firebase/analytics
@react-native-firebase/app
@react-native-firebase/crashlytics
@react-native-firebase/perf
@react-native-firebase/remote-config

##Acceptance Criteria

- [ ] Investigate whether the dependency is required, or if we could take steps to remove from our list.
-  [ ] Create a branch off of `feature-xl/Nov-22-Dependency-Updates`
-  [ ] update a few of the dependencies at a time, using `yarn upgrade <package 1> <package 2> <package 3>`
-  [ ] Check each dependency's release notes and make sure there are no breaking changes (Minor updates shouldn't have breaking changes but sometimes there are exceptions)
    -  [ ] If there are any breaking changes that affects our code, create a new ticket documenting this and move on.
-  [ ] After updating, perform smoke tests to ensure that the app is still working as expected

**Comment by bischoffa** [comment]
@Sparowhawk please see [Slack comment](https://adhoc.slack.com/archives/CU2Q76NPR/p1691149532722459?thread_ts=1691071649.573239&cid=CU2Q76NPR) first. 

![image.png](https://images.zenhubusercontent.com/63a07de791d550125d4fcca3/a13f797c-859f-48e9-9a54-1bd9bbc48560)

**Comment by bischoffa** [comment]
Conversation around including this ticket in Sprint 77 given blocked [conversation in Slack](https://adhoc.slack.com/archives/CU2Q76NPR/p1691071649573239).

**Comment by bischoffa** [comment]
Ticket will remain blocked until this work is prioritized. Only until its prioritized will it be removed from Icebox thus not needed to include in the biweekly icebox ask because there are no updates.

**Comment by bischoffa** [comment]
Q4 planning discussions did not include this or similar work, so suspecting it will remain in the backlog. Also reminder this ticket is blocking other work.

**Comment by Sparowhawk** [comment]
This was all addressed when I last did dependency updates earlier this year
