### ISSUE TITLE
BUG - sev-3 - Firebase Analytics - Analytics definitions are out of date/missing several big features

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4160]
## What happened?

We've been adding event-based analytics for new features (sometimes/when we remember), but our 'audience' and 'dimension' definitions are very behind/incomplete.

For example, here's the "Accessed Major Feature Users" audience definition:
The set of users who have accessed major app features like appointments, letters, profile edits, etc
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/84c7cfb0-1cdb-4eb3-94a7-a59101a28224)

So according to our current definition, the only major features in the app are letters, appointments, profile edit, and the veterans crisis line. 

Aka we are missing: claims & appeals, messaging, payments, and (soon) prescriptions. (If not also others I'm not thinking of right now, which is easy to do because our dimensions are also not up-to-date)

## Acceptance Criteria

Realistically, there are 3 parts to fixing this:
1. An audit of our existing definitions to figure out what all is missing
2. A FE ticket to add all of the missing stuff
3. Closing the process loop that's causing this --> off of the top of my head, documentation that's like "we have three categories of analytics we care about (events, dimensions, audiences), here's why, here's the analytics you get for free, and here's what you need to consider adding for a new feature", and linking that to the feature Step documents somehow (seems like analytics is a ticket that should be created before the end of step 2)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

- 3 - High (updated to reflect label)

We're missing analytics, and we don't even know what analytics we're missing. Not good.

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Linked to an Epic (General Tech/Design Debt & Maintenance)

**Comment by bischoffa** [comment]
Closing this ticket as Sprint 0 has spun off and till determine next steps.
