### ISSUE TITLE
CU - Upgrade @testing-library/react-native to version 11

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-app#4163]
## Proposed Change

We are currently on version 9 (9.1.0 specifically) of the @testing-library/react-native package and during our dependency updates it was recognized this is a couple major versions behind. This issue is to update to version 11 while [tending to any breaking changes needed to do so](https://callstack.github.io/react-native-testing-library/docs/migration-v11).

## Why Should We Prioritize?

As part of dependency updates, it's good to keep on top of newer versions since it can become exponentially more difficult to let dependencies fall too far behind and having more breaking changes to have the latest and greatest.

## Coding Time Estimation

Did not dive deeply, but the breaking changes list doesn't look that complicated. Perhaps a 5 would be appropriate.

**Comment by TKDickson** [comment]
Reassigning to Tom and Narin, based on the fact this is attached to an existing PR of Narin's. IDK if it will actually require any testing (I was auto-assigned based on tags) so you two should chat about it :)

**Comment by TimRoe** [comment]
Closing this ticket as it was already updated at some point. The package.json in develop branch says:
> "@testing-library/react-native": "^12.4.5"
