### ISSUE TITLE
Investigate new Push Notification library options

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#4185]
# Description
In fixing bug #3655 we discovered that tapping on a push notification forces a reload of the app, even if it is in the foreground, thus asking the use to re-authenticate.  

The push notification library we are using has no way to control or detect the relaunching of the app, and we've had to create a workaround to bypass biometrics if tapping a notification with the app in the foreground ([PR #4309](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/4039)). 

We want to determine if there are other options for push notifications that might allow us to have better control of app launches triggered by push notifications.

# Acceptance Criteria
- [ ] Investigate library options
- [ ] Create a write-up of pros/cons and make a recommendation

**Comment by timwright12** [comment]
@theodur @narin do we know if the issue outlined in the description here is still a problem? If not let's close it out. If it is, let's add the "global" label

**Comment by theodur** [comment]
From my recent testing with deep linking, I haven't noticed this issue, but I'll confirm on iOS and Android and report back

**Comment by theodur** [comment]
I just tried on both iOS and Android, and I'm not able to produce. This was probably fixed in a more recent version of `react-native-notifications`. Closing this one out
