### ISSUE TITLE
Remote Config - Retire Feature Flags

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4213]
## Description 
As a VA Mobile Dev, I want to have only one way to turn features on and off in the app, so that there is only one thing to maintain.

As part of this story we want to: remove the old Feature Flag functionality now that Remote Config is in and working.

- 

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by timwright12** [comment]
Closing because of age
