### ISSUE TITLE
[Spike] Investigate RN Hermes performance gains

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#4261]
## Description 
React Native version 0.70.0 enabled Hermes as on by default moving forward. 

~~A complication of this for our particular configuration with this is that the hermes-engine Pod for iOS contains two problematically large binary files (461MB and 924MB) that are too large for GitHub's 100MB size limit. As such, they can not be added to our repo which would complicate our development pipeline by needing to reconfigure CircleCI build processes around those files needing to be cached. As [documented here](https://github.com/facebook/react-native/issues/34643#issuecomment-1248096354), this appears unlikely to change in the future from the RN side.~~

The above is no longer relevant since we've added pods to `.gitignore`.

This issue is to research Hermes' effectiveness towards [the improvements proclaimed by the RN documentation: "For many apps, using Hermes will result in improved start-up time, decreased memory usage, and smaller app size when compared to JavaScriptCore."](https://reactnative.dev/docs/hermes) Once evaluated, discuss with FE engineers to determine whether the benefits of Hermes are worth the drawbacks for our general development pipeline/processes.

To enable Hermes, flip the `hermes_enabled` flag in `ios/Podfile` and `enableHermes` in `android/app/build.gradle` to true and perform [standard project setup steps to overwrite outdated modules](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupInstructions/DevSetupProcess/#with-vscode-or-intellij-idea-project-setup) (`yarn install`, `pod install`, bundle).

## Acceptance Criteria
  

On both Android and iOS:
-  [ ] Evaluate Hermes' improvement on start-up time
-  [ ] Evaluate Hermes' improvements on reduced memory use
-  [ ] Evaluate reduction in built app size

**Accessibility Requirements**
None, under the hood.

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
      - Should likely wait until the [November 2022 dependency updates](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4136) are merged into develop or done alongside those
    - Test accounts needed?
      - No.
- Does this require QA?
  - Not for the spike.
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by timwright12** [comment]
@dumathane is this still worth looking into?

**Comment by narin** [comment]
Updated the description to remove the first part about the file size complications since we no longer commit the pods file to the repo. The rest might still be relevant if we haven't enabled hermes though.

**Comment by dumathane** [comment]
I think we could probably close this one. We aren't hitting lags on startup time that we aren't creating with our own api calls and just don't see this one being prioritized highly.
