### ISSUE TITLE
Replace uses of touchable family of components with the Pressable component

### ISSUE THREAD

**Issue by jmarchi** [department-of-veterans-affairs/va-mobile-app#4280]
## Proposed Change
The touchable components (TouchableWithFeedback, TouchableOpacity, etc) are not recommended for use anymore but are still functional. The Pressable component supports a wider range of interactions and more closely matches the look and feel of the native OS. 

https://reactnative.dev/blog/2020/07/06/version-0.63#pressable

**Comment by timwright12** [comment]
@dumathane should we close this out? It's pretty old

**Comment by dumathane** [comment]
This one might be an easy good....fourth or fifth issue.

**Comment by timwright12** [comment]
Closing out as too old
