### ISSUE TITLE
Remove testIdProps and other obsolete utils

### ISSUE THREAD

**Issue by jmarchi** [department-of-veterans-affairs/va-mobile-app#4293]
## Proposed Change
Remove accessibility utils made for integration tests and check for where accessibility labels that were being applied by the util are necessary. 

There are places that accessibility labels are passed into components as "testID", remove that prop from all components and where a label is needed and extend AccessibilityProps instead.

**Comment by timwright12** [comment]
Closing this out because Detox brought back testID
