### ISSUE TITLE
Streamline theme and align with design

### ISSUE THREAD

**Issue by jmarchi** [department-of-veterans-affairs/va-mobile-app#4294]
## Proposed Change
Align color scheme and palette with design, reorganize theme file to be consistent and streamline parts that have been tacked on over the years.

Ideally, design would be aware of the theme and tickets could include these values as theme elements rather than hex codes. This would make things more consistent and give design a chance to say "we will be using this color as <something> going forward" when introducing a new theme variable rather than the engineers guessing how the new color fits into the theme and whether it should be tied to a specific feature or not.

**Comment by timwright12** [comment]
closing as this work is happening elsewhere
