### ISSUE TITLE
Removed indexed checks on elements from unit tests

### ISSUE THREAD

**Issue by jmarchi** [department-of-veterans-affairs/va-mobile-app#4300]
## Proposed Change
Some unit tests verify an element's content by gathering the complete list of instances of the type of component it is attempting to check and indexing into where it thinks it will be. This is hard to maintain as any update of the screen will shift the indexes, and it is hard to know whether we are checking the correct element whether the test passes or not. This can be done several ways, either by introducing some of the findBy utils we currently have or by introducing a testId system that can be used specifically for tests.

**Comment by Sparowhawk** [comment]
closed due to the unit tests being updated by Chris' tickets
