### ISSUE TITLE
BUG - sev-3 - All - SIS + DS Logon users will do MFA twice during login

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4341]
## What happened?

I turned on SIS and logged in as arfan (our DS Logon user), and I had to do MFA twice - once in the DS Logon flow, and then again after being redirected back to a more VA-looking flow. (With SIS off, I only do MFA once, in the DS flow)

Narin followed up with our SIS contacts, and it turns out this is a known integration problem:

> Hi Narin, this is, unfortunately, expected behavior at the moment. And this occurs with ALL va.gov web users (both Sign in Service and SSOe) currently as well. This is an unfortunate side effect of utilizing the DSLogon-through-ID.me credential. We are currently working with ID.me and DSLogon to see if either can provide a solution, but it’s unfortunately an issue with their integration with each other
> 
> Here’s what is happening:
> - We historically have integrated with DSLogon and MHV through ID.me because ID.me was able to provide 2FA, so this was able to make these authentications more secure on [VA.gov](http://va.gov/)
> - DSLogon recently introduced 2FA capabilities, so now any authentication with DSLogon, even directly, will utilize 2FA
> - So now DSLogon itself, and ID.me, both want the user to provide 2FA, thus the double MFA
> - Mobile didn’t necessarily experience this behavior before, because the IAM integration actually doesn’t go through ID.me, it goes straight to DSLogon

## Desired behavior

Only do MFA once during login

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

3 - Medium

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Linked to an Epic (General Tech/Design Debt & Maintenance)

**Comment by bischoffa** [comment]
no ux dependency

**Comment by bischoffa** [comment]
No updates on this, still blocked by external teams.

**Comment by bischoffa** [comment]
No update still blocked

**Comment by TKDickson** [comment]
Closing this bug ticket. It's still an issue, but after a conversation with stakeholders we determined we will not be using open bug tickets on our board to track external team problems that impact the mobile app.
