### ISSUE TITLE
Gender Identity - Analytics

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#4525]
## Description 
As a [type of user/persona], I want to [goal/objective], so that [benefit/desired result/some reason].

As part of this story we want to:   

- 

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by Sparowhawk** [comment]
@OVezeamama What kind of analytics would you like for gender identity? They would be fairly simple to add as long as they are defined.

**Comment by ala-yna** [comment]
Closing this out - no detail provided.
