### ISSUE TITLE
Update Demo Mode to reflect changes for Personal Info & Contact Info breakout changes

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#4544]
## Description 
As a Product Manager, I want to be able to view the latest changes made to the app in demo mode.   As part of this ticket we want to:

- Update Demo mode with the latest view of Profile and Profile Info & Contact Info screens

## Acceptance Criteria
  

-  [ ] Update Demo mode to reflect the changes made in tickets
            - #4506 
            - #4520 
            - #4522 

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by TKDickson** [comment]
This is done - personal and contact info are on separate screens in demo mode, with all of the features (etc) from those tickets. Closing as completed.

(Found this while doing cleanup of tickets assigned to me, in case anyone wonders about why I'm in here)
