### ISSUE TITLE
Component: Radio Group

### ISSUE THREAD

**Issue by kidlaurenpeace** [department-of-veterans-affairs/va-mobile-app#4592]
# Common Component Ticket

### Purpose

The radio group component is a form element used to make one selection from a list of options

### Image or Figma embed

[Figma Embed](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/VAMobile-DesignLibrary1.0-%F0%9F%93%90?node-id=803%3A3321&t=u975X2tKrHyqYqdk-4)

### Usage

The variants for the Radio Group component are: 
- Inactive: default state when user has not selected anything 
- Active: user has selected anywhere in the row
- Error: triggered when a selection is invalid upon interaction
- Disabled: an item in the list that is visible but unable to choose

Use the radio group in cases where choosing an option is considered the primary action on the screen, ideally beneath a header. Radio Groups allow users to only make one choice in the form. 

Enable secondary helper text as needed. For instance, when the meaning is too unclear to stand alone or the user needs more details before making a choice. 

Ensure the user can deselect the component in favor of another item in the form. If a user is required to make a choice, then the defined error state would ensue. 

### Example in practice

Used to select options in Schedule Appointments form, Preferred Name and Gender Identity, and the Sort picker in Prescriptions.
![image](https://user-images.githubusercontent.com/53520623/213578209-86a5b7ac-a5bf-4566-9f6c-7b4901d7618c.png)

***need to come back to add the darkmode instance***

### Best Practices

Use the Radio Group:
- In forms with a label, or to display responses to a question
- Independent of the Radio Button style in the same context (i.e. not within the same form)

### Content Guideline

Radio options should:
- Have a heading
- Use a few words to describe the selection 
- Use a secondary helper text string when more context is needed
- Start with a capital letter

### Accessibility

Accessibility labels:
- Label: Read as indicated
- Role: Radio button
- Hint:(none)
- Status: Selected, Unselected
- Value: Selection [n] of [n]

Highlight the entire row when tapped, to indicate an Active Radio Group. Allow tapping anywhere on the row to switch the row as `Active`. Allow selecting another row to deselect the initial selection. Enable errors in cases when a selection is required. (Example: User selects `Continue` when selecting an option is required to fill out a form.)

### Related Components/Resources

- [Radio Button (Inline text style)] (https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%9A-VA-Mobile-Design-Library?node-id=932%3A3474&t=3Vt2NpJ8V3cttTRF-4)

- [Radio Button - VA.gov Design System](https://design.va.gov/components/form/radio-button)
- [USWDS - Radio buttons](https://designsystem.digital.gov/components/radio-buttons/)
- [Radio buttons - Material Design](https://material.io/components/radio-buttons)
- [Toggles - Selection and input - Components - Human Interface Guidelines - Design - Apple Developer](https://developer.apple.com/design/human-interface-guidelines/components/selection-and-input/toggles/)

#### After filling out the ticket
- [ ] Tag Jen Ecker, Jon Bindbeutel, and Therese Dickson in a comment on this ticket, and one of them will be in touch to add you to an upcoming committee meeting to review.

#### After component committee review is finished
- [ ] PR submitted to add the component to the Front End > Components section of the documentation site
- [ ] UX, QA, and FE reps on the component committee have socialized the new component with their respective teams
- [ ] Moved ticket to the 'Ready to hand off to Eng' column on the VA-Mobile-UX board

**Comment by jessicawoodin** [comment]
Will be addressed with DS ticket #6788
