### ISSUE TITLE
Common Component Ticket: Pagination control

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#4600]
### Purpose
Pagination control is a component that splits information from a list over multiple screens instead of showing it all on a single screen. Pagination allows users to move from screen to screen of the paginated set.

### Image or Figma embed
<img width="468" alt="image" src="https://user-images.githubusercontent.com/45246038/214110825-9f593762-0885-4040-88fb-b5a6added5c4.png">
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FQVLPB3eOunmKrgQOuOt0SU%2F%25F0%259F%2593%2590-DesignLibrary1.0---VAMobile%3Fnode-id%3D2650%253A4446%26t%3DReWgsJYfVetmpTkV-1" allowfullscreen></iframe>

### Description
Paginated content is any content split into multiple screens determined only by a specific amount of content per screen, not split by any meaningful attribute, like feature or subject or step. In the VA Mobile app, we use pagination (as opposed to infinite scrolling) when the amount of content exceeds a specific threshold. This pattern choice is for both accessibility (it works better with assistive technology and cognitive load) and performance reasons.

The pagination control appears below each batch of 10 records, at the bottom of the screen. It scrolls with the page content and is not locked to the bottom of the screen. 

It contains two arrow controls at right and left for navigation back and forward between batches of records (the back arrow is disabled on the first page of records, the forward arrow is disabled on the last page of records). The total number of records in the list is always displayed along with a number range (X to X) indicating which group of 10 records is currently being displayed.

### Usage
Use pagination when:
- The number of rows or records in a list exceeds 10.
- Showing all the content on a single screen makes the screen take too long to load (not yet in the app)
- Most users will only need the content on the first screen or first few screens (not yet in the app)

### Example in practice
<img width="627" alt="image" src="https://user-images.githubusercontent.com/45246038/214111798-e990f690-6f32-4ded-8662-ba5e73196018.png">

### Best Practices
When not to use pagination:
- If your content has meaningful groupings or categories.
- For steps in a sequence.
- For short collections.

### Content Guideline
N/A

### Accessibility
[Pagination control - Native app accessibility checklist - MagentaA11y](https://www.magentaa11y.com/checklist-native/pagination-control/)

**Left Arrow:**
a11yLabel: 'previous-page' <--Not a .json variable.
a11yHint: pagination.previous: 'Previous page'
a11yRole: Link
a11yState(disabled): disabled true/false.

**Right Arrow:**
a11yLabel: 'next-page' <--Not a .json variable.
a11yHint: pagination.next: 'Next page'
a11yRole: Link
a11yState(enabled): {}

**Text count:**
"pagination.info": "{{beginIdx}} to {{endIdx}} of {{totalEntries}}",

**Readout on iOS:**
'previous page, dimmed, link, previous page'
'next page, link, next page'
'1 to 10 of 12'

**Readout on Android(Pixel 3):**
'previous page, previous page, link, disabled'
'1 to 10 of 12'
'next page, next page, link, double tap to activate'

### Related Components/Resources
- [Pagination - VA.gov Design System](https://design.va.gov/components/pagination) 
- [Pagination - U.S. Web Design System (USWDS)](https://designsystem.digital.gov/components/pagination/)
- [Pagination Best Practices for Google | Google Search Central | Documentation](https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading#selecting-the-best-ux-pattern-for-your-site)
- [NNG: Infinite Scrolling: When to Use It, When to Avoid It](https://www.nngroup.com/articles/infinite-scrolling-tips/)

#### After filling out the ticket
- [x] Tag Jen Ecker, Jon Bindbeutel, and Therese Dickson in a comment on this ticket, and one of them will be in touch to add you to an upcoming committee meeting to review.

#### After component committee review is finished
- [ ] PR submitted to add the component to the Front End > Components section of the documentation site
- [ ] UX, QA, and FE reps on the component committee have socialized the new component with their respective teams
- [ ] Moved ticket to the 'Ready to hand off to Eng' column on the VA-Mobile-UX board

**Comment by jessicawoodin** [comment]
Will be addressed with DS ticket #6788
