### ISSUE TITLE
RX Refill - Sorting - Prioritize Active Status 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#4615]
## Description 
As a Veteran in the VA Health and Benefits app, I want to first see active prescription listed first, so that I know which  prescriptions I can take action on. 

As part of this story we want to:   
- When Veteran has the same medication name listed multiple times then filter should show Active statuses first 

## Acceptance Criteria
  
-  [ ] AC 1
GIVEN Veterans in the VA health and Benefits App in the prescription section
WHEN list is filtered by medication name 
THEN  show medication name prescriptions 
AND first show active statuses 

**Accessibility Requirements**
 - [ ] Setting should be read by the screen reader - this case the alert and also copy in the UI
 - [ ]  If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the
component type needs to be announced by the screenreader. (Include name (title), role, value)
 - [ ] Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap,
or horizontal scroll.
 - [ ]  Each touch target must be at minimum 44px by 44px
 - [ ]  All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to navigate a page, its focus element should be clear.
 - [ ]  The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g. scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.

## Notes & Open Questions

- Came up in UAT on 1/24 when Veteran (Keith) went into Prescriptions and he has prescriptions with the same name (1 per month / refill) and the list defaults to showing Expired status then Active status. It was defaulted to Sort by medication name which it did but feel there is a need to prioritize Active statuses first. This would make the user scrolling through for this scenario easier.  

- Dependencies/Roadblocks:
    - Any internal/external dependencies? No
    - Test accounts needed? Yes 
    - Does this require QA? Yes
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by MekoHong** [comment]
duplicate ticket closing
