### ISSUE TITLE
Spike - Automate moving tickets to the "with QA (develop)" column on the FE board when merging PRs

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4657]
## Description 
As a FE Engineer, I want to merge my PR and then not have to remember to do anything else, so that QA will get notified that tickets are ready for them to start working no matter if I remember ZenHub workflows or not. 

As part of this story we want to:   

- Investigate if it's possible to automate moving tickets from [whatever FE board column they are in] to the "with QA" column on the FE board, at the point when an Eng merges a PR into `develop` or an XL branch

- If it's small, get that work done real fast during this investigation
- If it's not small, write up a new ticket saying "this is how it will be done" and drop that into the backlog
- If it's impossible, loop back to let Binny, Narin, Therese and Tom know & close this ticket.

Notes from Dylan(create spin off tickets to automate moving ticket to ready to merge and with QA on pull request approvals)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
please add a sprint to this

**Comment by TKDickson** [comment]
@Sparowhawk or @dumathane ^

**Comment by Sparowhawk** [comment]
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

**Comment by Sparowhawk** [comment]
name: Assigned Issues Are In Progress

on:
  issue:
    types: [assigned]

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    name: Move to In Progress Column
    steps:
      - name: Checkout
        uses: actions/checkout@v2
	  - name: Move to In Progress
	    uses: kin/gh-action-move-issue-to-column@1.0
		with:
		  access-token: "#{{ secrets.GITHUB_TOKEN }}"
		  project-name: "My Project"
		  target-column: "In Progress"

**Comment by Sparowhawk** [comment]
for potentially the other workflow/spin off tickets

on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"

**Comment by Sparowhawk** [comment]
https://github.com/actions/labeler

**Comment by Sparowhawk** [comment]
https://github.com/actions-ecosystem/action-add-labels

**Comment by Sparowhawk** [comment]
name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["triage"]
            })

**Comment by Sparowhawk** [comment]
so the workflows that can be created is

2 approvals to automate the label to be updated from FE-review requested to FE-with qa

when FE-With QA is applied to move the ticket to with QA column

3 approvals(QA being the 3rd) to automate either adding a label to ready to merge or to move the ticket to ready to merge or both.

on merge to move ticket to with qa develop column(still need to see if there is a way to automate tagging the release on the issue)

**Comment by Sparowhawk** [comment]
${{ github.event.release.tag_name }}.

**Comment by Sparowhawk** [comment]
I have created the 4 workflows that can be created from the research in this ticket. Will work on those when I have time.

**Comment by bischoffa** [comment]
@Sparowhawk can you add those 4 tickets to the comments on this ticket?
