### ISSUE TITLE
Spike - automate moving tickets on the QA board when daily/XL builds are built

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4658]
## Description 
As a QA Engineer, I want ZenHub columns to reflect our builds without manual intervention, because that would free up time I spend managing the board to go to other tasks (testing, process improvement, etc). 

As part of this story we want to:   

- Investigate if it's possible to automate moving tickets from the "Awaiting QA build" column on the QA board, to...
 >> the QA (develop) column for code that's in develop
>> the QA (XL branch) column for code that's in an XL branch 
... and have those tickets move only when a new build is created for that branch (daily/overnight for develop, and more erratically for XL)

- If it's small, get that work done real fast during this investigation
- If it's not small, write up new ticket(s) saying "this is how it will be done" and drop that into the backlog
- If it's impossible, loop back to let Binny, Narin, Therese and Tom know & close this ticket.

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by Sparowhawk** [comment]
QA now does their own builds and we have the same board and use labels when things are ready to be moved. This ticket is no longer needed
