### ISSUE TITLE
Update endpoint to retrieve Direct Deposit Payment info from Lighthouse source

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4744]
There is a new Lighthouse API that we need to use instead of EVSS to pull Direct Deposit payment info.  The VA.gov Auth Experience - Profile team is building an integration to the new LH Direct Deposit Mgmt API so we should utilize their integration.  

Endpoints:
GET/PUT /v0/payment-information/benefits

AC:

- [ ] Update our endpoint(s) to pull Direct Deposit info from the new VA.gov integration to LH
- [ ] Ensure all data is returned to the app in the same format

**Comment by DJUltraTom** [comment]
new error found: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6435

**Comment by DJUltraTom** [comment]
I have been able to complete the happy path test cases and filed the above bug for the unhappy path issue I found, think we are good closing this ticket:

https://dsvavsp.testrail.io/index.php?/runs/view/4683&group_by=cases:section_id&group_order=asc
