### ISSUE TITLE
Remove Feature Flag once stable in Prod

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4750]
Once the Encouraged Update feature has been turned on in Production, we should remove the Feature Flag is possible.  This Feature should only ever show for v1.40 and above, so that may keep us from removing the Feature Flag check.

AC:
 - [ ] Remove extra code to check Feature Flag 
 - [ ] Remove Feature Flag in setting for EU

**Comment by bischoffa** [comment]
@kellylein @ajsarkar28 is this ticket sill needed?

**Comment by bischoffa** [comment]
its in a closed epic so didnt want it to get lost

**Comment by timwright12** [comment]
@ajsarkar28 @dumathane What's up with this ticket? Did we retire the flag?
