### ISSUE TITLE
BUG - sev-2 - All - Appointments: need graceful response for 502 errors

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4762]
## What happened?

This morning, I'm getting 502 errors back from the backend when attempting to load the appointments activity (Health > Appointments), see the content of the 502 errors in the 'steps to reproduce' section.

I'm never seeing an error screen in appointments, however. Instead, despite the fact that the BE error appears within a second or two of trying to load appointments, the user is stuck on an unresponsive loading screen for appointments for a good long while (I stopped tracking it when we passed the 1 minute mark). On some of my devices that seems to eventually be 'crashing' out back to the Health landing page, and on some devices I've needed to force-close the app to be able to take any actions.

## Specs:

- Device: Pixel, OnePlus, iPad mini
- OS:
- User Account: judy, grethel
- Accessibility State:

## Steps to Reproduce

The call that's failing is the initial appointment GET/loading call: **GET /mobile/v0/appointments?startDate=2022-11-10T00%3A00%3A00.000-08%3A00&endDate=2023-02-09T23%3A59%3A59.999-08%3A00&page%5Bsize%5D=10&page%5Bnumber%5D=1&sort=-startDateUtc&included%5B%5D=pending**

`{
	"errors": [{
		"title": "Bad Gateway",
		"detail": "Received an an invalid response from the upstream server",
		"code": "VAOS_502",
		"source": {
			"vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/var/VeteranAppointmentRequestService/v4/rest/appointment-service/patient/ICN/1013120820V528557/appointments?endDate=02%2F10%2F2023&startDate=11%2F12%2F2022",
			"vamfBody": "<!DOCTYPE html>\n<html>\n<head>\n<meta content=\"text/html;charset=utf-8\" http-equiv=\"Content-Type\">\n<meta content=\"utf-8\" http-equiv=\"encoding\">\n<title>Error</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>An error occurred.</h1>\n<p>Sorry, the page you are looking for is currently unavailable.<br/>\nPlease try again later.</p>\n<p>If you are the system administrator of this resource then you should check\nthe <a href=\"http://nginx.org/r/error_log\">error log</a> for details.</p>\n<p>We have articles on troubleshooting issues like <a href=\"https://blog.openresty.com/en/lua-cpu-flame-graph/?src=wb\">high CPU usage</a> and\n<a href=\"https://blog.openresty.com/en/how-or-alloc-mem/\">large memory usage</a> on <a href=\"https://blog.openresty.com/\">our official blog site</a>.\n<p><em>Faithfully yours, <a href=\"https://openresty.org/\">OpenResty</a>.</em></p>\n</body>\n</html>\n",
			"vamfStatus": 502
		},
		"status": "502"
	}]
}`

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Issue Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-tracking) for details on Severity Levels

- 2 - High

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Estimate of 1 added

**Comment by TKDickson** [comment]
I am re-opening this bug ticket because I am getting the same "502 error is sent to app, of the exact type Chris had fixed previously, and the front end takes ~30 seconds to resolve to an error screen" (or, in my case, not show a snackbar) as before. Moving back to backlog - ready to work.

```
HTTP/1.1 502 Bad Gateway
Date: Thu, 23 May 2024 16:46:45 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 646
Referrer-Policy: strict-origin-when-cross-origin
Vary: Accept, Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Frame-Options: SAMEORIGIN
X-Git-Sha: 10dab8baa120443b048fed271b65aaf443ba58f8
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 7d32315c-af48-4de2-bbfe-49a84d86ff16
X-Runtime: 1.064389
X-Xss-Protection: 0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Connection: keep-alive
```

`{"errors":[{"title":"Bad Gateway","detail":"Received an an invalid response from the upstream server","code":"VAOS_502","source":{"vamfUrl":"https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vpg/v1/patients/434fce82be04d498f7e7e54f30c0d4c35f61bc4e53610137bcb446723597732a/appointments/7493d2615176fb78c69dfbd12330e7dbf31ee115ca4661e9cd484a7092db59da","vamfBody":"{\"code\":500,\"status\":500,\"message\":\"An error occurred (ID: d75e7e6f-a264-4362-84d6-d43d07b9a91c)\",\"id\":\"d75e7e6f-a264-4362-84d6-d43d07b9a91c\",\"traceId\":\"c17cb6b8902da4cd1c22f40ad80184e6\"}","vamfStatus":500},"status":"502"}]}`

**Comment by Sparowhawk** [comment]
Did a little digging and it isn't related to RQ as mutations don't have retries by default

**Comment by Sparowhawk** [comment]
Likely is a similar issue to what @alexandec addressed or tried to address in his original pr

**Comment by bischoffa** [comment]
@ala-yna FYI Sev-2 ticket that was reopened last sprint.

**Comment by bischoffa** [comment]
@ala-yna is this something H&B can look at next sprint? Its been reopened since late May.

**Comment by bischoffa** [comment]
@ala-yna is this something H&B can look at next sprint? Its been reopened since late May and Sev 2 should be worked on within a sprint of discovering.

**Comment by ala-yna** [comment]
Pulling this in to Pending Handoff, to be discussed at the next refinement.

**Comment by alexandec** [comment]
@dumathane I believe there was a similar case where we ended up asking the BE to simplify their error response. Should we consider that here?

**Comment by bischoffa** [comment]
@dumathane @alexandec @ala-yna any updates?   
  
CC @StacyB2023 given reference for BE

**Comment by alexandec** [comment]
Blocked by BE work. Moved to the Blocked column pending that work. BE ticket is linked as a blocker.

**Comment by aherzberg** [comment]
BE update has been made to remove source block in error for appointments. should be in prod today ~1pm EST. Let me know if there's still related errors popping up.

**Comment by TKDickson** [comment]
@alexandec @aherzberg great! I will close this ticket, thank you both.
