### ISSUE TITLE
Frontend - maintenance window mismatch between BE and FE

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4843]
## What happened?

The backend and frontend maintenance windows lists don't match.

The backend includes two endpoints not covered by the frontend, and vice versa (bolded in lists below).

[Backend](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/mobile/docs/schemas/MaintenanceWindows.yml):
             enum:
                **- evss
                - caseflow**
                - payment_history
                - facility_locator
                - appeals
                - military_service_history
                - claims
                - direct_deposit_benefits
                - disability_rating
                - letters_and_documents
                - auth_idme
                - secure_messaging
                - appointments
                - user_profile_update
                - rx_refill

[Frontend](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/feature-xl/IA-Nav-Updates/VAMobile/src/store/api/types/Errors.ts):
export type DowntimeFeatureType =
  | 'facility_locator'
  **| 'auth_dslogon'**
  | 'auth_idme'
  **| 'auth_mhv'**
  | 'appeals'
  | 'military_service_history'
  | 'claims'
  | 'direct_deposit_benefits'
  | 'disability_rating'
  | 'letters_and_documents'
  | 'secure_messaging'
  | 'appointments'
  | 'user_profile_update'
  | 'payment_history'
  | 'rx_refill'

## Acceptance Criteria

The backend team is going to look into/confirm what the real endpoints are (ticket #4842) and leave a note in this ticket confirming the source of truth.

Once that happens, the FE team should update their maintenance list (adding/removing endpoints) and ALSO add the maintenance window handling to the screens that would be impacted, if there are services that are added to the FE list

**Comment by jperk51** [comment]
This is a documentation issue. I'll make sure we update that. The possible responses are limited to features. As for the FE entries, the BE definitely won't ever return any auth_XXX windows.

**Comment by TKDickson** [comment]
This ticket ended up being a duplicate of #5008, so good to close
