### ISSUE TITLE
CU - Use constant for CategoryLanding template screens

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#4857]
## Proposed Change
Instead of supplying an options object to CategoryLanding screens, we should create a constant in `constants/screens.ts` and use that. Search for `FULLSCREEN_SUBTASK_OPTIONS` to see a similar constant already in use.

## Why Should We Prioritize?
A constant will prevent code duplication, typos, and other errors by ensuring consistent usage of options across all screens. It will also simplify the addition of new screens.

## Coding Time Estimation
2

**Comment by dumathane** [comment]
Going to call this one not necessary and close it.
