### ISSUE TITLE
CU - Use constant for FeatureLanding template screens

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#4858]
## Proposed Change
Instead of supplying an options object to FeatureLanding screens, we should create a constant in `constants/screens.ts` and use that. Search for `FULLSCREEN_SUBTASK_OPTIONS` to see a similar constant already in use.

## Why Should We Prioritize?
A constant will prevent code duplication, typos, and other errors by ensuring consistent usage of options across all screens. It will also simplify the addition of new screens.

## Coding Time Estimation
2

**Comment by rbontrager** [comment]
Verified that feature landing screens look the same as before on iOS and Android.  Approved by QA.
