### ISSUE TITLE
CU-Investigate Wire Mocks to Improve mocked data for Demo Mode

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#4898]
https://stackoverflow.com/questions/54958756/generate-current-date-in-stubbeds-json-file

**Comment by timwright12** [comment]
@Sparowhawk can you add more context to this ticket?

**Comment by theodur** [comment]
Based on the discovery from https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6798, I don't think this ticket is needed anymore
