### ISSUE TITLE
Add direct deposit mocks to demo mode

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4938]
## Description 
As a stakeholder or builder of the mobile app, I want to have a mocked version of the 'update direct deposit' info page in demo mode, so that I could easily demo or test that page as needed with the demo build.

As part of this story we want to:   

- Add mocked data for direct deposit to demo mode. Most of the id.me users, and also arfan (DS Logon), have direct deposit info in staging that we could grab a response for --- once #4878 is fixed, or manually working around that bug to grab the response info.

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by Sparowhawk** [comment]
this was added somewhere else
