### ISSUE TITLE
Draft new FE On-Call Process

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#4941]
## Description 
As a [type of user/persona], I want to [goal/objective], so that [benefit/desired result/some reason].

As part of this story we want to:   

- 

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by timwright12** [comment]
closing this out as we just broke off into teams and FE wouldn't be on call
