### ISSUE TITLE
Update Heading Spacing: WCAG 2.2

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4972]
**Description:**

As a mobile app user, I would like to ensure that accessibility requirements are met for Paragraph Spacing (Under Text Styling Criteria) to ensure the best experience when using the app.

As part of this story we have done a full review spike and noted the following are NOT in compliance. This ticket is to ensure updates/improvements are in compliance for the following:

**Update HEADINGS**
Recommendations:

"However, our **headings** (because we are using Bitter) could use a bit of work since slab-serif fonts are not as legible, especially when using a bold weight. I would recommend slightly increasing the letter and word spacing for the Bitter Bold Heading style to help with legibility."

**WCAG Text Spacing requirements for reference:** https://www.w3.org/WAI/WCAG21/Understanding/text-spacing

**Acceptance Criteria:**

[AC1] For Headings, view recommendations noted above by UX and make needed updates. Note any bottlenecks

**Comment by TKDickson** [comment]
@brea11y is this particular ticket still needed? Or could it be closed?

**Comment by brea11y** [comment]
I think we can close this one. This is being built into the typography tokens that Design System is working on. Closing it out with my comment.
