### ISSUE TITLE
BUG - sev-3 - iOS - Couple more places to remove white background in landscape for notched devices

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#4977]
## What happened?

Classic iOS visual thing (because they define a safe space for the notches on the screen) -- when rotating to portrait, white bars appear on the left and right of the screen (rather than the all-blue background aesthetic we've got going on in portrait). 

We fixed this in onboarding (#2903), and as I was looking at that one I saw a few other screens where it applies - sign in, sign out, and the initial app launch screen (screenshots of two of those at the bottom).

## Specs:

- Device: iPhone 12 (or any other iOS device with a notch)
- OS: iOS 15.3
- User Account:
- Accessibility State:

## Steps to Reproduce

Uninstall/reinstall app, or use developer screen (in settings in profile) to reset to a first time login.
Rotate device to landscape > observe white bars on prelogin home screen.
Rotate to portrait > all blue background.
Repeat those steps on the "signing in" screen, and the "signing out" screen.

## Desired behavior
Confirmed with Lauren that we'd want:
* All-blue on the sign-in and sign-out loading screens
* Red (for the VCL) and blue (for the rest of the screen) if we can make that happen on the prelogin home screen. If it's a hassle, then all-blue for that one too.

## Screen shot(s) and additional information

![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/9f10cd74-68db-4c71-aacb-db97dbd1e512)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/f4c32fcf-55f4-4967-bff0-a8b0cf96b857)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, feature, bug)
- [ ] Linked to an Epic (General Tech/Design Debt & Maintenance)

**Comment by Sparowhawk** [comment]
pulled into sprint

**Comment by DJUltraTom** [comment]
was able to verify the white space does not appear on the sides using landscape mode on notch devices
QA approves this fix

**Comment by DJUltraTom** [comment]
Verified I no longer see white edges in landscape on the screens mentioned in the description on notched devices.
QA approves this fix

**Comment by DJUltraTom** [comment]
verified this fix is appearing on the nightly QA build as expected, closing ticket!
