### ISSUE TITLE
Update Font Scaling : WCAG 2.2

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#4980]
**## Description** 
As a mobile app user, I would like to ensure that accessibility requirements are met for Text Spacing criteria. This includes an Update to Font Scaling ensure the best experience when using the app.

**Overall Spike ticket for reference:**
Spike for reference:

https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/4687

**Related Tickets:**
1. https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/4930

2. https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/4972
- 

## Acceptance Criteria

-  AC 1:  Ensure that as font scaling is increased within a user's device settings. 
- AC 2: Ensure that the line-height should also increases with the font size.

**Comment by Sparowhawk** [comment]
@brea11y I believe this one can be closed. The font scales when the user changes there screen text size

**Comment by brea11y** [comment]
@Sparowhawk – Awesome! Thank you! Closing with this comment!
