### ISSUE TITLE
CU - Remove unused maintenance window values

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#5008]
## Proposed Change
There are currently at least three maintenance window values in the mobile app that are not being used:
`'auth_dslogon', 'auth_idme',  'auth_mhv'`

Only auth_idme is being sent from the backend. We will remove it from there as well. 

If you find any other maintenance windows that are not being used, let the back end team know and we'll remove that as well. 

## Why Should We Prioritize?
Less code is better code.

## Coding Time Estimation
1 - cup of coffee

**Comment by theodur** [comment]
@liztownd @TKDickson I approved the PR and moved this to `With QA`, but I don't think there's anything that QA needs to test here since it's just removing downtime windows, so we should be good to merge this one
