### ISSUE TITLE
Remove Haptics Analytics Code

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#5018]
## Description 
As Ad Hoc, I want to remove unused code related to Haptics Analytics so we can keep the code clean

As part of this story we want to:   
- Original design of Haptics was going to track Haptics analytics based on the Haptics setting; however we migrated to using the phone settings so we removed the toggle thus the haptics analytics are not capturing anything 
- Ticket is 4518 was the OG ticket for Haptics Metrics and Data 
      - Data to know when a Veteran turns on Haptics setting haptic_setting_user_on
      - Data to know when the Veterans turns off Haptic setting (previously had it on) haptic_setting_user_off

## Acceptance Criteria
  

-  [ ] AC 1
GIVEN there is Haptics V1 feature 
WHEN there is code related to haptics metrics and data
THEN remove it from Ad Hoc's code 

**Accessibility Requirements**
- NA 

## Notes & Open Questions
 - Discussed during standup 3/7 to make a separate ticket for this; Dylan confirmed also that 4518 is not being done as we switched to using device settings 

- Dependencies/Roadblocks:
    - Any internal/external dependencies? NA
    - Test accounts needed? NA
     - Does this require QA? NA
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by timwright12** [comment]
@dumathane seems like this would be a quick win to knock out

**Comment by bischoffa** [comment]
please add a sprint to this

**Comment by bischoffa** [comment]
please add a sprint to this

**Comment by TKDickson** [comment]
no QA needed, OK to merge to develop
