### ISSUE TITLE
CU - Streamline useIsScreenReaderEnabled hook and update doc

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-app#5057]
## Proposed Change

The useIsScreenReaderEnabled function in hooks.tsx was updated for a needed adjustment on short notice for the Nav project going out in a manner that ensured consistent behavior for preexisting functionality with potentially unnecessary safeguards on ticket #5047. This issue is to check if the potentially unnecessary safeguards can be removed (it is believed they can) without breaking existing use cases.

The specific aims of this code upkeep are:
1. Check if the two other hooks that leverage useIsScreenReaderEnabled still work as desired when withListener argument is removed and the function is always adding a listener (will reflect the update immediately when screen reader status is changed on/off, instead of only checking once at render time)
2. Investigate if the isMounted variable needs to exist anymore either after always using the listener, remove if it doesn't
3. Update the documentation (documentation/docs/Engineering/FrontEnd/CustomHooks/useIsScreenReaderEnabled.mdx) to match after-this-ticket functionality and document the additional example variety added with #5047 and any others in the interim

## Why Should We Prioritize?

Would greatly streamline this hook's functionality to be clear, concise, and efficient; potentially function better than it does now for existing use cases; and should be a fairly small lift.

**Comment by alexandec** [comment]
Note for QA, check usage of useIsScreenReaderEnabled for regressions:

- CategoryLandingTemplate
- FeatureLandingAndChildTemplate
- HeaderBanner
- CollapsibleMessage
- useAutoScrollToElement (AlertWithHaptics, ClaimPhase)

**Comment by rbontrager** [comment]
Verified that the functionality in the app when useIsScreenReaderEnabled is true works as expected for the items listed above.  Approved by QA.
