### ISSUE TITLE
GHA - Update release_branch script to allow to manual trigger

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#5058]
# Automation Ticket

## Type of Change
- [x] Update existing automation
- [ ] Add new automation functionality
- [ ] Fix automation bug

## What systems/scripts are changing?
- [x] Git Hub Actions
- [ ] CircleCI
- [ ] Fastlane
- [x] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

With PR #5014 we migrated the release_branch workflow to GHA.  With that, we also added the option to trigger the workflow using the `workflow_call` trigger.  However, the script has logic that only allows it to execute every other Wednesday.

While the script is unlikely to fail, we want to add a flag to skip this date check if the workflow is triggered manually.

## Acceptability Criteria

- [ ] Add parameter to allow workflow to be called manually
- [ ] Script should take this parameter into account and skip the date check and execute the rest of the script anyway

**Comment by bischoffa** [comment]
@timwright12 is this something that @IsraelleHub will eventually do? It has Narin assigned by he isn't on QA and Release Team

**Comment by timwright12** [comment]
yeah, it should be @IsraelleHub

**Comment by bischoffa** [comment]
Closing. Please refer to 5721
