### ISSUE TITLE
Automation - Fix iOS Crashlytics .dsym upload

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#5103]
# Automation Ticket

## Type of Change
- [x] Update existing automation
- [ ] Add new automation functionality
- [x] Fix automation bug

## What systems/scripts are changing?
- [ ] Git Hub Actions
- [ ] CircleCI
- [x] Fastlane
- [ ] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

Crashlytics requires that we upload .dsym files in order to get more details in our iOS crash reports.  We have logic in our iOS Fastfile to do this automatically, but it hasn't been working for the past several releases, so we've been uploading the .dsym files manually. 

[fastlane upload_symbols_to_crashlytics docs](https://docs.fastlane.tools/actions/upload_symbols_to_crashlytics/)

#### What testing needs to be done to ensure that this work is complete in production?
Check that that .dsym has been uploaded successfully after a production release

## Acceptability Criteria

- [ ] upload_symbols_to_crashlytics command in iOS fastfile has been fixed
- [ ] We no longer get an email from Firebase asking us to upload the .dsym after an iOS release

**Comment by lexicalninja** [comment]
@timwright12 is this still in need of repair?

**Comment by timwright12** [comment]
@lexicalninja no, I fixed it on a different ticket. Thanks for flagging
