### ISSUE TITLE
Bug - sev-3 - Android - LargePanel Content if large enough gets cut off at the bottom

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#5127]
## What Happened?
For Android devices if the Large Panel Content is long enough it gets cut off at the bottom. This is present on the VCL screen and the PrepareForVideo screen. The fix needs to be applied to the template and not just the individual screens so that this isn't an issue in the future. This should also not negatively effect the entire screen being covered by the panel by unintentionally making the Panels smaller or larger than they should be.

## Steps to Reproduce

 only reproduce by setting the Display Size larger while the app was open. If I kill the app, set the display size to largest, then open the app, I don't see the issue.

## Desired behavior

 I think @TimRoe is right that the underlying cause is probably similar to that other ticket. In both cases the issue only seems to happen if the display size is changed while the app is open.

## Ticket Checklist
- [x] Steps to reproduce are defined
- [ ] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic]

**Comment by Sparowhawk** [comment]
@TKDickson I think this issue has already been fixed.

We no longer use the Dimensions API that we used to and now use the built in layouts from StackCardInterpolationProps which is supposed to adjust accordingly. Can you please confirm.

**Comment by Sparowhawk** [comment]
I believe this was fixed with #5692

**Comment by TKDickson** [comment]
Agree with @Sparowhawk, closing
