### ISSUE TITLE
CU - Replace 'Arrow' references with 'Chevron' where applicable

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#5138]
## Proposed Change

![image](https://user-images.githubusercontent.com/46909588/226385562-d67b8da7-c951-4dbd-89d4-2c1b7c70eae8.png)

Don't have Arrow and Chevron interchangeable, these are very specifically different things.

**Comment by liztownd** [comment]
This appears to already be complete. I have found no references in the codebase to `ArrowRight` or `ArrowDown`, etc., all references seem to be pointing to `ChevronDown` etc.

<img width="445" alt="Screenshot 2023-11-27 at 10 33 58 AM" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/72234279/714f2818-4f1c-4213-aeaa-9bff121ca453">

**Comment by TKDickson** [comment]
Yeah @TimRoe fixed this during [his big icons changes](https://github.com/department-of-veterans-affairs/va-mobile-app/commit/5dbfee3e592e017dd32b37cd99d4271f3441351a), closing.
