### ISSUE TITLE
Engineering Initiatives (Frontend)

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5139]
This is a general purpose epic so we can organize all work that is internal to the frontend engineering team for the VA Mobile App.

**Comment by bischoffa** [comment]
Checking with Product to see how to handle this epic given its not a planned epic for Q2 but is still being added to and worked.

**Comment by bischoffa** [comment]
For the time being if work from this epic is being pulled into a sprint then Engineering needs to work with their team's PM to determine which epic the ticket should be a part of so its appropriately tracked and reported on for the POs given this epic is not.  

Work can be pulled into existing Q2 epics that have reporting. PMs can determine which epic this should be tied to.

**Comment by bischoffa** [comment]
All open tickets moved to their team specific bug and maintenance epics. Closing this epic.
