### ISSUE TITLE
Analytics: Health Dashboard and Monitoring (Appointments)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#5146]
# Epic
  
Placeholder....

**Comment by bischoffa** [comment]
Epic was created by Health Pre-2Q planning - not sure if its still needed. Its not been on Mobile's roadmap for Q3 or Q4

**Comment by bischoffa** [comment]
Closing epic. It was part of planning and it was never used and the structure of the work went a different direction. Thus outdated and no longer needed for future use.
