### ISSUE TITLE
Engineering Initiatives QA - UI Automation / Detox UI

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5149]
This Epic is to help build up some QA capacity in the future. The plan is that FE and BE points can be used to contribute to this work along with a bit of QA. This could be a project that folks pull from through out the quarter but would be higher priority than other non prioritized initiative work.

**Comment by bischoffa** [comment]
Moved 3 remaining tickets to 7624. Closing this epic.

**Comment by bischoffa** [comment]
Benefits of this work were gradually implemented over time starting in July 4th RC testing.

**Comment by bischoffa** [comment]
November 21st - all tests that could be automated were automated and were implemented in release testing

**Comment by bischoffa** [comment]
Next steps 

*   Proactively updating and adding automated test cases for new and improved Mobile App features 
*   Exploring ways to run automated testing for individual features vs the entire app 
*   Exploring enabling Front End Engineers to write automated test vs just having QA engineers
