### ISSUE TITLE
Update doc site with operations materials

### ISSUE THREAD

**Issue by Hallm13** [department-of-veterans-affairs/va-mobile-app#5177]
- Guidelines around how we do research on the mobile team
- Guidelines around how we do content on the mobile team
- Team onboarding docs: Making consistent and publishing on the doc site, assuming we’ll need to introduce some new folks

**Comment by bischoffa** [comment]
@Hallm13 QA has documentation on the team's site and github. 

How do you want to handle this epic? Move it to Global given Research and Content resources are housed there?

**Comment by kellylein** [comment]
This work will be included in #9388
