### ISSUE TITLE
Wayfinding

### ISSUE THREAD

**Issue by Hallm13** [department-of-veterans-affairs/va-mobile-app#5237]
[Sprint 0 brief](https://docs.google.com/document/d/169LTYKE9Y1tvNj5bi_HyrHVvGrI7tzVWL7yZJazUi54/edit#heading=h.3zoauctm44vc)
Project to develop a high level understanding of our technical capability for leveraging location services and other tools to help Veterans navigate VA facilities or surface location based alerts.

**Comment by ajsarkar28** [comment]
Not enough information in sprint 0 to constitute an epic. Closing.
