### ISSUE TITLE
CU - Update fonts webviewTitle and textWithIconButton to minimum size of 16

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#5260]

**Comment by timwright12** [comment]
@Sparowhawk Can you add more context to this ticket?
@narin @kellylein should the button part of this be with the design system? I think we actually removed the icon button

**Comment by TimRoe** [comment]
@bischoffa This is not design system related, it is about the app-level theming. Resolving it may be helped in the future by the design system when we have typography tokens to slot in the place of the app manually building fonts/typography, but it would still be an app-level change to leverage our tokens package version that contained that. 

This ticket would be in the global team's wheelhouse.

**Comment by bischoffa** [comment]
Moved to blocked as there is no details

**Comment by juancstlm-a6** [comment]
Proposed changes
## Screenshots/Video

<details>
<summary>iOS</summary>

| Before webviewTitle | After webviewTitle |
| ---- | ---- |
| <img width="100%" alt="iphone_standard_before_webviewTitle" src="https://github.com/user-attachments/assets/f6510399-a2f3-4d91-8aa1-9878a94f927f"> | <img width="100%" alt="iphone_standard_after_webviewTitle" src="https://github.com/user-attachments/assets/ac4b83bb-d5d4-4016-8b13-84cdaffe9ec5"> |
| <img width="534" alt="Screenshot 2024-09-26 at 1 24 33 PM" src="https://github.com/user-attachments/assets/03ac31a8-ea8a-4871-a4c0-8a12d54bfd9a"> | <img width="534" alt="iphone_mini_after_webTitle" src="https://github.com/user-attachments/assets/1eb52d78-2a1d-4bae-9826-17c3b68fefdb"> |

| Before textWithIconButton | After textWithIconButton |
| ---- | ---- |
| <img width="458" alt="iphone_standard_before_textWithIconButton" src="https://github.com/user-attachments/assets/129a062d-5271-45d4-aeea-97dcfcc710be"> | <img width="458" alt="iphone_standard_after_textWithIconButton" src="https://github.com/user-attachments/assets/27683dcd-45c1-4c43-8b83-3a470cf55608"> |
| <img width="534" alt="Screenshot 2024-09-26 at 1 23 42 PM" src="https://github.com/user-attachments/assets/0160bd60-3a9b-4e4e-9cbf-e771e8e91891"> | <img width="534" alt="iphone_mini_after_textWithiconButton" src="https://github.com/user-attachments/assets/eb7aff9e-4719-4eea-aab6-f729dc5c66d7"> |



</details>

<details>
<summary>Android</summary>

| Before webviewTitle | After webviewTitle |
| ---- | ---- |
|<img width="519" alt="Screenshot 2024-09-26 at 12 33 57 PM" src="https://github.com/user-attachments/assets/56238d85-68e7-4fd1-9d0a-8e23bcdbe235">|<img width="519" alt="Screenshot 2024-09-26 at 12 11 23 PM" src="https://github.com/user-attachments/assets/f8681c8b-064d-4b99-815b-6128d744f974">|
| <img width="441" alt="Screenshot 2024-09-26 at 12 33 37 PM" src="https://github.com/user-attachments/assets/130be0c5-95f0-4b48-8d07-3a257c190235"> | <img width="441" alt="Screenshot 2024-09-26 at 12 18 45 PM" src="https://github.com/user-attachments/assets/ae545cbc-bc22-4cad-8455-5d08f064eae8"> |

| Before textWithIconButton | After textWithIconButton |
| ---- | ---- |
|<img width="441" alt="Screenshot 2024-09-26 at 12 30 41 PM" src="https://github.com/user-attachments/assets/5040976a-8768-425e-bbd9-ac70717bdf58">|<img width="441" alt="Screenshot 2024-09-26 at 12 19 40 PM" src="https://github.com/user-attachments/assets/7851c40d-5d90-4bbc-82d0-62d42e9639f1">|
|<img width="519" alt="Screenshot 2024-09-26 at 12 30 22 PM" src="https://github.com/user-attachments/assets/44cdd490-34a4-41d5-af7a-b36484a6d707">|<img width="519" alt="Screenshot 2024-09-26 at 12 12 29 PM" src="https://github.com/user-attachments/assets/c592ca9d-b089-4af6-a5c1-e8a1dff8df26">|

</details
