### ISSUE TITLE
Enhancement - All - Swap Large Nav Buttons to List Rows in Profile

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#5264]
## What happened?
Currently, for personal / contact information screens, we are using the large nav button component to contain information such as a Veterans address, preferred name, etc. We should swap these components out with the large list row component.

## Specs:
- Device: All
- OS: All

## Desired behavior
The personal and contact information screens should display the proper component.

## Acceptance Criteria

- [x] @brea11y to create new mocks for ENG
- [ ] ENG to replace / swap existing components with the updated component based on the mocks provided by UX

## Bug Severity
- Impact: High
- Frequency: Low 

- 2 - High

## Linked to Story
[Figma screen mocks that were handed off to ENG](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?node-id=133-1850)

## Screen shot(s) and additional information
![Screenshot 2023-03-30 at 2.58.01 PM.png](https://images.zenhubusercontent.com/62c49b561233b940b1c3c3fb/3dfb421c-6417-403c-b397-0705794d2145)
Current component used in Figma and in the app

**Comment by rbontrager** [comment]
Verified that profile has been switched to list rows that match the design in Figma.  Verified that the profile list rows work as expected.  Approved by QA.
