### ISSUE TITLE
Placeholder: Write content for the new component category landing pages

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#5299]
### Description
Write descriptions for the new component landing screen category pages (9) + landing screen subsection descriptions where applicable, as identified in [the docsite taxonomy](https://docs.google.com/spreadsheets/d/1RQpy9tClEJULqV7hU9Rx8eK9fsnzHsSZe6KgA5diAVU/edit#gid=1785909543) spreadsheet. 

### Acceptance criteria
- [ ] Content written for all new component landing screen category pages + landing screen subsection descriptions where applicable
- [ ] Content for all pages reviewed, editing & approved by @mistymg 
- [ ] Content published to component landing screen category pages

**Comment by kellylein** [comment]
No longer needed due to Design System work
