### ISSUE TITLE
Placeholder: Update & create component doc site screens with new UX description text & format

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#5306]
### Description

- Update **existing** [doc site component pages](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/ComponentsSection/) with new UX description text using [combined component page template](https://docs.google.com/document/d/1dXO__jHhiQ9R2gRCbjWJ73J76XN3t-XbAGZoZrmSLrY/edit#) format. 
- Create **new** doc site component pages for components with available UX description text.

See [VA mobile app docsite taxonomy: WIP Mapping UX to ENG components](https://docs.google.com/spreadsheets/d/1RQpy9tClEJULqV7hU9Rx8eK9fsnzHsSZe6KgA5diAVU/edit#gid=1785909543) for a list of available UX descriptions & the corresponding existing doc site component pages.

**Comment by kellylein** [comment]
No longer needed due to Design System work.
