### ISSUE TITLE
Appeals Claims Decision Letters

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5326]
Extend DDL functionality for Appeals.

Original DDL Epic: https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/4290 

The VA.gov team has added the ability to retrieve Appeal Decision letters from VBMS using our current integration.  We are currently filtering them out until we can build the experience for Appeals in addition to claims.

**Comment by StacyB2023** [comment]
@Hallm13 Got it. Thanks. Will update/remove from board to reflect

**Comment by StacyB2023** [comment]
@Hallm13 Actually when we say "future quarter", are we saying, start step 1 in Q4?

**Comment by Hallm13** [comment]
Appeals claims is hidden behind a feature flag on web until they make the following change:

* VA sometimes will take a second look at letter when they hit the efolder and make more revisions
  * They don’t want Veterans to see Letters too soon and need them to only see approved letters
  * Web is implementing a delay from document creation
    * Mobile would have to follow that approach
    * Seems to be 2-3 days
  * VA board of appeals surfaced this

**Comment by kellylein** [comment]
Moving this to post-Q4 23 since there are still conversations going with the Board.

**Comment by kellylein** [comment]
BVA still wants to hold off on adding this functionality as of 1/2/24: https://dsva.slack.com/archives/C04KHCT3ZMY/p1704232902714509

**Comment by StacyB2023** [comment]
@kellylein Thanks. I will then move this into blocked and out of the "Next" for Q1

**Comment by bischoffa** [comment]
May be something to chat with Alayna about as this seems like a Benefits/Health thing after API

**Comment by StacyB2023** [comment]
@ala-yna Just looping you in. You may hear of this in your conversations with BVA. Until they give us the green light we will leave this one in icebox/blocked for now. But just for awareness incase appeals comes up in conversations

**Comment by StacyB2023** [comment]
Closing this epic. We have the access policy update epic #9409 which will include any appeals claims items
