### ISSUE TITLE
Automation - Update Doc Site on Develop Merge

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-app#5366]
# Automation Ticket

## Type of Change
- [x] Update existing automation
- [ ] Add new automation functionality
- [ ] Fix automation bug

## What systems/scripts are changing?
- [x] Git Hub Actions
- [ ] CircleCI
- [ ] Fastlane
- [ ] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

It was noted that [the GitHub Action to update the VA Mobile documentation site](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/pages/pages-build-deployment) only [runs once per day via corresponding config file](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/documentation_deploy.yml).

This is unintuitive since the doc site only relies on develop and there should not be risk in updating right away after the changes are available.

This ticket is to update the configuration to check if the VAMobile/documentation folder is being updated with a merge into develop and, if so, to run the aforementioned GitHub Action so it is promptly deployed to the documentation site.

#### What testing did you do?
I am unfamiliar with updating GitHub actions, but based on other FE tickets I believe there is a way to run locally to confirm the script is being run as expected.
#### What testing needs to be done by the reviewer?
Probably none if the draft testing by the coder works as intended.
#### What testing needs to be done to ensure that this work is complete in production? 
Find or make a PR to update some part of the documentation site, get it merged, and validate a couple minutes later it appears on the documentation site.

## Acceptability Criteria

- [ ] Verify that a documentation change merged to develop appears in the documentation site shortly after being merged (not around the hours of the current automatic daily run at 3AM UTC)

**Comment by timwright12** [comment]
closing, I think I completed this on a different ticket: https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/documentation_deploy.yml#L7

**Comment by TimRoe** [comment]
Looks like not associated with another ticket that went through PR, but yes completed with:
- https://github.com/department-of-veterans-affairs/va-mobile-app/commit/54992504f8f6d2e34e87a4c5c440c2b52d363542
- https://github.com/department-of-veterans-affairs/va-mobile-app/commit/0d59943ec640a7bf131c16ecae99feb3bf159fe2

👍
