### ISSUE TITLE
Establish and document the device lifecycle process

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5381]
Our current process for dealing with devices is a little muddy. We want to write down, formalize, and communicate to the team:

- How inventory is managed ([current spreadsheet](https://docs.google.com/spreadsheets/d/152XBxp-PfsJCyuzLCHy7WPwgnQiOdVkPjpgpEWZ96bE/edit#gid=945617554))
- How new devices are requested 9([Out of date, but basic information here](https://docs.google.com/document/d/13dFiIASSlBmdgnVETwj5ucapa9puHQK-5Elck6GY1fQ/edit#heading=h.5sn68fqmfw3s))
- How we decide on what devices to order (mentioned in the linked document for "how new devices are requested")
- How folks return devices ([current](https://docs.google.com/document/d/1FkIGoOiS6HmX5tPhIKTzkk0ypqyDjvIjCoakelHDuQE/edit#heading=h.bq03knum58v1))
- How we decide when to sunset a device (and the process to do so)

Currently inventory is managed in a spreadsheet, this is fine, but let's also set a cadence to keep it updated and periodic reviews (quarterly?).

All processes should be added to the main documentation site. Any internal docs should be moved into the content library.

**Comment by TKDickson** [comment]
@DJUltraTom had a follow-up question for Seth about whether or not this ticket was workable.

**Comment by TKDickson** [comment]
Moving to blocked while it's still unclear whether mobile or general IT will own device processes

**Comment by bischoffa** [comment]
@TKDickson any other updates on this ticket? If you want to transition it to me let me know.

**Comment by TKDickson** [comment]
@bischoffa this is @DJUltraTom 's ticket, I just moved it to blocked because Tom had told me he was still waiting to hear from Seth.

**Comment by timwright12** [comment]
@bischoffa @TKDickson @DJUltraTom I think, at this point we should just move forward on this ticket. Even if we get official word about devices it would be quite a while before any action was taken

**Comment by bischoffa** [comment]
@DJUltraTom any updates on this ticket since Tim's comment?

**Comment by DJUltraTom** [comment]
I've updated the Device protocol sheet with our current and expected behaviors
I'm ready to close this ticket pending @timwright12 's thumbs up/down

**Comment by timwright12** [comment]
I think this is fine 👍 

Closing out
