### ISSUE TITLE
Document the feature testing process

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5399]
We need to document the process for running feature tests. This process should include updating the release candidate testing script to include new features & what we look for during peer test plan review

This should include:

- [ ] Written documentation published on the [mobile docs site](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [ ] A flow chart for the process published to the [mobile docs site](https://department-of-veterans-affairs.github.io/va-mobile-app/)

**Comment by bischoffa** [comment]
Need to align internally on what all is accounted for here so that each QA person is talking the same talk / process / standard

**Comment by bischoffa** [comment]
Chatted with Therese today during 1:1 assigning to her for Q1 priority and okay if it spills into Q2 given other work and coverage requirements while I am out on leave.

**Comment by TKDickson** [comment]
We've been reassessing our current standards as a team, documented in [this (private) spreadsheet](https://www.google.com/url?q=https://docs.google.com/spreadsheets/d/1KZe9QNwAPi3fy9wcNFYF3_XT2j4LytZRLVdMPbrTyhU/edit%23gid%3D0&sa=D&source=calendar&ust=1710360631304353&usg=AOvVaw1nxUP1I6WOrswLTYO11Mmx). Next meeting on this is on March 18

**Comment by TKDickson** [comment]
Have recurring every-other-Friday meetings to chip away at this with the team; ticket is not yet done (but is definitely more than 8 points, so I'll repoint it now). @bischoffa I can close this ticket (and open a new identical one) if you'd prefer that, for Q2 work (rather than continuing this ticket, and you can move it to whatever epic makes sense). Let me know.

**Comment by TKDickson** [comment]
Haven't had one of those meetings (due to key absences) for several weeks; moving to blocked.

**Comment by TKDickson** [comment]
Assigning to @DJUltraTom under the assumption he will answer 'yes' to me pinging in DSVA slack. This is not time-sensitive, so no rush.
