### ISSUE TITLE
Establish an app version to stop general support

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5413]
We don't currently have any information about where we should cutoff support for app features. A question was brought up with the migration from EVSS to Lighthouse where the data needs to be remapped to support older app installs. We realized we're just supporting to the beginning of time right now, so it would be nice to know where we can stop support.

Now that we have a wonderful data person, we thought it would be great to get something like this in the backlog.

[Slack conversation](https://adhoc.slack.com/archives/C02KU4WC960/p1681931757632459)

We're completely open to recommendations, if the output of this ticket is just the data or a dashboard, that's fine. We just want to start the conversation.

**Comment by g-opzt** [comment]
Data is complete. To be shared out at Manager Meeting.
