### ISSUE TITLE
Preferred Name - APIs don't currently support preservation of name capitalization

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5423]
## Description 
As a veteran, I want to be called by my preferred name, so that I feel recognized and known as an individual by the VA.

As part of this story we want to:   
- If a user enters "McKinley" (or some other name with capitalization other than the first letter), we'd like to display and use that capitalization throughout the app where we display the preferred name (nametag component, preferred name row on Personal Info screen, preferred name screen, etc)

Right now, the upstream APIs do not preserve capitalization (I believe for this example they would return MCKINLEY) so we can't make this happen. Here's some excerpts from Slack:

> Okay, so it looks like preferred_name, which we probably just map to name on the FE in Therese's example, comes back from va_profile's endpoint in all caps. I'll reach out to them and ask about it

Result from pinging in va profile channel:
> This came up before as well when going live. This I believe was something brought up with MPI, I dont remember the outcome of that conversation.

Slack thread for reference: https://dsva.slack.com/archives/C018V2JCWRJ/p1677528276439019

## Acceptance Criteria
  

-  [ ] Identify what is needed to display and use that capitalization throughout the app where we display the preferred name (nametag component, preferred name row on Personal Info screen, preferred name screen, etc)
     -  [ ] Is this a change needed with va_profile's enpoint
     -  [ ] Is there a change needed on our end (if not high complexity can we implement in this sprint?)

Example Screen shots

![image (10)](https://user-images.githubusercontent.com/90273080/234017524-8b3ff013-3fe3-415c-9b5e-351338b287a0.png)
![image (8)](https://user-images.githubusercontent.com/90273080/234017572-94f71cdb-6789-4be4-a6fb-55b9f7314beb.png)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/97efdc15-54c0-4a95-bd26-f4d5f579a8b9)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by ala-yna** [comment]
Closing this ticket out - it's over a year old, and any changes around Preferred Name would need to be re-investigated.
