### ISSUE TITLE
Separate Cancel button in Action sheets

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#5430]
## Description 
In #5053, we fixed a bug where where Cancel button was not appearing on iPad action sheets, however this changed the UI slightly on iPhone.  Previously, the Cancel button was separated from the other buttons with a slight margin in between like so:

<img src="https://user-images.githubusercontent.com/90273080/233714534-c0c9c7a7-4bc9-49d2-bf31-83b2f6fd9d3e.png" width="370" />

After the bug fix, the buttons are merged together with no margin like so:

<img src="https://user-images.githubusercontent.com/786704/233716203-88b3dcbe-c5ba-4637-81f9-33b2dfff3cc0.png" width="370" />

As part of this story we want to:   

- Revert back to the previous design with the separated cancel button while maintaining functionality in iPad

## Acceptance Criteria
  

-  [ ] Cancel button is separate from other buttons in Action sheet
-  [ ] Cancel button appears and works as expected on iPad and Android

**Accessibility Requirements**
- [ ] Screen reader, voice control, and keyboard should function as they did previously

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes:

**Comment by DJUltraTom** [comment]
screenshots of implementation for ipad and iphone from this build are below. 
Verified copy is correct according to: https://docs.google.com/spreadsheets/d/1_6AFhiQBaPlrr5OzcMtng-Gvb-j8MEReB28JESpFPV8/edit#gid=2142734236

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0d31a2dd103d5182fee90fe1f99fd18cde6624b/IMG_355A81235D82-1.jpeg)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b47727715f4e1c6f34a4cb7978227e167ff401f/IMG_CB52C277613D-1.jpeg)

**Comment by DJUltraTom** [comment]
verified change to action sheet is consistent with intended design on the QA overnight build
