### ISSUE TITLE
Minor Update Dependency Update Rest of React dependencies

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#5486]
## Proposed Change

Investigate the code requirements for updating the following minor updates to dependencies:
add these 2 scripts
“node”: “rm -rf node_modules && yarn install”
“pods”: “cd ios && pod install && cd ..”

Minor Updates
----------------
“typescript”: “^4.5.5",
“@reduxjs/toolkit”: “^1.9.7”,
“@react-navigation/bottom-tabs”: “^6.0.9”,
    “@react-navigation/native”: “^6.0.6”,
    “@react-navigation/stack”: “^6.0.11”,
    “react-navigation”: “^4.4.4”,

check to see if this resolution is needed:
“@react-navigation/native/**/nanoid”: “^3.1.31”,

check to see if these patches are needed
react-navigation/stack

## Acceptance Criteria

- [ ] Investigate whether the dependency is required, or if we could take steps to remove from our list.
-  [ ] Create a branch off of `feature-xl/May-2023-Dependency-Updates`
-  [ ] update a few of the dependencies at a time, using `yarn upgrade <package 1> <package 2> <package 3>`
-  [ ] Check each dependency's release notes and make sure there are no breaking changes (Minor updates shouldn't have breaking changes but sometimes there are exceptions)
    -  [ ] If there are any breaking changes that affects our code, create a new ticket documenting this and move on.
-  [ ] After updating, perform smoke tests to ensure that the app is still working as expected

**Comment by timwright12** [comment]
Removed the health label since this is a global task
