### ISSUE TITLE
BUG - sev-2 - All - Authentication: id.me "remember me" checkbox does nothing for mobile app login - QA to retest

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5525]
## What happened?

I’m seeing a “remember me” checkbox option during id.me sign-in that hasn’t been there previously (previously as in for the year and a half I’ve been on the team, but idk when in the "relatively recent" past it appeared). 
Currently, from my very brief messing around with it, it seems to have absolutely no effect during mobile login in staging (doesn’t actually remember/pre-populate credentials). That also tracks with reports from veterans during UAT & research sessions, who noted the existence of the box when logging in but said it doesn't do anything.
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/2c831335-0a7e-4291-86f5-5f2c37667fd8)

## Specs:

- Device:
- OS:
- User Account: any id.me staging user
- Accessibility State:

## Desired behavior

*shrug*
This is in the webview, so while it's _possible_ that an auth/id.me team would be able to work with us to make this checkbox "work", it's 1) basically entirely outside of our control and 2) all Eng I consulted with about this were initially skeptical that it could be made to work, with how auth handoffs happen between web & mobile.

Another possibility is asking the team who owns this webpage to HIDE the checkbox, specifically when accessing the auth workflow from the mobile app (we pass.... I'm pretty sure we pass URL parameters, but maybe it's some other method --- but 100% they know the login is coming from us), so that way we're not showing a broken login thing to id.me users. (Especially frustrating since it claims to speed up auth, which we all know is a huge pain point for veterans)

Other solutions are also possible! Figuring out our preference & working with the other team = a lot of the work of this ticket, so it's probably a Product-first ticket.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High 

- 2 - High

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by DJUltraTom** [comment]
@bischoffa  Given we rolled back "custom Tabs" which was required for the function of the "Remember me" box, we should probably leave this open, and maybe move it to the back burner until we get a new solution in place?

**Comment by bischoffa** [comment]
Yep we can move it off. Thanks for checking into it. I will leave it blocked still by custom tabs.

**Comment by bischoffa** [comment]
Ticket blocked from prioritization consideration until Custom Tab work is done (which it was rolled back per comment above).

**Comment by bischoffa** [comment]
Slack chain following this ticket from 9/15 https://adhoc.slack.com/archives/CU2Q76NPR/p1694806659251409

**Comment by bischoffa** [comment]
Slack chain following this ticket from 9/15 https://adhoc.slack.com/archives/CU2Q76NPR/p1694806659251409

**Comment by bischoffa** [comment]
Jennifer, Tim W, and Dylan identified this ticket no longer is blocked as the Custom Tabs work has been released. So ticket can be moved out of icebox.

**Comment by bischoffa** [comment]
Given this ticket can be prioritized to be worked. Plan is to prioritize it for next sprint within the Bug capacity feature.

**Comment by bischoffa** [comment]
Custom tabs was re-released on 9/12 according to its sev-1 bug ticket 6561.

**Comment by DJUltraTom** [comment]
verified the check box now retains email address after logging out/ force quitting the app etc.
