### ISSUE TITLE
BUG - Sev 3 - all - Secure Messaging - empty folders could use some design love

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#5585]
## What happened?

Visually, if you navigate to an empty folder, its not a pretty sight.

## Specs:

- Device: any
- OS: both
- User Account: +41, karsyn.gpsysasynctwo, both have empty folders
- Accessibility State: n/a

## Steps to Reproduce

- using either account listed above, navigate to an empty folder
- observe the empty folder screen

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact:  Low 
- Frequency: Low 

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

![IMG_C07306892B7F-1.jpeg](https://images.zenhubusercontent.com/610aca11d461c11ca8e7e65e/912bab90-7c3b-4552-bfd2-ad6263930c84)
![Screenshot_20230503-203324.png](https://images.zenhubusercontent.com/610aca11d461c11ca8e7e65e/af550f93-d483-477a-9796-9f84553b2ccd)

**Comment by bischoffa** [comment]
Blocked until desired behavior is determined (see ticket in the dependency section). No movement until we get prioritization on work to determine desired behavior.

**Comment by bischoffa** [comment]
No ETA on prioritization. Dependent on other bugs and priorities.

**Comment by theodur** [comment]
Based on Brea's [findings](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6331#issuecomment-1706672391), it looks like this ticket is no longer needed. Did you want to confirm before closing this one @DJUltraTom?

**Comment by Sparowhawk** [comment]
@bischoffa Looks like this one can be closed as no longer needed.

**Comment by bischoffa** [comment]
Thanks, waiting for Tom to respond. I know Tom is out for a bit so lets see if @TKDickson knows or we can wait till Tom is back
