### ISSUE TITLE
Add TTY to Claim Detail Screen

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5588]
## Description 
As a Veteran that utilizes TTY, I want to easily see how to contact the VA when looking at one of my claims, so that it is easier for me to get answers on my claim.

As part of this story we want to: 
- Add the TTY link to the bottom of the Claim Detail screen, below the 1800 number
See design ticket: #5402 

## Acceptance Criteria
  

-  [ ] Add TTY link on the Claim Detail Screen following existing patterns and UX input

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by DJUltraTom** [comment]
verified tty is now appearing at the bottom of claims details screen under the 800 number
QA approves this change

**Comment by DJUltraTom** [comment]
verified TTY is present on the bottom of the claims details screen with the current overnight QA build, marking ticket as closed
