### ISSUE TITLE
BUG - Sev 3 - Android - "Delete Draft" menu options do not match AC

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#5592]
## What happened?
When validating [5258](https://app.zenhub.com/workspaces/va-mobile-qa-638781293f91d46e66b4a935/issues/gh/department-of-veterans-affairs/va-mobile-app/5258) We discovered that the menu options for "delete draft" on android don't follow the provided AC and are inconsistent with iOS

## Specs:

- Device: Google Pixel 4a
- OS: Android
- User Account: +41
- Accessibility State: n/a

## Steps to Reproduce

On an account with saved drafts
- Navigate to the drafts folder
- Select a message in the drafts folder
- Once the draft is open tap the Three dots menu in the upper right hand corner of the screen
- Select "Delete"
- observe the order of the buttons
## Desired behavior

Order of buttons should be:
- Delete Draft
- Save Draft
- Keep Editing

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)
![Screenshot_20230504-110547.png](https://images.zenhubusercontent.com/610aca11d461c11ca8e7e65e/4766b283-23ac-4339-a3a8-86b6dbf2e065)

**Comment by theodur** [comment]
It looks this was fixed with the recent Android action sheet [changes](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6163):

![Screenshot_1691537789](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/b209112a-d43b-4f2c-b8f8-c8c872f258be)

This one is good to close ✅
