### ISSUE TITLE
Spike - Figure out why charles proxy isn't working on RC + Android

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5661]
## Description 
As a QA Engineer, I want to be able to use charles proxy for Android on the RC builds, so that if I get an error I can investigate it, I can mock calls as needed, etc.

As part of this story we want to:   
-  Investigate why charles proxy is failing, and write up a ticket with how to fix the issue (that can get prioritized in its own sprint)

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions
- Charles Proxy on Android, on the RC build, is rejecting all traffic with a "SSL handshake with client failed" error. Is this for the same root cause why charles proxy used to fail, for Android, on XL builds?

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
@TKDickson @DJUltraTom is this ticket still valid? If so is it fair to say this should be assigned to the QA and Release team and not mobile-blue team ?

**Comment by TKDickson** [comment]
@bischoffa yes, home team work. I'll update the labels and add the generic team backlog epic.

**Comment by DJUltraTom** [comment]
Verified issue still occurs. RC builds give the folowing messagineg:
`SSL handshake with client failed: An unknown issue occurred processing the certificate (certificate_unknown)`
Switching to a non RC build on the same device and using the same connection allows traffic to be viewed with no issue. I have a.chls log captured comparing the two but zenhub in its infinite wisdom wont let us attach it.

**Comment by DJUltraTom** [comment]
@bischoffa  I believe this could be a ticket better addressed by @IsraelleHub or @narin as I believe Narin may have addressed this issue in the "before times" when we were initially trying to get Charles proxy to work with the app.

**Comment by bischoffa** [comment]
@IsraelleHub I am going to add this to the DevOps backlog and assign to you. Seems like some more investigation is needed and will need you / Narin to move this ticket forward.

**Comment by bischoffa** [comment]
Moved it to the DevOps Q3 epic

**Comment by TKDickson** [comment]
Closing this because there are larger issues with Charles Proxy + Android, see #9521
