### ISSUE TITLE
Integrate dependabot into va-mobile-app repo

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5669]
We want to find a way to better integrate dependabot into the mobile app repo for dependency management. We're currently spending a lot of time manually upgrading parts of the app and it would be better if we could tune up an advanced config of dependabot that we're comfortable with to handle the brunt of the workload.

The engineer who picks this up should also sync with QA about with dependancies need to go through QA, and at what level.

**Comment by theodur** [comment]
Noting some assumptions I have about which dependencies need to go through QA:

- I'm assuming almost all [dev dependencies](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/53feb823c3237ca4462821dc66e75b52d030bf2d/VAMobile/package.json#L96-L154) won't need to go through QA, except for a few, like detox and maybe babel related dependencies.

- For [non-dev dependencies](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/53feb823c3237ca4462821dc66e75b52d030bf2d/VAMobile/package.json#L42-L95), I'm imagining a lot of these will need to go through QA, specifically for major updates, but in terms of semantic versioning, patches and minor updates for most of these packages probably won't need to go through QA, except for minor updates to _essential_ dependencies like `react`, `react-native`, `react-navigation`, etc.

I'll reach out to QA to confirm which dependency updates should go through QA, and at what level.

**Comment by theodur** [comment]
In regard to the process for getting dependency updates QA'd, Dependabot PRs won't have a ticket attached to them, so QA wouldn't know which PRs need to be QA'd via the Zenhub board. They would only be able to see which Dependabot PRs need QA by looking at the PR list in the repo and looking at the ones with the `FE-With QA` label attached. 

One way around this would be to create a GitHub Actions workflow that creates a ticket for QA, so they can attach any Dependabot PRs that need to be QA'd. This workflow could attach a link in the ticket description that links to the [filters](https://github.com/department-of-veterans-affairs/va-mobile-app/pulls?q=is%3Aopen+is%3Apr+author%3Aapp%2Fdependabot+label%3A%22FE-With+QA%22) for the PRs that need their review, making it slightly easier to see which PRs need to be attached to the ticket. The workflow would only create a ticket if it notices Dependabot opened a PR that would eventually require QA. There are a few ways to filter this in the workflow, such as the ticket title, labels, etc.

Also, FE engineers would need to know which PRs can be merged immediately, and which PRs need to be QA'd. We could make a group in the Dependabot config for dependencies that require QA, and have Dependabot add a label to those PRs signifying that they need to go through QA before being merged. Maybe something like `Needs QA Approval`.

This process can also be discussed when I sync with QA

**Comment by timwright12** [comment]
@theodur If dependabot is opening the PR could we satisfy that with running all our automated testing (unit, e2e)? Like a special workflow that triggers for only PRs open by dependabot. If we have anything that an engineer opened I would assume that there would be an associated ticket.

My thinking there is if we only have dependabot to patches and minors with no breaking changes AND we run all possible tests in full, that feels like it should be enough to bypass QA

**Comment by timwright12** [comment]
The CI workflows for Detox aren't 100% yet, but IMO it seems like something we could lean on

**Comment by theodur** [comment]
Yeah, I think so too, especially since the Dependabot PRs shouldn't have breaking code changes. We may have to make a reusable E2E workflow so that we don't have to duplicate the code from the existing one. Unfortunately, GHA doesn't seem to have a workflow trigger that filters by the author of a PR, but that shouldn't be too bad

**Comment by theodur** [comment]
[PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6993) with Dependabot config has been merged. I'll monitor things on the first batch of updates scheduled to take place this upcoming Monday, but the work for this is complete, so I'm closing this out
