### ISSUE TITLE
Explore differences between Lists / Rows / Cards Components

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5671]
## Description 
As part of this story we want to: 
- UX & FE work together to better understand the Lists / Rows / Cards components
     - Padding varies around and between content/lines
     - Icon sizes vary between 16px and 24px
     - Top/bottom borders vary between rows
- While UX makes any updates to the component in the design library, UX will also look into improving the light/dark mode transition of the component. Currently, it wipes out some content when switching from light to dark mode.

See original UX ticket: #5598 and #5515

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by jessicawoodin** [comment]
Closing -- Will be addressed with #6785
