### ISSUE TITLE
Explore if/when we use the old and new radio/checkbox rows

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#5672]
## Description 
As part of this story we want to:   

- UX works to better understand when we should use the new radio/checkbox rows and if there are places we should continue to use the old component
- UX consults FE as needed

See the original UX ticket for more details: #5598

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by jessicawoodin** [comment]
Will be addressed with Checkbox, Radio Button, and List/Row component in design system.
