### ISSUE TITLE
Patient check-in: Turn on Waygate/Turn off feature flag 

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#5691]
## Description
As part of production readiness we need to complete the following pre-production go-live tasks

#### Engineering

1. - [ ] Ensure that waygate is set to true
2. - [ ] Replace feature flag references with the waygate name
3. - [ ] Add What's New In-App text (if applicable): 

#### QA

1. - [ ] Patient-check in feature is on by default (visible in app after install, without touching feature flag overrides)
2. - [ ] Patient-check in waygate flag is 'on' in the developer screen after initial install
3. - [ ] Patient-check in waygate (remote) flag is 'on' in the developer screen after initial install
4. - [ ] Turning off Patient-check in waygate flag turns off the Patient Check IN feature (no longer visible in app)
5. - [ ] Patient Check-in non-waygate flag has no impact on whether Patient Check IN displays in-app or not
6. - [ ] In demo mode, after setting in-app updates & encouraged update versions both to [release version], can see Patient Check-In content in What's New banner

**Comment by timwright12** [comment]
@ala-yna @dumathane Is this ticket still relevant?
