### ISSUE TITLE
Check-in -- QA Spike -- Can we use the existing data prep tools?

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5701]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md

^ currently unclear if QA team will be able to follow these instructions as-is, or if we'll be missing (waves hands) permissions/background setup of some kind, that will be necessary to request before getting access.

Ticket is to step through the instructions above, note where I'm blocked (if anywhere), and communicate that back to Product for check-in

**Comment by TKDickson** [comment]
@rbontrager you said you were able to do a single check-in in staging, before this epic got paused, right? If yes, please add a comment and then I think we can close this ticket.

**Comment by MekoHong** [comment]
I don't believe you could do anything in staging.  One of the blockers for continuing is not having a test account in staging and syncing on the CIE and appointments. Documented and tracked here https://github.com/orgs/department-of-veterans-affairs/projects/984?pane=issue&itemId=33330662 (There are some additional connections to the enrollment system that need to happen in staging for the test patient Rupert Throckmorton to be accessible. Marcy is currently working on). The team hasn't yet been able to resolve

**Comment by bischoffa** [comment]
Removed Blocked-QA label as this is not blocked by QA but blocked by QA being provided necessary testing accounts / data prep. This is something PM or POs will need to help assist with when patient check-in resurfaces as a priority.
