### ISSUE TITLE
QA: Test Plan Patient Check in

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#5705]
## Objective 

The purpose of this ticket is to document the test plan for Patient Check-in  

## Reference Material:
  

- 

**Epic(s)**
  

## Acceptance Criteria

  

1. - [ ]  Create test plan
2. - [ ] Link to test case folder in TestRail
3. - [ ] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
@MekoHong added label to this as it did not have a sprint tagged to it. Seems it was pulled in directly from New Issues to In Progress

**Comment by MekoHong** [comment]
@rbontrager could you add QA estimated points for this? Thanks

**Comment by bischoffa** [comment]
@MekoHong @rbontrager what is this regarding?

**Comment by TKDickson** [comment]
Check in is currently not moving forward, putting this back into the 'ready to work' column with the rest of the check-in tickets
