### ISSUE TITLE
SM - FE - Turn URLs in the body to Hyperlinks

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#5712]
## Description 
As a Veteran in the VA Health and Benefits App's Secure Messaging Feature, I want the URLs in the body of my Secure Messaging Message to be URLs that allow me to touch and take me to that URL

As part of this story we want to:   
- Enable Veterans to tap URLs in the body of a SM 
- When clicking a URL app will inform them they are leaving the app
- URL design library to following existing structure (see comments for design library from Lauren)

## Acceptance Criteria
  

-  [ ] AC 1
GIVEN Veteran's SM Message 
WHEN URLs are in the body 
THEN turn them into inline hyperlinks 

-  [ ] AC 2
GIVEN Veteran's SM Message has URLS in their body
WHEN Veteran taps the link
THEN display a "you are leaving the app" alert
AND launch in the phone's default browser

**Accessibility Requirements**

- Ability for screen readers to pick up the hyperlink details
- Ability for screen readers to read the you are leaving the app alert (we do this in other areas of the app)

## Notes & Open Questions

- Dependencies/Roadblocks: Yes - UX design input - ticket [5632](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5632)
- Any internal/external dependencies? Yes - UX design input
- Test accounts needed? Yes, with SM product
- Does this require QA? Yes 
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

[Link to Mural wire](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1678814753774/6419ffbf0434844d695912522dfdbc1c708345d7?wid=0-1684777445395)

 Current Experience
 
<img width="203" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/1d31a86a-57db-4393-8d6a-e006443c6188">

**Comment by Sparowhawk** [comment]
@bischoffa @kidlaurenpeace do we also want other links to be clickable like phone numbers and map links?

**Comment by kidlaurenpeace** [comment]
@Sparowhawk Yes

**Comment by Sparowhawk** [comment]
@bischoffa @kidlaurenpeace @TKDickson for LoS

This is the string in one of the messages for demo mode that I will be matching for links

"Upset stomach is a common side effect of this medication.  Mild stomach pain is normal, but if you are having severe stomach pains, please let us know or seek in-person care. If you need further assistance that isn't an emergency please call 8006982411 or 800-698-2411 or (800)698-2411, or (800)-698-2411 or 800 698 2411 or +8006982411 or +18006982411 or 1-800-698-2411. For more information on the side effects please go to one of these links: https://www.va.gov/ or http://www.va.gov/ or www.va.gov or www.google.com or https://www.va.gov/education/about-gi-bill-benefits/ or google.com  you can also email me at test@va.gov or mailto:test@va.gov or you can come to the office at iOS: http://maps.apple.com/?q=Mexican+Restaurant&sll=50.894967,4.341626&z=10&t=s or android: http://maps.google.com/?q=50.894967,4.341626",
        

It will cover multiple phone number formats, email formats, maps and url formats.

It won't cover other possible formats or other types of links(twitter handles, other clickable apps/links)

**Comment by Sparowhawk** [comment]
if there are any other formats you would like me to add just let me know

**Comment by TKDickson** [comment]
Shortened URL a la https://rb.gy/riwea ?

**Comment by Sparowhawk** [comment]
@TKDickson added that one as well

**Comment by DJUltraTom** [comment]
test cases here: https://dsvavsp.testrail.io/index.php?/cases/view/54016 @rbontrager or @TKDickson can I get your review and a thumbs up/down on those?

**Comment by TKDickson** [comment]
@DJUltraTom 
Case I would add - accessibility (what's the screen reader callout for the links in the messages, are they successfully flagged by voice/keyboard/switch as actionable)

Questions I have, which would impact cases - which messages does this apply to -- just inbox? all folders (including sent, trash, custom folders)? If I'm typing a message out, and include a link, will it be linkified there (I'm assuming no)?

**Comment by Sparowhawk** [comment]
@TKDickson this affects the message card when viewing a message and the other individual messages in the thread below. It doesn't apply elsewhere.

**Comment by DJUltraTom** [comment]
incorporated feedback from @TKDickson and created separate test case to cover running the accessibility test pass:
https://dsvavsp.testrail.io/index.php?/cases/view/54820

**Comment by DJUltraTom** [comment]
iOS with voiceover: does not allow for selection of the links, can only select the message content as a whole and have it read from the top.

Android: Allows links to be selected, but is missing additional context "double click to activate" examples that are present in other apps

**Comment by Sparowhawk** [comment]
@DJUltraTom Understood. I know the issue is that I wrapped all the individual components into one text view that is selectable for all the text. I will have to change this so that individual words are selectable so that we get that result you are expecting.

**Comment by Sparowhawk** [comment]
updated

**Comment by DJUltraTom** [comment]
Still unable to select the links by swiping, explore by touch, or setting the rotor to words and swiping.
This is on an ipad mini 5 running 16.3.1
Moving back to "in progress"

**Comment by Sparowhawk** [comment]
@DJUltraTom I have tried changing the TextView box to our other TextArea and box components to ungroup the individual words further but then every word then appears on it's own line or doesn't wrap correctly. This is the best that can be done with our current components. Moving back to with QA, but I guess design will have to be fine with this limitation and we will have to come back to it later for accessibility

**Comment by DJUltraTom** [comment]
@brea11y we could use your input on this.
Need to determine if the limitations with iOS accessibility should hold up this feature, or if we are good to go and can fix the iOS issue when a react native solution becomes available.

**Comment by brea11y** [comment]
@DJUltraTom – Let's move forward with it for now with a plan to circle back as soon as we have a solution for iOS.

**Comment by DJUltraTom** [comment]
sounds good, created: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7615 to track the bug

**Comment by DJUltraTom** [comment]
QA has approved this build

**Comment by bischoffa** [comment]
@brea11y @DJUltraTom for the circle back plan this should go to the Health PM - Alayna for prioritizes and backlogging. I am unable to @ her in these comments. Are you able to? ala-yna is her github name.

**Comment by timwright12** [comment]
Testing @ala-yna

**Comment by DJUltraTom** [comment]
verified linkification works on the overnight QA build, Closing this ticket as done and dusted!
