### ISSUE TITLE
Data request: # of current users check-in potential

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#5771]
Request originated with Matt/Greta in discussion around check-in

**Required questions**
Who is the audience for this request (check all that apply)?
- [X] VA mobile app POs
- [X] VA mobile app team 
- [ ] BAH
- [ ] Other VA stakeholders (specify them and their connection to this work)
- [ ] Other non-VA stakeholders (specify them and their connection to this work)

Whose perspective is this measurement meant to capture?
- [x] Current users of the feature/function: appointments
- [ ] All current app users
- [ ] All potential app users
- [ ] A different audience (specify)

What is the core motivation for the measurement? (You may receive follow up questions to confirm definitions of any key terms used.)
We want to measure how many of our current users have had appointments at a digital check-in enabled location in order to:
- [ ] Make a decision (specify the decision)
- [ ] Monitor efficiency
- [ ] Monitor efficacy
- [x] Something else: advise on the potential value of adding in check-in to mobile app

**Optional questions that can speed up the request:**
* What is your hypothesis? What do you expect to find in the data?
Unsure; we're assuming the number of current app users interacting with appointments who are connected to VA facilities that are digital check-in enabled is low. 

* What target(s), if any, do we have for these measures? What is the basis of those targets?
NA

**Questions to be answered by DA upon review:**
* What are the questions that this dashboard will be answering?
* Do we have all the tracking in place to capture necessary data to speak to the questions identified?
* If not, write up tickets for tracking events to be added. Also write up follow up tickets for each measure to be added and mark it as blocked until 30 days post-production implementation of tracking events.
     * Then, follow up with requestor and define and prioritize inclusion of alternative proxies while we wait for the tracking to be available.

**Comment by OVezeamama** [comment]
@ala-yna can you advise on this ticket?
