### ISSUE TITLE
BUG - sev-3 - All - Claims submitted file requests: mobile shows less info than website, confusing for 'no longer needed' requests

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5787]
## What happened?

For claims file requests, after a file has been submitted (or otherwise taken care of), the website shows what I'm going to call "status information" about the file request. This is the "no longer needed" or "pending" labels that appear in this screenshot from the staging website:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/210743fe-b814-4a62-b6a2-263fc27d18d0)

Mobile doesn't show that information - we show the request name, file name, type and date only. 
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/9b4c3152-161e-4b3c-a573-8a2cf688059f)

A lot of the time, I'm OK with that (what does 'pending' mean? I'm not sure - although I, like veterans, can make up a meaning). The one case where I think we're really/clearly doing a disservice by not having 'status' info is for a file request that was never filled/submitted, but the VA indicated they don't need anymore. Contrast these two, which one makes you more confident you know what's going on?

Web:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/db164135-0196-461c-9a2b-9c76f6e2be95)

Mobile:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/33782049-28a7-4286-a8e7-9a6a2495c552)

## Specs:

- Device:
- OS:
- User Account: Arfan (DS login) and judy.morrison@id.me are users with submitted file requests, although you may need to dig around in their claims to find which ones have the submitted claims
- Accessibility State:

## Desired behavior

I'd argue that our current UI, specifically around 'no longer needed' requests, is confusing/doing the veteran a disservice, because it's not clear _why_ the request is marked as done (they go into details and see nothing has been uploaded - potentially they become concerned and try to follow up to make sure everything is OK and to double-check they really don't need to submit a file). I'd like to pull in that 'no longer needed' info somewhere the veteran can see it. 

Details found in - Screen shot(s) and additional information

- [ ] Submission information should be replaced with "No longer needed" when appropriate
- [ ] The "(pending)" status should be added to the end of the submission date when appropriate
 

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Linked to Story

Found while testing #4745, not caused by the migration

## Screen shot(s) and additional information

It does look like we get that info back in the API, in the events timeline section. So should be able to display without BE work, I think.

![image.png](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUFaIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c17e92726d26a94057b86b155dfbf04b0edc7b58/Screenshot%202023-08-18%20at%2010.09.57%20AM.png)

Based on the information that Theo was able to see ([Slack thread can be found here](https://adhoc.slack.com/archives/C0212B872MT/p1692280857827499)), it appears that the "submitted" date and "no longer needed" would never be displayed at the same time. So, I am recommending that "no longer needed" replace the submission information. We should also pull the "(pending)" status in the date. 

Mocks of these screens can be found [in Figma](https://www.figma.com/file/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?type=design&node-id=1502-9122&mode=design).

## Action items
- [ ] Submission information should be replaced with "No longer needed" when appropriate
- [ ] The "(pending)" status should be added to the end of the submission date when appropriate

**Comment by bischoffa** [comment]
Blocked until mobile prioritizes UX to review and determine desired behavior. At this time no ETA and not planned for next sprint. Will reassess for future sprint planning.

**Comment by brea11y** [comment]
I have updated the ticket to reflect the UX recommendations. A screenshot of those recommendations and links to Figma have been included. Please let me know if additional information is needed on my end.

**Comment by TKDickson** [comment]
@aherzberg -- will we still have the right information for Brea's recommended solution with the Lighthouse migration? (I can/will test for this when the changes come through, but thought you might know off the bat either way). FYI @alexandec

**Comment by alexandec** [comment]
I wanted to record the logic on va.gov which we are duplicating. Here's what closed means:

```
const closed =
  item.type.startsWith('never_received') ||
  item.status === 'NO_LONGER_REQUIRED';
```

so an item is considered `closed` if the type starts with 'never_received' OR the item status is 'NO_LONGER_REQUIRED'.

Here's what reviewed means:

```
export function hasBeenReviewed(trackedItem) {
  return (
    trackedItem.type.startsWith('received_from') &&
    trackedItem.status !== 'SUBMITTED_AWAITING_REVIEW'
  );
}
```

so an item is considered `reviewed` if the type starts with 'received_from' AND the status is not 'SUBMITTED_AWAITING_REVIEW'.

And finally, building on those, an item is considered `pending` if it is not closed AND not reviewed. I'll go with that same logic to determine what we display.

**Comment by aherzberg** [comment]
@alexandec @TKDickson Yup, with the migration, those criteria will still be met. Lighthouse migration shouldn't break anything for this.

**Comment by TKDickson** [comment]
Does not need to be tested with LH migration on (per above), so flipping assignment from me to Tom (as I'm still neck deep in AF testing)

**Comment by DJUltraTom** [comment]
spot checked on the overnight QA build using +54, looking good,
Closing as deployed
