### ISSUE TITLE
Bug - Sev 3 - User feedback: Appointments - missing appts

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#5809]
My name is [redacted] and I use the general va mobile app. There is a glaring problem that makes me, and likely others, want to stop using it that should be easily fixed.

I have included a screenshot of two appointments I have coming up. One is an in person appointment and one is a video appointment. THEY BOTH SAY THEY ARE IN PERSON APPOINTMENTS.

 This has caused me a good bit of anxiety, as I imagine it has multiple veterans with memory issues. Why are video visits being marked the same way as in person visits in the app? The schedulers can see one as a video and the other as in person; that should be reflected in the app.

I'm not sure who this needs to be forwarded to, but I hope this feedback helps create positive change.

![Screenshot_20221107-112154.png](https://images.zenhubusercontent.com/5f9c54a1ad5a556830833cd6/8e43421c-6a0e-4fee-a156-9209aa1358ae)

**Comment by TKDickson** [comment]
Hey @MekoHong - did we uncover anything during investigation for #6542 that would shed some light on this issue (or maybe even resolve it)? Seem very related.

**Comment by MekoHong** [comment]
Hey Therese investigation into issue 6542 was resolved and fix was put in place.  Short summary of the issue:  We were missing logic for Video-Onsite visits.  Mapping was added and we are now aligned with web.  We were displaying the incorrect appt modality for video appts that should be at a clinic, but we are showing it as a Video at home appt leading to Veterans missing their appt.   Work done by both front end and back end 1) to update ApptType mapping and 2) FE changes will be needed to display the appt info accurately on both appt list and detail view.  More details of the issue can be found in this DSVA thread for reference: https://dsva.slack.com/archives/C018V2JCWRJ/p1692904186776569

**Comment by TKDickson** [comment]
Thanks Meko! Meko also found an instance of this mismatch happening with staging data, my hero. She's [pinged VAOS about it in DSVA slack](https://dsva.slack.com/archives/CMNQT72LX/p1697212595385939?thread_ts=1695058886.997429&cid=CMNQT72LX).

**Comment by TKDickson** [comment]
Waiting on info from VAOS, see DSVA thread.

**Comment by Sparowhawk** [comment]
@ala-yna @rbontrager From the thread it looks like this should be completely handled by the BE team can you guys confirm and let us know if there is anything FE needs to do? Thanks.

**Comment by bischoffa** [comment]
@Sparowhawk @ala-yna @rbontrager any updates on this ticket? Is this moving to BE like Dylan mentioned in March? 

Also can severity level get added to the name and label?

**Comment by ala-yna** [comment]
Closing this out - we've done tons of work into reevaluating the Appointments experience, and we've investigated why certain appointments weren't showing up.
