### ISSUE TITLE
User Endpoint Improvements

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#5815]
# Epic
Clean up user endpoint data in order to minimize the possibility that it fails and blocks the user from using the app

## User Story?
As a user, I should be able to use the app if non-essential calls to services upstream of vets-api fail  

### Discovery task (i.e. conversation with another team, review of past research, collaboration with engineering, etc)
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4550

### Key Takeaways
1. patch existing behavior: have product/frontend consider which of the user profile data the app CURRENTLY needs to operate. if it turns out a lot of this data is not needed, the backend can be changed to at least not fail on fetching that data. however, my guess is that the current front end won’t have any mechanism in place for re-fetching in order to get that data later, so you’ll be stuck with partial data for the entire session (which i believe is only 30-45 minutes but we should check with front end to confirm how frequently they fetch this data).
2. improve behavior moving forward: break that user profile fetch into multiple endpoints and change the front end to fetch them independently. this will allow the front end to try again later and hopefully give full functionality.

### Staging test accounts used to do discovery research
Any

### Blockers 
We need to know what the minimum amount of user data we can pass to the FE and still allow the user to navigate the app. Once we have that we can figure out how to split up the existing user endpoint to provide that data, but keep other, not immediately necessary data, separate.

**Comment by bischoffa** [comment]
Removed the sprint from the epic

**Comment by EricaRobbins** [comment]
@rachelhanster - Can you describe what shipped for this item?

**Comment by rachelhanster** [comment]
@chrisj-usds and Erica:
Outcome: Veterans get to use part of the mobile app, even if something fails on the backend--an upstream service or logic fails.
The change: endpoints/ locations of where the app gets veterans' personal data changed, e.g. VA facilities
Details: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/user-endpoint-enhancement/UEE-Sprint-0.md
