### ISSUE TITLE
QA - QA pointing, capacity & ticketing plan (initial brainstorming)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5823]
## Description 
As a member of the mobile team, I want to accurately account for QA time each sprint, so that everyone is on the same page about what _can_ be accomplished, what _is_ accomplished, etc in a given sprint. 

As part of this story we want to:   
Ideate a QA ticketing process that would account for:
- the various practices that contribute to QA work (mostly FE & QA, also occasionally BE and UX)
- the 'chunks' of QA work over time (test planning; test running; fixes & followups) that are currently invisible in our sprint planning
- how we can estimate work for QA, for use in sprint planning

Have a proposal for:
- Ticket template(s)
- When, how & by who QA tickets are created
- When, how & by who QA tickets are estimated
- When, how & by who QA tickets are advanced through the ZH boards
- When, how & by who QA tickets are closed
- Decision points that need to be made by other teams (ex: if QA has their own tickets, it will impact FE tickets in these ways & XYZ people need to decide what they're going to do)

## Acceptance Criteria
  

-  [ ] Initial proposal for all of the above is created & documented in this ticket
-  [ ] Created further tickets for all of the other work that's going to need to happen after this (more brain time, running this past various folks to get input and approval, work to implement this in ZH/md templates, etc)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
@jennb33 can this ticket be closed?

**Comment by jennb33** [comment]
@bischoffa this can be closed, thanks.
