### ISSUE TITLE
Create "feature signoff" markdown ticket template for QA

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5826]
## Description 
As a QA Engineer, I want to have a single source of truth for 'what testing needs to happen for [feature]' and 'has QA signed off on feature release', so that other roles are kept in the loop with QA signoff, and currently-undocumented work (ex: testing that needs to happen for a feature holistically/not tied to a specific implementation ticket) has a place to 'live' in our ticketing/pointing system.

As part of this story we want to:   

- 

## Acceptance Criteria
  

-  [ ] Put a ticket template up for PR review that includes 1) fields/information necessary to actually do feature signoff (think: checklists, prompts/placeholders for information that you'd want to have documented in the ticket) and 2) documentation about how feature signoff itself works (who's responsible, what stuff is included in this ticket vs other tickets, etc)
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 
[Conversation thread in Slack where the need for this was discussed](https://adhoc.slack.com/archives/C02N65QRRB7/p1682976026215199?thread_ts=1682541166.991409&cid=C02N65QRRB7)

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
@dumathane what is the status of this ticket?

**Comment by TKDickson** [comment]
@bischoffa I've created a template that I've been using (copy-paste style) for features on global. I'm going to create an actual template for it in markdown, and then @DJUltraTom you can iterate on that if you want in a later ticket
