### ISSUE TITLE
BUG - sev-3 - All - Appointments: when adding to calendar, we are providing a location which could be wrong for video visits

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5855]
## What happened?

When a veteran adds an upcoming at-home video visit appointment to their calendar from the app, we are filling out the "location" field in the created calendar appointment with a not-their-home location. For instance, if the veteran is going to be having a video visit WITH the Cheyenne VA, the way that we supply the information to the calendar app makes it imply like the appointment is happening AT the Cheyenne VA.

App version of the appointment (list and details. Details does have the name of the Cheyenne VA, down in the "where to call to cancel" section):
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/096bf975-03ca-482f-8db9-7c2b77710c79)
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/0f0da6a7-65e8-464b-83cd-8343cce006fb)

Calendar version of the appointment:
![image.png](https://images.zenhubusercontent.com/61a5397dac83844bf079e942/7943eaf2-fa61-4881-ae31-e6160219e34c)

When I found this, I didn't have a staging user who had one of those funky video visits that happen at a third party location (presumably because the veteran can't make it all the way to the physical location of the appointment, and also doesn't have video visit tech at home? I forget what they're called, I _think_ it's the ATLAS ones), but I imagine the same problem would likely also impact those video visits as well.

## Specs:

- Device: iOS (iphone 13) and Android (oneplus n100)
- OS:
- User Account: judy.morrison and john.morrison both had upcoming video visits when I found this bug
- Accessibility State:

## Steps to Reproduce

Health > Appointments > [open the details for an upcoming video visit, which you'll know because it'll have the camera icon in the list] > "Add to calendar" 

## Desired behavior

To "fix" this bug, we probably need to have special handling in place for adding to calendar for video visits specifically. "If it's this type of video visit, leave location blank. If it's this other type, do XYZ; etc"

According to "looking things up in code" these are the four video visit types:

      case AppointmentTypeConstants.VA_VIDEO_CONNECT_ATLAS:
      case AppointmentTypeConstants.VA_VIDEO_CONNECT_HOME:
      case AppointmentTypeConstants.VA_VIDEO_CONNECT_ONSITE:
      case AppointmentTypeConstants.VA_VIDEO_CONNECT_GFE:

This bug could be improved/partially fixed by the work done for #5854, but because video visits have a lot of subtypes, it probably won't 100% fix it all the way. Aka -- I'm guessing if 5854 is fixed first, the "home" video visits won't be broken anymore, but the "onsite" and "ATLAS" video visits might be.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@bischoffa This ticket should no longer be blocked. The only question now is which of the 4 video visits is incorrect on where the location is currently so we know which ones need to be fixed?

**Comment by bischoffa** [comment]
@Sparowhawk once we know what is broken do we what location to put or do we need UX to determine that?

**Comment by Sparowhawk** [comment]
@bischoffa What I need to know is where the video appoints are to take place for these appointment types:

AppointmentTypeConstants.VA_VIDEO_CONNECT_ATLAS]: ?
  [AppointmentTypeConstants.VA_VIDEO_CONNECT_HOME]: At clinician's location 
  [AppointmentTypeConstants.VA_VIDEO_CONNECT_ONSITE]: At facilities location
  [AppointmentTypeConstants.VA_VIDEO_CONNECT_GFE]: ?

Once I know the Atlas and GFE locations that I need to add I can take care of this accordingly

**Comment by Sparowhawk** [comment]
@TKDickson @rbontrager @kidlaurenpeace @bischoffa Do any of you know where GFE and Atlas appointments are supposed to take place so I can supply the correct address?

**Comment by TKDickson** [comment]
Good question @Sparowhawk. Looping in @MekoHong who may also know, from all of the appointment request work. I know GFE is government furnished equipment so I'd _assume_ it's just at home, but definitely not sure enough to supply it as an answer.

**Comment by bischoffa** [comment]
Have we tried reaching out to any of the VAOS Slack channels with this ask?

**Comment by MekoHong** [comment]
This may be a mapping exercise that probably should get addressed with the appointment content/alignment activities.  And yes, will likely need to reach out to VAOS channel to see how they are mapping and or can test to see how it is being handled on web to help with guidance.  Test user alfred.castillo has video appts

**Comment by Sparowhawk** [comment]
@MekoHong @bischoffa @TKDickson   I was able to discern that ATLAS stands for Accessing Telehealth through Local Area Stations which would mean I can only supply the address that is sent to us for the appointment as it would not be their home address. So all that is left is if GFE is at home or not.

**Comment by Sparowhawk** [comment]
I was also able to discern through reading the va.gov website that GFE would also be at home. So onsite is simple enough as it is the VA Medical Center they go to. Atlas may or may not be correct from the api, I don't know how else we would be able to determine their local VA center. GFE and at Home are both done at home, one is on their personal device the other is a government device.

So final result would be as follows:

Atlas
Onsite
   Both use location provided by api

Home
GFE
  Use address in this order if we have the data: Home > Mailing(non po box) > location from api

**Comment by MekoHong** [comment]
I think we should reach out to the Appointments team.  Did you by chance look at a home video on web and see how the handle adding to the calendar by chance?  Not sure that they are populating the Veterans home address.   Can we hold on this bug ticket and @bischoffa this mapping should probably be added to the content/mapping clean up for appointments.  Not sure that I am comfortable with the above without consulting with the appointments team on the proper handling

**Comment by Sparowhawk** [comment]
@MekoHong I did reach out to the appointment-fe-eng team and didn't get a response. I did some digging and found out what those appointment ares. I am fine with putting this one on hold/blocked pending the appointments mapping

**Comment by bischoffa** [comment]
@MekoHong what is the appointment epic we should include this in for the appointments mapping

**Comment by MekoHong** [comment]
Appt List & Details Content Alignment epic

**Comment by bischoffa** [comment]
Removing Tom as this was picked up after new team structures were set. Assigning to Rachael.

**Comment by bischoffa** [comment]
@DJUltraTom if there is any background on this ticket from the year its been open can you provide it to Rachael? I am assuming its likely nothing if H&B is just picking it up

**Comment by Sparowhawk** [comment]
@bischoffa With our spreadsheet https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=293647606 and our work to componetize all the types of appointments this bug will be addressed in that work once all the video appts are converted over to the new components.

**Comment by rbontrager** [comment]
Verified that Home and GFE appointments show the home address from the contact info page.  Verified that the VA In person, ATLAS, video(onsite) appointments show the VA facility. Approved by QA.
