### ISSUE TITLE
Automate App Store Data Ingestion

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#5877]
Currently, each month the steps outlined [here](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/App%20metrics/UpdatingDashboard) must be completed each month to report out on data from the app stores. This epic tracks the work of these manual updates and work to pursue automation of this data ingestion.

## User Story?
  
As the VA mobile app team, we want to monitor data from app stores, such as downloads, reviews, etc., in order to assess the app's success in meeting user's needs.

### Discovery task (i.e. conversation with another team, review of past research, collaboration with engineering, etc)
 
This is the description of where we are in terms of automation from the existing documentation. It is unclear when we last investigated options around this.

> There are no APIs for some store data we use to derive the current dashboard, which makes automating the entire process difficult. Beyond that, some store data is very volatile and can take up to 7 days to settle. We currently update the reports every month after the 7th of the month for consistency and to avoid any discrepancies that happen due to Apple and Google's collection processes.

**Comment by OVezeamama** [comment]
@ajsarkar28 data is manually pulled from the app stores on the 7th of the month. Its a light lift. Is it a priority to seek ways to automate?
