### ISSUE TITLE
CU - Update pods in repo

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#5883]
## Proposed Change

It appears the pod configuration in the repo is out of date. When I run `pod install` locally, 31 changed files appear. Updating the repo with these changes will ensure engineers have the correct setup.

In addition, I noticed that the version of cocoapods in ios/Gemfile (1.12.0) does not match the version in podfile.lock (1.11.3). If `pod install` is run with the newer version, it introduces about 200 changed files. We should ensure the Gemfile and lockfile versions match, probably by running `pod install` with cocoapods 1.12.0. This will update the lockfile and other pod-related files. Committing these changes to the repo will ensure that if an engineer runs `pod install` with 1.12.0, their repo will be in the correct state.

Helpful commands to install and run the newer version:
- `sudo gem install cocoapods -v 1.12.0`
- `pod _1.12.0_ install`

## Why Should We Prioritize?

The presence of all these modified files in the repo makes development confusing and cumbersome for engineers.

## Coding Time Estimation

1
	
## Testing Considerations

A quick smoke test should be all that's needed

## Checklist
[] Add the front-end label tag

[] Attach to the Frontend epic for engineering initiatives

**Comment by Sparowhawk** [comment]
being taken care of with the dependency/native module stuff I am doing
