### ISSUE TITLE
BUG - SEV 3  - All - Inaccurate error for Appointments

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#5888]
## What happened?

Several engineers found that when we can't get Appointments data for users, we show an error message that mentions calling the MHV Help Desk ([5605](https://app.zenhub.com/workspaces/va-mobile-qa-638781293f91d46e66b4a935/issues/gh/department-of-veterans-affairs/va-mobile-app/5605) and [5843](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/5843)). This information in not consistent with how VA.gov handles this type of error and incorrect since MHV is not associated with Appointments.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

We should show a more accurate error message that doesn't point users to the MHV Help Desk

## Acceptance Criteria

- [x] Implement red (error) AlertBox component (see screenshot)
- [x] Header copy: We’re sorry. We’ve run into a problem.
- [x] Body copy: We’re having trouble getting your appointments. Refresh this screen or try again later.
- [x] Primary button: Refresh screen
- [x] Tapping "Refresh screen" button attempts to get Appointments data again

![Screenshot 2023-06-06 at 9.41.21 AM.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/9c418886-c341-49ba-9ea5-f906c367dcb4)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

https://images.zenhubusercontent.com/292052392/51d3ad12-eb1a-47a7-9f62-9b952e1ed2cc/wrong_appointments_error_1.mp4

[Wrong Appointments Error 2.png](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/d1b4e69f-db46-4fa4-a4be-6798ea8050c4)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
Ticket is blocked until desired state defined more. That work is done in ticket 6485. Needs to wait on priority for 6485 first which has no eta.

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by TKDickson** [comment]
Confirmed ACs using Charles Proxy to completely block the appointments list load call; error meets design.

**Comment by TKDickson** [comment]
No additional testing needed in develop, closing.
