### ISSUE TITLE
Update Light/Dark Mode Friendly Contrast Fills for Icons

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#5889]
### Description
As part of #[5673](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5673), we investigated our duotone icons and determined the most contrast-friendly fills for light and dark mode.

### Icons that will NOT change
**Icons that should stay transparent ([see images](https://www.figma.com/file/SuLGwesaarqeqlm5N1Izkl/Icons?type=whiteboard&node-id=11-19163&t=5hq5E7epBp0D3s16-4))**
- Add
- ExclamationTriangle
- QuestionMark

**Icons that should stay filled in ([see images](https://www.figma.com/file/SuLGwesaarqeqlm5N1Izkl/Icons?type=whiteboard&node-id=11-19164&t=5hq5E7epBp0D3s16-4))**
- Minus

### Icons that will change
**Icons that should change to transparent ([see images](https://www.figma.com/file/SuLGwesaarqeqlm5N1Izkl/Icons?type=whiteboard&node-id=11-19320&t=5hq5E7epBp0D3s16-4))**
- VASelector
     - CheckBoxFilled
     - CheckBoxIntermediate
     - RadioFilled
- Links
     - Calendar
     - Chat
     - CircleExternalLink
     - CirclePhone
     - Directions
     - PhoneTTY
     - RightArrowInCircle
     - Text

**Icons that change depending on where they're used ([see images](https://www.figma.com/file/SuLGwesaarqeqlm5N1Izkl/Icons?type=whiteboard&node-id=37-15469&t=5hq5E7epBp0D3s16-4))**
- CircleCheckMark
     - **Claims Row & File Requests** - keep filled in to match step numbers
     - **Snackbar** - change to transparent
     - **Rx Refill** - change to transparent
          - In dark mode, change greenDarker icon color to greenLight to pass color contrast.
- Remove
     - **Photo Review** - keep filled in to pass color contrast
     - **Rx Refill** - change to transparent
- Info
     - **Label Tag** - keep filled in to pass color contrast
     - Add transparent option for future usage in Alert Box component

**Comment by timwright12** [comment]
@jessicawoodin @kellylein should this be migrated over to the design system repo? Or maybe closed out at this point?

**Comment by TimRoe** [comment]
@timwright12 Probably good for Jessica to confirm, but believe this can be closed out as VADS and USWDS do not have two tone icons (e.g. when all icons are updated, there'll be no secondary fill for contrast and it'll just be transparent to the background).
