### ISSUE TITLE
Component: Photo thumbnail

### ISSUE THREAD

**Issue by kidlaurenpeace** [department-of-veterans-affairs/va-mobile-app#5893]
# Common Component Ticket

### Image or Figma embed

[Link](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=6417-17521&t=3g0yafecPxfsKszw-4)

### Description

This component provides a tiled view that can shuffle based on the device type and screen size. The megabyte size of the component is listed below the tile.

### Usage

This component helps display photos that users intend to upload to a Claim File Review or Secure Message. It also helps in confirming the correct media, and also provides a way to remove a photo, or recover potential mistakes before submitting a photo.

### Best Practices

The component should follow established design patterns for both light and dark modes. The Remove icon should present the native functionality for confirming a destructive action.

### Content Guideline

Display the photo size beneath the photo thumbnail.

### Accessibility

Label: [Photo]; [xx] megabytes

Role: 

State(s): 

Hint: 

Value: 

#### After filling out the ticket
- [ ] Tag Jen Ecker, Jon Bindbeutel, and Therese Dickson in a comment on this ticket, and one of them will be in touch to add you to an upcoming committee meeting to review.

#### After component committee review is finished
- [ ] PR submitted to add the component to the Front End > Components section of the documentation site
- [ ] UX, QA, and FE reps on the component committee have socialized the new component with their respective teams
- [ ] Moved ticket to the 'Ready to hand off to Eng' column on the VA-Mobile-UX board

**Comment by jessicawoodin** [comment]
Will be addressed with DS ticket #6788
