### ISSUE TITLE
Analytics review & improvement: Payments/Direct Deposit

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#5914]
In order to better define and measure success in the Payments/Direct Deposit feature:

1. Review existing analytics on the feature.
2. If necessary, define any missing events, event params, or user properties needed to build metrics and measures of user-centered success.
     - If this was necessary, create follow up tasks to:
          - Hand off to FE for implementation 
          - Document in [data dictionary](https://docs.google.com/spreadsheets/d/1kC9qfyLjA757Wj2IdMwHHKxsX453WDQr0kEEqvLYyLQ/edit#gid=895875184) after implementation completed
          - Review existing dashboards where new information will start displaying and ensure documentation is coming through correctly.
          - Improve the existing dashboards any time at least 30 days post implementation live to users

**Comment by ala-yna** [comment]
Closing this out - issue hasn't been updated in over a year.
