### ISSUE TITLE
CU - Audit Areas of the app where we fetch right after a POST/PUT

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#5927]
## Proposed Change

We want to identify all areas where we are immediately fetching data after a POST/PUT request.

## Why Should We Prioritize?

We ran into a situation with Preferred Gender & Identity where there was a race condition after updating one of these fields.  This was resolved upstream, however it would be good to know where else we're doing this in case we run into it again.

Also, we should have a discussion about why we are sometimes using this pattern of fetching immediately after, rather than "honoring" the success message from the API and updating our redux state to reflect the change, rather than re-fetching.

## Coding Time Estimation

3
	
## Testing Considerations

N/A

## Checklist
- [x] Add the front-end label tag
- [x] Attach to the Frontend epic for engineering initiatives

**Comment by Sparowhawk** [comment]
this will be taken care of with the react query migration as we wait until the on success blocks to invalidate queries which will then go and refetch giving a more prolonged gap between calls, we also have a stale time of I forget how long that Theo setup that will also periodically refresh the data for the user.
