### ISSUE TITLE
Web vs Mobile Difference for Claims - Web allows file request upload after 5103 submission; mobile does not

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#5958]
## What happened?

When a veteran has an open claim with file requests associated with it, they have the option to submit a 5103, also known in our app as the "claims decision request", which attests to the VA that the veteran has no further documentation to add to the claim and that it's ready for review. That 5103 is only available when you still have open file requests (if you've filled all of the file requests, then it's assumed you're ready for review).

**After a veteran submits a 5103, the UI/allowed behavior in web and mobile is different.**
On the website, veterans can still SEE and SUBMIT DOCUMENTS for, all of the remaining open file requests.
On mobile, veterans can neither see NOR submit documents for, any remaining open file requests.

## Specs:

- Device:
- OS:
- User Account: +54, arfan.a.russel1, any user with open file requests
- Accessibility State:

## Steps to Reproduce

1. Prep a user to have open file requests (will likely be Narin, see this #5533)
2. Log in to the mobile app as that user, and also to staging.va.gov as that user. Notice that the UI & options are essentially the same for that claim (can upload documents for the file requests, or fill out a 5103 saying "I'm all done, this is ready for review")
3. On either platform, submit a claim decision request (5103). On mobile, this is Benefits > Claims > Claim history > [specific claim] > Review file requests > Request decision > [check checkbox] > Request decision
4. Now, look at the UI and options for the claim on both platforms. On the website, still can SEE and UPLOAD DOCUMENTS for the claim; can't on mobile.

## Desired behavior

Not sure. @kellylein or another Product person will need to talk to Claims SMEs about this. Arguably the mobile behavior is better/more correct, because I imagine the VA wouldn't want a veteran to continue to submit documents AFTER saying they're done submitting documents. But I don't know, and the problem here is that we should be really certain we're doing the right thing because claims are very important.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Linked to Story

Found during the EVSS to Lighthouse migration of claims decision request; unrelated to the changes in that work

## Screen shot(s) and additional information

<details>
  <summary>Claim that has file requests & no 5103 submitted:</summary>

GET /mobile/v0/claim/600411432 HTTP/1.1
Host: staging-api.va.gov
x-key-inflection: camel
authentication-method: SIS
Connection: keep-alive
Accept: */*
Accept-Language: en-US,en;q=0.9
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJ2YS5nb3Ygc2lnbiBpbiIsImF1ZCI6InZhbW9iaWxlIiwiY2xpZW50X2lkIjoidmFtb2JpbGUiLCJqdGkiOiIzOWRlNmU2MC0xZGE5LTQ5MGMtYmZmNi00ZDU4ZDk5ZjdkNjEiLCJzdWIiOiJkNmQ1NzJmYTNhNDM0MjA0ODY5Y2M1YTdhMmQxODBlMyIsImV4cCI6MTY4NjMyNTYxNywiaWF0IjoxNjg2MzIzODE3LCJzZXNzaW9uX2hhbmRsZSI6IjMwMjgyY2U2LWUzM2EtNDM0NS04ZTAwLWJmM2YxYzE1MDBhMiIsInJlZnJlc2hfdG9rZW5faGFzaCI6ImE5YWE5YjUzMjJmMGEyNzI1ZDA0Mjk5MmI4NmIyMDMzNWRkODE3Y2E5OGMzNTc4YmYyYzY3ZDBmNzUwNjRmNjAiLCJwYXJlbnRfcmVmcmVzaF90b2tlbl9oYXNoIjoiNzUwYjdlNzc0OTI3ODA5MWEwYjZmMWQzYzNkYTg0Y2QzMGE0ZDlkNjdiN2ExMjU1YWEzYTAyODQxMTBlZjU5ZCIsImFudGlfY3NyZl90b2tlbiI6IjQwZWRkZjA1OTJkYzlkNGVmNjYzNGY3MGE4NDcyNmIxIiwibGFzdF9yZWdlbmVyYXRpb25fdGltZSI6MTY4NjMyMzgxNywidmVyc2lvbiI6IlYwIn0.g3h5Tiq5kU-DTvSsEL0B2Qk44Rl13Fc5-1L5EJv9RN7blICq42OQ5qj1GKV845qbAPTgyIucOOHtOJgYrNKN3cbX1RnJqtdRpcUaqdzVUbWrAw1Iy86xrHGqnsji6vLDg0-ucr80rGflBNFIF6yQLPZWMYFhtZLeFpC0EI0IMXzlqYEFFtVWb5YiPkK1Cjd0GeBdho-EG2D5e4QV3LfcqqugprFfSMx16BQGPhp2QiwWizBSIv6q2Pr2D0ririRchUnxonYYsx9GSjPruPL_ZZvJXhpgZKug2RaIgjRu8LC_wyII1Rybypg5Z-IeykChQjB1wfAerFyii7M2fv59AQ
Accept-Encoding: gzip, deflate, br
User-Agent: VAMobile/708 CFNetwork/1404.0.5 Darwin/22.3.0

{
	"data": {
		"id": "600411432",
		"type": "claim",
		"attributes": {
			"dateFiled": "2023-05-31",
			"minEstDate": "2023-11-28",
			"maxEstDate": "2024-04-21",
			"phaseChangeDate": "2023-06-08",
			"open": true,
			"waiverSubmitted": false,
			"documentsNeeded": true,
			"developmentLetterSent": true,
			"decisionLetterSent": false,
			"phase": 3,
			"everPhaseBack": null,
			"currentPhaseBack": false,
			"requestedDecision": false,
			"claimType": "Compensation",
			"contentionList": ["Waldenstrom's macroglobulinemia (New)"],
			"vaRepresentative": "Contact your VA regional office for more information.",
			"eventsTimeline": [{
				"type": "still_need_from_you_list",
				"trackedItemId": 412815,
				"description": "You told us that you were associated with a Reserve or Guard unit.  Please tell us the following:\r\\n{*}  Name, mailing address and telephone number of your unit\r\\n{*}  Whether you are currently assigned to the unit\r\\n{*}  Whether the unit is reserve or guard\r\\n{*}  If not currently assigned to the unit, tell us when you were last assigned.",
				"displayName": "Reserve or Guard service claimed - unit info needed",
				"overdue": false,
				"status": "NEEDED",
				"uploaded": false,
				"uploadsAllowed": true,
				"openedDate": "2023-06-08",
				"requestedDate": "2023-06-08",
				"receivedDate": null,
				"closedDate": null,
				"suspenseDate": "2023-07-08",
				"documents": [],
				"uploadDate": null,
				"date": "2023-06-08"
			}, {
				"type": "still_need_from_you_list",
				"trackedItemId": 412814,
				"description": "Provide the date (month/year) of your marriage to <name of spouse>.",
				"displayName": "Claimant - date of current marriage needed",
				"overdue": false,
				"status": "NEEDED",
				"uploaded": false,
				"uploadsAllowed": true,
				"openedDate": "2023-06-08",
				"requestedDate": "2023-06-08",
				"receivedDate": null,
				"closedDate": null,
				"suspenseDate": "2023-07-08",
				"documents": [],
				"uploadDate": null,
				"date": "2023-06-08"
			}, {
				"type": "still_need_from_you_list",
				"trackedItemId": 412813,
				"description": "Provide the type of termination (death/annulment/divorce) for your marriage to <name of former spouse>.",
				"displayName": "Claimant - previous marriage termination type needed",
				"overdue": false,
				"status": "NEEDED",
				"uploaded": false,
				"uploadsAllowed": true,
				"openedDate": "2023-06-08",
				"requestedDate": "2023-06-08",
				"receivedDate": null,
				"closedDate": null,
				"suspenseDate": "2023-07-08",
				"documents": [],
				"uploadDate": null,
				"date": "2023-06-08"
			}, {
				"type": "phase2",
				"date": "2023-06-08"
			}, {
				"type": "phase1",
				"date": "2023-06-08"
			}, {
				"type": "filed",
				"date": "2023-05-31"
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Dental - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-4142a General Release for Medical Provider Information",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Disability Benefits Questionnaire (DBQ) - Veteran Provided",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "5103 Notice Acknowledgement",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Medical Treatment Records - Furnished by SSA",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Goldmann Perimetry Chart/Field Of Vision Chart",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Buddy / Lay Statement",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Civilian Police Reports",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "STR - Medical - Photocopy",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-0779 Request for Nursing Home Info In Connection with Claim for Aid and Attendance",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-0779 Request for Nursing Home Info In Connection with Claim for Aid and Attendance",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Disability Benefits Questionnaire (DBQ) - Veteran Provided",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-8940 Veterans Application for Increased Compensation Based on Unemployability",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 26-4555 Veterans Application in Acquiring Specially Adapted Housing or Special Home Adaptation Grant Under Title 38 U.S.C. 2101(a) or (b)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-8940 Veterans Application for Increased Compensation Based on Unemployability",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Certificate of Release or Discharge From Active Duty (e.g. DD 214, NOAA 56-16, PHS 1867)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Military Personnel Record",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Medical Treatment Records - Furnished by SSA",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Civilian Police Reports",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Automated Review Summary Document",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Automated Review Summary Document",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Buddy / Lay Statement",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "VA 21-526EZ, Fully Developed Claim (Compensation)",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Photographs",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "Correspondence",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}, {
				"trackedItemId": null,
				"fileType": "5103 Notice Acknowledgement",
				"documentType": null,
				"filename": null,
				"uploadDate": null,
				"type": "other_documents_list",
				"date": null
			}],
			"updatedAt": null
		}
	}
}
</details>

**Claim that has file requests open AND ALSO 5103 submitted via mobile app:**
Exact same as above, but with `"requestedDecision": true,`

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
@drjecker this is the claims ticket about mobile / web differences I was referring to in our 1:1 today

**Comment by bischoffa** [comment]
Removing from bug epic and moving to UX initiative epic

**Comment by TKDickson** [comment]
I'm not surprised this got lost, it didn't have any of the labels we use now. It looks like we have the information necessary from external teams to make a decision on what we'd like to do (or, given our new team structure, ask our claims-stakeholder-counterparts what they'd LIKE us to do).

Confirmed that this is still occurring, with several claims today. Web display after 5103 submitted: <img width="271" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGRQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb77c11b99ff5f3a92d289b14e4b261d6c3cae97/image.png" alt="image.png" />

**Comment by Sparowhawk** [comment]
@TKDickson I believe this is because web allows silent failures and therefore allows a "Submit Evidence" flow. Currently the plan for mobile was once that flag is flipped that it would return to the submit evidence flow and therefore still allow them to submit evidence as needed. However that flag is turned off until the silent failures stuff is fixed.

**Comment by TKDickson** [comment]
@Sparowhawk perfect. I will close this ticket (we've done the work, and are waiting on the Experience team decision to flip the feature flag). So the fix is released, but not 'on' yet.
