### ISSUE TITLE
Document analytics: vama_find_location

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#5967]
Post FE analytics implementation: update data dictionary with new event and review dashboard filters to ensure new event can flow through as tracking begins.

**Comment by g-opzt** [comment]
Added to data dictionary but blocked for flowing into dashboards until after version release.

**Comment by timwright12** [comment]
@OVezeamama kicked this to you. Can you evaluate and decided if we still want this?
