### ISSUE TITLE
Dashboard improvement: Add "Find a VA location" feature users count to monthly dashboard

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#5968]
30 days post [5966](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5966) being live to users, update monthly reporting dashboard Users page to count the number of active users for the feature.

**Comment by timwright12** [comment]
@OVezeamama kicked this over to you to decide if we still want it
