### ISSUE TITLE
BUG - Sev 3 - All - App Store Feedback - Veterans Still Reporting RX Access Issues

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#5987]
## What happened?

- App store reviews still show Veterans posting they cannot see their prescriptions though it was reported less in May than in April
- April App Store Review 10 of 15 RX reviews reported issues with not having RX in the app
- May App Store Review 2 of 11 RX reviewed reported issues not having RX in the app
- One user indicated that the app directed me back to the website 

## Specs:

ADDITIONAL INFORMATION IN COMMENTS BELOW:
- Device: specifics not known 
- OS: Android and iOS reporting 
- User Account:  NA
- Accessibility State: NA
 
## Steps to Reproduce

Unknown

## Desired behavior

If a Veteran has RX, then Prescription Functionality appears in the app

## Acceptance Criteria

Have engineering review is there is anything lingering that can cause this issue or if it requires user actions to remedy

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Ticket Checklist
- [X] Steps to reproduce are defined - NA 
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@bischoffa Is this one still an issue or can this be closed?

**Comment by bischoffa** [comment]
@Sparowhawk I believe its still an issue, however is not planned for this sprint so it shouldn't be picked up. Are you looking for backlog work to be pulled into this sprint?

**Comment by bischoffa** [comment]
Intent of this ticket is to investigate to see if there is any issues with people not being able to access RX with the necessary versions. 

Not sure what release led to the RX release but some of those listed above are old versions and would explain it. If there are those with the correct version then need to dive in from there.

**Comment by Sparowhawk** [comment]
@bischoffa diving into this further the release went out with the 1.43 update for default to be true, remote config was released separately. Both are currently set to true. So there is nothing remaining that we can update to make sure the user gets access. The only thing currently prohibiting access to prescriptions is if the user is not authorized for that service in our AuthorizedServicesState object. Which pulls up the not authorized screen which should have steps on how to get authorized.

**Comment by bischoffa** [comment]
@Sparowhawk thanks. So the list above with the versions, anyone before 1.43 version is just on an old version and needs to update to get access to it, if they are an authorized user. Correct?  
  
For those on 1.43 they could be stuck with cached values until they refresh (uninstall, reinstall) or update the app?  
  
For users with release above 1.43 (2. -2.3 in the list above) they do not have access cause they are not authorized for the Prescrption service per the VA. Correct?

**Comment by Sparowhawk** [comment]
@bischoffa That is correct.

**Comment by bischoffa** [comment]
@Sparowhawk Thanks. I am going to close out this ticket.   
  
If this comes up again from Veteran feedback, then I think we can look into adding logging to help us see what is going on.
