### ISSUE TITLE
FE: Update Patient Check in Appointment Help panel

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#5996]
## Description 
As a Veteran, I would like guidance on how I can get answers to questions I may have about my appt when going through the check in tasks using my mobile app.

As part of this story we want to:   

- Update previously created Appointment Help panel screen for check in (created with ticket #5819 

## Acceptance Criteria
  

1. -  [ ] Update [Appointments Help large panel](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1680618865216/19982c43fee09740dedbf4ebaf4e7f12f4787b84?wid=0-1685972549913) screen to add the following information: 

- Screen title: Appointments help
- Heading: Need help with your appointment?
- Body copy: For questions about your appointment or if you have a health-related concern, ask a staff member at your VA health facility.

2. Verify when selecting Close the panel is closed

**Accessibility Requirements**

Standard:

1. Everything on the page should be read by the screen reader.

If anything is being conveyed visually only (buttons, menu items, list, tables, images, headings, forms, etc) the
component type needs to be announced by the screenreader. (Include name (title), role, value)

2. Each page should support text resizing based on the OS font scaling settings without loss of content, content overlap,
or horizontal scroll.
Each touch target must be at minimum 44px by 44px

3. All elements on a page should be able to be traversed by an auxiliary keyboard. As a user uses the keyboard to
navigate a page, its focus element should be clear.

4. The app needs to support operability by tap (no gestures) or voice control only. In cases where gestures occur, e.g.
scroll, ensure these simple gestures are operable through the OS’ built-in capabilities.

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by MekoHong** [comment]
Hi @rbontrager can you add QA estimate for this ticket?  Thanks!

**Comment by timwright12** [comment]
@ala-yna @dumathane is this issue still relevant?

**Comment by ala-yna** [comment]
@timwright12, nope.
