### ISSUE TITLE
 QA Test Plan - In-App Recruitment

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6001]
**Acceptance Criteria:** 
The purpose of this ticket is to document the test plan for In-App recruitment
The plan should outline the overall objective, scope, and cases of the test(s) to be executed

- [ ]  Create test plan
- [ ]  Link to test case folder in TestRail
- [ ]  List of test data (or other testing needs) for Product
- [ ]  QA peer review of test plan & cases complete (sent out & feedback incorporated)
- [ ]  Socialize the testing plan with relevant practices (Eng, UX, Product)

**Comment by DJUltraTom** [comment]
test cases started [HERE](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12427&group_order=asc&display_deleted_cases=0)
Will update when ready for QA peer review

**Comment by DJUltraTom** [comment]
@rbontrager  @TKDickson  the test cases linked above are ready for peer review. Please comment with findings in a comment on this ticket.

I think its worth noting that this feature will require us to alter our RC and automated test cases around settings

**Comment by DJUltraTom** [comment]
Test plan completed and signed off, closing this ticket
