### ISSUE TITLE
In-App Recruitment - FE - Add Reporting Events

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6004]
## Description 
As a Ad Hoc / VA, I want to be able to track Veteran events in the app regarding In-App Recruitment, so that report, track, monitor, and assess data for Veteran engagement.

As part of this story we want to:   
- Add events per Analytic's requirements for analytics

## Acceptance Criteria
  
**For the "Give feedback" large panel, add the following events and event params:**
-  [ ] `vama_givefb_close`: user clicks "Close" button in "Give feedback" large panel (**or swipes the panel away?**)

-  [ ] `vama_givefb_launch`: User clicks "Get started" button in "Give feedback" large panel

-  [ ] `vama_givefb_wv_close`: user clicks "Close" button in Webview opened in `vama_givefb_launch`

-  [ ] `vama_givefb_info`: User clicks "Learn more about the Veteran Usability Project" hyperlink in "Give feedback" large panel's
 
-  [ ] `vama_givefb_info_close`: user clicks "Close" button in Webview opened in `vama_givefb_info`

-  [ ] `vama_givefb_wv_fail`: Webview launched by `vama_give_fb_launch` fails

-  [ ] `vama_givefb_wvinfo_fail`: Webview launched by `vama_givefb_info` fails  

**Add new events to other features which will be used as comparisons to the give feedback interaction data:**  
-  [ ] `vama_review_prompt`: app displays native UI prompt to submit an app store review
   
-  [ ] `vama_review_prompt_close`: user closes/dismisses native UI app store review prompt

-  [ ] `vama_review_prompt_submit`: user clicks submit in native UI app store review prompt

**Accessibility Requirements**
NA 

## Notes & Open Questions
- [Figma file](https://www.figma.com/file/L702ULyDKZbO2WBIHdJbyX/%F0%9F%94%8D-GlobalFeatures2.0---Working---VAMobile?type=design&node-id=807-3292&mode=design&t=Y8vLQtZ2MyK9aPHe-0) (exclude alert box for this ticket) just going to launch just with settings 

-Limitations

- Given we are not creating a form on our website and are linking directly to Perigean through a webview, once the Veteran taps "Get started" button we have no insight or internal reporting to understand success rates, timing, where/when Veterans falloff, completion
- Perigean will need to provide reporting on their form for any information we need

- Dependencies/Roadblocks: Waiting on events to be named and determined 
- Any internal/external dependencies? NA
- Test accounts needed? NA
- Does this require QA? NA
    
- Dev Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by theodur** [comment]
This ticket depends on [#6514](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6514) being merged before a PR can be opened for this. I was able to do the work for this by basing off of the branch in https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6514. The branch with the analytics events is [feature/6004-theo-InAppRecruitmentAnalytics](https://github.com/department-of-veterans-affairs/va-mobile-app/compare/feature/6004-theo-InAppRecruitmentAnalytics?expand=1).

Unfortunately, we aren't able to add analytics for the following events:
- `vama_givefb_info_close `
- `vama_givefb_wv_fail `
- `vama_givefb_wvinfo_fail `

This is because these events would happen when the user's screen is out of the app's control. Since the review prompt functionality hasn't been added to the app yet, the `vama_review_prompt` events can't be added

**Comment by theodur** [comment]
@g-opzt Dylan brought up a [point](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7367#discussion_r1408385315) about combining `vama_givefb_close` and `vama_givefb_wv_close` into a single event like `vama_givefb_close` and pass in parameters to that event for distinguishing whether the screen or webview is closed. Would this be okay from an analytics perspective, or would you rather us keep it with the separate events?

I believe the same question holds for combining `vama_givefb_launch` and `vama_givefb_info` into a single event and having a parameter to distinguish which thing was launched

**Comment by g-opzt** [comment]
Yep, that's totally fine!

**Comment by TKDickson** [comment]
@DJUltraTom signed off in Slack that this is OK to merge without QA, "assigning" him.

**Comment by DJUltraTom** [comment]
given that this is analytics for code that we already have in production that is exercised by our normal test runs (and that I already signed off in slack) I'm approving this code

**Comment by DJUltraTom** [comment]
Closing as there is no QA testing to conduct
