### ISSUE TITLE
Define analytics for Patient Check in (Placeholder)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6006]
### What is your specific ask / need from data analytics 
* Define analytics for new feature being implemented on mobile app Patient Check in

### Provide relevant details related to this request below
* Feature Requirements: [2023.05.18 Check in MVP decisions.docx](https://github.com/department-of-veterans-affairs/va.gov-team/files/11565559/2023.05.18.Check.in.MVP.decisions.1.docx)
* Design Wireframes: [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1680618865216/19982c43fee09740dedbf4ebaf4e7f12f4787b84?wid=0-1685029095303)
* Epic: [4315](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4315)

------------------------

## Required questions for submitter
Who is the audience for this request (check all that apply)?

- [X] VA mobile app POs
- [X] VA mobile app team 
- [ ] BAH
- [ ] Other VA stakeholders (specify them and their connection to this work)
- [ ] Other non-VA stakeholders (specify them and their connection to this work)

Whose perspective is this measurement meant to capture?

- [ ] Current users of the feature/function
- [X] All current app users
- [ ] All potential app users
- [ ] A different audience (specify)

What is the core motivation for the measurement? (You may receive follow up questions to confirm definitions of any key terms used.)
We want to measure __________________ in order to:
- [ ] Make a decision (specify the decision)
- [ ] Monitor efficiency
- [ ] Monitor efficacy
- [ ] Something else (specify the decision)

## Optional questions that can speed up the request:
* What is your hypothesis? What do you expect to find in the data? 

* What target(s), if any, do we have for these measures? What is the basis of those targets?
 
-------------------
## Questions to be answered by DA upon review:
* What are the questions that this dashboard will be answering?

* Do we have all the tracking in place to capture necessary data to speak to the questions identified?

* If not, write up tickets for tracking events to be added. Also write up follow up tickets for each measure to be added and mark it as blocked until 30 days post-production implementation of tracking events.
     * Then, follow up with requestor and define and prioritize inclusion of alternative proxies while we wait for the tracking to be available.

**Comment by OVezeamama** [comment]
@ala-yna Can you advise on this ticket?
