### ISSUE TITLE
Flip traffic to LH Rated Disability

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6020]
Switch over traffic to the new LH Rated Disability integration.

Rollout the change slowly:
10%
50%
100%

**Comment by kellylein** [comment]
Per VA.gov, the Disability Rating LH integration has been turned on to 100% for the VA.gov dashboard and profile.  As long as they aren't seeing significant error rates by **9/25/23**, we will turn this integration on for the app.

**Comment by jperk51** [comment]
To mitigate impact if there is an issue I'll be turning this on Sunday when the endpoint has less traffic. If all is well I'll leave it on at 10% through Monday, if things cont to go well I'll bump it up to 50% Tuesday night, and then 100% Thursday night. If at any point the errors jump up then I'll let LH know what we are seeing

**Comment by jperk51** [comment]
Bumped to 10%. No issues so far. Will bump to 50% tomorrow if this continues.

**Comment by jperk51** [comment]
Noticed a data issue at 100%. Today the fix should go in, will then test it in staging, then we should be good to bump it back up
