### ISSUE TITLE
Flip traffic to LH Direct Deposit

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6021]
Switch over traffic to the new LH Direct Deposit integration.

Rollout the change slowly:
10%
50%
100%

**Comment by jperk51** [comment]
No issues at 10%. Looking to update to 50% this afternoon. Will leave it there for a few days while observing logs and reddit

**Comment by jperk51** [comment]
Things are looking good so far at 100%. No reddit posts and no logging anomalies
