### ISSUE TITLE
Upgrade Appium Dependency

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6026]
During a sweep up dependency upgrade to [clear out security vulnerabilities]([url](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6024)) we were unable to resolve 6 issues with Appium:

- Appium > request | No patch available | Moderate |
- Appium > request | No patch available | Moderate |
- Appium > request | No patch available | Moderate |
- Appium > request | No patch available | Moderate |
- Appium > xmldom | No patch available |Moderate |
- Appium > xmldom | Subpackage moved | Critical |

The xmldom dom sub-package is particularly challenging because it moved from xmldom to @xmldom/xmldom, so we can't resolve it internally. I reached to the Appium engineering team and they said that [upgrading to Appium 2.0 will solve this issue]([url](https://github.com/appium/appium/issues/18746)).

Through the resolution process, we also had to add 10 instances specifically for the version of appium we're using.

As of right now, appium 2.0 doesn't appear to be released and the support team is not updating 1.0 anymore, so this ticket is **blocked**. 

Will circle back to check this monthly.

## Definition of Done:

- [Appium](https://www.npmjs.com/package/appium) is upgraded to (at least) 2.0
- Yarn resolutions have been either updated or remove
- Security vulnerabilities are gone or reduced as far as possible (`yarn audit`)

**Comment by Sparowhawk** [comment]
This is being removed due to us no longer using appium or chrome driver and instead using detox
