### ISSUE TITLE
Backend: Update appointments endpoint it include check in eligibility info

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6031]
## User Story

We need to add a few new data fields to the appointments response. The fields are outlined in our docs currently, but I will also list them here in the ACs. 

`eCheckinAllowed` is true if all of the below are true:
`eCheckinEnabled` from VAOS appointments response. 
`extension.vistaStatus` is (NO ACTION TAKEN/TODAY, INPATIENT/NO ACT TAKN, NON-COUNT) or empty. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzBFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ce7abef92eaa02d37b726e227d7b46efe0d5b88/image.png)
`kind` == clinic (in person appointment)

## Acceptance Criteria

- [ ] Add `eCheckinAllowed`. This field should be true based on the criteria listed above. 
- [ ] Add `appointmentIEN`. This field comes from the VAOS appointments response. 
- [ ] Add `checkinWindow` to `meta` block the way it's outlined in our docs 

## Additional Info

[Full Auth Check in Sequence](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/full-auth-check-in)

**Comment by jperk51** [comment]
Closing this ticket with the PR up. The work is completed as much as we can, but the data isn't going to be available from the upstream until towards the end of sept so there's no point in merging at this time. Meko and I will be tracking the upstream work and when it's ready we'll create a small ticket to finalize and merge this work.
