### ISSUE TITLE
Backend: Create & integrate with new endpoint /v0/appointments/check-in

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6032]
## Description of end point

We need to create a new endpoint in order to attempt to check a user into an appointment. 

## Method Details
- [ ] Method: POST
- [ ] Follow this schema. https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments~1check-in/post 
- [ ] create spec file

## Additional Info
If existing endpoint schema needs modified feel free to do so, but make sure the FE is aware they need to change their integration if they have already picked up the ticket. 

[Full Auth Check in Sequence](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering/full-auth-check-in)

**Comment by jperk51** [comment]
The check in team created a service in vets-api for us to integrate with.

**Comment by jperk51** [comment]
Waiting for chip to update their VCRs with the proper error responses so Jason can wrap up accordingly. 2pts of carry over @jennb33

**Comment by jperk51** [comment]
I'll check back in with CHIP team to see what's up.

**Comment by jperk51** [comment]
CHIP ticket: https://app.zenhub.com/workspaces/check-in-experience-61fc23a2cb8a14001132e102/issues/gh/department-of-veterans-affairs/va.gov-team/64492

**Comment by jperk51** [comment]
CHIP is still updating their specs in vets-api

**Comment by jennb33** [comment]
Asked @MekoHong and @jperk51 if this ticket should be moved to Sprint 80, based on the scheduling information from CHIPS team (attached)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWFHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98f8082d75bf6c6829751666df8355b1ec561dad/Screenshot%202023-09-11%20at%209.10.54%20AM.png)
