### ISSUE TITLE
Backend: Create & integrate new endpoint Patch: /v0/appointments/check-in/demographics

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6033]
## Description of end point

Create endpoint to PATCH demographics info for check in

## Method Details
- [ ] Method: PATCH
- [ ] Follow this schema: https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments~1check-in~1demographics/patch
- [ ] create spec 

## Additional Information
[Check in API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/full-auth-check-in/chip-design-doc.md)

**Comment by jperk51** [comment]
@cadibemma work with Andrew and Jason to make sure there are no controller conflicts since you are all working on the check-in controller at the same time.
