### ISSUE TITLE
Backend: Create & Integrate with new endpoint GET /v0/appointments/check-in/demographics

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6034]
## Description of end point

Create endpoint to GET demographics info for check in

## Method Details
- [ ] Method: GET
- [ ] Follow this schema: https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments~1check-in~1demographics/get
- [ ] create spec 

## Additional Information
[Check in API docs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/full-auth-check-in/chip-design-doc.md)

**Comment by aherzberg** [comment]
finished and tested. updated to an 8 since we had to add credentials to AWS and manifests repo which was not originally part of work
