### ISSUE TITLE
RX: List & Detail View Enhancements - Step 2

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6036]
# Project Status Overview

In Q2 23' the mobile team conducted a usability research study to 

- Engage with Veterans who use the Prescriptions feature recently launched in the VA: Health and Benefits Mobile app
- Surface any usability issues or points of confusion along the way in relation to prescriptions statuses and dates
- Understand their current experience refilling a prescription. 

As part of this research a key finding that we would like to address

1. All participants were able to successfully refill a prescription during the session. However, participants struggled to review their full list of prescriptions in order to identify the correct prescription they were looking to refill.

**Veteran Job to be done:**

Veterans use the VA: Health and Benefits mobile app, Prescriptions feature to get two jobs done:

1 job: request and track refills.
2 job: view list of medications and details of a medication.

**Problems to solve**

- **Problem A:** Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill.
   -  Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill. Participants did not use any other prescription status besides Active to determine what to refill. When prompted to define them, participants provided their own interpretation when scanning the list and the Filter options. Veterans view a list of “actionable” scripts, defined as medications they currently take or are looking to refill, without having to use “Filter by.”
- **Problem B:** When a filter is on, header 1 and header 2 counts are unequal.
- **Problem C:** Need to remove to Prescription/Refill statuses: Active: Suspended and Non-Verified as they are not used
- **Problem D** Help Veterans understand the app’s usage of “VA prescriptions"
 

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Dr. Spahn approval of Mobile' RX design | Kay & Coulton leading discussions; Go / No Go determined by Dr. Spahn | No ETA |
 
</details>

### Project Timeline
<details>

<summary>Milestones</summary>

**Identity Timeline:**  

Sept 23' 

- Complete Design, Content, & Data discovery/analysis & recommendations
- Remove status codes Non-Verified & Active: Suspended target app release 10/10/23

Oct 23'
- Mobile to provide design recommendation to Kay and Coulton no later than the end of Sprint 83 (11/7)
- Rachel & Matt agreed that Mobile will only work on RX into Sprint 83 and be on hold for Q1

Nov '23 
- Mobile Design recommendation delivered to Kay and Coulton for review via va-mobile-app-design [slack thread ](https://dsva.slack.com/archives/C02M11AKKNU/p1698849712471259)
- Kay and Coulton to provide feedback to Mobile Team
- Kay and Coulton to coordinate review with Dr. Spahn with Mobile supporting 
- Kay and Coulton to get Dr. Spahn's Go/No go with design and implementation 

</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------| 
|Sep '23| Green| Team is currently exploring opportunities to solve problems identified. Problem C: Dev complete remove non used status codes Non-verified & Active: Suspended App. Planned release store release 10/10/23| N/A
|Oct '23| Green | Finalizing design recommendations based on feedback received on sort/filter and number of RXs. This will be reviewed by Kay and Coulton with intent that design proposal is done early November then Kay and Coluton can share it with Dr. Spahn.  After passing it off, Mobile will be on a holding until we get feedback / decision from Dr. Spahn |
|Nov '23| Green | Mobile shared clickable Figma prototype of our design recommendation to Kay and Coulton |

</details>

# Detailed Project Scope 

- [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/medication/Product/Prescription%20List%20View%20Enhancements/Discovery%20Sprint%20Requirements.md)
- [Decision Log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/medication/Product/Prescription%20List%20View%20Enhancements/Decision%20Log.md)
- [RX Filter/Sort Prototype](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/medication/Design/List%20enhancements%20Q4%202023.md)

### Definition of Done 
<details>
<summary>Following needs to be true</summary>

Epic is currently in exploratory phase and making recommendation.  

</details>

## Supporting Team

| Name | Role |
| :--------- | :--------|
| Rachel Han | Product Owner, VA |
|Ryan Thurlwell | Design Lead, VA |
| Meko Hong | Sr. Product Manager, Ad Hoc|
| Lauren Russell | Sr. UX Designer, Ad Hoc|
| Misty Milliron-Grant | Sr. Content Designer, Ad Hoc|
| Greta Opzt |Sr. Data Analyst, Ad Hoc|

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] Project Kickoff session
   - [ ] Initiative Scope finalized
   - [ ] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [ ] Link to Implementation Strategy
       - Implementation Plan
       - UAT Plan
       - Release Plan
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide
  - [ ] Coordinate with contact center support teams
- [ ] What’s New Content
- [ ] App Store/In App messaging (if applicable)
- [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
- [ ] App store images needed? Y/N
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by bischoffa** [comment]
Step 2 completed - Figma prototype shared with kay and Coulton for them to work with Ryan on getting Dr. Spahn's approval.

**Comment by bischoffa** [comment]
Closing out this epic as it was only for Step 2 and creating a separate epic to house Step 3 and beyond.

**Comment by EricaRobbins** [comment]
@rachelhanster - double-checking, is this card for the Rx: List Detail View Enhancement feature or usability research? Thanks in advance!

**Comment by rachelhanster** [comment]
@EricaRobbins It's design only. Veterans are not yet getting this Prescriptions enhancement. I've updated the title of the epic to reduce confusion. Going forward, please tag @Hallm13, the card's assignee in this case @bischoffa and myself.
