### ISSUE TITLE
Finding Medications - Comparative Analysis Research 

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6041]
**Purpose:** 
Determine the best way for Veterans to find their prescriptions.

- In current RxR experience Veterans have a search & scan function to find their prescriptions a feature that is not currently on the mobile app.

**Problem we are trying to solve:** 

How might we help Veterans easily find and manage their meds (i..e which do they need more of, what actions should they take)

With decommission of RxR there are some concerns raised surrounding Veterans that currently rely on RxR for scan and search may get lost when moving to VAHB mobile app when trying to find medications without these features. On average Veterans take 8-10 meds at once ,spreading bottles on a kitchen table. 

- Would adding a search &/or scan functionality on the mobile app better support Veterans in finding the prescriptions they need faster and with ease?

**Focus** Market research on Scan Feature used by other Commercial Apps (i.e. Retail Pharmacy & Mail Order Pharmacy)

- What are other commercial apps are doing
- How have they incorporated scan
- Those commercial apps that have also included search functionality
- What are the differences from Retail Pharmacy & Mail order pharmacy
- What are some of the reasoning that retail pharmacy put scan in place

**Out of Scope**

Direct user research

**Documents**

- 

**Constraints / Limitations**

- 

**Open questions:**

-

**Comment by kidlaurenpeace** [comment]
Reopened to add Readout ticket

**Comment by MekoHong** [comment]
Research readout completed 8/30.  Closing Epic; analysis complete
