### ISSUE TITLE
Engineering Initiative - FE - Tech Debt - Testing

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6050]
## Purpose:

- Handling Technical Debt related to mobile app testing 

## Notes:

- Sponsor: Tim Wright
- Front end to work with impacted teams such as QA for test needing related to this work 

## Other Info:

- Created per convo between Tim/Adam for Q3 projects moving away from a general technical debt bucket to projects
- [List of tickets / categories ](https://docs.google.com/spreadsheets/d/1fbON0iddF4SoUTA5JFUY1O-WLKU6Q5SknmLH1Mw70Qc/edit#gid=0)this originated from

**Comment by bischoffa** [comment]
Starting Sprint 86 Tech Debt for all disciplines will be managed inside the new Mobile teams.

**Comment by bischoffa** [comment]
@dumathane there is 1 ticket left on this before the epic can be closed out. Do you expect this to be worked before Q4 ends or will roll over into Q1.   
  
Asking for Q1 2024 Planning Purposes

**Comment by TKDickson** [comment]
The last ticket (for moving away from referencing specific strings in unit tests) was added to the general global backlog. Closing this out after removing #5743 from the epic.
