### ISSUE TITLE
Analysis: App version updates timeliness and retention

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6052]
### What is your specific ask / need from data analytics 
* How well do our users do at updating to the most recent versions of the app? 
* How do our notifications affect this?
* How does this connect with user retention?

### Provide relevant details related to this request below
* [VA Mobile App Utilization by App Version](https://lookerstudio.google.com/u/0/reporting/19689ab3-865b-49cb-b351-0daa9faa35bb/page/p_uruy4djq5c)

------------------------

## Required questions for submittor
Who is the audience for this request (check all that apply)?

- [X] VA mobile app POs
- [X] VA mobile app team 
- [ ] BAH
- [ ] Other VA stakeholders (specify them and their connection to this work)
- [ ] Other non-VA stakeholders (specify them and their connection to this work)

Whose perspective is this measurement meant to capture?

- [ ] Current users of the feature/function
- [X] All current app users
- [ ] All potential app users
- [ ] A different audience (specify)

What is the core motivation for the measurement? (You may receive follow up questions to confirm definitions of any key terms used.)
We want to measure **how many users update their app version and on what timeline** in order to:
- [ ] Make a decision (specify the decision)
- [X] Monitor efficiency
- [X] Monitor efficacy
- [ ] Something else (specify the decision)

## Optional questions that can speed up the request:
* What is your hypothesis? What do you expect to find in the data? 
     * Hypothesis: users who don't update more likely to not be retained over the next X days.

* What target(s), if any, do we have for these measures? What is the basis of those targets?
     * NA 
 
-------------------
## Questions to be answered by DA upon review:
* What are the questions that this dashboard will be answering?

* Do we have all the tracking in place to capture necessary data to speak to the questions identified?

* If not, write up tickets for tracking events to be added. Also write up follow up tickets for each measure to be added and mark it as blocked until 30 days post-production implementation of tracking events.
     * Then, follow up with requestor and define and prioritize inclusion of alternative proxies while we wait for the tracking to be available.

**Comment by bischoffa** [comment]
Need Mobile analytics for this. They are still onboarding so will reassess timing when Adam is back from leave to see when Victor may be able to help and prioritize it against the rest of this work

**Comment by bischoffa** [comment]
Need to determine which teams own this. The questions asked in this ticket seem to lean towards Global work given its retention related and seeing how features impact retention.
