### ISSUE TITLE
Draft Sprint 0: Sharing data back to users/Veterans

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6063]
Draft Sprint 0 and put on Sprint 0 agenda idea coming out of conversation with @timwright12 around data ethics/equity and data we gather from Reddit:
Share back out aggregate data to Veterans and app users specifically, include them in the interpretation of the data, and demonstrate how we are using their data to provide value back to them.

**Comment by g-opzt** [comment]
@ajsarkar28 Flagging that this will not be completed this sprint and other newer items from this Epic have been prioritized over this. I'm not sure what updates need to be made to this ticket to reflect this change.

**Comment by g-opzt** [comment]
Pulling in as due to planned work being blocked I have 1 point available for this sprint.

**Comment by g-opzt** [comment]
Returning to backlog; I was able to start a but given that #6650 was pulled in after planning I do not have the capacity to complete this.

**Comment by bischoffa** [comment]
@g-opzt is this ticket planned for Sprint 80? I see @jennb33 added the sprint but its in backlog ready to work.

**Comment by g-opzt** [comment]
It is not; as my comment above said I ran out of capacity because other work was pulled in and this is a low priority item. It should not be in this current sprint.

**Comment by jennb33** [comment]
Removed, thank you @g-opzt and @bischoffa

**Comment by OVezeamama** [comment]
@ajsarkar28 closing this ticket.
