### ISSUE TITLE
BE - Reddit Scraper (Feedback Hub)

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6075]
## Purpose:
- Engineering has created a Reddit Scraper that enabled the ability to pull information from Reddit based on keywords which was demoed to POs
- Engineering would like to explore expanding this into a feature 

**Epic Status- Jan/24**- Closing this epic based on the completion of related stories noted within the epic.
## Notes:
- Reddit policy / rules have changed sense initial prototype/product which means it now costs money to use, thus need to see if its worth that value of proceeding 

## Other:

- Prototype / example has been shown in past demo session with PO
- Engineering write up [documentation](https://docs.google.com/document/d/1d8dDIFkqUrhCz2dtjZYTYjrW4Qp5KxyFXtUVaRptr8o/edit)
- Created per convo between Tim/Adam for Q3 projects moving away from a general technical debt bucket to projects
- List of tickets / categories this originated from this doc
- - Sponsor Tim Wright

**Comment by StacyB2023** [comment]
@Tonksthebear : Safe to close this one? All the applicable tickets are complete

**Comment by StacyB2023** [comment]
Note: The

**Comment by StacyB2023** [comment]
Reopening Based on testing and set up efforts going on in Q1 for Feedback Hub

**Comment by StacyB2023** [comment]
Closing this epic: New epic for Feedback Hub continued implementation will be: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8167
