### ISSUE TITLE
Document current state mobile analytics approach and definitions

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6081]
The following items need to be documented about our data analysis approach and definitions:

For each measure and metric:
- What is it trying to measure? 
- What perspective is it measuring from? User, VA, technical, something else?
- What analysis measure is used (count, distinct count, sum, percent, etc.)?
     - For percentages, define numerator and denominator.
- Is it a direct measure or a proxy? 
     - If proxy, what is the justification for the proxy?
- Are there standard ways of slicing it? If so, what are they?
- Where is it shared? (specific dashboards, reports, etc.)

**Comment by g-opzt** [comment]
Plan is to finish this by EOY; @jennb33 will provide feedback and support on finalizing this.

**Comment by OVezeamama** [comment]
@ajsarkar28 closing this ticket out
