### ISSUE TITLE
CU - Update Feature Build Workflow to include a Merge from Develop

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#6090]
## Proposed Change

Update our on demand feature build workflow to merge dev into the branch before building and report any conflicts found and fail the build if they exist.

## Why Should We Prioritize?

Can turn off mandatory branch updating and ensure that QA is not attempting to build on a branch that has merge conflicts that already exist.

## Coding Time Estimation

2	

## Checklist
[] Add the front-end label tag

[] Attach to the Frontend epic for engineering initiatives

**Comment by theodur** [comment]
@dumathane Since mandatory branch updating isn't enabled anymore for PRs, is this ticket still needed?

**Comment by bischoffa** [comment]
@dumathane is this ticket sill valid?

**Comment by dumathane** [comment]
Closing ticket as no longer valid.
