### ISSUE TITLE
Documentation Site Search Feature Broken

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6128]
On the [mobile documentation site](https://department-of-veterans-affairs.github.io/va-mobile-app/), the search is adding an extra va-mobile-app slug into the URLs, which results in 404 errors when you search for anything.

## Steps to replicate

1. Visit the [mobile documentation site](https://department-of-veterans-affairs.github.io/va-mobile-app/) site
2. Search for anything (I used "help")
3. Click of the results in the dropdown
4. See "page not found" error

You'll get a URL like this: https://department-of-veterans-affairs.github.io/va-mobile-app//va-mobile-app/docs/UX/ComponentsSection/Buttons%20and%20Links/ClickForActionLink#examples-in-practice

Note that there is an extra "/va-mobile-app" in the URL. If you remove it, the page will load.

## Expected behavior

Clicking an item from the search dropdown will load the associated page.

## Definition of Done

You can successfully search for a term on the documentation site and view the associated page without editing the URL.

**Comment by hasahmed2** [comment]
I'm unable to reproduce:

![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/148818278/e64297c4-b808-4e1a-be80-0963b0592eda)
Then I click:

![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/148818278/1c359987-e5cc-4faf-97db-7be3a82bca27)


This is on my laptop Windows11 PC on chrome browser

@timwright12

**Comment by timwright12** [comment]
@hasahmed2 looks like this got fixed at some point. you can close out

**Comment by hasahmed2** [comment]
Appears issue was resolved by another commit.
