### ISSUE TITLE
In-App Recruitment - Give Feedback - large panel creation

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6151]
## Description 
As a VA mobile app product and research team that wants to ensure maximum flexibility in terms of being able to target _specific_ app users in the future for recruiting, we want to display a Give feedback page that can be accessed easily from more than one category—containing enrollment information and a button that links the Veteran to a webview to see Perigean's recruitment questionnaire link—so that the Veteran app users we are trying to reach can start the recruitment enrollment process.

As part of this story we want to:   
- 

## Acceptance Criteria
  
-  [ ] When Veteran taps the "Give feedback" menu item in Setting they are navigated to a large panel 
-  [ ] Large panel header/title says "Give feedback" 
-  [ ] Header has a "Close" button on the top right of the page
-  [ ] Veteran touches "Close" button to close panel and return to screen where it was triggered 
-  [ ] Headline style (MobileBodyBold) & content matches Figma file
-  [ ] Body style (MobileBody) & content matches Figma file 
-  [ ] Add a "Go to questionnaire" button that links to [Perigean URL](https://docs.google.com/forms/d/e/1FAIpQLSfRb0OtW34qKm8tGoQwwwDFs8IqwOMCLTde3DeM-ukKOEZBnA/viewform) to open survey in a webview)
-  [ ] Below "Go to questionnaire" button add a ClickForActionLink below the button called "Learn more about the Veteran Usability Project" which takes them to veteranusability.us 
-  [ ] Below link add HelperText "VA contracts: 36C10B22C0011 & 36C10X18C0061"

**Accessibility Requirements**
- [ ] Screenreader focus
- [ ] Screenreader able to ready headline, header, copy, button, link, va contracts
- [ ] Type meets[ WCAG requirements (line height = 1.5x type size;  paragraph spacing = 2x type size)](https://docs.google.com/document/d/1JEUL7G796LWEXOiPfQo3twGhcZTnCUcnlFG8Kilgz18/edit)
   - [ ] MobileBodyBold: 20px font size: line height should be 30px and paragraph spacing should be 40px
   - [ ] MobileBody: 20px font size: line height should be 30px and paragraph spacing should be 40px
   - [ ] Link: 20px font size: line height should be 30px and paragraph spacing should be 40px
   - [ ] HelperText: 16px font size: line height should be 24px and paragraph spacing should be 32px

## Notes & Open Questions

- [Figma file](https://www.figma.com/file/L702ULyDKZbO2WBIHdJbyX/%F0%9F%94%8D-GlobalFeatures2.0---Working---VAMobile?type=design&node-id=840%3A6795&mode=design&t=0RZmWgQLn45Rht50-1) with "Give feedback" large panel design 
- What is the [perigean URL](https://docs.google.com/forms/d/e/1FAIpQLSfRb0OtW34qKm8tGoQwwwDFs8IqwOMCLTde3DeM-ukKOEZBnA/viewform)? 

- Dependencies/Roadblocks: 
      - Finalized approval from Danielle Thierry for content - Misty coordinating with Danielle
      - Verify there is no copy concerns from Danielle Thierry for situation in which people have already completed a survey and sign up again as there is no feedback logic - Adam sent DM 6/22 - waiting response
- Any internal/external dependencies? Danielle Thierry copy approval 
- Test accounts needed? Yes - any 
- Does this require QA? Yes 
    
- Dev Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

![image.png](https://images.zenhubusercontent.com/5d70131f8974635e17e294dc/88bacadf-2ab8-4370-834d-68ebd208adf1)

**Comment by bischoffa** [comment]
In code review as its not a priority, focusing on other PRs first.

**Comment by bischoffa** [comment]
Month post code review - when should we close this? Its possible that In-App recruitment may not be prioritized till much later than now

**Comment by bischoffa** [comment]
@dumathane does this ticket stay in code review until In-app recruitment work is prioritized? This is not a top project for POs.  cc @jennb33

**Comment by bischoffa** [comment]
@dumathane reaching back on the previous question

**Comment by dumathane** [comment]
If we're not planning on delivering this anytime soon we should probably close the branch and just document it on this ticket for when we eventually pick it up. Then move the ticket back to the backlog. That sound fine to you @bischoffa ? If so @Sparowhawk can you make that happen?

**Comment by Sparowhawk** [comment]
work is completed in feature/6151-Dylan-InAppRecruitmentPanel branch, closing this pr for now and moving back to backlog

**Comment by DJUltraTom** [comment]
tested this code in test run: https://dsvavsp.testrail.io/index.php?/runs/view/5007&group_by=cases:section_id&group_order=asc
Everything is looking good, QA approves of this code

**Comment by DJUltraTom** [comment]
verified this is still functioning and looking as expected in overnight develop build
Closing ticket
