### ISSUE TITLE
In-App Recruitment - Post Go Live - Replace Feature Flag with Waygate

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6153]
## Description 
As a Ad Hoc / VA, I want to replace feature flag with a waygate, so that I have better control of turning on and off the feature

As part of this story we want to:   
- Remove the feature flag
- Add a Give feedback waygate 

## Acceptance Criteria
  

- [ ] Remove the feature flag
- [ ] "Give feedback" menu item in Settings is visible by default (visible in app after install, without touching feature flag overrides)
- [ ] Give feedback in waygate flag is 'on' in the developer screen after initial install
- [ ] Give feedback in waygate (remote) flag is 'on' in the developer screen after initial install
- [ ] Turning off Give feedback waygate flag turns off the Give feedback feature (no longer visible in app)
- [ ] Give feedback non-waygate flag has no impact on whether Patient Check IN displays in-app or not

**Accessibility Requirements**
- NA

## Notes & Open Questions

- Dependencies/Roadblocks:
- Any internal/external dependencies?
- Test accounts needed?
- Does this require QA?

- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by Sparowhawk** [comment]
@dumathane do we still need this ticket with the new waygate stuff you setup

@bischoffa for LoS

**Comment by DJUltraTom** [comment]
verified waygate panel changes work as expected and provide error messaging in line with what is entered via waygate switch

**Comment by DJUltraTom** [comment]
verified this appearing as expected in overnight dev build.
closing as deployed
