### ISSUE TITLE
Update Claims and Appeals controller to use both policies

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6165]
Claims and appeals controller only executes the claims (evss/lighthouse) access policy right now. We need to update it to also execute the appeals policy. Additionally if either of these policies fail, but not both, we should only fetch the one that succeeds. Given the current state of the policies this should rarely happen, but in case they change in the future we should handle it. 

AC:
- [ ] version claims and appeals endpoint 
- [ ] add appeals policy to controller
- [ ] return multi status response for when one of these fails up not the other
- [ ] add tests for versioned endpoint 
- [ ] update docs 
- [ ] work with FE/PMs to get ticket created for FE to switch to this version of the endpoint 

Note: If the FE is already prepared for a multistatus response from this endpoint then we don't need to version it

**Comment by DJUltraTom** [comment]
Using Judy.morrison (enabled for lighthouse with the my_va_lighthouse_claims property) Regular claims are looking good, unable to check appeals yet, 

Using +7 , which in the flipper indicates is the only user using "mobile_lighthouse_claims" I'm getting the following response which results in an "App is not working" screen
```
{
	"data": [],
	"meta": {
		"errors": [{
			"service": "appeals",
			"errorDetails": [{
				"title": "Not found",
				"detail": "Appeals data for a veteran with that SSN was not found",
				"code": "CASEFLOWSTATUS404",
				"source": "A veteran with that SSN was not found in our systems.",
				"status": "404"
			}]
		}, {
			"service": "claims",
			"errorDetails": "Forbidden: User is not authorized for claims"
		}],
		"pagination": {
			"currentPage": 1,
			"perPage": 10,
			"totalPages": 0,
			"totalEntries": 0
		}
	}
}
```

cst_use_lighthouse (CST = Claims status tool) property is enabled for everyone, and using +226 I am able to see appeals tickets with no issue but when I look at a normal claim I get a 502 Bad Gateway error:
```
{
	"errors": [{
		"title": "Bad Gateway",
		"detail": "Received an an invalid response from the upstream server",
		"code": "MOBL_502_upstream_error",
		"status": "502"
	}]
}
```

Do we know which of these properties is the one we should be validating with?

**Comment by jperk51** [comment]
@DJUltraTom This work is not dependent on lighthouse. Imo, the testing just be the normal, non-lighthouse, testing we do for appeals/claims. The work was just adding an access policy for appeals.

**Comment by DJUltraTom** [comment]
Verified using multiple accounts that appeals and claims are appearing as expected, no strange or unexpected activity appearing in responses while viewed in charles proxy
