### ISSUE TITLE
Investigate colors used in filter/sort components

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6179]
## Description 
As part of this story, we want to investigate the colors used for "cancel" "done" and "reset" in the filter/sort components. During #[5515](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5515), it was discovered that sometimes the buttons are gray, but other times they're blue.

![image.png](https://images.zenhubusercontent.com/63c8183fd2ad0e803513538d/ea3d194f-f63d-44bd-9be8-70b2998aa836)

![image.png](https://images.zenhubusercontent.com/63c8183fd2ad0e803513538d/6c8e81a7-8641-4db9-b629-44d83d2f66be)

## Steps
- [x] Review component in design library and demo mode
- [x] Review recommendation with design librarian and UX lead.
- [x] Create branch and update components based on recommendation
- [x] Work with PM to create FE implementation tickets.

**Comment by brea11y** [comment]
A FE implementation ticket #6587 has been created for this work. I am closing this ticket.

Recommendation: To help align with our universal link color (and what we are doing in the filter / sort panel within Rx), I recommend updating the links in the list header to blue. These recommendations have been approved by Jessica and screens with the recommended update can be found [in Figma](https://www.figma.com/file/tLJKv0x0iacZzkZPoqZVaa/Components-for-future-releases?type=design&node-id=202-1398&mode=design&t=bRTcma4rv79RB2qk-4).
