### ISSUE TITLE
Add/update analytics: Login

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6227]
## ACs
- [ ] Add new event **`vama_login_readme`**: During initial login flow, user clicks to expand the section "Read more if you haven't yet verified" section on Login screen.

Update the following existing events as described below:
- [ ] `vama_login_start`
* We want to modify the event logic to enable measurement of the login process from the user's POV on when they start logging in.
* **Biometric** user login starts when The user has to provide their biometrics.
     * Should be logged in [startBiometricsLogin()](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/9cdb079791cabdc920b1f0460b084c122a285341/VAMobile/src/store/slices/authSlice.ts#L597) 
* **Nonbiometric** user login starts when Webview of VA.gov sign on launches and no biometrics were provided before it launched
     * This should occur in [startAuth() in our auth hook](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/9cdb079791cabdc920b1f0460b084c122a285341/VAMobile/src/utils/hooks/auth.tsx#L20) 
* parameter `login_start_biometric` (string) 
     * If event was triggered by biometric condition above, then set value = `true`, else `false`.
       
- [ ] `vama_login_success` 
* We want to modify this to capture the initial point of the user successfully being able to access their personal information after each start of the log-in process (from the user's perspective).
* The event should fire when:
     * The **first time** an API call to the /user endpoint successfully returns the users personal information **following** `vama_login_start` (after it is modified as described above).
     * Make sure this isn't firing for subsequent calls to the /user endpoint if they are not preceded by the new occurrence of the above criteria.
       * Should be possible in the [getProfileInfo redux action]() and logging the event only if `screenID` is sync screen.  Sync screen will also need to be added to [Screens.ts](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/07c91b942c1dcd060a7200b342a13a0520885fe8/VAMobile/src/store/api/types/Screens.ts)

- [x] **Confirm that these events aren't firing anywhere else**

**Comment by TKDickson** [comment]
Removing my (auto)assignment from this ticket - analytics still can't be tested pre-release
