### ISSUE TITLE
Bug - Sev 3 - User Feedback: Secure Message notifications

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6253]
Sent: Wednesday, June 21, 2023 5:05 PM
To: VA Flagship Mobile <VAFlagshipMobile@va.gov>
Subject: [EXTERNAL] Secure message notifications

I continue getting new secure message notifications even after I've opened the app and read it. I get multiple of these.

**Comment by bischoffa** [comment]
attempting to pull this into next sprint for FE to investigate though its not yet been scrubbed by QA

**Comment by bischoffa** [comment]
@timwright12 @narin  CC @jennb33  Can you please add a size to this ?

**Comment by timwright12** [comment]
gave it a 2, but this is just someone reaching out to VANotify. If we find a bug on our end it will need to be repointed

**Comment by bischoffa** [comment]
@timwright12 is this front end or backend? There is no tag right now and likely not being looked at by either.

**Comment by timwright12** [comment]
It's neither at the moment since it's just asking VANotify a question. It can be frontend backend or product, whoever has capacity

**Comment by bischoffa** [comment]
@timwright12 Binny and team only look at tickets with Front-End label on it. I think Jayson does the same things if it has Back-end label.   
  
Without a label ticket won't be picked up by engineering

**Comment by jperk51** [comment]
I can handle it

**Comment by jperk51** [comment]
Slack thread: https://dsva.slack.com/archives/C01CSM3EZGT/p1695750233869579

**Comment by timwright12** [comment]
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6926

**Comment by bischoffa** [comment]
@timwright12 Can you add some more details as to what 6926 is in relation to this ticket?

**Comment by jperk51** [comment]
BE work on this is done unless #6926 or other future investigations result in new evidence. I'm good to close this ticket, but in the meantime I'm going to unassign myself

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by bischoffa** [comment]
@timwright12 follow-up on my prior question. any concerns with work being done in another ticket and this one being closed?   
  
Currently ticket is In-Progress with no assignee, moving to blocked until Tim's response.

**Comment by bischoffa** [comment]
@timwright12 follow-up on my prior question. any concerns with work being done in another ticket and this one being closed?   
  
Currently ticket is In-Progress with no assignee, moving to blocked until Tim's response.

**Comment by timwright12** [comment]
@bischoffa no concerns, we can just link up to this one for historical reference

**Comment by bischoffa** [comment]
Closing ticket
