### ISSUE TITLE
Storybook – Figma integration

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6275]
## Description
Add Figma integration to Storybook so that we can display Figma designs in our documentation

## Definition of done
- [ ] Add [Designs add-on](https://storybook.js.org/addons/storybook-addon-designs) to project
- [ ] Discuss with design how best to present Figma designs in a component (iframe, embed, link)

**Comment by narin** [comment]
@jessicawoodin When you get a chance, can you please take a look at [this demo](https://storybookjs.github.io/addon-designs/?path=/story/docs-figma-examples--embed-file) of what a Figma integration into Storybook could look like? Some follow-up questions:
1. Would this add-on even be useful?
2. Which variation of the examples seem most useful to you? (File, Frame, Private File, Prototype)

**Comment by jessicawoodin** [comment]
Thanks, Narin! I could see this being helpful for any visual QA of components in Storybook. I think it's also helpful to have Storybook and Figma both linking to each other so it's easy for us to reference both of them.

I think **embedding frames** is the best option. That's how we currently have our components set up in Figma. I'm seeing two potential frames we could link to and included their links below. Do you want to try them out as part of this ticket and see which works best?
- [the master component](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=578-273&mode=design&t=U1dy2k77F27RgTAf-4)
- [component overview](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=7332-11330&mode=design&t=U1dy2k77F27RgTAf-4)

Also, I tried to add the Storybook plugin in Figma. It's asking me for my team's Chromatic URL. Is there a way you can add me to our Storybook so I can see how it might work in Figma?
