### ISSUE TITLE
Design System Automation – Generate release

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6299]
## Description
Publishing a new version of a package to NPM currently requires several manual steps and some environment setup. We are also currently missing some common elements of a release process such as git tagging and changelogs. Git tags will allow us to keep historical snapshots of what code went out in each release and changelogs will provide our users with updates on enhancements, bug fixes, and any potential breaking changes.

As we continue to publish new versions of our packages and develop more critical components that external teams rely on, it’s important to have a repeatable process that includes the features mentioned above. 

## Definition of done
- [ ] Workflow inputs:
  - Select which package to publish
  - Select major, minor, patch, alpha, beta version to bump ([semantic versioning)(https://semver.org/))
- [ ] Check NPM registry to determine latest version and what version to bump to
- [ ] Increment the specified packages’s version in package.json and publish it to NPM
- [ ] Create git tags to correspond with each publish (e.g. components-v0.22.1)
- [ ] Automatically generate a changelog for the published package based on PRs, labels, bugs, closed issues using an existing GitHub Action such as [release-change-log-builder](https://github.com/marketplace/actions/release-changelog-builder)
- [ ] Commit the tags, changelog, and version bump in package.json to main branch

**Comment by bischoffa** [comment]
@ajsarkar28 was this pulled out from the sprint? if so can you remove the sprint tag and update it to the appropriate sprint?

**Comment by timwright12** [comment]
One thing we should look into here is that we're going to have multiple packages released from this repo (mobile-component-library, mobile-linting, mobile-tokens). I'm not sure github supports multiple release streams like that, but it's something to consider with the strategy.

**Comment by bischoffa** [comment]
Carryover ticket from Sprint 81 into Sprint 82

**Comment by bischoffa** [comment]
Identified as carryover again into next sprint.

**Comment by timwright12** [comment]
@bischoffa you can exclude the mobile-platform label from carryover reporting they're using a different ticketing style. @kellylein has the details.

**Comment by bischoffa** [comment]
@timwright12 @kellylein before doing that can you please provide details as to why platform is excluded and what platform is doing instead?  

CC: @jennb33 @Hallm13

**Comment by narin** [comment]
Drafted automation requirements and gathered feedback in [Google Doc](https://docs.google.com/document/d/1tm1Woe4MZohvuJF8D1kmWz_sLb8tEz6ex7xZQ3G55S0/edit). Copy pasted below:

## Automated Release Process


## Background

Publishing a new version of a package to NPM currently requires several manual steps and some environment setup. We are also currently missing some common elements of a release process such as git tagging and changelogs. Git tags will allow us to keep historical snapshots of what code went out in each release and changelogs will provide our users with updates on enhancements, bug fixes, and any potential breaking changes.

As we continue to publish new versions of our packages and develop more critical components that external teams rely on, it’s important to have a repeatable process that includes the features mentioned above. 


## Release Cadence

Initially, releases will be manual and triggered via a workflow dispatch in GitHub Actions. In the future we’ll likely introduce some sort of formal review process before publishing a new version. GitHub Actions makes it easy to schedule automatic releases as well if we decide to release on a recurring schedule (e.g. every sprint).


## Proposed Release Automation

Using a GitHub Workflow Dispatch comprised of custom scripts and existing GitHub Actions:



1. Workflow inputs:
    1. Select which package to publish
    2. Select major, minor, patch, alpha, beta version to bump ([semantic versioning](https://semver.org/))
2. Check NPM registry to determine latest version and what version to bump to
3. Increment the specified packages’s version in `package.json` and publish it to NPM
4. Create git tags to correspond with each publish (e.g. `components-v0.22.1`)
5. Automatically generate a changelog for the published package based on PRs, labels, bugs, closed issues using an existing GitHub Action such as [release-change-log-builder](https://github.com/marketplace/actions/release-changelog-builder)
6. Commit the tags, changelog, and version bump in `package.json` to `main` branch

**Comment by narin** [comment]
Created workflow and tested by incrementing each version bump type and package. Closing out.

- [GitHub Actions Workflow](https://github.com/department-of-veterans-affairs/va-mobile-library/actions/workflows/publish.yml)
- [Connected PR](https://github.com/department-of-veterans-affairs/va-mobile-library/pull/28)
