### ISSUE TITLE
Design System Automation – Publish to NPM

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6300]
## Description
Whenever we create a new release in GitHub, we should also publish this new version to NPM.

[See VADS's GitHub Action Workflow](https://github.com/department-of-veterans-affairs/component-library/blob/main/.github/workflows/publish.yml)

## Definition of done
- [ ] Creating a new release in GitHub should trigger the publishing of the new version of the library to NPM

**Comment by timwright12** [comment]
I opened this PR to do some testing https://github.com/department-of-veterans-affairs/va-mobile-temporary/pull/12

I can keep poking at it, but if this comes up in the sprint before I can finish, someone feel free to take it over.

**Comment by narin** [comment]
Publish action is now live on `main`.  Example run: https://github.com/department-of-veterans-affairs/va-mobile-temporary/actions/runs/6028299904/job/16355317417

Can be triggered manually or when a release is published. As of right now, version numbers in the package.json need to be incremented manually. Closing out.
