### ISSUE TITLE
CU - Enable Direct Deposit Demo Mode Data

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#6317]
## Proposed Change

Demo mode currently does not show any direct deposit data or let you easily access the screen to update said data. Demo mode should match the app as much as possible.

## Why Should We Prioritize?

Demo mode should match the app as much as possible.

## Coding Time Estimation

3
	
## Testing Considerations

Ensure Demo mode direct deposit functions and doesn't actually do anything and edits did not effect actual direct deposit edits in staging.

## Checklist
[ ] Add the front-end label tag

[ ] Attach to the Frontend epic for engineering initiatives

**Comment by alexandec** [comment]
I enabled Direct Deposit in demo mode a while back as part of [this PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6335) and it's been working fine. If any additional changes are needed, we could use this ticket to implement them. Would need to update the ticket with the specific changes needed in that case.

**Comment by Sparowhawk** [comment]
I guess this ticket can be closed as there is a e2e bug ticket #8051 that is to fix the react query migration for e2e tests as it currently works in demo mode
