### ISSUE TITLE
Sprint 0: User properties & parameters for Firebase Analytics

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6320]
See #4160 for background discussion.

**Problem statement to work in a Sprint 0:**
* We currently have Firebase audience and audience dimensions set up that are not documented.
* Based on what we know of how some of them are set up, it's not clear that they serve any purpose.
* Specifically for "Accessed Major Feature Users, " what is the value of a lifetime tracking of user engagement with a feature and how should that be defined?

**Comment by OVezeamama** [comment]
Closing this ticket. Similar working is being done to create data dictionary.[ #9283](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9283)
