### ISSUE TITLE
UX Bug Review of 5585 - Sev - 3 - SM - Empty Folders Situation

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6331]
## Purpose: 

- UX to review bug ticket and determine what the desired result we want to resolve the ticket
- Note focus should be on items we can do today vs adding new enhancements / changes
    - identify what we can do today and add that in the desired behavior of the bug ticket
    - if additional ideas / enhancements come out then create a separate ticket to capture that

## Bug Details
- Review Bug ticket [5585](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5585) for details and pictures
- Visually, if you navigate to an empty folder, its not a pretty sight.

**Comment by bischoffa** [comment]
No ETA on prioritization, dependent on bugs and other priorities. Will review each sprint to see. if no movement then no prioritization.

**Comment by brea11y** [comment]
We may want to discuss this issue with @DJUltraTom when he gets back from PTO. I'm not seeing an issue or a bug here and the screens appear how I would expect them to look. I also briefly chatted with @kidlaurenpeace about this to get her thoughts and she didn't see an issue here either.   
  
After talking to Lauren, I then compared the in-app screens with what is being shown on web (screenshots below) and it appears that we are displaying empty folders very similarly. I'm closing this for now, as it doesn't appear to be a bug, but we could always reopen if we get additional insight into why this is an issue once Tom is back.

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/2e014b5d-cc5b-4d51-b1f0-d3983217aacc)

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/76dacaed-f164-43e1-a6e3-19c0c98bd0a0)
