### ISSUE TITLE
App global: Delete weblink to VA Covid-19 updates

### ISSUE THREAD

**Issue by rachelhanster** [department-of-veterans-affairs/va-mobile-app#6338]
As a veteran, I no longer see and click "VA covid-19 updates" weblink(s) from the app.

**Comment by rachelhanster** [comment]
Covid uptick in summer 2023, hold this ticket to later.
2024 June: add initiative to backlog.

**Comment by Sparowhawk** [comment]
@ala-yna this would be fairly easy to do. I pointed it and it just needs to be prioritized.

**Comment by rbontrager** [comment]
Verified that the covid-19 updates have been removed from the home and health screens.  Approved by QA.

**Comment by ala-yna** [comment]
Will be included in the [July 16th release](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8985)
