### ISSUE TITLE
Analytics for Deep Linking

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6355]
The following new analytics events and parameters are required to measure the efficacy of the MVP of deeplinking in Secure Messaging:

- [ ] `vama_notification_click`: triggered when a user clicks any notification
  - [ ] parameter `notification_url` the link from the notification

**Comment by g-opzt** [comment]
@StacyB2023 Removed second event as updates to Implementation ticket mean we are now landing people directly on the message. Has been moved to #6393 as it is still part of regular SM analytics. 

I have added an open question to discuss at handoff which is essential to making sure we can measure that folks actually could read the message once the deep link was clicked.

**Comment by StacyB2023** [comment]
@g-opzt Thanks! And ok sound good. Let's clarify in handoff.

**Comment by g-opzt** [comment]
Outstanding question answered on FE; I'll be reviewing #6394 to ensure that we're all set to know when API fails happen while trying to use a deep link to take a user to a SM. Our recently added event vama_error should cover this; if not, we'll bring #6394 back to handoff next week and get that covered.

**Comment by theodur** [comment]
@g-opzt I noticed the AC says `when a user clicks any notification`. Just want to confirm whether this should include all notifications, even ones that don't have a URL? If we track this for notifications without a URL, the `notification_url` will be `undefined` for those.

**Comment by g-opzt** [comment]
Hmm, could we add another parameter that captures some kind of identifying feature for this? Do they have a name that could be put into a different parameter?

**Comment by g-opzt** [comment]
IF it is a large lift or not readily available, just let me know and I can open a follow up ticket and the situation you described above will be fine for now.

**Comment by theodur** [comment]
That's a good question. Currently, the only identifying attribute that we can count on being there from the notification is the title. We only have 2 push notifications setup in the app right now, and that's for SM and appointments. The title for appointment notifications is `VA Appointment Reminder`, so we could capture that in a separate parameter called `notification_title`.

Ideally moving forward, push notification that support deep linking should have the URL present, which isn't the case for the appointments yet, but I imagine eventually all notifications in the app will have a URL associated with them, even if it's just landing the user to the home screen

**Comment by g-opzt** [comment]
Got it; for now, let's leave it as is with the undefined value if the URL is missing. We can re-evaluate at a later point. Thanks!

**Comment by DJUltraTom** [comment]
No QA required or possible.... and binny already merged so , ya know.... closing.
