### ISSUE TITLE
QA Test Plan - RX List and Details Update

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6379]
**Description:** 
As QA, I want to create a test plan for the RX changes in order to validate the functionality works as expected 

**ACs**

- Testing [7434](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7434)
- Testing [7391](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7391)

**Notes**
- [Figma prototype ](https://www.figma.com/proto/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?page-id=1499%3A15245&type=design&node-id=1499-15407&viewport=812%2C486%2C0.31&t=gjAhJIZN0xMTxh98-1&scaling=min-zoom&starting-point-node-id=1499%3A15407)
- [Figma Prototype instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/medication/Design/List%20enhancements%20Q4%202023.md)

**Comment by bischoffa** [comment]
@DJUltraTom when you get a chance can you size this QA Test Plan for the RX List Sort work? If you have any questions feel free to reach out to me on the feature.

**Comment by rbontrager** [comment]
Test cases can be found [here](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=13043).  They were reviewed and signed off on [7355](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7355). Closing this ticket.
