### ISSUE TITLE
Add universal analytics for API calls

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6394]
**Goal**: to analyze when things aren't loading for a user because of API fails. This is needed to be able to distinguish between task success/fail when the task is being able to view information on a particular screen that is dependent on the API call working. Ex. User opens Appointments screen but it doesn't load because the API call did not return 200. 

This is connected to "Sprint 0: Error documentation" #6072

**Event**
- [ ] vama_api_call: Any time an API call is made, log the following event with parameters:

**Parameters**
- [ ] api_endpoint
- [ ] type: get, post, put, etc.
- [ ] response: response code returned by the call

**Comment by g-opzt** [comment]
I will review the new event vama_error to see if this covers what was needed here. If it does, we'll close this out. If not, I'll revise and return this ticket to hand off.

**Comment by OVezeamama** [comment]
@theodur was this issue resolved?
