### ISSUE TITLE
Backend: Correct issues with Lighthouse document uploader

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#6395]
#### Description
Investigating and fixing errors with uploading a document with lighthouse in staging

#### Dependent Issue

[department-of-veterans-affairs/va-mobile-app#4746](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/4746)

#### Test users

vets.gov.user+54@gmail.com

## Acceptance Criteria

- [ ] ...
- [ ] It logs its progression through the 'happy path' or helpful error details.
- [ ] I tested the feature on staging and could demo it if asked.
- [ ] Public Ruby API methods have [Yardoc](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md) comments.
- [ ] The [OpenAPI](https://swagger.io/specification/) documentation is up-to-date.

**Comment by aherzberg** [comment]
Devops is still in process of creating the new lighthouse bucket () in the mean time, we tested it with the evss bucket and found this error http://sentry.vfs.va.gov/organizations/vsp/issues/217955/?environment=staging&project=3&query=transaction%3A%22Sidekiq%2FLighthouse%3A%3ADocumentUpload%22&statsPeriod=1h . It may be that the new upstream BGS service is returning multiple filenumbers while the LH endpoint expects one. Kevin Duensing who added that BGS service upstream call is taking a look at it today to see if they know what's going on.

**Comment by aherzberg** [comment]
Pinged Devops on creating the new lighthouse bucket again: https://dsva.slack.com/archives/CBU0KDSB1/p1690915671133149. After fix has been merged and tested with old bucket, endpoint is still giving an error so will prioritize looking into that today.

**Comment by aherzberg** [comment]
this will carry over to next spring and should be pointed an 8

**Comment by aherzberg** [comment]
closing and continuing with https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6496
