### ISSUE TITLE
Automation - Add slack notification on Release Ticket creation

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6398]
# Automation Ticket

## Type of Change
- [ ] Update existing automation
- [x] Add new automation functionality
- [ ] Fix automation bug

## What systems/scripts are changing?
- [x] Git Hub Actions
- [ ] CircleCI
- [ ] Fastlane
- [ ] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

Add a slack notification when a release ticket is created in case people miss the GitHub assignment email.

## Acceptability Criteria

- [ ] Slack bot notifies #va-mobile-app channel upon Release Ticket creation

**Comment by timwright12** [comment]
completed on another ticket
