### ISSUE TITLE
Add show contact info endpoint

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#6401]
The mobile app needs to fetch contact info without the user endpoint. See the user controller to see how it's currently done.

Acceptance Criteria:
- returns all contact info fields that are currently returned from user show endpoint
- this will return an empty result if the user doesn't have a `vet360_id`. Ensure that this case is tested and documented
- request specs
- openapi documentation

**Comment by bischoffa** [comment]
Added label as this ticket is in progress and did not have a sprint tag on it @ajsarkar28

**Comment by jperk51** [comment]
Well these were planned for this sprint and were accounted for in the capacity planning, so I'm going to remove the tag.
