### ISSUE TITLE
Modify facilities info controller to specify whether the facility is one of the patient's treatment facilities

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#6402]
The user endpoint currently returns a list of the patient's treatment facilities. This data should be fetched separately. The facilities info show endpoint already returns a list of the patient's facility data, but it also includes child facilities. We can make this endpoint work for our purpose if we specify in the response whether a facility is in the user's va_treatment_facility_ids.

Facilities info is not currently in use. It was implemented for appointment scheduling, which was iceboxed. We can also add a "include_children" query param. This will allow us to exclude children for now for performance reasons while still allowing us to easily add them again later if needed. 

Acceptance Criteria:
- facilities info specifies whether it is in the patient's va_treatment_facility_ids
- add query param for including children
- change service object code to use new facilities cache in the mobile facilities service. 
- request specs
- openapi documentation

**Comment by jperk51** [comment]
Was planned for in sprint planning and capacity. Sprint tag was just missed.

**Comment by jperk51** [comment]
@kpethtel let me know how much carry over you expect on this

**Comment by jperk51** [comment]
Carryover 3. The ticket Kris flexed to for the FE took longer than expected.

**Comment by kpethtel** [comment]
I ended up doing this a bit differently from how it was described in the ticket due to some incompatibilities between the existing and new code. I made a new endpoint altogether instead and couldn't use the cache. I talked to VAOS about my caching idea and they said they'd look into it.
