### ISSUE TITLE
Add authorized services endpoint

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#6403]
The mobile app needs to fetch a list of the user's authorized services without the user show endpoint.

Acceptance 
- returns a list of all services. The current design has a list of authorized services and a separate list in the meta of all services. Let's combine the two in order to avoid the meta. It can return a list of all available services and specify which the user is authorized to use.
- request specs
- openapi documentation

**Comment by bischoffa** [comment]
@ajsarkar28 ticket is being worked on but not tagged with this sprint so looks like it was pulled in post planning so tagging it and adding sprint

**Comment by jperk51** [comment]
Was planned for in sprint planning and capacity. Sprint tag was just missed.
