### ISSUE TITLE
Create a way to collect user feedback

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6428]
### Description
As part of MVP, we'd like to create a way to collect feedback from users of the design system. For MVP, these will only be internal users.

### Steps
- [ ] Research how other teams collect user feedback about design systems
     - [VA Platform feedback](https://airtable.com/apptZUIOgNqO3mS4p/shromU8aG2H95jCvO)
- [ ] Draft options/recommendations
- [ ] Review with platform team
- [ ] Implement decisions

**Comment by timwright12** [comment]
Could this be an issue template in the the MDS repo?
