### ISSUE TITLE
Appointment Experience - SMS Alert - To Open App or Download App 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6432]
### User Story: 
As a Veteran user of the Flagship Mobile App going through the appointment experience, when I receive an SMS, I want to be able to click the link in the SMS so that it will open up the app or ask me to download the app, in order to use the flagship app for the next steps in the appointment experience 

### Notes: 

- Shared by Rachel via [Slack 8/1 ](https://dsva.slack.com/archives/C05B7UZP57G/p1690912024285489)
- [Slack thread](https://dsva.slack.com/archives/C022AC2STBM/p1690908224286089) related to this request 
- This is not MVP and is not a blocker for MVP release - if there is capacity great - focus is on getting the functionality of appointments out there and can do discovery later

**Comment by TKDickson** [comment]
This could probably be closed, given that the flagship app team is no longer implementing this feature @ala-yna
