### ISSUE TITLE
BUG - Sev 2 - BE - Remap Lighthouse 400 error to 500 Error for Direct Deposit routing numbers

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#6435]
## What happened?
With the EVSS to Lighthouse migration some error response codes have changed.
Where we would previously get a 500 error response we are now getting a 400 error. This ticket is to address remapping that error until we make some bigger changes around validating bank routing numbers in the app before the API call.

## Specs:

- Device: all
- OS: all
- User Account: lighthouse enabled (EG +226 )
- Accessibility State: n/a

## Steps to Reproduce

Sign into a user account that is flagged to use Lighthouse (EG: +226)
navigate to: Payments > Direct Deposit information 
edit the Direct deposit information with an invalid routing number.
Observe the error response 

## Desired behavior
user should have an informative screen on how to correct the incorrect information in their form.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
Sev 2

Sev 2

## Screen shot(s) and additional information

<details>
  <summary>500 Error from EVSS</summary>
  <{
	"errors": [{
		"title": "Internal server error",
		"detail": "Internal server error",
		"code": "500",
		"source": "EVSS::PPIU::Service",
		"status": "500",
		"meta": {
			"messages": [{
				"key": "payment.accountRoutingNumber.invalidCheckSum",
				"severity": "ERROR",
				"text": "Account Routing Number contains invalid checksum"
			}]
		}
	}]
}>

</details>
<details>
  <summary>400 Error from Lighthouse</summary>
  <{
	"errors": [{
		"type": "https://api.va.gov/direct-deposit-management/errors/bad-request",
		"title": "Bad Request",
		"status": "400",
		"detail": "Invalid routing number checksum.",
		"instance": "5bcddf67-2da0-11ee-aa50-81ba2d459e15",
		"errorCodes": [{
			"errorCode": "payment.accountRoutingNumber.invalidCheckSum"
		}],
		"code": "400"
	}]
}>

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by jperk51** [comment]
https://adhoc.slack.com/archives/C02N65QRRB7/p1690589258645149

**Comment by jperk51** [comment]
Was planned for in sprint planning and capacity. Sprint tag was just missed.

**Comment by DJUltraTom** [comment]
Current mapping is showing a 500 header response however the JSON package is different and the user is having the same result of "App is not working" with a retry button:

Using Lighthouse enabled user:
`{
	"errors": [{
		"title": "Bad Request",
		"detail": "payment.accountRoutingNumber.invalidCheckSum: Invalid routing number checksum.",
		"code": "cnp.payment.routing.number.invalid.checksum",
		"source": "Lighthouse Direct Deposit"
	}]
}`

Using EVSS user:
`{
	"errors": [{
		"title": "Internal server error",
		"detail": "Internal server error",
		"code": "500",
		"source": "EVSS::PPIU::Service",
		"status": "500",
		"meta": {
			"messages": [{
				"key": "payment.accountRoutingNumber.invalidCheckSum",
				"severity": "ERROR",
				"text": "Account Routing Number contains invalid checksum"
			}]
		}
	}]
}`

**Comment by DJUltraTom** [comment]
moved back to "In progress and pinged @Tonksthebear with information in slack

**Comment by DJUltraTom** [comment]
Yes! Verified the correct error is showing up now!
QA validates and approves this ticket
