### ISSUE TITLE
BUG - Sev 3 - All - Snackbars received in landscape mode are cut off when rotated to portrait mode

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#6444]
## What happened?
In landscape mode perform a task that  results in a snackbar (EG: changing/saving gender identity, sending a message), rotate to portrait mode and observe the snackbar does not resize to a functional size

## Specs:

- Device: ipad mini, google pixel 4a
- OS:
- User Account: N/a
- Accessibility State: N/A

## Steps to Reproduce

In landscape mode perform a task that results in a snackbar (EG sending a message, changing preferred gender)
receive the snackbar notification
rotate the screen to portrait mode
observe the snackbar

## Desired behavior

Snackbar should resize to fit display.
## Acceptance Criteria

tbd
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

![IMG_0163.PNG](https://images.zenhubusercontent.com/610aca11d461c11ca8e7e65e/ee5360f9-d6bf-47e6-92b4-94834c874b8b)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)
-

**Comment by theodur** [comment]
@DJUltraTom I tested this on both iOS & Android virtual devices and physical devices and I can't seem to reproduce the issue 🤔. I'm wondering if you're still seeing this behavior on the latest build?

**Comment by jennb33** [comment]
@DJUltraTom this ticket needs your attention, as @rbontrager and @theodur can not reproduce the error. Moving this ticket to Sprint 80, for when you are back in office.

**Comment by DJUltraTom** [comment]
Unable to reproduce with current RC builds on any of my devices. closing as "cannot repro"
