### ISSUE TITLE
BUG - sev 3- Android - Claims file upload warning message missing text on android

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#6445]
## What happened?

On android the warning box before you upload a file or photo supporting a claim is missing text.

## Specs:

- Device: google pixel 4a
- OS: adnroid
- User Account: judy.morrison
- Accessibility State: n/a

## Steps to Reproduce

navigate to "Benefits > Claims > Claims History > (select a claim with an upload available) > File request 
select the blue (open) file request and go through the flow to either take a picture or attach a file.
Select the document type and check the required check box
Tap submit file
observe the "are you ready to submit your file?" messaging

## Desired behavior

Information should be complete

## Acceptance Criteria

TBD, but likely match the messaging that is present on iOS

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

![Screenshot_20230802-172746.png](https://images.zenhubusercontent.com/610aca11d461c11ca8e7e65e/f346a3c6-842d-4489-a9a2-694fb7ddc08f)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by theodur** [comment]
I reproduced the steps, but I'm not seeing any missing text or discrepancies between iOS and Android. Can you confirm whether you're still seeing this issue on the latest build @DJUltraTom?

Here's what I'm seeing on both platforms:
<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/53e681c4-b893-45cc-8266-dd86e0de3c93" width="49%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/7676815a-442d-4d65-af96-34c6e9517db3" width="49%" />

**Comment by jennb33** [comment]
@DJUltraTom this ticket needs your attention, as @rbontrager and @theodur can not reproduce the error. Moving this ticket to Sprint 80, for when you are back in office.

**Comment by DJUltraTom** [comment]
Able to reproduce still on my google pixel, screenshot of my text settings below
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFBNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2fcb0e54e6a1e8569b2e4052c4be9faedf515be3/Screenshot_20230922-112900.png)

**Comment by theodur** [comment]
I was able to reproduce the issue and opened a [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6843) as a workaround. This is actually a bug in the [react-native-action-sheet](https://github.com/expo/react-native-action-sheet) library. Seems like others are also experiencing the text cut off when bold text is enabled. There's no word on when this is expected to be fixed, but the workaround in my PR should be good enough for now

**Comment by bischoffa** [comment]
Adding Sprint 81 as the ticket was not closed out in 80. Carryover work.

**Comment by DJUltraTom** [comment]
verified issue no longer persists!
Qa approves!

**Comment by DJUltraTom** [comment]
Validated looking good on the nightly QA build, closing as deployed
