### ISSUE TITLE
BUG - Sev -3 - Android - Storybook isn't running on Android with yarn

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6465]
## What happened?

The `yarn android` command to run storybook isn't working. There seems to be an incompatibility with the version of yarn we're using as building the app with npm works fine. 

## Steps to Reproduce

1. Clone the repo
2. Run `yarn` with yarn 3.6.1 to install dependencies
3. Run `yarn android` 

## Desired behavior

The app should launch on Android without errors

## Acceptance Criteria

- [ ] Storybook should be viewable on Android

**Comment by bischoffa** [comment]
Marking it as the lowest Bug ticket size of Sev - 3 to keep with bug consistency. Ticket not scrubbed as its flowing through platform work and not bug work

**Comment by narin** [comment]
Storybook is now functional on Android. Closing out.
