### ISSUE TITLE
Add Storybook links to segmented control documentation

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6483]
When the segmented control documentation was published to the doc site, a Storybook link was not ready. In this ticket, we need to:

- [x] Add link to [Storybook](https://department-of-veterans-affairs.github.io/va-mobile-library/) embed in "Examples" section
- [x] Add link to Code Usage section
- [x] Update how links to Figma display
- [x] Publish documentation

**Comment by timwright12** [comment]
Link to the published documentation: https://department-of-veterans-affairs.github.io/va-mobile-temporary/
