### ISSUE TITLE
Personalized Home Screen: UX Strategy

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6500]
- [x] Document UX strategy for implementing a personalized home screen that outlines Business + User Assumptions, the problem being solved, high level ideation, and a product & design iteration framework
- [x] Revise based on PM collab, Greta & Liz feedback
- [x] Post to Github

**Comment by htcollier** [comment]
Work in progress draft: [WIP Design Strategy Worksheet: VA Mobile App - Personalized Home Screen 2023 ](https://docs.google.com/document/d/1-nAN6VTg2dtKSv4UXIOlMZxdr8pWmA0l/edit#heading=h.n8e3xxx5wfij)

**Comment by htcollier** [comment]
Folded in PM feedback & posted to github: [VA Mobile app: Personalized Home Screen Design Strategy Worksheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/ux/personalization-homescreen-design-strategy-worksheet-2023.md)
