### ISSUE TITLE
Discovery: Personalized Home Screen content/data

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6502]
In order to inform the MVP feature requirements, we want to understand what content/data we have in the app (or MyVA) that we could show on the personalized home screen.

- [x] Conduct desk research to investigate possible content/data for personalized home screen 
- [x] Document existing content/data 
    - [x] Check w feature SMEs for completeness and accuracy of list, update based on feedback
       - [ ] ~~If necessary, plan activity and create any necessary artifacts for an ideation exercise with SMEs to determine data that could potentially be populated on a personalized home screen~~

See [Personalization work planning](https://www.figma.com/file/fQfBPKtLWbwEnPIFeaBaXf/Personalization-work-planning?type=whiteboard&node-id=0%3A1&t=0j9zI96bitis1mXW-1) for overall workplan.

**Comment by htcollier** [comment]
Current VA mobile app & MyVA content pieces documented in Figjam: [Personalized Data - Discovery - VA Mobile](https://www.figma.com/file/NHnXpvkhBeqvUQ6LIqMGqd/Personalized-Data---Discovery---VA-Mobile?type=whiteboard&node-id=0%3A1&t=rOMrbyhfhmg0eJ2d-1)

**Comment by htcollier** [comment]
1. Folded in new info from MyVA onsite notifications documentaiton
   - [Onsite notification inventory/ideas](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/product/onsite-notification-inventory.md)
   - [MyVA Action Items - Included in MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/onsite-notifications/2023-scaling-onsite-notifications/product/onsite-notification-inventory.md)
2. Added a [Personalized content by High-level User Type (mobile & MyVA)](https://www.figma.com/file/NHnXpvkhBeqvUQ6LIqMGqd/Personalized-Data---Discovery-%26-Classification--VA-Mobile?type=whiteboard&node-id=102-477&t=r0TN6nNxq2dMkdqt-4) to board to get a better sense of variable v fixed content & zero states.
3. Reached out to VA mobile app Health (@MekoHong) & UX team for [confirmation of possible personalized data](https://adhoc.slack.com/archives/C01NC7PN4A0/p1693330218252239?thread_ts=1693236655.082279&cid=C01NC7PN4A0) currently included in the board. Have not yet heard back, so I'm closing out this ticket with data unconfirmed (will update as we get feedback from them).
