### ISSUE TITLE
Research Documentation: add study signup template

### ISSUE THREAD

**Issue by lstraghalis** [department-of-veterans-affairs/va-mobile-app#6504]
As a researcher on the mobile app team, I want to utilize existing research study templates to make running a new research study easy and efficient.

## Acceptance Criteria
  

-  [x] Add research study signup sheet to the documentation site
-  [x] Add usage guidelines to the documentation site

## Notes & Open Questions

- Dependencies/Roadblocks: none
    - Any internal/external dependencies? none
    - Test accounts needed? none
- Does this require QA? nope
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by drjecker** [comment]
Updated info can be found on the [doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/Foundations/Research/)
