### ISSUE TITLE
Preliminary Measures of Success for Personalization & Personalized Home Screen 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6506]
* Outline potential measures of success for a Personalized mobile app & Personalized home screen based on the Outcomes in the Personalization Kickoff [deck](https://docs.google.com/presentation/d/1pIk7hEV0w18namfZsSaCAiUHlFyC7uD1Lfzud4100r0/edit)

**Comment by g-opzt** [comment]
Holly shared [Design Strategy Worksheet for the Personalized Home Screen](https://docs.google.com/document/d/1-nAN6VTg2dtKSv4UXIOlMZxdr8pWmA0l/edit#heading=h.30j0zll) to help prep for this work. Waiting for meeting invite to prioritize when I will review these artifacts.

**Comment by g-opzt** [comment]
Meeting tomorrow mid-day so this will be prioritized for review in the morning.

**Comment by g-opzt** [comment]
Call held today where we completed step 1 of the data project design process in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1692806168671/522ac14b0a665b372c043880b0c8baa66a0348f4?sender=u955e947bb617e3eae45a5638) by defining the measurement motivation, restrictions, rewards, etc. A second call will be held on Friday to finish step 2, which is planning the research questions. Once this step is complete, there will be a data project motivation touchstone with a list of preliminary research questions documented. These will be living documents that will require further revision in future sprints as the exact design of the product changes is still to be determined and alignment will have to be reached about the design of the overall experiment.

**Comment by g-opzt** [comment]
Resized to reflect actual capacity spent.

**Comment by g-opzt** [comment]
Summary of discussions shared with Ameet and Holly in[ Google Docs.](https://docs.google.com/document/d/1xa5d114xMp6Ls1x2KR904LUoAQ7tDGKZBiijE8MJRKc/edit) Attaching PDF here of the draft as shared with them; it is a living document that is meant to be updated/refined as the project takes shape and measurement possibilities are clearer. [[Data Project Plan] Personalized Home screen - Google Docs.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDVFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--167aa01a389f6b3db319f70526d072efc01d28c7/%5BData%20Project%20Plan%5D%20Personalized%20Home%20screen%20-%20Google%20Docs.pdf)
