### ISSUE TITLE
In-App Recruitment - Analytics

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6518]
Review in-app recruitment screens and write ticket for front-end implementation of analytics to track task success, utilization, and failures as possible.

**Comment by g-opzt** [comment]
@bischoffa Dylan reached out to me with questions about what analytics should go on the inAppRecruitment screen but we never had a ticket for this. I'm making this one but would like your input on what the priority is here as I don't have capacity to pick this up this sprint based on current sprint plan.

**Comment by bischoffa** [comment]
See ticket 6004 - closing this one
