### ISSUE TITLE
Analytics for Letters & Documents task: Review a letter

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6530]
### Add new event: vama_letter_select
- [ ]  `vama_letter_select`: Logs when a user clicks a letter type on LettersList. Includes parameter:
  - [ ] event_param.key = `letterName` 
  - [ ] event_param.value.string_value = what type of letter the user clicked on LettersList. Ideally this would be 1 to 1 with the parameter of the same name on `vama_letter_download`

#### Context
The task to be measured is: As an app user, I want to be able to view my letters from the VA.
- Task starts (attempts): When the user clicks a letter type on the "Review letters" screen.
- Task ends (succeeds): When the user is able to view the PDF of the letter.

**The goal is to be able to measure both attempts and successes by:**
* Users: total unique users starting and successfully completing the task
* Instances: total times letters were viewed, which would include if a user views the same letter more than once.
* Distinct letters: How many distinct letters were viewed, so counting each letter type once per person

Current analytics are sufficient for users and instances, but not distinct letters.

I can track that a user has gotten to the task start point because they will log a `screen_view` event of either `GenericLetter` or `BenefitSummaryServiceVerificationLetter` with the prior screen viewed being `LettersList`. Which type of `GenericLetter`, however, can't be seen in the data until the user logs the success event `vama_letter_download` in the parameter `letterName`. I need this same identifier when the user clicks one of the letter options on `LettersLists` to be able to calculate attempts per distinct letters.

**Comment by Sparowhawk** [comment]
@bischoffa this one shouldn't be blocked, it is blocking the next ticket not blocked by it.

**Comment by bischoffa** [comment]
@ajsarkar28 for awareness given its analytics related
