### ISSUE TITLE
Document analytics additions for Address updates

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6533]
Based on final implementation of #6531:
- Document in [data dictionary](https://docs.google.com/spreadsheets/d/1kC9qfyLjA757Wj2IdMwHHKxsX453WDQr0kEEqvLYyLQ/edit#gid=895875184) after implementation completed
- Review existing dashboards where new information will start displaying and ensure documentation is coming through correctly.
- Improve the existing dashboards any time at least 30 days post implementation live to users

**Comment by OVezeamama** [comment]
Working on updating the data dictionary.
