### ISSUE TITLE
Backend: Move vet360 linking from v2 User endpoint to another location

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#6534]
#### Description
We have had several discussions about where vet360 linking should be triggered. This ticket is intended to commit time to deciding and implementing where it would best fit. Some ideas:

- Ask the SIS team if there's a way for us to add some actions after a mobile user logs in
- Create some sort of login endpoint that doesn't return data but exists just to execute login actions
 
We basically want the linking to happen as soon as the user logs in and only once

**Comment by Tonksthebear** [comment]
After moving where the vet360 linking happens, you'll need to relocate a couple of tests that test for the linking to be triggered in the user controllers

**Comment by kpethtel** [comment]
Tested on staging. Got 200.
