### ISSUE TITLE
CU - Veteran Status Unit Tests

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#6535]
## Proposed Change

Add Veteran Status Screen Tests once it is official as well as nametag checks if parts of it become variable or not. It's possible this breaks some detox e2e if it was referencing some pre-existing homescreen stuff.

- [ ] Nametag test file updates.
- [ ] PhotoUpload test file updates.
- [ ] VeteranStatusScreen test file created.

## Why Should We Prioritize?

New stuff should have new tests.

## Coding Time Estimation

2
	
## Checklist
[ ] Add the front-end label tag

[ ] Attach to the Frontend epic for engineering initiatives

**Comment by bischoffa** [comment]
@dumathane do these still need to get done?

**Comment by TKDickson** [comment]
Closing this ticket; the IIR team owns veteran status
