### ISSUE TITLE
Veteran Status - Analytics - Add Events for Tracking

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6536]
## Purpose: 

- Review Veteran Status MVP and determine basic event tracking needed for MVP 
- MVP [Figma file](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1806-90255&mode=design&t=BMeiQdH7AJlwuT6j-4)

## Event details and naming for FE: 

- Taps Veteran Status on Home Page/Name Tag 
- Taps close on Proof of Veteran status full panel in the top right 
- How many times viewed / how many viewers of "VeteranStatusScreen" 
- Measure time on "VeteranStatusScreen" 

## Other info:

- Photo was removed for MVP
- Its possible we may or may include a link for the Veteran to select if the information is correct - waiting on Rachel for confirmation on which direction

**Comment by g-opzt** [comment]
Putting this in Blocked until we have decision from PO on success question inclusion. Otherwise, MVP measurements of number of views & time spent viewing will already be available with existing analytics, as will measurement of API fails (if applicable).

**Comment by bischoffa** [comment]
@g-opzt success question is not part of MVP at this time. That work has been moved to the backlog.

**Comment by g-opzt** [comment]
Got it; in that case we will track all of this from screen_view events alone and no analytics need to be added by FE for MVP. Closing this out to reflect that.
