### ISSUE TITLE
Bug - Sev 3 - PROD Issue (MOBILE): VVC on VA device display as VVC @ Home vs. VVC on VA Device (BE: Update Appt Type Mapping to acct for Video Connect at VA location)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6542]
### Description

An issue was identified that Veterans have missed their appts because they thought their appointment was a VVC-at home appt (as displayed on the appt list on the mobile app).  However, the appt should be displayed as Video Connect on VA Device. 

Investigation is needed by the Appointments team identify what is needed to address and display the information accurately:

Current Tasks
- SPL team to review all the data and fix the logic of what TH means for Veterans.
- SPL to potentially send something different than going off the Kind field
- OCTO leads to ensre all data elements are coming through as expected

The appointments FE team has created the below ticket to address
Issue: [63865](https://github.com/department-of-veterans-affairs/va.gov-team/issues/63865) has been created by the appointments team to modify logic to determine when to show VVC - Home vs. VVC-VA device. 

We will need to stay connected with the appointments team to determine what changes Mobile will need to make to be nsync and display the correct modality data 

Update: 
Mapping on the web

- For Telephone appointments, Appointment - Kind field = 'phone'.

- For Video appointments, Appointment - Kind field = 'telehealth'.

- For Atlas, Appointment - telehealth field should have an atlas field. i.e telehealth: {atlas: ...}

- For VA Video Connect using a VA device,  Appointment - telehealth field should have vvsKind field = 'MOBILE_ANY'  i.e telehealth: {vvsKind: 'MOBILE_ANY'} & Appointment.extension.patientHasMobileGfe === true

- For VA Video Connect at Home, Appointment - telehealth field should have vvsKind field = 'MOBILE_ANY'  i.e telehealth: {vvsKind: 'MOBILE_ANY'} & Appointment.extension.patientHasMobileGfe === false

- For VA Video Connect at a VA location,  Appointment - telehealth field should have vvsKind field = 'CLINIC_BASED' or 'STORE_FORWARD'  i.e telehealth: {vvsKind: 'CLINIC_BASED'}

See thread for context: https://dsva.slack.com/archives/C018V2JCWRJ/p1692904186776569

## Acceptance Criteria

1. Reflect mapping  Update appointAppointment type mapping; should match above web mapping.  Note the main change is to check for patientHasMobileGfe & depreciation of MOBILE_GFE 

## Test Account: 

alfred.castillo@id.me

**Comment by MekoHong** [comment]
Based on convo, it looks like FE already has logic to account for VA_Video_Connect_Onsite appointments.  Change will only be needed on the backend and we do not have to add a new version.

**Comment by jperk51** [comment]
The onsite entry above needs to be added to the mapping in `modules/mobile/app/models/mobile/v0/adapters/vaos_v2_appointment.rb` line 242 following the rules listed in the ticket description

**Comment by MekoHong** [comment]
Screenshots from testing; aligned with web and shared update in DSVA thread... https://dsva.slack.com/archives/C018V2JCWRJ/p1693428535174719
![image (12)](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/90273080/89822eaa-fad9-45f0-8071-641fed8ac2bb)
![IMG_7826](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/90273080/532f4489-6c3c-4cb4-a43b-66aa42dd967f)
