### ISSUE TITLE
QA Task - Update Test Rail RC tests for Veteran Status panel

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#6544]
Once the Veteran Status is completely rolled out we will need to update our RC test plans to smoke test the new feature.
This ticket is to ensure the test cases are updated and to document that work.

Linked to ticket: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6375
Epic: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4270

**Comment by TKDickson** [comment]
This has been done for a long time; closing
