### ISSUE TITLE
Veteran Status - Photo Upload - Error Handling

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6550]
**Description:** 

- Binny identified during 8/21 call
- Action sheet we would share for Veteran Status which uses native events can throw errors (not sure of the root cause of the fail) and we throw a generic error for this 
- Need to revisit the error content and error handling 
- We do error handling for claims and other upload items using alert box 

**Other Info:**
- If using a snackbar it should only be for instances where we are directly interfacing with a API

**Comment by jennb33** [comment]
@g-opzt did you say in the DSU on 9/11 that this ticket can be closed? I thought I heard you say that this ticket wrapped with you, and I'm not sure if that means the entire, comprehensive ticket, or just the analysis work. TIA.

**Comment by bischoffa** [comment]
Photo upload was excluded from Veteran Status, this work is for the backlog for if/when photo uploads are prioritized.
