### ISSUE TITLE
Veteran Status - Photo Upload Enablement 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6551]
**Description:** 
- Originally not MVP but changed PO's mind that photo would be impactful for a Veteran Status feature based on research indicating that stores ask for photo ids and concerns with stolen valor 
- During demo of the feature Rachel determine to turn off Photo upload
- Digital VIC team said that they have to filter out photos as some want to upload inappropriate ones and currently there is no filter for mobile's upload for Veteran Status 
- The photo is only stored on the phone's cache and not through the VA - given this Digital VIC team mentioned they would be okay in keeping
- Digital VIC also mentioned they are working to get legislation changed to remove the photo requirements 
   -  Outside of the meeting it seems like this has been a discussion for a few years and hasn't been changed yet and likely wont - Mobile should revisit in Q4 23 or Q1 24 discussions 
 

**Ask:**
- Quick discovery on any preventative measures 
- Turn photo upload back on

**Comment by timwright12** [comment]
@bischoffa @ajsarkar28  I think VA killed photo uploads for veteran status. We can probably remove this issue

**Comment by TKDickson** [comment]
Closing this ticket; the IIR team owns the veteran status feature
