### ISSUE TITLE
Veteran Status - Content - In App Feedback Copy 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6555]
**Description:**

- Need a way to ask Veterans if Veteran Status is working as expected
- Based on research and thought from Greta a proposal was created by Brea in Figma
- Rachel / Ryan liked it but held it out of MVP

**Info:**

- Figma draft [here](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1817-46594&mode=design&t=0NzXwkAj4eGo9Up2-0)
- Misty to work on copy
- Rachel indicating this should be prioritized for next sprint
- Per 8/21 Slack target this inclusion next sprint

**Ask:**

- Finalize copy to be used for the in-app feedback experience 
- Coordinate with UX as needed 
- Add final copy to [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6558)

**Comment by mistymg** [comment]
Final copy added to [Figma](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1817-46594&mode=design&t=kY3uyYJj0l1pOhK0-0) and [eng ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6558). Closing as done
