### ISSUE TITLE
Veteran Status - Analytics - Events for In-App Feedback metrics

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6556]
**Description:**

- Need a way to ask Veterans if Veteran Status is working as expected
- Based on research and thought from Greta a proposal was created by Brea in Figma
- Rachel / Ryan liked it but held it out of MVP

**Info:**

- Figma draft [here](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1817-46594&mode=design&t=0NzXwkAj4eGo9Up2-0)
- Misty to work on copy
- Rachel indicating this should be prioritized for next sprint
- Per 8/21 Slack target this inclusion next sprint

**Ask:**

- Finalize what metrics / events are needed for improved tracking
- Recommendations on timing on when the feedback should be asked for

**Comment by TKDickson** [comment]
Closing this ticket; the veteran status card is included on the in-app review popup, and further in-app feedback would be rolled into (likely) the overall global initiative on it.
