### ISSUE TITLE
Veteran Status - FE -  In App Feedback - Add New metrics / Events - Business Logic Recommendation

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6557]
**Description:**
- Need a way to ask Veterans if Veteran Status is working as expected
- Based on research and thought from Greta a proposal was created by Brea in Figma
- Rachel / Ryan liked it but held it out of MVP

**Ask:**

- Add new events in order to track metrics for In-App feedback on Veteran Status 
- Recommend business logic for how often to show this

**Info:**
- Rachel indicating this should be prioritized for next sprint
- Per 8/21 Slack target this inclusion next sprint

**Comment by TKDickson** [comment]
Closing this ticket; the veteran status card is included on the in-app review popup, and further in-app feedback would be rolled into (likely) the overall global initiative on it, or initiated by the IIR team who now is responsible for this feature.
