### ISSUE TITLE
Veteran Status - Eng - Building In-App Feedback for Veteran Status 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6558]
**Description:**

- Need a way to ask Veterans if Veteran Status is working as expected

**Info:**

- Figma draft [here](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1817-46594&mode=design&t=0NzXwkAj4eGo9Up2-0)
- Copy:
     - Alert box heading: Did the proof of your Veteran status help you?
     - Button 1: Yes
     - Button 2: No
     - Button 3: Cancel
- Rachel indicating this should be prioritized for next sprint
- Per 8/21 Slack target this inclusion next sprint

**Ask:**

- [ ] - Front end to build UX design 
- [ ] - Implement business logic on how often this shows up 
- [ ] - Identify how to change the business logic for future needs

**Comment by mistymg** [comment]
@bischoffa @dumathane Copy for the feedback alert box for Veteran status is done. This is ready to work whenever it's prioritized.

**Comment by bischoffa** [comment]
Before moving forward with implementing In-App feedback there needs to be discussion if not approval from PRA.

 it’s a [PRA policy, also known as Paperwork Reduction Act.](https://pra.digital.gov/do-i-need-clearance/) There are restrictions on in-app surveys if we ask the same yes/no or multiple choice question or question(s) to more than 10 people. We’d need to get PRA clearance, which can take 9+ months. However, we can ask open ended questions (like, “tell me about your experience using the app) without needing to go throughPRA clearance.

[Data and Insight Platform at VA uses Medallia](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/platform-data-sources) for va.gov surveys - Assumption is they had to go through PRA clearance for that.

**Comment by timwright12** [comment]
@bischoffa I added the label veteran-status to this so it will show up on the VS team's Zenhub board, that's the label they're tied into with the va.gov-team repo

**Comment by TKDickson** [comment]
Closing this ticket; the veteran status card is included on the in-app review popup, and further in-app feedback would be rolled into (likely) the overall global initiative on it, or initiated by the IIR team who now is responsible for this feature.
