### ISSUE TITLE
Updated build tools version to 33 

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6559]
We got a warning that our target API level in Android needed to be updated to 33: 

https://play.google.com/console/u/0/developers/7507611851470273082/app/4974294731909201030/policy-center/issues/4988276614632641488/details

The deadline for this is Aug 30, 2023 or we won't be able to release to the play store.

**Violation**

App must target Android 13 (API level 33) or higher

> To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From Aug 30, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

Research from here: https://onkarjanwa.com/how-to-update-android-target-api-level-in-react-native/

**Comment by bischoffa** [comment]
@jennb33 this ticket was pulled in via Slack convo. Screen shot below. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDRtIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96a1794510782a53df352055080fc9e44338e914/image.png)

**Comment by DJUltraTom** [comment]
Test run here: 
https://dsvavsp.testrail.io/index.php?/runs/view/4805&group_by=cases:section_id&group_order=asc
No new issues uncovered:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFlxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a4f9c52a729ec6da70f0888cb3a910b09c2847b/Screenshot%202023-08-22%20at%203.11.37%20PM.png)

**Comment by timwright12** [comment]
Merged this into develop this morning. The next release is set for 8/29, a day before the Android cutoff so we should be OK, but if the release gets delayed at all we'll need this in there
