### ISSUE TITLE
UX - Remote Disaster Recovery (Discovery Phase)

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#6566]
## Description 
Today, when critical errors affect the Mobile Application, we currently do not have an immediate way to remotely address error fixes or clear cashes outside of the normal app store release and review process. As a result, users experience a broken app until it can be fixed and the Veteran experience is undesirable.

Related Epic: [ 6566](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6565)

UX Discovery: Remote Disaster - User Journey Review

- Review related user journeys for the following use cases
    - A [**feature (or part of feature) is broken** in the mobile application and we are working to resolve it remotely](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Remote-Disaster-Mitigation.md#main-use-case)
    - **[iOS or Play store Roll Backs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Remote-Disaster-Mitigation.md#possible-use-cases-tbd-not-finalized)**
    - **[Feature Rollouts by %](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Remote-Disaster-Mitigation.md#possible-use-cases-tbd-not-finalized)**(Paced Rollout)
    - **[A/B Testing](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Remote-Disaster-Mitigation.md#possible-use-cases-tbd-not-finalized)** 
- Note potential differences in flow based on "waygate" location
- Investigate examples of similar/related interactions from the app (ex: error messaging)

## Acceptance Criteria

The following things have been documented: 
  - [x] Examples of similar/related interactions from the app, where they occur & current display logic (ex: error messaging) 
  - [x] Screenshots for each of the user journeys for the various use cases, noting when there are possible differences based on "waygate" location if applicable/needed
  - [x] User & business goal for each use case

**Comment by StacyB2023** [comment]
@htcollier This is the placeholder ticket. Feel free to chop it up however you like

**Comment by htcollier** [comment]
[Discovery Figjam for Remote Disaster](https://www.figma.com/file/0Z8pARNjQdDrOJCxtJUyG0/Remote-Disaster---Discovery---VA-Mobile?type=whiteboard&node-id=0%3A1&t=NhgXUjGWtHfzeXpU-1) includes:
- Catalogue of how (by component & situation) the app communicates with users directly
- Current Data Availability check error message content & display logic

**Comment by htcollier** [comment]
[Updated use cases](https://www.figma.com/file/0Z8pARNjQdDrOJCxtJUyG0/Remote-Disaster---Discovery---VA-Mobile?type=whiteboard&node-id=30-11551&t=sa5nv4FWyEFeN7ZA-4) based on 9/6 meeting:
1. A screen is so broken in the mobile application that it can’t be rendered without crashing app/red screen of death
2. A screen element, feature (or part of feature) is broken in the mobile application but the screen can still be rendered
      A. and we are working to resolve it remotely 
      B. it is now resolved and installing a new version of the app will correct the problem

Not in scope:
- iOS or Play store Roll Backs
- Feature Rollouts by %(Paced Rollout)(this doesn’t feel like a remote disaster case)
- A/B Testing (this doesn’t feel like a remote disaster case)
