### ISSUE TITLE
PR to Add Copy for App Store What's New Content to Tuesday Aug 29, 2023 Release

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6567]
AC:

- PR is created which adds the copy for the App Store's "What's New Content" to the [Tuesday Aug 29, 2023 Release](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6515)
- Content should be as follows: "We changed the prescriptions list to show your active prescriptions first. We also added general improvements and fixed a few bugs."
**- Note: This should be for both Android and IOS**

**Comment by alexandec** [comment]
Content added to VAMobile/android/fastlane/metadata/android/en-US/changelogs/default.txt and VAMobile/ios/fastlane/metadata/en-US/release_notes.txt in the release/v2.10.0 branch.
