### ISSUE TITLE
Create List of Components to be Added to the Design System

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6569]
### Steps
- [x] Review [current list](https://docs.google.com/spreadsheets/d/1_EAH2LWSzwF8Om7o4LAYJf6gT9UWENANYpF7SZy3j8w/edit#gid=0) of components
- [x] Review each component against the criteria for a "good" candidate to determine component vs pattern vs snowflake
- [x] Decide which components are global vs flagship-specific vs feature-specific
- [x] Review updated component list with platform team

**Comment by TimRoe** [comment]
If helpful, [linking my notes from the determine a first component ticket](https://github.com/department-of-veterans-affairs/va.gov-team/blob/d691ce14512a870ccd766667c7410410e1f089fb/products/va-mobile-app/platform/Research/6238%20-%20Research%20Notes.md) that went through every component currently in the `components` folder of the app and labeled many as "No" for documented reasons. The "Revisit" and "Maybe" lists may form a handy short list of components to evaluate for design system consideration in the relatively near term.
