### ISSUE TITLE
SM MHV Login Issue - Error Message Implementation

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6571]
Blocked reason - MHV needs to validate the solution will work. MHV in their documentation shared with Mobile PO indicated it needed to be validated. 

**Purpose:** 

- Related to ticket  [5986](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5986)
- High level issue - sometimes Veterans sign into the app and do not get SM access, though they should s  - this is related to the user having a premium account however during the login process there was an issue in which the incorrect value is being passed to Mobile and Mobile does not display SM. Web has the same issue 
- Note Mobile is consuming what we are given - just we are not given correct info or missing info
- Thus need to account for this scenario and provide an error message similar to what MHV SM Web does to have them contact support to upgrade their account to premium and tie it to their existing MHV account 
- Originating issue is [5986](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5986) worked by Jayson - for triggering info please reach out to Jayson 

**Ask:**

- Code and implement UX design and content based on this [Figma File] - this is an existing error message (https://www.figma.com/file/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?type=design&node-id=1212-6891&mode=design&t=TZYjTWroFMaZ3tlh-0)

<img width="134" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/18bfbf0f-2d4e-482e-a825-8588ee653c07">

<img width="135" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/839756c5-a14d-4ad3-b308-c815238067fd">

**Comment by bischoffa** [comment]
UX portion of the bug ticket is completed. Error message can be found [here](https://www.figma.com/file/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?type=design&node-id=1212-6891&mode=design&t=TZYjTWroFMaZ3tlh-0)

**Comment by bischoffa** [comment]
@jennb33 thanks. Did Rachel provide any other specifics / details on why not to work on this?  Is the issue adding a message or the content of the message?

**Comment by bischoffa** [comment]
Adding this to blocked and addd blocked po label given direction was from PO and need further details to see how to get it unblocked.

**Comment by jennb33** [comment]
@bischoffa I tagged you in Rachel's Slack message

**Comment by bischoffa** [comment]
new content and new error message needed before this ticket can be worked. dependencies added.

**Comment by timwright12** [comment]
@bischoffa seems like this is no PO Blocked anymore, correct?

**Comment by bischoffa** [comment]
PO blocked no, blocked yes. Awaiting response from SM on what content to use.

**Comment by bischoffa** [comment]
Posted a [request](https://dsva.slack.com/archives/C03ECSBGSKX/p1694702796051919) in mhv-secure-messaging DSVA channel. No clear answer but some names to reach out to.   
  
Messaged David Rawlins 9/18 to see if they can help.

**Comment by bischoffa** [comment]
Brought up during MHV Standup. Told to post in mhv-sm-backend and to connect with Bryan Riley and Janie Tankard-Carnock. Posted today.

**Comment by bischoffa** [comment]
Had a call with Haritha (BE MHV Access Portal Lead) today and still do not have a clear path forward. Going with reach out to Jayson to see if we can tag a future meeting. May be getting stuck with Haritha's technical discussion and her validating what we did to identify the issue. 

Note posts and inquiries have been made with mhv-secure messaging, mhv-sm-backend - mhv-portal access, mhv standup, and not getting much traction. Told to talk with Bryan Riley, Christy Gales, David Rawlins, Haritha Cheruvu, and include Janie Tankard-Carnock. 

Still trying to move forward but I expect it to be slow.

**Comment by bischoffa** [comment]
Jayson chatted with Haritha and recommended reaching out to Haritha's PO Carnetta Scruggs. 

Removing the ticket from this sprint. Not expecting it to be prioritized in the next sprint as language is not yet known.

**Comment by bischoffa** [comment]
Reached out to Bryan and Christy who I was told are my main contacts. I informed them that I was asked to reach out to Carnetta Scruggs and asked them to verify if that is what they recommend.

**Comment by bischoffa** [comment]
Talked with Rachel to see if Mobile should send email. Rachel is going to look into it on her end and recommended the email is best sent from VA. I sent Rachel my email draft. 

I message Joe Niquette (part of original discussion) to see if he can help given mobile is getting the run around.

**Comment by bischoffa** [comment]
Transitioned this from Bugs to its own Epic.

**Comment by bischoffa** [comment]
Continues to be blocked as we do not yet know the content. Still blocked. No action. Related to ticket 6737

**Comment by mistymg** [comment]
Worked with Laura W today to write an error message for Solution 2 (telling user to go to MHV class website and sign in using Login.gov/ID.me account). Adam confirmed with Eng that we can determine which account a user has used to sign in the app, so the copy I wrote can be dynamic based on how they signed in.

**Comment by mistymg** [comment]
BE implemented fix so there's no need for new error message.
