### ISSUE TITLE
Bug - Sev 3 - FE - Update Colors in Botton Tab Bar

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#6588]
### Purpose:

- Related to ticket  [6180](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6180)
- Low-level issue – It was discovered that the light mode and dark mode color patterns for the bottom tab bar are different. In light mode, they're all blue. In dark mode, some are grey. Two recommendations were proposed and [recommendation #1 ](https://www.figma.com/file/tLJKv0x0iacZzkZPoqZVaa/Components-for-future-releases?type=design&node-id=102-875&mode=design&t=bRTcma4rv79RB2qk-4)was chosen as the best solution.
- [Recommendation #1](https://www.figma.com/file/tLJKv0x0iacZzkZPoqZVaa/Components-for-future-releases?type=design&node-id=102-875&mode=design&t=bRTcma4rv79RB2qk-4) keeps dark mode the same, but updates the light mode inactive tabs to be gray (vs. the previous primary blue). This matches the inactive gray and active blue used in dark mode currently. It also helps to provide more visual emphasis to the active tab and sets it apart from the inactive tabs.

### Ask:
- Update the colors used in the bottom navigation (tab bar) to [recommendation #1 in Figma](https://www.figma.com/file/tLJKv0x0iacZzkZPoqZVaa/Components-for-future-releases?type=design&node-id=102-875&mode=design&t=bRTcma4rv79RB2qk-4).

**Comment by rbontrager** [comment]
Verified that inactive tabs are gray in light mode and dark mode on iOS and Android.  Approved by QA.
