### ISSUE TITLE
Prod Issue (Mobile): Update current mapping to accurately display Video Connect Appointments at VA Location

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6591]
## Description 

An issue was identified that Veterans have missed their appts because they thought their appointment was a VVC-at home appt (as displayed on the appt list on the mobile app).  Through investigation, it was identified that we do not currently have mapping in place to account for `patientHasMobileGFE` in the appt type mapping.  

The Backend team will be making an update to the mapping to incorporate this logic.  As part of this ticket we will need to 

- Add logic to the front end to account for the mapping change (see ticket #6542) for reference
- Update the appt list view to display the correct modality
- Update Appt Details to provide the additional Header and content information for the appt type

## Acceptance Criteria
  

-  [ ] Verify if appointmentType is X then display 
        - icon:
        - with text: at [clinic] (placeholder need content and design review) 
on the appointment list screen

-  [ ] Verify if appointmentType is X that the appointment details page displays the following information
- Header:
- Text:
- Add all details that display for in person appt......

**Accessibility Requirements**
- [ ] Verify when appointmentType = X  that the modality displayed = 
 
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

## Test Account:  [alfred.castillo@id.me](mailto:alfred.castillo@id.me)
Appt Date 6/20

Web View:

![Screenshot 2023-08-25 at 12 25 42 PM](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/90273080/bc175674-57f6-49ea-bdad-b7c0fb4b85b4)
![Screenshot 2023-08-25 at 12 25 54 PM](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/90273080/bfe8485f-5b9d-4970-896f-fd8763950d19)

**Comment by Sparowhawk** [comment]
I can confirm that this one shouldn't be an issue as long as the correct appt type is coming in from the BE. @ala-yna can we close this ticket?
