### ISSUE TITLE
Technical Assessment of Surfacing Personalized Data on Homescreen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6593]
AC:

- [ ] Document the technical complexity of surfacing each data point listed in this [FigJam](https://www.figma.com/file/NHnXpvkhBeqvUQ6LIqMGqd/Personalized-Data---Discovery-%26-Classification--VA-Mobile?type=whiteboard&node-id=77-402&t=rM6mT9D1yTIsZkAi-0)
- [ ] While investigating, work with FE to determine if the timing of the call for data would need to be changed
- [ ] Record any endpoints where you believe the moved data should potentially be split into a new endpoint

**Comment by jperk51** [comment]
Meeting on Thursday with Ryan. After that I'll collect my thoughts in this ticket and close it

**Comment by jperk51** [comment]
The main technical concern is the more data we want to show on the homescreen the more API calls need to be made as soon as the user logs in the longer they have to sit and wait for the initial app load to happen. Small API calls are less impact to this load time, and there are UI methods (lazy loading, etc) that can minimize the loading stall, but those come with accessibility concerns a lot of the time. Surfacing any data that already exists in the app only requires dealing with the above concerns, but surfacing any new data requires integrating with new APIs, coordination with other teams, AND dealing with the above concerns thus is a significantly higher lift. 

As Ryan, mentioned in the meeting yesterday, I think it's a really good idea to separate things that are more like "notifications", things that are very timely and will likely go away after the user acknowledges it. Those things are significantly more complex in how we want to manage them or how we even know if they happen than data that is much more static.
