### ISSUE TITLE
Personalized home screen: High level UI concept creation & audit

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6594]
Identify potential home screen MVP approach by examining whether previously created home screen concepts address our new personalized home screen product brief (and create new home screen concept wireframes for evaluation if needed).
- [x] Collect existing home screen concepts from 2021-present into one place
- [x] Conduct audit of navigation design exploration concepts based on predefined success criteria ([#6595](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6595))
    - [x] Create new wireframe concepts where gaps exist 
   - [x] Narrow the list to finalists for proposed home screen MVP approach/es
    - [x] Share finalists with ENG for preliminary feasibility review
    - [x] Map high level UI architecture for finalists (zones, content types)

See [Personalization work planning](https://www.figma.com/file/fQfBPKtLWbwEnPIFeaBaXf/Personalization-work-planning?type=whiteboard&node-id=0%3A1&t=0j9zI96bitis1mXW-1) for overall workplan.

**Comment by htcollier** [comment]
[Existing & new home screen wireframe concepts in balsamiq](https://balsamiq.cloud/s4uw4la/pnnwuqv/rFCBA)

**Comment by htcollier** [comment]
Narrowed explorations to 4 finalists for feasibility review with ENG based on conversation with @ajsarkar28: [Personalization Explorations - success criteria audit - finalists](https://balsamiq.cloud/s4uw4la/pnnwuqv/rF333).
