### ISSUE TITLE
Personalized home screen: Define & document success criteria for home screen approaches

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6595]
Define and document success criteria for an effective personalized home screen
- [x] collaborate to define proposed success criteria with @ajsarkar28 based on [Product Brief](https://docs.google.com/document/d/1qPUDihOxzkiNqK96ZPFlX4wTTHov033n5bOXgt1jmvU/edit) & [UX strategy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/ux/personalization-homescreen-design-strategy-worksheet-2023.md)
- [x] review proposed success criteria with ENG, refine according to feedback
- [x] post to github
- [x] align on proposed success criteria with PM & ENG lead

See [Personalization work planning](https://www.figma.com/file/fQfBPKtLWbwEnPIFeaBaXf/Personalization-work-planning?type=whiteboard&node-id=0%3A1&t=0j9zI96bitis1mXW-1) for overall workplan.

**Comment by htcollier** [comment]
First pass: [DRAFT VA Mobile App: Criteria for Evaluating Personalized Home Screen Approaches
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products[…]tures/design-personalization/ux/home-screen-success-criteria.md)

**Comment by htcollier** [comment]
Shared with @ajsarkar28 & @jperk51 for PM & ENG feedback before passing on to POs.

**Comment by htcollier** [comment]
Everybody is on board with criteria. Closing
