### ISSUE TITLE
Travel Claims - BE Discovery - 3 APIs (Get Token, Submit Claims, Get Claim status)

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6600]
**Purpose:** 

- For the proposed Travel Claims MVP AC on filing a travel claim request on past appointments, OCTO indicated that 3 APIs are needed in order to get information, submit a claim and get a claim status 
- See if there are any issues, limitations, or concerns with Mobile's needs to integrate with 
- After this UX will take learnings and also understanding of what fields are available in order to start their design work 

**Other info:** 
- [BTSSS Claims Inject Documentation Link](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/engineering)
- Identify if there are any open questions that need to be answers by the team owning this
   - Can ask them in the Travel Pay VA slack channel 
- Feature MVP focus 
    - User navigates to Health/Appointment/Past
    - For an eligible appointment, user sees option to start a travel claim
    - Eligible appointment = Veteran is Checked-In and appointment date is < 30 days old
User sees messages on tasks to do before submitting a claim and getting reimbursed. User is redirected to do these tasks
For users who have already successfully submitted a claim and got reimbursed, do not show message(s) in step 3
User submits a claims
User tracks claim

**Ask:**
- [ ] If you have questions please first review the closed questions on the epic; if not answered please add them to the Open Questions section on the epic 
- [ ] Discovery on Get Token API
- [ ] Discovery on Submit Claims API
- [ ] Discover on Get Claim Status API
- [ ] Where does Mobile / FE get Appointment Check-In / Checkout Status (its only of the eligibility requirements)

**Comment by aherzberg** [comment]
waiting on getting dev creds to get response data to finish discovery

**Comment by aherzberg** [comment]
@bischoffa we still don't have the dev credentials but I got an idea of what the schema is and if it doesn't drastically change (It's simple enough that I don't think it will) we should be good to call discovery complete. the dev credentials won't be necessary now until we do implementation. 

Current state of endpoints, subject to change.

# Submit Claim Endpoint 
Request body schema 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63a071d89d92bf4b5c9c6db2989f84cc412ee6d9/Screenshot%202023-09-11%20at%209.22.45%20AM.png)

# Claim Status
Request Body
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe52fe340991be50905f2852daf03c9eabdd852a/Screenshot%202023-09-11%20at%209.24.09%20AM.png)

Response Schema
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3032d10aaa4c57ce336a1b6aad21a876da957f21/Screenshot%202023-09-11%20at%209.25.09%20AM.png)

The only field we need to identify the appointment to submit to the claim to is the datetime of the appointment which we already are sending to FE in the appt endpoint.

The appt Ids should match up and can the claim status endpoint can map to the appointments through that field. If UX would like to show the submit claim button on the index list page of appointments this could be done by concurrently sending a claim status call with the same date range we call for appointments. appointments already takes a fair amount of time so it's unlikely that this call will lengthen the total time to load the page. 

These services will be built into vets-api so integration should require minimal effort. We'll just need the credentials for the dev and prod environment which has been set in motion. 

It could be problematic if the submit claim endpoint takes 30+ seconds like the docs says it currently does but this is being worked on and will hopefully be reduced. If it doesn't, we may need to lengthen our timeout period so the endpoint doesn't timeout before the request has gone through.

**Comment by jperk51** [comment]
Seems like the extra ticket isn't necessary. @bischoffa ?

**Comment by bischoffa** [comment]
@jperk51 @aherzberg with the info Andrew provided above additional discovery does not seem to be needed. I will cancel the ticket and also remove from sprint planning.   
  
I do suspect that UX will have some BE questions as they start their mock-up design work.
