### ISSUE TITLE
Bug - Sev 3 - Content - SM Login Issue - Error Message Content

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6608]
**Purpose:** 

- Ticket is purely for content but will need to coordinate with Designer to determine UX ticket [6570](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6570)
- Timeboxed to 2 points
- Related to ticket  [5986](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5986)
- High level issue - sometimes Veterans sign into the app and unable to access SM - this is related to not having premium account however during the login process they should have received it and that info passed to Mobile but it was not
- Note Mobile is consuming what we are given - just we are not given correct info or missing info
- Thus need to account for this scenario and provide an error message similar to what MHV SM Web does to have them contact support to upgrade their account to premium and tie it to their existing MHV account 

**Actions:**
- Review ticket [5986 ](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5986)
- Need to design error message UX and content for engineering to build 
- Likely will need to reach out to MHV SM to see what they use if not in the thread above

**Comment by mistymg** [comment]
Determined to reuse an existing error message that we already show in SM for when a user doesn't have a premium account. Content decisions documented in UX [6570](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6570).
