### ISSUE TITLE
Review documentation for Label Tag and Tabs components

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6623]
**Review and update content guidelines in component documentation for:**
- [x] [Label Tag](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/3138)
- [x] [Tabs](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/3493)

**Related tickets**
#6422 Label tag
#6423 Tabs

**Comment by bischoffa** [comment]
Will be part [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclI2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b21026012f2ed8c2ace5d561e93ab3ded8adedaf/image.png)
