### ISSUE TITLE
Testing MHV SM Re-Engineered APIs - SM Patient API Folder Phase 1 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6626]
**Purpose:**

- Mobile is being asked to test SM after MHV SM has re-engineered their APIs 
- Mobile is currently already integrated so only testing effort is needed 

**Ask:**
- Test SM to make sure SM acts as expected
- Email has specific areas to test
- Feel free to do a full regression if you think that is necessary 

**Info:** 
- Asking Engineering for help as there is only 1 QA this sprint
- Not previously planned for the sprint; just was informed of this testing need today via email (below)
- MHV SM test request - email below

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFpiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22448329256c44c381e9db8678baa68c38ce9f35/image.png)

**Comment by bischoffa** [comment]
Shared results with MHV SM owner. Closing ticket as nothing else is needed. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWwwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b253d4c50dca40f7bf990e6e876caf54b0bca0a/image.png)

**Comment by Sparowhawk** [comment]
@bischoffa When talking with Chris and his tests we ended up retesting the endpoints and found that the method I was using to test the new api's in the code doesn't do what it actually says it does so it was a false positive.

Moving this back to in progress and will be working on this tomorrow

**Comment by bischoffa** [comment]
@Sparowhawk thanks for letting me know. Lets keep an eye on it. MHV SM already pushed this into production on 9/13.   
  
Would this same issue impact the testing of the other tickets?

**Comment by bischoffa** [comment]
@Sparowhawk thanks for letting me know. Lets keep an eye on it. MHV SM already pushed this into production on 9/13.   
  
Would this same issue impact the testing of the other tickets?

**Comment by bischoffa** [comment]
Also for the future, if we are pulling in work to this sprint please update the sprint tag to include the sprint its being worked on. I did it for this one.

**Comment by Sparowhawk** [comment]
@bischoffa Since this was pushed to production already I can confirm production is working otherwise we have Vets that would be calling in. So no additional work needs to happen for this ticket and I will reclose it.

Per @Tonksthebear What's the goal of testing upstream services before BE implement them? They go through some processing on our end so the raw response would most likely never end up in the app. 

With what he said all the MHV tickets I don't feel should be tested by mobile as it would be covered by BE when they are implemented

**Comment by bischoffa** [comment]
Intent of testing all of this is to ensure the changes work in Mobile before MHV SM pushing out the API changes and we see it breaks things in production. So pre-production validation in mobile is the intent and purpose this ticket and others tied to this epic.

**Comment by Sparowhawk** [comment]
@bischoffa 

per @Tonksthebear 
Everything was switched over and without feature flags so I'm pretty confident things would've blown up already

So all SM messaging api's I can confidently say have been thoroughly tested cause they are already live for vets to use and nothing has blown up

**Comment by Sparowhawk** [comment]
closing this ticket as it has been thoroughly tested

**Comment by bischoffa** [comment]
Thanks. That means this specific change is good. The other tickets are related to other changes before they are pushed to production by MHV SM.

**Comment by Tonksthebear** [comment]
> Per @Tonksthebear Basically all of mobile's secure messaging has switched over to mhv-sm-api/patient/v1/* urls, so any secure messaging endpoint you hit will already be using those upstream urls. So I think your actual test scope is just make sure mobile messaging endpoints work
> 
> With what he said all the MHV tickets I don't feel should be tested by mobile as it would be covered by BE when they were implemented

I misunderstood what was being tested, I was under the impression the mhv urls were being tested directly. After finding out Mobile already integrated with the `mhm-sm-api/patient/v1/*`, I understood the goal was just to make sure that integration went well. As I said to @Sparowhawk, the switch happened without feature flags so it's been live and tested

**Comment by Sparowhawk** [comment]
As I understand it with what @Tonksthebear is saying is that all SM api's have already been updated. There would be no way for us to test the upstream service directly as mobile due to security/authentication that only the staging/prod severs have and since it is all in production as of right now with no feature flags. Everything can be said that it was tested and works.

**Comment by bischoffa** [comment]
Not all APIs have been updated to my knowledge. They are working in partitions.

**Comment by bischoffa** [comment]
This is the [test plan breakout](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0) from MHV SM. We are asked to test out the feature once they push their changes to the test environment which has not been done for all the items.

**Comment by Sparowhawk** [comment]
Actually it looks like not all of them might be in production as they are pending MHV to push

However per Jason C:

if they’re not in staging there’s nothing you can do to test them

And if they’re in staging then they’ll be in prod

**Comment by Sparowhawk** [comment]
@bischoffa We don't have access to the test environment in mobile I don't know if BE has access to their test environment. We only have access to our middleman api's which are based off whats in staging which is what will be in production

**Comment by Sparowhawk** [comment]
There is no way to call the testing ones because they still need the authentication/security that we don't have access to. So I am not sure how we are supposed to test this.

**Comment by bischoffa** [comment]
@jperk51 any thoughts on @Sparowhawk comments above regarding testing?  I don't recall an access issue coming up.

**Comment by jperk51** [comment]
All we should need to do it perform the actions we usually do for QA for SM. As soon as these go live in sysb according to MHV they are live in the app in staging.

**Comment by Sparowhawk** [comment]
@jperk51 Right, I think that is how i understand it that it would go live in the app in staging. I think @bischoffa is wanting us to test them before they get to staging though and I don't know how we could possibly do that since it's the same existing endpoint and I/we don't have access to their test environment on the upstream service.

**Comment by Sparowhawk** [comment]
I also was in talks with Alex Morgun and he gave me the link to the MHV sysb file.(I can't open it due to needing to be on the VA network) however with @jperk51 comments here if they are in sysb they are in staging then I don't even need to fool around with that
