### ISSUE TITLE
Spike - Create deprecation notice for components going into MDS

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6648]
There's a linting plugin for deprecation at: https://github.com/AlexMost/eslint-plugin-deprecate/ VADS uses this to help migrate teams off of old components by tartgetting the import: https://github.com/AlexMost/eslint-plugin-deprecate/blob/HEAD/docs/rules/import.md

This ticket is a spike into figuring out if we can use this same model for getting app teams to migrate off older components

VADS does this from [inside vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.eslintrc.js#L49), ideally, it would be better if we could do this remotely from within our own npm published eslint config

**Definition of Done**

- [ ] Document (in the ticket is fine) if we can do this and how
- [ ] Spin up follow-on tickets for the work

**Comment by narin** [comment]
After researching this plugin, it seems like it is very straightforward to use.

We could use it in the same manner in the same manner that `vets-website` is using it, by adding a rule to `va-mobile-app`s eslintrc for each component, e.g. **OR** if we foresee using it for other consumers, and to notify developers about future components that may become deprecrated, we could create our own eslint plugin.

## Simple method
Add a rule for each new component as we implement it. It could be a standard AC for each `va-mobile-app` implementation ticket. e.g.:

```
'deprecate/import': [
  'warn',
  {
    name: 'components/AlertBox',
    use: '@department-of-veterans-affairs/mobile-component-library/AlertBox',
  },
]
```

### Pros
- Simple pattern to add for each component

### Cons
- When teams are split, app devs will need to remember to add this rule for each component they implement
- Design library team won't have control of deprecation rules, and we'll have to trust that the app developers will add them

## Eslint plugin method
We'd create another NPM package that is an eslint plugin, where we could define all the deprecation rules. Consuming apps would just add our plugin to the `extends` section of their eslint config.

### Pros
- We'd "own" the ruleset and could update/publish it as needed
- It could be kept in sync with our component library versioning, so if in the future we delete or rename a component, we could use this system to warn consumers

### Cons
- Another npm package to set up, maintain and keep in sync with component library
- Library consumers would still have to bump the version of the plugin when we release a new version
- Higher LOE to get set up, as creating a new eslint plugin isn't something we've done before (although looks straightforward)

**Comment by narin** [comment]
Ticket created here: #6988

Closing out.
