### ISSUE TITLE
Testing Effort - SM - Create Message API Phase 2 – Send Message & Reply Message - Test

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6659]
Ready 11/3 to test - moving into production on 11/15 - plan to test early Sprint 84

**Purpose:**
- MHV SM is Migrating to new Re-Engineered APIs for MHV SM 
- Mobile has already completed integration work 
- MHV SM asked Mobile to test functionality to make sure it works as expected and notify MHV SM on results
    - If successful, MHV SM will move forward with production releases
    - If unsuccessful then MHV SM and Mobile will need to troubleshoot until the issue is resolved
- Only testing is needed at this time 
    - Testing can be completed by engineering or QA  
- Multiple items will be tested between Sept - early Nov  - [testing sheet ](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0)

**Ask:**

- Complete testing of item 3 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEo0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--721c87c37b8f302add72b41cfcf61c7f50d4cd09/image.png)
- Post findings / results to this ticket and @Adam 
- Adam to coordinate with MHV SM on findings

**Comment by bischoffa** [comment]
Pulled out of Sprint 80 as MHV SM indicated this wont be ready for this sprint. Testing to take place between 10/3 - 10/18

**Comment by bischoffa** [comment]
added front end as capacity was planned for front end to do the qa test here like dylan did last sprint

**Comment by alexandec** [comment]
Logged in as Karsyn (staging user), then sent a message and replied to it. Verified that send and reply features worked.

Send message:


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWJrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--99546b650d7d649b99b1bc8ea15eb12ecd2b8114/send-message.mp4)


Reply to message:


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlBrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--689adbb4fba2653471690e5605234e12a131aa88/reply-message.mp4)

**Comment by bischoffa** [comment]
@alexandec I will have to reopen this. They are planning to make their changes by 10/2. So we can't test till 10/3.

**Comment by bischoffa** [comment]
I will move it into blocked until it can be tested once MHV environment changes are made. Sorry I should have put it in blocked before vs just putting timing in the title.

**Comment by bischoffa** [comment]
I will move it into blocked until it can be tested once MHV environment changes are made. Sorry I should have put it in blocked before vs just putting timing in the title.

**Comment by alexandec** [comment]
@bischoffa got it, I'll wait and retest when the endpoint is ready.

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUgyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--995dbae67b98b2e9551b0d40569dabf8d4b5cad7/image.png)

**Comment by alexandec** [comment]
@bischoffa thanks for the update. I'll wait until we know for sure that the endpoint is hooked up.

**Comment by alexandec** [comment]
Moved this to blocked based on a chat with @jennb33. Will continue work when the endpoint is ready.

**Comment by bischoffa** [comment]
No confirmation from Christy yesterday, I followed up this morning asking for a status

**Comment by bischoffa** [comment]
Removing from current sprint, assigning to next sprint

**Comment by bischoffa** [comment]
Christy followed up and said it should be ready on 10/13. Thus updated the timing to start testing the following Monday. Keeping it in blocked until I get confirmation from Christy on Friday of their change.

**Comment by bischoffa** [comment]
Christy followed up 10/13 and indicated it may not be till Monday or Tuesday until we can test it.

**Comment by bischoffa** [comment]
Reached out for an update, waiting for a reply

**Comment by bischoffa** [comment]
Delayed again, will check in in a couple days.

**Comment by bischoffa** [comment]
Moved it into next sprint. Work next started so pulling it off of Sprint 10/25

**Comment by bischoffa** [comment]
Messaged Christy today asking when this would be available for Mobile to test

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--973493435eaea7df20f8fbc9a0f9eb2c14882167/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTJmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef39ec11a20099e42da8a091d91f1aa5f82b1759/image.png)

**Comment by bischoffa** [comment]
@alexandec this is ready to test. if possible could we get this tested before EOD tomorrow?

**Comment by alexandec** [comment]
@bischoffa sure, I can pick this up now

**Comment by alexandec** [comment]
Logged in as Karsyn (staging user), then sent a message and replied to it. Verified that send and reply features worked.

Send message:



https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/d390ab0b-543f-45b7-b1a8-2ad79b0960e7


Reply to message:


https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/95e28fee-b550-41cb-936a-07c92d027249

**Comment by bischoffa** [comment]
Thanks @alexandec it finally all came together!!! I shared this with MHV SM. Closing this ticket.
