### ISSUE TITLE
Testing Effort - SM - Folder API Phase 2 – Search for Messages - test between 9/27 - 10/2

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6660]
**Purpose:**
- MHV SM is Migrating to new Re-Engineered APIs for MHV SM 
- Mobile has already completed integration work 
- MHV SM asked Mobile to test functionality to make sure it works as expected and notify MHV SM on results
    - If successful, MHV SM will move forward with production releases
    - If unsuccessful then MHV SM and Mobile will need to troubleshoot until the issue is resolved
- Only testing is needed at this time 
    - Testing can be completed by engineering or QA  
- Multiple items will be tested between Sept - early Nov  - [testing sheet ](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0)

**Ask:**

- Complete testing of item 6
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDE0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0165a243aa55dc2196d8fab5c15915149bd5372b/image.png)
- Post findings / results to this ticket and @Adam 
- Adam to coordinate with MHV SM on findings

**Comment by bischoffa** [comment]
Updated to 1 per convo with Binny - testing only effort

**Comment by bischoffa** [comment]
added front end as capacity was planned for front end to do the qa test here like dylan did last sprint

**Comment by bischoffa** [comment]
Given timing change from MHV this has shifted to next sprint.

**Comment by bischoffa** [comment]
Ready to be tested per MHV SM

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnJMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ea4663163fbcec42fc44840bf617c288fa697ff/image.png)

**Comment by alexandec** [comment]
@bischoffa I looked into this particular endpoint a bit. We don't support searching messages in the mobile app (see this [slack comment](https://dsva.slack.com/archives/C03T8JY2DM2/p1690217411447569?thread_ts=1690208428.708249&cid=C03T8JY2DM2)) so I don't think there's a good way to test this endpoint on mobile. Based on that slack thread it looks like the MHV web app could be used to test this endpoint.

**Comment by bischoffa** [comment]
Thanks! I will let them know!

**Comment by bischoffa** [comment]
Thanks! I will let them know!

**Comment by bischoffa** [comment]
Told Christy on 10/2 [Uploading... image.png]

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazcyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9bbea874bf27ce83d6632bb25ef0791fae2b38e1/image.png)
