### ISSUE TITLE
Testing Effort - SM - Create Message API Phase 2 – Save Draft Message & Save Reply Draft - test between 9/20 - 9/25

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6661]
**Purpose:**
- MHV SM is Migrating to new Re-Engineered APIs for MHV SM 
- Mobile has already completed integration work 
- MHV SM asked Mobile to test functionality to make sure it works as expected and notify MHV SM on results
    - If successful, MHV SM will move forward with production releases
    - If unsuccessful then MHV SM and Mobile will need to troubleshoot until the issue is resolved
- Only testing is needed at this time 
    - Testing can be completed by engineering or QA  
- Multiple items will be tested between Sept - early Nov  - [testing sheet ](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0)

**Ask:**

- Complete testing of item 6
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUo0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eef1b1c2c8bf4b8b6c6169577edfac639f4d39eb/image.png)
- Post findings / results to this ticket and @Adam 
- Adam to coordinate with MHV SM on findings

**Comment by bischoffa** [comment]
Updated to 1 per convo with Binny - testing only effort

**Comment by bischoffa** [comment]
added front end as capacity was planned for front end to do the qa test here like dylan did last sprint

**Comment by bischoffa** [comment]
Dylan did the testing for previous tickets, so if there are any questions Dylan can assist.

**Comment by bischoffa** [comment]
MHV Confirmed this is ready today for testing 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjNMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a32f96c79e1950e12921b1cba3148f4d498f3f3d/image.png)

**Comment by alexandec** [comment]
Based on [this slack discussion](https://adhoc.slack.com/archives/C0206QFMXFU/p1695659657242349), all the new endpoints mentioned in [the spreadsheet](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0), that we use in the mobile app, are already hooked up to our staging API. So testing the SM feature in the app with a staging user will automatically test the new endpoints. I've [asked QA](https://adhoc.slack.com/archives/C02N65QRRB7/p1695666132158999) to confirm that their existing RC testing will test the features listed in the spreadsheet. Just waiting on confirmation from QA.

**Comment by alexandec** [comment]
I tested saving a draft and saving a reply draft in the app, with staging user Karsyn. It worked fine so I'm closing this ticket

Save draft:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2piIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--729a7e249fb379d2ec9999e0ce1263b6ddc12219/draft.mp4)

Save draft reply:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3piIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4594da0e12b9f90a07087aa9a7ffcd8e3143de2/reply%20draft.mp4)
