### ISSUE TITLE
Testing Effort - SM - Folder API Phase 2 – Get Messages for Folder - test between 9/27 - 10/2

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6662]
**Purpose:**
- MHV SM is Migrating to new Re-Engineered APIs for MHV SM 
- Mobile has already completed integration work 
- MHV SM asked Mobile to test functionality to make sure it works as expected and notify MHV SM on results
    - If successful, MHV SM will move forward with production releases
    - If unsuccessful then MHV SM and Mobile will need to troubleshoot until the issue is resolved
- Only testing is needed at this time 
    - Testing can be completed by engineering or QA  
- Multiple items will be tested between Sept - early Nov  - [testing sheet ](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0)

**Ask:**

- Complete testing of item 10
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk40IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1690bde1318bf66a95803da5f124a192d028a87c/image.png)
- Post findings / results to this ticket and @Adam 
- Adam to coordinate with MHV SM on findings

**Comment by bischoffa** [comment]
Updated to 1 per convo with Binny - testing only effort

**Comment by bischoffa** [comment]
added front end as capacity was planned for front end to do the qa test here like dylan did last sprint

**Comment by bischoffa** [comment]
MHV SM confirmed this is ready to be tested by Mobile. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmpMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a476dc75fa9ac7c909fee055dc680b091be4e15/image.png)

**Comment by alexandec** [comment]
Logged in as Karsyn (staging user) and clicked on various folders. Messages were listed in the folders, indicating that the Get Messages for Folder endpoint is working fine.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbURqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ce9c0a04f0440812ee8b8e216fc6c66d0d469572/show%20messages.mp4)
