### ISSUE TITLE
Testing Effort - SM - Create Message API Phase 3 - Mobile to test TBD

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6663]
**Purpose:**
- MHV SM is Migrating to new Re-Engineered APIs for MHV SM 
- Mobile has already completed integration work 
- MHV SM asked Mobile to test functionality to make sure it works as expected and notify MHV SM on results
    - If successful, MHV SM will move forward with production releases
    - If unsuccessful then MHV SM and Mobile will need to troubleshoot until the issue is resolved
- Only testing is needed at this time 
    - Testing can be completed by engineering or QA  
- Multiple items will be tested between Sept - early Nov  - [testing sheet ](https://docs.google.com/spreadsheets/d/1PNN94ncKh_CW2-9vlepbjWbyLLh-zEsU3mHr503NbGA/edit#gid=0)

**Ask:**

- Complete testing of item 6
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDE0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0165a243aa55dc2196d8fab5c15915149bd5372b/image.png)
- Post findings / results to this ticket and @Adam 
- Adam to coordinate with MHV SM on findings

**Comment by bischoffa** [comment]
Updated to 1 per convo with Binny - testing only effort

**Comment by bischoffa** [comment]
added front end as capacity was planned for front end to do the qa test here like dylan did last sprint

**Comment by bischoffa** [comment]
Asked Christy MHV Web for an update on timing on 10/2 , waiting a response 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFAyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4f97ffc550d05dfc8ab7eb97e0648044924b7c12/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTMyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58a4b7a74a41f3a16e82a181f09b4d569bf2f05f/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTMyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--58a4b7a74a41f3a16e82a181f09b4d569bf2f05f/image.png)

**Comment by bischoffa** [comment]
Messaged Christy today asking when this would be available for Mobile to test

**Comment by bischoffa** [comment]
6663 - earliest is 11/8. I asked for them to confirm its out and working before Mobile moves on it.

**Comment by bischoffa** [comment]
No specific eta 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe53a06e0909098b78e84d63cc3d5b1a820bd5a1/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecf0d3c6fd142405522532d99e4afba9a14308b0/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3pUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de12deac084b6d9786c98b2aafdf4c340165bd2f/image.png)

**Comment by bischoffa** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNC9nQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f14711467d2a94270d47ff2ec92708a33e4babd/image.png)

**Comment by bischoffa** [comment]
@alexandec this just got unblocked. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVltQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db471c25930cb1abe469da5bf53e153c4ec6edf5/image.png)

**Comment by alexandec** [comment]
Logged in as Karsyn on staging and sent a message. Confirmed that the message showed up in Karsyn's Sent folder.


https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/e046132e-4b22-4cac-8baa-fd5a8f1178a0

**Comment by alexandec** [comment]
Replied to message as Karsyn and confirmed successful reply.

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/630890f9-83d5-4b7d-9e08-c6be58303e4a
