### ISSUE TITLE
Demo Mode - Add appt data for C&P and Telehealth (Onsite) appointments

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6664]
## Description 
As a mobile user, I want to view appointment types C&P and Telehealth (Onsite & GFE) in demo mode.

As part of this story we want to:   

- Add appt data for 
   -  C&P appts
   -  Telehealth appts (onsite)
   

## Acceptance Criteria
  

1. -  [x] Add appt data for C&P appointment use test user royal.tester@id.me upcoming appt
       - Upcoming Appt- Claim exam,  Appt date December 1, 2023 at 8:00 a.m. MT
       - Canceled Appt - Claim exam, Appt date December 3, 2023 at 7:00 a.m. MT
2. -  [x] Add appt data for C&P appointment use test user claudia.c.lapomarda@id.me for canceled and past appt
      -  Past appt - Claim exam, Appt date September 3, 2023 at 10:00 a.m. MT 
3. -  [x] Add appt data for Telehealth Video- Onsite to demo mode, use test user alfred.castillo@id.me
       - Upcoming appt - Sept 20, 2023 at 4:00 PM Mental Health

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 
  - Test above have same password as Judy Morrison
  - Use dynamic date method to always have the above appointments shown in upcoming/past accordingly

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by TKDickson** [comment]
Not seeing these appointments in the build from this branch, pinged Dylan in slack

**Comment by TKDickson** [comment]
Was looking for them on the dates in the ACs, but they're actually more cleverly added:

> they will forever be 10 and 12 days in the future
> The mental health one will always be 5 days in the future
> there will also be a past claim exam 2 days in the past

**Comment by TKDickson** [comment]
Found #7035 while confirming the demo mocked data. This all looks accurate for now! OK to merge to develop.
