### ISSUE TITLE
Travel Claims - UX Design Mockup - Submit Claims on Eligible Past Appointments

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6681]
**Purpose:**
- Mobile is starting work on allowing Veterans to submit a travel claim reimbursement request for past appointments in the mobile app
- Minimum Viable Product AC for inclusion in Appointments
    1.) User navigates to Health/Appointment/Past
    2.) For an eligible appointment, user sees option to start a travel claim
         

- Eligible appointment = Veteran is Checked-In and appointment date is < 30 days old

    ~~3.) User sees messages on tasks to do before submitting a claim and getting reimbursed. User is redirected to do these tasks~~
    ~~4.) For users who have already successfully submitted a claim and got reimbursed, do not show message(s) in step 3~~
    5.) User submits a claims
    6.) User tracks claim status

**Other info:**
- Analytics only has 1 point tied to this project for this sprint, feel free to engage Greta to get analytic thoughts for the design - Analytics will be involved more in future sprints
- FE does not have capacity this sprint, however FE lead will answer any questions needed when doing design 
- Intent is after mock-up designs get PO (Rachel feedback) and then work with other teams to get their feedback, I am planning on having the sprint after this to also be design work as well
- Andrew (BE) will be able to provide information as to what data attributes will be available for UX to use 

**Ask:**
Come out of the sprint with:
- [x] [Mock-up designs ](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=1611-155&mode=design)
- [x] Any new questions that come up feel free to post on DSVA travel-pay channel

**Comment by kidlaurenpeace** [comment]
Stakeholder meeting 9/13 decided against the need for support copy describing tasks or to-dos, so we omitted it from the initial flows.
