### ISSUE TITLE
Travel Claims - Analytic Support - Submit Claims on Eligible Past Appointments

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6683]
**Purpose:**
- Mobile is starting work on allowing Veterans to submit a travel claim reimbursement request for past appointments in the mobile app
- Minimum Viable Product AC for inclusion in Appointments
    1.) User navigates to Health/Appointment/Past
    2.) For an eligible appointment, user sees option to start a travel claim
         - Eligible appointment = Veteran is Checked-In and appointment date is < 30 days old
    3.) User sees messages on tasks to do before submitting a claim and getting reimbursed. User is redirected to do these tasks
    4.) For users who have already successfully submitted a claim and got reimbursed, do not show message(s) in step 3
    5.) User submits a claims
    6.) User tracks claim status

**Other info:**
- Analytics only has 1 point tied to this project for this sprint to help with early designs, Analytics will be involved more in future sprints as designs get more defined
- Andrew (BE) will be able to provide information as to what data attributes will be available for UX to use 
- Planning next sprint to also include design post feedback 

**Ask:**
Come out of the sprint with:
- [ ] Support of UX designs for analytic tracking

**Comment by g-opzt** [comment]
Blocked until meeting with design/content on 9/20 to have sufficient information to work.

**Comment by g-opzt** [comment]
Attended mid-sprint sync call. Discussed flow and content factors that could impact what we are able to understand about incomplete claims. Actual implementation of analytics should be relatively small or already covered by existing screen views and error capture analytics. Aside from this advising/discussion, no further work to be completed this sprint other than monitoring developments so closing this ticket. 

So long as final design does not vary drastically from current plan, discussed with @bischoffa that a final follow up analytics ticket will not be very large (I'm currently estimating 2 points).
