### ISSUE TITLE
Integrate with existing lighthouse labs and tests service

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6685]
AC:
- [ ]  Create endpoint(s) necessary for a user to be able to view their medical labs and test results as text in the app
- [ ]  Add specs for new requests
- [ ]  update docs for new endpoint(s)

Notes: Address the concerns in the discovery ticket. Additionally you may need to update the service with a few more LH API connections in order to capture all the data a user might want. See Andrew's notes in [discovery](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/3427). Lighthouse health api - `lib/lighthouse/veterans_health/client.rb`

**Comment by bischoffa** [comment]
Removed label as Matt informed this was part of the big generic BE initiative bucket during the past sprint planning. Matt mentioned BE is working to split up the large bucket 

List of projects [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/vets-api-unused-services/vets-api-unused-services-explanation.md](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/vets-api-unused-services/vets-api-unused-services-explanation.md)

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/85259d00-f64a-48bb-93bc-f8d4bbea0659)

**Comment by jperk51** [comment]
Closing. Work will cont in next sprint in #6834
