### ISSUE TITLE
BUG - sev3- Facility contact number showing as null-null for Video appt types (GFE & Home)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6687]
## What happened?

While pulling some documentation together from appt content audit, I noticed a potential bug that may be in production.   

Wanted to double check if it is staging data issue or not before spinning up a ticket.

There are 2 Video appts in which the facility number is showing as null-null

1) Video Connect-home appt for 10/2 at 10:00 a.m. EDT 
2) Video Connect appt -GFE date 10/16  at 9:30 AM 

Test user: alfred.castillo@id.me
PW; same as Judy

## Acceptance Criteria:

1) Validate if we are not mapping facility contact info for these appt types

Screenshots attached

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63ef4b0c1af90e57e2b3eb709ee5ae8565968fb0/IMG_8084.jpg)

**Comment by MekoHong** [comment]
issue added post planning.  Jason has bandwidth to review added to sprint

**Comment by cadibemma** [comment]
After investigating this issue, I believe this is an issue with the user's (alfred.castillo@id.me) data and not with the mapping of the facility contact info. 

Alfred's phone info was returning null for most appointments (VA, Video-Connect-Home, Video-Connect-GFE). Checked staging using Judy (who has VA, Video-Connect-Home, and Video-Connect-ATLAS appts ) and was not able to replicate issue.  Also checked staging using Cecil Morgan (who has VA, Community Care, Video-Connect-Home, Video-Connect-GFE, and Video-Connect-ATLAS appts) and was not able to replicate issue. Judy and Cecil's appts all included phone info.
