### ISSUE TITLE
Investigate vet360 linking issues

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#6688]
We recently added some logging around the vet360 linking efforts. A quick look at the logs shows that we are getting some linking successes as well as many linking failures. However, it looks like the failures frequently retry. The job has `retry: false` so this shouldn't be happening. 

There's also [this](http://sentry.vfs.va.gov/organizations/vsp/issues/212399/?environment=production&project=3&query=is%3Aunresolved+mobile&statsPeriod=14d) error. Ask around about why that happens and whether it makes sense to continue attempting to link for those users. 

Acceptance Criteria:
- determine why job is retrying and fix 
- look for any other insights around this. So far there only appears to be one "regression" from linked to unlinked. Look at why that may be. 
- determine whether if any of this logging is no longer valuable and remove if so
- determine whether or not we should continue retrying for users without ICNs with signing authorities.

**Comment by Tonksthebear** [comment]
Huge discussion ended up spawning off of investigating this https://dsva.slack.com/archives/CSFV4QTKN/p1695147661857419

**Comment by Tonksthebear** [comment]
SIS is attempting to fix this issue. It should hopefully resolve itself after their fix
