### ISSUE TITLE
Service Blueprint/User Journey for the Design System

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#6690]
Creating a resource that explains what a user should expect from building functionality using the Mobile Design System.
Audience is external teams and stakeholders, but can be in draft state for this story.

Estimate = 1 Kelly, 5 Ameet, 5 Jessica

AC:
- [x] Determine which users to include
- [x] Determine which user journeys to include
- [x] Create service blueprint template
- [x] Create Mural/FigJam with draft service blueprint(s) for using the Design System
     - [x] Designers
     - [x] Developers
- [ ] Work with developers on developer journey
- [ ] Determine next steps

**Comment by bischoffa** [comment]
Carryover ticket from Sprint 81 into Sprint 82 .
