### ISSUE TITLE
FE: Implementation – Remove Icons from Buttons

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#6695]
## Description 

Related to ticket [#5677](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5677)

As part of this story we wanted to take a look at the attachment button and how it compares to the standard button component that is used most often throughout the app. During this exploration, we realized that the only places that we use icons inside of our buttons are within secure messaging and Rx (“Go to My VA Health” button). 

## Ask
  
To help ensure consistency in the mobile app, we are making the following recommendations:
- [ ] Remove all icons that are currently found within the buttons of secure messaging. [Figma file for reference](https://www.figma.com/file/4mitPba7RfRMrEKbxxQXAO/%235677-%E2%80%93%C2%A0Updating-Attachment-Button?type=design&node-id=273-11194&mode=design&t=iGfPNEwC7yJXtSdU-4).
- [ ] Remove the icon within the [attachment component](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=3859-9433&mode=design&t=reiP3fduigNZhGyz-4).

**Comment by Sparowhawk** [comment]
this will be taken care of with the VA button propagation tickets this upcoming sprints
