### ISSUE TITLE
FE: Implementation – Removal and Relocation of External URL Button

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#6696]
## Description 

Related to ticket [#5677](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5677)

As part of this story we wanted to take a look at the attachment button and how it compares to the standard button component that is used most often throughout the app. During this exploration, we realized that the only places that we use icons inside of our buttons are within secure messaging and Rx (“Go to My VA Health” button). 

## Ask
  
To help ensure consistency in the mobile app, we are making the following recommendation:
- [ ] The button that is currently being used within the Rx screens for “Go to My VA Health” should not be a button, but should instead be a text link (“Click for Action” link component) that is nested within the alert box on that screen. [Figma file for reference](https://www.figma.com/file/4mitPba7RfRMrEKbxxQXAO/%235677-%E2%80%93%C2%A0Updating-Attachment-Button?type=design&node-id=273-11133&mode=design&t=iGfPNEwC7yJXtSdU-4).
     - It appears that initially, the plan was to include to include the “Go to My VA Health” link within the alert box as a text link, but at some point there was a change that resulted in this being swapped out with a button, based on the screens [shown in the Rx Refill 1.0 file](https://www.figma.com/file/DASXMhE1OZgTrpIqk4LXiE/%F0%9F%94%8D-Rx-Refill-1.0---Working---VAMobile?type=whiteboard&node-id=418-10401&t=mdpBc2VctdexrRA2-4).

**Comment by Sparowhawk** [comment]
this has already been completed when we migrated to the design system's link component.
