### ISSUE TITLE
Add analytics: Capture users WebView browser type and version

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6734]
- [ ] Adjust Firebase analytics to capture what browser and browser version app users are taken to when in a Webview. 

## Background
* On 9/14 a potential login bug was surfaced (see conversation on DSVA slack [here](https://dsva.slack.com/archives/C018V2JCWRJ/p1694654535598999)).
* As part of investigating, we wanted to see how many users were specifically using Firefox as their default browser as that seems to be the affected group.
* Firebase analytics does bring in the fields that appear that they could/should be capturing this.

**Comment by Sparowhawk** [comment]
@g-opzt 

so with further look into webviews, at least for iOS it isn’t possible to get their default browser
I can check if we can launch a specific browser and basically it would tell us which ones are installed on the phone
then we can potentially force the user to use a specific browser
but that is about the best I can do for the analytics

I can't get the version at all.

The same limitations are more or less their for android though I may be able to get the default browser there, but it doesn't necessarily guarantee that is the browser they are using in the app.

**Comment by bischoffa** [comment]
@ajsarkar28 for awareness as this would come through the Analytics epics.

**Comment by g-opzt** [comment]
Confirmed with @dumathane that the value of tracking this in analytics for future issues is very low and not worth the effort it will requires for the quality of data we would get in return.
