### ISSUE TITLE
SM Login Issue - Error Message and Content Design - Bug 5986

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6737]
**Purpose:**
- Create a new alert message and content to better match the issue in ticket 5986 ; can do this by leveraging what MHV SM shows today in the web. 
- Veteran with premium account does not always get premium account access in mobile; thus need a message to tell them what to do when this happens

**Other Info:**
- We originally did this work in 6570 but Rachel on 9/14 indicated that we need new alert message / content specifically for this issue
- OG thought was to use the existing error message we had vs something new
- Tied to [Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1694694600327349)
- Per Brea,  I have the screens [in Figma](https://www.figma.com/file/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?type=design&node-id=1212-6891&mode=design&t=NtYtOiI444zega9S-0) where Misty can update that content. If she runs into any issues or needs me to make any adjustments to the design to help better accommodate the content, I'll be on standby to make those updates.

**Actions:**
- Create copy that mirrors MHV Web's alert message for Mobile to create and use for the alert message
- Suspect we will have some wiggle room but want to use MHV SM copy as the main inspiration

**Comment by bischoffa** [comment]
![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/dda6b593-738c-4bff-a0dd-93b0a315c26b)

**Comment by mistymg** [comment]
Yea, no design should be needed. This is really just content.

**Comment by mistymg** [comment]
A few open questions I have:

- Will this error message always show just for people who definitely have a premium account but we're not getting that information? Or could it possibly show up for people who don't have a premium account?

- If the only solutions is for the user to call the help desk, what exactly does the user need to tell the help desk? The issue is technically on us...not the user. But we're making the user fix it. So we want to be super clear on what they need to say to the help desk to get it resolved.

**Comment by bischoffa** [comment]
Intent is to only show it for those experiencing the issue. This is done based on the triggers BE identified in the original ticket.   
  
Only solution for the short term is for the user to call back. Long term MHV needs to expose an endpoint for SIS to integrate with and use. This issue is something MHV SM has known about but mobile is just not finding out about, so I question if it will be something they will start moving on. It possible this gets resolved as they migrate away from MHV login.  I am curious what explicitly web uses for us to say so to your point we can be extremely clear and directive for the veteran.

**Comment by mistymg** [comment]
No work was actually done for Sprint 80 on this. Will move it to Sprint 81.

@bischoffa Any updates on this? Have we heard anything from MHV team on if they have this error on the web side?

**Comment by bischoffa** [comment]
@mistymg still no updates. I am not being sent to Rachel's peer on MHV. Sending out an email today. I would say plan this not for this sprint but the following cause of that.

**Comment by mistymg** [comment]
Confirmed with Adam that we'll move this to sprint 82

**Comment by bischoffa** [comment]
Blocked as MHV SM has not provided content. From documentation it seems they themselves do not know. Told to reach out to Content Team which Misty is submitting an intake form request to do so. Also told to reach back out to Bryan Riley.

**Comment by bischoffa** [comment]
Bryan from MHV SM looking into it further,  no updates . still blocked

**Comment by mistymg** [comment]
Still blocked also on my end as I haven't heard yet from CAIA team. [CAIA ticket I submitted](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66458)

**Comment by mistymg** [comment]
Chatted with Danielle about how to proceed on 10/10. She asked that we set up a meeting with her and Laura W (and Janie Tankard-Carnock and Coulton Bunney). I asked Adam (PM) to schedule a call between all of us to get on the same page about what the issue is.

**Comment by bischoffa** [comment]
Providing this update to MHV Weekly Standup Today. We will see if anyone else wants to be added then will schedule.

**Comment by bischoffa** [comment]
Meeting scheduled for 10/25 9:35am - earliest I could get all the required VA folks. Ticket will be blocked until at least that date. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTB0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66641a409b8029a8c52e08f9b0f7fa125facc84e/image.png)

**Comment by mistymg** [comment]
Removing this from blocked as we still meet on 10/25

**Comment by mistymg** [comment]
[DSVA Slack thread with meeting notes/next steps](https://dsva.slack.com/archives/C04DRS3L9NV/p1698242434940089)

**Comment by bischoffa** [comment]
Moving it to blocked and out of the sprint. Blocked until we hear back from CAIA team on their follow-up items.

**Comment by mistymg** [comment]
Worked with Laura W on copy for Solution #2 in [Figma](https://www.figma.com/file/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?type=design&node-id=1212-59&mode=design&t=rfyEykdOR3ogWV5P-0)

Still don't know about Solution #1

**Comment by mistymg** [comment]
BE implemented fix so no need for new error message.
https://dsva.slack.com/archives/C018V2JCWRJ/p1711028876365279?thread_ts=1710874599.292759&cid=C018V2JCWRJ
