### ISSUE TITLE
Design System: Alert Box - Align with VADS and publish documentation

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6745]
### Description
Before implementation, we need to align this component with VADS and write documentation.

#### UX refinements
- [x] Audit component with VADS to determine if we need to update it to be more aligned
- [ ] Update component in Figma based on alignment decisions - will be addressed in a separate ticket once the Button and Link components are updated

#### Documentation
- [x] Update Figma design library
     - [x] Update component template and assets panel
     - [x] Update metadata with description, link and alternative names
- [x] Write [documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Alerts%20and%20Progress/AlertBox/)
- [x] Review with UX team
     - [x] Review accessibility with Brea
     - [x] Review content with Misty #6896
- [x] Publish documentation to doc site
     - [x] Add link to component in Figma design library
- [x] Update [component documentation spreadsheet](https://docs.google.com/spreadsheets/d/1_EAH2LWSzwF8Om7o4LAYJf6gT9UWENANYpF7SZy3j8w/edit#gid=0)

**Comment by bischoffa** [comment]
Carryover ticket from Sprint 81 into Sprint 82 .
