### ISSUE TITLE
DevOps and Release Management Improvements - Q2

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6761]
# Project Status Overview

### Project Objective:

Work and effort for Quality Assurance and Release Management (Qart) to improve Mobile DevOps and Release process. 

Items may include:

- Release documentation (process maps, steps, reports)
- QA build improvements / fixes 
- CI changes 
- Maintaining App Store requirements (certifications, etc) 
- Relevant Slack messaging 
- Documentation to explain mobile app release process 

 ### Stakeholder Updates

|Date| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|April 2024 | Green | Project was prioritized for Q2. Charnelle's capacity will focus solely on this work. Charnelle to collaborate with Tim on ticket prioritization and then Charnelle will size the tickets based on her knowledge. With Charnelle being new she will also learn about Mobile system as she works on these tickets which will increase her proficiency and efficiency on these tickets. Charnelle is working with Narin, Tim and Binny as need arises. Completed Accessibility Assessment on the VA Mobile Docs site which Tim is currently coordinating with FEs to fix. |  None | 
|5/6/24 | Green | Working on a ticket to require QA approval before a ticket gets moved into a release | None |
|5/20/24| Green | Completed work on the ticket that will automatically block a pr merge before QA approval [6261](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6261) - currently awaiting peer review | None|  
|5/29/24| Green | Charnelle is working on adding documentation to main a list of QA members for the PR check approval process. Will be adding it to the QA Github Page in the DevOps folder.  She is also working on Slack alerts when Approve command fails. Further she has started reviewing and sizing this epic's backlog. | None |
|6/7/24| Green | Approve command fail work was merged. Completed development on Slack Alert for when release builds fail, just waiting for a review. Identified and merged some QA approval workflow changes. Next steps is to document QA Approval Process. | No blockers | 
|6/17/24| Green | No change given offsite that happened between last update and this one.  | No blockers |
|6/26/24| Green | Added documentation to Github on maintaining the [QA/Engineering Review list](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Maintaining%20QA%20and%20Engineer%20Reviewer%20Lists%20in%20the%20Workflow.md) on the approval workflow that is being PR. Received Android Play Store notification we need to update to Android 14 before 8/31/24 - coordination within DevOps on researching as it indicates a backward incompatible change due to security reasons | Awaiting PR review on automating blocking of PR merge without QA approval | 
|7/10/24| Green | Reopened ticket for QA Approval Process, addition testing taking place. Backlog grooming took place and prioritized several groomed tickets. Android notified VAHB about a new SDK version coming up that they indicated will introduce backwards-incompatible changes, Tim is researching this. | No blockers | 
|7/24/24| | Green | Q3 planning in which another epic was created for Bugs/Maintenance just for Q3 and have to move over the backlog of tickets to the new epic.  Backlog grooming between Tim, Narin and Charnelle to ensure tickets were sized, reviewed and ready for the new prioritization set by the team. Modified QA approval being needed to merge PRs - engineers / ticket writers will need to ensure tickets are tagged properly so that this works | No blockers |

|8/7/24| |In progress| Image Optimization for app store store ticket is on going. Testing and review taking place. In addition, accessibility check bug fixed
|8/21/24|
|9/4/24|

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal & external dependency  |  Determination on how the external team will engage with Mobile - through Flagship or directly with Qart |
| Internal & external dependency | Determination on how non-Mobile VA POs are involved in the release process |
|  |   |

</details>

# Detailed Project Scope 

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.) Work on this epic will ramp up as DevOps resource becomes more comfortable and familiar with materials 
 
 2.) When engineering resources are needed to assist Charnelle, they will be prioritized by Tim 
 
 3.) 
 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.) DevOps resource is new to the Mobile team and to Mobile processes 
 
 2.) No engineering resources allocated to Qart team, will need to be prioritized / pulled from other Mobile teams 
 
 3.) 
 
 
</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Mobile processes | Web processes | 
| Mobile release | Web releases | 

</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Don McCaughey

**Ad Hoc:** 
- **Mobile Team**: Qart
- **Mobile Team PM:**  Adam Kasmier 
- **FE Engineering:** None 
- **BE Engineering:** None
- **Design:** None 
- **Content** None 
- **DevOps** Charnelle
- **QA:** Charnelle
- **Mobile Teams that are involved:** Will pull in engineering resources from other teams as needed

</details>

### Questions 
<details>
<summary>Open Questions</summary>
 
 - How are we measuring success? 
 
 - What is MVP and what is out of scope?
   
 - Has there been existing research or work done on this project before?
   
 - Is this work being done within the VA today (ex. web) 
 
</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer | Owner |
|--------|----------|------|
| | | |
| | | |

</details>

### Change / Decision Log 

Product will need to create on in the Github folder and link it here.

**Comment by bischoffa** [comment]
@kellylein @TimRoe is this design system work (per the label) or being moved over to the QA / Release team per Kelly's updated assignment? One thing to call out if it moves over to QA / Release team - we have no engineering resource so the tickets that have spawned out of the work requiring engineering will not be completed within the QA / Release team.   
  
If moved over to QA / Release team I will need more information as details are pretty light. @kellylein can you move this over into the epic template and fill out the information based on the work that has been done on this since October? This will also help me understand what this project is and what work is needed / planned for the rest of the quarter in Mobile SoS board. Later we can figure out how this will will be done with no engineering resources.

**Comment by timwright12** [comment]
This is an epic Kelly and I were using to house all the release management work. I updated the label to reflect that (we had been using release-mgmt for the underlying tickets, but I see you also have "QA and Release" - feel free to update the tickets - up to you). The expectation here is that the tickets will likely sit (or I might chip away at them myself) until we can hire a devops person after the new year to start working on them.

**Comment by bischoffa** [comment]
Thanks.  This project was not talked about with Matt when scoping the work so I do not expect that QA and Release team to consider this work until Matt is back or later as I assume there will be some discussion.

**Comment by timwright12** [comment]
yeah, we need to hire someone first, so it'll be sitting for a while

**Comment by bischoffa** [comment]
Ticket not currently planned for 1Q as no DevOps person yet. Project will be revisited if/when DevOps person is hired.

**Comment by TKDickson** [comment]
Moving to the Q2 consideration column (FYI @bischoffa and @kellylein) since 1) there are tickets from this epic actively being worked right now, and 2) (more importantly) because we have a DevOps Eng on the team.

**Comment by bischoffa** [comment]
Target date is end of Q2. New epic will be stoodup for Q3 if more work is needed.

**Comment by bischoffa** [comment]
Going to close this epic and move the tickets to Q3 DevOps epic.
