### ISSUE TITLE
Investigate Datadog service graph functionality

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6768]
Tim shared this link from the [datadog docs](https://docs.datadoghq.com/tracing/services/services_map/). Do some digging into it and report your findings. If it seems useful or possible we could set up a service graph go ahead and make tickets for doing so. 

ACs:
- [ ] Dig into datadog service graphs
- [ ] Make a test/example (if applicable)
- [ ] Make follow up tickets to build out a full service graph for us (if applicable)

**Comment by kpethtel** [comment]
Closing in favor of [this](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7121)
