### ISSUE TITLE
Automation - Fix Google Auth Issue

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6775]
# Automation Ticket

There is an issue on Google's end where authenticating with the Play Console sometimes does not work, which will cause the release automation to fail. Fastlane has released a new version with an added retry setting that should help to resolve this issue.

## Type of Change
- [ ] Update existing automation
- [ ] Add new automation functionality
- [x] Fix automation bug

## What systems/scripts are changing?
- [ ] Git Hub Actions
- [ ] CircleCI
- [x] Fastlane
- [ ] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

Update to the latest version of fastlane and add the `SUPPLY_UPLOAD_MAX_RETRIES` setting as described in this issue thread: https://github.com/fastlane/fastlane/issues/21507#issuecomment-1723116829

## Acceptability Criteria

- [ ] Fastlane has been updated and `SUPPLY_UPLOAD_MAX_RETRIES` setting is added

**Comment by bischoffa** [comment]
@jennb33 @narin You added this to Sprint 80 but is in New Issues. Is this ticket being worked on? 

Is this work continuing into Sprint 81

**Comment by narin** [comment]
@bischoffa @jennb33 A fix has been merged but we won't be able to confirm it resolved the issue until our next release build, Oct 4.

**Comment by narin** [comment]
Confirmed that this fix resolved the issue with [today's release build](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/6396924180). Closing out.
