### ISSUE TITLE
BUG - sev-3 - Android - Snackbar should never be null, but sometimes it is - review logging 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6789]
## What happened?
Work was done in ticket [5401 ](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5401)on this issue. Logging was added. This ticket is to check the logging to see if we can learn anything more about this issue. 

It will be in icebox till at least ~mid October. Logging gets release 10/10 then need a couple weeks in production to see if we can find anything more specific. 

## Steps to Reproduce

We don't know the steps to reproduce, unfortunately -- can see the crash logs linked from the original ticket (#4496), and the first step of whichever Eng takes this would be to try to track down where they're coming from, and add that info to the ticket.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/testing/VA%20Mobile%20App%20Test%20Plan.md#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@bischoffa @g-opzt I took a look in firebase analytics and apparently there isn't any parameters being sent up with the analytic we added. I have no idea why as we hard code where it crashes. Are either of you seeing it differently for vama_snackbar_null?

**Comment by Sparowhawk** [comment]
@g-opzt @bischoffa from what I can tell with previous crash logs is that when the app starts up the reference is null sometimes for the Toast container. I think I found a kind of hacky solution to fix it looking at the dependency issues. This dependency is no longer support by the author and hasn't received updates in sometime.

**Comment by Sparowhawk** [comment]
the crash is due to calling hideAll on snackbar that is null

The patch I was trying isn't possible  with the useRef hook that is used, it only accepts null or a Toast type, which I can't create right there.

My recommendation is we don't change anything since the current state of the app is my recommendation. The user still sees snackbars when they are supposed to.

**Comment by bischoffa** [comment]
@Sparowhawk thanks for your work on this. I would agree with your recommendation. I am closing this ticket. No further action is needed.
