### ISSUE TITLE
add logs on click with modal, color accessibility and general polishing of visualization test suite

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#6797]
repo: https://github.com/adhocteam/va-mobile-tests

See sprint 0 doc for further implementation guidance:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/BE-status-visualization/BE-status-visualization-sprint-0.md

**Comment by aherzberg** [comment]
running into some issues with getting firewalled. see convo: https://dsva.slack.com/archives/CSFV4QTKN/p1696438907546719

**Comment by aherzberg** [comment]
moving firewall issue to it's own ticket https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6947. will have PR up today for remainder of changes. This ticket took some extra time has I added all upstream services in the following new format: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2daQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beb17c173b4a045de1c44f7f511da2385f28090d/Screenshot%202023-10-09%20at%2010.10.56%20AM.png).
New verisons of chrome broke the chrome driver which required more then a reinstall of the driver.

**Comment by aherzberg** [comment]
PR created: https://github.com/adhocteam/va-mobile-tests/pull/13

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by aherzberg** [comment]
updated to 13 due to some unforeseen issues such as creating a rails project, getting firewalled, chrome driver install issues and manually sorting and placing of nodes rather then using an algorithm
