### ISSUE TITLE
Investigate React Query Demo Mode Options

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#6798]
## Description

Currently demo mode is centered around the Redux store's `demoSlice`. This approach still works with React Query, since queries and mutations are ultimately making API calls that are being mocked and updated in the store, but it would be good to look at alternative solutions to see if we can remove the need for using the Redux store for async calls in demo mode. It could be that using the Redux store is still the best aproach, since the infrastructre is in place and already works well.

One alternative could be to use an API mocking library like [msw](https://github.com/mswjs/msw) to mock API requests.

## Acceptance criteria

- [ ] Investigate alternative ways of handling demo data with React Query
- [ ] Create appropriate implementation tickets if a better approach is discovered

**Comment by Sparowhawk** [comment]
upon review of the library it is my recommendation that we migrate the json mocks over to using msw and not the redux store. It would help in the epic #8080 that is updating our demo mode data to break the mocks out into separate files for each api, it would also benefit us by updating our data. The added benefit of using msw is that the unit test json mocks will no longer be needed and detox and unit tests will be more aligned. 

I have included setting up msw and migrating over as a requirement in the 8080 epic which will then be broken down further to other tickets once we get to them.

**Comment by Sparowhawk** [comment]
leaving this in code review until FE Sync to discuss with everyone else
