### ISSUE TITLE
BUG - Sev-3 - iOS (notched devices) - Remove white background in landscape for veteran status card 

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#6800]
## What happened?

Another issue with the iOS white background thing after rotating from portrait to landscape.  This was fixed for onboarding and the home screen ([4977](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4977)).

## Specs:

- Device: [iOS notched devices](https://apple.fandom.com/wiki/Notch)
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Navigate to the veteran status card
2. Rotate the device to landscape.  Notice the white bars to either side.
3. Rotate the device to portrait. Notice the background is all blue

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f6d4d2981f6e7cdcfaa3bb21c2a20b995d87abee/A8FA0848-9E9C-452B-B8A1-22C0D5D7B040.png)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
@rbontrager has this ticket been scrubbed?

**Comment by rbontrager** [comment]
Verified that the white background is no longer there for iOS (notched devices).  Approved by QA.
