### ISSUE TITLE
Add image optimization into CI for app store submissions

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6809]
We want to put some level of image file size optimization into the process to reduce the size of the files, which should help upload times and bundle size.

This compress can be added to each build, should be pretty lightweight.

We should probably add this optimization step to the release build workflow before we submit to the app store. If we decide to do this step anywhere before the release workflow, we'd need to make sure that we commit the updated images back to the repo.

One possible CLI tool we can use is [ImageOptim](https://github.com/JamieMason/ImageOptim-CLI).

**Comment by bischoffa** [comment]
Adding next sprint to this ticket given this is carryover
