### ISSUE TITLE
Automate the notification of the release ticket to assigned people

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6812]
The release issue is auto-assigned to folks and there should be an email notification, but PMs also spin up a slack thread on it. We should be able to automatically fire off a slack thread when the release issue is created pinging all related parties and also send out approval reminders as needed.

[Example thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1722428026986259)

## Acceptance Criteria

- [ ] The PM Slack thread for release coordination is automatically created
- [ ] The [people listed on the release issue](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/ISSUE_TEMPLATE/release_ticket.md) are all pinged in Slack (will require a mapping from github username to Slack name)
- [ ] The conversation thread should be filled out as much as possible compared to the linked example

## Slack ID mappings

| Name | Github Username | Slack Member ID |
|-----------------|-----------------|---------------|
| Tim Wright | timwright12 | U01DBDAJZ18 |
| Don McCaughey | DonMcCaugheyUSDS | U06PCD1R0EL |
| Tom Gammons | DJUltraTom | U02BBL9L0CU |
| Chris Johnston | chrisj-usds | U7C369Q2X |
| Jen Ecker | drjecker | U01FY4VEHJ9 |
| Rachel Han | rachelhanster | U047Q1LKDFY |
| Kelly Lein | kellylein | UJHA49K6X |
| Charnelle Domguia | IsraelleHub | U06N7M2QSUA |
| Therese Dickson | TKDickson | U02PJLJ0H6H |
| Alayna Abel | ala-yna | UQC180926 |
| Ameet Sarkar | ajsarkar28 | U05BNQLJ9UZ |
| Jon Binbuetel | dumathane | U02RC1BRZBP |
| Ryan Thurlwell | rtwell | UEY4D750B |

**Comment by timwright12** [comment]
Added some acceptance criteria to this ticket

**Comment by timwright12** [comment]
Updated the ticket with slack member ID mappings

**Comment by IsraelleHub** [comment]
Added Ryan slack User ID
