### ISSUE TITLE
Investigation - Appointments Cancellation Errors

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6817]
[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/14995/?environment=production&project=3&query=is%3Aunresolved+mobile&statsPeriod=30d)

ACs:
- [ ] Determine if these errors are expected or not
- [ ] if so, try to figure out a way we could possible mitigate them or preemptively stop the user from take the erroring action
- [ ] if not, determine what's causing the unexpected error and put together the necessary tickets for the fix

Timebox this to 3 pts.

**Comment by Tonksthebear** [comment]
VAOS said that this error occurs when a user tries to cancel an appointment but the appointment site uses a privileged user list that the user is not on. They're pushing out an update this week that should handle this situation more gracefully and significantly lower this error rate

https://dsva.slack.com/archives/C023EFZPX4K/p1696266854238619?thread_ts=1696266606.667879&cid=C023EFZPX4K

**Comment by Tonksthebear** [comment]
They also said that `isCancellable` does not take this privileged user list into account and it's not easy to make it so that it does. It seems we'll just need to make sure that we handle the error in a graceful way for users in the app

**Comment by Tonksthebear** [comment]
The linked ticket also references the wording of the exact error if we should to handle it in a specific way
