### ISSUE TITLE
Investigation - RX Refill Errors

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6820]
[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/200852/?environment=production&project=3&query=is%3Aunresolved+mobile&statsPeriod=30d)

ACs:
- [ ] Determine if these errors are expected or not
- [ ] if so, try to figure out a way we could possible mitigate them or preemptively stop the user from take the erroring action
- [ ] if not, determine what's causing the unexpected error and put together the necessary tickets for the fix

Timebox this to 3 pts.

**Comment by Tonksthebear** [comment]
It seems like this it a known issue that has already been d[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVgvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--42ecd0618f6763e1a4ba36d507254609f5f1841e/screenshot_2023-10-03_at_10.22.59_am_720.png)
ecided as inevitable in the past
[Uploading... screenshot_2023-10-03_at_10.22.59_am_720.png] the team responsible is only accessible via email so if we need to investigate further it will require email
