### ISSUE TITLE
Investigation - Payment Info Restriction Indicators Errors

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#6823]
[Sentry Error](http://sentry.vfs.va.gov/organizations/vsp/issues/196588/?environment=production&project=3&query=is%3Aunresolved+mobile&statsPeriod=30d)

ACs:
- [ ] Determine if these errors are expected or not
- [ ] if so, try to figure out a way we could possible mitigate them or preemptively stop the user from take the erroring action
- [ ] if not, determine what's causing the unexpected error and put together the necessary tickets for the fix

Timebox this to 3 pts.

**Comment by cadibemma** [comment]
Confirmed that this issue is not preventable but it's not caused by anything on our end. This error is only occurring for EVSS users.
