### ISSUE TITLE
Monthly mobile app review analysis: September

### ISSUE THREAD

**Issue by lstraghalis** [department-of-veterans-affairs/va-mobile-app#6825]
In order to stay current on what Veterans think of our mobile app, we analyze qualitative comments left on mobile app reviews on a monthly basis. We currently use a basic (free account) on the AppFollow platform. The platform recently changed their free features - we no longer have access to download app review data using custom date ranges.

Research needs to work with our FE engineer to download the September app review data. Research will analyze all September monthly reviews and prepare a high-level summary and post to github. We will also share these findings with our VA Product Owners.

## Acceptance Criteria
  

-  [x] Work with Jon B to get access to September app reviews
-  [x] Download data into centralized format 
-  [x] Analyze data with tags
-  [x] post to gh and share with POs during SOS

**Comment by lstraghalis** [comment]
@dumathane do you think this ticket is feasible for someone in ENG to do between 10/2 - 10/4?

**Comment by dumathane** [comment]
Yup. I'll take care of this one @lstraghalis .

**Comment by lstraghalis** [comment]
thank you!
