### ISSUE TITLE
Update Storybook for Segmented Control

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6826]
- [x] Remove app-specific content from labels and make them more generic (maybe Label 1, Label 2)
- [x] Create variations for additional segments
     - [x] 3 segments
     - [x] 4 segments
- [x] Create variations for both light mode and dark mode that does not depend on system settings
- [x] Remove [Storybook intro text](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/segmented-control--two-segments) or update to match [doc site](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Components/Navigation/Secondary/SegmentedControl/)
     - **Current**: A component used to switch between related views of information within the same context
     - **Doc site**: A segmented control is used to switch between related views of information within the same context.
- [x] Share updated Storybook links with @jessicawoodin

**Comment by TimRoe** [comment]
Per the AC, @jessicawoodin the updated links should be same as before then:
- `segmented-control--2-segments`
- `segmented-control--3-segments`
- and `segmented-control--4-segments`

in place of `segmented-control--two-segments`
