### ISSUE TITLE
Update documentation for Segmented Control

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6827]
- [x] Review updated links from engineering
- [x] Update doc site with new Storybook links
     - [x] 3 segments
     - [x] 4 segments
     - [x] Light mode, dark mode

**Comment by TimRoe** [comment]
To [cross reference](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6826#issuecomment-1767181463):
> Per the AC, @jessicawoodin the updated links should be same as before then:
> - `segmented-control--2-segments`
> - `segmented-control--3-segments`
> - and `segmented-control--4-segments`
> 
> in place of `segmented-control--two-segments` once the branch is merged to main and the action is run to propagate the changes to the Storybook.

**Comment by TimRoe** [comment]
Did this not require a PR against the doc site in the VAMobile repo?

**Comment by jessicawoodin** [comment]
It will! I'm batching 3 tickets into one PR (typography page, segmented control, and alert box tickets) so the PR will come through when I finish the alert box ticket. I figured I could close this ticket in the meantime.
