### ISSUE TITLE
Deep Linking analysis - Sprint 81 work

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-app#6830]
- [x] Review analytics data flowing in from new deep linking event created in #6355
- [x] Revise Secure Messaging dashboard to include a deep linking page that includes the MVP measurements described below

## MVP measurements will be of the task, "Read a Secure Message
* Starting point (attempts): How many notifications were clicked
  * Note: There is the non-notification starting point of a user opening Secure Messaging inbox from with in the app that we can compare to for utilization.
  * Event ideally called `vama_notification_click` with parameter `notification_url` (see notes at bottom for more info)
* End point (success): How many SMs opened
  * Note: again, we will compare SMs opened via notification vs notification path.
  * Add event `vama_sm_open` that logs upon click of a specific SM in the inbox with parameters
    * `notification_open` that gathers if it was opened from the notification path and is left null if it was opened any other way
    * `sm_id` that gathers the id of the SM opened

These measurement will be available in a count of total instances and total unique users but **not** per individual Secure Message/notification. We also will not be measuring the total number of notifications recieved.

Known failures we can monitor:
* API call fails
* Log-in fails

Other notes from Theo's demo:
* So long as the user does not close out of the app after clicking notification, we should be able to track them landing them in the SM inbox. (i.e. if the user moves backwards in the authentication process it will not prevent us from tracking if they finally make it through to the inbox).
* It is likely we can do one universal analytic that would track all notification clicks and then gather the link of the notification as a parameter to differentiate them.

**Comment by jennb33** [comment]
This ticket was duplicated from 6610 (https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6610) and the work that carried over into Sprint 81 was for 2 story points, per @g-opzt

**Comment by g-opzt** [comment]
Blocked by BQ access

**Comment by g-opzt** [comment]
Per conversation with team leadership I will continue to not run any additional queries beyond what the existing dashboard queries are pulling so that we can monitor the impact of the dashboards alone more easily. I will be OOO until Oct. 17-22 so we will revisit the status of this blocker on Monday, Oct. 23.

**Comment by g-opzt** [comment]
Most of the work was completed today by restructuring the queries for the dashboard to incorporate the new analytics. Monday, I should be able to complete the dashboard updates, including documentation steps.

**Comment by g-opzt** [comment]
Dashboard is live with the updated documentation and new tiles based on the new analytics.
