### ISSUE TITLE
BUG - Sev 3- All - sighting "Code not in state" "pretty-print" messaging when attempting sign in

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#6832]
## Specs:

- Device: ipad mini, google pixel 4a
- OS:
- User Account: Judy.morrison, +54
- Accessibility State: voice over on.

## Steps to Reproduce

inconsistent reproduction but happened twice on 2 different accounts on 2x devices with the strings build 961 (iOS)
and 886(android) respectively.
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3ZWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e560e640c9bcb926e00aa7020c64d6479620cd8b/IMG_0164.PNG)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3pWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7725f9886447d25dd83e36e1c430c306ffe8f37f/Screenshot_20230925-155814.png)

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic]

**Comment by bischoffa** [comment]
@DJUltraTom has this ticket been scrubbed?

**Comment by TKDickson** [comment]
"Code in state is not valid" is an error I've seen a few times when staging is down. No idea where the "pretty print" came from, never seen that one, but I'm guessing internal testing?

@DJUltraTom when you're back - were you hoping for better error messaging for this? We could try to figure out which auth-related team this is related to, and confirm veterans would see better errors.

**Comment by TKDickson** [comment]
@DJUltraTom pinging on this now that you're back!

**Comment by TKDickson** [comment]
@bischoffa I don't actually think that this would be owned by mobile. This is an error that was appearing in the webview during authentication, so the mobile team work would be to eventually pass an FYI along to the team who owned this. Since it's not happening anymore (unless @DJUltraTom joins in to say that he's seen it recently) I think we should just close.

**Comment by bischoffa** [comment]
@TKDickson thanks. I will go ahead and close it. @DJUltraTom if this is still happening reopen the ticket and add a comment. 

If its open I think it would be global's responsibility to coordinate with upstream teams for future discussion when looking at all the current teams and their roles.
