### ISSUE TITLE
Integrate with existing lighthouse labs and tests service - Sprint 81 carryover

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-app#6834]
AC:
- [ ]  Create endpoint(s) necessary for a user to be able to view their medical labs and test results as text in the app
- [ ]  Add specs for new requests
- [ ]  update docs for new endpoint(s)

Notes: Address the concerns in the discovery ticket. Additionally you may need to update the service with a few more LH API connections in order to capture all the data a user might want. See Andrew's notes in [discovery](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/3427). Lighthouse health api - `lib/lighthouse/veterans_health/client.rb`

**Comment by Tonksthebear** [comment]
Found a bug in the lighthouse client, I have a PR up and it should make all labs and tests work in staging https://github.com/department-of-veterans-affairs/vets-api/pull/14043

**Comment by Tonksthebear** [comment]
The fix worked, these endpoints officially work in staging so closing the ticket out now
