### ISSUE TITLE
SM Login Issue - Discovery 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6851]
**Purpose:** 

- Investigation on what we can tell the Veteran to solve the issue
- Lauren Alexander was reached out to by Rachel and Lauren recommended reaching out to Jason Boire for a solution 

**Action:**

- BE to reach out to Jason Boire
- Document findings

**Comment by TKDickson** [comment]
@StacyB2023 @jperk51 I have no idea what this ticket is, I'm just trying to clean up/add labels to tickets without any. I imagine this likely can be closed.

**Comment by jperk51** [comment]
Yeah I can only assume this was around the issue where folks would not see MHV stuff when the logged into the app because their idme/logingov account was never tied to their MHV account. Closing.
