### ISSUE TITLE
Segmented Control - Fix deprecated attributes

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6857]
## Description

In the segmented control component we have some reported deprecated attributed that should be updated:

- accessibilityRole
- TouchableOpacity
- accessibilityLabel
- focusable

These present themselved in the console of storybook (local, not the [public docs](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/segmented-control--two-segments)

## Steps to replicate

- Locally Navigate to /packages/components inside the [va-mobile-library repository](https://github.com/department-of-veterans-affairs/va-mobile-library)
- Run `yarn && yarn storybook:web`
- Open the console
- View the deprecation messages (image attached) 
- 

## Definition of Done

- [x] The deprecation messages are gone
- [x] The component still works as intended

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUxoIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fd2c4fda8b892583561cd92712d3a915b65a586e/Screenshot%202023-09-27%20at%2011.06.30%20AM.png)

Tangentially related addition:
- [ ] Since this is the last ticketed changes to the Segmented Control, bump [version to 0.1.0 for the components package in accordance with the versioning policy](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/README.md#versioning-policy)

**Comment by kellylein** [comment]
@DJUltraTom part of the QA work for this would be to test out the testing process.  Please add QA estimate.  thank you!
