### ISSUE TITLE
Submit Content Intake Form for Assistance on SM Login Content Need

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6858]
**Purpose:**
- Intake request form needed to get Content Team's help
- Told to reach out to Content team on 9/27 during MHV Standup shared in [Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1695821065165039?thread_ts=1695820196.016549&cid=C018V2JCWRJ)
- Rachel confirmed Danielle is aware her and her team's help is needed for this 
   -  Danielle is OCTO's point person for health related comms

**Ask:**

- Submit Content Team intake form
- Link intake form to this ticket 

**Deliverables:**
[CAIA intake request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/66458)
[Slack thread making CAIA team aware](https://dsva.slack.com/archives/C01K37HRUAH/p1695836500498519)

**Comment by bischoffa** [comment]
MHV Standup informed Mobile on 9/27 that Mobile needs to reach out to Content team to find MHV's content message. Intake form is needed. Misty to submit.

**Comment by mistymg** [comment]
CAIA ticket and Slack thread noted above. Closing this ticket
