### ISSUE TITLE
Integrate Design Tokens with Figma

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#6860]
## Description
Once we have our design tokens in JSON format and published, we want to be able to import them into Figma so that Figma and our codebase can use the same source of truth

## Acceptance Criteria
- [x] Set up a Figma plugin that can consume our [design tokens](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/packages/tokens/src/tokens/colors.json) which are in CTI ([style-dictionary](https://github.com/amzn/style-dictionary/tree/main)) format

**Comment by jessicawoodin** [comment]
While working on the Button component, I was playing around with variables/tokens in Figma. I was curious how a plugin might export the tokens, so I exported it to a json file with dummy data. I'm attaching the json file to this ticket in case it's helpful for you to see while working on this ticket. If there's anything else you'd like to see in Figma, just let me know.

[export.json](https://github.com/department-of-veterans-affairs/va-mobile-app/files/13231054/export.json)
