### ISSUE TITLE
Component App Propagation - Collapsible View

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6866]
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the Collapsible View component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

## Important links

- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] The Mobile app team has been alert to the existence of the new component
- [ ] Areas of the the app that need to be updated have been communicated and documented
- [ ] The new Collapsible View component is implemented in all areas of the app
- [ ] The Mobile apps have been released to their respective app stores with the component installed

**Comment by kellylein** [comment]
This work will be represented by separate Epics for the Flagship teams.  Closing this Story.
