### ISSUE TITLE
QA: Test Plan (Availability Framework)

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#6875]
## Objective 

Today, when critical errors affect the Mobile Application, we currently do not have an immediate way to address them outside of the normal app store release and review process. As a result, users experience broken app features until we are able to push a release.

This ticket supports testing the use cases supporting the [EPIC](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5120) on Availability Framework.

## Reference Material:
Please review the Use Cases listed in the PDF document in the Epic for full details.

- 

## Acceptance Criteria

  

1. - [x]  Create test plan
2. - [x] Link to test case folder in TestRail
3. - [x] List of test data (or other testing needs) for Product
4. - [x] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [x] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
@StacyB2023 will this ticket be included in the upcoming sprint? (Also hi! Working on getting my sea legs under me)

**Comment by StacyB2023** [comment]
@TKDickson Heyyy therese! Welcome back. I see this one is in progress. Yes, ive tagged it to this coming sprint!!! :)

**Comment by TKDickson** [comment]
Per conversations with Binny, the initial push of AF is "framework itself, tools to test it, and implementing it on the various profile-related screens". Implementation on other screens (ex: login; categories of health, benefits, payments; etc) would be coming in later tickets. Should scope out test plan according to first push, and hopefully have fairly reusable test cases....? Fingers crossed.

**Comment by TKDickson** [comment]
Cases needed:
* 1, 2, and 3 -> success (all screens) -- shows appropriate waygate
* 2 or 3 -> failure (all screens) -- shows error message (and NOT waygate)
* spot check bad setup on RC (ex: missing fields (title is required), link in content (shouldn't work)) 
* 2 setup cases (one for demo mode, one for staging/prod with VERY STRONG language)
* the 'all screens' STC. Have to figure out if I want one looooong one, or split into Nav sections (probably the latter?)

**Comment by TKDickson** [comment]
Cases _almost_ all written, need to add screenshots/examples for the RC setup expected results
* [Availability framework cases](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=11848&group_order=asc&display_deleted_cases=0)
* [New "all the screens" cases ](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12194&group_order=asc&display_deleted_cases=0)(broader use than just AF)

My test plan will be:
* Running use cases 1, 2 and 3, as well as the hierarchy case, on ALL screens in the app
* Spot-checking a few screens with the "remote config setup failure" cases


- [ ] My reminder to add those screenshots/examples, which I will check off when it's done

**Comment by TKDickson** [comment]
Binny and Stacy both OK'd the plan; closing ticket.
