### ISSUE TITLE
Fix Broken e2e tests for github iOS and Android

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#6879]
Currently there are a couple of broken e2e tests for android and iOS

Android
Messages, Appointments, Contact Info, Personal info, prescriptions, claims, direct deposit, home, letters, settings

iOS
Messages, Appointments, Contact Info, Personal info, prescriptions, claims, direct deposit, home, letters, settings

**Comment by timwright12** [comment]
@Sparowhawk we have tickets for iOS tests in CI already, can you make sure there are not dupes? Also each test suite should be its own ticket.

Also curious about what happened with iOS, we had all but 5 suites passing previously

**Comment by Sparowhawk** [comment]
@timwright12 there were 6 not passing after latest update. I added the 2 missing tickets for iOS. Working on adding android and adding a ticket to turn on the slack functions for both iOS and Android once they are working

**Comment by Sparowhawk** [comment]
closing this issue as it will be a duplicate

**Comment by timwright12** [comment]
awesome, thanks!
