### ISSUE TITLE
Write content considerations for Alert component

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6896]
- [x] Review [VADS content considerations](https://design.va.gov/components/alert#content-considerations) for Alert component
- [x] Write mobile app specific content considerations ([draft started here](https://docs.google.com/document/d/1CK18qCqFL-342WyG3l0lwmn31Th67ceJTmBufobVIno/edit?usp=sharing))
     - Do any website-specific guidelines not apply to mobile app?
     - What's unique about mobile?

**Comment by mistymg** [comment]
Pulling this work into this sprint as I had a point of capacity open up

CC/FYI: @jennb33

**Comment by mistymg** [comment]
Met with Jessica and she shared the [Alert Figjam](https://www.figma.com/file/FXCve8uZL1t1TAB8xIIApK/Design-system-%2F-Alerts?type=whiteboard&node-id=0-1&t=ZG8FX2K6opVWOXal-0) audit she did. Will use this to help inform any content consideration for this component.
