### ISSUE TITLE
Investigate visualization integration with Platform Atlas

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6900]
## Description

The Web platform team is building a tool called Atlas that is set for MVP release. In speaking with Bill Chapman (OCTO Eng Director) the visualization tool we're building could be useful at a much larger scale for everyone to use. We need to take a little time and look at the Atlas implementation (Rails app) to see if our work could be integrated into their system.

## Important links

- [Atlas dev instance](https://dev.va.gov/atlas)
- [Atlas code](https://github.com/department-of-veterans-affairs/platform-atlas)

## Definition of Done

- [ ] Clear documentation answer as to if we can integrate our code with theirs
- [ ] Document how it might be integrated to send to platform (Give to Tim and he can send it)

**Comment by jperk51** [comment]
This was done yesterday I just forgot to close it. VA is moving away from Atlas so there's no reason to pursue further, but if we had ultimately wanted to we could have integrated our visualization or scraping tools into it.
