### ISSUE TITLE
BUG - SEV 3 - ALL - Wrong capitalization for Rx statuses

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6909]
## What happened?

Per VA style guide, we should be using sentence case (versus title case). There are 2 prescription statuses that are currently in title case and need to be changed to sentence case.

## Specs:

- Device: n/a
- OS: n/a
- User Account: 
- Accessibility State:

## Desired behavior

`Active: On Hold` and `Active: Refill in Process` need to be in sentence case (i.e., `Active: On hold` and `Active: Refill in process`) in all places that they appear. This includes in the tag on the prescription card, in the status filter panel, and the status definition panel.

Special note: In sentence case, the first word after the colon is still capitalized. It's the following words that are not.

## Acceptance Criteria

- [x] `Active: On Hold` status now reads `Active: On hold`
- [x] `Active: Refill in Process` now reads `Active: Refill in process`
- [x] These changes to capitalization appear in these statuses in the following places:
- The status tags on both the list and details view
- The radio button options for these status in the status filter panel
- The status definition panels for both statuses

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [X] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by mistymg** [comment]
@bischoffa Created this bug ticket for a capitalization issue in Rx. Thanks!

**Comment by bischoffa** [comment]
@mistymg @MekoHong is this a bug or an enhancement? It feels like a bug given its been released for awhile and didn't know about it until we got VA style guide.

**Comment by mistymg** [comment]
It's a bug, which is why I filed it as a bug. 

We've had the style guide since before I was here. This issue just slipped past us on release (or I may have been originally told we couldn't change the capitalization when I first worked on this feature, but Eng confirmed we could change it).

**Comment by bischoffa** [comment]
Thanks for confirming, wanted to verify as sometimes people write bugs thinking its a bug when it isn't and this seemed similar to those.   
  
Given its a bug it needs to next be reviewed and scrubbed by QA per BAU process. @DJUltraTom @rbontrager not sure who the current scrubber is but please add this to your queue.

**Comment by TKDickson** [comment]
Created #7401 for detox updates

**Comment by TKDickson** [comment]
Closed that ticket because Dylan had already made those changes (woo!); both labels are correctly in sentence case in all three locations. Good to merge to develop.

**Comment by TKDickson** [comment]
No further testing needed in develop, closing.
