### ISSUE TITLE
CU - Review dependencies and select good candidates for native modules/

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#6913]
## Proposed Change

Currently, we are using quite a few dependencies in the app. It would be nice to remove the ones that either aren't being used, or are minimally used, and replace them with native modules or custom code. We should review our dependencies in the [package.json](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/package.json) file and create a list of which ones are good candidates for being replaced with our own implemented code.

## Why Should We Prioritize?

Removing unused/minimally used dependencies will make dependency management easier, as we'd be managing fewer dependencies. This would also enhance the security of our app, since having more dependencies means there's a greater chance for security vulnerabilities to make their way into the app.

This would also give us more control over parts of our codebase, because we'd be able to write the native modules in a way that best integrates with our code.

## Coding Time Estimation

No coding would be involved in this work since it's just reviewing the our dependencies.
	
## Testing Considerations

N/A

## Checklist
- [x] Add the front-end label tag
- [x] Attach to the Frontend epic for engineering initiatives

**Comment by theodur** [comment]
# Summary
Overall, there weren't many packages that can be easily replaced with native modules. The few mentioned below are probably the best candidates to be replaced with native code, mainly because they are minimally used in our repo, or they are unmaintained. 

I came cross multiple packages that are unused in our repo and can be removed. I can either make a PR and attach it to this ticket, or make a separate ticket for that.

I separated the packages by category below, mentioning some of the reasons why they would be good alternatives.

## Potential packages that can be converted into native modules:
- [@react-native-community/clipboard](https://github.com/react-native-clipboard/clipboard)
  - The functionality seems simple enough to implement
  - We're only using this in one place in the app, the developer screen
  - Even though the package has a variety of [methods](https://github.com/react-native-clipboard/clipboard#methods) for getting, setting, and interacting with the clipboard, we're only using the `setString` method, so that would be all we'd need to implement
  - In the future, If we require a more functionality than just setting the string, we can always add the needed functionality to the natve module
  
- [@react-native-cookies/cookies](https://github.com/react-native-cookies/cookies)
  - Only used in the authSlice when performing any type of authentication function
  - We're only using one method from this library, `clearAll`, so most of the functionality provided by the library isn't needed
  
- [react-native-file-viewer](https://github.com/vinzscam/react-native-file-viewer#readme)
  - We're only using the `open` method from this library, which could be replaced with the iOS [QuickLook framework](https://developer.apple.com/documentation/quicklook) and the Android `ACTION_VIEW` Intent
  - Packages doesn't seem maintained, as the last commit was in Dec. 2021

## Unused packages that can be removed
- [jwt-decode](https://github.com/auth0/jwt-decode)
- [react-native-responsive-screen](https://github.com/marudy/react-native-responsive-screen)
- [redux-logger](https://github.com/LogRocket/redux-logger)
- [@types/redux-logger](https://www.npmjs.com/package/@types/redux-logger)

## Packages that can be removed and replaced with vanilla JS
- [querystringify](https://github.com/unshiftio/querystringify)
  - Only used in 2 files
  - Can be replaced with the built-in [URLSearchParams API](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)
- [@types/querystringify](https://www.npmjs.com/package/@types/querystringify)
  - Can be removed alongside `querystringify`

**Comment by theodur** [comment]
@dumathane @Sparowhawk I added a list above with packages that can potentially be converted to native modules. Let me know if you guys have any questions. I'll leave this ticket in the `Code Review` pipeline to signify it's being reviewed.

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by Sparowhawk** [comment]
@theodur Can you spin up the 3 tickets for creating those native modules and include removing the package that it is replacing as well.

I also think that this ticket should have a PR to remove the other unused modules and also update to vanilla JS and remove those 2 modules since it looks like a simple change.

**Comment by theodur** [comment]
@Sparowhawk I made 3 tickets for the packages that can be replaced with native modules:
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7005
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7006
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7007

While I agree that removing unused modules and replacing `querystring` with the built-in API are simple changes, for sprint ticket tracking accuracy, I feel like separate tickets should be spun up for that work, as it makes it easier to separate the concerns of the tickets. Plus, QA may need to validate the `querystring` replacement, and this ticket was already carried over from the previous sprint. I went ahead and made additional tickets for both of those tasks and assigned them to myself:
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7009
- https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7010

Now that all the necessary tickets are made based off this discovery work, this ticket should be good to close now
