### ISSUE TITLE
Update RX refill list view filters & default view (Placeholder)

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6915]
## Description 

**Problems to solve**

**Problem A**: Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill.

**Problem B**: When a filter is on, header 1 and header 2 counts are unequal.

As part of this story we want to:   

-  Group Active statuses (Active, Active: on hold, refill in process, etc) and will be the default filter
- Update Filter view screen
- Update Tab header to be dynamic
- Update list view screen text

## Acceptance Criteria
  

-  [ ] AC 1
-  [ ] AC 2
-  [ ] AC 3

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
No longer needed.
