### ISSUE TITLE
Create baseline engineering documentation

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6920]
## Description

We don't have any documentation about how to get started or up and running locally with the design system right now. We should do that. At the time of this ticket, engineering documentation lives at: https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro
This documentation should be written for devs that are either new on the Flagship team or on an external product team, starting to build functionality within the Flagship app.

## Definition of Done

- [x] Look at equivalent VADS documentation to determine what/how we want ours to be similar
- [x] Documentation is published [here](https://department-of-veterans-affairs.github.io/va-mobile-app/design/About/engineers) that will allow an engineer to get up and running locally with the design system without outside support
- [x] Propagate over [versioning guidance](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main#versioning-policy) for both internal and external teams' awareness
- [x] Propagate over [getting started guidance](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/components#getting-started) for engineers who will be contributing/needing to set up the libraries locally

**Comment by kellylein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/6920?planning-poker) with Zenhub @narin @TimRoe @timwright12

**Comment by TimRoe** [comment]
Closing out, [ticket 143](https://github.com/department-of-veterans-affairs/va-mobile-library/issues/143) created to follow-up on redoing the automation part after the library repo is made public.
