### ISSUE TITLE
Document release strategy for design system

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#6921]
As of the writing of this ticket we do not have a release strategy and we need to figure that out. 

The Strategy should include:

- How often we release (sprint-based, feature-based, other?)
- How the actual release feature in github will be used
- How release tagging will happen
- Any sign off needed for a release (PO? QA?)
- How do we inform consumers about a new version?

This ticket should also explore and other items we need to consider and document.

## Definition of Done

- [ ] Release process is documented within the Design System section of the doc site.
- [ ] Follow up tickets are made for any related engineering effort

**Comment by timwright12** [comment]
@kellylein @narin I found this ticket mislabeled as release mgt, I think we completed most of it elsewhere though

**Comment by narin** [comment]
I think you're right in most of this has been discussed when we worked on our publish workflow, but it hasn't been documented on our site yet. We can keep it open until we've done so.
