### ISSUE TITLE
Buttons / Links - Component audit in app

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6928]
Before the Button and Link components are incorporated back into the mobile app, we recommend doing an audit of how buttons and links are currently used in the app and if/how they should be updated during the FE implementation.

- [x] Create structure for audit
- [x] Collect all instances of buttons and links in the app
     - Reference ticket #5523
     - Reference notes in epic #7172
- [x] Review usage guidelines for [buttons](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Buttons%20and%20Links/VAButton) / [links](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Buttons%20and%20Links/ClickForActionLink)
- [x] Determine if we need to make any changes to how buttons and links are implemented in the app
- [x] Add findings to [epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7172)
- [x] Close out #5523?

If you have any questions, reach out to @jessicawoodin.

**Comment by alexandec** [comment]
@brea11y I made a bunch of additions to [the spreadsheet](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit#gid=1283894560), mostly buttons. Should be in good shape with that now. Let me know if you have any questions about any of that.

**Comment by brea11y** [comment]
Thanks so much @alexandec! I'll start working through everything tomorrow and will let you know if I have any questions. I really appreciate your help on this!
