### ISSUE TITLE
Detox in Github Actions - Fix iOS test suite: Letters

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#6930]
The Letters test suite in github actions is failing. This ticket is to fix it.

Looks to be a scrolling issue with elements not visible on the screen. Add scroll to elements and play with visibility percentage to get it to work on github and locally.

Definition of Done:

Letters tests pass in CI with the iOS workflow (screenshot proof is fine)
Letters tests still pass locally (iOS & Android)

**Comment by timwright12** [comment]
@Sparowhawk for some of these visibility issues, I've discovered that it's that the keyboard is blocking a button or input rather than an issue with scrolling
