### ISSUE TITLE
Detox turn on Slack Notification for Android daily QA build in github actions

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#6939]
go to e2e Android and uncomment out:

schedule:
- cron: '0 4 * * 1,2,3,4,5'
start_slack_thread:
name: Start Slack thread
uses: ./.github/workflows/start_slack_thread.yml
secrets: inherit
with:
channel_name: va-mobile-build-alerts
message: 'E2E Android build process starting. Please see 🧵 for results. This process may take a while.'
needs: start_slack_thread
- name: Inform Slack of Failure
  #   id: post_failure
  #   if: failure()
  #   run: |
  #     ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
  #       -H 'Content-type: application/json' \
  #       --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Failed! Please check workflow for results: https://github.com/department-of-veterans-affairs/va-mobile-app/actions"}' \
  #       https://slack.com/api/chat.postMessage|
  #       jq -r '.ts')
  #     echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT

  # - name: Inform Slack of success
  #   id: post_failure
  #   if: ${{!failure()}}
  #   run: |
  #     ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
  #       -H 'Content-type: application/json' \
  #       --data '{"channel":"'${{needs.start_slack_thread.outputs.channel_id}}'","thread_ts":"'${{needs.start_slack_thread.outputs.thread_ts}}'","text":"Success! All E2E tests have passed"}' \
  #       https://slack.com/api/chat.postMessage|
  #       jq -r '.ts')
  #     echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
and remove the push: workflow step once you verify that the slack thread is created and posted to the channel that Android succeeded

**Comment by TKDickson** [comment]
All the tickets that were blocking this work have been approved, moving to current sprint as a very low priority.

**Comment by rbontrager** [comment]
Slack messages are being displayed daily for the e2e github action scripts. Found and made a ticket for a tiny UI issue when the script fails [7461](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7461) but still closing this ticket.
