### ISSUE TITLE
TOU - Testing Validation 

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6943]
## Description 

VA would like all users utilizing VA.gov and its surrounding sites and services to be presented with a unified version of the Terms and Conditions. Additionally, they want to be able to track acceptance on a user-by-user basis, including when revisions are made to the terms and conditions and updates are presented to the user.

As part of this ticket, we will need to partner with the identity team and test the TOU experience on mobile and report any findings

User Experience

- Upon login; user will be prompted with VA Online Services Terms of Use
- If the user Accepts, they are able to continue servicing on the VAHB app.
- If the user Declines, they will be logged out of the VAHB app and messaging displayed explaining what’s next.
- Users will have the opportunity to accept TOU if they previously declined.

## Acceptance Criteria
  

-  [ ] Validate the TOU experience on mobile app.  See user experience above
-  [ ] Report issues/findings to the Identity team 

TOU POCs
-  Joe Niquette (Lead engineer)
- Tom Black (PM)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies? Coordination with the Identity Team
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by MekoHong** [comment]
Example of web redirect of TOU: https://staging.va.gov/terms-of-use?redirect_url=https%3A%2F%2Fstaging.va.gov%2Fauth%2Flogin%2Fcallback%3Fcode%3D7c799671-8a49-4ed4-927d-49b887a4252d%26state%3Daeab2e9d3e7135fd504c7450878c7c03f14495d3e51dd154206ce524%26type%3Didme&terms_code=f27473dc-a06b-42f6-ae37-ec9a8728e8fd cc: @mistymg

**Comment by bischoffa** [comment]
@MekoHong can you add a size estimate to this ?

**Comment by MekoHong** [comment]
@rbontrager can you add an estimate?

**Comment by bischoffa** [comment]
@TKDickson can you add a comment why this is blocked? Given its blocked I am moving it to the blocked column

**Comment by kellylein** [comment]
Tested again on 10/30/23 and still not redirecting on Android.  Waiting on additional fixes.

**Comment by rbontrager** [comment]
Verified the following on iOS/Android and with Login.gov, ID.me, and DS Logon logins:
- If the user hasn't accepted/seen ToU that ToU is displayed on login
- When ToU is declined, the user is taken back to the login screen on 'Sign Out'
- ToU is displayed again on a previously declined user on log in
- When ToU is accepted, the user is redirected to the home screen of the mobile app and all services are available

Approved by QA.
