### ISSUE TITLE
Measures of Success for Personalized Home Scree Wireframes

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6946]
- [ ] Based on top candidates for Personalized Home Screen wireframes, outlines measures of success

**Comment by g-opzt** [comment]
@ajsarkar28 #5919 #5916 will be blockers to measures comparing the current home screen to the redesigned one so I am pulling those into this sprint to get the reviews done and so analytics can be implemented ASAP.

**Comment by g-opzt** [comment]
I've started revising the measurement plan from the version completed in August. Draft will be completed and shared  with Ameet & Holly on Monday.

**Comment by g-opzt** [comment]
Draft shared with @ajsarkar28 and @htcollier for review. Final version will be moved to markdown following their feedback.

**Comment by g-opzt** [comment]
[Updated measurement plan is on Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/data/data_project_plan.md)
