### ISSUE TITLE
Deep Linking Appointments: UX Discovery

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#6953]
As a product team, we want to understand what the best practices are for deep linking to destinations within the app in terms of origin logic, routing, and back actions.

## Acceptance Criteria
  

-  [x] Investigate best practices for deep linking to app content for appointments
-  [ ] [Diagram](https://www.figma.com/file/efonMkGyYE5Krx30gd0sG5/Deep-Linking---Discovery---VA-Mobile?type=whiteboard&node-id=228-233&t=fjeMOpdaLdeEBwHs-4) the logic and routing for various situations
-  [x] Map current push notification sources & content

**Additional Info:**
MVP Reference for UX Deep Linking -Secure Messaging 
EPIC: [HERE](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6037)

UX TICKET: [HERE](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6221)

**Comment by StacyB2023** [comment]
@kidlaurenpeace I added this ticket for sprint 82. @drjecker mentioned you may be doing the UX discovery? I added the references from the MVP tickets to this as well.

**Comment by kidlaurenpeace** [comment]
Added [link](https://www.figma.com/file/efonMkGyYE5Krx30gd0sG5/Deep-Linking---Discovery---VA-Mobile?type=whiteboard&node-id=228-233&t=fjeMOpdaLdeEBwHs-4) to Appts Diagram
