### ISSUE TITLE
Add new analytic event: Full panel viewed

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6960]
- [ ] `vama_full_panel_click` captures when a link to open full panel is **clicked**. Store name of the link used to open the panel (or another similar identifier) in a parameter `panel_name` so that we can differentiate between which full panel was opened. 

## To discuss at handoff
The first event here is really a subset of an even more universal tracking collection: anything that can be clicked. For example, this has not been ticketed yet but we need a way to track clicks on things on the home page that launch different webviews, and buttons that are clicked, etc. What is the best approach to this from FE POV?

**Comment by Sparowhawk** [comment]
@g-opzt Do we not already get which screens are visited in analytics? Wouldn't that cover this?

**Comment by g-opzt** [comment]
Full panels don't appear to come through in the screen_view event, but if we could get them to, that would be sufficient.

**Comment by g-opzt** [comment]
@Sparowhawk I would still need the first event to capture the clicks.

**Comment by g-opzt** [comment]
I do see one full panel that is coming through as a screen name: VeteransCrisisLine. Perhaps looking at it vs how the Profile large panels are coded could give us a clue.

**Comment by dumathane** [comment]
Ya I'd like to discuss event 2. Not sure what we're looking to garner from that one.
