### ISSUE TITLE
Add new analytic event: submission retry from snackbar

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6961]
- [ ] `vama_sb_retry` captures whenever a user clicks "Retry" in a snackbar following an API call fail. In a parameter, capture the message that was displayed on the snack bar and the screen name the snackbar was displayed on.

**Notes**
We currently have this in `vama_rx_refill_retry` but not for any other similar situations, like updates to profile information. I'm thinking based on prior tickets that making this a universal event instead of writing separate events for each call that can be retried is preferable, but we can also refactor this ticket to be separate events. In particular, for the Profile feature, we need this for updates to preferred name, gender identity, mailing address, home address, phone numbers, and email addresses.

**Comment by Sparowhawk** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/6961?planning-poker) with Zenhub @alexandec @dumathane @narin @Sparowhawk @theodur @TimRoe

**Comment by TimRoe** [comment]
> I'm thinking based on prior tickets that making this a universal event

One thought on this: the snackbar is planned to become a library component down the road. So the most intuitive "universal event" of baking it into the component would likely not be able to persist long term. It could still be made universal by having a shared app-level "retry" function that all uses of snackbar pass through.

**Comment by OVezeamama** [comment]
@theodur did we progress further on this ticket on still same stage?
