### ISSUE TITLE
Add new event for push notification button clicks and universal toggle interactions

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6962]
- [ ] `vama_push_notifications` **event** that captures clicks of turn on push notifications button on the Settings screen
- [ ] `vama_toggle` **event** that captures whenever a user clicks a toggle button. Capture in parameters
  - [ ]`toggle_name` for what the button was for (such as Appointments in push notification settings in Profile)
  - [ ]`status` whether they set to off or on
  - [ ]`screen_name` ensure the screen name comes through so that if we add more toggles in the future we have more ways to identify than just toggle name (which could get reused)

**Comment by Sparowhawk** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/6962?planning-poker) with Zenhub @alexandec @dumathane @narin @Sparowhawk @theodur @TimRoe

**Comment by alexandec** [comment]
The `vama_uses_push` event is interesting because it's more a recording of the current user's preference settings rather than a particular event the user triggered in the app. Do you know if we have a precedent for how to handle this? I'm wondering when to send this event, and how often.

**Comment by Sparowhawk** [comment]
@alexandec I am pretty sure this will be handled the same way isScreenReaderEnabled is in my one ticket

**Comment by alexandec** [comment]
@Sparowhawk I wonder if we could send a single event that contains multiple user settings in it. Not sure if it would work with BigQuery for reporting, but it seems more efficient and simple than having a separate event per setting
