### ISSUE TITLE
Add new analytic event: Universal webview fail event

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6975]
We have an event vama_login_fail that was originally designed to capture when logins failed at the point of the webview reporting an error. (i.e. the webview itself crashing or running into an error.  If the website within has an error this doesn't count)

We use webviews in several other parts of the app, so ideally we'd have universal tracking of this in a new event:

- [ ] `vama_webview_fail` captures any time a webview crashes/reports an error similar to the specific event above. It would also capture a parameter `webview` that stores the link for which URL the webview launched so we can differentiate between where in the app it occurred and, if possible, `error` that stores the returned error message.

**Comment by alexandec** [comment]
We have a useExternalLink hook that's called whenever the user taps on an external link. Currently that hook sends the `vama_link_click` and `vama_link_confirm` events. We could add a new `vama_link_error` event there. That said, I don't know for sure if we'd actually get any errors, or what type they might be.

**Comment by rbontrager** [comment]
Verified that the event showed up in the logging file in staging on the sim. No other work can be done so closing this ticket.
