### ISSUE TITLE
Define Analytics:  Availability Framework

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#6978]
## **Description** 

Today, when critical errors affect the Mobile Application, we currently do not have an immediate way to address them outside of the normal app store release and review process. As a result, users experience a broken app until it can be fixed.

For this User Story, we would like to define analytics for Availability Framework (Direct Measurements) as well as advice on any Indirect Qualitative User Experience measurements that can be done.

**Epic and Use Cases for Reference** [HERE](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5120)

## Acceptance Criteria
  

-  [x] Define Direct Measurement for Analytics including any new events that need to be added 
           

- Is the veteran seeing the critical message in the app?
-  Is the veteran performing the update (via the button) for the app store fix?

- [x] Advice on User Experience Qual measurements (such as user testing/research sessions)

**Comment by StacyB2023** [comment]
@g-opzt As we discussed for the direct measurement.

**Comment by g-opzt** [comment]
Ticket #6983 written for analytics for availability framework to measure direct function and impact on updates to resolve. All other measurements discussed thus far will rely on these in combination with existing analytics. The final metrics plan will be posted to Github pending @StacyB2023 discussions with @lstraghalis for research insights.

**Comment by g-opzt** [comment]
Blocked until I hear from Product/Research on user experience qualitative measures

**Comment by lstraghalis** [comment]
We don’t need to move forward with research ahead of launch unless our confidence levels were low. We can use lagging indicators vis-a-vis monthly app store reviews and reddit convos to glean insight into Veteran comprehension of the errors, if we end up launching error messaging.
We can start by monitoring reviews and reddit boards if error messaging goes into production. If there's a clear indication that Veterans are confused, then we can reassess the need for a future research study.

**Comment by g-opzt** [comment]
Based on the above from Liz, moving ahead with finalizing the notes on how the measurement will be done before closing out this ticket.

**Comment by g-opzt** [comment]
Measurement plan available in the feature documentation [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Availability%20framework%20measurement%20plan.md).
