### ISSUE TITLE
Bug - Sev-2 - Android login failing when default browser is DuckDuckGo

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#6981]
When an Android user has DuckDuckGo as their default browser, login does not succeed. We fixed the login issue in Firefox in #6736, but the issue remains in DuckDuckGo.

## Steps to replicate:

1. On Android device, change default browser to DuckDuckGo
2. Sign in the app with login.gov user vets.gov.user+12345@gmail.com
3. Login issue should present itself

## Impact:

We do not yet have analytics for the percentage of our Android users who have DuckDuckGo set as their default browser. Based on [US mobile browser share](https://gs.statcounter.com/browser-market-share/mobile/united-states-of-america) we expect the percentage to be quite small, <1%.

## Relevant links and background information

- [Bug - Sev-2 - Android login failing when default browser is Firefox](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6736). PR for this ticket fixed the login issue in Firefox. Ticket contains additional information about the login issue.
- [Custom tabs re-implementation PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6613). This is where the login issue began to occur.
- [Firefox issues with the launchMode](https://github.com/flutter/flutter/issues/56690)
- [SIS thread about this issue](https://dsva.slack.com/archives/C03DY3FN7HQ/p1694694078283649)
- [Initial reporting of the issue](https://dsva.slack.com/archives/C018V2JCWRJ/p1694654535598999)
- [A potential fix that failed](https://dsva.slack.com/archives/C022SV53ASZ/p1694698934761459)

**Comment by alexandec** [comment]
@StacyB2023 I created this ticket as a followup to #6736 which fixed the Android login issue in Firefox. This is to fix the same issue in DuckDuckGo.

cc @dumathane @jennb33 @timwright12 @bischoffa

**Comment by StacyB2023** [comment]
@alexandec Thanks!!!

**Comment by alexandec** [comment]
Currently we always use the default browser when launching the Custom Tab for login. Since some browsers don't support Custom Tabs, I created a PR that checks the installed browsers and chooses one that supports Custom Tabs. It works as follows:

- If the user's default browser supports Custom Tabs, use that browser
- If the user's default browser does not support Custom Tabs, find a different installed browser that does support Custom Tabs, and use that browser instead
- If none of the installed browsers support Custom Tabs, use the default browser (best we can do)

Some browsers that support Custom Tabs: Chrome, Firefox, Brave, Edge
Some browsers that don't support Custom Tabs: DuckDuckGo, Opera Mini

**Comment by bischoffa** [comment]
CC @StacyB2023 - update above.

@alexandec another ticket was created for Edge [7180](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7180)

**Comment by alexandec** [comment]
@bischoffa thanks for the heads up. The change in this ticket shouldn't affect Edge since that supports Custom Tabs. I did a quick test on my Galaxy S7 with Edge, and login worked fine there. Maybe someone with a different Android device can pick up 7180 and see if they can reproduce it. These login issues can be highly specific to particular device/browser combinations.

**Comment by DJUltraTom** [comment]
props @alexandec thats a slick solution!
Verified that if: 
- default browser does not support custom tabs a browser that does install custom tabs is used instead
- default browser supports custom tabs works as normal
- default browser does not support custom tabs and no installed browser does, signin looping does occur, 

QA approves this code

**Comment by DJUltraTom** [comment]
verified fix works as expected on the overnight QA build, closing ticket
