### ISSUE TITLE
Analytics for availability framework implementation

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#6983]
- [ ] `vama_af_shown` capture any time an availability framework message is displayed to a user. Include parameter for:
  - [ ] `af_status` capture if the message is currently stating that there is an error that we're working on (`open`) or if the error has been resolved and the message is now displaying an update button to users (`closed`)
  - [ ] `firebase_screen` should be automatically collected but make sure that is recorded with this event in case we are ever in a situation were AF is being used on two different screens in the app at the same time.

These two events are modeled off of what we currently have for the encourage update feature with events `vama_eu_updated` and `vama_eu_updated_success`
- [ ] `vama_af_updated` capture if a user clicks to update the app from the button in the availability framework message
- [ ] `vama_af_updated_success` capture if the app version was successfully updated
  - [ ] `firebase_screen` should be automatically collected but make sure that is recorded with this event in case we are ever in a situation were AF is being used on two different screens in the app at the same time

**Comment by theodur** [comment]
@g-opzt For the first analytic `vama_af_shown`, the parameter `af_status` says it should capture if the messaging states that there is an error we're working on. The best way that we have to determine if there's an error is to use the same logic that determines whether the AlertBox should be the color red for an error or orange for a warning. This won't explicitly check whether the messaging in the body states we're working on it, but it's probably safe to assume if we're showing the color red for the AlertBox that we're working on an error. Just wanted to confirm this is fine? And based on this logic, any time the AlertBox isn't an error, the `af_status` would be `closed`

**Comment by g-opzt** [comment]
@theodur would we ever use AlertBox with those colors outside of the availability framework?

**Comment by theodur** [comment]
@g-opzt Yeah, those colors are used throughout the app, but the analytics I've added will only capture the AlertBoxes specifically for the availability framework

**Comment by theodur** [comment]
After chatting with Binny, it seems like the logic for `af_status` should be based on whether we're displaying the app update button, which also seems more aligned with what you mentioned in the ticket description @g-opzt. I went ahead and made that change. Let me know if that doesn't sound right

**Comment by theodur** [comment]
We also ended up removing the `vama_af_updated_success` analytics because unfortunately we don't have a way to accurately track whether a user came back from the app store after recently updating the app

**Comment by g-opzt** [comment]
Thanks, @theodur. The af_status logic you described makes sense. For the update success piece, I think I can cobble that together from checking if they come back to that screen on the new version within X amount of time after clicking the update button.
