### ISSUE TITLE
BUG - sev-2 - Android - We don't clear out the "ID" apps created during Android login

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#6986]
## What happened?

Custom tabs login in Android, as implemented after ticket #6736, jumps the veteran out of the VA to an "ID" app to do authentication.

That ID app remains, no matter if authentication succeeds or not. From a single day of testing (lots of login/out), you can see [I've got a number of ID apps in my appswitcher, from ~0:35 onwards in this video.](https://drive.google.com/file/d/1aUvJ8u47Y8GZ89d4KJ3DjBq1nL28HUHM/view?usp=drive_link)

## Specs:

- Device:
- OS: Android
- User Account:
- Accessibility State:

## Desired behavior

We should close the ID app when the authentication workflow jumps back to the app, or some other method of closing out that window.

This makes identifying the correct ID app to go to even more confusing, in the event you are stuck in a login loop as described in #6985.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High 

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by alexandec** [comment]
The linked PR should fix this issue for Chrome on Android, which we believe accounts for the vast majority of users. It does not fix the issue for Firefox.

**Comment by TKDickson** [comment]
Linked PR fixes the issue for Chrome and Samsung Internet, across Pixel, OnePlus, and Samsung devices. Opera Mini and Firefox are still exhibiting this behavior, see #6994.
