### ISSUE TITLE
EVSS to Lighthouse migration - update mocked data for demo mode to reflect Lighthouse API data input

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#6997]
As part of the mobile app team, I want demo mode to closely reflect the current state of the app so it can be useful for stakeholders, usability research, etc.

As part of the Lighthouse migration, a couple places should now show different information:
* claims file request rows now are their titles such as “Request for proof of date of marriage” (instead of “Request #“)
* Claims details, make sure the "your representative for VA claims" field is ~~either not there or~~ 'contact office' ~~(whichever design prefers)~~

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU0xQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f94d7bccea02ad5d5c06a2dc10c30b7eb5eeddfb/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVExQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b0ca7b769437c1cd666f05a717fccf41558c7da/image.png)

**Comment by TimRoe** [comment]
> Claims details, make sure the "your representative for VA claims" field is either not there or 'contact office' (whichever design prefers)

Taking a quick glance at the code, updating this AC to the only valid option ("contact office", that is the generic filler it is not conditionalized to not appear)

**Comment by bischoffa** [comment]
@kellylein with you owning this is the working being done through Design Systems? or is it falling to another team like global?

**Comment by TKDickson** [comment]
Demo mode claims details, file request list, and file request details all look consistent with the LH-migrated UI and content. Good to merge to develop.

**Comment by TKDickson** [comment]
No further testing needed in develop, closing.
