### ISSUE TITLE
Make it easier to sign into demo mode

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#6999]
## Description 
As a user of the VA app demo mode, I want to log in quickly, so that I can get to the good stuff faster.

As part of this story we want to:   
Request from Ryan Thurlwell in DSVA slack:

> If, by chance, we can make it easier to sign into demo mode when we make these updates, that would be amazing. 21 taps + password with upper/lower/special is annoying. As an example, the State Farm app just uses a 4 character user name, and no password at all and it’s so nice to access quickly and on the fly.

Note other requirements of the above comment are captured in this issue:
https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7410

## Acceptance Criteria
  

-  [x] lower the number of logo taps required to show the password prompt

**Accessibility Requirements**
- [ ] AC 1

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by rbontrager** [comment]
Verified that the number of taps to get into demo mode has decreased to 7 and that the change has caused no issues with our detox tests.  Approved by QA.
