### ISSUE TITLE
Replace @react-native-community/clipboard package with native module for clipboard

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7005]
## Description

Based on the discovery in https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6913, we aren't using much of the functionality from the [@react-native-community/clipboard](https://github.com/react-native-clipboard/clipboard) package, and the functionality that we are using is just in one part of the app, the developer screen. This makes the package a good candidate for us to implement our own custom solution, rather than adding this package to the app just for one function. We're only using the `setString` function from the package, so this functionality is the only thing that would be needed in the native module.

## Acceptance criteria

- [ ] Create a native module for saving strings to the clipboard
- [ ] Replace instances of `@react-native-community/clipboard` with the native module
- [ ] Remove the `@react-native-community/clipboard` package from the repo

**Comment by bischoffa** [comment]
please add a sprint to this

**Comment by rbontrager** [comment]
Verified you can copy the various strings in developer mode on iOS and Android.  Approved by QA.
