### ISSUE TITLE
Replace @react-native-cookies/cookies package with native module for clearing cookies

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7006]
## Description

Based on the discovery in https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6913, we aren't using much of the functionality from the [@react-native-cookies/cookies](https://github.com/react-native-cookies/cookies) package, and the functionality that we are using is only in one part of the app, the authentication slice in the Redux store. This makes the package a good candidate for us to implement our own custom solution, rather than adding this package to the app just for one function. We're only using the `clearAll` function from the package, so this functionality is the only thing that would be needed in the native module.

## Acceptance criteria

- [ ] Create a native module for clearing cookies
- [ ] Replace instances of `@react-native-cookies/cookies` with the native module
- [ ] Remove the `@react-native-cookies/cookies` package from the repo

**Comment by bischoffa** [comment]
please add a sprint to this

**Comment by TKDickson** [comment]
Hey @Sparowhawk -- I see from Theo's notes in the ticket description that we're using this during authentication. Can add some specific notes about what should be tested to make sure this is working as intended?

**Comment by rbontrager** [comment]
Still crashing on iOS.  DM'ed Dylan who is investigating.

**Comment by rbontrager** [comment]
This is no longer crashing on iOS and login/webviews look fine.  Approved by QA.
