### ISSUE TITLE
BUG - sev-3 - iOS - Native camera within large panel has visual issue (photo label cutoff)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7028]
## What happened?

The native iOS camera app, hosted within a large panel on the VA app, has definitely one (and arguably maybe two) visual issues. The word "photo" above the picture-taking button is cut off, which I'm pretty sure is because we're enforcing the peekaboo (for lack of a better term) with the app screen behind/at the top of the screen. 

This:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f789379bd37592e5b78b71700885c42443c067a1/image.png)

I've seen this in both claims (evidence for file requests) and messaging (taking a photo for attachment) so it seems like a global thing.

## Specs:

- Device: iPhone
- OS: iOS
- User Account: can use demo mode or any staging user
- Accessibility State: I've got larger text on, but my font size is just two clicks above the very lowest that it can go, so doesn't seem like an A11y settings bug.

## Desired behavior

I imagine that this was caused by a fix for a different visual issue with large panels, so if there's a lot of weird code/tradeoffs involved, would likely be a question for Holly/global if it's worth it.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
this is likely fixed by adding the presentationStyle prop to the launchCamera and LaunchImageLibrary calls

Controls how the picker is presented. currentContext, pageSheet, fullScreen, formSheet, popover, overFullScreen, overCurrentContext. Default is currentContext.

**Comment by TKDickson** [comment]
changing from global to health, as the camera is only used in health (messaging) and benefits (claims file request) features.

**Comment by alexandec** [comment]
More info on presentation style options: https://developer.apple.com/documentation/uikit/uimodalpresentationstyle. Ended up going with fullScreen

**Comment by rbontrager** [comment]
Verified that the photo label is not cutoff on the largest text size on all the iOS devices I have.  Approved by QA.
