### ISSUE TITLE
Travel Reimbursement - Clickable Figma Prototype

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7032]
**Summary:**
As VA, I want a clickable prototype for Mobile's Travel reimbursement flow that I can best get familiar and comfortable with the feature request during reviews and approvals. 

**Other info:**

- Assumption - VA does not make request to update it - updates will have to wait till we pick it up 
- Use what we currently have including content
- Will be used for VA stakeholders reviews and approvals 
- Suggested by Mark Dewey 10/18 to do it for the Office of Travel approval  
- Claim status may have to pick the one that Misty did a write up for - not all statuses have a write up 

**Ask:** 

- Create a Figma clickable prototype for Travel Claims to showcase the feature
   -  Login -> Appointments ->  Eligible Appointment -> Submit Claim -> submission accepted, submission decline, submission error) 
   -  Eligible Appointment -> Submit Claim -> submission decline
   -  Eligible Appointment -> Submit Claim -> submission error
   -  Travel Claim Previously Submitted -> Veteran views status -> Veteran gets more status

**Comment by kidlaurenpeace** [comment]
- Figma clickable prototype - [link](https://www.figma.com/proto/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?page-id=1961%3A12220&type=design&node-id=2059-5269&viewport=502%2C402%2C0.12&t=Xh8RbsdDkjHlXW6K-1&scaling=min-zoom&starting-point-node-id=2059%3A5269&mode=design)
- Figma prototype flow layout - [link](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=1961-12221&mode=design&t=fu97STKZmPwh8GKR-4)

**Comment by bischoffa** [comment]
Closed it during today's carryover convo.  If closed too early let me know.
