### ISSUE TITLE
BUG - sev-3 - All - Misleading content for cancelled C&P appointment?

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7035]
## What happened?

There's a specific sub-office (the C&P office) that needs to be contacted to schedule a claims-related appointment, which is why we have specific content for it for upcoming appointments, mobile and web:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEpNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8456b771191e06368e45ba8e616cab6a4fac8aa8/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzVNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c22d64470610df50b2d3b57c76f731e9c2668dab/Pasted%20Graphic%202.png)

The cancelled C&P appointments just have the generic "call the medical center" content, which is not correct - veterans who call there, rather than the C&P office, will either not be able to schedule or will be redirected (idk which). _Also, looks like web also has generic content, but since it's "us" rather than medical center I think they're in a slightly better spot than us._

Mobile:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0269e67688178498f6c0b483ae4e5f1ae525115f/image.png)

Web:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzlNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b7f1531ddec6706b49faf7e05a77c498fae9bfe/Pasted%20Graphic%201.png)

## Specs:

- Device:
- OS:
- User Account: royal.tester@id.me Dec 3rd 2023 appt
- Accessibility State:

## Desired behavior

Will need Misty to figure out the content (so will need to spin up a content decision ticket that will block this one)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by timwright12** [comment]
@TKDickson @bischoffa Are we still blocked by UX for this one?

**Comment by bischoffa** [comment]
@timwright12 yes we are. Desired state is not yet defined.

**Comment by Sparowhawk** [comment]
@wavelaurenrussell can you let us know what to do for this one in this ticket and not the other one lol

**Comment by wavelaurenrussell** [comment]
Content issue UX, so yes still blocked.

**Comment by Sparowhawk** [comment]
This will be addressed with the appts work for C&P appts

**Comment by alexandec** [comment]
Will use the content specified in [Misty's spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=402791918), columns Y and AA.

**Comment by rbontrager** [comment]
Verified that cancelled C&P appointments follow the content specified in Misty's spreadsheet and has been fixed with the new appts work for C&P appointments.  Approved by QA.
