### ISSUE TITLE
BUG - sev-3 - iOS - Issues Reported When Sending a Secure Message

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7045]
## What happened?

During the Section 508 meeting on 10/19/2023, one attendee informed us about a couple of accessibility bugs that she experienced while using VoiceOver. I attempted to recreate the following issues, but didn't experience them on my end.

1. Having to click the Send button twice (could not recreate)
2. Not being able to hear as she types and deletes characters (could not recreate)

## Specs:

- Device: iPhone
- OS: iOS

## Acceptance Criteria

- [ ] Verify that a form can be submitted using VoiceOver by only interacting with the button once (the user reported having to interact with the button twice to send)
- [ ] Verify that VoiceOver is announcing characters while both typing and deleting characters while sending a message

## Bug Severity
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High
- Frequency: High

- 3 - LOW

## Screen shot(s) and additional information

**Transcript from the meeting which details the user's experience:**  

[User] 16:17:46
Right. It'll make you do the send button twice for with voice over on the app.

[User] 16:17:53
Like you have to hit it twice. For it to go. Yes.

[Martha Wilkes] 16:17:55
You're talking about a native mobile app, [user], the native mobile app. Okay, yeah.

[Martha Wilkes] 16:18:01
Okay, we can take that as a note. If that's so this team I sorry for my confusion and not clearing this up this team is It is the website version of secure messaging, but it's.

[User] 16:18:15
Okay.

[Martha Wilkes] 16:18:15
Also making sure it works well on the phone. So there's like multiple ways to do the same thing, of course, right?

[Martha Wilkes] 16:18:22
You could do it on the native mobile app or you could come to the website. And do this message.

[User] 16:18:25
And on the, I did secure messaging just actually yesterday and it's not reading to me. Like when I make a mistake, it will not.

[Martha Wilkes] 16:18:27
Anyway, okay.

[User] 16:18:40
Read. Like when you're deleting. You know, like character or whatever.

[User] 16:18:48
So you're like deleting and guessing. Then kind of playing the Control right arrow to here.

[User] 16:18:55
What's there or something like that? So it's not like. Reading what I deleted or something, you know what I mean?

[User] 16:19:05
So I have to play around with it to then. Here again and then it would it would send it.

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Hey @brea11y - we fairly recently (in #5660) fixed the third thing you're reporting here (screen reader not bringing focus to errors). 

Wanted to check - when you were attempting to reproduce what the user reported, do you know if you were on a version of the app that included that fix? Would have had to be 2.14 or higher, aka not the released app right now.

**Comment by brea11y** [comment]
@TKDickson – Doh! That was exactly it! 🤦🏻‍♀️ I was using 2.13 when I ran the check. I just tested it again and the error began to announce as soon as I submitted it. Let me update the ticket and remove that one. Thank you!   
  
For the other two, I'm not sure if these are actual issues (at least not ones that I was experiencing when I tested?). I even pulled it up on TalkBack later that day to see if it might be happening on Androids also and I can't recreate either one of them. My only thought was that maybe the user has older version of the app or an older iPhone? Possibly a glitch?

**Comment by TKDickson** [comment]
Cool, thanks Brea! I will do my best to reproduce them as well, fingers crossed that it's either an old device thing or I run into it somehow.

**Comment by TKDickson** [comment]
Unassigning myself, did not get to attempts to reproduce this during my bug scrub rotation.

**Comment by Sparowhawk** [comment]
non issue, 8042 covers this
