### ISSUE TITLE
CU - Get rid of all FE IAM code

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7049]
## Proposed Change

There are a few veterans on versions of the app so old, RC isn't in there - otherwise, with RC for SIS set to 100% for a very long time, we have no need for the IAM code in the app anymore.

## Testing Considerations

Confirm the dev tools RC flag for IAM is gone (pretty much the only testable thing)

## Checklist
[ ] Add the front-end label tag

[ ] Attach to the Frontend epic for engineering initiatives

**Comment by bischoffa** [comment]
https://adhoc.slack.com/archives/C0212B872MT/p1697737304901509

**Comment by DJUltraTom** [comment]
happy to report that all IAM associated flags have been removed from the developer screen options
QA approves this build

**Comment by DJUltraTom** [comment]
verified the IAM flags are not present on the overnight QA build, closing
