### ISSUE TITLE
discovery: Awards and dependants integration 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7050]

**Comment by kpethtel** [comment]
Didn't have time to work on this much before heading out on PTO, so I'm unassigning from myself.

**Comment by cadibemma** [comment]
- Dependent Service: Manages a veteran's dependents, including application submissions. File is located in `app/services/bgs/dependent_service.rb`. Submissions is form type 686C

- Awards Service: Retrieves information about veteran awards and their amounts. File is located in `app/services/bgs/awards_service.rb`.
- Dependency Verification Service: Checks a veteran's dependent status. File is located in `app/services/bgs/dependency_verification_service.rb`.
- Bid Awards Service: Retrieves pension information. File is located in `lib/bid/awards/service.rb`
These endpoints appear to be easy and ready to be integrated with.
