### ISSUE TITLE
Automate generation of changelog with release

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#7053]
## Description
Whenever we create a new version of our packages, we want to update a change log that describes the changes made since the last version. There are several tools that can automate this for us based on our GitHub issues, labels, pull requests and commits. However they typically handle monorepos by using a single changelog. We should investigate solutions that could handle independent changelogs within a monorepo.

Some examples of libraries that do this:
- [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) (Also has GitHub Action)
- [lerna-changelog](https://github.com/lerna/lerna-changelog)

## Acceptance Criteria
- [ ] Investigate solutions that can generate changelogs based on issues, labels PRs
- [ ] Determine if it's possible to generate separate changelogs for each of our packages, or if we'll need to use a combined changelog
- [ ] Implement the solution into our release automation

**Comment by kellylein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7053?planning-poker) with Zenhub @TimRoe @timwright12 @narin

**Comment by narin** [comment]
First iteration of automated changelog is complete. This currently generates a unified changelog. We'll want to update the automation to have separate changelogs for each package once we've moved our issues to va-mobile-library. Ticket created (#7411).

Copying further info about the changelog from [slack thread](https://adhoc.slack.com/archives/C05DQPHUVNZ/p1701204329034859):

> The changelog is generated on every publish based on the titles of either closed issues or PRs merged to main in between tags. Since our issues don't currently live in the va-mobile-library repo, for now we are only relying on PRs merged. Until we migrate the issues to our repo, we will have to use [a unified changelog ](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/CHANGELOG.md)that will live in the root of the repo.
> 
> Note that there are some empty sections for now due to testing and non-package related changes but it'll get cleaner and more useful as we follow the new publish workflow. Proposed changes to our workflow are as follows:
> 
> 1. PRs that we want to include in the changelog should have the changelog label applied
> 2. Since the changelog is based on PR's merged to main, moving forward, we should only run the publish workflow for major/minor/patch releases AFTER the PR has been merged in order for it to appear in the changelog correctly (alpha/beta publishes are fine pre-merge). I've updated the PR template checkboxes to reflect this, but we may want to also add this as an AC in the issues so it's not forgotten.
> 3. As mentioned, the changelog uses PR titles, so I've added note to the PR template about making the titles descriptive and suitable for a change log instead of the [feature/bug/cu]/ticket-num-description pattern we've been following

Closing out.
