### ISSUE TITLE
Waygate (availability framework) Implementation: Setup, Home, and Profile

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7054]
## Description 
Waygates need to be placed and confirmed toggle-able in three different use cases across all applicable pages within the app. 

As part of this story we want to:   

- Ensure all relevant pages are able to be intercepted by a waygate setup and display as we would want them to.

## Acceptance Criteria
  

The following three AC's need to be applied to the attached list of screens:

-  [x] Confirm Use Case 1 appropriately intercepts page navigation to the given page.
-  [x] Confirm Use Case 2 appropriately disables screen content and is replaced by only an alertbox.
-  [x] Confirm Use Case 3 displays a warning alertbox as well as the associated screen content.
-  [x] Confirm Error and Loading states still display as we would expect.

List of Screens:

-  [x] 'WG_Home'
-  [x] 'WG_Profile'
-  [x] 'WG_PersonalInformation'
-  [x] 'WG_HowDoIUpdate'
-  [x] 'WG_PreferredName'
-  [x] 'WG_GenderIdentity'
-  [x] 'WG_WhatToKnow'
-  [x] 'WG_ContactInformation'
-  [x] 'WG_HowWillYou'
-  [x] 'WG_EditAddress'
-  [x] 'WG_EditPhoneNumber'
-  [x] 'WG_EditEmail'
-  [x] 'WG_MilitaryInformation'
-  [x] 'WG_IncorrectServiceInfo'
-  [x] 'WG_Settings'
-  [x] 'WG_ManageYourAccount'
-  [x] 'WG_NotificationsSettings'
-  [x] 'WG_ContactVA'
-  [x] 'WG_VeteransCrisisLine'
-  [x] 'WG_VeteranStatus'
-  [x] 'WG_Login'
-  [x] 'WG_RemoteConfig'
-  [x] 'WG_Developer'
-  [x] 'WG_WaygateEdit'

Additional One-Of AC's:
-  [x] Confirm each waygate use case matches the content tickets that Misty provided for AF, and replaces the generic 000-000-0000 placeholder phone number in Figma with 800-698-2411
-  [x] Confirm waygates are editable via Firebase on a fresh install. This may take 5-30 minutes to cache and take effect.
-  [x] The Login Screen waygate will function differently and a use case 1 and 2 will not be possible to enable.

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
@StacyB2023 @dumathane heads up that this ticket exists in a very rough draft state, is assigned to Binny, and moved to in-progress.

Stacy and @bischoffa - this work was always planned for this sprint, we just didn't have a ticket for it. So - put whatever sprints and labels on here as makes sense, I suppose.

**Comment by bischoffa** [comment]
@StacyB2023 I will let you modify the ticket as it your feature. If you need help let me know :)

**Comment by StacyB2023** [comment]
@TKDickson Added this sprint tag to it. Thanks! P.S Also added 8 points for QA going for sprint 83. We can always adjust next week.

cc: @bischoffa

**Comment by TKDickson** [comment]
Things found while testing (test run):
- WG_Home and WG_HomeScreen
- Getting haptic feedback on initial screen load, then also when scrolling down, and also when you get back to the top of the page when scrolling up. Also when typing EACH LETTER on forms (ex: edit phone number) (too much feedback) - UC 3. does NOT happen when scrolling on large panels.
- Manage account (content-only screen), the alert is appearing on top of the content (or the content isn't loading, can't tell which). SCREENSHOT. << Happens on Notification Preferences and Edit Email as well, those have ACTION items hidden under the alert.
- Verify mailing address with UC3 can result in alert - header - alert. SCREENSHOT.
- "How to update or fix an error in your legal name" and "How to fix an error in your date of birth" are apparently the same screen? < need to document

**Comment by TKDickson** [comment]
[slide-on loading animation with alertbox](https://drive.google.com/file/d/18F1r2ye1goebv4bMzmeNq22XsYz88HYK/view?usp=sharing)

**Comment by TKDickson** [comment]
Couple more issues found - #7279 and #7282.

**Comment by TKDickson** [comment]
Last round of tickets to document here, because my initial testing is complete - #7296, #7297, and #7298. 

Will be updating the testing milestone a couple of comments up, but not doing any further testing of this ticket, per se, since I'll be working off of the various bug tickets.

**Comment by TKDickson** [comment]
Also - this testing was done on my OnePlus and iPad mini devices.

**Comment by TKDickson** [comment]
Spotchecked some Profile and Home screens; they are still enabled in develop. Closing.
