### ISSUE TITLE
Create endpoint for POST Preneeds Burial Claims

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7079]
Discovery: #6323

AC:
- [ ] https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Endpoint%20Creation%20Checklist
- [ ] Update existing cassettes if necessary to reflect current state of upstream data

Note: Keep it in mind that we may very well use the forms service for other forms in the future so if there's any future proofing intermediary classes that would be useful go ahead and make those.

**Comment by kpethtel** [comment]
Passing this to Andrew because he's already done the background work for it.

**Comment by aherzberg** [comment]
This will carry over to next sprint due to being put to the side in favor of #7196
