### ISSUE TITLE
Cont Cont: Flip traffic to LH Rated Disability

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7080]
Still following up with the LH teams to figure out how we can filter out the 'extra' records we are seeing. Once we know how I'll make the fix and roll it back out again. 

#6956

**Comment by kellylein** [comment]
Met with LH to help describe the issues we are seeing. Jerek from VA.gov created a way of comparing the differences between EVSS and LH.  We are waiting on a fix from LH.

**Comment by jperk51** [comment]
LH team ran into more issues and is delaying until mid-Jan

**Comment by TKDickson** [comment]
Hello @jperk51 and @kellylein -- two questions.
For testing for a different thing for global, any idea if the LH team is back under way?
Any word from LH how/if all of the staging data would be impacted by this switch getting flipped? I remember from early days testing that there was a very specific list of users that had data prepped (and it wasn't in the staging environment), so I'm wondering if I should expect to see staging data disappear once this is officially on.

**Comment by jperk51** [comment]
The LH group that is managing the intergration with disbaility rating has been trying to figure out this issue we uncovered for the past several months. This thread is where updates have been going: https://dsva.slack.com/archives/C02CQP3RFFX/p1697050321703279

We control the switch flip, not LH. I believe we still only have specific users on for it in staging, but when we do get closer to going live again we would turn it on for every, but the data should remain identical from the perspective of the Mobile app
