### ISSUE TITLE
TLC - Messages: smart component loading UX decisions to make

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7096]
## What happened?

Loading message details, when there are attachments, has some undesirable loading behavior.

Problem one (ticket #3331 ): _The full-page loading screen for opening an attachment is missing_

Problem two (this ticket): The spinner style for opening up a message and awaiting attachments filling in ('smart component' spinner, video below) seems to have gotten mixed up with opening an attachment (second spinner, which is being brought back to a loading page rather than loading indicator in the ticket above). This is the only place we have a smart component (once the message is opened, the component is calling to get the attachment info). 

 [(Spinner for attachment filling in)](https://drive.google.com/file/d/1AUrxN6OYJbXv0lgG4VUo3K3Y9w8uBsRX/view?usp=sharing)

## Specs:

- Device:
- OS:
- User Account: +41 or anyone else with messages with attachments (please open UNREAD messages when possible to preserve testing data, thanks!)
- Accessibility State:

## Steps to Reproduce

1. Log in.
2. Health > Messages > [pick an (ideally unread) message from the list, that has an attachment] > EXPAND THE MESSAGE WITH THE ATTACHMENT IN IT to get the 'smart component' spinner that this ticket is about 
3. Notice that the smart spinner a) is too big and b) isn't accessible
4.  Now tap the attachment name to open the attachment -> get teeny tiny spinner right next to the attachment link/name while you're waiting for the attachment to open, which is the original desired size for the smart component spinner

## Desired behavior

Smart components may feature more heavily in personalization attempts, so we should figure out what we want to do with them from a UX perspective, and then work with Eng to see if it's feasible.

Decisions that UX needs to make/things that need more investigation:
- [x] What's the behavior that we want for this smart component? (Should it be custom or native spinner? Does it have a string while it's loading? Etc) **A: Use custom component – indicated in the Figma mockup**
- [x] How should accessibility work for this component? (Right now it's not recognized/read out by screen readers, for example; also needs to work for Switch/Voice access, etc) **A: See A11y guidance outlined below**

**UPDATES 10/19/23:**
Design solution outlined in the comments. [Link to Figma here](https://www.figma.com/file/B3cMgZxUlawJhbK7ltDbco/Lauren's-Sandbox?type=design&node-id=1116-549&mode=design&t=J8tYHehkdNQI7FRO-4).

**A11y guidance**
- Label: "Loading"
- Role: Loading indicator
- Hint: "Loading your attachment"
- Status: Active (if this makes sense here?)
- Value: 1 of X (number of attachments that need to load)

## Acceptance Criteria

Solution as outlined:

Apply string below spinner, referenced in #3331
Localize the spinner to Attachments area
[Figma reference link](https://www.figma.com/file/B3cMgZxUlawJhbK7ltDbco/Lauren's-Sandbox?type=design&node-id=1116-549&mode=design&t=J8tYHehkdNQI7FRO-4)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--086210a2bfc9e0495ec1d57afdf11a55210cc1a1/image.png)

**Comment by TKDickson** [comment]
Switching to me since Tom is out

**Comment by TKDickson** [comment]
With [the build from this branch](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/6817933060), I'm not seeing the string in either iOS or [Android](https://drive.google.com/file/d/1c4g2QTYRLHLxQKUhy4-LqpZaZeehd4Tn/view?usp=drive_link). Moving back to in progress.

**Comment by Sparowhawk** [comment]
@TKDickson I do not see the video/picture on your 2nd link. It is requiring me to request access

**Comment by TKDickson** [comment]
Bah. Gave access; also Dylan already put in a fix for that problem. That's looking good - once there's FE PR approval again, this is good to merge.

**Comment by TKDickson** [comment]
Doesn't need further testing in develop, closing
