### ISSUE TITLE
Monthly data interpretation process: identify qualitative data 

### ISSUE THREAD

**Issue by lstraghalis** [department-of-veterans-affairs/va-mobile-app#7104]
As part of our monthly data interpretation efforts, we want to bring quantitative and qualitative data sources together in a monthly report in order to support our cross-functional teams in utilizing a data-led product development process.

As a first step, we need to identify the MVP qualitative data criteria we want to bring into a first draft of a monthly report.

Identify:
What qualitative data is most important to include? 
What qualitative data are we leaving out for now, and why?
How does it correspond to first draft of quantitative data?
How is the data presented together?

## Ticket Checklist

- [ ] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by bischoffa** [comment]
@liztownd can this ticket be closed? If not can you update the sprint to include Sprint 84?
