### ISSUE TITLE
Monthly data interpretation process: identify quantitative data 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7107]
As part of our monthly data interpretation efforts, we want to bring quantitative and qualitative data sources together in a monthly report in order to support our cross-functional teams in utilizing a data-led product development process.

As a first step, we need to identify the MVP quantitive data criteria we want to bring into a first draft of a monthly report.

Identify:
What qualitative data is most important to include?
What qualitative data are we leaving out for now, and why?
How does it correspond to first draft of quantitative data?
How is the data presented together?

### Ticket Checklist

- [ ]  Acceptance criteria defined
- [ ]  Labels added (front-end, back-end, feature)
- [ ]  Linked to an Epic

**Comment by g-opzt** [comment]
Initial conversations held this sprint. Conversation to wrap up outline of approach to be held tomorrow. @ajsarkar28 closing this ticket out in anticipation of the rollover/new ticket to be created for next sprint.
