### ISSUE TITLE
3rd Party BUG - Lighthouse migrated claims file upload has upstream bugs

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7119]
## What happened?

Evidence uploaded through the new migrated Lighthouse API (#4746) doesn't populate a received date, which allows veterans to upload multiple times (rather than 'knowing' that a particular request has been fulfilled).

This is a *not us* bug, but we will need to test the fix when the migration team has it done.

Screenshots (with LH, before LH):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--392dde997e7f4ec056500350474131c40697a46f/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7420746883b8a14de76bcc2505ebec460ec4baf/image.png)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by kellylein** [comment]
It looks like Source Comments and Uploading User Role are still missing in VBMS ([Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1699368803216669?thread_ts=1699298115.648559&cid=C018V2JCWRJ)).  Andrew to reach out to LH team to ensure they are aware.

**Comment by bischoffa** [comment]
@TKDickson @kellylein any update on this ticket? 

Also I see a bug label but no severity on it

**Comment by TKDickson** [comment]
@bischoffa I have no idea what the progress is on this. When I transitioned onto global several months ago, I also transitioned off of the EVSS migration testing. Is @kellylein still owning that project overall, or did it transition to @StacyB2023 at this point?

as far as the "no severity label", I think that's because it's not us. I found an issue with another team's code that we reported to that other team (and it _technically_ doesn't impact the mobile app, but does impact veterans who use the mobile app). 🤷‍♀️

**Comment by jperk51** [comment]
As far as I know the status of this hasn't changed. Claims got flipped but doc upload has never been on LH in prod for us and again afaik this is true for va.gov also. The hits to claims for evss was likely caused by a fix we put in recently. We noticed all attempts to upload docs were failing so we flipped claims back to evss while @Tonksthebear fixed the issue, but we have been back on LH for a couple weeks now.

**Comment by StacyB2023** [comment]
Ok cool. Yeah that most likely explains that API hit. I will share that with LH team.

@bischoffa Do we then want to close this?

**Comment by bischoffa** [comment]
@StacyB2023 thoughts on moving it to blocked until your hear back from LH once you follow-up with them? 

Based on LH comment we can close it or move it to blocked until they fix it.

**Comment by ala-yna** [comment]
@TKDickson - can you or someone on QA see if this is still an issue? When you have time?

**Comment by jperk51** [comment]
@ala-yna LH is still working on making fixes to their file upload implementation accord to the last update they gave so I would suspect this is not quite ready to test again. I don't mind if we close this though. LH is making less than transparent changes to file upload from what I understand so we will likely need to make a backend update once they are done before it's ready to test again.

**Comment by TKDickson** [comment]
@jperk51 @StacyB2023 whenever Lighthouse says that their document upload is finally ready again, is it on the list to have QA test? Because this particular bug went unnoticed by the Lighthouse QA process (whatever/whoever that is), and can't be found purely by mobile backend testing, so I'd want to have mobile QA take a look.

I'm fine with closing this ticket if we think we have a ironclad way to remember to have QA test the doc upload generally, and look for this issue in particular, whenever LH is ready.

**Comment by jperk51** [comment]
Yeah we definitely want to have you all test it again. I'm fine with leaving this open as the reminder for that since I don't think we have a "list" or anything like that it's just generally been part of the process of these LH migrations.

**Comment by TKDickson** [comment]
OK we officially have a policy on external tickets now, which is to close them after reporting to the upstream team. So closing this one as can't/won't fix, and I will be checking this when this eventually circles back around.
