### ISSUE TITLE
Investigate Datadog service graph functionality part 2

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7121]
Tim shared this link from the [datadog docs](https://docs.datadoghq.com/tracing/services/services_map/). Do some digging into it and report your findings. If it seems useful or possible we could set up a service graph go ahead and make tickets for doing so. 

ACs:
- [ ] Dig into datadog service graphs
- [ ] Make a test/example (if applicable)
- [ ] Make follow up tickets to build out a full service graph for us (if applicable)

**Comment by jperk51** [comment]
Carryover from #6768

**Comment by kpethtel** [comment]
Unfortunately, I don't think we can do much with the services graphs as they're currently configured. If you look at the vets-api service graph, you'll see it's very limited and only shows relationships between services within the vets-api, such as postgres and redis. Upstream services do not appear to be represented in the services list at all, so showing relationships with those is probably not possible without someone on the platform team configuring those services. It also doesn't show relationships between areas of code within the vets-api. It only shows relationships between hosted services. 

One thing I think could be possible and may merit exploration is creating a new graph on our dashboard that groups endpoints together based on which upstreams they consume. That could replace or supplement our current monitor alerts.
