### ISSUE TITLE
RX: Final Design Recommendations and Figma Prototype

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7125]
**Story:** 

As part of this story we want to:

Finalize design recommendations for list view changes in prescriptions (surfacing active prescriptions at the top of the list).

**Acceptance Criteria:**

- [x] - [Finalize design](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1499-15246&mode=design&t=Pdf29YJiblNoANm0-4) based on Friday's 10/20 convo
- [x] - Collaborate with Misty on final design using final copy 
- [x] - Share design with Kay / Coulton on DSVA design slack 
- [x] - Apply feedback from Kay / Coulton from the final design
- [x] - Create [figma prototype](https://www.figma.com/proto/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?page-id=1499%3A15245&type=design&node-id=1499-15407&viewport=584%2C321%2C0.18&t=kErprq55lSsUBCKO-1&scaling=min-zoom&starting-point-node-id=1499%3A15407&mode=design) with changes

**Other info:**

- Tentative for a future sprint demo

**Comment by kidlaurenpeace** [comment]
Added link to Figma [design](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1499-15246&mode=design&t=Pdf29YJiblNoANm0-4) and [prototype](https://www.figma.com/proto/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?page-id=1499%3A15245&type=design&node-id=1499-15407&viewport=584%2C321%2C0.18&t=kErprq55lSsUBCKO-1&scaling=min-zoom&starting-point-node-id=1499%3A15407&mode=design).
