### ISSUE TITLE
Backend: LH Docs tracked item ids not passing correctly 

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#7154]
#### Description
It was found during QA testing that tracking item ids are not passing correctly causing all doc uploaded to go into "other documents" list.

#### Dependent Issue

department-of-veterans-affairs/va-mobile-app#0000 or N/A

## Acceptance Criteria

- [ ] ...
- [ ] It logs its progression through the 'happy path' or helpful error details.
- [ ] I tested the feature on staging and could demo it if asked.
- [ ] Public Ruby API methods have [Yardoc](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md) comments.
- [ ] The [OpenAPI](https://swagger.io/specification/) documentation is up-to-date.

**Comment by TKDickson** [comment]
Adding notes from today - still isn't working as expected, and Andrew found a casing mismatch (see PR above). Should also be fixed on the FE, per Andrew:

> FE is sending multi image with snake case tracked_item_id  while single image is sent with camel case trackedItemId . The fix I put in assumed only one type. It should be Camel.

I will spin up a ticket for the FE fix and drop the ID in here.

**Comment by TKDickson** [comment]
Wrote up #7179 for the FE fix

**Comment by aherzberg** [comment]
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7196

**Comment by aherzberg** [comment]
@TKDickson Am I good to close this out in favor of the below ticket? 
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7196

**Comment by TKDickson** [comment]
@aherzberg we still need to update the mapping for SUBMITTED_AWAITING_REVIEW, right? I can make a comment in that other ticket if we're waiting/will do that in sync with upstream changes.

**Comment by TKDickson** [comment]
Never mind, I misread the other ticket the first time. Yep I'm good with that, can close this one.

**Comment by TKDickson** [comment]
Bah, better notes. Tracking ID is being passed appropriately for both single and multi files, closing. Still generally issues with claims upload, which is in the other ticket.
