### ISSUE TITLE
Update Canceled Appointment (Past and Upcoming) Details for Phone appts 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7157]
## Description 
As the VA, I want to update the Mobile App's Apt Phone Details View for Cancelled Appointments so that its more consistent with what the Veteran would see on the web. 

As part of this story we want to:   
- Update details screen view for canceled phone appts
- Remove colored status banners
- Remove add-to calendar link

## Documentation: 

[Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)

## Acceptance Criteria
  

**Upcoming Appointment**

1. - [ ]  Verify for Canceled phone appts (cancelled and upcoming) the following fields are displayed on the appt Details Screen

* Header reads: Canceled phone appointment
* Text: [Canceler] canceled this appointment. where Canceler is a dynamic field.  
* Display [Day/Date/Time] (existing)
* Dynamic text: [type of care]
   * If type of care is not available, display: Type of care not noted
* Dynamic text: [Provider name]
  * If provider name is not available, display: Provider not noted
* Details you shared with your provider (bold)
Reason: [Reason for appt]
Other details: [Booking note]
  - If Reason for visit is not available, display: Reason: Not noted 

`Get: /v0/appointments`: reason

**Reschedule Section**

Need to reschedule? (Bold)

If you need to reschedule this appointment, call us or schedule a new appointment on VA.gov.

[Scheduling facility's phone number] 
TTY: 711
External link: Go to VA.gov to reschedule (Goes to this link: https://www.va.gov/health-care/schedule-view-va-appointments/)

2. - [ ] Remove colored status banners for canceled and use body copy space after header to explained who canceled appointment. 

3. -  [ ] Remove add-to-calendar link for canceled appointments. 

## Figma Mock screens:

- [Canceled](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2156-14597&mode=design&t=BJgV9xp0NzxxcEmX-4)

- [Canceled-Empty States](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2156-15291&mode=design&t=BJgV9xp0NzxxcEmX-4)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
- Only VA points 
- Not impacting pending appointments
- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with an upcoming appoint
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by MekoHong** [comment]
@jperk51 FYI, these are the fields for the appt mapping update for phone type.  We currently show the canceler name on mobile, but it isn't always consistent with what web is displaying.  Confirming in with you to see if you know what field on the API documents that we show for canceler name?  cc: @bischoffa

**Comment by jperk51** [comment]
I figured out the issue. There is a field in the VAOS response called `cancellationReason` and a different field called `cancelationReason`. Currently we are using the wrong one. I will update the BE code to use the correct one and I believe that should resolve the issue on its own but I'll double check with the FE to make sure we return what they expect.

**Comment by bischoffa** [comment]
@jperk51 what is the ticket # for the BE work to use the correct field?

**Comment by jperk51** [comment]
Haven't made a ticket because we're still trying to confirm that's actually the issue. Seems like I was probably mistaken. Here's the thread with the appts team: https://dsva.slack.com/archives/CMNQT72LX/p1698696238506509

I'm creating a PR for some logging to confirm if this is even happening in prod or if it's just a staging data problem.

**Comment by jperk51** [comment]
I have identified the reason web and mobile are showing different things in staging though. The appt in question is missing the field which we use to determine who the "canceler" was. One web when the field is missing they default to CANCELLED BY FACILITY and we default to CANCELLED BY PATIENT. That being said the appts team is suggesting in the thread that this should be possible so it's either a bug in an adjacent system or a staging data problem.

**Comment by bischoffa** [comment]
Updated Design for Phone Only Cancelled Details [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzZZQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f1e50a1cc52cfce2b8c4b04c1159cf31c56d1da/image.png)

**Comment by bischoffa** [comment]
@jperk51 from your conversations is there BE changes that would prevent FE from working this ticket?

**Comment by jperk51** [comment]
I don't think so. Even if we ended up making a change we could work around whatever changes the FE has made

**Comment by jperk51** [comment]
Related: in the PR above I updated the backend to return "cancelled by clinic" when the cancellation field is missing from the VAOS response. This will at least make it so we match what web is doing, but I am still logging some info and work with them to make sure this is what we _should_ be doing. FE is still be good to go ahead with this ticket

**Comment by Sparowhawk** [comment]
@bischoffa What do I put for [Booking note]? We do not get this field in the api call

**Comment by jperk51** [comment]
Related slack thread: https://adhoc.slack.com/archives/C0206QFMXFU/p1700148297154639

I'm not sure what the purpose was supposed to be for the booking note field but that's no longer returned by VAOS and doesn't seem to show up on web as far as I can tell. Afaict, it's supposed to mimic the `You shared these details about your concern` field from web which comes from the `comment` field I mentioned in the slack thread. 
<img width="1032" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/11302644/a065fbb0-f0c1-43e8-80c1-82b17b4323bb">

**Comment by bischoffa** [comment]
Removed [Booking note] AC , backlog ticket will be added to look into this further at a future date

**Comment by rbontrager** [comment]
Verified that canceled phone appts match the acceptance criteria and the wireframe given by Adam in the comments.  Approved by QA.
