### ISSUE TITLE
Detox - Turn off in-app review in demo mode

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7158]
## What's going on
Some detox tests were failing because the in-app review was popping up, and since it's outside of the app we can't find it and tap on it with detox.

Best case scenario, we'd just turn off in-app reviews in demo mode (afaik, no one wants to demo them now anyways plus breaking detox tests).

I made an attempt, but actually delivering that will take longer than the pointed estimate on my ticket so I'm breaking it off into its own thing. 

ACs:
- [x] Turn off in-app review pop-up in demo mode (bonus points if it's done in a way where we could easily turn it back on again, should we at some point desire to make a "demo mode in-app review on" build)

### Notes if they're helpful
I attempted this in inAppReviews (bolded are my changes): 

export const registerReviewEvent = async (): Promise<void> => {
  **const { demoMode } = useSelector<RootState, DemoState>((state) => state.demo)**
  const prev = await AsyncStorage.getItem(STORAGE_REVIEW_EVENT_KEY)
  const total = prev ? parseInt(prev, 10) + 1 : 1
  await AsyncStorage.setItem(STORAGE_REVIEW_EVENT_KEY, `${total}`)
  const versionName = await getVersionName()
  if (total >= IN_APP_REVIEW_ACTIONS_THRESHOLD **&& !demoMode**) {
    const lastReview = await AsyncStorage.getItem(STORAGE_LAST_REVIEW_PROMPT_DATE_MILLIS)
    if (!lastReview) {
      await callReviewAPI(versionName)
    } else {
      const days = DateTime.fromMillis(parseInt(lastReview, 10)).diffNow('days').days
      const lastReviewVersion = await AsyncStorage.getItem(STORAGE_LAST_REVIEW_VERSION)
      if (days > IN_APP_REVIEW_INTERVAL_DAYS && lastReviewVersion !== versionName) {
        await callReviewAPI(versionName)
      }
    }
  }
}

That's breaking the detox tests as well, because then demo mode is off and we're attempting to do API calls that utterly fail.

**Comment by TimRoe** [comment]
A broad question to QA/engineering on this: does anyone care if these are fully suppressed for any dev environment? 

I can't speak for others, but I've found it a periodic annoyance draft testing and no one in a non-production build should be doing anything but closing it. This would miss VA/outside folks accessing demo mode from the production version, but that seems fine since it's existing behavior and probably a good-to-know for them to familiarize with the app.

**Comment by bischoffa** [comment]
Assigned to Global as it has to do with In-App review functionality. Coordinate with Rachael when this gets picked up.

**Comment by bischoffa** [comment]
@rbontrager given this is Detox related is this ticket still relevant as some time has passed.

**Comment by timwright12** [comment]
@TKDickson 

> That's breaking the detox tests as well, because then demo mode is off and we're attempting to do API calls that utterly fail.

Where were you seeing extra API calls being fire off? I'm looking though the app and `if( demoMode )` seems to be the way we would handle this kind of thing - it should just be checking the demomode status, not turning it on or off so I'm curious why didn't work in this instance. That conditional seems like it's inclusive to the entire function

**Comment by TKDickson** [comment]
@timwright12 the code changes I attempted (as included above) didn't work. IDK why it broke *every single* detox test, but it did. If you want to open a branch and give it a go, go for it! I'm sure you'll have more success troubleshooting than I did 😆

**Comment by timwright12** [comment]
yeah, I'll poke around. I feel like that code should have worked

**Comment by TKDickson** [comment]
Confirmed that in-app reviews still appear by default (after the triggering workflows) in staging. After turning off in-app reviews via the toggle, I could not get the review popup to appear.

I've got the [detox scripts that were previously broken because of adding further in-app review events](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10372739162/job/28716237914), running.

**Comment by TKDickson** [comment]
Those detox scripts are passing (minus a completely unrelated thing with finding an OK matcher for Prescriptions AF), so this is approved to merge.

**Comment by TKDickson** [comment]
Following up to remove the 'resetInAppReview' function from the many MANY places we're calling it, which will overall speed up running tests, will happen in #7159.

**Comment by TKDickson** [comment]
Confirmed (on a build with the latest changes) that in-app reviews still appear by default (after the triggering workflows) and after turning off in-app reviews via the toggle, I could not get the review popup to appear.

**Comment by TKDickson** [comment]
I can't approve merge to develop until I get an iOS on-demand build (doesn't seem specific to this ticket, but also need to make sure by getting a working build). Blocked for now.

**Comment by TKDickson** [comment]
iOS builds working again today (confirmed I could log in, toggle things -- can't confirm in-app review popup in iOS, see limitations in earlier comments). Approved to merge.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
