### ISSUE TITLE
Add Retries to the component integrations unit test run

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#7173]
The current [check-component-integrations.yml](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/.github/workflows/check-component-integrations.yml) workflow pulls in the flagship mobile app, wires up any of the new component code, and runs unit tests. The system is working fine, but sometimes unit tests can be flakey so we want to just add a retry to the unit test runs to surface only legitimate failures related to component code.

[Retry example](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/chore/wire-up-nvm/.github/workflows/code_checks.yml#L42)

AC:
- [ ] unit tests retry if they fail

**Comment by kellylein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7173?planning-poker) with Zenhub @narin @TimRoe @timwright12
