### ISSUE TITLE
BUG - sev-2 - Android - Login doesn't work with Edge

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7180]
## What happened?

After being successfully redirected back to the app from Edge authentication, you're never actually logged in. The veteran who reported this from Prod said he was dumped back to the sign-in option screen (initial app screen). Internally, I was stuck on this screen forever:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3FNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bce1b10f5da0cfe6a60facdd6fe75b80195fdfe8/image.png)

I assume it would also not work if I tap "stay in Edge" and I worry about the "remember my choice" option on this screen as well, in terms of how site-specific that toggle is in Edge..... [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3lNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2969d855047cf0d8dbfe7bc68dc32f4cfcf1623f/image.png)

See the JSON response section for what we're getting back from the sign-in service (I was using ID.me, as you will be able to tell)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

Edge is 0.33% of current US mobile browser share (less than Duck Duck Go), so low frequency.

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

https://staging-api.va.gov/v0/sign_in/callback?state=eyJhbGciOiJSUzI1NiJ9.eyJhY3IiOiJsb2EzIiwidHlwZSI6ImlkbWUiLCJjbGllbnRfaWQiOiJ2YW1vYmlsZSIsImNvZGVfY2hhbGxlbmdlIjoib3daUHBYdlBmRWJZeDNsVDhWbE4tMmxOR0hycURLeGY2Y2VwOU1mMWtCTSIsImNsaWVudF9zdGF0ZSI6bnVsbCwiY29kZSI6IjJiOTllNzhhZmQ2Yzg1NWQ4MjIzNWE2YjAwMzRhMzk0IiwiY3JlYXRlZF9hdCI6MTY5ODc4Mzg1MH0.RR-BdzZTWNfjDY7ZEZL3fwatSNMePooYd4sLDgAnQLkkIWPdVqthzzQjUv0HbxQg2dNmIG7VQ40SSee384tlu58_4FlvCul9thqzs_M0PNFOtskoopXDyiVhbcnS1q_8O6XzHaORRgVBWadACKu2qBleCWCf5gZnr874whbzH4AMwVzH3-cAphpKEyvMHw46n0ly-AWbOQ7du6zarrkJOcE-VgCWVwwANNLgq8tmqyNunKAqB8DMhpRmyDC9pIoeALzNX-Db_byoOs-zA7u1KRO_Lez1erD3Hm479N5tIZjUs2aC-G4DZugYx9fqdKsoMxMR6RYus-q66yhIzCxjFA&code=37ce5b35f9b5499396185faacc20bf31

HTTP/1.1 200 OK
Date: Tue, 31 Oct 2023 20:24:39 GMT
Content-Type: text/html; charset=utf-8
Etag: W/"ce5e702b850c4e3a38e9196744741e0a"
Referrer-Policy: strict-origin-when-cross-origin
Vary: Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Git-Sha: 8f8816768912dbc2c0ca03ccbe749968bd6ac055
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 8b900611-c3b6-4304-b7eb-902cfa702a11
X-Runtime: 3.073186
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Encoding: gzip
Transfer-Encoding: chunked
Connection: keep-alive

```
<html lang="en">
  <head>
    <meta http-equiv="refresh" content="0;URL=vamobile://login-success?code=1606663c-b29f-4fd9-943b-053af63570c5&amp;type=idme" />
  </head>
  <body></body>
</html>
```

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
CCing @StacyB2023 as I think this is tied to Custom Tab

**Comment by TKDickson** [comment]
There may be some device specificity for this? I was seeing on my Google Pixel 6 running Android 14.

**Comment by DJUltraTom** [comment]
some of the discussion in ticket [6736](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6736) may be relevant to this bug

**Comment by Sparowhawk** [comment]
@TKDickson can you check again. I believe @alexandec  PR that specifically launches an acceptable browser that was merged last week should be able to take care of this one.

**Comment by TKDickson** [comment]
Yeah, can't reproduce on that same device anymore with this morning's build, closing.
