### ISSUE TITLE
Send Failure Message via Slack when [Build] Release Build Fails

### ISSUE THREAD

**Issue by jennb33** [department-of-veterans-affairs/va-mobile-app#7184]
## Description 

When a new [Build] Release Build fails, there currently is no alert that is sent to the stakeholders in DSVA Slack noting the failure. 

We need to add, in the Slack thread, a note when these [Build] Release Builds fail so that the release can be manually re-run and the release has minimal delay. 

Add a retries to the yarn install steps for [build_ios.yml](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/build_ios.yml) and [build_android.yml](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/build_android.yml)

Content:
Version X.X.X experienced a failure for X [Platform]

**Important links**

- [Release Build history](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/release_build.yml)
- [Release Build workflow](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/release_build.yml)
- [Example of where we've already installed a retry](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/code_checks.yml#L41)
- [Slack alert example](https://dsva.slack.com/archives/C018V2JCWRJ/p1698695833908419)

**Comment by timwright12** [comment]
Retries were added to iOS on ticket #7822
