### ISSUE TITLE
Investigate/Add testrail integration for github action automation tests results

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7189]
## Description 
TestRail has a way to integrate with github actions so test automation results are displayed.  Investigate if this is possible and implement it if it is

## Acceptance Criteria
  

-  [ ] AC 1: Automation results are put in TestRail (pass/fail/skip) after the RC build testRail run is made
-  [ ] AC 2: Results are shown in the 'Regression Pass for release' run alongside any manual test cases
-  [ ] AC 3: The results show up no matter if the e2e workflows pass or fail

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by timwright12** [comment]
@rbontrager can you fill out the ACs on this ticket?

**Comment by timwright12** [comment]
Thanks!

**Comment by timwright12** [comment]
@rbontrager can you check off the ACs in the ticket just so we know someone confirmed that they're all met?
