### ISSUE TITLE
Veteran Status - Verify PRA Policy Impact for Veteran Feedback

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7195]
**Overview:**
As VA, I need to know if adding In-App Feedback to Proof of Veteran Status follows Paperwork Reduction Act (PRA) or if PRA clearance is needed to implement In-App Feedback Feature. 

**Other Info:** 
- In past Mobile feature conversations there has been comments that Mobile is limited to what feedback can be asked by the App to mobile users 
- Need to understand constraints or what approvals are needed for design an acceptable method to get feedback within the App
- Design proposed by mobile for In-App Feedback is just a proposal and did not look into if VA policy rules or regulations allowed it - when showing it to the VA POs there was no concerns proactively communicated 
- PRA policy, also known as [Paperwork Reduction Act](https://pra.digital.gov/do-i-need-clearance/). There are restrictions on in-app surveys if we ask the same yes/no or multiple choice question or question(s) to more than 10 people. We’d need to get PRA clearance, which can take 9+ months. However, we can ask open ended questions (like, “tell me about your experience using the app) without needing to go through PRA clearance.
- [Data and Insight Platform at VA uses Medallia](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/platform-data-sources) for va.gov surveys - I’m guessing they had to go through PRA clearance for that.

Acceptance Criteria: 

- PO's confirm and verify what PRA rules this in-app feedback needs to follow
- Identify who the PRA POs are 
- Follow necessary procedures / request processes if a new request is required

**Comment by timwright12** [comment]
@bischoffa Do we know what's up with this ticket and the other Veteran Status tickets it's blocking?

**Comment by bischoffa** [comment]
This ticket can be closed. This work was out of scope for Veteran Status. 

History: 

- As part of Veteran Status POs wondered if we could get feedback on if the Veteran was able to use Veteran Status and get a discount in the app when they pull it up
- It was something we investigated and found that Mobile cannot do on our own without an exemption from the PRA 
- Also found VA largely prefers to use their existing vendors who do this type of this such as Medelia (not sure I am spelling it right) 
- Given this work was not part of MVP we did not look at this any further 


Outcome: 

- Mobile cannot perform own feedback ask within the app per VA rules without exemption 
- Mobile needs to work with VA to partner with existing vendors that own the contracts for Veteran feedback 

Ticket closed
