### ISSUE TITLE
Backend: Investigate changed behavior for status changes from EVSS to LH claim document upload

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#7196]
#### Description
claim tracked item status does not change immediately after a document is uploaded. Investigate how this effects app behavior and if any changes are needed

See convo: 
https://dsva.slack.com/archives/C02CQP3RFFX/p1696352627608979
https://dsva.slack.com/archives/C018V2JCWRJ/p1698330605305639
#### Dependent Issue

department-of-veterans-affairs/va-mobile-app#0000 or N/A

#### Test users

vets.gov.user+000@gmail.com

## Acceptance Criteria

- [ ] ...
- [ ] It logs its progression through the 'happy path' or helpful error details.
- [ ] I tested the feature on staging and could demo it if asked.
- [ ] Public Ruby API methods have [Yardoc](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md) comments.
- [ ] The [OpenAPI](https://swagger.io/specification/) documentation is up-to-date.

**Comment by aherzberg** [comment]
PR is up and will probably be merged before end of sprint but will be with QA afterwards so won't be closed till next sprint.

**Comment by aherzberg** [comment]
PR is merged and in staging. @TKDickson, on LHs recommendation the `upload` has been changed to set to true when there's anything in the documents arrays. I've tested it and looks to be working. Let me know if you run into any more issues.

**Comment by TKDickson** [comment]
Document uploads associated with tracked items are now working as expected (showing the request as fulfilled) in the mobile app. Sort order for filled/not filled requests isn't working as it was pre-migration, that's ticket #7216 above. Closing this ticket, but will be doing more poking around in claims with all of the changes we've had to make recently.
