### ISSUE TITLE
Feature Request: Sign-in credential transition support

### ISSUE THREAD

**Issue by batemapf** [department-of-veterans-affairs/va-mobile-app#7208]
### Full Name

Patrick Bateman

### Email

patrick.bateman@va.gov

### What would you like to add as a new feature?

Sign-in credential transition support

## Headline

Over the next year, we're going to transition users of VA's Veteran-facing digital products (e.g., VA.gov, mobile app) to Login.gov and/or ID.me accounts. On or before December 1, 2024, we will stop accepting DSLogon and MHV accounts for purposes of signing into our digital products.

## Stories

"As a mobile app user that sign into the mobile app using a My HealtheVet account, I need to know that I will no longer be able to use my My HealtheVet account as a sign on method on December 1, 2024 (~12 months from now), so I can take the necessary actions to obtain/utilize a different sign in method." 

"As a mobile app user that sign into the mobile app using a DSLogon account, I need to know that I will no longer be able to use my DSLogon account as a sign on method on December 1, 2024 (~12 months from now), so I can take the necessary actions to obtain/utilize a different sign in method." 

## Timeline

Ideally we'd like to start messaging this change in December 2023.

## Considerations

- Messaging should be consistent across digital modalities
- Messaging should be targeted to DSLogon/MHV users (i.e., don't bother people who already use Login.gov / ID.me)
- Messaging should include clear, actionable call to action

**Comment by timwright12** [comment]
@batemapf Do we yet know how Web is handling this messaging? Asking because mobile just uses the [Web login page/modal](https://www.va.gov/?next=loginModal) pull in through a WebView. So, if the messaging is on that page for the Web it will also appear in the mobile authentication flow and we may not need anything special.

We might be able to target users after they've already signed into the app as well.

**Comment by batemapf** [comment]
We're coordinating with Web too, so thank you for pointing that out. I think we're mainly looking to see if there is any additional opportunity within the mobile app to help support the transition effort (like post-sign-in as you mentioned).

**Comment by rachelhanster** [comment]
Mobile may need to provide content to users before login. To make this decision, we need to understand the % of users with multiple login accounts, MHV/DS logon plus login.gov/id.me

**Comment by timwright12** [comment]
I spun up a ticket to confirm whether or not we're able to detect login method: https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7221

**Comment by timwright12** [comment]
Looks like we do have this data coming through v2 of our user endpoint, so we should be able to do this when the time comes.

<img width="357" alt="Screenshot 2023-11-08 at 3 58 58 PM" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/459581/e84e8dfe-4868-4679-9273-67f2b0afa695">
