### ISSUE TITLE
Status Counting Mechanism for Prescriptions

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7212]
**Background**
On the Personalized Home Screen, each feature will have a module that displays the number of active statuses which empowers veterans to have improved visibility as to  what is going on for each feature that they are using. For instance, the Home Screen could let a veteran know that they have 3 active prescriptions which consists of 1 prescription ready for refill and 2 prescriptions that are currently processing

This ticket covers the backend work to:
- determine which statuses should be counted active them summing
- sum up all statuses for a total count of active statuses 
- 

AC:
- [ ] Alongside product and UX, determine which statuses for Prescriptions count as "Active"
- [ ] Implement a mechanism to count the total number of "Active" statuses for Prescriptions
- [ ] Add count to meta field of prescriptions response 
- [ ] Update docs and specs

**Comment by Tonksthebear** [comment]
Lauren gave us a list of what is considered "active":
- active
- hold / provide hold(?)
- parked
- refill in process
- submitted
- + any 

refills that have current tracking #s associated
