### ISSUE TITLE
Backend: Investigate Central Hosting for apps

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#7224]
#### Description
As the title states, this discovery ticket is for investigating what it takes to host our apps centrally. We are now at the point with the reddit scraper that central hosting is desired. This can also benefit the visualizer.

## Acceptance Criteria
- [ ] Answer the question "how do we host"

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7224?planning-poker) with Zenhub @aherzberg @Tonksthebear
