### ISSUE TITLE
BUG - sev-3 - All - Slightly different info for special instructions on va.gov than mobile for some appts

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7225]
## What happened?

Once more, we seem to be pulling from slightly different fields for appointment details, for comments. It doesn't impact every appointment, but some of them. For the appointments where we don't show the same comments, we aren't even getting the same strings back from the backend, see excerpt in the JSON section.

Staging.va.gov for royal.tester@id.me, the Pharmacy appointment on Nov 16th:
"New medical issue: aefatrf"

Mobile, the same appointment:
"aefatrf"

## Specs:

- Device:
- OS:
- User Account: Staging.va.gov for royal.tester@id.me, the Pharmacy appointment on Nov 16th
- Accessibility State:

## Steps to Reproduce

Staging.va.gov for royal.tester@id.me, the Pharmacy appointment on Nov 16th

## Desired behavior

Should we show the same info? Probably, ideally, yes.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

Website:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c5bc8d2004c48bf582163fa2f96a6913a0b4e01/image.png)

Mobile:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWV3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15f334dfd6fdcb95aee91b127381bcb94169b04e/image.png)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  
```
 {
		"id": "192905",
		"type": "appointment",
		"attributes": {
			"appointmentType": "VA",
			"appointmentIen": "11643",
			"cancelId": "192905",
			"comment": "aefatrf",
			"healthcareProvider": null,
			"healthcareService": "CHY PHARMACY",
			"location": {
				"id": "983",
				"name": "Cheyenne VA Medical Center",
				"address": {
					"street": "2360 East Pershing Boulevard",
					"city": "Cheyenne",
					"state": "WY",
					"zipCode": "82001-5356"
				},
				"lat": 39.744507,
				"long": -104.830956,
				"phone": {
					"areaCode": "307",
					"number": "778-7550",
					"extension": null
				},
				"url": null,
				"code": null
			},
			"minutesDuration": 60,
			"phoneOnly": false,
			"startDateLocal": "2023-11-16T09:00:00.000-07:00",
			"startDateUtc": "2023-11-16T16:00:00.000+00:00",
			"status": "BOOKED",
			"statusDetail": "CANCELLED BY CLINIC",
			"timeZone": "America/Denver",
			"vetextId": "442;3231116.09",
			"reason": null,
			"isCovidVaccine": false,
			"isPending": false,
			"proposedTimes": null,
			"typeOfCare": "Pharmacy",
			"patientPhoneNumber": null,
			"patientEmail": null,
			"bestTimeToCall": null,
			"friendlyLocationName": "Cheyenne VA Medical Center",
			"serviceCategoryName": "REGULAR"
		}
```
</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
This may end up being a backend only bug fix, or could need both FE and BE. Starting with both labels for now.

**Comment by bischoffa** [comment]
Decided to move this out of bugs to the Appts Epic

**Comment by aherzberg** [comment]
@TKDickson I still see this appointment on the web but when calling the mobile endpoint directly, I can't see the appointment. Just to make sure I'm not missing something, is it still showing up in the app for you? There may be something filtering it out on the mobile side.

**Comment by TKDickson** [comment]
@aherzberg ugh, it's not showing up for me either anymore. I'm getting the Cerner alert for that patient where I don't think it was showing up before, which could potentially be related....? I can't guarantee it wasn't there during the original ticket writeup.

**Comment by TKDickson** [comment]
I do - at least - have the original response info for when it WAS showing up in mobile in the collapsible JSON section in the original ticket, does that help?

**Comment by aherzberg** [comment]
Yup, it does. But I should look into why it's not showing up now and not being consistent with web since It's still showing on web so think may be a separate issue with filtering. I'll look further into it, just wanted to make sure my backend call was consistent with the app. Thanks!

**Comment by aherzberg** [comment]
Fix looks to be working when hitting the endpoint directly! Moved to QA column

**Comment by DJUltraTom** [comment]
compared appointments with royal.tester in app and on web, looks like it matches up.
