### ISSUE TITLE
SPIKE - QA for Analytics

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#7226]
Spike to learn more about Sprint 0: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/QA%20for%20analytics/Sprint%200%3A%20QA%20for%20analytics.md

5pt time box to start.

**Comment by Sparowhawk** [comment]
@kellylein this should be addressed with ticket #6363

**Comment by bischoffa** [comment]
@dumathane can you confirm if this is carrying over?

**Comment by bischoffa** [comment]
@dumathane do you expect this ticket to be worked this sprint? If not how do you proposed we get it worked in this new structure?

**Comment by bischoffa** [comment]
Did not get picked up in Sprint 86 thus will be carryover again. Per discussions this is likely falling through the gaps during of the team transition. 

Posted to other PMs that Flagship App will need to pick up this work in order to support QA as QA does not have an engineering resource.

**Comment by TKDickson** [comment]
I don't _believe_ that I'd be needed for this spike, so un-(auto)assigning myself, but whoever picks it up feel free to lmk if you would like some QA eyes/time.

**Comment by theodur** [comment]
Adding some notes on findings and progress:

After looking into how to track analytics in different environments like staging, it seems like the recommended way is to create a Firebase project for each environment. I was able to create a [va-mobile-app-staging](https://console.firebase.google.com/project/va-mobile-app-staging/overview) project for staging. I tested logging analytics for staging by using the `GoogleService-Info.plist` and `google-services.json` files that are specific to the staging Firebase project in the build. The good news is I was able to see events being logged. The bad news is I wasn't able to see them in real time, even when looking at the [Realtime Analytics dashboard](https://console.firebase.google.com/project/va-mobile-app-staging/analytics/app/ios:gov.va.vamobileapp/streamview/realtime~2Foverview%3Ffpn%3D61889608576). There appears to be an hour-long delay for when events appear in Firebase. This means that QA would have to wait extended time frames to test analytics, which isn't ideal.

To provide a better experience for testing analytics, I started looking into enabling the DebugView in Firebase for QA and RC builds. There's also an [old ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/2775) for this as well. I was able to achieve this for iOS by adding logic to the build process that dynamically adds the `-FIRDebugEnabled` flag to the build process for QA and RC builds. 

Unfortunately, I ran into issues enabling DebugView for AppTester (Android) builds. DebugView for Android requires the `debug.firebase.analytics.app` property to be set to `gov.va.mobileapp`. I tried setting that dynamically in the build, but it didn't seem to work. Hopefully being able to test on TestFlight builds should meet our needs for now. I don't think there would be many times when we'd need to test analytics on a specific platform, but if we ever need Android functionality, we can always make another ticket and take another look.

**Comment by bischoffa** [comment]
Thanks @theodur for your work and progress on this! 

I added in @TKDickson given its a global ticket and its in a With QA column.

**Comment by TKDickson** [comment]
Timeboxing to a 2, given this is just the starting point. Want to focus on:
* Playing around with what shows up in firebase when it's enabled (how we could use this for testing analytics)
* Confirming (either with my own effort or talking with Theo) that this doesn't impact PROD/is easy to sort out from prod analytics

**Comment by TKDickson** [comment]
Neither @theodur nor I were able to get debugview events coming over when we attempted with the on-demand build workflow (even though he had been able to do it previously, it's strange).

The ['new staging environment' stuff](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7226#issuecomment-1940472129) may be the best bet for doing this in the future, even though there's a lag between taking the action and being able to confirm the flow in firebase.
