### ISSUE TITLE
Apple App Store + Google Play Store data update for November 2023

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#7228]
Monthly recurring task due between 4th-7th of the following month.

- [ ] Complete [Instructions here](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/App%20metrics/UpdatingDashboard)
- [ ] Create task for next month's update

**Comment by g-opzt** [comment]
@ajsarkar28 assigning to you until a new DA is in place in anticipation of my roll off of the team prior to the next update being due at the beginning of December.

**Comment by TKDickson** [comment]
Closing as outdated
