### ISSUE TITLE
BUG - 3 - All - Endpoint SID not cleared on logout

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7229]
## What happened?

The VEText team noticed an issue where signing out and signing in to a different account on the same device will still send push notifications of the previous account. It turns out that the device isn't being re-registered every time a user logs in on a device. Based on this [logic](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/d1aae9b92df5bde5fe18d2f316c6d5bf4d303098/VAMobile/src/store/slices/notificationSlice.ts#L61), clearing the endpoint SID on logout will ensure the device is re-registered to with VA Push notifications when signing in.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Hey @theodur - are you going to want/recommend our QA team to take a look at this when it's done?

**Comment by theodur** [comment]
@TKDickson Assuming my PR doesn't need any changes, I think we should be good to skip QA. The VEText team is doing their own testing on a build I made for them, which is why I haven't opened the PR for review yet (waiting for them to complete their testing)

**Comment by TKDickson** [comment]
Based on a conversation in DSVA slack, moving this ticket back to 'in progress' - needs to be checked with Product/UX stakeholders before the change in behavior (users no longer receive PN after they log out of the app) is moved ahead.

**Comment by TKDickson** [comment]
If/when this ticket makes it back to a testable state, (and if it's still relevant when that happens) some of the things discussed to test are:
* Does the behavior change for users who log out (but have not yet logged back in again)
* Does this behavior impact users who time out, and have not signed back in again (ex: token expires when they're trying to do a thing, and they're like ARGH I'll just do it later so they don't continue to log in again)
* How would this work, hypothetically, for two users who share the same device? (original bug question)
* Is the solution going to result in a spike in PN registration calls (either one time, or ongoing)

**Comment by theodur** [comment]
The implementation for this has been updated and is in code review again. To answer your questions @TKDickson:

> Does the behavior change for users who log out (but have not yet logged back in again)

No, this behavior will remain the same. Users who log out will still get push notifications

> Does this behavior impact users who time out, and have not signed back in again (ex: token expires when they're trying to do a thing, and they're like ARGH I'll just do it later so they don't continue to log in again)

No, won't impact users who time out. As long as a user has logged in the app at some point, that device will always be registered for push notifications for that user until they delete the app or a new user signs in

> How would this work, hypothetically, for two users who share the same device? (original bug question)

With the fix that was implemented, the app will save the user ID in the device storage (async storage) after they log in so we can reference it for subsequent logins. When a new user logs in, the app will compare the new user's ID with the ID in async storage. If the user ID matches what's in async storage, the app won't re-register the device (which is also the current behavior). But if the user ID doesn't match the ID in async storage, we know a new user has logged in, so the app will re-register the device with VEText. Re-registering the device with VEText will remove the previously logged-in user's relation with the device in VEText's database

> Is the solution going to result in a spike in PN registration calls (either one time, or ongoing)

This will most likely increase the number of PN registration calls, but it shouldn't be by a large amount. Since we'll only be re-registering when new users log into a device, this won't impact most users, only those who share devices with other people, which is probably a small percentage of users

**Comment by theodur** [comment]
I'm going to reach out to the VEText team so they can retest this on their end. The user time-out scenario you were originally going to test doesn't apply @TKDickson. It wouldn't hurt for QA to test basic login functionality to ensure nothing funky is happening, though. Technically, the actual bug could also be tested by using the SM portal and sending a user a message, which would trigger a push notification, then signing out and signing in to a different user, and re-sending a message to the previous user. But since the VEText team will be testing this on their end, that kind of testing is probably optional

**Comment by TKDickson** [comment]
Awesome, thanks for the explanations @theodur -- this new solution I like a lot. I will do basic login/nothing super broken testing for the mobile app, and then just hold for an update from the VEText team on this ticket.

**Comment by TKDickson** [comment]
What I did on iOS and Android:
1. Log in. Opt out of PN when prompted (iOS only). Navigate to the Notifications screen (in Profile, then Settings) -- tells me to go to settings to turn on PN.
2. Turn on PN for the VA mobile app in device settings, then go back to mobile app -- shows me a list of PN preferences.
3. Change from the default preferences, then forcequit the app. Log back in -- not re-prompted for PN opt-in.
4. Go to Notifications screen again -- remembers my preferences (not reset to default).

iOS worked great. 

@theodur With the build for this branch, on Android, at step 2 when attempting to turn on PN for app, I saw this which does not allow me to turn on PN for the app:
<img width="379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6b34a6f70f8a1dac6a0e7a6da6c444aaf2351b0/image.png" alt="image.png" />


On the develop branch daily build for today, running the same workflow with the same user (+54), I saw this which does allow me to turn on PN for the app:
<img width="379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejU2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27a719a96c809fa85d9c9c5e8cd930fae55b0726/image.png" alt="image.png" />

**Comment by theodur** [comment]
@TKDickson It just hit me that this is an existing bug in the app. I remember Narin running into a similar issue, and Tom confirmed on his end as well ([Slack thread](https://adhoc.slack.com/archives/C0212B872MT/p1691606009599799)). It must be something related to Pixels because both Narin and Tom were using Pixel devices, and I assume you are as well. I saw the same issue on my Pixel emulator but not my physical Samsung device

**Comment by TKDickson** [comment]
That ticket, as in the little in between thing in the timeline immediately prior to this, is #7611.

**Comment by theodur** [comment]
@TKDickson Shane from VEText tested this today and confirmed it's working 🎉 I'll wait for your thumbs up before merging

**Comment by TKDickson** [comment]
@theodur I think we're good. I did the basic testing I wanted to, I've written up that pre-existing Android issue, and the VEText team has signed off..... I will go sign off on the PR, and advance this ticket.

**Comment by TKDickson** [comment]
No additional testing needed in develop, closing.
