### ISSUE TITLE
Waygate (availability framework) Implementation: Benefits

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#7232]
## Description 
Waygates need to be placed and confirmed toggle-able in three different use cases across all applicable pages within the app. 

As part of this story we want to:   

- Ensure all relevant pages are able to be intercepted by a waygate setup and display as we would want them to.

## Acceptance Criteria
  

The following three AC's need to be applied to the attached list of screens:

-  [ ] Confirm Use Case 1 appropriately intercepts page navigation to the given page.
-  [ ] Confirm Use Case 2 appropriately disables screen content and is replaced by only an alertbox.
-  [ ] Confirm Use Case 3 displays a warning alertbox as well as the associated screen content.
-  [ ] Confirm Error and Loading states still display as we would expect.

List of Screens:

  | 'WG_DisabilityRatings'
  | 'WG_Claims'
  | 'WG_ClaimsHistory'
  | 'WG_LettersOverview'
  | 'WG_LettersList'
  | 'WG_BenefitSummaryServiceVerificationLetter'
  | 'WG_ClaimLettersScreen'
  | 'WG_ClaimDetailsScreen'
  | 'WG_AppealDetailsScreen'
  | 'WG_ConsolidatedClaimsNote'
  | 'WG_WhatDoIDoIfDisagreement'
  | 'WG_FileRequest'
  | 'WG_FileRequestDetails'
  | 'WG_AskForClaimDecision'
  | 'WG_SelectFile'
  | 'WG_TakePhotos'
  | 'WG_UploadFile'
  | 'WG_UploadOrAddPhotos'

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
Rachael:
| 'WG_Claims'
| 'WG_DisabilityRatings'
| 'WG_LettersOverview'
| 'WG_LettersList'
| 'WG_BenefitSummaryServiceVerificationLetter'
| 'WG_ClaimLettersScreen'
| 'WG_ClaimsHistory'
| 'WG_AskForClaimDecision'

Therese:
| 'WG_AppealDetailsScreen'
| 'WG_ConsolidatedClaimsNote'
| 'WG_WhatDoIDoIfDisagreement'
| 'WG_FileRequest'
| 'WG_FileRequestDetails'
| 'WG_SelectFile'
| 'WG_TakePhotos'
| 'WG_UploadFile'
| 'WG_UploadOrAddPhotos'

**Comment by TKDickson** [comment]
Rachael and I's testing documented against the [AF milestone in test rail.](https://dsvavsp.testrail.io/index.php?/milestones/view/1395)

**Comment by TKDickson** [comment]
Spotchecked some Benefits screens; they are still enabled in develop. Closing.
