### ISSUE TITLE
BUG - Sev -3 - All - Include Vaccine Records in Mobile's Maintenance Window Logic - Backend

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7236]
## What happened?

Identified during COLA 2023 that Vaccine Records does not have a maintenance window and is the only feature that does not have one. Thus want to add maintenance window logic to Vaccine Records

Backend to return a maintenance window that is accessible by front end to consume. Frontend's work is on a separate ticket - see dependencies section

## Specs:

- Device: Any
- OS: Any 
- User Account:
- Accessibility State: Match existing accessibility needs that is currently being used by other maintenance window logic 

## Desired behavior

Vaccine records should be included in maintenance window logic for mobile 

## Acceptance Criteria

Mobile to show a maintenance screen for Vaccine Records when needed / triggered

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Linked to Story
 
[7219](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7219)

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
I added Scrubbed Label as we know its an issue.

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7236?planning-poker) with Zenhub @aherzberg @Tonksthebear
