### ISSUE TITLE
BUG - Sev -3 - All - Include Vaccine Records in Mobile's Maintenance Window Logic - Front End 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7237]
## What happened?

Identified during COLA 2023 that Vaccine Records does not have a maintenance window and is the only feature that does not have one. Thus want to add maintenance window logic to Vaccine Records

Frontend to consume maintenance window information from backend and display current maintenance window content for Vaccine Records. 

## Specs:

- Device: Any
- OS: Any 
- User Account:
- Accessibility State: Match existing accessibility needs that is currently being used by other maintenance window logic 

## Desired behavior

Vaccine records should be included in maintenance window logic for mobile 

## Acceptance Criteria

Mobile to show a maintenance screen for Vaccine Records when needed / triggered

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Linked to Story
 
[7219](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7219)

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
Removed from next sprint as BE needs to do their work first. So it should be ready for Sprint 86

**Comment by bischoffa** [comment]
Backend work has been completed

**Comment by alexandec** [comment]
Talked with @kpethtel and said that `immunizations` is the correct maintenance window to use for vaccination data. Used that in the PR for this ticket.

**Comment by DJUltraTom** [comment]
verified that the "immunizations" maintenance window is working as expected
QA approves this change

**Comment by DJUltraTom** [comment]
verified maintenance window is recognized and works as designed with overnight QA build
closing ticket

**Comment by bischoffa** [comment]
@jperk51 fyi maintenance window for vaccine records has been completed.
