### ISSUE TITLE
CU - Clean up Appeal Current Status file

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7247]
There are several groupings of strings that can be combined like:

appealStatusDisplayedData.details = [
        translation('appealDetails.statutoryOptInDescription1'),
        translation('appealDetails.statutoryOptInDescription2'),
        translation('appealDetails.statutoryOptInDescription3'),
        translation('appealDetails.statutoryOptInDescription4'),
        translation('appealDetails.statutoryOptInDescription5'),
      ]

This ticket is to go through the file and combine all the strings that can be combined and to remove the unneeded ones from the common translation file.

**Comment by hasahmed2** [comment]
Upon further investigation, the way the strings are broken up are used to specify the exact way that they are rendered in the page and as such merging the strings together will not be as simple as that, but instead will require a more thought-out analysis of each individual group of strings. Here is an example of how the individual string elements of the array are used to render body and link text differently.

![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/148818278/20b22521-8eb4-4a7b-84a1-871d389cbeb5)

For future reference, here is an example of a possible approach to injecting links into strings using regex already in use within the mobile application: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7076
