### ISSUE TITLE
Transfer Backend on call schedule into pagerduty

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#7251]
Take the on call schedule that is currently in Slack and move it into the new pagerduty team.

[Mobile team schedule page](https://dsva.pagerduty.com/teams/PSACBVG#schedules)

**Definition of Done**

- [ ] Schedule has been transferred and set up
- [ ] Weekly slack alerts are still happening as before, but coming from PagerDuty

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7251?planning-poker) with Zenhub @aherzberg @Tonksthebear

**Comment by kpethtel** [comment]
I imported the schedule but as far as I can tell pager duty doesn't allow notifications to slack regarding the on call schedule. I've created [this](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7413) ticket to implement an escalation policy that will use the schedule.
