### ISSUE TITLE
BUG - sev-3 - All - Availability Framework - AF alert should always be below VCL banner

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7255]
## What happened?

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDdNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75ba96dd453a60ca2ea2cbd9ad5913a9e1eb0d28/image.png)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

For accessibility reasons + it's the app standard, the VCL should always be directly below the header and above any content that falls within the screen

Which means our AF alertbox needs to go below the Veterans Crisis Line banner, and it currently goes above it.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
just to help out since I kind of know what the code looks like the issue is the waygate wrapper needs to just wrap the children in this area of the category landing screen:

return (
    <View style={fillStyle}>
      <StatusBar translucent barStyle={theme.mode === 'dark' ? 'light-content' : 'dark-content'} backgroundColor={theme.colors.background.main} />
      <HeaderBanner {...headerProps} />
      <WaygateWrapper>
        <VAScrollView testID={testID} scrollEventThrottle={title ? 1 : 0} onScroll={onScroll} {...scrollViewProps}>
          <View onLayout={getTransitionHeaderHeight}>
            <CrisisLineCta onPress={navigateTo('VeteransCrisisLine')} />
            {title && !screenReaderEnabled ? <TextView {...subtitleProps}>{title}</TextView> : null}
          </View>
          {children}
        </VAScrollView>
      </WaygateWrapper>
    </View>
  )

That will allow the waygate wrapper to scroll and it will keep the VCL banner where it should be

**Comment by TKDickson** [comment]
Testing (and testing saga) documented on #7259. Both tickets are now OK to merge to develop when AF is ready.

**Comment by TKDickson** [comment]
Confirmed this fix is still present in develop, closing.
