### ISSUE TITLE
Appt List - In Person Only Cards - Update Card 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7256]
## Description 
As the VA, I want to update the Mobile App's Apt List cards for In-Person only appointments so that its more consistent with what the Veteran would see on the web. 

## Acceptance Criteria
  

Update Appointment Card for VA Appointments

- [ ]  [Status] icon
- [ ]  [Day/date/time] (bold)
- [ ]  [Type of care]
   - [ ]   If type of care is not available, display: Type of care not noted
- [ ]  [Provider name]
   - [ ]   If provider name is not available, display: Provider not noted
- [ ]  Modality icon At [facility name]

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXpNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac10e8aa80e661c0269bb3870d1b31a5bdb67eff/image.png)

## Documentation 

- [Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)
- Figma File for Reference -  [Appt List - In Person Appt - Card Design Update](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2245-4711&mode=design&t=5IOV03gfsWL9K5xV-0)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
- VA appointments only - no changes to community care appointments
-  When an data field is empty (not an error, we just don't have the info), we will not omit that field but instead show copy to communicate that this information is not available/known in our system. This creates consistency in the number of fields that are always shown on the list view card. (Note: Empty field is different than error.)
- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with in person appts
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by DJUltraTom** [comment]
Looks like this build completely breaks appointments in demo mode, both iOS and android, we get a black screen.

**Comment by DJUltraTom** [comment]
verified we are seeing the correct changes for in person appointment cards on the overnight QA build
Closing ticket
