### ISSUE TITLE
Update Canceled Appointment (past or upcoming appts ) Details for In Person appts 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7258]
## Description 
As the VA, I want to update the Mobile App's In Person VA Appoints Details View for Cancelled Appointments so that its more consistent with what the Veteran would see on the web. 

As part of this story we want to:   
- Update details screen view for canceled VA phone appts

## Documentation: 

[Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)

## Acceptance Criteria
  

**Details upper section**

- [ ]  Header reads: Canceled in-person appointment (bold)
- [ ]  Text: [Canceler] canceled this appointment. (where Canceler is a dynamic field)
- [ ]  [Day/Date/Time] (bold)
- [ ]  [type of care]  (bold)
   - [ ]    If type of care is not available, display: Type of care not noted
- [ ]  [Provider name]  (bold)
   - [ ]   If provider name is not available, display: Provider not noted
- [ ]  [Clinic name]  (bold)
- [ ]  Text: Clinic location: [physical location] (where physical location is a dynamic field
   - [ ] If physical location is not available display: Clinic location: Not noted   
- [ ]  [Facility name]  (bold)
- [ ]  [Facility address line 1]
- [ ]  [Facility address line 2]
- [ ] Icon [Facility phone #] (link)
- [ ] Icon TTY: 711 (link)
- [ ] Details you shared with your provider (bold)
- [ ] Reason: [Reason for appt]
   - [ ]  - If Reason for appt is not available, display: Reason: Not noted 

**Reschedule Section**
- [ ]  Header reads: Need to reschedule? (bold)
- [ ]  If you need to reschedule this appointment, call us or schedule a new appointment on VA.gov.
- [ ] Icon [Scheduling facility's phone number] 
- [ ] Icon TTY: 711
- [ ] External link: Go to VA.gov to schedule (Goes to this link: https://www.va.gov/health-care/schedule-view-va-appointments/)

- [ ]  Remove colored status banners for canceled appointments as body copy will be enhanced

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe448c4b194633ef35ee8d8125720c9bd7df5b1e/image.png)

## Figma Mock screens:

- [In Person Cancelled Appt](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2299-17981&mode=design&t=5IOV03gfsWL9K5xV-4)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
- Past and upcoming appointments that are cancelled 
- add to calendar link removed 
- VA appointments only - no changes to community care appointments
 - physical_location field that should sometimes include clinic floor/room #.
 - Peter confirmed phone number is always the main facility phone number (not clinic number) for VA appointments.
 - Add-to-calendar link for cancelled appointments removed 
 - Don't hide empty states 
- Only VA appointments
- Not impacting pending appointments
- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with an upcoming appoint
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by bischoffa** [comment]
Removed [Booking note] AC , backlog ticket will be added to look into this further at a future date

**Comment by DJUltraTom** [comment]
test cases here: https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12986&group_order=asc&display_deleted_cases=0

**Comment by rbontrager** [comment]
Waiting for resolution on: https://dsva.slack.com/archives/C03CGTDLTFF/p1706023246099669

Couple issues have been found while going through the test cases. 
- Showing the get directions link for cancelled/past appts when you shouldn't be
- Missing a dash between the area code and the phone number in the you need to reschedule section
- Upper section details are out of order.  Clinic name is before the provider name when according to above it should be after
- Spacing doesn't match the figma design between  [Canceler] canceled this appointment and the date

Couple demo json problems as well 
- typeOfCare, healthcareProvider, reason, and healthcareService fields are missing causing the type of care, provider, clinic, and details you share with your provider to be missing in the details section

**Comment by Sparowhawk** [comment]
@rbontrager 

1. directions link is fixed
2. fixed the missing dash
3. the section details are correct. It goes type of care, provider, then facility

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeno5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b546b3aa5e2cc1bb30dd11befb30c1e7d90962ea/Screenshot%202024-01-25%20at%2010.54.24%20AM.png" alt="Screenshot 2024-01-25 at 10.54.24 AM.png" />

4. spacing is following the WCAG 2.2 guidelines
5. moved that section to below reason sections


6. here is how most of those sections are coded
if (phoneOnly || (appointmentType === AppointmentTypeConstants.VA && serviceCategoryName !== 'COMPENSATION & PENSION')) {
    return (
      <TextView variant="MobileBodyBold" accessibilityRole="header" mb={theme.dimensions.standardMarginBetween}>
        {typeOfCare || healthcareService || t('appointments.noTypeOfCare')}
      </TextView>
    )
  }
  return <></>

so if typeOfCare or healthcareService exists it will display only for phone/in person va non C&P appts, otherwise it will show not noted for those appts. For all other appts that section is hidden. I checked all the sections you listed here and they follow the same thing.

So if those sections aren't showing then it is an issue with how the demo mode data is classified in it's type. Likely it is a C&P appt in the code.

**Comment by rbontrager** [comment]
A couple of the appointment previews say 'Type of care not noted' but then there is something in that field in the appointment details itself (see picture).  

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9CQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b25961d189a2ffbdabd345f32a00339647b3074f/1FEE43A9-EFCA-4DD3-88CE-678F1EA439A9.png" alt="1FEE43A9-EFCA-4DD3-88CE-678F1EA439A9.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTBCQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f27720dc0f155bc6b9b89ccb3a757d065b346a7/ECA88212-B619-49D6-B95F-852FFE5CDAF7.png" alt="ECA88212-B619-49D6-B95F-852FFE5CDAF7.png" />

**Comment by DJUltraTom** [comment]
yes! successfully completed test run with all the test cases,
[Test run here](https://dsvavsp.testrail.io/index.php?/runs/view/5111&group_by=cases:section_id&group_order=asc)
QA approves this change!

**Comment by DJUltraTom** [comment]
spot checked with judy.morrison and its looking good
