### ISSUE TITLE
Update Past Appointment Details for In Person appts 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7262]
## Description 
As the VA, I want to update the Mobile App's In Person VA Appoints Details View for Past Appointments so that its more consistent with what the Veteran would see on the web. 

As part of this story we want to:   
- Update details screen view for VA cancelled In Person appointments 

## Documentation: 

[Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)

## Acceptance Criteria
  

**Details section**

- [ ]  Header reads: Past in-person appointment (bold)
- [ ]  Text: This appointment happened in the past.
- [ ]  [Day/Date/Time] (bold)
- [ ]  [type of care]  (bold)
   - [ ]    If type of care is not available, display: Type of care not noted
- [ ]  [Provider name]  (bold)
   - [ ]   If provider name is not available, display: Provider not noted
- [ ]  [Clinic name]  (bold)
- [ ]  Text: Clinic location: [physical location] (where physical location is a dynamic field)
   - [ ] If physical location is not available display: Clinic location: Not noted   
- [ ]  [Facility name]  (bold)
- [ ]  [Facility address line 1]
- [ ]  [Facility address line 2]
- [ ]  Icon [Phone] (link)
- [ ]  Icon TTY: 711 (link)
- [ ] Details you shared with your provider (bold)
- [ ] Reason: [Reason for appt]
    - [ ]  - If Reason for appt is not available, display: Reason: Not noted 

**Reschedule Section**
- [ ]  Header reads: Need to schedule another appointment? (bold)
- [ ]  If you need to schedule another appointment, call us or schedule a new appointment on VA.gov.
- [ ] Icon  [Facility's phone number] 
- [ ] Icon TTY: 711 (link)
- [ ] External link: Go to VA.gov to schedule (Goes to this link: https://www.va.gov/health-care/schedule-view-va-appointments/)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3pNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d46082ba33a44c3909279974f711ae7ade0b3471/image.png)

## Figma Mock screens:

- [In Person Cancelled Appt](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2299-17598&mode=design&t=5IOV03gfsWL9K5xV-4)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
- add to calendar link removed 
- VA appointments only - no changes to community care appointments
 - physical_location field that should sometimes include clinic floor/room #.
 - Peter confirmed phone number is always the main facility phone number (not clinic number) for VA appointments.
 - Don't hide empty states 
- Only VA appointments
- Not impacting pending appointments
- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with an upcoming appoint
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by bischoffa** [comment]
Removed [Booking note] AC , backlog ticket will be added to look into this further at a future date

**Comment by DJUltraTom** [comment]
test case is here: https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12986&group_order=asc&display_deleted_cases=0

**Comment by DJUltraTom** [comment]
yes! successfully completed test run with all the test cases,
[Test run here](https://dsvavsp.testrail.io/index.php?/runs/view/5111&group_by=cases:section_id&group_order=asc)
QA approves this change!

**Comment by DJUltraTom** [comment]
spot checked appointments with judy.morrison and things are looking groovy.
