### ISSUE TITLE
Update Upcoming Appointment (Confirmed) Details for In Person appts 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7265]
## Description 
As the VA, I want to update the Mobile App's In Person VA Appoints Details View for Upcoming Appointments so that its more consistent with what the Veteran would see on the web. 

As part of this story we want to:   
- Update details screen view for canceled phone appts

## Documentation: 

[Get: /v0/appointments](https://department-of-veterans-affairs.github.io/va-mobile-app/api/#/paths/~1v0~1appointments/get)

## Acceptance Criteria
  

**Details section**

- [ ]  Header reads: In-person appointment (bold)
- [ ]  Text: Go to [facility name] for this appointment.
- [ ]  [Day/Date/Time] (bold)
- [ ]  Click to action link: Add to calendar 
- [ ]  [type of care]  (bold)
   - [ ]    If type of care is not available, display: Type of care not noted
- [ ]  [Provider name]  (bold)
   - [ ]   If provider name is not available, display: Provider not noted
- [ ]  [Clinic name]  (bold)
- [ ]  Text: Clinic location: [physical location] (where physical location is a dynamic field)
    - [ ] If physical location is not available display: Clinic location: Not noted   
- [ ]  [Facility name]  (bold)
- [ ]  [Facility address line 1]
- [ ]  [Facility address line 2]
- [ ]  Icon Get directions (Click to action link )
    - [ ] If longitude / latitude date is not available, hide this   
- [ ] Icon [Facility phone #] (link)
- [ ] Icon TTY: 711 (link)
- [ ] Details you shared with your provider (bold)
- [ ] Reason: [Reason for appt]
- [ ]  - If Reason for appt is not available, display: Reason: Not noted 

**Reschedule Section - When not cancelable through the app**
- [ ]  Header reads: Need to reschedule or cancel? (bold)
- [ ]  If you need to reschedule or cancel this appointment, call us.  
- [ ] Icon [Facility phone #] 
- [ ] Icon  TTY: 711 (link)

**Reschedule Section - when its cancelable through the app**
- [ ]  Header reads: Need to reschedule or cancel?  (bold)
- [ ]  You can cancel this appointment in the app. But if you need to reschedule, call us.
- [ ] Icon [Facility phone #] 
- [ ] Icon TTY: 711 (link)
- [ ] Cancel appointment button 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZNQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--412a5a0ea17d816320fa6dd0bef566ed597a51af/image.png)

## Figma Mock screens:
- In Person Details for Upcoming Appointment](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2299-17598&mode=design&t=5IOV03gfsWL9K5xV-0)

## Accessibility Requirements
- [ ] Screen reader accessible 

## Notes & Open Questions
 - physical_location field that should sometimes include clinic floor/room #.
 - Peter confirmed phone number is always the main facility phone number (not clinic number) for VA appointments.
 - Don't hide empty states 
- Only VA appointments
- Not impacting pending appointments
- Dependencies/Roadblocks: No
- Any internal/external dependencies? No 
- Test accounts needed? Yes, one with an upcoming appoint
- Does this require QA? Yes - comparison of old vs new 
    
- Dev Notes: 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
@bischoffa The title of this ticket said this was for past and upcoming but the content of this ticket is really just for upcoming (confirmed) appt. You'll need a separate ticket for past, if you don't already have it.

**Comment by bischoffa** [comment]
Removed [Booking note] AC , backlog ticket will be added to look into this further at a future date

**Comment by DJUltraTom** [comment]
test cases found here: https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=12986&group_order=asc&display_deleted_cases=0

**Comment by Sparowhawk** [comment]
@rbontrager 

The spacing for both is following the WCAG 2.2 guidelines. It is figma that is off.

@brea11y  can you confirm the WCAG 2.2 spacing for those 2 sections. So I can adjust if needed.

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Q5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--602fa3b9b08464cd0411edb8087ddf69e2da36f5/Screenshot%202024-01-25%20at%2010.24.43%20AM.png" alt="Screenshot 2024-01-25 at 10.24.43 AM.png" />

**Comment by Sparowhawk** [comment]
@rbontrager null-null is now fixed

**Comment by brea11y** [comment]
@Sparowhawk The spacing is right in your screenshot.

**Comment by rbontrager** [comment]
@Sparowhawk Seeing the same thing with confirmed appts that I was seeing with canceled where it says 'type of care' not noted in the appt list but then has a typeOfCare value in the appt details.

**Comment by Sparowhawk** [comment]
@rbontrager That should be fixed for all the appts. It uses typeOfCare if noted first then healthcareService then typeOfCare not noted string

**Comment by DJUltraTom** [comment]
yes! successfully completed test run with all the test cases,
[Test run here](https://dsvavsp.testrail.io/index.php?/runs/view/5111&group_by=cases:section_id&group_order=asc)
QA approves this change!

**Comment by DJUltraTom** [comment]
spot checked appointments with judy.morrison and things seem to be appearing as expected
