### ISSUE TITLE
UI Automation - Claims Expansion

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7266]
## Description 
As part of this story we want to make a new test that covers the following for claims:

- Add testing for each claim type
- Add testing for each claim step

## Acceptance Criteria
  

-  [ ] Test covers all the areas mentioned above
-  [ ] Test runs properly on github actions on android and iOS/locally on android and iOS

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by DJUltraTom** [comment]
need to add:
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5787
