### ISSUE TITLE
UI Automation - Contact Info Expansion

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7269]
## Description 
As part of this story we want to make a new test that covers the following for contact info:

- Add testing for military base/non-US countries contact info addresses
- Error handling

## Acceptance Criteria
  

-  [ ] Test covers all the areas mentioned above
-  [ ] Test runs properly on github actions on android and iOS/locally on android and iOS

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
@rbontrager do you need anything else on this ticket before merging?
