### ISSUE TITLE
UI Automation: Veteran Status Expansion

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7277]
## Description 
As part of this story we want to make a new test that covers the following for veteran status:

- Add testing to check various military branches

## Acceptance Criteria
  

-  [ ] Test covers all the areas mentioned above
-  [ ] Test runs properly on github actions on android and iOS/locally on android and iOS

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by bischoffa** [comment]
Will need to account for future changes from the Veteran Status contract team

**Comment by bischoffa** [comment]
Depending on the timing of this, it may be worth considering working with the VS contract team to do the work un Matt Reilly

**Comment by bischoffa** [comment]
Talked with Rachael during 1:1 today - ticket part of Q1 Qart Priority
