### ISSUE TITLE
CU - Replace waygateNativeAlert function with new combo

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#7278]
## Proposed Change

Availability Framework introduces waygateNativeAlert and Chris A suggested maybe we should execute the following:

> I wonder if this repeated pattern could be replaced with a new function like:
> 
> navigateWithWaygateCheck('DisabilityRatings')
> 
> This new function would just be a wrapper around navigateTo but with the waygate check included.
> 
> Then we could just replace navigateTo('screen') with navigateWithWaygateCheck('screen').
> 
> If the name is too long, other options could be things like:
> 
> goTo
> goToScreen
> navigateToScreen
> navigateWithWaygate
> 

In addition to this we should replace all iterations of navigation.navigate with the new function.

## Why Should We Prioritize?

Reduce lines of code, simplify navigation and rope in waygate checks automatically.

## Coding Time Estimation

5
	
## Testing Considerations

Will need to retest all of usecase1 in availability framework.
Do initial AF testing for the ~9 screens where it's now enabled.

## Checklist
[ ] Add the front-end label tag

[ ] Attach to the Frontend epic for engineering initiatives

**Comment by Sparowhawk** [comment]
ClaimPhase.tsx has
navigateTo('FileRequest', { claimID })() (line 162)
and looks to have a corresponding unit test checking that in lines 153-158 of the tests file
Although does look like it has an extra special mocking for just that (lines 32-36 of the tests file)
Isn't that the scenario you're describing? Seems annoying for sure, but functional...?

The above is how to get navigateTo('ClaimPhase')() to work with unit tests

**Comment by TKDickson** [comment]
Rachael has a working version of the AF detox script locally that she's going to run for the bulk of UC1 regression testing.

My test plan will do a spotcheck UC1 regression on:
- [ ] Veteran Status
- [ ] Messaging
- [ ] 

And I'll also do initial AF implementation (UC1, UC2, and UC3) on the new screens:
- [ ]   | 'WG_Claims' when user HAS decision letters access
- [ ]   | 'WG_Claims' when user does NOT have decision letters access
- [ ]   | 'WG_LoaGate'
- [ ]   | 'WG_GenericLetter'
- [ ]   | 'WG_Webview'
- [ ]   | 'WG_Sandbox'
- [ ]   | 'WG_HapticsDemoScreen'
- [ ]   | 'WG_InAppRecruitment'

**Comment by TKDickson** [comment]
Found #7700 while testing

**Comment by TKDickson** [comment]
Finished with my testing, found the one issue above.

Yesterday's update from @rbontrager :

> Going to let the iOS test finish locally (had to rerun some of them because my test timeout was too short) and will look at the results tomorrow.  Then I'll do android as well.
> My short AF test where I just test the various screen types (childTemplate, featureLandingTemplate, LargePanel, etc...) ran and passed fine but because Chika touched everything I'm also going through the whole list regardless of screen type.

**Comment by TKDickson** [comment]
Actually, @dumathane had changes on a different branch he wanted to move to this one to avoid a merge conflict in develop. So I'll need to retest InAppRecruitment waygates with a new build when he's merged his stuff.

**Comment by TKDickson** [comment]
UC1 with the changes from Binny, for in-app recruitment, still works.

Approved on my end to merge to develop, still awaiting a PR signoff from an Eng, post-Binny-change

**Comment by TKDickson** [comment]
Spotchecked that UC1 works on military info screen on an android device in develop. Closing ticket as complete.
