### ISSUE TITLE
BUG - sev-3 - All - Availability Framework: Gender Identity screen will also briefly display the "what to know before sharing" AF alert

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7279]
## What happened?

When there's a waygate alert for the "what to know before sharing your gender identity" screen, [when you tap on that link, the WTKBSYGI AF alert will display on the Gender Identity screen](https://drive.google.com/file/d/1sUI4C2e54J1EZdI5byRZAQihYWUbABYR/view?usp=sharing), as well as on the large panel that appears, and will disappear when you hide the large panel.

In other workflows where a large panel appears over another screen (ex: what if my military service info is incorrect), the screen below doesn't seem to be displaying/inheriting the panel AF alert in the same way. Not sure what's different with Gender Identity.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by dumathane** [comment]
Not wanting to lose research, here's some notes:

This appears to be something relevant to stack navigation and how we are checking for the navigationState route names. 

  console.log('-0:' + useNavigationState((state) => state.routes[state.routes.length - 0]?.name))
  console.log('-1:' + useNavigationState((state) => state.routes[state.routes.length - 1]?.name))
  console.log('-2:' + useNavigationState((state) => state.routes[state.routes.length - 2]?.name))
  console.log('-3:' + useNavigationState((state) => state.routes[state.routes.length - 3]?.name))
  
  The following code in waygateWrapper reveals this when we go to gender identity screen:
  
[0]  LOG  -0:undefined
[0]  LOG  -1:GenderIdentity
[0]  LOG  -2:Tabs
[0]  LOG  -3:undefined

Then this when we click the WhatToKnow:

[0]  LOG  -0:undefined
[0]  LOG  -1:WhatToKnow
[0]  LOG  -2:GenderIdentity
[0]  LOG  -3:Tabs
[0]  LOG  -0:undefined
[0]  LOG  -1:WhatToKnow
[0]  LOG  -2:GenderIdentity
[0]  LOG  -3:Tabs

This basically appears to be rendering both screens, one in fore and one behind but not differentiating for the discrepency.

**Comment by TKDickson** [comment]
Confirmed fixed by PR 7454, ready to merge with the rest of AF.

**Comment by TKDickson** [comment]
Confirmed fix still present in develop, closing.
