### ISSUE TITLE
Create github workflow that on 2 approvals(1 Eng and 1 QA) that it automatically moves the ticket to ready to merge

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7289]
Research is the comments in this ticket

https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4657

Workflow also needs to reset if approvals are removed or new code is pushed

**Comment by timwright12** [comment]
Related issue: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6261

**Comment by timwright12** [comment]
@Sparowhawk this might need a larger estimate, it's huge pain to test since you need 4 people (PR owner, 2 engineers, 1 QA) for each time you make a change and want to test the triggers

**Comment by timwright12** [comment]
@Sparowhawk was this closed as a dupe?
