### ISSUE TITLE
Create Github action that when there are approvals, dismissals it applies the correct label and when pr is created or marked as ready for review

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7291]
The state of the submitted review. Can be one of: commented, changes_requested, approved or dismissed.

See changes requested workflow and create a new workflow for approvals

When 1 approval from an Engineer apply the FE-With QA label and remove the FE-Needs Review label
When 2 approvals from an Engineer and QA apply the FE-Ready to Merge label and removes the FE-With QA label 

create a workflow on review dismissed to drop all FE-With QA and FE-Changes Requested and applies FE-Needs Review
Research in this ticket

create a workflow that when pr created and not a draft it applies FE-Needs Review and one that when draft is marked as ready applies FE-Needs Review

https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4657

**Comment by timwright12** [comment]
@Sparowhawk what's up with this issue?

cc @IsraelleHub @bischoffa

**Comment by TKDickson** [comment]
I'm not sure who's supposed to be working this ticket (@bischoffa FYI on that part)

@Sparowhawk wanted to drop a line that it's been very cool to see the labels on PRs updating automagically

**Comment by bischoffa** [comment]
Added health label given @Sparowhawk is assigned so it should now appear when Health team reviews their backlog/work.
