### ISSUE TITLE
BUG - sev-3 - All - Availability Framework - better guardrails against firebase setup that causes a crash?

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7297]
## What happened?

I crashed the app (iOS) or threw errors (Android) when trying to access screens that had no type specified in the availablilty framework setup in firebase:

No type:
```
{
  "enabled": false,
  "errorMsgTitle": "Contact VA FB Title",
  "errorMsgBody": "Contact VA FB Error body. Sorry this isn't working, you can always use the website in the meantime.",
}
```

_Interestingly enough, it will also crash the remote config screen (because, I assume, it can't figure out how to display the no type setup?). That's much less important though._

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
@dumathane this is broken again, in the develop branch with AF in it. Moving back to in-progress for now.

**Comment by dumathane** [comment]
We confirmed the broken part was a trailing comma after the last string was defined. This will break the JSON.parse command, and we should avoid including that in any scenarios we write in the future.

**Comment by TKDickson** [comment]
Confirmed that without the trailing comma in FB setup, we still don't crash in develop. 

Added examples of correct setup to copy-paste to the notes document to hopefully help with this for future us, as well as a note that it can be fragile so needs to be checked right away.

**Comment by TKDickson** [comment]
Closing
