### ISSUE TITLE
Create GET dependants endpoint

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7305]
Create endpoint to GET a user's dependents based on `app/services/bgs/dependent_service.rb#get_dependents`

AC:
- [ ] Check to ensure that upstream resource will not change in the near future and is expected to be stable
- [ ] Create dependants controller
- [ ] Create GET endpoint
- [ ] Add request spec
- [ ] update docs
- [ ] test in staging

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7305?planning-poker) with Zenhub @aherzberg @Tonksthebear
