### ISSUE TITLE
Create POST dependants endpoint 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7306]
Create endpoint that will allow a user to file a dependant request based on `app/services/bgs/dependent_service.rb#submit_686c_form` 

AC:
- [ ] Check to ensure that upstream resource will not change in the near future and is expected to be stable
- [ ] Create POST endpoint 
- [ ] Add request specs 
- [ ] Update docs
- [ ] Test in staging (if possible)

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7306?planning-poker) with Zenhub @aherzberg @Tonksthebear

**Comment by jperk51** [comment]
Yup, we didn't get a chance to work on it at all this spint.

**Comment by jperk51** [comment]
Removed due to post planning adds around "Code Yellow" and swapped for something smaller that could be completed.

**Comment by aherzberg** [comment]
non disability benefits teams made some major changes to the service in master so putting this back in progress to redo the service changes and specs
