### ISSUE TITLE
Create GET Awards endpoint

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7307]
API should return a user's awards summary based on `app/services/bgs/awards_service.rb#get_awards`. If get_awards doesn't also include pension awards info then also integrate with `lib/bid/awards/service.rb#get_awards_pension` and combine all awards into one response. 

ACs:
- [ ] Check to ensure that upstream resource will not change in the near future and is expected to be stable
- [ ] Create awards controller 
- [ ] Create GET awards endpoint
- [ ] add request specs
- [ ] update docs
- [ ] test in staging

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7307?planning-poker) with Zenhub @aherzberg @Tonksthebear
