### ISSUE TITLE
Create GET dependants request decisions 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7308]
Return status of user's dependant requests based on `app/services/bgs/dependency_verification_service.rb#read_diaries`

ACs:
- [ ] Check to ensure that upstream resource will not change in the near future and is expected to be stable
- [ ] Create GET dependants request decisions endpoint 
- [ ] Update docs
- [ ] Create specs
- [ ] Test in staging

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7308?planning-poker) with Zenhub @aherzberg @Tonksthebear
