### ISSUE TITLE
Component App Propagation - Button - Flagship Benefits

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#7309]
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the VAButton component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

### VAButton Instances
- Letters: 6
- Claims/Appeals: 21

## Developer Notes
- Component does NOT support icons on buttons, they should be removed.
- `a11yLabel` will no longer be integrated with `testIdProps`
- `ButtonTypeConstants` has been renamed to `ButtonVariants` and can also be imported from the library- Button variant names are the same but without the `button` prefix. (e.g. `Destructive` instead of the previous `buttonDestructive`
- The following props have been removed as they were not being used or being deprecated:
  - accessibilityState
  - disabled
  - disabledText
  - hideBorder
  - iconProps
  - minHeight

### Important links
- [Storybook documentation](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/button--secondary)
- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] The Flagship Mobile app team has been alerted to the existence of the new component
- [ ] VAButton has been replaced with new Button component is implemented in the Benefits screens of the app
- [ ] The Mobile apps have been released to their respective app stores with the component installed
- [ ] Flagship devs relay any DS feedback to the DS team

**Comment by rbontrager** [comment]
QA Estimate: 3
Verify that all the buttons changed look as expected
Verify that voiceOver/talkBack hasn't changed
Verify that detox tests still pass

**Comment by rbontrager** [comment]
Verified that voiceOver/talkBack hasn't changed and that the buttons changed look as expected.  Testrail run is here: [run](https://dsvavsp.testrail.io/index.php?/runs/view/5101&group_by=cases:section_id&group_order=asc). Verified that the detox tests still pass.  Approved by QA.
