### ISSUE TITLE
BUG - SEV 3 - All - Letters: Making user take extra step to get not authorized message

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7310]
## What happened?

When checking for what we show a user when they're not authorized for VA letters and documents, I noticed we don't show the user the "We couldn't find information about your VA letters" until after they've verified their address. We're forcing the user to do an unnecessary step (verifying their address) before we even tell them they're not even going to see any letters here.

## Specs:

- Device: iPhone SE
- OS: iOS
- User Account: Karsyn
- Accessibility State: none

## Steps to Reproduce

- Sign in to mobile app using Karsyn's credentials
- Tap Benefits in bottom navigation
- Tap VA letters and documents
- Tap blue Review letters button on the Letters screen
- You get this:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjdoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5953679140a049cd98e1900b04f59b9dc22a4b08/unnamed.png)

## Desired behavior

We should not make the user take the unnecessary step of verifying their mailing address if they aren't even authorized to access this feature. 

Note: This may be an issue of when we're actually making the call to determine eligibility and a problem of the fact that we have the verify-address-screen first before the list of letters.

## Bug Severity
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by mistymg** [comment]
@bischoffa New bug for the backlog!

**Comment by rbontrager** [comment]
Verified that if the user is not authorized to see letters they see the 'we couldn't find information about your VA letters' immediately after tapping into VA letters and docs.  Approved by QA.
