### ISSUE TITLE
Component App Propagation - Button - Flagship Health

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#7311]
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the VAButton component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

### VAButton Instances
- Appointments: 9
- RX: 13
- Secure Messaging: 20

## Developer Notes

- Component does NOT support icons on buttons, they should be removed.
- `a11yLabel` will no longer be integrated with `testIdProps`
- `ButtonTypeConstants` has been renamed to `ButtonVariants` and can also be imported from the library
- Button variant names are the same but without the `button` prefix. (e.g. `Destructive` instead of the previous `buttonDestructive`
- The following props have been removed as they were not being used or being deprecated:
  - accessibilityState
  - disabled
  - disabledText
  - hideBorder
  - iconProps
  - minHeight

### Important links
- [Storybook documentation](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/button--secondary)
- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] The Flagship Mobile app team has been alerted to the existence of the new component
- [ ] VAButton has been replaced with new Button component is implemented in the Health category of the app
    - [ ] This includes StartNewMessageButton and ReplyMessageButton. These are currently separate components that contain VAButtons with icons. Since we are deprecating icons, they no longer need to be separate components and can probably be replaced entirely with Buttons
    - [ ] **Note:** The appointment details screen currently uses a disabled VAButton for VA Video appointments when the appointment isn't ready to join. Because we are moving away from disabled buttons, this button cannot be replaced by a Button without a UX review. Replacement of this button will be handled in a separate ticket - Talking with Lauren we decided to open a panel if they can't join yet that says - "Can't join video appointment until x and x time"
- [ ] The Mobile apps have been released to their respective app stores with the component installed
- [ ] Flagship devs relay any DS feedback to the DS team
- [ ] Remove Start a New Message, Footer Button, and ReplyMessage Button Components from Flagship
- [ ] Check with Design if we are safe to remove the icons related to the above buttons

**Comment by Sparowhawk** [comment]
This ticket does require us to also delete Reply Message button and Start New Message button and transition these two components to the VAButton usage in their respective places since images are no longer on buttons. It also allows us to delete those assets wherever they are

**Comment by rbontrager** [comment]
QA Estimate: 3
Verify that all the buttons changed look as expected
Verify that voiceOver/talkBack hasn't changed
Verify that detox tests still pass

**Comment by Sparowhawk** [comment]
Talking with Lauren we decided to open a panel if they can't join yet that says - "Can't join video appointment until x and x time"

**Comment by rbontrager** [comment]
All button changes work and look as expected.  All relevant detox tests still pass locally.  Passing testrail run can be found [here](https://dsvavsp.testrail.io/index.php?/runs/view/5113&group_by=cases:section_id&group_order=asc). Approved by QA.
