### ISSUE TITLE
Appts - Implement - Adding Other Details [Booking note] to In Person, Phone and Video

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7316]
**Description:** 
As VA, I want to add Other Details field to Appointments so that Veterans can see booking notes in order to be more transparent and personable with the Veteran

**Notes:** 
- Identified by Dylan on 11/15 that FE does not have access to this
- This ticket can only be worked if / when BE can integrate it and make available to front-end - separate ticket 
- Design / UX already determine the content and design for it as of Nov 2023

**ACs:** 

- [ ] Add Text: Other details: [Booking notes] to Phone, Video and In Person Appointments (past, cancelled, upcoming) 
- [ ] When [Booking notes] does not have a value then put Text: Other Details: Not noted  

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5a3e80f55b9a57ba62718fec0a88d0b9ba95fef/image.png)

**Comment by Sparowhawk** [comment]
this is included in our appt rewrite and is the "comment" field in the api
