### ISSUE TITLE
Appts - Booking Field - BE access to field for FE to later access 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7317]
**Description:** 
As VA, I want BE to integrate to get Other Details field for Appointments so that FE can pull this into Appointments design. 

**Notes:** 
- Identified by Dylan on 11/15 that FE does not have access to this
- This ticket can only be worked if / when BE can integrate it and make available to front-end - separate ticket 
- Design / UX already determine the content and design for it as of Nov 2023
- [Slack chat](https://adhoc.slack.com/archives/C0206QFMXFU/p1700148297154639) on this topic - seems like its not visible to BE; they see a comment field but not sure its the same 

**ACs:** 

- [ ] BE integration / pulls in [Booking note]

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5a3e80f55b9a57ba62718fec0a88d0b9ba95fef/image.png)

**Comment by Sparowhawk** [comment]
we found that booking note was actually comment in the api so this ticket isn't needed and closing accordingly
