### ISSUE TITLE
SPIKE - Design tokens strategy

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#7320]
Narin, Tim and Jessica work together on a strategy for design tokens.

**Open questions**
[See Google Doc](https://docs.google.com/document/d/1IxQ63s0EEjR_oKG_9Jyqk9hqy9isLazYsi2SpHSJb8Y/edit#heading=h.66qzle3qg4wa)

**AC**
- [ ] document our strategy
- [ ] create any additional tickets that are needed

**Comment by kellylein** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7320?planning-poker) with Zenhub @narin @TimRoe @timwright12 @jessicawoodin

**Comment by narin** [comment]
Had an initial discussion with Jessica in our 1:1 last Thursday. Created a spike ticket #7425 as part of the action items. Having another discussion to address some unanswered questions on Wednesday.

**Comment by narin** [comment]
Discussed all items in [the Google Doc](https://docs.google.com/document/d/1IxQ63s0EEjR_oKG_9Jyqk9hqy9isLazYsi2SpHSJb8Y/edit#heading=h.66qzle3qg4wa) and created any follow-up tickets necessary.  @jessicawoodin to format the document a bit to present our thoughts to Ryan in our next touchpoint. Closing this ticket out.
