### ISSUE TITLE
Appts - Cancelled Logic - Displaying Cancelled Button with Y / N Indicator

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7326]
**Description:** 
As Mobile, I want to use the align Appt Cancelled Button logic with web, so its consistent across channels. 

**Notes:** 
- Currently blocked until I get confirmation from Appt team on if this needs to be implemented
- Current Mobile logic if Mobile gets Cancelld indicator then FE displays Cancelled Button for upcoming appointments in which Veterans can cancel the appointment
- In discussion with Ad Hoc Appts team on 11/16 Web team uses the Y / N field that accompanies the Cancelld indicator and are changing their Y / N logic in which N will be used in place of Y in some instances
- 11/17 Mobile [Slack discussion ](https://adhoc.slack.com/archives/C0206QFMXFU/p1700231679816019)- Mobile does not use Y / N field but instead uses Cancelld only as Cancelld indicator was 1:1 when comparing to N 

**ACs:** 

- [ ] When Cancelld indicator is N then do NOT display Cancel Button in upcoming appointments
- [ ] When Cancelld indicator is Y then SHOW Cancel button in upcoming appointments

**Comment by Sparowhawk** [comment]
not sure if this ticket is still needed with our appts rework

**Comment by ala-yna** [comment]
Closing this out - all appointments work not completed earlier this year would have to be reevaluated.
