### ISSUE TITLE
Appt - Inclusion of Booking Notes

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7329]
## Description 
As a [type of user/persona], I want to [goal/objective], so that [benefit/desired result/some reason].

As part of this story we want to:   

- 

## Acceptance Criteria
  

-  [ ] Add Other notes: [ Booking notes] field to all phone appointment types
-  [ ] Add Other notes: [ Booking notes] field to all in person appointment types
-  [ ] When Other notes: [ Booking noes] field is empty put Booking notes: Not noted

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0RoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd4011e87d607eab92cfdc3b2fb5e08a53e97c3f/image.png)

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by ala-yna** [comment]
Duplicate ticket, closing for now.
