### ISSUE TITLE
CU - Combine Loading and Error components into main screen logic for Health & Payments

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#7360]
## Proposed Change

For Benefits, Home, and Profile, for Availability Framework coding we combined down to using only a single screen template per screen and not reusing them for loading or error state checks. This wasn't done for Health and Payments but should be.

## Why Should We Prioritize?

Consistency, faster screen loading, less duplicative code.

## Coding Time Estimation

5
	
## Testing Considerations

Will need to test all loading and error states in this two app paths.

## Checklist
[ ] Add the front-end label tag

[ ] Attach to the Frontend epic for engineering initiatives

**Comment by alexandec** [comment]
Note for QA, affected components are:

- Appointments screens
- Prescriptions screens
- Secure Messaging screens (compose, save, draft, send, move, list, etc)
- Vaccine screens
- EditPhoneNumber screen
- Direct Deposit screens
- Payment History screens
- AskForClaimDecision screen

Functionality should be unchanged, especially loading and error states.

**Comment by rbontrager** [comment]
Verified the loading screens and error cases for the following screens:
- Appointments
- Prescriptions
- Secure Messaging
- Vaccine
- Contact Information
- Direct Deposit
- Payments
- Claims

Test cases can be found here: [8460: Loading and Error component test](https://dsvavsp.testrail.io/index.php?/runs/view/5465&group_by=cases:section_id&group_order=asc). Approved by QA.
