### ISSUE TITLE
CU - Show error when appointment from push notification can't be found

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7363]
## Proposed Change

When an appointment is opened via a push notification and the screen isn't able to find the correlating appointment based off the `vetextId` an invalid date and time message is shown:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejMzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--753caf9bdd22976acda37ecae417ad3adc86f756/Screenshot%202023-11-21%20at%209.37.19%20AM.png)

Instead of showing the invalid date and time message, we should show an error component instead to provide a better user experience.

## Why Should We Prioritize?

To provide a better and less confusing experience to veterans viewing appointment information via push notifications.

## Coding Time Estimation

1
	
## Testing Considerations

Ensure this works with a staging user's appointment. This can be mocked locally.

## Checklist
- [x] Add the front-end label tag

- [x] Attach to the Frontend epic for engineering initiatives

**Comment by theodur** [comment]
@DJUltraTom There probably isn't a good way to test this on staging without having the VEText team send a notification via the API, but we've tested this locally, so I don't think there's any testing needed from QA for this

**Comment by DJUltraTom** [comment]
based on the above comment QA approves of this change.

**Comment by theodur** [comment]
Thanks @DJUltraTom, just merged the PR. Are we good to close this one?

**Comment by DJUltraTom** [comment]
since theres no QA validation we can really perform. I'd suggest testing it locally(if possible) with tomorrows develop build and then closing if everything is looking good.
If thats not possible, we can close it now and think good thoughts ;)

**Comment by DJUltraTom** [comment]
closing as deployed
