### ISSUE TITLE
Update splash screen to remove white button

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#7365]
The design system will not include a white variation of the button. Based on a discussion with Ryan, the splash screen will need to be updated, so that the default blue or base gray button will work on the background in light and dark mode.

**Links**
[Button in Storybook](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/button--base)
[Button in Figma](https://www.figma.com/file/QVLPB3eOunmKrgQOuOt0SU/%F0%9F%93%90-DesignLibrary2.0---VAMobile?type=design&node-id=11477-14278&mode=design&t=aUxIARIaoZ55keT7-4)

**Screenshots**
[Button in Figma](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmI0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c05cc36be3cf1ad9baa655556bc793426444b47/image.png)

[Splash screen](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlQ0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aaf2d8d94dda4295896e6a0f83ec1e50eae5e182/IMG_DE351B8231A4-1.jpeg)

**Comment by brea11y** [comment]
I have updated the splash screen buttons to reflect the changes made during the design tokens / system work and also the changes recommended during the button / link audit. I have updated the primary button to the new dark mode gray primary button style in both light and dark modes and also updated the "Find a VA location" link to be an official button (it is currently coded as a button but styled as a link that is outside of the design system). That secondary button is now using the dark mode gray secondary button style. 

These proposed updates can be seen [in Figma](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=938-170&mode=design&t=OGONTd44icA3BGDR-4).
