### ISSUE TITLE
Update primary colors to align with VADS/USWDS

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#7371]
**Note:** This ticket was updated to remove the AC to update the colors in the mobile app.  Separated that portion to a separate ticket that should be handled by the app team #7573.

On December 4, [VADS is updating their primary blue colors to align with USWDS](https://dsva.slack.com/archives/C03R5SBELQM/p1699983323484419).

AC:
- [ ] Add any missing colors
- [ ] update existing colors 

This Story is to update the Design System colors, not to update the flagship app colors.

**The mobile app team needs to update the HEX numbers in the following locations:**
- [ ] [this file in va-mobile-library](https://github.com/department-of-veterans-affairs/va-mobile-library/blob/main/packages/tokens/src/tokens/color/base.json) (front-end)
- [ ] [the design library files in Figma](https://www.figma.com/files/827597988283174959/project/60961499) (UX)

The color changes are outlined below.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmY5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--973f3b8a4dd1e77b16de5a2f05c7f443ed2bbe6f/image.png)

**Comment by narin** [comment]
@jessicawoodin According to [the PR that the VADS team merged](https://github.com/department-of-veterans-affairs/component-library/pull/974/files#diff-4c8e552054bce5d252f757cbd4130433736912bf2c1b93cfcdc0c94423de92b6) to update their primary colors, they replaced `color-primary-darker` and `color-primary-darkest` with `color-primary-dark` and `color-primary-darker`, getting rid of `color-primary-darkest`.

I did a search through the app, and it appears we're using all 3 variants throughout. I see that the table you attached above does have a mapping for all 3, but just wanted to confirm if an audit of the app was done for each spot they were used?

**Comment by narin** [comment]
Also just noticing that the story description mentions this is for updating the design system colors only, however there's a checkbox'ed link to where the mobile app colors need to be updated.

**Comment by jessicawoodin** [comment]
@narin To answer your first question, no, I didn't do an audit of the app. VADS created the table and I just added it to this ticket -- assuming we'd just be able to update the HEX numbers. I'm a little confused why they replaced certain colors, but those changes aren't showing in the table documentation. Is there someone you could ask about the PR?

Also, I'm not sure about that comment to not update the flagship app colors. I didn't write that part of the ticket. In my opinion, it'd be kinda strange (and inefficient) to only update the colors in the design system file if the majority of the colors are in the flagship file. If it's not us, which team would be responsible for updating the colors?

**Comment by narin** [comment]
@jessicawoodin I can ask the creator of the PR about the removed color, but I think the attached table covers our needs for the app. Would you agree? Also, who provided the table? I don't see it in the PR or Issue attached in the [VADS is updating their primary blue colors to align with USWDS](https://dsva.slack.com/archives/C03R5SBELQM/p1699983323484419).

**Comment by narin** [comment]
Discussed this further with @jessicawoodin and we decided that due to the removal of primary-darkest, it would be better to move the AC to update the colors in the app to a separate ticket. There are also questions as to whether it is our team's responsibility to reconcile the removal of the color, as it is used throughout the app.

New ticket [here](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7573).
