### ISSUE TITLE
CU - change e2e daily QA builds to a singular workflow to have only one slack thread for both

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7373]
t would be nice if we could have a single thread for both iOS and Android tests, similar to how we do with on demand builds. That way, the results would be in one place. This would probably require a new workflow for running both test suites, because they'd need to reference the same Slack thread

**Comment by timwright12** [comment]
@Sparowhawk We want to keep the e2e workflows separated so they can pass or fail without interfering with the other and also maintain a level of modularity for reruns and independent runs. If you want to figure out how to have them share a slack thread, that's fine, but we want the code to be separated.
