### ISSUE TITLE
Home Screen Module Logic - Prescriptions

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7381]
**Background**
* This ticket covers the content and display logic for the Prescriptions module which displays on the home screen

**Acceptance Criteria**
* If the Veteran has Active Prescriptions, based on the backend work in the ticket in the comments, then display a module on the home screen with the following content:
    * Text that says “Prescriptions (x active)” 
        * In this example, x should be replaced with the number of active Prescriptions returned from the backend. For instance, if the Veteran has 2 active Prescriptions, the module will read “Prescriptions (x active)” 
    * If clicked, the module should deep link the user to the Prescriptions page
 * If the Veteran has 0 Prescriptions returned from the backend, then do NOT display a Prescriptions module
 * NOTE - error handling is not finalized and will be covered in a separate ticket (ex. health) not feature level (ex. just prescriptions) 
* NOTE - This ticket is strictly display logic. The UI will be covered in a separate ticket once designs are finalized

**Comment by ajsarkar28** [comment]
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7212

**Comment by TKDickson** [comment]
This is the super simple, happy path, ugly UI implementation -- QA estimate 1 point (karsyn without tracking; link to prescriptions).

I'm proposing splitting off the testing that requires prep from MHV into its own ticket, running that past @ajsarkar28 in slack. If the plan changes, will update estimate accordingly.

**Comment by TKDickson** [comment]
Testing
- [ ]  User with PrescriptionCount of 1 or more (mock it if needed) - rx module shows up on the homescreen, with the correct # displayed
- [ ]  User with PrescriptionCount of 0 - the rx module does not appear on the homescreen


For a user when the module appears on the screen:
- [ ]   when I tap on the Rx module, it navigates to the Rx list
- [ ]  when I tap '< Health' at this point, it navigates to Health category landing
- [ ]  or if I tap on the built-in back (Android back button, iOS swipe), it navigates to the Health category landing

**Comment by TKDickson** [comment]
Closed #7470 because we're changing the definition of the Rx count to just refillable meds (which will not need special prep). This ticket also has all cases pass, closing. Good to merge to XL.

**Comment by TKDickson** [comment]
Alrighty -- this merged to the XL branch ~2 weeks ago, but I was OOO so didn't get to test (until now) that Rx and Appts showed up nicely together on the home screen. They do (had to mock the data because no staging user actually has both), so officially closing this ticket.
