### ISSUE TITLE
Category Screen - Health

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7382]
**Background**
* This ticket covers the content for the new Health category screen. Specifically:
  * The personalized data at the top of the category screen
  * The modules for each Health feature
  
**Acceptance Criteria**
Personalized Data Section

- At the top of the Health category screen, there is section that displays Personalized Health data
  - If the Veteran is enrolled in VA healthcare, this section displays "You are enrolled in VA health care"
 
Health Category Modules
* The following modules display on the Health category screen:
  * Appointments
  * Messages
  * Prescriptions
  * VA vaccine records
  * COVID-19 updates
  * note that all of these modules already exist. The display text will vary for the first three and is described next
 
* For the Secure Messages module, if the veteran has unread Secure Messages returned from the backend, then the module should read “Secure messages (x unread)”
  * In this example, x should be replaced with the number of unread Secure Messages returned from the backend. For instance, if the Veteran has 2 unread Secure Messages, the module will read “Appointments (2 upcoming)” 
  * If the veteran has no unread Secure messages, the module should read "Secure messages (0 unread)"
* For the Appointments module, if the veteran has upcoming appointments returned from the backend, then the module should read “Appointments (x upcoming)”
  * In this example, x should be replaced with the number of upcoming appointments returned from the backend. For instance, if the Veteran has 2 upcoming appointments, the module will read “Appointments (2 upcoming)” 
  * If the Veteran has no upcoming appointments, the module should read "Appointments (0 upcoming)"
* For the Prescriptions module, if the veteran has active Prescriptions returned from the backend, then the module should read “Prescriptions (x active)”
  * In this example, x should be replaced with the number of active prescriptions returned from the backend. For instance, if the Veteran has 2 active prescriptions, the module will read “Prescriptions (2 active)” 
  * If the Veteran has no active prescriptions, the module should read "Prescriptions (0 active)"

When the modules with variable display content (Secure Messages, Appointments, and Prescriptions), are loading, display a bar over the variable content until the variable content is retrieved.

**Error logic??**

**Comment by TKDickson** [comment]
[health screen UI cases link](https://dsvavsp.testrail.io/index.php?/cases/view/59275&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=13520)
