### ISSUE TITLE
RX - Changes List and Sort - Product - Update Call Center Doc

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7390]
**Description:**
As the VA Call Center, I want my call center guide to be updated in order to have the most updated version of the document when helping Veterans that call in. 

**Ask:**

- Updated the call center docs to accurately reflect images and content for the RX changes 
- Refer to Github Call Center [Guide Doc ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/releases/Call%20Center%20Docs) pages 20 - 35
- Share with VA Call Center through their process 
- 

**ACs:**
- Update call center guide images to incorporate new RX home page, sort and filter options 
- Update call center guide content to reflect the feature changes 
- Update revision history
- Update Table of Contents to ensure content and page numbers are correct

**Comment by bischoffa** [comment]
Product specific work - sized as a 3 points because of the number of pages that need to be updated and screenshots that will be needed. May need to coordinate with Engineering to get the screenshots you want.

**Comment by bischoffa** [comment]
Alayna to collaborate with Adam on these changes

**Comment by wavelaurenrussell** [comment]
I created a new guide in the G drive folder and provided updates. Changes are reflected in version 7.4. Please advise on next steps to get to the Call Center, as its ready for review.

@ala-yna @bischoffa

**Comment by bischoffa** [comment]
Call center guide process and steps can be found [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/releases/Call%20Center%20Docs) .

**Comment by bischoffa** [comment]
Forgot to @ for the above post @ala-yna @kidlaurenpeace.

**Comment by wavelaurenrussell** [comment]
Submitted [Ticket #75756](https://github.com/department-of-veterans-affairs/va.gov-team/issues/75656) today for Contact Center review.
