### ISSUE TITLE
Personalized home screen: What's New Copy

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7396]
## Description 
Write content for launch of personalized home screen

## Acceptance Criteria

- [x] Content for app store What's New sections

~~- [ ] Content for in-app What's New alert box~~ (Decided as team on 4/16 stand up that we will not use this for new Home screen.)

## Approved Copy
 _**Use this copy for just the app store What's New section**_

We created a new personalized Home screen. It shows important activity happening with your VA health and benefits. We also made other improvements and fixed a few bugs.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
@ajsarkar28 I updated this ticket with ACs that we usually require. But given our 11th-min conversation after DSU, if this changes, please let me know.

**Comment by mistymg** [comment]
Per Ameet in Slack thread re: what we're trying to communicate to Veterans in release notes/what's the benefit of the new home screen, "...I'd start from the perspective that we redesigned the home screen to surface personalized content that helps Veterans manage their current interactions across VA. Other than that, I'm not sure there's other functionality worth calling out."

**Comment by mistymg** [comment]
Bumping this ticket to next sprint to prioritize something else.

**Comment by mistymg** [comment]
Brainstorming notes:

**Comment by mistymg** [comment]
I'll likely suggest we include the "We also made other improvements and fixed a few bugs." just to cover the other things we did for Personalization that weren't covered in talking about the Home screen.

**Comment by mistymg** [comment]
After sleeping on it, I'm recommending the following copy: _We created a new personalized Home screen. It shows important activity happening with your VA health and benefits. We also made other improvements and fixed a few bugs._

Will review with PM when he's back from PTO.

**Comment by mistymg** [comment]
Ameet approved today. Copy from the "Approved copy" section in ticket will need to be put in release ticket when we're ready to release.
