### ISSUE TITLE
BUG - sev-2 - All - vama_claim_count not capturing business logic as described in original ticket

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#7402]
## What happened?

The original ticket for the analytic event `vama_claim_count` #5940 stated the following logic for when the event should fire:
> 1) Opens Claims feature
> 2) Opens Claims History
> 3) Clicks on ""Closed"" or ""Active"" tabs on Claims History

The first criteria was determined to be infeasible, but the second and third were supposed to be implemented. However, upon review, only the third criteria was addressed by the analytic as implemented. 

## Steps to Reproduce

See the information in the above "what happened" section
## Desired behavior

Given that we have since implemented the event `vama_segcontrol_click` to address the second criteria originally mentioned, the event `vama_claim_count` should be modified to address just the second business logic criteria from the original ticket and can drop the third altogether. 

## Acceptance Criteria

- [ ] Modify `vama_claim_count` to **only** fire when a user navigates to the screen ClaimsHistory.
- [ ] Continue to capture the custom parameters `closed_claims` and `open_claims`
- [ ] Remove `claims_tab` parameter.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
  - this does not impact the user's experience at all
- Frequency: High 
  - Claims is our most used feature and this blocks a critical part of sizing Claims interactions in analytics.

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by alexandec** [comment]
Nothing to QA on this one since it's just an analytics change. We don't yet have a way for QA to check analytics events
