### ISSUE TITLE
BUG - Sev-2 - All - Availability Framework: Use case 1 not working for claims correctly

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7403]
## What happened?

Turn on use case 1 for claims, navigate to the claims screen and notice that it displays claims history under the popup

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Turn on use case 1 for claims for a user with claims history and letters (+54 as an example)
2. Navigate to Benefits > Claims.  Notice the popup appears but that claims history is shown underneath it

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVUQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--226469350bf28ee0394e250cf2a6a2e740335199/trim.52250762-F9AC-4466-B9FD-6B133ABB8331.MOV)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by dumathane** [comment]
After discussing with Therese (and I will confirm my logic with Theo when he's in) the solution for this is actually to remove WG_Claims as an option from the app. WG_Claims should only exist when the decisions letters waygate is enabled, and simply has two nav buttons and no data. The solution that fixes both waygate/authorization questions is to just use the claimsHistory or ClaimLettersScreen waygates instead. I've merged this to the main feature/Binny-AvailabilityFramework branch (oops) and it is available for testing.

**Comment by TKDickson** [comment]
Need to test:

- [ ]  Someone who has both DL and claims access; WG_ClaimsHistory use case 1 still works
- [ ]  Someone who has both DL and claims access; WG_DecisionLetters use case 1 still works
- [ ]  Someone who does NOT have DL access but DOES have claims; WG_ClaimsHistory use case 1 still works

**Comment by TKDickson** [comment]
Confirmed fix still workign in develop, closing.
