### ISSUE TITLE
BUG - sev-3 - All - Availability Framework: sometimes we fire an API call even with use case 1 and 2

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7404]
## What happened?

I’ve noticed that for use case 1 (where the veteran is not allowed to navigate to the activity but instead gets a popup), sometimes the underlying API call fires (ex: Android + Prescription History) and sometimes it doesn’t (ex: iOS + Prescription History; both platforms for Secure Messaging, Appointments).

List of instances from further investigation [in this comment, below.](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7404#issuecomment-1843742908)

Another example of this -- setting the AF waygate for RefillRequestSummary doesn't actually prevent the refill request from going through. (Setting the waygate for RefillRequestModal DOES, for both the multiple and single refill workflows, so there is a way to block that off -- but refill specifically is not the point of this ticket/issue)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

I imagine that we're going to attempt to use analytics & API traffic to figure out if AF is working, so 'leaks' like that one will throw off our perception of AF effectiveness.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@dumathane this likely has to do with our usage of calling api's in the useEffect hook on those screens. looks like we will need to add the waygate logic to determine if the api should be called or not

**Comment by TKDickson** [comment]
@theodur hypothesized & was correct that this will also impact some screens with use case 2. Updated the title accordingly. 

FE has requested that I do a deep dive to find the screens impacted by this, before they jump into fixing. Assigning to me.

**Comment by TKDickson** [comment]
Okie dokie. Here's my list for investigating UC2 and UC1 to figure out which of these still make API calls.

Screens to test:
 | 'WG_Home'
  | 'WG_Profile'
  | 'WG_PersonalInformation'
  | 'WG_PreferredName'
  | 'WG_GenderIdentity'
  | 'WG_ContactInformation'
  | 'WG_EditAddress'
  | 'WG_EditPhoneNumber'
  | 'WG_EditEmail'
  | 'WG_MilitaryInformation'
  | 'WG_NotificationsSettings'
  | 'WG_Health'
  | 'WG_Appointments'
  | 'WG_FolderMessages'
  | 'WG_PastAppointmentDetails'
  | 'WG_PrescriptionDetails'
  | 'WG_PrescriptionHistory'
  | 'WG_SecureMessaging'
  | 'WG_UpcomingAppointmentDetails'
  | 'WG_VaccineDetails'
  | 'WG_VaccineList'
  | 'WG_ViewMessage'
  | 'WG_StartNewMessage'
  | 'WG_ReplyMessage'
  | 'WG_EditDraft'
  | 'WG_RefillRequestSummary'
  | 'WG_RefillScreenModal'
  | 'WG_RefillTrackingModal'
  | 'WG_Payments'
  | 'WG_PaymentDetails'
  | 'WG_DirectDeposit'
  | 'WG_PaymentHistory'
  | 'WG_EditDirectDeposit'
  | 'WG_Benefits'
  | 'WG_DisabilityRatings'
  | 'WG_ClaimsHistory'
  | 'WG_LettersOverview'
  | 'WG_LettersList'
  | 'WG_BenefitSummaryServiceVerificationLetter'
  | 'WG_ClaimLettersScreen'
  | 'WG_ClaimDetailsScreen'
  | 'WG_AppealDetailsScreen'

Screens I didn't test because they don't support UC1/UC2:
  | 'WG_Login'

Screens I didn't test because they don't make API calls when _loading_ the screen:
  | 'WG_HowDoIUpdate'
  | 'WG_WhatToKnow'
  | 'WG_HowWillYou'
  | 'WG_IncorrectServiceInfo'
  | 'WG_Settings'
  | 'WG_ManageYourAccount'
 | 'WG_ContactVA'
  | 'WG_VeteransCrisisLine'
 | 'WG_VeteranStatus'
  | 'WG_RemoteConfig'
  | 'WG_Developer'
  | 'WG_WaygateEdit'
   | 'WG_PrepareForVideoVisit'
  | 'WG_Attachments'
  | 'WG_ReplyHelp'
  | 'WG_ConfirmContactInfo'
  | 'WG_PrescriptionHelp'
  | 'WG_StatusDefinition'
  | 'WG_SessionNotStarted'
  | 'WG_HowToUpdateDirectDeposit'
  | 'WG_PaymentIssue'
  | 'WG_PaymentMissing'
  | 'WG_ConsolidatedClaimsNote'
  | 'WG_WhatDoIDoIfDisagreement'
  | 'WG_FileRequestDetails'
  | 'WG_AskForClaimDecision'
 | 'WG_FileRequest'
  | 'WG_SelectFile'
  | 'WG_TakePhotos'
  | 'WG_UploadFile'
  | 'WG_UploadOrAddPhotos'

**Comment by theodur** [comment]
Re-estimated this to a 3 based on the findings from the investigation

**Comment by theodur** [comment]
I was able to fix all the screens from the list except for 2:
### `v0/user/contact-info` when navigating out of the Letters Overview screen:

This is caused by an unrelated bug I noticed. When a screen has `DenyContent` as the waygate type (UC2), and you're navigating away from the screen, the content of the screen will briefly start while navigating to the previous screen. It's similar to the bug from: https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7261. This is why the contact info API call isn't called when navigating to the Letters Overview screen, but navigating back starts loading the content, which enables the `useEffect` that triggers the API call. I made a [ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7522) for this, where a screen recording can be seen in the description.

### `v0/military-service-history` on the home screen

From what I noticed, this call seems to be made when first logging in before the app navigates to the home screen. This is actually happening on the SyncScreen instead, as the home screen doesn't make this, or any API calls. That call seems to be preloading the military information for both the Home and Profile screens, so we may want to keep that one, so that we're handling the scenario where the home screen has content blocked, but the profile screen still has its content available

**Comment by TKDickson** [comment]
@theodur makes sense, appreciate the heads up (and new ticket). I will do my testing based off of the list of screens fixed, which I'll document in the next comment

**Comment by TKDickson** [comment]
Confirmed that with a UC2 AF alert set up on the following screens, the listed API call does not happen when navigating to that screen:
- [ ] v0/payment-information/benefits on Direct Deposit
- [ ] v0/claim/[######] on claim details
- [ ] v0/appeal/[######] on appeal details
- [ ] v0/claims/decision-letters on claim decision letters
- [ ] v0/letters/beneficiary on BSSV letter
- [ ] v0/letters on letters list
- [ ] v0/user/authorized-services on claims history (this one is.... confusing to me, but I saw it multiple times)
- [ ] v0/disability-rating on Disability rating
- [ ] v0/push/prefs/null on Notification Preferences
- [ ] v0/user/contact-info on Contact Information
- [ ] v2/user and v0/user/gender_identity_edit and v0/user/demographics on Personal Information
- [ ] v0/messaging/health/recipients on Start New Message
- [ ] v0/messaging/health/recipients and v0/messaging/health/folders/0 and v0/messaging/health/messages/#### and v0/messaging/health/messages/####/thread?excludeProvidedMessage=true on Edit Draft
- [ ] v0/messaging/health/messages/#### and v0/messaging/health/messages/####/thread?excludeProvidedMessage=true on View Message
- [ ] v0/health/rx/prescriptions?........(the prescription history/list call) on Refill Screen Modal
- [ ] v0/health/rx/prescriptions/#####/tracking on Refill Tracking Modal
- [ ] v0/health/rx/prescriptions?........(the prescription history/list call) on Prescription History
- [ ] relevant folder call v0/messaging/health/folders/##/messages?page=1 on Folder Messages
- [ ] v0/messaging/health/folders/0 and v0/messaging/health/folders/0/messages?page=1 on Secure Messaging
- [ ] v0/appointments?startDate=......" x2 - both the upcoming and past appointments calls on Appointments
- [ ] v0/user/authorized-services on all of the category screens (timing matters for this -- make sure you enable the AF banner, log out, and log back in again to check)
- [ ] v0/health/locations/XXXXXX on Vaccine Details
- [ ] v1/health/immunizations?page..... (the vaccine list call) on Vaccine List

**Comment by TKDickson** [comment]
Found while testing:
[View message bug (no API call, but also no screen content)](https://drive.google.com/file/d/1kt5hb9teH1xzQsE_7APAkBEwsMvuvXAh/view?usp=sharing)

**Comment by theodur** [comment]
@TKDickson I just pushed a fix to the branch for the no screen content on the view message screen, so that should be good now. And yeah, the prescription history load is most likely due to the screen transition issue 🙁

**Comment by TKDickson** [comment]
Sounds good, thanks Theo! I think my recommended approach is just going to be to document, in the usual place, the API call exceptions for military history, contact info (with linked ticket) and I can add prescriptions to that as well. I'll throw a checkbox up in my test plan so I don't forget.

**Comment by TKDickson** [comment]
Shoot, we're also calling `v0/messaging/health/folders/0` on the Health category screen (I'm assuming for the unread messages count) but it only shows up the first time you switch to that tab, so that may be how I missed it in my initial investigation. That's the last one, done with initial testing. @theodur is that one fixable?

I'll go start up a build for the view message fix now.

**Comment by theodur** [comment]
Cool, sounds good! And yeah the call on the health screen is an easy fix. I'll push that change to the branch when I'm back at my computer

**Comment by TKDickson** [comment]
View message fix is working great! And the exceptions are documented. Health screen is the last one and then we can (gasp!) merge to develop. @StacyB2023 FYI.

**Comment by theodur** [comment]
@TKDickson The changes to the health screen are up in the branch now ✅

**Comment by TKDickson** [comment]
Fix is working! This is ready to merge to develop, so all of AF is ready to merge to develop

**Comment by TKDickson** [comment]
Confirmed fix working in develop via spotcheck (see #7545), closing
