### ISSUE TITLE
BUG - sev-3 - All - Availability Framework: claims file request 'are you sure' cancellation content and use case 2 don't play nicely together

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7406]
## What happened?

In either iOS or Android, with a use case 2 (DenyContent) availability framework alerts (either 'WG_UploadFile or 'WG_UploadOrAddPhotos') in claims file request, the "FYI we're getting rid of your content" confirmation that appears when tapping cancel doesn't make sense, because we are blocking the veteran from proceeding so there's no benefit to tapping "continue upload".

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9WQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--286994c1b8b9452ff1c2b7074fee1887e56b9572/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHNWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2954876bdfd393519adbb16ef6d4fd688c6d97cf/image.png)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Set up Use Case 2 for 'WG_UploadFile or 'WG_UploadOrAddPhotos' using [the instructions in testrail.](https://dsvavsp.testrail.io/index.php?/tests/view/1127701&group_by=cases:section_id&group_id=11848&group_order=asc)
Using +54 (or demo), go to Claims > Claims History > [claim with a file request] > Review file requests > [specific file request] and then try both the photo upload and file upload workflows, to hit each of the screens with the UC2 banner on it.

Once on the relevant screen (where you can see the AF banner), tap 'cancel' and get the confirmation in the screenshots in the problem description.

## Desired behavior

Not sure/could use UX weigh-in. Is it possible to *not* show that cancellation banner specifically when AF UC2 is in play? If yes, is that something we want to do or is it relatively fragile in FE code?

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
adding health team label

**Comment by rbontrager** [comment]
Verified that if AF use case 2 is enabled for WG_UploadFile or WG_UploadOrAddPhotos then hitting back in the upload file/upload photos screen will no longer display the cancel upload menu and just back out of the screen.  Approved by QA.
