### ISSUE TITLE
Configure pager duty escalation policy. 

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7413]
In [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7251), we attempted to configure pager duty to automatically send notifications or set the channel topic in slack when the person on call changes. That doesn't appear to be possible. It looks as though the schedules in pager duty aren't used that way. Instead, they're used as part of their escalation policies to ping the on call person when an issue arises. 

We should transfer our alerts from datadog to pager duty by configuring an escalation policy that's configured the same way as our datadog alerts and to use the schedule to ping the on call person.

Whoever does this ticket will probably need to be configured as a "manager" in pager duty.

**Comment by kpethtel** [comment]
Escalation policy works and sends notifications to anyone on the team who has their PD notifications configured. Created [this ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7572) for next pager duty integration steps. That ticket will hopefully get slack to use our pager duty schedule.

**Comment by timwright12** [comment]
testing comments
