### ISSUE TITLE
Update datadog alert monitors to use new service dashboard data instead

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7418]
[New dashboard](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?env=eks-prod&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&sort=error-rate%2Cdesc&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&view=spans&start=1701356709938&end=1701360309938&paused=false)
At the top of the dashboard there is a section for setting up monitors.

AC:
- [] If possible replace the existing monitor with one that uses the resource data  from the new dashboard instead of the http url tracking like it does now.

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7418?planning-poker) with Zenhub @aherzberg @Tonksthebear
