### ISSUE TITLE
Add most recent recurring payment to payment history meta

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7423]
As part of personalized home screens, we want to show users their most recent recurring payment. To enable that, the back end should add this value to the endpoint meta. 

Acceptance Criteria:
- add value from most recent payment with `'paymentType' => 'Compensation & Pension - Recurring'` to payment history meta.
- if there is no dollar amount, value should be nil
- update specs
- update docs
- test on staging

**Comment by kpethtel** [comment]
Moving to the icebox for now. According to @dumathane, "So, I talked to Holly, and basically that's a great placeholder and don't start working on it yet. they are still contemplating exactly what they'd want, they think it's this, but aren't 100% yet"

**Comment by timwright12** [comment]
Moved this to Blocked

**Comment by jperk51** [comment]
I think we are good to close this now that the new home screen has been live for a bit? @timwright12

**Comment by dumathane** [comment]
Fine to close.
