### ISSUE TITLE
[Spike] Integrate VADS design tokens into mobile-tokens

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#7425]
## Description
In our tokens package, we have been copying color values over from VADS instead of referencing their tokens directly. This is partially because they are missing some USWDS colors used in our components. Ideally, we could reference [VADS's JSON tokens](https://github.com/department-of-veterans-affairs/component-library/blob/bf563e097b4064cc250742bd3ae91eb43cab0011/packages/css-library/dist/tokens/json/variables.json) and [USWDS's tokens](https://github.com/uswds/uswds/tree/develop/packages/uswds-tokens/colors) directly instead of duplicating them, and maintaining our own copy.

This spike is meant to determine if we can pull in VADS's and USWDS's package and generate our tokens from their `.json` files so that we don't have to manually duplicate them.

## Acceptance Criteria
- [x] Determine if/how we can reference VADS's [variables.json](https://github.com/department-of-veterans-affairs/component-library/blob/bf563e097b4064cc250742bd3ae91eb43cab0011/packages/css-library/dist/tokens/json/variables.json) and [USWDS's color tokens](https://github.com/uswds/uswds/tree/develop/packages/uswds-tokens/colors) for use as primitive color tokens
- [x] Questions to answer:
  - [x] Once imported, do we need to "re-build" our own distribution file using style-dictionary? 
  - [x] If we plan to have different levels of tokens such as semantic and component tokens as described in [this document](https://docs.google.com/document/d/1IxQ63s0EEjR_oKG_9Jyqk9hqy9isLazYsi2SpHSJb8Y/edit#heading=h.q40uzmvguspg), how would we reference the imported tokens?
  - [x] Can the above be automated in GitHub Actions?
- [ ] If we determine the above is all technically feasible, implement the integration

**Comment by TimRoe** [comment]
A thought on:
> Determine if/how we can reference their [variables.json](https://github.com/department-of-veterans-affairs/component-library/blob/bf563e097b4064cc250742bd3ae91eb43cab0011/packages/css-library/dist/tokens/json/variables.json) for use as primitive tokens

If they aren't able to provide us with a method that works, we could always add a ticket against their repo to expose their values in a way we can use--I assume they'd be fine PRing and approving if we didn't break anything for them.

**Comment by narin** [comment]
Some updates since beginning this ticket:
- [x] Asked VADS team to update `css-library` package to include tokens in JSON format
- [x] Figured out how to include `css-library` as a dependency in our project, reference color tokens, and transform them into JS for our needs
- [x] Determined that VADS team is already fetching USWDS tokens as we planned to do, but are only filtering out colors that they need. Any colors missing need to be added to [this file](https://github.com/department-of-veterans-affairs/component-library/blob/2060dceff8261812c411f5b102212da9378bbfa1/packages/css-library/copy-uswds-color-tokens.js)
- [x] Answered the following questions in the AC
   - Once imported, do we need to "re-build" our own distribution file using style-dictionary? **Yes, we'll still want to transform the tokens into JS for our needs, as add any tokens that are unique to our projects (e.g. fonts)**
   - Can the above be automated in GitHub Actions? **Yes. I have a prototype working and we just need to make some modifications to our style dictionary config.**
   - If we plan to have different levels of tokens such as semantic and component tokens as described in , how would we reference the imported tokens? **Yes. See this basic example:**
 ```JSON
{
  "color": {
    "primitive": {
      "black": { "value": "#000000" },
      "white": { "value": "#FFFFFF" },
      "red": { "value": "#FF0000" }
    },
    "semantic": {
      "text": { "value": "{color.primitive.black.value}" },
      "background": { "value": "{color.primitive.white.value}" },
      "error": { "value": "{color.primitive.red.value}" }
    }
  },
  "component": {
    "button": {
      "textColor": { "value": "{color.semantic.text.value}" },
      "backgroundColor": { "value": "{color.semantic.background.value}" },
      "errorColor": { "value": "{color.semantic.error.value}" }
    }
  }
}
```

@jessicawoodin Could you please comment with the list of USWDS colors that we're missing or that we'll be needing in the foreseeable future? So far the ones I've identified are:
- BlueVivid30
- RedVivid40

Once we get the list, I can create a PR to request that the colors be added.

**Comment by jessicawoodin** [comment]
@narin - Here's a list of colors that we'll need added to VADS for our current and next few components. I included the USWDS token name and HEX #.

The following colors are found in **USWDS.json**, but not found in **color.json**:
- gray-20 - #ADADAD
- gray-80 - #2E2E2E

The follow colors are not found in **USWDS.json** or **color.json**:
- gray-warm-90 - #171716
- blue-vivid-80 - #112F4E
- blue-vivid-30 - #58B4FF
- blue-vivid-20 - #A1D3FF
- blue-vivid-10 - #CFE8FF
- blue-vivid-5 - #E8F5FF
- red-vivid-80 - #5C1111
- red-vivid-40 - #FB5A47
- green-cool-vivid-80 - #19311E
- yellow-vivid-80 - #5C4809

**Comment by narin** [comment]
As discussed in [this Slack thread](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2085), VADS requires that we define semantic tokens for each USWDS color we add to their repo. This will take some time, so I will pull the missing USWDS tokens listed above manually in the interim.
