### ISSUE TITLE
UX - Bug 7202

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7456]
**What is Happening:**  
Right now, if a user has a reply draft for a message that's older than 45 days and attempts to finish and send the draft, they get the generic messaging error snackbar which gives them the option to try again. They will also get the generic error snackbar when attempting to save the draft, for the same reason, which also has a try again button.

However, messages older than 45 days are not allowed to be replied to, so trying again will never work in either case -- we're getting a more specific error message from the backend about it, so we can do better error handling to let the veteran know to start a new message/pick a different path.

**Notes**

- Review bug ticket [7202](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7202)

**ACs:**

- UX to determine desired state for bug ticket [7202](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7202)

**Comment by Sparowhawk** [comment]
duplicate
