### ISSUE TITLE
UX Bug 6951 Work

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7458]
**Whats happening:** 

- When the request for fetching beneficiary data fails, the Benefit summary and service verification letter screen is stuck showing the loading component. This is caused by the logic in the onViewLetter function that gets called when a user tries to view the letter.
- It's not clear whether we should show an error if the beneficiary data request fails, as the logic for generating the letter will still generate the letter if beneficiary data isn't available. It needs to be determined whether we should show an error when the request fails, or if we should still allow the user to view the letter without the beneficiary data included.
- It's not clear whether we should show an error if the beneficiary data request fails, as the logic for generating the letter will still generate the letter if beneficiary data isn't available. It needs to be determined whether we should show an error when the request fails, or if we should still allow the user to view the letter without the beneficiary data included.

**Notes:**

- Review bug ticket [6951 ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6951)for more info

**ACs:**

- UX to determine desired state for [bug 6951](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6951)

**Comment by Sparowhawk** [comment]
@wavelaurenrussell can you tell me what we would like to do here?
