### ISSUE TITLE
RX - Filter and Sort - Analytics

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7466]
**Description:** 
As VA Mobile App, I want to know which sort and filter options Veterans are selecting when engaging with the RX feature so that I know how the Veteran is using the app. 

**Notes:** 
- Identified 12/5 during grooming
- Out of the box Mobile can track if Veterans go to the Sort / Filter component/page & which filter or sort by option is selected
- However there is additional work needed in order to know which filter + sort option the veteran used 
- If we want to know what filter + sort by combination they are cancelling from that will need to be discussed as its  currently not part of this scope 

**ACs:** 
- As the VA I want analytics on which filter and sort combination Veterans are apply on their RX refill
- Out of the box - how many veterans go to this page
- out of the box - how many veterans click cancel 

<img width="350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUUwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c66f5c48f00b3f33c71d3adf0def92b3d27cf53/image.png" alt="image.png" />
<img width="366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUkwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82b275738d6c9510c6bedecdf5e9f6c338f35ea4/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
@alexandec @Sparowhawk when you get a chance can you review and size this ? Analytics ticket for RX filter/sort

**Comment by bischoffa** [comment]
@alexandec @Sparowhawk can you please size this work

CC @kidlaurenpeace

**Comment by alexandec** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7466?planning-poker) with Zenhub @Sparowhawk

**Comment by bischoffa** [comment]
@Sparowhawk can you add your planning poker estimate?

**Comment by alexandec** [comment]
Merged the PR because it's solely an analytics change (no QA can be performed). Closing the ticket.
