### ISSUE TITLE
QA and Release Team Specific Backlog

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7467]
# Project Status Overview

### Project Objective:

- Purpose of this epic is to be QA and Release team's backlog of improvement items, technical debt, or other related needs that could impact our team and customers 

# Detailed Project Scope 

### Problem Statement
- Identified that the QA and Release team need a place to put suggestions, ideas on how to improve QA 
-  Also in need of a place to manage / prioritize a backlog of work that could improve the QA / Release team 

### Assumptions 
- QA and Release specific work only 
- If its related to project / epic work that work should be associated with that specific mobile team and epic 

### Risks 
- Work may need to be bucketed into its own epics - QA Documentation, Detox UI , Automate Release, etc

### Process

- Anyone can add tickets to this epic themselves or send idea/details to QA and RElease PM to put in a placeholder ticket
- If more information is needed the ticket will be assigned to it's inventor to add more information to it overtime
- Intent is to review this for at least quarterly planning consideration
-

**Comment by bischoffa** [comment]
Epic built to be a backlog of work that can be easily identified by the QA team. Its not meant for OCTO teams to see. Work will be pulled off of this and into other epic that will be viewed by OCTO teams.

**Comment by TKDickson** [comment]
Closing this epic as completed; work for the QART team is tracked on epics against workstreams now (QA, accessibility, devops)
