### ISSUE TITLE
SM - Test API header keys for Send/Reply w/ Attachment

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7476]
**Description:** 
The VA.gov team requested a change on the API header keys for send/reply message with attachment and need to ensure that Mobile is aligned with these changes. 

**Notes:** 

- New request made on 12/5 from SM team cause VA.gov wants to test this 
<img width="1441" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkU1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc1aa3105850f7593763573ff2f45bcc7da59502/image.png" alt="image.png" />
-SM's understanding is that your team uses the same header keys that VA.gov is using so this change should not impact you.  However, I still think it would be a good idea for you to test once we move it to the SysB environment.
-Updated API header keys not yet provided by Christy Gales / MHV SM 

**ACs:** 
- Ensure that API header keys match

**Comment by alexandec** [comment]
Logged in as Karsyn and created a message with an attachment, then downloaded the attachment:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/9c3cbfc8-e255-424a-bf7e-37534fde1b75

Also with Karsyn, replied to a message and added an attachment, then downloaded the attachment:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/06b0312c-5d59-48ce-9c0b-f869e7aebd70

Didn't see any issues.
