### ISSUE TITLE
BE Work - Endpoint Creation - Messaging Reply Triage Team Errors

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7482]
**Description:** 
As the VA Mobile App, I want to prevent Veterans from replying to SM messages when they do not have a triage group assigned to them any longer, in order to proactive prevent them from sending a message vs erroring out after they hit the reply button. 

**Notes:** 
- Identified in Sentry Error ticket [6822](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6822)
- In 1 month about 3.3k unique users are negatively impacted leading to about 9.2k sentry logs 

 **AC:** 
- [ ] Review ticket  [6822](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6822)
- [ ] Update /v0/messaging/health/messages/{id} to include a field that uses the endpoint in the thread above to identify if a user is still on the triage group for the given secure message
- [ ] Update specs and docs accordingly

**Comment by Tonksthebear** [comment]
My DataDog access disappeared. Waiting for a resolution with that

**Comment by jperk51** [comment]
@Tonksthebear make sure to test this in staging before closing the ticket.

**Comment by jperk51** [comment]
QAing against this ticket will happen with the FE ticket for hiding the reply button. @bischoffa

**Comment by bischoffa** [comment]
@DJUltraTom FYI to Jayson's comment above when QAing will happen

**Comment by Tonksthebear** [comment]
Confirmed this works in staging
