### ISSUE TITLE
UX - Message - SM Reply to Triage Team Errors

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7483]
**Description:** 
As the VA Mobile App, I want to prevent Veterans from replying to SM messages when they do not have a triage group assigned to them any longer, in order to proactive prevent them from sending a message vs erroring out after they hit the reply button. 

**Notes:** 
- Identified in Sentry Error ticket [6822](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6822)
- In 1 month about 3.3k unique users are negatively impacted leading to about 9.2k sentry logs 

 **AC:** 
- Review ticket  [6822](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6822)
- Identify if we need any kind of messaging to inform the Veteran why they can't reply

**Comment by mistymg** [comment]
After confirming with some team members, closing this ticket as it's almost a year old.
