### ISSUE TITLE
BUG - SEV 3 - All - Inconsistent copy in appeals details screen

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7488]
## What happened?

We're using inconsistent copy on the appeals details screen when talking about a Veteran going to VA.gov to do something they can't do in the app. Everywhere else in the app, we say "go to". But on the appeals details screen, we use the wording "visit." This should be updated to be consistent with other parts of the app.

## Specs:

- Device: iPhone SE
- OS: iOS
- User Account: Demo mode
- Accessibility State: n/a

## Steps to Reproduce

- Sign in to demo mode
- Tap Benefits on bottom navigation
- Tap Claims
- Tap Claims history
- Tap Disability compensation appeal updated on November 22, 2011
- Scroll to Need help? section

## Desired behavior

We want to be consistent with how we talk about a Veteran leaving the app to do something on VA.gov.

## Acceptance Criteria

Copy in Need help? section is updated to include:
- [ ] To review more details about your appeal, go to VA.gov.
- [ ] Go to VA.gov

Note: There should be a period at the end of the "To review more..." sentence. Not a colon.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
- Impact: Low 
- Frequency: Low 
- 3 - Low

## Screen shot of current bug

<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVEvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0da13cb7d19e41c3b0d1acd7bfb6a5cae2296413/unnamed.jpg" alt="unnamed.jpg" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [X] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Verified that 'Vist VA.gov' has been changed to 'Go to VA.gov' in the appeals need help? section as well as the file upload screen reader dropdown in claims.  Approved by QA.
