### ISSUE TITLE
Create a list of sidekiq jobs that mobile uses

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7492]
OCTO platform folks are trying to make monitoring general health and operations of vets-api better. As part of that they need to collect all the sidekiq jobs so we've been asked to make a list of all the jobs we use. 

ACs:
- [x] Create a list of sidekiq jobs we use and share it with Steve Albers

**Comment by aherzberg** [comment]
list given to Steve
Actively used Mobile specific jobs:
modules/mobile/app/sidekiq/mobile/v0/pre_cache_claims_and_appeals_job.rb
modules/mobile/app/sidekiq/mobile/v0/weekly_maintenance_window_logger.rb
modules/mobile/app/sidekiq/mobile/v0/vet360_linking_job.rb

Obsolete, no longer used, slated for removal: 
modules/mobile/app/sidekiq/mobile/v0/pre_cache_appointments_job.rb

called by Mobile endpoints but not mobile specific:
app/sidekiq/va_notify_dd_email_job.rb
app/sidekiq/lighthouse/document_upload.rb
