### ISSUE TITLE
Travel Reimbursement Claim Submission within Mobile - Build and Implement

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7500]
# Project Status Overview

### Project Objective:

1.)  Enable Veterans to digitally submit a Simple Travel Claim for eligible past appointments in the Flagship App's Appointment feature
   - Eligible part appointment = Veteran Checked In or Checked Out + Appointment in the past 30 days
   - Simple Travel Claim - roundtrip from home to VA facility and back - claim for roundtrip mileage only 
   
2.) Enable Veterans to view their Travel Reimbursement Claims for past appointments in the Flagship App's Appointment feature 

 
### Acceptance Criteria
<details>
<summary>ACs</summary>

**File a claim:**  

Given user checked into an appointment, user sees a message on the ability to submit travel claim in app

Acceptance Criteria

1.  Veteran logs into the Flagship Mobile App
2.  Veteran taps Health icon
3.  Veteran taps Appointments option on the list 
4.  For eligible past  appointments, Veteran sees the ability to start a travel claim 
    - Eligible appointment = Veteran is Checked-In and appointment date is < 30 days old (anticipating using VAOS fields from Vets-API)
    - May need to consider another filter so separate Past Appointment that are Eligible vs those that are not
5.  Veteran clicks icon to start a travel claim 
    - Simple Travel Claims only supported - Veterans with personal vehicles travel round trip to the VA facility and getting mileage reimbursement
    - Anticipating mobile will use Call Get Token, Call Claim Status to identify the eligible past claims with no submission
6.  Veteran sees message on simple claim tasks to complete before submitting a claim and getting reimbursed
7.  Veteran taps to submit travel claim request 
    - System verified all fields filled in correctly and are not missing 
    - Mobile to send request through Submit Claim API
8.  Veteran notified if their request was successfully submitted, submission was decline, or there was an error in their submission (not that the claim was approved/ processing or declined)
    - Submit Claim API will provide Mobile with a response
      - Successfully submitted - BTSSS accepted the claims request which will be manually reviewed 
      - Submission was declined - BTSSS did not accept the claim submission 
      - Error in the submission - BTSSS system error; Veteran told to submit the claim a different way
      - Mobile to prevent another submission for that appointment again 
9.  Post claim submission,  Veteran can see Travel Claim status
      - Get Token, Get Claim Status API to identify what appointments have claims and then display status 
      - See Travel Claim status of any claim they have submitted regardless of channel / method (paper, mobile, BTSSS, etc) 

</details>

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Vets-api service only can get token and submit a claim; does not get a claim status. New team being stood up to do this work - part Booz Allen and part Ad Hoc. | BTSSS  | TBD | 
| Mobile will need a faster decision than current 30+ seconds on the BTSSS decision engine.  | BTSSS / Mark  | No ETA - BTSSS testing through the environments and having some technical challenges so no commit date as of now  | 

</details>

### Project Timeline
<details>
<summary>Milestones</summary>
 - The timing is purely tentative and an estimate, but want to track the steps / needs

|Step | Timing | Status |
|-------| ---------| ------| 
| Kickoff | 8/22 & 8/25 | Completed |
| UX Discovery on Submit Claims in Appointments | Mobile Sprint 79 |  Completed | 
| BE Discovery on Get Token, Submit Claims, and Get Claim Status  | Mobile Sprint 79   |  Completed | 
| Draft Mobile UX Flow in Appointments | Sprint 80 - Sprint 82  | In Progress |
| Analytic review for TC Submission in Appointments | Sprint 80 | Completed 
| Research exploration and proposals | Sprint 82| Completed - presented 10/11 |
| Review Mobile UX Design with Travel Office and Feedback Inclusion | Est  Sprint 82 | Not Started | 
| BTSSS API changes ready for Mobile Integratin| Ongoing no ETA | In Progress | 
| Mobile applies feedback from stakeholders | TBD | Not Started | 
| Final Design Approval for  TC in Appointment by POs | TBD | Not Started | 
| Final Content review by Sitewide team | TBD | Not Started | 
| Build Travel Claim Submission in Appointments | TBD  | Not started |
| Research efforts to better understand Veteran and their understanding of travel | Not started or prioritized |
|User acceptance testing | TBD - depends on build | Not started | 
| 100% Release | TBD based on implementation / build | Not started |
|Step 4 - Post Verification| TBD based on implementation / build | Not started |
</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Aug '23| Green | Kickoff meetings, Q&A, verified which MVP ACs are supported but current BTSSS systems. Travel-pay DSVA slack channel created.  | BTSSS integration is not ready, teams being stood up to create and improve APIs |
|Sep '23| Green | Discovery completed for BE, UX, and Content.  Sprints focused on design work involving content and UX. Started meeting with Web Appointments team biweekly to discuss Mobile's work . Discussion that Mobile will work till design then shelf the work till integration is ready for Mobile. | BTSSS integration is not ready, teams being stood up to create and improve APIs. Web Appointments won't have engineering capacity will early 2024 | 
|Oct '23| Green | Demoed Mobile's proposed design during 10/11 meeting. Demo info posted on Travel-Pay DSVA slack on 10/13 for external teams to review and provide feedback. Mark to coordinate reviewers / informers within Travel. Determined that this project will be put On Hold after Sprint 82 two sprints earlier than planned for Step 2 work. Thus Mobile will get feedback from reviewers/approvers but changes will not be reviewed/incorporated until this project gets reprioritized | Prioritization| 
|Nov'23| On Hold | Project has no prioritized planned work for Q4 | Not prioritized | 
</details>

# Detailed Project Scope 

### Problem Statement
<details>
<summary>Details</summary>
- Veterans are not able to easily discover, remember, monitor, submit, or track travel claims through fax, mail, kiosk (no longer supported) or BTSSS’ web tool. These challenges come from using a complex system, a complex user experience, and a slow and error prone system.  
- Difficulties in this process span from Veteran’s to the VA’s staff of Travel Clerks who are involved in manually reviewing travel claim submissions. 
- 
</details>

### Assumptions 
<details>
<summary>List of Assumptions</summary>
</details>

### Risks 
<details>
<summary>List of Risks</summary>

- Multi-team collaboration to work web and mobile at the same time - leads to risk in prioritization, readiness, communications 
- Mobile dependency on integration readiness from other teams
- VA talks about Travel Claims focused on receiving payments/money for their claims, however project does not provide payment information as its not ready by BTSSS 

</details>

### Definition of Done 
<details>
<summary>Details</summary>

|Item | Completed | 
|-------| ---------|
| App to determine what appointments are eligible for Travel Claims | Design mocked up | 
| Veterans can submit a Travel Claim for an eligible appointment | Design mocked up| 
| Veterans will know if their travel claim is submitted, denied, or errored | Design mocked up |
| Veteran will know what to do if denied or receive an error | Design mocked up | 
| Veteran is able to see the status of any submitted travel claim | Design mocked up |

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Discoverability - Veteran can find where to submit travel claims | Including Claim payments in Mobile payments |
| Submit simple claim on eligible past appointments | Inclusion of other transportation modes outside of personal car roundtrip (train, plane) | 
|Display status of submitted Travel Claims | Upload receipts and view what I already uploaded | 
|Mobile to prevent duplicate travel claim submission for the same appointment when done in mobile | Reminder(s) to file a claim on time |
| | Inclusion of non-VA facility appointments | 
| |Any new notifications|
| | Incorporating travel claims in mobile check-in process (kay asked to get a ticket for mobile backlog) |
| | Mobile to check the many Travel Claim eligibility rules prior to submission |
| | |

</details>

### Important Project Links 
<details>
<summary>Links</summary>

- [Beneficiary Travel BTSSS Github - APIs, roadmap, Jira board, etc](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel)
- [Mobile Sprint 0](https://drive.google.com/drive/folders/1ip3WxOZiWajP5ASDqH_ng3PHyJk__QoJ  )
- [Mobile Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Travel%20Claims%20and%20Reimbursement/Product/Product%20Brief_%20Travel%20Reimbursement%20(Mobile%20App).docx)
- [Product Canvas](url)
- Research
   -[Final Report - 18F Path Analysis on Beneficiary Travel Self-Service System (BTSSS).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHAzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--632903c6f30c1abd414abcb9b44d4f44eb1ec6cf/Final%20Report%20-%2018F%20Path%20Analysis%20on%20Beneficiary%20Travel%20Self-Service%20System%20%28BTSSS%29.pdf)

   -[Travel Reimbursement Research Report 8/10/23](https://dsva.slack.com/archives/C022AC2STBM/p1692647914735679)
- Design 
   - [Current web experience in BTSSS](https://www.va.gov/hines-health-care/programs/beneficiary-travel-self-service-system-btsss/)
   - [Current web app demo](https://dvagov-my.sharepoint.com/personal/benjamin_brasso_va_gov/Documents/PCI%20travel%20reimbursement%20demo/PCI%20with%20travel%20pay%20demo.mp4?web=1)
   - [Web Design Artifacts](https://dsva.slack.com/archives/C02GXKL8WM6/p1679601902467839?thread_ts=1679410716.846019&cid=C02GXKL8WM6)
  - [Web Prototype](https://www.sketch.com/s/38819fc4-18ef-4958-a330-a699785301d6/prototype/a/0042DC07-D314-45AF-946F-884DCBBE43C0)  
  - [Web check in with travel in production](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/p/1A228FD4-6078-4206-98D1-E26C374F342C/canvas)
  - [Content changes being discussed related to eligibility](https://www.sketch.com/s/a31fc97a-2d0c-4ef0-a698-7b73b773836f/a/x0yRpoA) (Currently being worked on by Laura W. and Kelly Smith)
  - [Web's user flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1677531124203/5edcfd3ea4b1eaf1ef082d56782a8b3291ef3932?sender=u37bb983bd3fc3cc00c7d3286) (Ben B said on 8/30 that this will be updated soon to support Veterans that have more than 1 appt for the day at the same facility.)
  - Ben B provided [this additional link](https://www.sketch.com/s/0e890de3-2530-4ee0-986e-cf0314334aec/p/0EC89917-F949-4461-A7B3-32A5201FD2A2/canvas) to note how they've moved to using only a single sentence for all H1s. This is not in production. Content may be able to be used for error messages/"we can't file your travel pay claim" type of copy.
- Engineering
   - [BTSSS API info - Get token, Submit Claim, Get Claim Status](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/beneficiary-travel/engineering)

Important BTSSS docs from Mark Dewey
- [Some BTSSS screens](https://www.sketch.com/s/50c13762-b34d-44df-a657-6a75872faf82): This was a before and after done by 18F. The BEFORE screens are what's current. 18F's suggestions were not implemented.
- [BTSSS user guide](https://github.com/department-of-veterans-affairs/BTSSS_Documentation/blob/Working/Env_Depl_Impl/BTSSS_3.7.0%20User%20Guide.docx): Must be downloaded as Word Doc
- [Letter on appeal](https://dsva.slack.com/archives/C05Q9HH47PS/p1696339147255099?thread_ts=1696005901.410659&cid=C05Q9HH47PS): Letter is in Slack thread; had trouble downloading PDF
- [VA.gov page on appeals](https://www.va.gov/health/appeals/)
- [VA.gov page on travel reimbursement](https://www.va.gov/health-care/get-reimbursed-for-travel-pay/)
- [BTSSS Vetern-facing status definitions](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VDQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7efde583f2ac16f0a40f2a49ada452c13f7dcbfb/KA-01021%20%C2%A0%C2%B7%20BTSSS.pdf)

</details>

### Team Members

<details>
<summary>Contact List</summary>

- **Slack Channel:** #travel-pay

**Mobile**
  - **OCTO Product Leads:** Rachel Han 
  - **Ad Hoc PM:** Adam Kasmier
  - ** Mobile Backend Engineering:** Jayson Perkins and Jon Bindbeutel
  - ** Mobile Frontend Engineering:** TBD 
  - **Mobile Design:** Lauren Russell

**Notifications**
  -**OCTO Notifications:** Beverly Nelson

**Travel Pay BTSSS**
  - **OCTO Travel Engineer :** Mark Dewey
  - **OCTO PO Patient Check-In, Appointments, Travel Claims** Lauren Alexanderson
  - **OCTO Design Lead worked on travel pilot:** Kristen McConnell

**Travel Pay BTSSS API Team**
 - Booz Allen
 - Ad Hoc 
   - Kevin Duensing - Engineering Lead
   -  Lauren Ernest - PM 
   
**Appointments** 
 - **PM** - Lead De La Costa
 - **PM** - Jeff Roof
 - **Design** - Peter Russo
 - **Lead Engineer** - Simi Adebowale
 - **BE Engineering** - Core Ferris 

**Sitewide Content**
- **PO** - Danielle Thierry 

</details>

### OKR and Analytic Metrics 
<details>
<summary>Metric definitions</summary>

- Veteran engagement?  
- Veteran task success?  
- Which path gets to higher veteran task success?

</details> 

<details>
<summary>Metric Details  </summary>

|What we are measuring | Why | Event Name 
|-------| ---------| ----- |
| Number of veterans who started a claim | | |
|Number of incomplete claims| | |
|Number of complete claims | | |
|Number of submitted claims| | |
|Number of reimbursement payments | | |
|Number of veterans with reimbursement payments | | |
|% of claims successfully submitted via A vs B| | |
|% of veterans who successfully submitted a claim via A vs B | | |

</details>

### Questions 

- [Github Link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Travel%20Claims%20and%20Reimbursement/Product/Question%20Log.md)

### Decision / Change Log 
- [Github link](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Travel%20Claims%20and%20Reimbursement/Product/Decision%20Change%20Log.md)

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] Project Kickoff session
   - [ ] Initiative Scope finalized
   - [ ] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [ ] Link to Implementation Strategy
       - Implementation Plan
       - UAT Plan
       - Release Plan
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide
  - [ ] Coordinate with contact center support teams
- [ ] What’s New Content
- [ ] App Store/In App messaging (if applicable)
- [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
- [ ] App store images needed? Y/N
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by bischoffa** [comment]
Design epic for this work was [1255](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/1255). Purpose of this epic is coding, building, and releasing the feature when prioritized.

**Comment by ala-yna** [comment]
Closing out this epic in favor of [#9663](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9663)
