### ISSUE TITLE
BUG - sev-2 -All - Back button chevron too large

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#7511]
## What happened?

The back button chevron is too large as a side effect of [#5034](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5034). Icon width of 15px is missing, which was exposed by the change.

## Steps to Reproduce

View any back button that has text next to it.

## Desired behavior

Back button chevron should be 15px wide by 13px high.

## Acceptance Criteria

Back button chevron is the correct size.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High

- 2 - High

## Screen shot(s) and additional information

<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/20d7c8d4-966b-478b-bf27-17fcafda039a" width="50%">

## Ticket Checklist
- [x] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by alexandec** [comment]
This should be quick to resolve by adding a width to the DescriptiveBackButton icon.

**Comment by DJUltraTom** [comment]
verified back arrow is looking good
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--647d2d8f75b59888978d0cca3df0ac4fa941f1a9/IMG_E83E66491329-1.jpeg" alt="IMG_E83E66491329-1.jpeg" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkp2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21cdf3c35707d238f7071fb1834150bae6e54147/Screenshot_20231218-193438.png" alt="Screenshot_20231218-193438.png" />

**Comment by DJUltraTom** [comment]
changes look correct on nightly builds, 
Closing this ticket as deployed.
