### ISSUE TITLE
Retest Request of  Create Message Phase 3

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7514]
**Description:** 
As MHV SM, I need Mobile to again test send, ply with attachment and test download of attachments of sent and received messages so that MHV SM can proceed with their SM Patient API changes

**Notes:** 

- Slack thread https://dsva.slack.com/archives/C05TU9FPZU0/p1702333210816559
- Request of Mobile to again test Create Message Phase 3 

**ACs**
- send / reply a message with attachments 
- download attachments of sent and received messages 
- 

<img width="1129" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3hSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4076950be4fe1a2537fc8951f8fb020109d25b5a/image.png" alt="image.png" />

**Comment by alexandec** [comment]
Logged in as Karsyn and created a message with an attachment, then downloaded the attachment:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/9c3cbfc8-e255-424a-bf7e-37534fde1b75

Also with Karsyn, replied to a message and added an attachment, then downloaded the attachment:

https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5805150/06b0312c-5d59-48ce-9c0b-f869e7aebd70

Didn't see any issues.
