### ISSUE TITLE
RX - Update / Create Detox Tests

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7515]
**Description:** 
- As Mobile, I need to update automated testing for the changes we are making to RX in order to reduce the risk of finding bugs and issues. 

**Notes:** 
- Needs to be updated before work is put into production 
- Team should also discuss RC testing updates and if FE needs to update Unit tests

**ACs:**
- Existing RX detox tests need to be updated with RX changes that are happening for this epic

**Comment by alexandec** [comment]
@rbontrager since I've revised the detox tests for the new RX changes in [this PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7636/files), we can use this ticket to cover your review of those tests and any changes that might be needed

**Comment by rbontrager** [comment]
@alexandec Just a couple small issue.  As you alluded to in my navigation PR you will need to delete line 41/42 ([['Prescriptions', 'Pending (8)'], 'Pending refills (8)'], [['Prescriptions', 'Tracking (5)'], 'Refills with tracking information (5)']]).  It would probably be easiest to change ACETAMINOPHEN... in this line ([['Prescriptions', 'Get prescription details'], 'ACETAMINOPHEN 325MG TAB']) so it matches the name of the first prescription and line 185: await waitFor(element(by.label('ADEFOVIR DIPIVOXIL 10MG TAB.')))... to match the name of the second prescription.  

Also when I ran the prescriptions test it was crashing on line 387: await element(by.text('Prescriptions')).atIndex(0).tap().  This line shouldn't be necessary anymore and can be deleted.

**Comment by alexandec** [comment]
@rbontrager thanks! I've made those changes in the PR, and the prescriptions and navigation tests are all succeeding for me locally. Let me know if there's anything else to do on these tests

**Comment by rbontrager** [comment]
@alexandec Looks good on my end.

**Comment by alexandec** [comment]
@rbontrager great, thanks for taking a look. I'll close this one.
