### ISSUE TITLE
BUG - sev-2 - All - Pending appointments not returning in appointments call, nor throwing error

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7516]
## What happened?

Logging into the app as grethel.g.petryniec@id.me, I get no errors in the appointments API returns, BUT none of her pending appointments display.
Logging into the website as that same user, I can see…. looks like ~10 pending appointments. (Ex: 198552 is a pending appointment for her)

Same thing happens with brienne.b.ferrara@id.me, so it's not limited to a single user.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Tonksthebear** [comment]
Need to investigate with FE because from what I'm able to see, we are returning the pending appointments in the response as expected

**Comment by Tonksthebear** [comment]
FE looked in to it and they found the missing appointments. It seems it is a non-issue
https://adhoc.slack.com/archives/C0212B872MT/p1703821063719239
