### ISSUE TITLE
BUG - sev-3 - All - Availability Framework: The screen content is shown when navigating back from a screen with use case 2

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7522]
## What happened?

When a user navigates back out from a screen that has `DenyContent` (use case 2) set, the content for that screen is briefly shown, while navigating to the previous screen. This issue is similar to https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7261. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Set use case 2 for a screen and navigate to that screen. Press the back button and see the screen's content shown as the app navigates back.

## Acceptance Criteria

Navigating back out of a screen with use case 2 enabled shouldn't show the content for that screen while navigating back.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODlWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b60379eaf786346e8c9c19a9d80db7bfda0e454/Simulator%20Screen%20Recording%20-%20iPhone%2013%20Pro%20Max%20-%202023-12-12%20at%2020.03.15.mp4)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
This is one of the "fix only if it doesn't increase code complexity" tickets currently slated for this sprint

**Comment by TKDickson** [comment]
Fixes AF use case 2, and animations for UC1 and UC3 still working as expected ([video](https://drive.google.com/file/d/1QiHIBssHw4MpxpOvSVP5rZmD5bXGzzbo/view?usp=sharing)). Also did a quick screenreader pass that announced and moved as expected as well.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop, closing
