### ISSUE TITLE
Display Monthly Payment & Disability Rating on the Home Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7530]
AC:
- If the Veteran has a disability rating above 0%, then display it on the home screen
- If the Veteran has a monthly payment from disability, then display it on the home screen

Notes & References:
[MVP Balsamiq](https://balsamiq.cloud/s4uw4la/pnnwuqv/rC00A)

**Comment by TKDickson** [comment]
QA points: 2. This ticket does not include error handling, just basic display/disappearance of the data (which I will mainly mock).

Will need notes added (from either @ajsarkar28 or FE Eng who works this) about which APIs & fields we're checking exactly for this info, and that we've confirmed those are the correct ones (pre- and post-Lighthouse migration) with the BE team.

**Comment by TKDickson** [comment]
@theodur can you confirm you're using these fields:
* Disability rating: `combinedDisabilityRating` from `mobile/v0/disability-rating `
* Monthly payment: `monthlyAwardAmount` from `mobile/v0/letters/beneficiary`

**Comment by TKDickson** [comment]
If/when Theo confirms the above, I realized that I did the initial testing on this, last week. 

Which is limited to "if there's a non-zero number in the fields above, it shows up on the home screen. And if those fields are either null or the equivalent of 0, the information does not show up on the home screen"

**Comment by theodur** [comment]
@TKDickson Sorry, I should have noted the endpoints I'm using based on your [comment](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7530#issuecomment-1861236936) above 😅.

I'm using both of those fields from the endpoints you mentioned

**Comment by TKDickson** [comment]
Excellent! Testing done, no issues found, ready to merge to XL.

**Comment by TKDickson** [comment]
Merged to XL; closing.
