### ISSUE TITLE
BUG - sev-3 - All - claims: another error to handle more gracefully

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7531]
## What happened?

Basically the same problem as addressed by #4879, but with a different error coming back from the backend (see JSON section)

The user experience is - tap "claims", have a longgggg time sitting there waiting for the page to load, eventually get an error. But the backend is sending us the error IMMEDIATELY upon tapping claims.

IDK if this is a problem related to the fact that this user is going Benefits landing page --> Claims history (rather than Benefits landing page --> claims landing page --> claims history), just in case that helps.

## Specs:

- Device:
- OS:
- User Account: karsyn (meds tester)
- Accessibility State:

## Steps to Reproduce

Log in as karsyn and tap "benefits" then "claims", see traffic with Charles.
Alternatively, mock this using the charles response in the JSON below.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  
HTTP/1.1 502 Bad Gateway
Date: Wed, 13 Dec 2023 20:22:58 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 446
Referrer-Policy: strict-origin-when-cross-origin
Vary: Accept, Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Git-Sha: 01728b493b7365a1c476e017bfc7a7d3de86b765
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: bc89d8bd-40ac-46fd-9034-4c4ca65c7122
X-Runtime: 0.536960
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Connection: keep-alive

{"data":[],"meta":{"errors":[{"service":"appeals","errorDetails":[{"title":"Not found","detail":"Appeals data for a veteran with that SSN was not found","code":"CASEFLOWSTATUS404","source":"A veteran with that SSN was not found in our systems.","status":"404"}]},{"service":"claims","errorDetails":"Forbidden: User is not authorized for claims"}],"pagination":{"currentPage":1,"perPage":10,"totalPages":0,"totalEntries":0},"activeClaimsCount":0}}
</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@TKDickson @rbontrager can you check to see if this is still an issue React Query migration for Claims and appeals was just merged

**Comment by rbontrager** [comment]
@Sparowhawk This looks to still be a problem on the latest React Query build.

**Comment by Sparowhawk** [comment]
@rbontrager @TKDickson Unfortunately the hang up is the response.json() function that is a function we have no control over. I have tried some type casting fixes for deserialization that should have sped it up, but didn't when testing. The only thing I can think of to do from here is to have BE manually send us an easier error to parse that is as simplistic as possible. This might be a good candidate for the first usage of the error wrapper component that is coming soon.

**Comment by Sparowhawk** [comment]
@bischoffa @rbontrager @TKDickson I believe this one will partially be addressed once the retries for react query is turned off if it hasn't been already.

**Comment by TKDickson** [comment]
This is a duplicate of #7746, closing. (7746 has been fixed)
