### ISSUE TITLE
Update Status Counting Mechanism for Prescriptions

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7532]
**Background**
On the Personalized Home Screen, each feature will have a module that displays the number of active statuses which empowers veterans to have improved visibility into what is going on for each feature that they are using. For instance, the Home Screen could let a veteran know that they have 3 prescriptions ready for refill.

AC:
- [ ] Update status counting mechanism for prescriptions to only count the number of prescriptions that are able to be refilled 
  - note that this is an update to functionality built in this [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7212)

**Comment by TKDickson** [comment]
No QA estimate; testing for all of the counting logic will be done/documented against #7549.

**Comment by TKDickson** [comment]
Bahh I mean all QA against BE testing will happen on #7533, not the one linked above.
