### ISSUE TITLE
Spike / Sprint 0 - Having non-QA team create / update detox tests for new/updated features

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7540]
**Description:** 
As VA Mobile Release Team, I want to investigate the pros and cons of having engineers being responsible for creating/modify automated QA test vs relying on QA to do it to see if there is way to further improve QA testing efficiency, improve VA OKR of stability, and reduce VA's OKR of fatal errors  

**Notes:**
- Could be written up as a sprint 0 
- Short term if we can at least make Detox test MVP requirements this ticket can be delayed
- Intent is to reduce the reliance on QA to do the automated testing and also to ensure that this gets done during feature creation / improvement 

**ACs:** 
- [ ] Understand if this something Mobile engineering can do
- [ ] Understand if this is something that external teams plugging into Mobile platform should be able to do 
- [ ] Does this improve VA OKR's stability OKR 
- [ ] What would be QA's role / responsibility if engineering could or could not do it 
- [ ] Document findings and recommendation - store in Github [QA team folder ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release)

<img width="504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRmQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a116226a651b29d5e24f11e82ecf8461fe0937d/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Tim mentioned on 1/4/2024 that he supports the end state of having engineers handling this. The time to make this transition is not expected to be done in early 2024 with current resources. So holding off on pushing this ticket till Q2/Q3 consideration.

**Comment by TKDickson** [comment]
Closing this as no longer needed (FE currently expected to, and doing, detox updates instead of QA)
