### ISSUE TITLE
Exploratory - Does QA need to keep the last 2 days of the Sprint open just for QA testing 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7543]
**Description:** 
As VA Mobile QA, knowing that sometimes that last few days of a sprint is when teams dump a lot of testing needs onto QA I would like to explore how best to accommodate , in order to improve stability, testing efficiency, and be mindful of QA work overload and burnout. 

**Notes:** 
- Name of the ticket is proposing a solution but any solution is welcomed
- Not sure if this is needed all the time 
- Could tie into SLA when responding to other teams 

ACs: 
- [ ]  Team discussion 
- [ ]  Verify if its a problem and if so what specifically is the problem
- [ ]  Brainstorm possible solution
- [ ]  Team to test at least 1 solution to see if its helpful

**Comment by bischoffa** [comment]
In convo with Matt in April 2024, this may be something the team considers as non-Mobile VA POs will need to approve work. And currently Mobile team's don't know what is going to get completed in a sprint until the day the sprint ends which is not timely for an approval process for VA POs. 

Keeping in backlog until Mobile Leadership and Mobile VA make a determination on how non Mobile VA POs will engage with release / ticket approvals.

**Comment by TKDickson** [comment]
Closing this ticket; QA process will remain that we test the highest priorities first. If tickets are required to make a given sprint, PMs for the subteam (ex: global) will need to work with the full team to make sure that everyone is on the same page, that the tickets themselves are in a testable state in a suitable time frame, etc.
