### ISSUE TITLE
BUG - sev-3 - All - Inconsistent analytics

### ISSUE THREAD

**Issue by g-opzt** [department-of-veterans-affairs/va-mobile-app#7555]
## What happened?

Event `vama_claim_eval_submit` should track when the user clicks "Request claim evaluation" on the Claim evaluation screen.
Then, the user must perform a confirmation click in their native UI. That click should be captured by `vama_claim_eval_conf`.

Since `vama_claim_eval_conf` comes after `vama_claim_eval_submit`, the count for `vama_claim_eval_submit` should be greater than or equal to the count for `vama_claim_eval_conf`. However, the opposite is happening. This means, something is wrong with the logic with one or both of these events.

## Desired behavior

Described above and in original ticket #5940

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
- 3 - Low
- 
## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Verified vama_claim_eval_submit is shown in the emulator logs before vama_claim_eval_conf.  Approved by QA.
