### ISSUE TITLE
Update Status Counting Mechanism for Appointments

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7556]
AC:
- [ ] Update status counting mechanism for appointments to such that only appointments that are in the next 7 days are counted NOT appointments in the next 2 weeks, which is the current functionality 
  - note that this is an update to functionality built in this [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7211)

**Comment by timwright12** [comment]
@kpethtel testing comments
