### ISSUE TITLE
Upgrade React Native from 0.72.7 to latest

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7560]
RN 0.73.0 was released week of 12/10. It requires updating a lot of our other dependencies. So those will need to be updated first prior to updating this one

**Comment by timwright12** [comment]
Removed the health label since this is a global task

**Comment by TKDickson** [comment]
@timwright12 -- Dylan's doing the work, and it should therefore be tested by Tom. I understand why the health label is technically incorrect by the type of work, but for all practical purposes this is being done by health so it makes logistics easier (pulling into searches, covering at correct standup, now the QA automation stuff).

**Comment by timwright12** [comment]
The people involved is up to the team, but it's global work, so we should label it as such

**Comment by Sparowhawk** [comment]
have to wait for detox to support 0.73.x https://github.com/wix/Detox/issues

**Comment by DJUltraTom** [comment]
QA note: to validate we will want to perform a full RC test on the new builds

**Comment by rbontrager** [comment]
Two slight issues being seen with detox. Runs here [android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/8203560496/job/22436519300), [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/8203557899/job/22436511498)
1. Appeals is currently failing.  On best guess it is now printing out a GMT date in demo mode on github actions and not UTC like it was previously.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cef4fe076026d12f5a9bc4b0ae341eb3cdd39642/AppealsFailureRNUpdate.png" alt="AppealsFailureRNUpdate.png" />

<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTNNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d7abc0057537c9e54ed93a8e1eaa7822286b945/Appeals.PNG" alt="Appeals.PNG" />

2.  Navigation is failing for android with a "Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment" both locally and on github actions.

**Comment by Sparowhawk** [comment]
@rbontrager I fixed both issues and it should be fine now.

**Comment by rbontrager** [comment]
Ran a full RC test and detox test with no issues.  Approved by QA.
