### ISSUE TITLE
Re-fetch claim when not found

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7564]
Recent [errors](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?env=eks-prod&graphType=flamegraph&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Aclaims%2CselectedResource%3A%28type%3Aresource%2CresourceID%3A8333ac3c792a8596%29%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=4507534500178944645&spanViewType=errors&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Aratio%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&timeHint=1702401730880&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&trace=AgAAAYxfDOlARPlAuQAAAAAAAAAYAAAAAEFZeGZEUHFnQUFCZkp1Z2R0c0QyRmdjYwAAACQAAAAAMDE4YzVmMGQtYzE2MC00YjcyLTk1ZmMtOWI4NTQyYTI0YWI4&traceID=2019806864130720079&view=spans&start=1702399198421&end=1702402798421&paused=true) indicate that front end is requesting claims request decisions that aren't being found, which is causing internal server errors. 

This [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7519) fixed the internal server errors, but replacing a 500 with a 404 still results in a bad user experience. 

When the user requests the claims and appeals index from EVSS, the records are all written to the database (which is rare for the vets-api) and then deleted by a cron once they're over 24 hours old. It's possible this is causing some sort of race condition in which the front end is using locally cached data that has already been deleted on the server, so when the user requests a claim, document, or request decision, the backend attempts to find the record in the database and returns 404 when it's not found. 

This user experience can be improved by re-fetching the claim and re-writing it to the database. This applies to `get_claim`, `get_request_decision`, `upload_document`, and `upload_multi_image` in `modules/mobile/app/services/mobile/v0/claims/proxy.rb`. All of those receive a claim evss id from the front end, which could be used to refetch the claim record from upstream using `lib/evss/claims_service.rb#find_claim_by_id`. That would allow all four of those methods to proceed safely and provide the user the data.

Acceptance Criteria:
- attempt to confirm behavior by asking front end how it responds to 500 vs 404
- look at datadog logs by user session and attempt to determine whether the race condition is happening
- change behavior for all proxy methods to re-fetch the claim. return 404 if claim is still not found
- add any logging that would be helpful for future proofing
- update specs
- ensure docs are still up to date

**Comment by kpethtel** [comment]
See Charles' comment here: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7519#issuecomment-1860664547

**Comment by Tonksthebear** [comment]
Any error > 399 results in the same error screen https://adhoc.slack.com/archives/C0212B872MT/p1704742308090589

**Comment by Tonksthebear** [comment]
Notable [error](https://vagov.ddog-gov.com/apm/error-tracking?query=resource_name%3A%28%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23request_decision%22%20OR%20%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23index%22%20OR%20%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23upload_document%22%20OR%20%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23get_claim%22%20OR%20%22Mobile%3A%3AV0%3A%3AClaimsAndAppealsController%23get_appeal%22%29&index=&issueId=6071ece4-622d-11ee-8022-da7ad0900007&refresh_mode=paused&view=spans&from_ts=1701417600000&to_ts=1704096000000&live=false)

**Comment by Tonksthebear** [comment]
After looking through the code and errors, it seems like the best option here may be to take no action, especially considering EVSS is legacy code. @kpethtel is right that the most likely culprit has to do with our database that saves EVSS claims. The errors pop up with 
```
        def request_decision(id)
          claim = EVSSClaim.for_user(@user).find_by(evss_id: id)
          claim_not_found(id, __method__) unless claim

          jid = evss_claim_service.request_decision(claim)
          claim.update(requested_decision: true)
          jid
        end
```

For some reason, certain claims are not saved to the database and claim is nil. The two options would be:

1. Ignore claim being nil and just pass `id` into `evss_claim_service.request_decision(claim)` directly. This would require tweaking the service to accept just an id
2. Create a new EVSSClaim if it is nil. Creating the claim would require passing in extra parameters to `request_decision`

Neither of these options seem great considering the code is legacy and we're not sure of the original intention of the database. Changing things may not be worth the risk, especially considering the low volume of errors coming through related to this code
