### ISSUE TITLE
GitHub/ZenHub automation - When Health/Global/Platform team label is applied it auto assigns the corresponding QA team member to the zenhub issue

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7587]
During standup we found that one issue was a ticket was previously worked on other people but was moved over to health. Tom didn't know it was on his radar as he wasn't assigned. So to fix this when the labels are added and removed the workflow should assign or remove people from the corresponding issue ticket.

**Comment by Sparowhawk** [comment]
@DJUltraTom Here is that workflow we talked about in standup

It auto assigns QA to an issue based on the labels.

Health = Tom
global = Therese
design-system = Rachael

I don't think this action works until it is merged into develop so won't be able to test until then

**Comment by DJUltraTom** [comment]
validated by creating https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7672 and assigning different labels to it, verified the corresponding QA engineer is auto assigned

**Comment by DJUltraTom** [comment]
closing as deployed
