### ISSUE TITLE
Document 2023 Retention

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7593]
AC:

- User retention, based on whether the Veteran viewed the Home Screen, is documented for entirety of 2024

**Comment by OVezeamama** [comment]
Closing this ticket out. Working on it through on a[ different ticket ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8916)
