### ISSUE TITLE
Update Data Dictionary with Push Notification Opt-in

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7594]
AC:

- Data dictionary is updated for user property vama_uses_notifications, which denotes whether the Veteran has opted in to receiving push notifications

**Comment by g-opzt** [comment]
This was already add. See the User properties tab of the [analytics dictionary sheet.](https://docs.google.com/spreadsheets/d/1ECSer30BRCs4gHyvapIoCsGAx33_pIyqeYYsd3PznSQ/edit#gid=709539025)
