### ISSUE TITLE
Update Category page template with new home screen personalization UI with Populated and Loading States

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7598]
**AC:**
* Category page template is updated with the new home screen personalization UI, in this linked [Figma](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2999-1191&mode=design&t=rDrIgUlQHnoOIvh5-4)

**Populated**
- For detailed appearance logic, see this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?wid=0-1704409212320)
- Display all feature modules for respective Category screen

**Loading** 
- The Category page reflects the loading designs in the Figma file

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
Payments is the only category screen that doesn't have dynamic content, so after #7598 and #7936 it'll be completely finished. So, [test case for that category screen](https://dsvavsp.testrail.io/index.php?/cases/view/59277) as the stand-in for this ticket.

**Comment by TKDickson** [comment]
Merged to XL, closing.

Testing details on #7936.
