### ISSUE TITLE
Link Row Component Creation & Implementation

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7599]
**Component Creation**
- A new Link Row component is created (derived from Simple Row), that reflects the designs for the Contact us and Find a VA Location in this [figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-1920&mode=design&t=vJWw89ED2PwHi60F-4)
- VQA by Lauren and Therese is required to complete this ticket

**Component Implementation**
- The new Link Row component, created above, is implemented on the home screen in the VA Resources section for Contact us and Find a VA Location

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
[Test rail cases link](https://dsvavsp.testrail.io/index.php?/cases/view/59280)

**Comment by wavelaurenrussell** [comment]
1. Make sure the same spacing from the right is the same as on Vet Status chevron. We want a clean line top to bottom.
2. Make sure the icon is fixed and does not resize on display zoom. 
3. Can we change the icons to primary-blue and dark mode vivid blue? I updated the spec in Figma.

@TKDickson @theodur

**Comment by theodur** [comment]
@wavelaurenrussell @TKDickson Made the requested changes, this is ready to be reviewed again ✅

**Comment by wavelaurenrussell** [comment]
Yep. Looks good.

**Comment by TKDickson** [comment]
Merged to XL, closing
