### ISSUE TITLE
Investigate and fix messaging 500 errors when read_receipt is nil from MHV

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7619]
We occasionally get messages back from MHV with a nil read_receipt. It seems that our counting logic doesn't play nice with nils. Try to clean this up. My assumption is it's safe to treat the nils as false but confirming with MHV [here](https://dsva.slack.com/archives/C05TU9FPZU0/p1704305167247559)

https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?env=eks-prod&graphType=flamegraph&panels=qson%3A%28data%3A%28resource%3A%28resourceName%3AMobile%253A%253AV0%253A%253AMessagesController%2523thread%2CresourceID%3A12886fb66f8af323%29%2Ctrace%3A%28traceID%3A3179884543335978012%2CspanID%3A4569116987664084482%29%2CactivePanelKey%3Atrace%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=4569116987664084482&spanViewType=errors&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1704276000000&end=1704283200000&paused=true

**Comment by jperk51** [comment]
Since this is only happening for v0 controller it seems to be an issue with this code: `obj.read_receipt`

**Comment by jperk51** [comment]
@StacyB2023 Is there a reason this was pulled to in progress?

**Comment by StacyB2023** [comment]
@jperk51 : Unassigned since you are OOO. Putting this one in next sprint so someone else can pick up and close this coming sprint.  cc: @kpethtel @Tonksthebear @aherzberg
