### ISSUE TITLE
Document bug ticket frequency update process

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7623]
The current process for updating the [bug frequency documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/#frequency-definitions) (which states which features are used by 15% or more of monthly users) is undocumented, but this work is done every quarter to see which new features are 'high frequency' (happens a decent amount) and if there are any existing features that have slipped out of the high frequency category (not as common).

- [ ] Record a zoom call of the current process
- [ ] Figure out a way to transcribe that meaningfully in the doc site (or other central resource)

**Comment by bischoffa** [comment]
Fromb 1/3 Qart meeting, Therese to create a recording on how this is done so that Adam can own this process. 

Frequency in the process may change from quarterly to 2x a year or 1x a year - tbd
