### ISSUE TITLE
2024 Mobile Code Freeze Review and Decision - Revisit Q4 Planning

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7629]
**Purpose:** 
As VAHB, I want to determine early in 2024 is there will be a mobile code freeze that aligns with the VA code freeze, so that we can proactive identify and communicate it with VA and impacted teams. 

**Info:** 
- Find Review VA 2024 Freeze Schedule
- Identify what Mobile's release overlap is
- Mobile decided to have a freeze last minute in 2023 - would like to be proactive and identify earlier

**ACs**:
- [ ] Propose and get approval from POs for freeze
- [ ] Share decision with team for all to be aware
- [ ] Update release calendar
- [ ] Update relevant release documents 
- [ ] Update QA decision log

**Comment by bischoffa** [comment]
May need to consider expanding it to freeze 2 releases. For 2023 we froze release 2.19 but that branch was cut on the 3rd and not a ton of people were in the office or prepared for this release while out causing some confusion for 2.19

**Comment by bischoffa** [comment]
Asked Rachel for input on 1/9; followed up on 2/5.

**Comment by bischoffa** [comment]
Sent proposal idea of delaying 2.44 and 2.45 to Tim 

<img width="1277" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01yQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b3778dd04b936a19c912702227376f349c8e27e/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
[VA Holiday Freeze found here](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies#DeploymentPolicies-Holidayreleasefreezeschedule)

**Comment by bischoffa** [comment]
Tim isn't against the principle but may depend on the content.

**Comment by bischoffa** [comment]
https://dsva.slack.com/archives/CE4304QPK/p1699303084791119 

<img width="1318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUpaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8197056494f6c1ecbaeb20448186610f779574bb/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Will reach out to Don to get his thoughts on this.

**Comment by TKDickson** [comment]
@timwright12 a code freeze around the holidays has already been agreed upon & approved, right? If yes (or if no but this ticket isn't needed because the work is happening elsewhere), I will close this ticket.

**Comment by timwright12** [comment]
Yeah you can close this. We haven't communicated the freeze yet but it's approved
