### ISSUE TITLE
Strategy for QA Team PM Assistance in Testing Q3

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7630]
**Purpose:** 
As QA and Release Team, I want to determine what testing efforts and needs that the QA PM can support, so that we can adequately educate the PM and set expectations. 

**Info:** 
 - Likely be dependent on PM's skills, knowledge capabilities
 - Maybe consider education in phases 1 - easy/simple 2- little more completed 3 - very complicated
 - Determine what tools / systems need access 

**ACs:**

- [ ] Determine what testing QA PM can / should do
- [ ] Document necessary information
- [ ] Educate QA PM 
- [ ] Repeatable process / document

**Comment by bischoffa** [comment]
See [Test Accounts Policy](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Ticket%20Account%20Needs.md) for more information. Feeling that is adequate enough to close out this ticket.

**Comment by bischoffa** [comment]
Revisited when I am back from Paternity leave. 2Q goal?

**Comment by TKDickson** [comment]
Closing this ticket as no longer relevant/outdated.
