### ISSUE TITLE
Component App Propagation - Button - Flagship Remaining Global Spots

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#7635]
## Description

This ticket needs to be sprint-aligned with the Global App team to be able to offer support, collect feedback, and make needed changes to the VAButton component package for App Propagation. Due to the nature of this ticket, the work will likely carry over multiple sprints.

## Developer Notes
- Component does NOT support icons on buttons, they should be removed.
- `a11yLabel` will no longer be integrated with `testIdProps`
- `ButtonTypeConstants` has been renamed to `ButtonVariants` and can also be imported from the library
- Button variant names are the same but without the `button` prefix. (e.g. `Destructive` instead of the previous `buttonDestructive`
- The following props have been removed as they were not being used or being deprecated:
  - accessibilityState
  - disabled
  - disabledText
  - hideBorder
  - iconProps
  - minHeight

## Important links
- [Storybook documentation](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/docs/button--secondary)
- [npm package](https://www.npmjs.com/package/@department-of-veterans-affairs/mobile-component-library)

## Definition of Done

- [ ] VAButton has been replaced with new Button component and implemented on the following screens of the app
    - [ ] Error screen
    - [ ] Call help center
    - [ ] Error alert
- [ ] The Mobile apps have been released to their respective app stores with the component installed
- [ ] Flagship devs relay any DS feedback to the DS team (ex: if anything was difficult to work with - tools or process, if anything didn't work as we intended or the Flagship team needs any additional support for the DS team to implement the component.)

**Comment by Sparowhawk** [comment]
@kellylein I updated all the spots when I did 7311. This one can be closed
