### ISSUE TITLE
BUG - sev-3 - All - Contact Info - remove home address confirmation is showing the accessibility callout if you enter the 'edit' screens with screenreader on

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7642]
## What happened?

If I tap into edit [specific piece of contact info, ie address, phone or email] with screen reader on, the confirmation text that appears for the remove [specific piece of contact info] will display the accessibility text (not just read it).
If I tap into edit with screen reader off, I see the 'normal' text for the remove home address confirmation  

iOS is showing the bug, Android is showing what I'd expect to see. Note "VA" vs "  V-A " (extra spaces intentional in those quotes) in the photo:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7adc289cc52972f21ac32511a080abef64a0928/image.png" alt="image.png" />

Is this some kind of workaround we needed to have in place, in order to get "VA" to be pronounced correctly on this confirmation? Is that the best choice, or should we just have "vah" or "via" or etc instead of "vee ay"?

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by theodur** [comment]
This is definitely a workaround to get the screen reader to pronounce "VA" correctly. The alert hook uses the `a11yLabelVA` function whenever the screen reader is enabled. Unfortunately, there's not a way to specify accessibility labels for native alerts.

Not sure if we need Brea to weigh in, but since only a small percentage of our users are impacted by the mispronunciation of "VA" I think it'd be better to visually represent the "VA" text correctly as opposed to visually misrepresenting it just to account for the mispronunciation issue. I made those changes in my [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8791) for now.

**Comment by TKDickson** [comment]
not currently testing (over limit)

**Comment by TKDickson** [comment]
Picking up this ticket as one of my 3

**Comment by TKDickson** [comment]
<img width="525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGh0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45cee72970a7ae411837c808c148b46604abe6a9/image.png" alt="image.png" />

Approved to merge to develop

**Comment by TKDickson** [comment]
Does not require further testing in develop; closing
