### ISSUE TITLE
BUG - [iOS] - TOU: User is redirected to 'signing you in screen' that never goes away after declining Terms of Use

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#7644]
## What happened?

When declining the terms of use the user is redirected to the signing you in screen instead of back to the login screen.  This only happens on iOS and the identity team [here](https://dsva.slack.com/archives/C03DY3FN7HQ/p1703094921053359?thread_ts=1696541395.629659&channel=C03DY3FN7HQ&message_ts=1703094921.053359) it is probably on our end.

## Specs:

- Device: iOS
- OS:
- User Account: +249
- Accessibility State:

## Steps to Reproduce

1. Login to user +249
2. In the TOU page scroll down and tap 'Decline'. Tap 'Decline and sign out'.
3. In the 'We've signed you out page' tap sign in.  Notice that you are sent to the signing you in... screen and not the login screen

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjJpQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--160fcb3eb143eecf5becff23f56845acc587b70f/RPReplay_Final1702057367%20%281%29.mp4)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
@kellylein is Global team picking this up next sprint? Or is this being worked under your team? Trying to figure out what team label is needed for this ticket? From Slack I thought it would be Global

**Comment by bischoffa** [comment]
@rbontrager can you update the ticket to identify the severity of this ticket? and also tag the flagship team doing this work.
