### ISSUE TITLE
Investigate necessity of vet360 linking sidekiq job

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7653]
When a user auths we run a vet360 linking job which is intended to tie a users dataset to the dataset from vet360 but this may have only been necessary for the IAM integration of auth. The issue with how it is right now is platform is watching errors raised by sidekiq jobs and this one errors frequently enough to be noisy. Since we likely aren't going to do anything about the failures we should just make them quite and check them manually ourselves via a log line. 

Ref thread: https://dsva.slack.com/archives/C018V2JCWRJ/p1704378405845069

AC:
 - [ ] determine if this is still needed for SIS or IAM auth 
 - [ ] if no longer needed go ahead and remove it else do below ACs
 - [ ] Clean up linking job so the error isn't raised
 - [ ] add logging for recording the error

**Comment by Tonksthebear** [comment]
This is being investigated on [#vsp-identity](https://dsva.slack.com/archives/CSFV4QTKN/p1705961409519999). In the meantime, I removed the raise so that we don't clog the dashboard
