### ISSUE TITLE
Update In-App Review Code to Include New Features

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7657]
# Project Status Overview
The list of events which prompt a user to review the VA app hasn't been updated since August 2021. This is a one-time effort to 'catch us up' to all of the new features that we've added since that point.

### Monthly Update 
<details>
<summary>Updates</summary>

|Date| Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| --------|---------|
|8/20/24| Updating review code has passed QA and will be released to prod on 8/27/24 
</details>

**Comment by TKDickson** [comment]
This work was done in #9221, closing as duplicate
