### ISSUE TITLE
Incorporate Link Design System Component into the app - Health & Benefits

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#7669]
# Project Status Overview

### Project Objective:

- The Design System team will be creating the Link component as part of department-of-veterans-affairs/va-mobile-library#56.  This Epic covers the Flagship H&B team implementing that new component in the Health & Benefits sections of the app.  The Flagship team will give feedback on the process to the Design System team to help them improve the Design System.

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
|  |   |
|  |   |
|  |   |

</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|May 2024| Green | Following close back and forth with the DS team, we are in the final phases of QA | None
</details>

### Team Members

<details>
<summary>Contact List</summary>

- **OCTO Product Leads:** Rachel Han and Ryan Thurlwell
- **PM:** Rachel Han
- **Ad Hoc PM:** Alayna Abel
- **Engineering:** Jayson Perkins and Jon Bindbeutel
- **Design:** Lauren Russell
- **External Team 1 & Role:**
- **External Team 1 & Role:**

</details>

**Comment by ala-yna** [comment]
@kellylein, two questions:
1) What version of the design system library should we be using for this?
2) Can you add a ticket to remove the old link component, once all Global and H&B pages have been updated?
