### ISSUE TITLE
App headings: Content review from audit

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7677]
The [app headings audit](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4603) has been completed and there are a few headings that need a content review. The full list of audit result can be found [in this Google sheet](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing), but I am listing the headings that need your review below with each heading's location and my reasoning / recommendations.

### App headings to review:
- [x] Row 64: **Manage account** (located within the card on Profile / Settings / Manage account)
     - Brea would recommend slightly altering this heading so that it isn't repetitive. 
     - Misty found that this was a content bug and copy was not aligned with VA.gov. Created [bug ticket 7756](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7756) to address.
- [X] Row 147: **John Smith** (located on Health / Appointments / Details)
     - Brea's not sure whose name this is or why it is a heading. Is this the provider's name?
          - If so, we may want to consider removing the heading tag and adding a heading prior to the name that say "Provider", "Provider name", or "Provider information".
     - Misty believes this is a UX ticket that both her and Lauren should work on together. Noted as such on spreadsheet.
- [X] Row 150: **"MID-V10 CRH MH PSY MD PT [ location name ]"** (located on Health / Appointments / Details)
     - We may want to consider removing the heading tag on the location name and adding a heading above it that says "Appointment location" or "Location".
     - Misty believes this is a UX ticket that both her and Lauren should work on together. Noted as such on spreadsheet.
- [X] ~~Row 169: **Request [number]** (located on Benefits / Claims / Claims history / Claim details / File requests / Request [number])~~
     - ~~We should update the content of this heading since it is a duplicated heading. Alternatively, we could restructure the page so that this heading could be eliminated.~~
     - Determined this one just needs the heading tag removed in code. While it is duplicative content at the moment, this isn't an easy fix. The web CTS team is also working on updates to the tool that may affect if we continue numbering requests or give them actual names.
- [X] Row 180: **File** (located on Benefits / Claims / Claims history / Claim details / File requests / Request [number])
     - Brea recommends updating the content to something like "File name" to be more descriptive for non-sighted users.
     - I created [content bug ticket 7770](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7770) to make heading more accessible to non-sighted users and users with cognitive disabilities.
- [X] Row 181: **Type** (located on Benefits / Claims / Claims history / Claim details / File requests / Request [number])
     - Brea recommends updating the content to something like "File type" to be more descriptive for non-sighted users.
     - I created [content bug ticket 7770](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7770) to make heading more accessible to non-sighted users and users with cognitive disabilities.
- [X] ~~Row 182: **Request [number]** (located on Benefits / Claims / Claims history / Claim details / File requests / Request [number])~~
     - ~~We should update the content of this heading since it is a duplicated heading. Alternatively, we could restructure the page so that this heading could be eliminated.~~
     - Technically a duplicate of 169

**Comment by mistymg** [comment]
Pulling into this sprint
