### ISSUE TITLE
Incorporate Design System Link Component - Health

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#7687]
Related to: https://github.com/department-of-veterans-affairs/va-mobile-library/issues/240
```[tasklist]
### Tasks
```

**Comment by alexandec** [comment]
Noticed this is blocked by a ticket to create the Link component. Probably we'll need to wait until that is completed to proceed.

**Comment by alexandec** [comment]
The Link component now exists and is usable, so this ticket is unblocked.

**Comment by alexandec** [comment]
Note for QA, here are the screens affected by the change.

Switch to the Link component in the following components:
screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber
screens/HealthScreen/Appointments/NoAppointments/NoAppointments
screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails
screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo
screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails
screens/HealthScreen/CernerAlert/CernerAlert
screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistory
screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized
screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails
screens/HealthScreen/SecureMessaging/CernerAlertSM/CernerAlertSM
screens/HealthScreen/SecureMessaging/NotEnrolledSM/NotEnrolledSM
screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineScreen
screens/HomeScreen/VeteransCrisisLineScreen/VeteransCrisisLineNumbers/VeteransCrisisLineNumbers

Also switch to the Link component for all phone/TTY numbers (except on Veteran Status screen):
components/WaygateWrapper
components/CommonErrorComponents/CallHelpCenter
screens/BenefitsScreen/ClaimsScreen/NeedHelpData/NeedHelpData
screens/BenefitsScreen/ClaimsScreen/NoClaimsAndAppealsAccess/NoClaimsAndAppealsAccess
screens/BenefitsScreen/DisabilityRatingsScreen/DisabilityRatingsScreen
screens/BenefitsScreen/Letters/NoLettersScreen/NoLettersScreen
screens/HealthScreen/Appointments/AppointmentDetailsCommon/AppointmentAddressAndNumber
screens/HealthScreen/Appointments/NoMatchInRecords/NoMatchInRecords
screens/HealthScreen/Appointments/PastAppointments/PastAppointmentDetails
screens/HealthScreen/Appointments/UpcomingAppointments/AppointmentCancellationInfo
screens/HealthScreen/Appointments/UpcomingAppointments/UpcomingAppointmentDetails
screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionDetails
screens/HealthScreen/Pharmacy/PrescriptionDetails/PrescriptionsDetailsBanner
screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNoPrescriptions
screens/HealthScreen/Pharmacy/PrescriptionHistory/PrescriptionHistoryNotAuthorized
screens/HealthScreen/SecureMessaging/ReplyHelp/ReplyHelp
screens/HealthScreen/SecureMessaging/ViewMessage/IndividualMessageErrorComponent
screens/HealthScreen/Vaccines/NoVaccineRecords/NoVaccineRecords
screens/HomeScreen/ContactVAScreen/ContactVAScreen
screens/HomeScreen/ProfileScreen/MilitaryInformationScreen/IncorrectServiceInfo/IncorrectServiceInfo
screens/HomeScreen/ProfileScreen/PersonalInformationScreen/HowDoIUpdateScreen/HowDoIUpdateScreen
screens/PaymentsScreen/DirectDepositScreen/DirectDepositScreen
screens/PaymentsScreen/DirectDepositScreen/HowToUpdateDirectDepositScreen/HowToUpdateDirectDepositScreen
screens/PaymentsScreen/PaymentHistory/NoPayments/NoPaymentsScreen
screens/PaymentsScreen/PaymentHistory/PaymentIssueScreen/PaymentIssueScreen
screens/PaymentsScreen/PaymentHistory/PaymentMissingSceen/PaymentMissingScreen

**Comment by rbontrager** [comment]
@alexandec Most everything looks good but there are a couple instances where the icon size is causing text to run off the screen. Icons need to be capped at 24x24 for text resizing purposes.

**Comment by alexandec** [comment]
@rbontrager I've add a fix that patches the Link component to allow  `preventScaling: true` to be passed in. Then I modified the LinkWithAnalytics wrapper component to always pass that option. So all link icons should no longer scale.

Link to the relevant thread just for context: https://adhoc.slack.com/archives/C067S0FRP0C/p1712157857536259

**Comment by alexandec** [comment]
Based on instructions from Design Systems in the above Slack thread, I've removed the patch and upgraded to the beta version of @department-of-veterans-affairs/mobile-component-library. Now we can QA with that beta version instead.

**Comment by alexandec** [comment]
QA found an additional issue with the Link component: the icon was misaligned when text was scaled. Once both issues are fixed, Design Systems can release a new final version of the Link component, which we can incorporate into our PR. Then we can perform QA again to ensure no issues. For now we need to keep this ticket open, as well as #7688 which is the followup to this one.

**Comment by alexandec** [comment]
Relevant design system bug ticket is department-of-veterans-affairs/va-mobile-library#240

**Comment by alexandec** [comment]
I bumped up the mobile-component-library version to 0.12.1-beta.1 because Design Systems implemented another fix. More QA is happening to check the fix

**Comment by rbontrager** [comment]
Messages was missing the new attachments link.  Chris has added those in as well.

**Comment by rbontrager** [comment]
Verified the following for screens affected by this change (given by Chris in a comment above):
- Link icons line up with what is expected from the design system library
- Links work as they did before
- A11y checks (text resizing, voiceOver/talkback, keyboard, landscape/portrait, color contrast, light mode/dark mode) look good.  Note: Lauren signed off in a DM on the link icons for iOS on the maximum settings
- Analytics work as expected
- Detox tests are passing

Approved by QA

**Comment by alexandec** [comment]
Merged the PR with mobile-component-library version 0.12.1
