### ISSUE TITLE
Debts discovery work

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7692]
Investigate existing debts service and create integration tickets available endpoints

**Comment by aherzberg** [comment]
verified services are active and stable. https://dsva.slack.com/archives/CPE4AJ6Q0/p1705595148836839

**Comment by aherzberg** [comment]
tickets created: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7747

https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7748

https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7749

https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7750
