### ISSUE TITLE
Review of Demo Mode - ID what is missing / not working as expected

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7699]
**Description:** 
As VAHB QART team, I want to review existing demo mode to see what features/functionality is currently missing or not working as expected in production, so that we can determine if additional demo changes / inclusion are needed. 

**Info:** 
- Requested by Matt on 1/12 as we make Demo mode updates an MVP requirement
- Likely going to see limitations due to data 
- Looking to put together an inventory type list for us to review 

**ACs:** 
- Create a list of items not working or appearing in demo mode 
- If possible identify the rationale

**Comment by bischoffa** [comment]
<img width="505" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2NLQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a0318eb47fc3c825d4707ad034a4c94bf5ee39d/image.png" alt="image.png" />

**Comment by DJUltraTom** [comment]
Started side by side comparison today (7/25)

**Comment by DJUltraTom** [comment]
Demo mode is looking pretty solid at the moment, and has parity with production builds:
Only issues I noted are:
no saved data for:
- direct deposit
- preferred name (is there intention to have this preferred name appear anywhere in the app?)

Aesthetic improvements (no functionality issues)
- mail in messages is all from 2021
- payment history is from 2016/17

@bischoffa I'm closing this ticket but if any of the above warrants changes to demo mode we can create corresponding tickets for these changes

**Comment by bischoffa** [comment]
Created ticket 9205 with these findings so we can get demo mode updated or at least review findings and determine if we should.

**Comment by bischoffa** [comment]
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9205
