### ISSUE TITLE
BUG - sev-3 - All - Haptics demo screen broken/doesn't launch

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7700]
## What happened?

Going to Profile > Settings > Developer Screen and attempting to launch the Haptics Demo screen - button does the 'tapped' animation but nothing else happens. Screen does not load, you stay on the dev screen page.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

According to Feb 2024 informal surveys of the QA and FE teams, we don't use/need the 'Haptics Demo' or 'Sandbox' options on the developer screen anymore.

I'd recommend removing those buttons & screens from the app. And up to the engineer about whether that's deleting vs commenting out/archiving in some way.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Bug scrub rotation - I think (rather than fixing haptics demo) we could likely remove/comment it out. Asking around to figure out if there other things in the dev screen menus we could do the same with.

**Comment by TKDickson** [comment]
Confirmed QA team doesn't need this, or the 'sandbox' option. Checking with FE.

**Comment by TKDickson** [comment]
Same from FE team. Updating the desired behavior in the ticket above.

**Comment by theodur** [comment]
There's not really much to QA here, but I removed the `HapticsDemo` and `Sandbox` screen from the app, so you'd probably just need to confirm that you don't see those screens anymore and that the `Developer` screen loads as normal @TKDickson

**Comment by TKDickson** [comment]
<img width="410" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN28yQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26772a7ee718142e0596fe7a6343bb8b7024e7c/image.png" alt="image.png" />
Success

**Comment by TKDickson** [comment]
No further checks needed in develop, closing
