### ISSUE TITLE
BUG - SEV 3 - All - Decision letter copy not aligned with web

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7715]
## What happened?

When a Veteran can access a new decision letter in claims, we use the tag component to tell the Veteran such. We use the copy "Decision letter available". But I learned the web side is using the word "ready" instead of "available". I'd like to have us align with web in this instance for this copy and change the word "available" to "ready".

## Specs:

n/a

## Desired behavior

We want copy to be more aligned with web to reduce confusion/cognitive load and maintain trust with Veterans. When a Veteran has a new decision letter they can access, the tag component should read "Decision letter ready".

## Acceptance Criteria

- [ ] Copy for tag when Veteran has new decision letter reads "Decision letter ready"

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
- Impact: Low 
- Frequency: Low 
- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
@alexandec This breaks the claims detox test. I believe all you will need to change is the 'Closed_Claim_Decision_Letter_ID' constant to match the new wording.

**Comment by alexandec** [comment]
@rbontrager Thanks, I've updated the constant.

**Comment by rbontrager** [comment]
Verified that the decision letter bubble now says 'Decision letter ready' on iOS and Android. Verified that the detox tests pass.  Approved by QA.
