### ISSUE TITLE
CU - Claims screens need to be updated to our coding standards

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7724]
These screens are outdated and need to be updated to our current coding standards

AC:

Functionally nothing should changed, but the codes should be cleaner, more optimized and easier to read

**Comment by rbontrager** [comment]
@DJUltraTom Ran the Claims e2e test with no issues.

**Comment by DJUltraTom** [comment]
went through claims screens with no issues.
QA approves this change

**Comment by DJUltraTom** [comment]
verified claims screens loads and functions as expected on overnight QA dev build.
Closing as "deployed"
