### ISSUE TITLE
CU - Appeals screens need to be updated to our new coding standards

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7725]
These screens are outdated and need to be updated to our current coding standards

AC:

Functionally nothing should changed, but the codes should be cleaner, more optimized and easier to read

**Comment by DJUltraTom** [comment]
@alexandec for QA, should an appeals run through suffice to validate nothing  changed? any areas you think we should exercise more than others?

**Comment by alexandec** [comment]
@DJUltraTom yep, that should do it. Specifically AppealCurrentStatus, AppealTimeline, and AppealPhase.

**Comment by DJUltraTom** [comment]
Not sure if this is related but when I go to demo mode and select the first cancelled appointment I get the following:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3NUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be06ebd5c22089ca181081c2b612b0f197f8467f/Screenshot_20240130-190319.png" alt="Screenshot_20240130-190319.png" />

**Comment by alexandec** [comment]
@DJUltraTom this branch doesn't touch appointments so it must be from some other change. I'm seeing the same thing in the develop branch.

**Comment by alexandec** [comment]
@Sparowhawk could this be related to the appointments stuff you've been working on?

**Comment by DJUltraTom** [comment]
@alexandec you are totally correct this isn't the appointments code. my bad.
all of the claims and appeals screens seem to load correctly on this build QA approves

**Comment by DJUltraTom** [comment]
verified appeals screens load and function as expected on overnight QA dev build.
Closing as "deployed"
