### ISSUE TITLE
Migrate vaccineSlice to React Query

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7735]

**Comment by rbontrager** [comment]
@Sparowhawk I don't know if anything can be done but the loading times to view the vaccine details has increased dramatically from around 1-2 sec to over 10 seconds.

**Comment by rbontrager** [comment]
Verified that the vaccine functionality has stayed the same with the move to react query. Verified that the loading times for the vaccine details are back to 1-2 seconds.  Approved by QA.
