### ISSUE TITLE
Migrate secureMessagingSlice to React Query

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7736]

**Comment by rbontrager** [comment]
@Sparowhawk Couple issues. 
1. Attachments aren't appearing in message cards and message threads in the inbox or any of the folders. 
2. If you go into any of the folders (drafts/sent/my folders) and without selecting a message, select to go back its going to the inbox and not back to folders.  
3. Messages aren't showing up as read in the inbox after clicking an unread message

**Comment by rbontrager** [comment]
@Sparowhawk Still a couple issues:
1.  While the attachments are appearing in the message card you can't click on them to open/preview them
2.  Attachments still aren't appearing in the message threads
3.  I'm still seeing the blue unread indicator in the inbox if I open an unread message and back out to the inbox.  It will only show up as read if you completely back out of messages and go back in.

**Comment by rbontrager** [comment]
Still seeing issue #3 above so moving back to in progress.

**Comment by rbontrager** [comment]
@Sparowhawk Binny/Theo seems to have fixed #3.  I've found a couple more issues including a couple I discussed with Binny but weren't fixed yet

1. There is an issue with threading. Specifically
    - The 'Messages in this conversation' section in the reply screen is missing the message thread 
    - If the user opens up a new message, replies, and navigates back to review message the reply isn't appearing in the message thread
2. The 'Triage team does not exist' error is popping up when you edit a reply, cancel, and try to save to draft on all messages.  Its also appearing when you try to edit a draft in the draft folder. I can confirm that this isn't happening when manipulating the same messages in the latest RC.
3. Pressing undo after moving a message does not move it back to the inbox
4. Is there a reason that there are 100 messages on the first page when the rest of the pages are defaulting to 10

**Comment by rbontrager** [comment]
@Sparowhawk 
- Still seeing the issue outlined in the second bullet point of issue 1 above (where if the user opens up a message and replies to the message, the reply isn't appearing in the message thread).  
- Same thing that was happening with pagination (where its not navigating to the top of a page on a page that has already been pagination through) that I saw with appointments

**Comment by Sparowhawk** [comment]
fixed

**Comment by rbontrager** [comment]
Thread is still only half working.  If the user replies to a message that hasn't had a reply before it still isn't starting the thread and showing it in the message card.  It does work if the message has been replied to before.

**Comment by Sparowhawk** [comment]
fixed

**Comment by rbontrager** [comment]
Hopefully final couple errors @Sparowhawk 

- Hitting refresh in the error screen isn't working
- Same issue as above (where you can't save to a draft). This is working for the 'save' option but is not working for the save option in the cancel menu. I've outline steps about how to reproduce below
        - Press 'start new message', edit the required fields, press 'cancel', tap 'save'
        - Open a message and press 'reply', edit the required fields, press 'cancel', tap 'save'
        - Navigate to the draft folder and select a message, edit the message, press 'cancel', tap 'save'

**Comment by Sparowhawk** [comment]
so for the refresh error part that either requires https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8454 to be merged first, or would be fixed with this ticket

**Comment by Sparowhawk** [comment]
added the missing line of code from the regular save button to the cancel alert save button. Hopefully that works otherwise I will need to make additional changes

**Comment by Sparowhawk** [comment]
Ok I think the scenarios are now fixed. I found the issue was that the recipient ID was being over ridden with undefined or a bad ID and would likely be causing the error

**Comment by rbontrager** [comment]
@Sparowhawk We found an additional issue with how the screen is transitioning on your latest code. Its no longer using the 'saving your draft' transition screen or the correct transition slide. 
Old:
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFNnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad8d2c5aa1a85e13be7892fdeb784d8f5817f8d6/Screen%20Recording%202024-04-29%20at%201.25.10%E2%80%AFPM.mov)

New:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFdnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f94c2ff45bad5bd0217834f2971374a30c2ad21/Screen%20Recording%202024-04-29%20at%201.13.27%E2%80%AFPM.mov)

**Comment by rbontrager** [comment]
@Sparowhawk Binny fixed the issue above.  I was re-running my the passed test cases (because over 20 days and a lot of changes have occurred) and noticed that the retry snackbar is not appearing when a message/reply fails to send.

**Comment by Sparowhawk** [comment]
fixed. there was a check for SM129 as the error code for error snackbars to appear. That was incorrect as SM129 should have an alert, not a snackbar. I have updated it accordingly for all 3 offending screens.
