### ISSUE TITLE
Migrate claimsAndAppealsSlice to React Query

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#7742]

**Comment by rbontrager** [comment]
@Sparowhawk Couple issues found:
1. The file request screen is not immediately updating as completed after you go through the steps of adding photos/files.  See [example](https://drive.google.com/file/d/1QThZWarGwD9A6aIQhrNj0YGZKPqu7nJG/view?usp=drive_link)
2. The claim itself is not updating and showing that step 3 has been done when go through the steps to ask for your claim evaluation
3. Pagination is broken again in demo mode for claims/appeals.  I changed the detox test to work with pagination so its breaking some of the detox tests.
4. The claims history list is not loading as it was before when you tap to go to the next page. Before it was showing a brief 'loading your claims and appeals' page with the loading icon before populating everything on the new page together. Now it is immediately showing everything above 'your active claims and appeals' and populates the list of claims/appeals a few seconds after. See ([example](https://drive.google.com/file/d/1QSWEsbVL2grS8f8Mhjk0Alw5eiUXajJZ/view?usp=drive_link).

**Comment by rbontrager** [comment]
@Sparowhawk Still seeing 1 and 2 (might even be worse) and pagination is still broken on demo mode.  The 4th point is fixed though.

**Comment by rbontrager** [comment]
@Sparowhawk It looks like there may be another refresh issue going on. When you request a claim evaluation it correctly match the screenshot below.  If you go back to claim history and then select the claim again it will again say there are open file requests which is incorrect.  The page eventually goes back to correctly match the screenshot. 

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHdEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a12fc73221f0a7a7af8678a8f4f752f38d8e16a6/IMG_0018.PNG" alt="IMG_0018.PNG" />
