### ISSUE TITLE
BUG - SEV 3 - ALL - Settings copy inconsistent with VA.gov

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7756]
## What happened?

Out of the app headings audit, it was recommended to change the heading on the "Manage account" screen so that there were not 2 heading says the same thing. But after reviewing VA.gov, I noticed this copy is just incorrect.

## Specs:

I reviewed this content bug in demo mode but the bug should be corrected everywhere, not just demo mode.

## Steps to Reproduce

From Home screen,
Tap Profile
Tap Settings
Tap Manage account

## Desired behavior

This copy should mirror what is on VA.gov so as not to confuse users. Screenshot of current VA.gov below. _Note: I'm not suggesting yet that we add a link to send users to the account website. That can be addressed in another ticket. For now, I just want to align copy where appropriate in the app._
<img width="606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNURnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d1b51815b3263f95e67c2d058e120be48438240/Screenshot%202024-01-19%20at%2010.07.54%E2%80%AFAM.png" alt="Screenshot 2024-01-19 at 10.07.54 AM.png" />

## Acceptance Criteria

- [x] "Manage account" role on Settings screen now reads "Account security"
- [x] Screen title on current "Manage account" screen now reads "Account security"
- [x] Current "Manage account" header now reads "Sign-in information"
- [x] Body copy now reads "To access or update your sign-in information, go to the website where you mange your account information. Any updates you make there will automatically update on the mobile app."

## Bug Severity
- Impact: Low 
- Frequency: Low 
- 3 - Low

## Before screenshots

Screenshots of areas addressed in ACs
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHZnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7194d486831d2d7defe7448a0cef06e017adc8d1/IMG-0189.jpg" alt="IMG-0189.jpg" />
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDNnQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2502564b443d130227e513e243fbd9243a627aee/IMG-0190.jpg" alt="IMG-0190.jpg" />

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Removing blocked, this is one of the three I'll work on

**Comment by TKDickson** [comment]
Confirmed the content changes in the app. This would have broken detox, so I committed the changes I think are needed to @dumathane 's branch, and am running the Settings Screen script to see if they were the correct ones.

**Comment by TKDickson** [comment]
Alright, there's a bug that prevents the (passing) settings screen tests from showing up, but the fact that they're NOT here means they all pass.

So this should be good to merge, will go sign off on the PR.

**Comment by TKDickson** [comment]
No testing in develop needed
