### ISSUE TITLE
BUG - SEV 3- ALL - More descriptive heading copy for submitted file requests (Claims)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7770]
## What happened?

Out of the app headings audit, we found that several headings were not descriptive enough for non-sighted users on the details screen of a submitted file request in claims.

## Specs:

I reviewed this content bug in demo mode but **the bug should be corrected everywhere, not just demo mode.**

## Steps to Reproduce

From the Home screen in demo mode, 
Tap Benefits tab
Tap Claims
Tap Claims history
Tap Claim for compensation updated on May 05, 2021
Tap Review file requests
Tap Request 5

## Desired behavior

The copy for these headings should be more descriptive for non-sighted users as well as users with cognitive disabilities.

## Acceptance Criteria

- [ ] "fileRequestDetails.fileTitle" string now reads: "File type"
- [ ] "fileRequestDetails.submittedTitle" string now reads: "Submitted on"
- [ ] "fileRequestDetails.typeTitle" string now reads: "Request type"

Note: I'll leave it up to Engineering if the variable name should change to match the new copy.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
- Impact: Low 
- Frequency: Low 
- 3 - Low

## Screen shot(s) and additional information

<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e9912c76b77c02a6324d466f9038dce3e7ee94c/unnamed.jpg" alt="unnamed.jpg" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [X] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Verified that the file request details headers have been changed to "File type", "Submitted on", and "Request type" on iOS and Android.  Approved by QA.
