### ISSUE TITLE
BUG - sev-2 - All - XL-specific, Claims: no longer calling claims API on second page in list

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7779]
## What happened?

Current behavior in the app:

Go to home screen --> calls claims overview API
Go to claims list --> calls claims overview API
Go to second page of claims list --> does NOT call claims overview API (this is the problem, because we change the UI of the page to say it's the second page of claims but still show all of the first page of claims in the list)
Go to third page of claims list --> calls claims overview API (and correctly show third page of claims data)

I have confirmed this is only present in the XL home screen branch (not develop), so I'm guessing I missed it when testing #7485.

## Specs:

- Device:
- OS:
- User Account: +54
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
This issue is only present in the home screen XL (not develop), hence why it's assigned to global instead of health and benefits.

**Comment by TKDickson** [comment]
Getting correct return on claims for home screen, and also on each page of a multi-page list (upcoming, which was impacted; and past, which shouldn't have ever been but I looked at anyways). I also couldn't remember if I originally checked pagination in appointments (which also has fetching & caching things happening throughout the app), so double-checked that and past & upcoming appointments are still totally fine.

Good to merge to XL.

**Comment by theodur** [comment]
Merged this into the XL branch ✅
