### ISSUE TITLE
BUG - sev 2 - all - Secure messaging - editing a draft does not return to folder message list

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#7781]
## What happened?

Using secure messages, if you save a draft and then go to edit the draft, Saving the draft will loop you back to the draft page and you cannot exit the draft unless you delete the draft

## Specs:

- Device: ipad, pixel 4a
- OS: iOS android
- User Account: any with SM enabled
- Accessibility State: n/a

## Steps to Reproduce

on an account with Secure messaging enabled navigate to messages
- create a new message
- fill out required fields and "save draft"
- navigate to the drafts folder
- open the draft you just saved, 
- edit the draft and try to save it
- observe you are returned to the draft  (banner reads message was saved)
- attempt to leave the draft screen
- observe the only way to exit is by deleting the draft

## Desired behavior

after saving the draft user should be returned to message list in draft folder

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Verified that editing and saving a draft returns the user to the folder message list.  Approved by QA.
