### ISSUE TITLE
Investigate Issues Related to: EVSS API LH (Letters)

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#7785]
## Description 

In this story, we want to investigate the following issues noted below as it relates to the the flip (feature toggle switch on) for EVSS LH (Letters). We want to confirm that (1) the Issues still exists (2) Note if  if a solution is possible on the mobile side or Best resolved on the VA side

**Issue 1 Noted in Ticket**: [7119](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7119)

**Issue 2,** Noted from Jacob Worrell (VA team): 
**Note: Jan (2024)** 

- We have a recent issue to deal with before we can use the LH evidence service. We need to figure out if it can accept evidence submissions from users who DO NOT have a BIRLS ID. If not, we will need to implement our own interim solution to stop silent failures from happening for CST users that receive evidence requests from VA but who cannot submit evidence through CST. Just want you to be aware of that.This is also going to be an issue for you guys
and probably already is whether you know it yet or not

- We have users without BIRLs IDs who are able to see claim status details via LH end points right now
And these users are currently getting silent failures when they think they're submitting evidence, it's a bad situation we're prioritizing fixing and by "we" I mean multiple cross-functional teams

- 

## Acceptance Criteria
  

-  [ ] Investigate/Confirm the above noted errors
-  [ ] If a solution is possible, note possible implementation routes that we can plan for estimation

**Comment by StacyB2023** [comment]
@jperk51 : Let me know if this ticket needs more detail. Tried to be as basic as possible since we are just confirming the issues here

**Comment by aherzberg** [comment]
For Issue 1: I got an update from the benefits team "At this point we aren’t sure, we are waiting for someone to determine who is responsible for actually dealing with submissions that are accepted by LH but fail to get into the efolder at this point. ". The logic change needs to happen between LH and efolder, that's far enough away from mobile logic that there's nothing we can do to solve the issue on our side.  

For Issue 2: see convo https://dsva.slack.com/archives/C02CQP3RFFX/p1707410776546399. received date is now being populated and the other two fields that are not were explained to me why they aren't necessary to populate
