### ISSUE TITLE
UX: Replace buttons with links on claims screens

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7794]
The following list are the updates that need to be made to buttons in the claims screens. All of these buttons need to be links, so UX should weigh in before ENG makes updates to the code.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [ ] **Get claim letters**
     - **Location:** Benefits / Claims / Claims history (Closed) / Claim details
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** N/A
     - **What happens?** Navigates to Claim letters screen
     - **Recommended change:** Should be a link not a button (assume button was chosen for increased visibility to user)
- [ ] **Review file requests**
     - **Location:** Benefits / Claims / Claims history / Claim details
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** N/A
     - **What happens?** Redirects you to the file requests page
     - **Recommended change:** Should be a link not a button
- [ ] **Request 1, 2, etc.**
     - **Location:** Benefits / Claims / Claims history / Claim details / File requests
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Right
     - **What happens?** Redirects to the individual request's child screen
     - **Recommended change:** Should be a link not a button
- [ ] **Review evaluation details**
     - **Location:** Benefits / Claims / Claims history / Claim details / File requests
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** N/A
     - **What happens?** Displays claim evaluation details in the subtask screen
     - **Recommended change:** Should be a link not a button

**Comment by wavelaurenrussell** [comment]
Apply the [found workaround](https://adhoc.slack.com/archives/C0212B872MT/p1710173300254359?thread_ts=1709586531.321009&cid=C0212B872MT) to read visual button as a link.

**Comment by brea11y** [comment]
Closing. Resolved in claims work.
