### ISSUE TITLE
Content: Review link in claims help

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7795]
Misty, the following link was found during our buttons + links audit last quarter. I thought you'd like to take a look.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

- [x] **Learn about your decision review options.**
     - **Location:** Benefits / Claims / Claims history / Claim details / Status / What should I do if I disagree with VA's decision on my disability claim?
     - **Current component type:** Link
     - **Current style:** Tertiary
     - **Icon:** N/A
     - **What happens?** Launches the "you're leaving the app" native alert 
     - **Recommended change:** This link copy is inconsistent with the rest of the links in our app. We do not typically include an entire sentence as the link copy. Misty should review.

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2IyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5810f17d26fb83c6b6c4eae65b97ca8043fa5fb/IMG_2427.PNG" alt="Screenshot of the claims help panel in the VA Mobile app" />

**Comment by mistymg** [comment]
Set up time to chat with Brea on Friday 2/2 about what's needed here or what the concern is.

**Comment by mistymg** [comment]
Met with Brea to groom ticket. Pointing as 1.
