### ISSUE TITLE
ENG: Update links on main Health screen

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7799]
The following links on the main health screen within the app need updates.
_This has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

- [ ] **Go to My VA Health**
     - **Location:** Health
     - **Current component type:** Link
     - **Current style:** CTA Link (with icon)
     - **Icon:** Right Arrow
     - **What happens?** Launches the "you're leaving the app" native alert 
     - **Recommended change:** We should align the icons to be the same for all external links and consider a descriptive icon. _We recommend replacing this with the external link icon._
- [ ] **Ok**
     - **Location:** Health / Go to My VA Health alert
     - **Current component type:** Button
     - **Current style:** Secondary
     - **Icon:** N/A
     - **What happens?** Opens My VA Health in the device's browser
     - **Recommended change:** Does not alert the user that My VA Health will open in the device's browser.

**Comment by Sparowhawk** [comment]
this was updated when we migrated to the link component from the design system team
