### ISSUE TITLE
ENG: Update buttons and links on Appointments screens

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7800]
The following list are the updates that need to be made to buttons and links on appointment screens within the app.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [ ] **Go to My VA Health**
     - **Location:** Health / Appointments
     - **Current component type:** Link
     - **Current style:** CTA Link (with icon)
     - **Icon:** Right Arrow
     - **What happens?** Launches the "you're leaving the app" native alert 
     - **Recommended change:** We should align the icons to be the same for all external links and consider a descriptive icon. _We recommend replacing this with the external link icon._
- [ ] **Get directions**
     - **Location:** Health / Appointments / Details
     - **Current component type:** Link
     - **Current style:** CTA Link (with icon)
     - **Icon:** Directions
     - **What happens?** "You're leaving the app" functionality – opens in device's default map / directions app 
     - **Recommended change:** This is an action and should be a button (may need UX to weigh in on this if a style update would occur).
- [ ] **Ok**
     - **Location:** Health / Appointments / Go to My VA Health alert
     - **Current component type:** Button
     - **Current style:** Secondary
     - **Icon:** N/A
     - **What happens?** Opens My VA Health in the device's browser
     - **Recommended change:** The accessibility label does not indicate that this will launch in your device's browser. This should be updated.

**Comment by Sparowhawk** [comment]
completed with our appts feature-xl branch and migrated to use the design library components
