### ISSUE TITLE
UX: Make recommendation for button on Start New Message screen

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7802]
While performing the buttons and links audit in quarter 3, we ran across the following button that needs a UX recommendation. It does not align with other link styles in the app that are typically used to launch a full panel.
_This has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [ ] **Only use message for non-urgent needs**
     - **Location:** Health / Messages / Start new message
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Down
     - **What happens?** Launches the messages help panel
     - **Recommended change:** Should be a link not a button and does not follow our link panels. This is an additional information component (expand / collapse), but launches a panel instead of expanding.

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXYyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--755f5c38c6632b443cb7997feb164d9e6ee032bb/IMG_2430.PNG" alt="Screenshot of the start new message screen with a button that says only use message for non-urgent needs" />

**Comment by wavelaurenrussell** [comment]
Solution: Replace with current Link component, omit Additional Info Row component.

**Comment by rbontrager** [comment]
@Sparowhawk There are quite a few instances of 'only use messages for non-urgent needs' that you missed turning into a link.  These include the following:
- Messages > Edit Draft
- Message > Review message/Message card
- Message > Reply to message

**Comment by Sparowhawk** [comment]
ah, that would be because I went off the title of the ticket specifically talking about the start new message screen

Adjusting those now too

**Comment by Sparowhawk** [comment]
@rbontrager Updated

**Comment by rbontrager** [comment]
Verified that all instances of 'only use messages for non-urgent needs' have been updated to a link in messages. Approved by QA.
