### ISSUE TITLE
UX: Make recommendation for "remove" link on Start New Message screen

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7804]
While performing the buttons and links audit in quarter 3, we ran across the following link that needs a UX recommendation. Since "remove" is an action and not a way to navigate, this link should actually be a button.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [ ] **[Attachment File Name] Remove**
     - **Location:** Health / Messages / Start new message
     - **Current component type:** Link
     - **Current style:** Tertiary
     - **Icon:** Circled X
     - **What happens?** Shows Remove Attachment action sheet
     - **Recommended change:** This is an action, so this should be a button.

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWYyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94093554ead0b9d404aacb380781d6854c683f26/IMG_2429.PNG" alt="Screenshot of the start new message screen with an attachment included" />

**Comment by alexandec** [comment]
@wavelaurenrussell one note here is that the user can attach multiple files:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL095QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--beaf0e2d25471c692fed381dd79710a9593503af/Simulator%20Screenshot%20-%20iPhone%2013%20-%202024-03-05%20at%2009.24.30.png" alt="Simulator Screenshot - iPhone 13 - 2024-03-05 at 09.24.30.png" />

Should we place the destructive Remove button beneath each file in the list? And do we need spacing or another indication about which file belongs to which Remove button?

**Comment by alexandec** [comment]
@wavelaurenrussell here's how it looks swapping out the old Remove link and putting in a destructive button instead, with no other layout changes:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDZ6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60c544296b292d2423cb438cd1eb1f438a3e93a1/Simulator%20Screenshot%20-%20iPhone%2013%20-%202024-03-05%20at%2010.12.38.png" alt="Simulator Screenshot - iPhone 13 - 2024-03-05 at 10.12.38.png" />

**Comment by rbontrager** [comment]
Verified that the remove link for attachments in messages has been changed to a button and the associated a11y tests work.  Approved by QA.
