### ISSUE TITLE
UX: Make recommendation for "Go to inbox" button

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7806]
While performing the buttons and links audit in quarter 3, we ran across the "go to inbox" button in the secure messaging area (appears to only be within empty folders). Since this is a way to navigate to the inbox and is not used to perform / complete an action, this should be a link and not a button.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

If possible, you may discuss with ENG whether it is feasible to simple switch out how this button is coded rather than changing the appearance of the "button" itself.

### Detailed information:
- [ ] **Go to inbox**
     - **Location:** Health / Messages / Folders / Empty folder
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** N/A
     - **What happens?** Redirects you to the messages inbox
     - **Recommended change:** Should be a link not a button

**Comment by wavelaurenrussell** [comment]
Recommendation: Have [Go to inbox] button read as a link.

**Comment by alexandec** [comment]
@wavelaurenrussell I tried a variety of ways to change the accessibility role of this button to be "link" instead of "button". But regardless of what I tried, the screen reader still reads the role as "button". More specifically, the design system's Button component has a role of "button" and does not support modifying that role. Wrapping the Button component in another component with the "link" role did not work.

I would recommend we actually change this button into a link, so it both displays and reads as a link. Would that approach work for you from a design perspective?

**Comment by wavelaurenrussell** [comment]
@alexandec Yes that works. I can provide a design, and this will also lead to another discussion re links and their associated icons. Will probably result in an additional ticket, but can we discuss at 3/5 dsu?

**Comment by wavelaurenrussell** [comment]
Per standup, @alexandec and I will work on making a recommendation for the link component, starting with styling this button as a link.

**Comment by wavelaurenrussell** [comment]
Top level decision pasted below. Background available in this [Slack thread between designers](https://adhoc.slack.com/archives/C01NC7PN4A0/p1709663778269489).
![7806-internal-external](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/156008783/5df669fb-7883-441b-a139-9f3db3d67c4c)

**Comment by wavelaurenrussell** [comment]
We're electing to make these the [default style](https://department-of-veterans-affairs.github.io/va-mobile-library/?path=/story/link--default), and eliminating the icon for internal links.

**Comment by rbontrager** [comment]
@wavelaurenrussell The 'go to inbox' link looks like the following for alert boxes.  Should it be left aligned/have paragraph spacing now that its a link etc? 

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG5OQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b324400a4da141c288aac5176d290ad85adce3c8/IMG_0067.PNG" alt="IMG_0067.PNG" />

**Comment by wavelaurenrussell** [comment]
Yes, please left align this link.

**Comment by alexandec** [comment]
Here's how it will look:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b810ff2c6e4650395718c268dac543f28e71405/Simulator%20Screenshot%20-%20iPhone%2013%20-%202024-03-11%20at%2014.30.08.png" alt="Simulator Screenshot - iPhone 13 - 2024-03-11 at 14.30.08.png" />

**Comment by alexandec** [comment]
Updated the alignment and spacing for all the "Go to inbox" links

**Comment by wavelaurenrussell** [comment]
Looks good thank you

**Comment by rbontrager** [comment]
Verified that the 'go to inbox' button in SM is now a link.  Verified that the spacing and alignment for the link in error messages looks good.  Approved by QA.
