### ISSUE TITLE
UX: Make recommendation for "Start refill request" button

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7808]
While performing the buttons and links audit in quarter 3, we came across the "Start refill request" button in the Rx area. Since this button is actually a way to navigate to the screen where the prescriptions needed to be refilled can be selected and not the actual "request refill" (to submit the request) action to submit the request, this should be a link.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

If possible, you may discuss with ENG whether it is feasible to simple switch out how this button is coded rather than changing the appearance of the "button" itself.

### Detailed information: 
- [ ] **Start refill request**
     - **Location:** Health / Prescriptions
     - **Current component type:** Button
     - **Current style:** Primary
     - **Icon:** N/A
     - **What happens?** Redirects to the refill request subtask screen 
     - **Recommended change:** Should be a link not a button

**Comment by wavelaurenrussell** [comment]
Read [Start refill request] as a link

**Comment by alexandec** [comment]
@wavelaurenrussell I did some additional experimenting and I think I've found a way to force a button to be read as a link. Would you like me to try that here, or should I change the button into an actual link?

**Comment by wavelaurenrussell** [comment]
Yes, let's do the technique of keeping the button and changing the role here.

**Comment by rbontrager** [comment]
Verified that talkback now reads the start refill request as a link and not as a button.  Approved by QA.
