### ISSUE TITLE
UX: Make recommendation for "Go to all pending refills" button

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7809]
While performing the buttons and links audit in quarter 3, we came across the "Go to all pending refills" button in the refill Rx summary area. Since this button is actually a way to navigate and not an action, it should be a link.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._

If possible, you may discuss with ENG whether it is feasible to simple switch out how this button is coded rather than changing the appearance of the "button" itself.

### Detailed information:
- [ ] **Go to all pending refills**
     - **Location:** Health / Prescriptions / Refill request summary
     - **Current component type:** Button
     - **Current style:** Secondary
     - **Icon:** N/A
     - **What happens?** Navigate to Prescriptions screen, but with Pending tab selected and "Start refill request" button hidden
     - **Recommended change:** Should be a link not a button

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelQzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519b0f81c29ebe0d1984f6c9f5c3c0f1069f3561/IMG_2431.PNG" alt="Screenshot of the prescription refill summary page with a button that says go to all pending refills" />

**Comment by wavelaurenrussell** [comment]
Recommendation: Have the SR read [Go to all pending refills] as a link

**Comment by rbontrager** [comment]
Verified that the go pending refill buttons now says <go to all pending refills link> in talkback/voiceOver.  Approved by QA.
