### ISSUE TITLE
ENG: Update buttons on home screen

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7811]
**Note: Since we are updating the home screen, these issues are likely being addressed with that work and may no longer be needed. If so, this ticket can be closed.**

The following list are the updates that need to be made to buttons on the home screen of the app.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing)._
- [x] **Profile**
     - **Location:** Home
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Profile
     - **What happens?** Redirects to profile screen
     - **Recommended change:** Should be a link and not a button
- [x] **Contact VA**
     - **Location:** Home
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Right
     - **What happens?** Redirects to Contact VA child screen
     - **Recommended change:** Should be a link (or menu item) and not a button
- [x] **Find a VA location**
     - **Location:** Home
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Right
     - **What happens?** Launches webview / Find VA locations on VA.gov
     - **Recommended change:** Should be a link (or menu item) and not a button
- [ ] **COVID-19 updates**
     - **Location:** Home
     - **Current component type:** Button
     - **Current style:** N/A
     - **Icon:** Chevron Right
     - **What happens?** Launches webview / Coronavirus FAQs: What Veterans needs to know on VA.gov
     - **Recommended change:** Should be a link (or menu item) and not a button

**Comment by theodur** [comment]
The accessibility role for the `Contact us` and `Find a VA location` buttons were made links from the HSP changes. And the `COVID-19 updates` button was recently removed. The only change needed for this was making the `Profile` button have the accessibility role `link`.

**Comment by brea11y** [comment]
Perfect! Thank you, @theodur. That is exactly right. When I did the accessibility audit for HSP, the only thing that I noticed is that `Profile` was still reading out as a button, but I didn't note it because I knew we had this ticket open. We should be good to go once the `Profile` link is reading out correctly.

**Comment by TKDickson** [comment]
COVID-19 no longer exists (home or health); the rest from the home screen all read as links

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
