### ISSUE TITLE
Add a retry to the iOS build so we don't have to refresh it when it fails

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#7822]
The iOS build on the release workflow seems to fail on a semi-frequent basis. This is almost always solved by rerunning the workflow, so I'd like add a programmatic retry to the build to lessen the amount of manual intervention. 

Example of a failing workflow: https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/7626978205/job/20774639659

**Comment by timwright12** [comment]
PR: https://github.com/department-of-veterans-affairs/va-mobile-app/pull/7823

**Comment by bischoffa** [comment]
@timwright12 what is the next steps on it? Its part of 2.21 but its not a closed ticket.

**Comment by bischoffa** [comment]
first pass didn’t work then I got pulled away fro P&P. You can remove the sprint if that helps. I’m just going to work on it as time allows

**Comment by bischoffa** [comment]
No impact to the release
