### ISSUE TITLE
Lovell/Oracle Facility Transition

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#7828]
### **Background**
On March 9, 2024, the Lovell Federal Health Care Center (Lovell FHCC) in North Chicago (Station ID 556) will be switching to Oracle Health for its EHR. Once this switch happens, Veterans who use that facility will no longer have access to MHV features, including RX and Secure Messaging. To make the transition go smoothly, we are being asked to disable certain features and add content communicating to the user what is happening and where to go.

### **User Story**
As a Veteran enrolled at Lovell FHCC, I want to see messaging about when my facility transitions Oracle, so that I know I need to go to a different portal to manage my health. 

### **Acceptance Criteria** 
When a Veteran's facility switches to the Oracle portal, the mobile app displays a message giving the Veteran context and directing them to use the Oracle portal. 

## Timeline/Activities Needed
* Notes: for all days listed, the action indicated should be done at 12:01am ET
* Notes: March 9 is a Saturday and March 10 is a Sunday

| Tooling                |                           Message/Step                          | Location                     | Date starting | Date ending | Point Person |
|------------------------|:---------------------------------------------------------------:|------------------------------|:-------------:|:-----------:|--------------|
| Availability Framework | Step 1 - Warning                                                | Health home page             | Feb 28        | March 4     |     Binny         |
| Availability Framework | Step 1 - Warning                                                | Messages landing screen      | Feb 28        | March 4     |         Binny     |
| Availability Framework | Step 1 - Warning                                                | Prescriptions landing screen | Feb 28        | March 6     |     Binny         |
| Availability Framework | Step 2 - Access Restricted                                      | Health home page             | March 4       | March 10    |     Binny         |
| Availability Framework | Step 2 - Access Restricted                                      | Messages landing screen      | March 4       | March 10    |   Binny           |
| Availability Framework | Step 2 - Access Restricted                                      | Prescriptions landing screen | March 6       | March 10    |    Binny          |
| Testing                | Ongoing testing and validation                                  | Throughout app               | Feb 28        | March 9     | Tom Gammons  |

### **OCTO Tickets**
<details>
<summary>OCTO Tickets</summary>

-  [Messages](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/989)
-  [Prescriptions](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/988)

</details>

### **Previous work**
This work was last done in 2021. 
<details>
<summary>Previous tickets</summary>

-  [Epic](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1174)
-  [Some facilities](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1369)
-  [All facilities](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1368)
-  [Backend work](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/1659)

</details>

**Comment by mmiddaugh** [comment]
Connecting to related issues for visibility across Digital Experience crews 
- [Prescriptions - Lovell transition to Oracle](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7829)
- [VAHB: Prescriptions updates needed for users at Lovell FHCC to support transition to Oracle Health #988](https://github.com/department-of-veterans-affairs/digital-experience-products/issues/988)
- [Oracle health transition at Lovell Federal health #17077](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17077#top)

**Comment by ala-yna** [comment]
Questions for OCTO:

Though we may be able to shut off access to SM and RX for any Lovell-associated user (using Availability Framework), we're concerned that this will be a bad user experience. We believe that by relying on MHV upstream changes, SM and RX should not go through. Therefore:

- Does Mobile need to do separate work to ensure that **no** secure messages with a triage group tied to Lovell are sent? 
     - Why we're asking: Relying on MHV, we should be able to prevent messages sent to Lovell-related facilities from going through.
     - Per [this thread ](https://dsva.slack.com/archives/C0190MTGNUE/p1707339367424159) MHV should be responsible for preventing messages related to Lovell-related triage groups from being sent. The providers won't be visible in the app. 

- Does Mobile need to prevent users with Lovell as a facility from refilling any prescription?
    - Why we're asking: MHV _should_ be able to change the `is-refillable` tag on these prescriptions, so there shouldn't be a need for Mobile to make any changes. However, we haven't gotten a clear answer from MHV on when/if this is happening.

**Comment by EricaRobbins** [comment]
@ala-yna - can you please add the "roadmap-DMC" label to this card?
