### ISSUE TITLE
Bug - sev-2 - ENG: Update Payments App Headings

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7832]
The following updates need to be made in the payments area of the app.
 _This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [ ] **Content:** Amount
     - **Location:** Payments / VA Payment History / Details
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [ ] **Content:** Method
     - **Location:** Payments / VA Payment History / Details
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [ ] **Content:** Bank
     - **Location:** Payments / VA Payment History / Details
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [ ] **Content:** Account
     - **Location:** Payments / VA Payment History / Details
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.

**Comment by rbontrager** [comment]
Verified that the payment details amount, method, bank, and account are saying they are headers in voiceOver/talkBack.  Approved by QA.
