### ISSUE TITLE
ENG: Update Global App Headings

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7833]
The following updates need to be made in the global areas of the app. 
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [x] **Content:** Welcome, [ name ] 
     - **Location:** Onboarding
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Manage your healthcare
     - **Location:** Onboarding
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Manage your benefits
     - **Location:** Onboarding
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Manage your payments
     - **Location:** Onboarding
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** [ full name ]
     - **Location:** Veteran Status
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Disability rating
     - **Location:** Veteran Status
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Period of service
     - **Location:** Veteran Status
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Date of birth
     - **Location:** Veteran Status
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [x] **Content:** Need to fix an error?
     - **Location:** Veteran Status
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.

**Comment by TKDickson** [comment]
Confirmed all items above are read out as headings, iOS and Android.

**Comment by TKDickson** [comment]
Does not require further testing in develop; closing
