### ISSUE TITLE
ENG: Update Home Screen App Headings

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7834]
The following update needs to be made to the home screen of the app.
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [ ] **Content:** [ veteran name ]
     - **Location:** Home
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.

**Comment by theodur** [comment]
@brea11y Is this ticket still applicable? Currently, the veteran's name is only shown in the name tag button, where all the text all gets announced together with the accessibility role as `button`. With the new UI in the HSP changes, the veteran's name is no longer displayed on the Home screen

**Comment by brea11y** [comment]
@theodur – It is not. Once the HSP updates are launched, this will no longer need to be updated. Lauren addressed all of this in that work. Thanks for checking! Closing this one out.
