### ISSUE TITLE
ENG: Update Appointments App Headings

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7839]
The following updates need to be made in the appointments area of the app. 
_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [ ] **Content:** Select a date range
     - **Location:** Health / Appointments / Past
     - **Currently a heading?:** No
     - **Recommended change:** We might want to consider making this a heading.
- [ ] **Content:** VA Video Connect VA location
     - **Location:** Health / Appointments / Details
     - **Currently a heading?:** No
     - **Recommended change:** This should be a heading.
- [ ] **Content:** VA Appointment
     - **Location:** Health / Appointments / Details
     - **Currently a heading?:** No
     - **Recommended change:** We might want to consider making this a heading.
- [ ] **Content:** Select a date range
     - **Location:** Health / Appointments / Past / Filter
     - **Currently a heading?:** No
     - **Recommended change:** We might want to consider making this a heading.

**Comment by wavelaurenrussell** [comment]
Additional UX recs are available for this screen.

**Comment by Sparowhawk** [comment]
These were updated in our Appts componentization. Closing this ticket
