### ISSUE TITLE
UX: Make Recommendation for Provider Name App Heading in Appointments

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7840]
While performing the app headings audit, the following heading was found. Initially, it was unclear whose name this was and a little discovery work was done by engineering to figure out that this is actually the provider's name. In an effort to make this more clear, we are recommending that the heading tag be removed from the provider's name and that a new heading be added above this name that indicates that this is the provider's information.

_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [ ] **Content:** John Smith [provider name]
     - **Location:** Health / Appointments / Details
     - **Currently a heading?:** Yes
     - **Recommended change:** This is the provider's name. We may want to consider removing the heading tag from the provider's name and adding a heading prior to the name that says "Provider", "Provider name", or "Provider information".

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzRFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd4f54fbb5023aef4120753313c4618c408bf708/IMG_2448.PNG" alt="Screenshot of the appointment details screen of the VA mobile app" />

**Comment by wavelaurenrussell** [comment]
Add a heading that says Provider above the [Provider name]

**Comment by rbontrager** [comment]
Verified that appointments now have a heading of Provider above the provider information.  Approved by QA.
