### ISSUE TITLE
UX: Make Recommendation for Location App Heading in Rx

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#7841]
While performing the app headings audit, the following heading was found. It is recommended that we remove the heading tag from the location name. We should consider adding a new heading above the location information (i.e. "Location or "Appointment Location") that helps make it clear to a Veteran that the information below that heading is the location's information. 

_This list has been pulled in from the [full list of audit results](https://docs.google.com/spreadsheets/d/1KnR9Isdw8e3aBp5WhOFk7vaR4p6v4-wpYIO4GsEk4Go/edit?usp=sharing)._

- [ ] **Content:** "MID-V10 CRH MH PSY MD PT [ location name ]"
     - **Location:** Health / Appointments / Details
     - **Currently a heading?:** Yes
     - **Recommended change:** We may want to consider removing the heading tag on the location name and adding a heading above it that says "Appointment location" or "Location".

**Screenshot:**
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEVFQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5e65195ade7d12ee5a71cba086ee9feed30ecd2/IMG_2449.PNG" alt="Screenshot of the appointment details page of the VA mobile app" />

**Comment by wavelaurenrussell** [comment]
Recommendation: Add heading above friendly name that says Location name

**Comment by alexandec** [comment]
@wavelaurenrussell Here's how that heading looks:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2poQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86dda200fcfaa3ab28d9de0872fee5d1c3b7e991/Simulator%20Screenshot%20-%20iPhone%2013%20-%202024-03-14%20at%2013.48.37.png" alt="Simulator Screenshot - iPhone 13 - 2024-03-14 at 13.48.37.png" />

**Comment by wavelaurenrussell** [comment]
Awesome. Looks good!

**Comment by alexandec** [comment]
@rbontrager I see, that expands the scope but I can add it

**Comment by ala-yna** [comment]
We are going to hold off on this work for now - we're in the process of overhauling all of the appointments screens.

**Comment by brea11y** [comment]
Since appointments has been updated, this ticket is no longer applicable.
