### ISSUE TITLE
Update Crisis Line CTA Component with New Home Screen Designs 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7850]
AC:

- Update the Crisis Line CTA component in all locations in the app to reflect the designs in [figma](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3306&mode=design&t=vJWw89ED2PwHi60F-4)

Accessibility & Content 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
Needs to branch off of the feature XL, moving back to in-progress.

**Comment by theodur** [comment]
Updated the base branch, and got the PR re-approved by FE, this is good to continue reviewing ✅

**Comment by TKDickson** [comment]
Various locations of VCL button:
* Prelogin (aka the login screen)
* Interstitial screen for first time login (aka LOA gate)
* Home screen
* Health category
* Benefits category
* Payments category
* Messages: edit draft
* Messages: reply help (?)
* Messages: reply to message
* Messages: compose new
* Contact VA

**Comment by TKDickson** [comment]
VCL functionality unchanged (shows up at the top, brings to correct page) and accessible through various AT. [My test run is complete!](https://dsvavsp.testrail.io/index.php?/runs/view/5217&group_by=cases:section_id&group_order=asc)

Holding off on approval until VQA done (or deliberately postponed). Checking with UX.

**Comment by TKDickson** [comment]
Found #8049 during testing; not caused by.

**Comment by TKDickson** [comment]
Lauren signed off on VQA for this component, ready to merge to feature branch
