### ISSUE TITLE
Flip Health and Benefits Global Navigation Buttons 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7851]
AC:
- Update the navigation buttons at the bottom of the screen to be in this order: Home, Health, Benefits, Payments
- This order should be persistent regardless of which screen the users is one

**Comment by TKDickson** [comment]
Nav buttons switched on the bottom bar (now: Home, Health, Benefits, Payments). 

Light mode and dark mode, with and without screenreader, at the top or deeper in the stack, switching between categories - all looked good and functioned appropriately with the change. Good to merge to develop.

**Comment by TKDickson** [comment]
Swapped in the develop build from this morning, which is all I really checked post-merge. Closing.
