### ISSUE TITLE
Create and Implement Banner Component for Announcements at Bottom of Home Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7852]
**Component Creation**
- A new banner component is created, that reflects the designs in this [figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3006-1234&mode=design&t=vJWw89ED2PwHi60F-4)
- This new component should link to a hardcoded URL (for MVP)
- VQA by Lauren and Therese is required to complete this ticket

**Component Implementation**
- The banner component, created above, is implemented in the home screen under the VA resources section
- The component links to this PACT Act [URL](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/)

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
[Test case in TestRail](https://dsvavsp.testrail.io/index.php?/cases/view/59281)

**Comment by TKDickson** [comment]
[test run](https://dsvavsp.testrail.io/index.php?/runs/view/5300&group_by=cases:section_id&group_order=asc)

**Comment by TKDickson** [comment]
Minus a pending "have an app-wide standard for icon resize" ticket (that would also apply to this ticket), we're good for VQA.

**Comment by TKDickson** [comment]
OK @cadibemma in addition to any VQA comments incoming from @wavelaurenrussell , can you update the max size of the icon on the announcements banner to 24x24?

**Comment by TKDickson** [comment]
@cadibemma default icon size looks good. Should stay 24x24 even with text/display resizing on device though, which currently isn't happening:

<img width="548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c780d247cef94197772b6830119423354202815a/image.png" alt="image.png" />

**Comment by cadibemma** [comment]
Should be good now! @TKDickson

**Comment by wavelaurenrussell** [comment]
@cadibemma let's match the box shadow style here with the About you section one (I think it's .15??)

**Comment by theodur** [comment]
@wavelaurenrussell Yeah it's .15, here's what it looks like with the updated opacity:

<img width="548" alt="image" src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/973feec6-b842-4790-b3d1-4dbf9d02ce3d">

I'm also spinning up a new build so you can view it out on a physical device

**Comment by TKDickson** [comment]
Lauren approved the change above. Merged to XL, closing
