### ISSUE TITLE
Add docs for pulling and setting up postman collection of BE endpoints

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7857]
ACs:
- [ ] Investigate possibility of auto generating postman collection from new api docs json
- [ ] Create walkthrough docs for setting up postman collection and hitting endpoints in staging

**Comment by kpethtel** [comment]
Here's the current postman collection: modules/mobile/docs/MobileAPI Integration Test Collection.postman_collection.json
