### ISSUE TITLE
Send analytics event when user has facility transitioning to Cerner

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#7859]
Send an analytics event when user has a facility transitioning to Cerner. This will allow us to selectively disable features in the future for that user.

**Comment by alexandec** [comment]
@DJUltraTom any additional testing you want to do on this now that it's merged, or should we close it?

**Comment by DJUltraTom** [comment]
Lets keep this ticket here for a bit, I'll do additional validation on it next week

**Comment by DJUltraTom** [comment]
doing additional validation on this feature on BE ticket: [7861](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7861)
Closing this as deployed
