### ISSUE TITLE
Mark users as transitioning to cerner

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7861]
As part of facilities transitioning to cerner there is a 3 day period where all transactions to that facility need to be disabled. In order to give the user some custom messaging the FE needs to create a data set of users who are at that facility. To help them do that we will be marking users at the given facility (id: 556 for prod) with a new attribute. 

AC:
- [ ] add `hasFacilityTransitioningToCerner` to v2/user response 
- [ ] hardcode list of facility ids that are transitioning
- [ ] `hasFacilityTransitioningToCerner` should be true for users who have a facility in common with the hardcoded list

**Comment by jperk51** [comment]
Thread regarding the facility id: https://dsva.slack.com/archives/C0190MTGNUE/p1706634086548719

**Comment by kpethtel** [comment]
Haven't tested with feature flag on yet but have confirmed that v2/user works as expected with flag off.

**Comment by DJUltraTom** [comment]
QA is testing this using account: MHVTestFive.Test@id.me

**Comment by DJUltraTom** [comment]
verified messaging about using the VA health portal and Lovell facilities are showing up for appoints and secure messaging. RX is looking as good as far as I can tell for a user with no RX history. I'm good marking this as "deployed"
