### ISSUE TITLE
Availability Framework - Cerner Lovell Transition - From 02/28/24 - 03/04/24(03/06/24)

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7864]
**Description:** 
As VAHB Mobile App, I need to use Availability Framework to account for upstream changes involving Lovell Facility using Cerner so that VAHB can proactively  make Veterans aware of the upstream change implications. 

**Notes:** 
- [Ad Hoc Thread](https://adhoc.slack.com/archives/C067S0FRP0C/p1706561597318409)
- [OCTO Thread](https://dsva.slack.com/archives/C0190MTGNUE/p1706556021923479)
- AF being used to provide proactive messaging the Veterans before the change, when the change is happening Backend will control what is happening, after the change Mobile will be using existing message that exists today in demo for these users 
- OCTO wants messages out 30 days before the change starts which is 2/9; Mobile will not be able to facilitate that because the release with the code needed for this will go out after; so Mobile will turn it on when its available
- FE had to add code to look for a variable that BE is coding to add ; FE PR is completed and needs to be done in this sprint so it goes out in the release ; BE code does not need a release for this to work so not
- Tom to prioritize testing the FE PR before release branch cutoff on 1/30 

### **-New-** Details

Content can be found here: [mural link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1706284632056/bd0898e9be89541a02ed5c50076ade10e7fe31ec?wid=0-1707247345487&sender=alayna1905)

Dates for messages:

|           Message          | Location                     | Date displayed | Date removed |
|:--------------------------:|------------------------------|:--------------:|:------------:|
| Step 1 - Warning           | Health home page             | Feb 28         | March 4      |
| Step 1 - Warning           | Messages landing screen      | Feb 28         | March 4      |
| Step 1 - Warning           | Prescriptions landing screen | Feb 28         | March 6      |
| Step 2 - Access Restricted | Health home page             | March 4        | March 10     |
| Step 2 - Access Restricted | Messages landing screen      | March 4        | March 10     |
| Step 2 - Access Restricted | Prescriptions landing screen | March 6        | March 10     |

**ACs:** 

- [ ] Determine what component to use
- [x] Content creation 
- [ ] Add alert to our pre login screen 
- [ ] Pre Production Testing 
- [ ] Turn on AF at X ET MM/DD/YYYY  
- [ ] Determine strategy to turn off AF 
- [ ] Turn off AF at X ET MM/DD/YYYY

**Comment by TKDickson** [comment]
Confirmed this morning that this will be Tom's responsibility (from the QA side), unassigning myself (from autoassignment)

**Comment by bischoffa** [comment]
[Availability Framework process ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Process-%20Availability%20Framework.md)

**Comment by ala-yna** [comment]
@bischoffa, I added some more details about messaging and dates. How should we manage this work/make this happen?

**Comment by bischoffa** [comment]
@ala-yna I would recommend the following post our 2/7 PM sync:
1. Review the AF document, if not done already 
2. Schedule a meeting with impacted parties to discuss the work (Content, FE, QA).
   - Content - Shared Service - Misty 
   - QA - Health QA - Rachael
   - FE - Global - Binny (currently the FE lead until there is documentation that lets any FE handle it) 
   - BE - whomever involved in making the BE variable accessible for FE 
   - Optional - me 
3. Update ticket with details and notes from the meeting
4. Schedule / plan implementation (turn on and off) 
  - Looks like someone has to log in off hours on a Sunday 3/10 to turn it off

**Comment by bischoffa** [comment]
Also may want to consider what kind of monitoring and reporting Health & Benefits may need to provide to VA. I think there are some basic reporting but Binny can provide more details
