### ISSUE TITLE
Gather metrics on Lovell users of VAHB

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#7871]
Gather the following for OCTO RX Team:

[4:15 PM] Fink, Kaitlin E.
Users that have requested a prescription refill from Station 556 using VAHB

So that we can understand the impact of the work we're currently doing to manage the transition

**Comment by dumathane** [comment]
Didn't have this in our own metrics and have some questions out trying to find this data.
