### ISSUE TITLE
Review Action Sheets Cancel Button Treatment

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7873]
AC:

- Application's action sheets, located in this [document](https://docs.google.com/spreadsheets/d/1_6AFhiQBaPlrr5OzcMtng-Gvb-j8MEReB28JESpFPV8/edit#gid=2142734236), are audited on both mobile devices & tablets to determine whether they are in-line with Apple's guidance.
  - If not, document which ones need to be updated

**Comment by brea11y** [comment]
@ajsarkar28 – This is complete. The results can be found in [this following Google Sheet](https://docs.google.com/spreadsheets/d/1HoVOyId-ZOdkhC9evw5BsWIyxyLzS_4VzCRBbwvL0ns/edit?usp=sharing). 

I analyzed the action sheets and issued each one a "yes", "no", or "maybe" as to whether updates were needed to adhere to [the Apple guidance](https://developer.apple.com/design/human-interface-guidelines/action-sheets). There were 5 that I labeled as a "maybe", but none that were a definitive "yes". We could discuss the maybe's as a team or loop Holly in for her opinion. It's possible that I am overthinking the button labels (some of the forward buttons include the word "cancel" and some cancel buttons include the words "continue"). I felt that this could become confusing, especially for Veterans with cognitive disabilities, but it is possible that I am getting too hung up on the specific words.
