### ISSUE TITLE
Modify Top Navigation Bar Shadow

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7877]
**AC:**
- Top navigation bar's shadow is updated to reflect the designs in this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3090-1460&mode=design&t=9QI418ZjJkXvbfdI-4)
  - note that shadow is only in light mode 

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by dumathane** [comment]
@kidlaurenpeace @ajsarkar28  I don't think this is linking to the appropriate Figma location?

**Comment by TKDickson** [comment]
VQA-only, no specific test cases written in TestRail for this one. Will be a check that it matches Figma, and then sending to Lauren for review.

**Comment by TKDickson** [comment]
Merged to XL, closing
