### ISSUE TITLE
Write content considerations for Pagination component

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#7882]
The only content in this component is "1 to 10 of 31" -- I'm thinking the answer is no, but wanted to double check... do you think we need any "content considerations" for this component?

If yes...
- [ ] Write content considerations

**Comment by mistymg** [comment]
No work done - After chatting with Danielle Thierry about CAIA's work on VADS content considerations, I'm going to fold my mobile-content expertise into their efforts. This will make sure that both design systems are approaching content from a unified position.
