### ISSUE TITLE
Write content considerations for Menus component

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#7884]
This is the overflow menu that appears in Messages so you can Save or Delete a draft. This is basically a Button, so I was thinking the [Button content considerations](https://design.va.gov/components/button/#content-considerations) might apply here, too. Do you think that's sufficient? Or would you want to add anything else?

If yes...
- [x] Write content considerations

**Comment by mistymg** [comment]
No work done - After chatting with Danielle Thierry about CAIA's work on VADS content considerations, I'm going to fold my mobile-content expertise into their efforts. This will make sure that both design systems are approaching content from a unified position.

**Comment by mistymg** [comment]
Bringing this in to sprint 101

**Comment by mistymg** [comment]
Content considerations
- The VA mobile app currently only uses menus as a list of actions versus a list of options or navigation. Because menus are 
- In addition to VA Design System content considerations for buttons, 
- - Keep labels to 24 characters or less regardless of word count. Article words (a, an, the) can be omitted.
- - Order menu items based on most used at the start of the list.

**Comment by mistymg** [comment]
@jessicawoodin Hey there! Had time to check out content considerations for overflow menus. Comment above has my recommendations for the our design system. Need anything else from me?

**Comment by jessicawoodin** [comment]
Great, thanks! Would you mind adding the guidance to the [Content Considerations section](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Buttons%20and%20Links/Menus#content-considerations) for the Menus component on the doc site?

**Comment by mistymg** [comment]
Updating to 2 points if I'm going to update the doc site.

**Comment by mistymg** [comment]
Doc site updated and edits confirmed in live site.
