### ISSUE TITLE
Improve Availability Framework content capabilities

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#7885]
## Description 
As a Veteran, I want my Availability Framework messaging to be considerately spaced and have meaningful contact numbers for me in time of crisis.

As part of this story we want to:   

- Code a way to include string manipulation (whitespace, carriage return, etc.) that doesn't break backwards compatibility.
- Include a new variable for overriding the displayed phone number in ClickToCallPhoneNumber, default to the previous existing.
- Ensure all accessibility concerns are addressed for the new approach.
- All additions need to be included in the developer menu remote config objects.

## Acceptance Criteria
  

- [ ] Code a way to include string manipulation (whitespace, carriage return, etc.) that doesn't break backwards compatibility.
- [ ] Include a new variable for overriding the displayed phone number in ClickToCallPhoneNumber, default to the previous existing.
- [ ] Ensure all accessibility concerns are addressed for the new approach.
- [ ] All additions need to be included in the developer menu remote config objects.

**Accessibility Requirements**
- [ ] AC 1
- [ ] AC 2
- [ ] AC 3

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by rbontrager** [comment]
Verified that AF for Android and iOS supports newline, carriage return, tab, and bullet point characters and that the phone number can be changed. Verified that both of these options are in the developer screen under errorMsgBodyV2 and errorPhoneNumber for each feature. Verified that accessibility still functions as expected.  Approved by QA.
