### ISSUE TITLE
Data visualization mapping on OST using quarterly app review summary

### ISSUE THREAD

**Issue by lstraghalis** [department-of-veterans-affairs/va-mobile-app#7894]
We will review Q4 2023 app review trends by experimenting with mapping these Veteran-sourced areas onto the Opportunity Solution Tree in order to determine if this is a feasible way to pursue prioritization moving forward. 

We will copy the Q4 2023 app review summary onto the OST and use a scale of small, medium and large evidence circles as a first pass at this experiment.

**Comment by TKDickson** [comment]
@meggraham I have no idea what this is, I'm just trying to add labels to all tickets. Feel free to close if this isn't relevant anymore/already done.

**Comment by meggraham** [comment]
This is no longer relevant. I'll close it. Thanks for helping to bring order to the ticket chaos!
