### ISSUE TITLE
BUG - SEV 3 - All - Inaccurate copy in claims

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7907]
## What happened?

As part of the link/button audit, we found a link with copy that could be improved.

## Specs:

Found in demo mode but changes should be implemented everywhere.

## Steps to Reproduce

From Home...
Tap Benefits
Tap Claims
Tap Claims history
Tap first claim (Claim for compensation updated on December 05, 2021)
Tap "What should I do if I disagree with VA's decision on my disability rating?"
Scroll to bottom of large panel

## Desired behavior

Copy could be more helpful by aligning with the H1 of the webpage it's going to. There's also no reason to include a period at the end of the link.

## Acceptance Criteria

- [ ] Link copy now reads: "Learn more about decision reviews and appeals"
- [ ] Link copy does not include a period at the end

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--638548539cef9fddf55f7404c7d40979e60a689a/unnamed.jpg" alt="unnamed.jpg" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Verified that the link copy in the 'what should I do if I disagree...' panel now displays "Learn more about decision reviews and appeals" on iOS and Android.  Approved by QA.
