### ISSUE TITLE
BUG - SEV 3 - All - Copy change to Claims to align with web

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7919]
## What happened?

The Claims Status Tool team on VA.gov has decided to consistently use "Received" when talking about the date when a VA claim is initiated. [Here is the web's related ticket.](https://github.com/department-of-veterans-affairs/va.gov-team/issues/72065) We want to update our wording within our Claims feature to align with their change and create consistency for Veterans.

## Specs:

Screenshots of where this is occurring are from demo mode but this change needs to be changed in production as well.

## Steps to Reproduce

From the Home screen,
Tap Benefits
Tap Claims history
Tap between both Active tab and Closed tab

## Desired behavior

On the claims list screens (both Active and Closed), every time we say "Submitted" should be changed to "Received".

## Acceptance Criteria

- [ ] "Submitted" is changed to "Received" on all Claims/Appeals cards on the Active claims list
- [ ] "Submitted" is changed to "Received" on all Claims/Appeals cards on the Closed claims list

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shots

<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3N5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bb8617b18327f8fb582c522c0d953e9f47a8c96/IMG-0200.jpg" alt="IMG-0200.jpg" />
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzB5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da06ab9b8f99d68849f5fea10a0489c223c3a834/IMG-0199.jpg" alt="IMG-0199.jpg" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by bischoffa** [comment]
@mistymg I tagged this for the H&B team to review. In the future can you tag the team that you think its most relevant for? 

This ask is because QA is moving away from having 1 person do bug scrubbing for the entire mobile app to  having each QA agent scrubbing bugs in their specific areas. (ex. Therese for Global, Rachael for H*B, Tom for Platform) 

Its a recent change I am working to send out communications and didn't think about this scenario. I will work with QA to try to bridge this gap in the mean time.

**Comment by rbontrager** [comment]
Verified that the claims/appeals cards have switch from saying 'submitted <date>' to 'received <date>'.  Approved by QA.
