### ISSUE TITLE
BUG - 3 - All - User endpoint is being called when user isn't logged in (Access token JWT is malformed)

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#7922]
## What happened?

The `/v2/user` endpoint is being made before authentication is complete, which is causing the error `Access token JWT is malformed : {:access_token_authorization_header=>"undefined"}`. This is caused by the personal info query that is being called in the [NoticationManager](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/b29d4281484ec579e315b65d61fe1a31c1cb76af/VAMobile/src/components/NotificationManager/NotificationManager.tsx#L20). This can be resolved by disabling the query until login is complete.

A safer approach might be to disable all queries by default until loggin is complete, but the only concern is as we migrate more of the app to use React Query, we can't assume every query will be for making an APi call. There will likely be some that will be fetching data from async storage, which occurs before login is complete, so that will need to be account for. I'll spin up a CU ticket for that.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Sign in to the app, and once the screen navigates from the SyncScreen to the HomeScreen, the error should appear. The API call being made with the undefined token would be called on the sync screen, so you can verify that with Charles proxy

## Desired behavior

The `/v2/user` endpoint shouldn't be made before authentication is complete.

## Acceptance Criteria

- [ ] Disable personal information query from the `NotificationManager` until logged in

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Going back through old logs, I see the v2/user failures from this bug ticket. So for my testing, I'm going to run through the login sequence a few different times/ways, watching in Charles Proxy for any failed calls (v2/user or otherwise). Things I intend to vary: iOS/Android, signed up for PN/not, 'true' auth vs biometrics.

**Comment by TKDickson** [comment]
On initial login (+54) on Android, I got a trio of 400 failures in a row for /mobile/v0/push/register, before getting to the onboarding screen:

```
HTTP/1.1 400 Bad Request
Date: Wed, 07 Feb 2024 14:40:52 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 169
Referrer-Policy: strict-origin-when-cross-origin
Vary: Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Git-Sha: 1a55f85a45ac8be734485fefb7a2701767626b4a
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: f6731880-afa4-42f2-965c-9e23d7007da1
X-Runtime: 0.251047
X-Xss-Protection: 0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Connection: keep-alive

{"errors":[{"title":"Operation failed","detail":"The request to the upstream service was malformed and could not be processed","code":"VETEXT_PUSH_400","status":"400"}]}
```

**Comment by TKDickson** [comment]
Pinged for [BE assistance on investigating the errors above in DSVA slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1707317890003979)

**Comment by TKDickson** [comment]
Wrote up #7926 after quick discussion with BE team (unrelated to this ticket specifically). VEText team is working on fixing their setup, after which should be able to continue testing this ticket without running into those 400s.

**Comment by TKDickson** [comment]
VEText setup complete! Found #7954 (also, I'm assuming, unrelated to this change).

OK to merge to develop.

**Comment by TKDickson** [comment]
No further testing needed (or done) in develop, closing.
