### ISSUE TITLE
BUG - sev-3 - All - Claims/Appeals: incorrectly blocking feature access during maintenance windows

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7928]
## What happened?

Claims and appeals are two different features that appear in the same list/screen in the app (Benefits > Claims History). They have separate maintenance windows because the information for each comes from different systems.

However, currently our app will block access for BOTH features (by locking down the claims and appeals list screen entirely), even if just one of them has a maintenance window.

So in staging I mocked a maintenance window for JUST appeals, but instead of being able to still access claims from the claims list screen I saw this:
<img width="533" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXc1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c5b916e4ce6652fe7d2f42d6bcffc4bd12bc071/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Using Charles Proxy, mock a maintenance window for either JUST claims or JUST appeals
Log into the mobile app and navigate to the claims list screen
See that the maintenance window handling blocks access to both features

## Desired behavior

Ideally, would be able to access data for feature that isn't in maintenance, while still seeing a message explaining what's happening for the feature that IS in maintenance.

Will need UX team input on what that might look like/how that might function.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@TKDickson @rbontrager this one should already be fixed when we merged the RQ update for claims and appeals

this is the logic for the error component:

{claimsAndAppealsListError ||
      getUserAuthorizedServicesError ||
      (!claimsNotInDowntime && !appealsNotInDowntime)

**Comment by bischoffa** [comment]
@rbontrager checking in. Ticket has been stale for 14 days

**Comment by rbontrager** [comment]
I had a discussion with @DJUltraTom and he told me this was tested during the maintenance window checks.  Closing this ticket a fixed by RQ.
