### ISSUE TITLE
Implement contract testing in appointments service

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#7929]
We recently wrote a contract schema testing library. We need to use it in live code. We've already talked to VAOS about this and they've given us the green light to add it to their code. Work with the VAOS team to get the schema as correct as possible.

Resources:
[Spike ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7579)
[Spike draft PR](https://github.com/department-of-veterans-affairs/vets-api/pull/15103)
[Conversation with VAOS engineering team](https://dsva.slack.com/archives/C023EFZPX4K/p1705603082034489) 
[Lib ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7771)

AC:
- add contract schema testing to vaos code
- it saves results to db
- it alerts us to inconsistencies via error logging
- it is feature flagged
- the schema was use is accurate and detailed (work with vaos on that)

**Comment by aherzberg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/7929?planning-poker) with Zenhub @Tonksthebear @kpethtel

**Comment by StacyB2023** [comment]
@kpethtel Added this into an epic for tracking purposes on the PM side
