### ISSUE TITLE
Change SM routes to match the rest of our routes 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#7933]
Since the initial implementation the SM routes have been represented differently than the rest of our routes. We should update them to follow the say 'url' to 'controller#method' pattern as the rest. The pattern the rest of the endpoints use is much easier to parse at a glance and much easier to understand for people who don't know ruby/rails. 

ACs:
- [ ] update SM routes 
- [ ] make sure tests pass
- [ ] ensure this is getting tested in staging before hitting prod and is able to be rolled back before the next prod deploy 
- [ ] ensure all routes are being used

**Comment by aherzberg** [comment]
merged changes and tested all messages endpoints. ready for prod deploy tomorrow
