### ISSUE TITLE
Generate mockups of content for Lovell Transition

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#7934]

**Comment by Sparowhawk** [comment]
Step 1 mockups

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUU2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--902e72e6e1a6a977326862e8edb9f269d9dc91da/Screenshot%202024-02-07%20at%2011.40.51%20AM.png" alt="Screenshot 2024-02-07 at 11.40.51 AM.png" />
<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUk2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7dcf7be84aa8da32d608296101de38659cf5bcd2/Screenshot%202024-02-07%20at%2011.41.03%20AM.png" alt="Screenshot 2024-02-07 at 11.41.03 AM.png" />
<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU02QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58902b0243bf192f6d6aa0f222a4ad1181adb86b/Screenshot%202024-02-07%20at%2011.40.29%20AM.png" alt="Screenshot 2024-02-07 at 11.40.29 AM.png" />

**Comment by Sparowhawk** [comment]
Step 2 mockups

<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVk2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5bcfc94c9eb23a25229b275d70df0b742168143/Screenshot%202024-02-07%20at%2011.47.15%20AM.png" alt="Screenshot 2024-02-07 at 11.47.15 AM.png" />
<img width="425" src="https://api.zenhub.com/attachedFil<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWM2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d42973061e26c34004f81661db4694954079e19/Screenshot%202024-02-07%20at%2011.47.23%20AM.png" alt="Screenshot 2024-02-07 at 11.47.23 AM.png" />
es/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVU2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3f6d62c160e7068ca556cebcee46eccb4566e07/Screenshot%202024-02-07%20at%2011.46.56%20AM.png" alt="Screenshot 2024-02-07 at 11.46.56 AM.png" />
