### ISSUE TITLE
BUG - sev-3 - All - Calling the mobile/v0/push/register API at least three times

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7954]
## What happened?

When we call the /mobile/v0/push/register API from the app (which happens during the sign-in sequence for Android, or after opt-in for iOS), we nearly always call it..... three times simultaneously.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmhEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--699f1f331398e4586d469eb83f0d8f769d598ea9/image.png" alt="image.png" />

_Once - just once, like a unicorn vanishing into the mist - I saw it log five times during the login sequence on Android._

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Should just call it once.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@TKDickson This likely will be fixed with the React Query Migration for Notifications when that gets merged you should recheck this

**Comment by TKDickson** [comment]
Added the notification migration ticket as a dependency.

**Comment by theodur** [comment]
@TKDickson Are you fine with me attaching this ticket to Dylan's RQ Notification PR and marking it as in progress? This should get resolved there with the updated RQ logic

**Comment by TKDickson** [comment]
@theodur yes definitely

**Comment by TKDickson** [comment]
Have been blocked on this since Tuesday - there's a reverse proxy server somewhere in the staging notification ecosystem that's not playing nicely. Hopefully resolved today.

**Comment by TKDickson** [comment]
DSVA support thread is resolved and I've confirmed I can successfully register for notifications, as well as fetch preferences, from upstream servers. This is unblocked and I can start working on it tomorrow.

**Comment by TKDickson** [comment]
During login, we're still calling the register call twice when opting into push on iOS:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUs0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3604e7daf34fa2e35296839146dc1f6818c350d5/image.png" alt="image.png" />

If you opt-out of push during login, and then later turn it on (via jumping from the notification preferences screen in the app out to settings), then the register call is made...... dear god, 7 times:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0M0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57a6b5fe98ad01304d63c6892937218dd303e017/image.png" alt="image.png" />

@Sparowhawk still broken

**Comment by TKDickson** [comment]
This is improved, but not yet fully fixed.
- When calling the push notification registration during login, it's only being called once - pass.
- If enabling notifications for the first time AFTER login (by going to Profile > Settings > Notifications > Go to Device Settings, then turning on notifications and app-switching back to the H&B app), the registration call is being made twice. - improved, but still a fail.

**Comment by TKDickson** [comment]
This is fully fixed/resolved - won't be able to close until the issue on #8253 is ready, but does not require further testing.
