### ISSUE TITLE
Create Disability Rating and Monthly Payment Component

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7966]
**Overview**
This ticket covers creating the new disability rating and monthly payment component. The implementation of these components is in the About you section creation and content [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7968).

**Component Creation**
- A new disability rating/monthly payment component is created, that reflects the designs in this [figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-1979&mode=design&t=vJWw89ED2PwHi60F-4)
   - Component data includes:
      - Disability rating %
      - Monthly compensation payment amount
   - See this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258) for data appearance logic
- VQA by Lauren and Therese is required to complete this ticket

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
[Test rail cases](https://dsvavsp.testrail.io/index.php?/cases/view/59279)

**Comment by TKDickson** [comment]
* We (QA and Eng) didn't understand the accessibility annotations on the Figma for this component - so immediately asked, figured it out, and pushed in a change to match the original intent.

Now, Android only, we're seeing the same type of thing in the DR and $ portions [as have seen previously](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4000) (reads as: “disability rating 70% service connected” (swipe) “70%” (swipe) “service connected”)

**Comment by TKDickson** [comment]
Right now, the disability rating and military service history API calls kick off during the sync screen, but the letters beneficiary call only kicks off AFTER the home screen loads. Can we be front-loading the beneficiary call as well, to make loading the $ info on the home screen (or the entire about you section, I think, after #7968 adds the loading stuff) faster?

**Comment by TKDickson** [comment]
Wrote #8143 after conversation with Binny; should ideally be addressed at the same time as the API refresh/activity reloading behavior (which is still unticketed work)

**Comment by TKDickson** [comment]
With QA and VQA signoff (see the above ticket again), merged to XL and closing

**Comment by TKDickson** [comment]
[belated test run link](https://dsvavsp.testrail.io/index.php?/runs/view/5289&group_by=cases:section_id&group_order=asc)
