### ISSUE TITLE
Create About You Section with Populated, Loading, and Empty States

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7968]
**Overview**
This ticket covers the creation of the home screen's About you section with the populated, loading, and empty states. The error and edgecases are covered in this [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7967).

For all visual elements in this ticket, reflect the designs in this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3305&mode=design&t=vJWw89ED2PwHi60F-4).

**Header**
- A header that says About you implemented.

**Populated**
For detailed appearance logic, see this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?wid=0-1704409212320)
- If the user is a Veteran, display the branch of service and Veteran Status Card
- If the user has a disability rating that's greater than 0, display it
- If the user has a monthly payment that's greater than 0, display it
- If the user has a disability rating AND a monthly payment that's greater than 0, then display them both together

**Loading** 
- The About you section reflects the loading designs in the Figma file

**Minimum State**
- If no data has been returned, then display the minimum state UI

**Accessibility & Content** 
- All accessibility guidelines in previously linked Figma file have been followed
- All content is linked in this [Mural](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=u4daa07e974be596b6b097258)

**Comment by TKDickson** [comment]
[Test rail cases](https://dsvavsp.testrail.io/index.php?/cases/view/59279) (shared with #7940 and #7966)

**Comment by TKDickson** [comment]
* Icon and related text should be combined into a single screenreader callout for loading and empty states, a la "Error, We can't show your information right now", same thing as on the activity section ticket #7935. (Previously was unclear whether separate or together in Figma)
* Error icon in iOS and Android is announcing Error and then a bunch of nonsense (Android "Error 2 left curly bracket error 2 right curly bracket", and iOS similar see screenshot)
<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5edbacd1ff7f3a4a63ab916c092905ef05732c94/image.png" alt="image.png" />
* It's also showing up as actionable in Voice Control, which is weird (see #4 in screenshot)
<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFhHQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69b0c3ce1f959e9d8af65e76c6c3f732ddedceff/image.png" alt="image.png" />


Hopefully all of those things are relatively easily addressed together by combining the icon and text into a single, non-actionable readout

**Comment by wavelaurenrussell** [comment]
Thanks. Can we lighten the shadow a little for the components in the About you section? I want it to match closer to Activity buttons. I know its probably using the same exact style, so we may need to eyeball it for the iOS displays. It renders closer to the design in Android, but looks pretty dense on iOS. Knowing many more users are running iOS, I think its worth it to take a look-see.

1. Confirm its using the same specs as design (box-shadow: 0px 6px 20px rgba(163, 176, 181, 0.4) 
2. Lighten just a touch (maybe to .3 or .2 ?) and ping me to view in device.

**Comment by wavelaurenrussell** [comment]
Discussed with @dumathane. Lightened to 1.5. All is well.

**Comment by TKDickson** [comment]
QA and VQA signoff complete, merging to XL and closing.

**Comment by TKDickson** [comment]
[belated test run link because I realized I didn't include it earlier](https://dsvavsp.testrail.io/index.php?/runs/view/5299&group_by=cases:section_id&group_order=asc)
