### ISSUE TITLE
All of the id.me credentials are changing in staging — current credentials expire ~ May 6

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7982]
**Description:** 
As VAHB Mobile App, I need to know how this change will impact Mobile App so that we can plan accordingly so that we are prepared when old credentials expire. 

**Notes:** 
- Existing expires ~90 days after ~ Feb 6
- Mobile not notified till after the change was done - gap on VA's side 
- Nearly all of QA's testing is done with id.me credentials ; QA uses other creds rarely or if forced 
- Credentials are also going to be on developer.va.gov, aka only accessible on the VA network, aka NOT accessible currently to Tom or Rachael - meaning only Therese can handle this 
- Email is attached in the comments -> [Changes to Accessessing Test Data Idme.pdf](https://github.com/department-of-veterans-affairs/va-mobile-app/files/14271083/Changes.to.Accessessing.Test.Data.Idme.pdf)

**ACs:** 

- [ ] See how this impacts mobile
- [ ] Determine if all test accounts are getting new credentials or just some 
- [ ] Document findings
- [ ] Share findings with QA

**Comment by bischoffa** [comment]
Ticket is created based on what we now as of now from the email. More discussions, discovery needed to work out how Mobile is impacted and what we need to do about this change. Though not needed till early May QA would like to do at least some initial discovery early to learn more about the impact and situation. That way we are not waiting till the end and uncover something that puts us in a tight corner.

**Comment by TKDickson** [comment]
Created a support ticket with the Lighthouse team (using the web form linked from the original email) to try to figure out how we got on the contact list, and their knowledge about the changes to staging.

Background: a bunch of different teams maintain sandbox and staging, and sometimes (depending on the area) we've known them to maintain parity between environments, and some teams don't.

**Comment by TKDickson** [comment]
Latest email sent to support:

> Hello Rachel,
> 
> I attempted to log into staging using some of the new test users on developer.va.gov/explore/api/patient-health/test-users/[a whole bunch of numbers/letters that I'm unable to copy-paste from my VA Citrix session to here].
> 
> During the redirect from id.me back to the website (and similarly, during the redirect from id.me back to the mobile app, I tried multiple platforms) I received the following message: This credential is not valid for use, please try again.
> 
> Are these new credentials live and working? If not, when are they expected to be working? If they should be usable already, are you sure they're all populated in the staging environment (not just sandbox)?
> 
> Thanks,
> Therese

**Comment by TKDickson** [comment]
QA team should be OK. Latest response from support (and I asked her to close the ticket):

> Hello, Therese,
> 
> In staging, rotating the test users is not necessarily needed. For clarification, if the existing ID.me test user starts with "vets.gov.user...", the credentials do not need to be rotated. Only the "va.api.user..." credentials are being rotated.
> 
> Please let us know if this helps or if you have any additional questions.
> 

I will let the backend team know as well. QA team generally doesn't use the va.api.user.... usernames so we are essentially unimpacted.

**Comment by TKDickson** [comment]
Notified backend team in Slack, and closing ticket.
