### ISSUE TITLE
Direct deposit account to include education benefits

### ISSUE THREAD

**Issue by rachelhanster** [department-of-veterans-affairs/va-mobile-app#8002]
4.20.24 proposed deadline: The education business at VA is migrating their direct deposit functionality into the same backend that supports the comp & pen direct deposit information. They are starting with Chapter 33 (GI Bill) benefits, and then migrating the other education benefits over a number of years.

[va.gov VA Profile epic ticket](https://github.com/orgs/department-of-veterans-affairs/projects/940/views/6?filterQuery=is%3Aopen+label%3A%22team-auth%22&pane=issue&itemId=53422017)

# Project Status Overview

### Project Objective:

- As a Veteran, I'm informed that updating direct deposit account info in the mobile app will impact disability compensation, pension benefits, and education benefits.

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| External dependency - direct deposit work has been paused  |  Education Benefits | Unknown
|  |   |

</details>

### Monthly Update for Stakeholders
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
| May 2024  | Yellow | Work was completed, but being held until we hear from the education benefits team | We don't have an ETA for when we should make this change
|August 2024 | Green | This was was prioritized in the current sprint and will be delivered in the next release on 8/27.
</details>

### Team Members
<details>
<summary>Contact List</summary>
 
**VA:**
- **Mobile OCTO Product Leads:** Rachel Han 
- **VA OCTO Product Leads:** Chante Lantos-Swett
- **External Team 1 & Role:** Direct Deposit
- **External Team 1 & Role:** Education benefits
- 
**Ad Hoc:** 
- **Mobile Team**: Health and Benefits
- **Mobile Team Lead:** Alayna
- **FE Engineering:** Chris, Dylan
- **BE Engineering:** Jayson
- **Design:** Lauren
- **Content** Misty
- **QA:** Rachael
- **Mobile Teams that are involved:** API team is making a small backend change
</details>

**Comment by mistymg** [comment]
@ala-yna Is this still blocked? I thought this went out in a recent release?
