### ISSUE TITLE
Process/spike: how to handle unsupported mobile OS versions

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8004]
I'm pretty sure (from initial research) that we haven't stranded anyone app version wise yet (looking into it in #8003) but we need to have something in place for when we do.

Things like:
* Messaging for encouragement (you CAN upgrade and you should!)
* Messaging for cutoff (you can't upgrade and we're no longer supporting you; here are alternatives if you can't upgrade)
* Actual cutoff (FE/BE)

This ticket would be to figure out those details (or any others) and document them, as part of a "how to handle unsupported app versions" per the [OS compatibility and support page.](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/Compatibility/)

To be super clear - we're not going to have great options for very old mobile client users (as of the time writing this ticket) because being able to handle something like this wasn't built into the app (#8661 may be able to help, if it's done). Nevertheless, we should present fallback options, if at all possible.

**Comment by TKDickson** [comment]
[ABC news 'offboarding'](https://help.abc.net.au/hc/en-us/articles/360001527275-What-can-I-do-if-my-device-is-not-compatible-with-the-latest-version-of-the-ABC-NEWS-app) with how to create shortcut to website (interesting....)

[Disable download of old app versions (iOS)](https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/make-a-version-unavailable-for-download/)

Android appears to just do this automagically (although there are non-official routes like APK Mirror and F Droid - we're not on those sites as of right now)

**Comment by TKDickson** [comment]
Position: internal & external support should match. (Supporting internal but not external is a waste of time/resources. "Supporting" external but not internal is just asking for trouble) 

Which means that prior to _having_ to cut off versions, we need to establish how we cut off versions & communicate that internally & externally. Also, with those plans/communication channels in place, gives more flexibility on what do support.

**Comment by TKDickson** [comment]
Idea: use iOS version support to disallow download of old versions *in production* (3 versions past sufficient change?) ex: new Nav (would have been), availability framework (recommended now), .....


Also useful image for later:
<img width="299" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9a8f9fb2a8222c5add569acf93340af141a550a/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
If we do nothing:
* Eventually (on both platforms) we will release app versions that the OS on people's devices will be incompatible with.
* (come back and edit this to have more detail later! but posting to save this trail of thought that I want to fill out)

**Comment by bischoffa** [comment]
@TKDickson lets talk about this in a future 1:1. I am thinking this may be outside of Qart and and be Global specific given the features are owned by Global.

**Comment by TKDickson** [comment]
We (finally) looped back around to this; here's the gist:
* The work of "how should the QA/platform teams handle OS version support" is done - ticket #7601.
* QA implementing the choices from ^ ticket is being worked - ticket #8664.
* The work of "as a QA person, investigate what's been done with apps & unsupported OS versions elsewhere" is also done - that's this ticket. It would certainly need to be supplemented by an Eng doing investigation in the future.
* Global (or the relevant app team of the future) would need to do work, in the future, around "how do we move users off of an unsupported app version". There's no specific ticket targeting that exactly, but the work being done for custom BE errors (#8603), and sending more detailed information on API calls (#8661), should assist in that endeavor.

So, closing this ticket as complete.

**Comment by bischoffa** [comment]
@timwright12 see above. 

We suspect it will be related to how we want to handle the SDK changes for Android if not backwards compatible. VAHB may want to think of ways to communicate it and it may include stuff we do not do today.
