### ISSUE TITLE
BUG - sev-3 - All - Loading screen experience for personal information is not great

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8017]
## What happened?

Idk when it happened, but our loading screen indicator for personal info no longer takes the 'full screen' - you can still see the entry points for gender identity and preferred name, but they're in the default state/don't have your info loaded yet, and hang out at the bottom of the page. And then when loading finishes your information comes in and the whole screen 'snaps together'. On subsequent loads, it'll have your data but still have the weird 'hanging out at the bottom then snapping up' UX.

[It's just not a polished look, altogether (video).](https://drive.google.com/file/d/1ka-Zi-dL7z1LFZWiIx_nsK4qWBpzDLEz/view?usp=sharing)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Loading screen indicator should also 'cover' gender identity and preferred name entry points, I assume. Will need UX ( @htcollier ) to confirm.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by htcollier** [comment]
Yep, for now the loading screen should 'cover' gender identity and preferred name entry points 
(I could see a future where we do a skeleton load that doesn't snap in the future, but covering is fine for now).

**Comment by TKDickson** [comment]
[Detox personal info run](https://dsvavsp.testrail.io/index.php?/runs/view/5446&group_by=cases:section_id&group_order=asc) matches what's currently failing in develop/no additional fails with this change.

**Comment by TKDickson** [comment]
Original screen load, plus screen load coming back to screen (ex: saved new preferred name) is looking much better.<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGVUQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--788c661d925c10beb757f82ef1e11265c2ad80e7/image.png" alt="image.png" />

Good to merge to develop

**Comment by TKDickson** [comment]
no testing needed in develop; closing
