### ISSUE TITLE
Locations not found

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#8028]
Per [this slack conversation](https://adhoc.slack.com/archives/C0206QFMXFU/p1708452322246579), show location consistently returns 404 in staging. This appears to have two causes:
- in `locations_controller#show` we parse locations on the assumption that their ids are three characters long. When I tested this on the staging console, they were all two characters. For example, we expect `vha_855_296` which would indicate an id of `855`, but we actually receive`vha_85_296` which results in a location of `85_`. We then use that id to fetch location data from upstream. The upstream returns nothing because `85_` is not a location.
- Even when you send the correct id (i.e., 85), no data is returned from upstream. This may indicate that there is no actual location data on staging.

Also, looking at [datadog](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?env=eks-prod&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28activePanelKey%3Aresource%2Cresource%3A%28resourceName%3AMobile%253A%253AV0%253A%253ALocationsController%2523show%2CresourceID%3Ae3b6ea3f7fd4315a%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Alocation%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Aratio%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Acount%2CbreakdownAs%3Apercentage&view=spans&start=1707852892497&end=1708457692497&paused=true), this endpoint has a roughly 15% error rate in prod. This seems disconcertingly high. It may be because some prod facilities have two digit ids. 

AC:
- parse by splitting on underscores, not by expecting three characters in the middle
- investigate why there is no location data in staging. 
- update specs
- add logging to help understand why the 404 rate in prod is so high

**Comment by Tonksthebear** [comment]
I'm waiting to add logging until we see if switching to `string.split()` solves the issue. It may be unnecessary to add more logs if that's all it was

**Comment by Tonksthebear** [comment]
We've received confirmation from people that the errors have gone away for a few of those affected
