### ISSUE TITLE
Push Notifications - Content for “Enable push notifications” opt-in flow 

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#8037]
## Description
Create final content for the new screens and states in the [“Enable push notifications” opt-in flow](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7880).

See Figma board for entire flow:[UX recommendation for notifications opt-in for Android & iOS](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=993-8290&mode=design&t=2eYY0UMuABiFfDbu-4)

## Acceptance Criteria

- [X] New copy for context-setting screen (appears before native opt-in request)
- [X] New copy for notifications screen - new "not yet enabled" state
- [X] Copy updates to other screens as needed in E2E flow
- [x] [A decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/content/content%20decision%20log.md)

## Notes & Open Questions
**Design:**
- [UX recommendation for notifications opt-in for Android & iOS](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=993-8290&mode=design&t=2eYY0UMuABiFfDbu-4). 

**Discovery:**
- [Comparative Analysis: Push Notifications: How do apps approach asking users to enable push notifications?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-comparative-analysis-2023.md#how-do-apps-approach-asking-users-to-enable-push-notifications)
- [Discovery/Desk Research: Push Notification Best Practices - Permissions & management](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-best-practices.md)

**Strategy:**
- [Push Notifications Design Strategy Worksheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/ux/push-notifications-design-strategy-worksheet.md)
- [Push Notification Strategy - Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/product/Push%20Notification%20Product%20Brief.md)

## Ticket Checklist
- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
- Check on VA.gov Profile of context setting content for enabling notifications.

**Comment by mistymg** [comment]
Groomed with Holly in meeting

**Comment by htcollier** [comment]
updated Figma links
