### ISSUE TITLE
Update Demo Mode with Personalized Home Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8039]
AC:
- Demo mode displays active item modules for secure messages, appointments, claims & appeals, and prescriptions
- Let Brea know when this is complete so shipped files can be updated

**Comment by TKDickson** [comment]
This is already done, by who-knows-what PRs over the course of the XL. (as in, it is in demo mode)

Whether or not demo mode is tailored to show what we want it to show (right now it's all the things all the times) is still kind of an open question.
<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0xJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8904cef17867906b33f1e93080a7983b2c7283c3/image.png" alt="image.png" />
<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66ff0063dbf48678b05428f12842a2e558592645/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Team discussed in grooming yesterday, and for the MVP we think it makes sense to have all of the new components present and populated. As we add to the home screen (ex: a payments deeplink button Payments "You have 1 new payment to your account"), then we should re-evaluate when it makes sense to remove older activity buttons to balance the look of the demo screen.

The information passes a basic sniff test, closing this ticket as complete.
