### ISSUE TITLE
BUG - sev-3 - iOS (and maybe Android) - Secure messaging: User report that unread messages are announced as read with VoiceOver

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8043]
## What happened?

Another [bug report from (blinded veteran) from DSVA Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1708608558136159):
New incoming messages are displaying as “read” but she never opened or read them. Device is iPhone 15 Pro, and she keeps automatic updates so the iOS should be the latest version

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Unable to reproduce on the RC candidate build for 2.21, as well as using demo mode with the released app. [Read messages are reading as read in message list and unread are reading as unread.](https://drive.google.com/file/d/1olMi2A59j6iU30KHfSq3Ohj0snKw4-Xd/view?usp=sharing) iPhone 12 on iOS 17.3.1.

I want to try as well with the very latest develop build for iOS, just on the off chance; those builds are currently failing (for the last 2 days) and @timwright12 is looking into what commit may have broken things.

**Comment by TKDickson** [comment]
I was briefly hopeful that I had reproduced this, then realized I was actually encountering the inverse problem (messages that SHOULD be marked as read but aren't) in specific scenarios. Ticket #8056

**Comment by Sparowhawk** [comment]
@TKDickson @rbontrager I am fairly certain this and the other ticket is resolved with the RQ migration

**Comment by TKDickson** [comment]
@rbontrager can you either confirm (and close), or add a comment & keep this open? Same with #8056.

**Comment by rbontrager** [comment]
Can confirm that I'm not seeing this in the latest RC build (2.29.0) and unread messages are being declared as unread and read messages are being declared as read.  Closing this ticket as not reproducible.
