### ISSUE TITLE
BUG - sev-3 - All - Secure messages: app won't mark more than one message in a thread as 'read' until after you reload the inbox

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8056]
## What happened?

As a veteran with more than one unread message from a single thread, 
* Go to Inbox. Open one of the unread messages in the thread.
* Exit the message details, and notice it's marked as read in the list.
* Open another unread message in that thread.
* Exit the message details, and notice that message is NOT marked as read.
* Reopen the message repeatedly. It will not be marked as read.
* Exit and re-enter the inbox, then reopen & exit that message again. It is finally marked as read.

[Here's a video of ^ workflow](https://drive.google.com/file/d/16CdTDvHj4sS1KkI3WGO4M-M6AockOGr7/view?usp=drive_link)

I had Charles open while I was doing this. 
* The first message, we call both `/v0/messaging/health/messages/[message ID]` (message details) AND `v1/messaging/health/messages/[message ID]/thread?excludeProvidedMessage=true` (message thread).
* The never-marked-read meessage, we only call `v1/messaging/health/messages/[message ID]/thread?excludeProvidedMessage=true`
* Then after exiting and re-entering the Inbox, and attempting that message again, we'll call both message details and the message thread APIs for that message.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

When a user reads a message, it should be marked as read.
When a user hasn't read a message yet, it should remain unread.

That's it.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by Sparowhawk** [comment]
@TKDickson @rbontrager I am 100% sure this one will be fixed with the React Query Migration for SM when it gets merged. Will need to retest then

**Comment by Sparowhawk** [comment]
I just tested this with 3 threads now. This is working. Here is a video of it working correctly


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6cc5034e93b1db1211bd76a3516f58310d5dce4/Screen%20Recording%202024-05-14%20at%201.49.01%E2%80%AFPM.mov)

**Comment by rbontrager** [comment]
Can confirm that to the best of my knowledge that this was fixed with the SM React Query and that if it is still happening its might be a specific issue with HSP and caching.  I was able to reproduce before SM react query and was not able to reproduce on the latest dev build.
