### ISSUE TITLE
BUG - sev-3 - Backend - Some maintenance window services that we're not currently respecting, but probably should

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8059]
## What happened?

Here are all of the different services that have sent maintenance windows in the last 6 months (Aug 23 2023 - Feb 23 2023) - this is according to the data Andrew had in [this thread](https://adhoc.slack.com/archives/C0206QFMXFU/p1708702139104189). A bunch of them we correctly respect, a few of them we correctly ignore, and then a few we likely SHOULD be doing something with, but currently don't. 

I've mainly got my eye on `mhv_mr` and `mhv_sm` and `vaosWarning` and `lighthouse_direct_deposit`, aka OMG we can be more targeted than "all of lighthouse is down" but whoever grabs this ticket will ideally look into things and know more than my hunches:

```
bgs
dmc
dslogon
es
evss
idme
lighthouse_direct_deposit
mhv
mhv_mr
mhv_sm
pcie
ssoe
vaosWarning
vbms
vet360
```

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Ideally - figure out what features of ours these map to, and send service names that the FE is already handling. If there ends up being FE work needed, will need to write another ticket.

## Acceptance Criteria
- [ ] Look at the list of existing maintenance windows and record the ones we should use that we aren’t
- [ ] Investigate and update our upstream service map in our docs
- [ ]  create the necessary tickets to fill in the gaps/update the windows service map in vets-api

**Comment by jperk51** [comment]
the MHV_XXX are brand new and a result of us asking them to become more specific about what is down, but before I was on vacation afaik it wasn't ready to go just yet. It's nice to see that LH is also doing that, but we definitely should encourage all the other LH groups to do the same.

**Comment by aherzberg** [comment]
doc from LH about upstream dependencies: https://github.com/department-of-veterans-affairs/leeroy-jenkles/wiki/API-Backend-Systems#api-to-va-backend-mapping

**Comment by StacyB2023** [comment]
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8111 Adding this ticket for reference as well

**Comment by jperk51** [comment]
AFAIK the BE work on this is done

**Comment by TKDickson** [comment]
Closing this ticket as complete. Since the backend team updated the mapping (not adding new), the existing frontend code will respect it, it's all version-independent, all the good things.
