### ISSUE TITLE
Copy change for "You're leaving app" alert

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8060]
## Description 

As part of the Design System team work, we changed the "You're leaving the app" alert copy to be more general so that other apps could use it without needing to put their app name in the copy. We also updated the copy to follow a model we use in other dialogues/alerts of the header being a question, the body giving more context, and the buttons being the user's answer to the header question.

## Acceptance Criteria
  

- [x] Alert header copy: Leave the mobile app?
- [x] Alert body copy: You'll go to a website outside of this app.
- [x] Alert confirm button: Leave
- [x] Alert cancel button: Go back
- [x] Verify that there are no accessibility concerns

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Any internal/external dependencies?
    - Test accounts needed?
- Does this require QA?
    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
Presumably also need to update detox scripts for this change, QA2

**Comment by TKDickson** [comment]
Copy matches above & got clarification from Brea that there are no special accessibility concerns (anymore) with this change. I've updated the detox utils file and am running the Settings script for this branch to confirm that it'll work with the changes, iOS and Android. If that comes back clean, can mark the PR as approved.

**Comment by TKDickson** [comment]
Detox scripts need attention; marking this as blocked until those are resolved. (Mostly because for both QA & Eng, right now HSP is going to take higher priority than resolving this)

**Comment by TKDickson** [comment]
Working on detox. I've fixed [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/8617257874), checking to see if that also fixes iOS.

**Comment by TKDickson** [comment]
Does not require retesting in develop, closing.
