### ISSUE TITLE
Availability Framework - Set Warning Messages for Oracle Transition on 2/28

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8065]
On 2/28 at 12:01 CT, we need the following messages to appear:

|           Message          | Location                     | Date displayed | Date removed |
|:--------------------------:|------------------------------|:--------------:|:------------:|
| Step 1 - Warning           | Health home page             | Feb 28         | March 4      |
| Step 1 - Warning           | Messages landing screen      | Feb 28         | March 4      |
| Step 1 - Warning           | Prescriptions landing screen | Feb 28         | March 6      |

Content can be found here: [mural link](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1706284632056/bd0898e9be89541a02ed5c50076ade10e7fe31ec?wid=0-1707247345487&sender=alayna1905)

## Acceptance Criteria
- [x] Message is set to appear on the Health home page
- [x] Message is set to appear on the Messages landing screen
- [x] Message is set to appear on the Prescriptions landing screen
- [x] Misty to review content and make sure it looks good
- [x] Tom to QA as possible

**Comment by dumathane** [comment]
![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/8d0c73c2-5770-4d77-81f4-1b97d3b60d48)

![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/ec99cbc0-0808-454e-9bcc-1c3ca4381c81)

**Comment by dumathane** [comment]
https://adhoc.slack.com/archives/C067S0FRP0C/p1709079411725839
Link for the update info. AF is now live and scheduled to start at midnight CST (GMT -6).
