### ISSUE TITLE
SPIKE - Work with MHV to update MHV policy for account eligibility 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8066]
Reach out to Oleksii Morgun as he has been gathering info from MHV and work with Patrick Bateman to discover what is necessary to update our policy checks for MHV. 

ACs:
- [ ] create tickets necessary to update vets-api to accurately detect MHV user account eligibility

**Comment by StacyB2023** [comment]
@jperk51 I moved this one into current sprint work. If it ends up that we do not have to play this ticket, you can just comment and close

**Comment by jperk51** [comment]
Currently being worked by Janie Tankard-Carnock and Oleksii Morgun of the web SM team. They are investigating if the existing session endpoint would cover what we need for now.

**Comment by jperk51** [comment]
Work to be done in #8032
