### ISSUE TITLE
BUG - SEV 3 - Demo mode - Incorrect copy in Notifications

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8075]
## What happened?
This bug is a follow-on bug related to [ticket 7393](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7393). As part of that ticket, we were updating copy on the Notifications screen. Originally I had asked for some copy changes to the toggle labels. But then learned the toggle label copy is pulled from an API and not hardcoded. ~~Until we could dig into whether it was OK to change the toggle copy, we removed those 2 ACs. But the wrong copy is still showing up in demo mode.~~

UPDATE on 3/5/24: I was able to get alignment with CAIA on updating this copy and get the VEText team to update API so we have the new copy I want showing. Now I just need demo mode to follow suit.

## Specs:

- Device: iPhone
- OS: SE
- User Account: Demo mode
- Accessibility State: n/a

## Steps to Reproduce

Sign in to demo mode, tap Profile, tap Settings, tap Notifications

## Desired behavior

Copy on Notifications screen should be the same in demo mode as it is in production.

## Acceptance Criteria
In demo mode, the toggle labels should read:
- [ ] Appointment reminders
- [ ] New secure messages

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 

- Impact: Low 
- Frequency: Low 
- 3 - Low

## Linked to Story
Related to [ticket 7393](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7393)

## Screen shot(s) and additional information
What is currently in demo mode:
<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c96e1f2104c26ebf3e9417dfd7f3768c803704c3/303739765-0c89ddaa-9dda-4f34-b59b-553cbf587168.jpg" alt="303739765-0c89ddaa-9dda-4f34-b59b-553cbf587168.jpg" />

What is should be:
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSt6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b763cb13266269e51069d1571459d5669100d975/IMG-0209.PNG" alt="IMG-0209.PNG" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [X] Steps to reproduce are defined
- [X] Desired behavior is added
- [X] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [X] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by mistymg** [comment]
Updated this bug description/ACs after getting approval for new copy and getting API changes from VETest team in [ticket 7701](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7701).

**Comment by TKDickson** [comment]
Switching to @rbontrager since @Sparowhawk is the Eng

**Comment by rbontrager** [comment]
Verified that the notifications wording in demo mode matches the wording in staging.  Approved by QA.
