### ISSUE TITLE
BUG - SEV 3 - All - Unread analytics not being captured appropriately

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8090]
## What happened?

We noticed after the first attempt at home screen capture analytics that the unread counts were not being captured at nearly the correct quantity. After review we found that when a '0' was the unread amount the analytics were failing to log, and we're changing that to be zero inclusive.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Attempted to run detox (worked on Android, didn't on iOS). Did a quick manual check of demo and staging modes to make sure nothing obviously broken, and confirmed with Rachael that what I was seeing was test flakiness (likely due in part to iOS/RN updates).

This ticket should be good to merge. I'll have it sit for an overnight develop detox run just in case.

**Comment by TKDickson** [comment]
Overnight iOS develop detox run failures last night were in prescriptions (which we didn't touch/have nothing to do with this change). Good to close.
