### ISSUE TITLE
Cerner Health Category Screen Alert

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8091]
- [Link to mockup](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3264-2449&mode=design&t=zkyR423EUd7gM2WP-4)

**Comment by TKDickson** [comment]
@ajsarkar28 @wavelaurenrussell Closing this ticket, assuming it was an HSP-related placeholder. Free free to reopen and add details if it should still be open.
