### ISSUE TITLE
Update datadog alert to consider endpoint traffic

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8109]
Right now we have a number of endpoints that trigger alerts when a single call fails because the endpoint is so low traffic. We need to figure out a way to incorporate # of errors into our alert trigger so these stop happening. 

ACs:
- [ ] Alerts now only trigger based on % and a significant number of instances of an error within the alert time frame

**Comment by jperk51** [comment]
Close the related task on this incident report: https://vagov.ddog-gov.com/incidents/226/remediation

**Comment by kpethtel** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/8109?planning-poker) with Zenhub @aherzberg @jperk51 @Tonksthebear

**Comment by aherzberg** [comment]
Dropping this for now in favor of https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8300 but I think a good solution may be to use the clamp_min function on the request hits of the monitor to keep low volume endpoints form triggering alerts. If not this solution, we may have to make two separate monitors where we put all the low volume endpoints in one monitor and manually set the threshold higher over longer period of time.

**Comment by aherzberg** [comment]
ended up adding the clamp_min function with a min of 10 requests. can change this as needed. closing
