### ISSUE TITLE
CU - Spike - Remove Pods directory from remote repo

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#8114]
## Proposed Change

Currently, we house the `ios/Pods` directory in the remote repo. This leads to faster install times in CI, but the downside is any changes to iOS native code has to have the Podfiles updates alongside it. This leads to many drawback including:
- Making PRs containing native iOS changes difficult to skim through due to the large number of Podfiles updated
- Issues with syncing local pod changes with the remote repo

This also doesn't seem like standard practice to push the `ios/Pods` directory to the repo, as many react-native projects seem to be ignoring the directory in their `.gitignore` file.

Instead of pushing Pods to the remote repo, we can store them in GitHub Actions cache to store the Pods, that way we'd get the benefit of faster CI times while not needing to manually push the Pods directory.

Relevant changes would be:
- [ ] Deleting the `ios/Pods` directory
- [ ] Adding the `ios/Pods` directory to the `.gitignore` file
- [ ] Storing/using cached Pods in the appropriate GitHub Actions workflows

## Why Should We Prioritize?

This would enhance the development process by removing the need to deal with Podfiles in PRs

## Coding Time Estimation

5
	
## Testing Considerations

This will need to be tested with on demand builds made off of the branch before it gets merged.

## Checklist
- [x] Add the relevant team label (Health, global, etc.)
- [x] Attach to the [Engineering Initiatives (Frontend)](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5139) epic

**Comment by timwright12** [comment]
This was completed elsewhere: https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.gitignore#L122

https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8207

Closing out
