### ISSUE TITLE
Inventory of external links in VA Mobile App

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#8119]
As a VA Mobile App designer, I want an inventory of all external links in the VA mobile app so I can determine how to standardize links going forward. Inventory should include the location of the link and the type of icon used, if any.

**Comment by alexandec** [comment]
## Inventory of existing links in the app

### Links with no icon
- Login screen: Find a VA location
- Home screen: Contact VA, Find a VA location, COVID-19 updates
- Veterans Crisis Line screen: VeteransCrisisLine.net
- Appeal Details screen with a merged claim or statutory opt in claim: Your claims and appeals
- Claim Details screen, What should I do if I disagree: Learn about your decision review options
- Upcoming Appointment Details, video appointment: join session
- Prescription History Not Authorized: Learn how to upgrade to a My HealtheVet Premium account
- Secure Messaging Not Enrolled: Learn how to upgrade to a My HealtheVet Premium account
- Secure Messaging: any link inside the message body
- Settings: Privacy Policy

### Links with horizontal right arrow icon
- Claim Details Take Photos: Go to VA.gov
- Claims Need Help: Go to VA.gov
- Disability Ratings: About VA disability ratings
- Health screen inside Cerner Alert: Go to My VA Health
- In-app Recruitment: Learn more about the Veteran Usability Project
- Letters, Benefits Summary Service Verification: Go to Ask VA
- Secure Messaging Terms and Conditions: Go to HealtheVet

### Links with diagonal arrow emerging from box
- Appointment Details: Go to VA.gov to find your VA facility
- Appointments - No Appointments: Visit VA.gov
- Appointment Details (canceled): Go to VA.gov to schedule
- Appointment Cancellation Info: Find your VA location
- Prescription History inside Cerner Alert: Go to My VA Health
- Prescription tracking details: tracking number
- Secure Messaging: Go to My VA Health

### Links with road sign icon
- Appointment Details: Get directions

### Links with calendar icon
- Appointment Details: Add to calendar

### Links with telephone icon
- All screens/components that link to a phone number

### Links with smartphone icon
- All screens/components that link to a text message number

### Links with TTY icon
- All screens/components that link to a TTY number

### Links with chat bubble icon
- Link to "Start a confidential chat" on Veterans Crisis Line screen

### Links that look like buttons, with button role
- Prescription details with transferred prescription: Go to My VA Health button

**Comment by alexandec** [comment]
@wavelaurenrussell I've added the results of my link inventory. The links are categorized by icon type.

**Comment by wavelaurenrussell** [comment]
Thank you. Shared these with @brea11y to weigh her recs against ours.

**Comment by brea11y** [comment]
@wavelaurenrussell – The missing links have been [added to the bottom of the audit results](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing) and highlighted in yellow. Most of them simply an icon added or changed. Some of them I couldn't test live (or with a screen reader), so I just audited based on them all being external links (or webview links) and with the assumption that the external links launch the "You're leaving the app" alert. Please let me know if you guys have any questions!

**Comment by alexandec** [comment]
@brea11y sounds good to me! I'm going to close this ticket since I don't see anything further to do here.
