### ISSUE TITLE
BUG - All - Getting error (404 record not found) when asking for claim evaluation

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8120]
## What happened?

A 'request could not be sent' error is being displayed when trying to submit a claim evaluation on staging.   Charles proxy is showing that we are receiving. "404 record not found" response (full response below)

## Specs:

- Device:
- OS:
- User Account: +54
- Accessibility State:

## Steps to Reproduce

1. Login to user +54 and navigate to claims
2. Open the submitted February 15, 2024 claim (if this no longer has file requests you will need to ask Therese/Narin to give you more). 
3. Select 'Review file requests'
4. Select 'Review evaluation details'
5. Check the checkbox and select 'request claim evaluation'. Notice the error.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL080QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f59a12d96ef57f3196da98273657e436abfd7a0c/screen-20240305-145020~2.mp4)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

```
{
	"errors": [{
		"title": "Record not found",
		"detail": "The record identified by 600482482 could not be found",
		"code": "404",
		"status": "404"
	}]
}
```
</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by jperk51** [comment]
@rbontrager Can you also provide which endpoint is returning this error?

**Comment by rbontrager** [comment]
This was a case where the user was set to lighthouse but needed to be on evss.  Once Jayson flipped it it worked. Closing this ticket as working.
