### ISSUE TITLE
Test plan review: Home screen personalization

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8140]
Link to Epic

**Comment by TKDickson** [comment]
Test plan review should cover:
* TestRail folder where cases are located (link)
* Will also be running accessibility (quick) cases on all tickets

Test plan review will not cover:
* Scope still TBD on how we're refreshing information on the category and home screens (#7728, #7477, probably other future tickets)
* "source of truth" links in TestRail. I'm delaying putting the Figma links in for as long as possible, in the hopes that by the time I put the links in (when testing), they'll be in a location that doesn't change after that point :crossed-fingers:

Helpful links:
- Home screen personalization epic: #3542
- [Error and edge case mural ](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?sender=59c3cb7b-c368-40b0-88eb-28482a86d764)- source of truth for basically all content for this epic
- [UI Handoff Figma ](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2723-814&mode=design&t=twfbJ3EoBJYo5UUO-0)- source of truth for all UI/UX, as well as accessibility behavior, for this epic

**Comment by TKDickson** [comment]
Reassigning from @rbontrager to @DJUltraTom

**Comment by DJUltraTom** [comment]
test plan is looking good so far, 
in the places where we still have "ADD LINK" for the the figma link, are we planning on updating that, or should new tickets kick off when those are getting ready to be implemented or are decided on?

**Comment by TKDickson** [comment]
@DJUltraTom I checked, and it sounds like we still don't have a permanent location for all of the Figma files, which is what I was hoping to have before adding the link everywhere. *sigh* But it sounds like the UX process is changing (no longer doing shipped files? or maybe not doing them in the same way?) so I'm going to add the links to the current location, which will be slightly better than "none at all"
