### ISSUE TITLE
BUG - SEV 3 - All - Crisis Line font size

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8169]
## What happened?

When going through Android build 1334, I noticed the font size is different from the [Homescreen mocks](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3306&mode=design&t=Te7GQU6zY3o1BPoZ-4).

## Steps to Reproduce

Navigate to any screen with the Crisis Line CTA, see the difference in font size when compared to the designs

## Desired behavior

The font size should adhere to the specs in the [mockup](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3053-3306&mode=design&t=Te7GQU6zY3o1BPoZ-4)

## Acceptance Criteria

Please ensure the font size is set to 16px.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

</details>

## Ticket Checklist
- [x] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
Found #8294 (precedes this change). Font/spacing looks good to me, and am going to double-check with Lauren.
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bd228d87d764e59a5120c9574244f7ef9fcad1b/image.png" alt="image.png" />
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29yQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--261fcec6ee822884e1dd2dd06dc52ebe0a633aa5/image.png" alt="image.png" />
<img width="565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cccff2df527074278241f4ca53ed193b8a00945/image.png" alt="image.png" />
