### ISSUE TITLE
Verify Detox Mapping makes sense for 8081 

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8170]
## Description 
I figured out how to get the files changed for a PR and how to change the file name to its relevant detox name for ticket [8081](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8081). This ticket is for one of my fellow QA's to check my mapping of the various files in the app to a) make sure I didn't miss anything dumb and b) make sure that the detox tests needed to run for each test look correct.  The link to my google sheet can be found here: [Detox Mapping](https://docs.google.com/spreadsheets/d/1gXrl4KSJVg4wO_JB5MU-_ZegeDVPKXz0MNDfSwUhwP8/edit#gid=0).

**Comment by TKDickson** [comment]
Made suggestions in the spreadsheet above & had a handoff conversation with Rachael, and have created stub tickets for the two enhancements coming out of this review #8194 and #8195
