### ISSUE TITLE
Skeleton Loader for Category Screens

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8173]
AC:
- When data has not loaded for the modules on the category screen, display a skeleton loader
- Accessibility should match what is outlined on the Figma

All functionality and design should reflect this [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3090-2380&mode=design&t=rWhVyIm0Vd3wmuFz-4) 

This ticket should have visual QA

**Comment by TKDickson** [comment]
Skeleton loader in Android with TalkBack is announcing as two things:
"Appointments, menu item" 
/
"Loading activity"

iOS VoiceOver is correctly announcing as all one thing.

**Comment by theodur** [comment]
Just pushed some changes, the Android behavior should be consistent with iOS now

**Comment by TKDickson** [comment]
Approved and merged to XL, closing.
