### ISSUE TITLE
Investigate immunizations issues

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#8176]
As discussed in [this conversation](https://adhoc.slack.com/archives/C0206QFMXFU/p1708452322246579), all immunization-related location lookups in staging are returning 404. These location urls are formed in the immunizations serializer. There may also be a discrepancy between the immunizations data being returned from lighthouse and what's in our VCR cassettes. It may be necessary to use the staging rails console in order to get more insight into the errors being returned. 

AC:
- update VCR cassettes if anything has changed
- determine why all location lookups in staging are returning 404

**Comment by jperk51** [comment]
This specific error is no longer showing up. Jason put in a fix a few weeks ago that seems to have resolved it. That being said there are a number of location_ids we get back from vaos that are returning 404s from lighthouse so I'm still gonna ask about it.
