### ISSUE TITLE
Add Spaceforce SVG Icon to App

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8184]
AC:

- Spaceforce SVG icon is added to the app
- When a Veteran is a part of the Spaceforce, display the spaceforce icon in all areas of the app that display branch of service icons
- Let Brea know that this has been added so the design library can be updated

**Comment by dumathane** [comment]
https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/site/assets/img/vic-space-force-logo.png

**Comment by dumathane** [comment]
Link for thread discussion:
https://adhoc.slack.com/archives/C063KLSMVAR/p1711635893168319

**Comment by theodur** [comment]
I updated the PR to use the new SVG ([Slack thread](https://adhoc.slack.com/archives/C063KLSMVAR/p1714059230926169?thread_ts=1714057914.394809&cid=C063KLSMVAR))

I confirmed the only difference between the two SVGs is the text color (and some very minor alignment of the logo above the text), so I just used the light theme logo and made the fill color changeable. This way, we only need 1 SVG in the app for SpaceForce, and can just set the fill color as we need to.

**Comment by TKDickson** [comment]
Logos now have appropriate contrast in light, dark and blue modes. Ready to merge.

**Comment by TKDickson** [comment]
Merged; closing.
