### ISSUE TITLE
Home screen personalization - merge develop into the XL branch

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8188]
We didn't explicitly ahead of time come up with a plan for keeping develop and XL in sync with each other, so now the home screen personalization XL branch is..... 500 commits behind develop (and counting).

This ticket is for the larger-ish upcoming one-off effort to merge develop back into XL, and then the FE team is expected to keep them in sync much more regularly/no explicit ticket from here to the end of the HSP XL branch.

ACs:

- [ ] Merge develop into the XL
- [ ] Do regression-testing that we haven't broken existing HSP functionality with the merge

**Comment by TKDickson** [comment]
Since we ended up with the new branch strategy, I'm going to just..... link to the draft PR from here and add the testing documentation I have from Rachael about what she did. 

@dumathane has said the plan going forward is to keep this HSP2 branch up-to-date with develop every day, and if there were major develop changes they'll ask the FE who made them to handle merge conflicts on this draft PR.

[Draft PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8215)
[Regression run that happened while I was out sick this week, on the draft PR](https://dsvavsp.testrail.io/index.php?/runs/view/5336&group_by=cases:section_id&group_order=asc&group_id=4180) (covers regression testing + HSP)

iOS detox seems to be broken, and that's still an area under investigation.

**Comment by TKDickson** [comment]
@theodur @dumathane the font for the iOS home screen activity buttons (in the skeleton loading on-demand build, which I assume is branched off of HSP2) is wrong now. Gotta assume that's dev-merge-related:
<img width="401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d46970257353be99bfe1c0b4c43fac7468c9d42f/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Confirmed this is also present in the bare bones HSP2 branch. Pinging in Slack to figure out what to do (new ticket?) because this ticket isn't actually associated with an open PR, for reasons.

**Comment by theodur** [comment]
The font issue with iOS should be fixed now, the `project.pbxproj` file got out of sync from the merge and didn't include the reference to the font asset

**Comment by TKDickson** [comment]
Done with initial merge testing. Will need to get detox working, but that's sufficiently captured by existing ticket #8102, so closing this ticket.
