### ISSUE TITLE
BUG - SEV 2 - All - Appointments: typeOfCare null using healthcareService

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8191]
## What happened?

When reviewing data on our Appointments screens, I found that where we're typically showing the typeOfCare field, there was information showing that wasn't an actual type of care. After some digging, Dylan advised me that when typeOfCare is null, we check if there's a healthcareService, and we display that instead. Only when there's no typeOfCare AND no healthcareService is when we show the null copy ("Type of care not noted").

This is a problem because we're not entirely sure what type of information we get back from the healthcareService attribute. In the screenshots in the section below, it looks to return information that looks like clinic names. This is confusing to users who usually see type of care (mental health, primary care, etc.) in this field. This is also a problem because Lauren and I are going to suggest including a heading labeled "Type of care" above this field. So we need to make sure that that heading is accurate and that the information that will be shown is truly a type of care (and not something else).

Mobile App BE engineers (Jayson & Kris) chimed in on DSVA to help us understand the healthcareService field. Jayson advised it was likely intended to be used for appointment scheduling (which we never implemented). He said that we can update the backend to just make it the equivalent of typeOfCare so it starts acting that way until we change the FE (which is the purpose of this ticket).

[Link to Ad Hoc Slack discussing internally](https://adhoc.slack.com/archives/C067S0FRP0C/p1710428152331039)
[Link to DSVA Slack discussing with Appointments team and our BE engineers](https://dsva.slack.com/archives/CMNQT72LX/p1710434118651729)

## Specs:

- Device: iPhone
- OS:
- User Account: Judy Morrison
- Accessibility State: n/a

## Steps to Reproduce

- Sign in on test device using Judy Morrison
- Navigate to past appointments
- Scroll to October 27, 2023 and October 10, 2023 appointments

The problem is occurring on both the list and details views of appointments. See example screenshots in section below.

## Desired behavior

When the typeOfCare field is null, we should show the null copy. We should not be using the healthcareService attribute as a back up for when typeOfCare is null.

## Acceptance Criteria

- [ ] Logic that shows healthcareService when typeOfCare is null is removed
- [ ] When typeOfCare is null, null copy is shown: "Type of care not noted"

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High
- Frequency: Low 
- 2 - High

## Screen shot(s) and additional information

<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01d62676bac4b10be2fff4940f96eeda7e39924e/IMG-0215.jpg" alt="IMG-0215.jpg" />
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFBsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b238d332f724cc9ee517d7d81c2080b7c78a69d0/IMG-0216.jpg" alt="IMG-0216.jpg" />
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFRsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--314734548305b0a8b2ff4059a3ddf76efad6bce2/IMG-0217.jpg" alt="IMG-0217.jpg" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [x] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by mistymg** [comment]
Note: Since Jayson said they'd can update the backend to just make it healthcareService equivalent of typeOfCare so it starts acting that way until the FE is changed...I'm not sure when BE is doing that or if that will affect our ability to test this.

**Comment by rbontrager** [comment]
@Sparowhawk The healthcare service is still showing in the appt preview in the list instead of 'type of care not noted' for confirmed/canceled in-person appointments.
