### ISSUE TITLE
e-folder deprecation/LH Integration: Discovery 

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8206]
## Description 

**Issue:**

- efolder is being deprecated. timeline TBD. Additionally, the FE would like to be able to show people what they've uploaded. 

**User Story:**
- In order for veterans to see what they uploaded/shared with VA, in-app we'd need to consider Lighthouse's Claims Evidence API

**As part of the outcome of this discovery, we would like to:**

 (1)Determine what API url we use for evidence viewing
 (2) LOE for integration with a new LH endpoint

## **Acceptance Criteria**
  

-  [ ] Document API URL and related information for integration
-  [ ] Create an corresponding tickets for Integration Implementation
-  [ ] Note any dependencies/bottlenecks

**Comment by StacyB2023** [comment]
@jperk51 Im reviewing the channels,did they ever state a timeline for this one? (the actual deprecation)

**Comment by jperk51** [comment]
@StacyB2023 are there any threads where this was being discussed? We are already integrated with the LH doc upload API as part of the EVSS transition. My expectation would be that LH would manage the e-folder depreciation problem and it would be transparent for consumers of LH.

**Comment by StacyB2023** [comment]
Adding the original thread slack to this ticket: https://dsva.slack.com/archives/C018V2JCWRJ/p1710438102498869

**Comment by jperk51** [comment]
Should need any work for current functionality. If we want to have a "view all uploads" type feature for the app we would need to integrate with some new endpoints, but either way the "efolder" related changes should be handled by LH.

**Comment by StacyB2023** [comment]
Moved to Blocked: Currently we don't show the users what they have and havent uploaded and the submission is covered by our current implementation so really this is like a new feature request (viewing uploaded docs in the "efolder")

**Comment by Tonksthebear** [comment]
Does that mean you're ok with me closing this ticket?

**Comment by jperk51** [comment]
Blocking this until we get PO guidance. Efolder is going away, but right now LH has an endpoint for returning a users docs that we would like to integrate with. That endpoint uses the efolder and we working on trying to convince lighthouse to agree maintain their endpoint and its data shape then integrate with the new solution when it's decided. Either way, if the POs say go ahead we'll integrate with the LH endpoint then do whatever we have to do in the future once the new solution is finalized. cc: @DonMcCaugheyUSDS

**Comment by jperk51** [comment]
The earliest estimate of VBMS going away is march 2025 so we will move forward with integrating with the existing vets-api (VBMS) download config then when the alternative is actually created we will migrate to that. Based on the thread people seem to think march 2025 is very unlikely to actually happen like most migrations, but we should be good either way.

**Comment by jperk51** [comment]
#9773 and #9774 are the implementation tickets for getting the docs list and then downloading the doc
