### ISSUE TITLE
Write vets-api script (or however else to do it) to automatically update lighthouse maintenance windows

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8232]
It seems lighthouse does not update their maintenance windows on PagerDuty, only their own [website](https://valighthouse.statuspage.io/) that specifies each endpoint's status. Questionable if we should be the ones in charge of this, but, if that is the case, here is the ticket.

Relevant comment in a relavant thread: https://dsva.slack.com/archives/C02CQP3RFFX/p1710898663281229?thread_ts=1710861192.369069&cid=C02CQP3RFFX

**Comment by kpethtel** [comment]
Alternatively, this script could be added to actioner.
