### ISSUE TITLE
(GHA) Verify builds work in PRs with relevant changes

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#8267]
## Description

There are instances where we may want to confirm that changes in a PR didn't break the app build. This would serve as a gate to prevent changes that don't require manual QA from being merged into `develop` without confirming the build still works. This is mainly a concern when updating the folders for native code, e.g. `VAMobile/android`, `VAMobile/ios`.

## Acceptance criteria
- [ ] Determine which scenarios a build should run in CI for verification
- [ ] Update the CI workflow to run a test build when those scenarios occur in PRs

**Comment by timwright12** [comment]
Kicking this over the the release team (cc: @bischoffa )

**Comment by bischoffa** [comment]
Added this to DevOps Q3 epic for consideration. Will need to be reviewed and sized before being worked so moving the ticket to New Issues column
