### ISSUE TITLE
BUG - Sev 3 - android - on screen keyboard does not dismiss when cancelling out of contact information screen

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8283]
## What happened?
when editing the contact information screen and tapping "cancel", the on screen keyboard does not dismiss and covers the action sheet

## Specs:

- Device: pixel 4A
- OS:
- User Account: N/A
- Accessibility State: N/A

## Steps to Reproduce
go to "Profile > Contact information"
Tap into address field 2 and enter some text
Tap into address field 1 and as the header reappears, tap "cancel"
observe the On screen keyboard does not dismiss and the action sheet is not visible

## Desired behavior

On screen keyboard should dismiss

## Acceptance Criteria
TBD

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency:  Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by TKDickson** [comment]
@DJUltraTom pinging on this again. Will also ping in Slack.

**Comment by DJUltraTom** [comment]
still seeing it:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d19f55b1f4e260ec3c62e4db62ae72ebc351def2/az_recorder_20240515_140625_edited.mp4)

**Comment by TKDickson** [comment]
not currently testing (over limit)

**Comment by TKDickson** [comment]
Picking up as one of my 3

**Comment by TKDickson** [comment]
Bah. I could have saved time re-reading that this doesn't happen on my devices. 

@DJUltraTom would you be able to check this out, either this sprint or next? The build is Android 1713 "8283 keyboard and cancel now"

**Comment by TKDickson** [comment]
Reassigned to @DJUltraTom

**Comment by DJUltraTom** [comment]
Verified the OSK dismisses and action sheet now takes precedence
QA approves this fix

**Comment by DJUltraTom** [comment]
Validated fix works on overnight QA build, QA approves, closing as deployed
