### ISSUE TITLE
BUG - sev-2 - All - Majority of maintenance windows no longer working

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8291]
## What happened?

I'm guessing it was the React Query changes? But whatever the case, the majority of maintenance windows are no longer working, off a build from develop (for ticket #8067).

I put the exact same range for all of the maintenance windows (2 months ago to 1 month from now), and then logged in.

Did not display maintenance window UI/broken: Immunizations, Disability rating, claims, decision letters, letters, payment history, direct deposit, military history

Did display MW UI/working: Appointments, messages, Rx, personal info, contact info

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Acceptance Criteria

All features should correctly display downtime info when in downtime.

UI similar to (or identical to, if #8067 is in there) this:
<img width="397" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUFtQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ff5fe00ab03d1085db83524e6ead096f3177df8/image.png" alt="image.png" />

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the [bug epic](https://app.zenhub.com/workspaces/va-mobile-product-view-610035bc5395bb000e62e529/issues/gh/department-of-veterans-affairs/va-mobile-app/5367)

**Comment by rbontrager** [comment]
Talked with Binny and he says this will be fixed in home screen personalization and verified with [7967](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7967). 

I confirmed that all maintenance windows work with react query and that Dylan is adding the same logic to any new react query changes.
