### ISSUE TITLE
Bug & Maintenance/ Tech Debt Mgmt - API Service Team (Q2)

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#8304]
**STATUS: IN PROGRESS**

### Monthly Update for Stakeholders

 
|Date| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|5/6/24 | In Progress. | N/A-Continuous| No Blockers
|5/21/24| In Progress | N/A-Continuous| No Blockers
|6/6/24|In Progress| N/A-Continuous| No Blockers
|6/26/24|In Progress| N/A-Continuous| No Blockers
|7/8/24|In Progress| N/A-Continuous| No Blockers
</details>

## Purpose of this feature:
- for Bug and maintenance tickets AND Tech Debt
- Only bug tickets that have been scrubbed (reviewed by QA indicating they are ready to be reviewed by engineering)
- Prevent a large culmination of tech debt backlog

**Comment by StacyB2023** [comment]
@kellylein Let's discuss on our 1:1

**Comment by StacyB2023** [comment]
Moving issues labeled as "new" or "blocked" into the Q3 Epic for Bugs/Tech Debt so we can close this one out for Q2. cc: @jperk51

**Comment by StacyB2023** [comment]
Q3 Epic: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9001
