### ISSUE TITLE
Bug & Maintenance Mgmt - QART - Q2

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#8305]
## Purpose of this feature:
- For Bug tickets and maintenance tasks
- Only bug tickets that have been scrubbed (reviewed by QA indicating they are ready to be reviewed by engineering)
- Prevent a large culmination of tech debt backlog

# Project Status Overview

### Project Objective:

Work and effort for Quality Assurance and Release Management (Qart) Team to manage team specific bugs, maintenance tasks and technical debt in order to prevent a culmination of technical / coding debt. 

Items may include:

- Qart specific bugs
-  Testing Automation / Detox fixes and enhancements 
- Manual testing fixes and enhancements 
- Creating new or updating Qart specific documentation 

 

### Stakeholder Updates

|Date | Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|April 2024 | Green | Prioritized for Q2. Per VA PO 30% of Qart capacity will work on bug, maintenance and technical debt. That capacity will go to here or to the external team prep epic.  Qart determined that all detox work and detox bugs will be part of this epic vs having a separate epic.  | None at this time | 
|5/6/24| Green | Working on detox tests that are breaking due to new code being pushed out. This will continue to happen until FE gets educated on doing Detox tests vs only having QA do it which is a goal for Q2. | None | 
|5/20/24| Green | Rachael was able to get caught up on Detox tests that were broken due to new changes introduced by Mobile teams. Still working towards getting FE educated so they can self-service some aspects of Detox needs when they change / add code. Given unplanned work that is appearing in H&B that is pulling in Rachael, the plan next sprint is for Rachael to start this work before H&B | Unplanned work is pulling Rachael away more than expected. | 
| 5/29/24 | Green | QA and Release Team implemented 3 WIP ticket limit. Meaning that QA team can only be actively working on 3 tickets at a time. Any others will remain in the backlog to pull from once they complete any of the 3 tickets. Rachael is exploring additional improvements to Detox to improve the ease of mapping to reduce human error through Github actions. | No blockers |
|6/7/24| Green | QA spending its on technical debt to test untested code that H&B pushed out with React Query instead of waiting for Global to prioritize the work after Homescreen Personalization Work. Felt this was needed sooner given the concern it caused.  Verified access to perform Claims File Requests and coordinated new test device to UX. Detox maintenance  and strategy to enable FE to perform some detox work by end of Q2. | No blockers |
|6/17/24| Green | No new update since last post given Offsite was last week | No blockers |
|6/26/24| Green | Used QA tech debt to test the untested production code for React Query that was released instead of waiting to when Global is able to prioritize it after HSP.  Found a RQ bug related to contact / personal info 8901. Review and findings will be demoed at the next Mobile Demo. Updated several ticket templates - VA Call Center Guide Update,  App Store Updates (images, content), Release Candidate Testing. Updated Android App Support Website. During offsite new devices were provided to Brea and  | No blockers | 
|7/10/24| Green | Updated RC ticket template. Team meeting to review the 3 ticket WIP policy and future improvements. Team decided to continue with the WIP 3 ticket limit. Updated the Va.gov Marketing Page App Store updates to include Alt Text file. Update the Android App Store App Support Website link. Multiple detox updates while also creating Detox Best Practices which will help in Q3 when FE starts doing detox work instead of just Rachael. | No blockers. | 
|7/24/24| Green | Worked on a couple detox bugs that came up cause of HSP changes. Completed an assessment to see what process are known by a single person or more so that we can ensure multiple people can handle certain processes or issues. RC branch was recut as Global did not get their App Store Images changes done before the end of the sprint. Q3 planning in which another epic was created for Bugs/Maintenance just for Q3 and have to move over the backlog of tickets to the new epic.  | No blockers| 

|8/7/24|
|8/21/24|
|9/4/24|

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal & external dependency  | None at this time  |
| Internal & external dependency | None at this time  |
|  |   |

</details>

# Detailed Project Scope 

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.) Team will use their full capacity allocation for work on bugs and tech debt 
 
 2.) Work in this epic is purely for QA, anything tied to mobile app features (Global or H&B) will be part of their unique bug epics 
 
 3.) QA will be able to spend their allotted capacity on this epic vs being taken up by Flagship App / Platform teams which has happened in past quarters 
 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.) Team's capacity for bugs / tech debt is pulled off for other work (unplanned, underestimated, change in priority) 
 
 2.) Team appropriately add bug and severity labels 
 
 3.) Team adds Bug and Severity level to ticket name 

 
 
</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Qart specific work | Flagship, Design System, API, H&B, external team specific tickets | 
| | | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>
 
- Github Epic
-[ Github Qa and Release Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release) 
- [Github Bugs Details ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Bugs)
- [Board with Bug Label ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug)
- [Board with Sev 1 Label](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-1)
- [Board with Sev 2 Label](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-2)
- [Board with Sev 3 label ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-3)
- [Bug Tracking for Q2](https://docs.google.com/spreadsheets/d/1Uehnj7xRQIQhN_ilWobAddTYdatAyifVfXO2Tl9huww/edit#gid=0)

</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Don McCaughey

**Ad Hoc:** 
- **Mobile Team**: Qart
- **Mobile Team PM:**  Adam Kasmier 
- **FE Engineering:** None 
- **BE Engineering:** None
- **Design:** None 
- **Content** None 
- **DevOps** None
- **QA:** Therese, Tom, Rachael  
- **Mobile Teams that are involved:** Qart, may need to pull in engineering if need calls for it 

</details>

**Comment by bischoffa** [comment]
Discussed during PM sync on 4/3. VA Technical PO would like to allocated 30% of capacity to bug mgt.

**Comment by bischoffa** [comment]
This will be an ongoing epic. However a new epic will be stood up for Q3 as typically epics are asked not to rollover quarter to quarter.

**Comment by bischoffa** [comment]
q3 new epic [9029](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9029)

**Comment by TKDickson** [comment]
Closing; Q2 is over (we're using the new epic above) and all tickets associated with this epic are also closed.
