### ISSUE TITLE
BUG - sev-3 - All - Header dropshadow disappears when screen reader is on (light mode only)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8317]
## What happened?

The dropshadow on the header (which shows up in develop when you're scrolled far enough down on the screen that the header transitions from VA to the page-specific screen title) disappears when the screen reader is turned on.

This drop shadow only exists in light mode; so this only impacts light mode.

Screen reader off (has dropshadow):
<img width="383" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUE4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--766a97392fb4f8104d43feae4429fac9d1e8cc02/image.png" alt="image.png" />

Screen reader on (no dropshadow):
<img width="373" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUU4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7176d0168e9f9a0712ef16f31ada5b4fcead153f/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Drop shadow should remain (sighted users also use screen readers, so having the visual cue that there's scrolling is still relevant)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
This is one of the "fix only if it doesn't increase code complexity" tickets currently slated for this sprint

**Comment by theodur** [comment]
@TKDickson In the codebase, the header drop shadow is intentionally turned off screen readers

https://github.com/department-of-veterans-affairs/va-mobile-app/blob/06ce71169261f6cc3f60f61aafe0de5dc3b377bb/VAMobile/src/components/Templates/HeaderBanner.tsx#L147-L154

These changes are from this [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/5047):

> The resolution also hides the header drop shadow when screen reader is on--mostly as the most convenient way to address not appear on content (Veteran's Crisis Line) that is flush against the header, but also because it's visual fluff that is unlikely to benefit a screen reader user.

**Comment by TKDickson** [comment]
Perfect, thanks @theodur! Closing.
