### ISSUE TITLE
Investigate appt can't be cancelled

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8326]
We get a large number of 400s from appts cancel attempts. Try to figure out why and if it's something we can preemptively determine create a ticket to implement the necessary update to appts list endpoint. 

[datadog logs](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28activePanelKey%3Atrace%2Cresource%3A%28resourceName%3AMobile%253A%253AV0%253A%253AAppointmentsController%2523cancel%2CresourceID%3A13f1b244ed199f13%29%2Ctrace%3A%28traceID%3A3054469738905014149%2CspanID%3A4107976868815989844%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Acancel%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=4107976868815989844&spanViewType=metadata&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Acount%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1712329386872&end=1712588586872&paused=true)

ACs:
- [ ] if needed create implementation tickets to preemptively stop users from requesting cancels on appts we know can't be

**Comment by Tonksthebear** [comment]
Working theory is that this is caused by the appointment flipping from cancellable to not cancellable. This is looking like a front end fix.

https://adhoc.slack.com/archives/C0212B872MT/p1712959566039429
