### ISSUE TITLE
Remove SM policy feature flag

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8328]
New SM policy has been live and successful in prod for long enough that we're confident we will be sticking to it going forward. 

ACs
- [ ] feature flag is removed
- [ ] old sm policy logic is removed from mobile module
- [ ] tests updated

**Comment by Tonksthebear** [comment]
On the PR, there were instructions for how to finish cleaning up the Flipper on other env. I took care of staging but I'm waiting to officially close this until we get confirmation that prod has been cleared. I reached out to platform and they're going to take care of it today
