### ISSUE TITLE
Investigate why people aren’t seeing their appointments in the app

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8329]
Figure out what logging is necessary to determine why some users are not able to see their appts. If you need to log PII follow [these](https://depo-platform-documentation.scrollhelp.site/developer-docs/personal-identifiable-information-pii-guidelines) guidelines 

[Slack thread of details](https://dsva.slack.com/archives/C018V2JCWRJ/p1711732422072909)

ACs:
- [ ] determine why users are getting empty appts lists on mobile but not on web
- [ ] if not add logging necessary to be able to make that determination

**Comment by kpethtel** [comment]
Wrote and ran a script for fetching appointments the mobile way and web way on production multiple times across a few days. Same results each time. All web appointments were present in mobile, except ones that we explicitly filter out to match web front end filter rules. This was all exactly as expected. We were unable to determine why this is happening. 

Conversation on slack: https://dsva.slack.com/archives/C018V2JCWRJ/p1713901564998119?thread_ts=1711732422.072909&cid=C018V2JCWRJ
