### ISSUE TITLE
BUG - Sev-3 - [iOS] - Infinite rendering loop in header

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#8334]
## What happened?

An infinite rendering loop in the HeaderBanner component causes the app to become completely unresponsive.

I was able to reproduce this consistently in multiple different iPhone simulators, in demo mode. Other engineers have not been able to reproduce it. I could not reproduce on my physical iPhone, only in the simulator.

In fixing this, need to make sure that  [#8310 Header text missing with SR staying on](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8310) remains fixed. The fix for that bug is what caused this new issue to arise.

## Specs:

- Device: iPhone simulator only (not physical phone)
- OS: iOS 17.4
- User Account: Demo mode
- Accessibility State: Screen reader off

## Steps to Reproduce

- Run iPhone simulator on develop branch
- Login with demo mode
- Navigate to any other screen after login
- App becomes unresponsive to all input

## Desired behavior

App should function normally

## Acceptance Criteria

- App is responsive to user input in demo mode, while navigating between pages
-  [#8310 Header text missing with SR staying on](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8310) remains fixed

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Doesn't need retesting in develop; closing
