### ISSUE TITLE
BUG - sev-2 - All - excludeProvidedMessage boolean not respected in v1 thread api call

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#8346]
## What happened?
When migrating FE SM api calls it was discovered that `/v1/messaging/health/messages/${messageID}/thread?excludeProvidedMessage=${excludeProvidedMessage}` did not respect the boolean excludeProvidedMessage. If that field is present in the query it excludes the message no matter if it is true or false. This wasn't discovered in FE prior to this because we manually did some stuff with the thread in our redux state before. 

## Specs:

- Device:
- OS:
- User Account: +226
- Accessibility State:

## Steps to Reproduce
In the app navigate to view a message that is new(it should have no messages in the thread, then tap the reply button. This screen should have the original message in the thread. The only thing that changed was that instead of excludeProvidedMessage being true it is now false. Meaning the api isn't respecting the boolean value.

## Desired behavior
The api should respect the boolean value.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
@rbontrager @DJUltraTom this is already in production (because its an API ticket that's been sitting for 5 days), have one of you tested this?

cc @bischoffa

**Comment by bischoffa** [comment]
FYI @StacyB2023

**Comment by bischoffa** [comment]
@StacyB2023 @rbontrager @DJUltraTom following up on last weeks comments

**Comment by StacyB2023** [comment]
@DJUltraTom : Tom any update on this? Looping in @kpethtel also who may have some background on this. We have this noted as with QA from the API backlog side and not in our bucket

cc: @bischoffa

**Comment by bischoffa** [comment]
@kpethtel @DJUltraTom checking in. 

@StacyB2023 not sure if Tom is working this as he is not assigned to it. No QA is assigned to this ticket. 

Ticket is tale for 19 days

**Comment by bischoffa** [comment]
Per Dylan this was resolved during the SM RQ testing that is currently passing. So by testing SM RQ migration this ticket is tested so not specific work / action needed by QA on this ticket.  [Slack thread](https://adhoc.slack.com/archives/C0206QFMXFU/p1714490963282369)

**Comment by bischoffa** [comment]
@Sparowhawk @StacyB2023 

Dyland can you please close this ticket if you think it has been resolved based on your comments above.

**Comment by bischoffa** [comment]
@Sparowhawk can you close this ticket based on your comments above. Stale for 40+ days

**Comment by bischoffa** [comment]
https://adhoc.slack.com/archives/C0206QFMXFU/p1716995635988709

**Comment by TimRoe** [comment]
Jayson closed, but tagging @timwright12 for visibility as I assume that's who Adam meant.
