### ISSUE TITLE
Feedback Hub: Add some contact info to site

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8359]
**## Description** 
Let's add some VA Mobile credit and contact info to the feedback hub website!

**Acceptance Criteria:**

- [ ] Add VA Mobile Feedback Hub as the site header/H1
- [ ] Can we add VA Mobile Feedback Hub as the `<head><title></title></head>`?
- [ ] Add "For more info: VA Mobile on Github" in the footer/bottom of the site

**Accessibility Requirements**

- [ ] Make sure we're using an h1 for the site header

**Comment by StacyB2023** [comment]
@jperk51 @Tonksthebear @drjecker Added to pending handoff so we can get this ticket estimated next week.

**Comment by Tonksthebear** [comment]
Upping to a 5 because I'm going to make other improvements as well, such as sortable table
