### ISSUE TITLE
BUG - sev-3 - All - "JSON parse error: Unexpected EOF" is.... most of our errors apparently

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8360]
## What happened?

39 million (67%) of our errors in the `vama_error` event, over the time we've been logging it, are "JSON parse error: Unexpected EOF"

I'd love to cut our total errors by 2/3! Let's investigate where this might be coming from. Likely this will involve a request for pulling better data out of BigQuery to be able to look into it.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Bringing to handoff to figure out what FE would need to look into this

**Comment by theodur** [comment]
After looking into this, I noticed the screen that this error is most occurring on is the Sync screen. The most frequent call stack param value for the `vama_error` event is the infamous `Access token JWT is malformed` error, and the endpoint this seems to be occurring on the most is the `/v0/user/authorized-services`. 

This implies that the authorized services query is being called before login is complete. Even though this was somewhat fixed a while ago, this may have been reintroduced in https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8481. The queries on the Sync screen (services history, and disability ratings) both [use](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8481/files#diff-4c6093a14ca19645cd0ec831e7465739521c82ade40b3bfb9bb1f28d5fe7384cR34) the authorized services query internally. Even though the authorized services query was [disabled until login](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/release/v2.32.0/VAMobile/src/screens/SyncScreen/SyncScreen.tsx#L39-L41) on the Sync screen, the authorized services query called in services history and disability ratings did not have the authorized query disabled until login, so this was still attempting the auth services API call in the code of those 2 queries.

With the home screen personalization changes that are launching in v2.33.0, the authorized services query is [blocked](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/release/v2.33.0/VAMobile/src/api/authorizedServices/getAuthorizedServices.tsx#L30) at the root from executing until login is complete. So regardless of where the auth services query is being referenced, it won't make the API call until login is complete. I expect the number of `vama_error` events to go down once HSP is released. We can keep this ticket open until we confirm the number goes down in the upcoming release

**Comment by theodur** [comment]
I moved this to the `Code review` lane while we wait for data from the upcoming release to avoid confusion that it's actively being worked

**Comment by TKDickson** [comment]
@theodur filtering to the 2.33 release (orange in screenshot, whereas all releases over the same time period is the blue), I'm not seeing any "JSON parse error: Unexpected EOF". I scrolled through the whole list; screenshot is just where it would show up in the list if it was happening at roughly the same frequency as pre-2.33.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFVuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a59a2732217ac3f56a971e025b0b0e0cb30e287/image.png" alt="image.png" />

**Comment by theodur** [comment]
@TKDickson Nice! That's what I was expecting to see with 2.33. It also looks like the total event count has decreased. Usually the event count naturally drops over the weekend (Friday-Sunday) because I assume fewer veterans are using the app those days, and typically Monday-Thursday the count stays mostly consistent. On Wednesday, July 31, I'm seeing a large dip in the number of events from the previous day (more than 100,000 lower)

<img src="https://github.com/user-attachments/assets/10c8a7e5-d343-4cfe-b549-9515746884e2" width="49%" />&nbsp;&nbsp;<img src="https://github.com/user-attachments/assets/a0ef189e-f104-44d7-9ab7-da1401851048" width="49%" />

So it definitely looks like the release is already dropping the number of `vama_error` events.

**Comment by TKDickson** [comment]
Can confirm that with 2.33 (and 2.34 now) I'm not seeing any JSON parse error: Unexpected EOF errors in our error logs. Closing this ticket as fixed!
