### ISSUE TITLE
Add some branding to site (V2)

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8363]
## Description 
Let's add some VA branding to the feedback hub website

Some UX/design options to consider:

- [ ] Use VA fonts and colors
- [ ]  Create/add an updated icon to site (also use as a favicon?)
- [ ]  Suggest any other improvements

**Acceptance Criteria:**

- [ ] Outline or mockup suggested changes and share with @drjecker 
- [ ] Incorporate any feedback
- [ ] Hand off to eng

- 

**Accessibility Requirements**
- [ ] Make sure any suggestions follow WCAG 2.2 guidelines

**Comment by drjecker** [comment]
Per a convo with @brea11y we are going to:

Tinker with the header. Specifics:
- [ ] Try adding some color
- [ ] Try some text alignment for menu items
- [ ] Move site title into header space
- [ ] Try out another icon for the logo space (which we can use as a favicon for the site)

Search box layout
- [ ] Consider some alternate layouts (current things to look into include odd borders at breakpoints, and the full width search button)

Other suggested updates:

Table 
- [ ] for data in Title and Content columns remove whitespace nowrap so the text wraps in those cells

Search button 
- [ ] use VA colors (exact specs TBD)

Typography 
- [ ] use [Public Sans](https://fonts.google.com/specimen/Public+Sans) 

Links 
- [ ] use VA colors (exact colors TBD) 
- [ ] include underline
- [ ] remove target="_blank" from external links
- [ ] add aria info to external links (specs TBD)

**Comment by brea11y** [comment]
Due to some possible upcoming changes, @drjecker has asked that I hold on this work for now. Moving this to the Icebox column for now, but can resume work when we're ready to move forward.

**Comment by StacyB2023** [comment]
Closing this epic. Any pending, blocked tickets have been moved to the Q3 epic

cc: @Tonksthebear
