### ISSUE TITLE
Qart External Team Onboarding Procedures - Preparation  Q2

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8364]
# Project Status Overview

### Project Objective:

Work and effort for Quality Assurance and Release Management (Qart) to onboard external teams that will be engaging with Mobile Platform. 

Items may include:

- Documentation to explain what QA does
- Documentation to explain mobile app release process 
- Developing QART standards and expectation on tickets they are supposed to work 
- Establish a release process that involves VA PO that are no the VA Mobile POs 
- Documentation on how to engage with Qart from start to code release 

 

### Stakeholder Updates

|Date| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|April 2024 | Green|  Epic prioritized for Q2. Tickets moved from old epic to this epic. Adam is working with Therese on prioritizing applicable tickets. Adam and Tom are collaborating the first couple sprints (until he gets pulled in by Platform) to draw out the topics needed for external onboarding then working to fill in the material. We have identified that QA has a lot of existing information but some may be old from past PO requirements which will need to be reviewed and updated. | None | 
| 5/6/24 | Green | Tom and Adam collaboration continuing. Confirmed documentation to be put it the VA Mobile Docs site. Drafting topics that we want to include then will prioritize them and start writing / pulling in content. Starting with a Google Doc then will move into VA Mobile Doc site when topics are completed | Do not fully understand how an external team will work with Mobile|
|5/20/24| Green | Tom and Adam drafted up a topics list. Gathered all existing docs from Mobile Doc Site, Github, and Google Docs to see what kind of topics we currently have. Then going to start drafting content with an external party as the main focus. Starting next Sprint Tom is losing come capacity on this to work on Design System Testing Experiment. Therese collaborated with VA Mobile PO Don in setting Operating Limits for the App [7601](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7601).   | There is a lot of topics to sift through and currently  do not fully understand how an external team will work with Mobile | 
|5/29/24| Green | Topics and content for QA Onboarding of External team have been consolidated into a [single document](https://docs.google.com/document/d/1KWoGh1R0XOdnOObWLs6JtyoRrSPmmHnVLLFBp-7B4DI/edit). Content still being developed. Next steps is to get Qart feedback then others | Tom is being pulled off to help with Design System testing experiment | 
|6/7/24| Green | Document content still being worked on. Received feedback from Tom and have made changes. Created 1 new policies - [Handling Untested Code in Production](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Handling%20untested%20code%20that%20went%20out%20into%20production.md) and started to draft up another for [Handling Multiple Large Changes in a single release](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Enabling%20Multiple%20Large%20Changes%20in%20a%20Single%20Release.md) | Do not fully understand how an external team will work with Mobile so drafting content with loose expectations | 
|6/17/24| Green | Limited update given offsite that happened between last update and this one. Drafting policy on how Qart will handle finding untested code in production which was derived from the React Query project / experience  | Do not fully understand how an external team will work with Mobile so drafting content with loose expectations.  |
|6/26/24| Green | High level review with Kelly and a detailed review on the RACI portion of the document. Updated the RACI to align with Step 0 - Step 4 process. Plan is to have QA timebox and review the document next sprint. Consolidated all Github related topics for QA and Release into a single place in [Github  ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release). Drafting a policy for[ handling multiple large changes in a single release ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Enabling%20Multiple%20Large%20Changes%20in%20a%20Single%20Release.md)and finalized a p[olicy on handling untested code what goes out into production](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Handling%20untested%20code%20that%20went%20out%20into%20production.md) |  Do not fully understand how an external team will work with Mobile so drafting content with loose expectations | 
|7/10/24| Green | Reviewed RACI document with Matt and created a separate doc for for Product with just the RACI. QA team to complete the review of the External Onboarding doc by end of sprint. Migrated Ad Hoc Content Library QA information into Qart's Github page. |  Do not fully understand how an external team will work with Mobile so drafting content with loose expectations | 
|7/24/24| Green | External team onboarding doc has been reviewed by all of Qart. Next step is to implement those changes and then determine location. Originally was going to be on the doc site but now the doc site is for internal and external use only so need to rethink how to handle that to reduce confusion and also overwhelming external teams with all the information. Given this, this epic will spill over into early Q3.  | Do not fully understand how an external team will work with Mobile so drafting content with loose expectations | 
|8/7/24|
|8/21/24|
|9/4/24|

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal & external dependency  |  Determination on how the external team will engage with Mobile - through Flagship or directly with Qart |
| Internal & external dependency | Determination on how non-Mobile VA POs are involved in the release process |
|  |   |

</details>

# Detailed Project Scope 

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.) Have enough information to put together a process in how to interact with an external team
 
 2.) Ability to spend our tech debt capacity allocation on this epic vs being pulled off on other work 
 
 3.) Topics and content will be prioritized based on needed
 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.) There is uncertainty on the timing and how the external team will collaborate with an external team. This unknown will influence documentation, process and collaboration needs. June 2024 per POs sounded like no one will be onboarded in 2024. 
 
 2.)  Mobile Teams having Qart do more work than their planned capacity for that team, which has been an occurrence since last quarter 
 
 3.) 
 
 
</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| | | 
| | | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>
 
- [VA Mobile Doc ](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/)
- [Mural Board on Brainstorming External Work](https://app.mural.co/signin?invitationToken=&returnUrl=%2Ft%2Fadhoccorporateworkspace2583%2Fm%2Fadhoccorporateworkspace2583%2F1713280769477%2Fe73933dc7cc9b9f08106086f0e12c5f80c77d053%3Fsender%3Du7ec1ac1ea3bde48882e36908&title=&viral=true)
- [Write up from Mural Board](https://docs.google.com/document/d/1IzNyB3C65es7pPZ2KciU36Waq2Q453BLb6hDc7UnzKU/edit)
- [Inventory on topics from VA Mobile Doc ](https://docs.google.com/spreadsheets/d/1RBRQdMIZWmBkSfPKvEPTGXpx9bRP84U6--h5AR7XgP0/edit#gid=0)

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Rachel Han or  Ryan Thurlwell
- **VA OCTO Product Leads:** 
- **External Team 1 & Role:**
- **External Team 1 & Role:**

**Ad Hoc:** 
- **Mobile Team**: Qart
- **Mobile Team PM:**  Adam Kasmier 
- **FE Engineering:** None 
- **BE Engineering:** None
- **Design:** None 
- **Content** None 
- **DevOps** Charnelle
- **QA:** Therese, Tom, Rachael  
- **Mobile Teams that are involved:** Global, Health and Benefits, Design System, QA, API 

</details>

### Questions 
<details>
<summary>Open Questions</summary>
 
 -VA Mobile Doc site is public to all - any concern? 
 
</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer | Owner |
|--------|----------|------|
| What document tool will we used for the external team | VA Mobile Doc Site | Tim April 2024 |
| Should the VA Mobile Doc site be written just for an external perspective  | Yes | Tim April 2024|

</details>

**Comment by bischoffa** [comment]
Target date is end of this quarter. Carry over work will result in a new epic for next quarter.

**Comment by bischoffa** [comment]
This work is carrying over into a new epic for Q3 planning given epics were not allowed to carryover over in past quarterly planning per POs and Ad hoc Leads . Go here for the [new one ](https://github.com/orgs/department-of-veterans-affairs/projects/823/views/13?filterQuery=ext+&pane=issue&itemId=70481950)

**Comment by TKDickson** [comment]
Closing this Q2 epic; outdated
