### ISSUE TITLE
Establish Feature Testing Standards

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8369]
## Description 
As a Mobile QA , I want to standardized feature testing requirements amongst the QART team, so that the team follows at least a base set of standards and requirements for all testing needs, in order to be consistent and provide clarity to teams that work with QART including future external teams. 

As part of this story we want to:   
- Identify the different testing methods 
- identify how each team member does testing / differences
- develop a standard
- implement and follow through on the standard 

## Acceptance Criteria
  

-  [ ] Document types of testing 
-  [ ] Document how each person is testing those methods 
-  [ ] Draft best practices / standards
-  [ ] Review with team
-  [ ] Determine how to validate they are being used (audited, peer review, etc) 

## Notes & Open Questions
- [Spreadsheet for feature testing ](https://docs.google.com/spreadsheets/d/1KZe9QNwAPi3fy9wcNFYF3_XT2j4LytZRLVdMPbrTyhU/edit#gid=0)
- Started by Therese

    
- Dev Notes: 

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by TKDickson** [comment]
This work has been completed (over several other tickets); closing. There will be other ticket(s) to do the validation that we're doing this consistently, in Q4.
