### ISSUE TITLE
BUG - sev 3 - Android - strange animation navigating to and from "find a VA location" screen

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8375]
## What happened?

on Android when navigating from the "find a VA location" screen back to sign in , the screen "jumps" (see attached video
## Specs:

- Device: pixel 4A
- OS:
- User Account: all
- Accessibility State: n/a

## Steps to Reproduce

from the "sign in" screen, tap "find a VA location"
observe the screen "jump"
tap "done"
observe the screen navigates to the sign in screen... and "jumps"

## Desired behavior

No more nav screens jumping on the app

## Acceptance Criteria

tbd
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzlhQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--716ecf822d8943c9c86edbef73741b46bc60ace1/az_recorder_20240412_182340_edited.mp4)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by bischoffa** [comment]
Adding Health Team Label

**Comment by bischoffa** [comment]
Added the wrong team label, switched to Global

**Comment by TKDickson** [comment]
Fixed in Android, light and dark mode. I also checked that iOS was unchanged by this (it was), and that navigating to and from the other options on this page (sign in and VCL panel) were also unchanged.

**Comment by TKDickson** [comment]
Doesn't need retesting in develop; closing
