### ISSUE TITLE
Investigate Claims: Inconsistent Data

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8379]
## Description 
**Investigation Story/Ticket:**

**In the Reddit Report listed below, the Veteran is noticing the following with claims**

- [ ] Duplicated Claims Data
- [ ] Inconsistent Claims Reporting- see reddit thread

https://www.reddit.com/r/VeteransBenefits/comments/1bmn478/strange_changes_on_mobile_app/

## **Acceptance Criteria**
  
Validate:
-  [ ] Investigate if what is noted above (inconsistent/missing data) is what we are also seeing on the claims BE
-  [ ] Note any of discrepancies for claims
-  [ ] Create any supporting stories for fix (if a fix is possible)

- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by StacyB2023** [comment]
Moving to ready to work (backlog) for now based on priority

**Comment by StacyB2023** [comment]
@jperk51 I think we can close this until another incident opens? Thoughts?

**Comment by jperk51** [comment]
Fine by me

**Comment by StacyB2023** [comment]
Closing. Team will reopen (new ticket) if more incidents occur etc.
