### ISSUE TITLE
Update the "The time and date of this appointment are still to be determined." Alert to Align with VADS Guidance

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8392]
To better align with the VADS Guidance [regarding slim alerts](https://design.va.gov/components/alert#examples---slim-alert---v1) and [informational alerts](https://design.va.gov/components/alert#informational-alert-aka-default), we should:
* [ ] Update the copy within the alert to be descriptive copy (not bold) instead of the bold (heading) copy that we have currently.
* [ ] This alert should be blue since it informational.

**Comment by Sparowhawk** [comment]
The alert is being removed with the appts rework and this ticket is no longer needed
