### ISSUE TITLE
Update the "You canceled this appointment." Alert to Align with VADS Guidance

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8393]
To better align with the VADS Guidance [regarding slim alerts](https://design.va.gov/components/alert#examples---slim-alert---v1), we should update the copy within the alert to be descriptive copy (not bold) instead of the bold (heading) copy that we have currently.

**Comment by Sparowhawk** [comment]
This alert is no longer needing to be updated as we removed it with the appts update
