### ISSUE TITLE
Update the "... canceled this appointment." Alert to Align with VADS Guidance

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8394]
Full alert copy: "[clinic / provider] canceled this appointment."

To better align with the VADS Guidance [regarding slim alerts](https://design.va.gov/components/alert#examples---slim-alert---v1), we should update the copy within the alert to be descriptive copy (not bold) instead of the bold (heading) copy that we have currently.

**Comment by Sparowhawk** [comment]
This alert is removed in the upcoming appts feature xl branch and this is no longer needed
