### ISSUE TITLE
Content: Review the "We can't refill this prescription in the app" Alert

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8395]
## Alert details:
* **Type:** Warning
* **Heading:** We can't refill this prescription in the app
* **Description:** 
We transferred this prescription to My VA Health.
To refill this prescription, you can:
• Use My VA Health portal, or
• Contact your local VA pharmacy, or
• Call our automated phone system, or
• Mail in the refill slip that was included with your previous refill

* **Link 1:** Automated phone system: 541-830-7563
* **Link 2:** TTY: 711 

### Screenshot for reference:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFJoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3ee6f27e1b3ff6deed547967397f4ae64e757ff/74DBC0C9-BBDE-4BD7-AB83-E179795218A9.png" alt="74DBC0C9-BBDE-4BD7-AB83-E179795218A9.png" />

---

@mistymg – I just wanted to get your opinion on link 1. Should we have "Automated phone system" there? It appears to be the only alert link that we have with additional copy included with the phone number and it is stated in the copy that they can call the automated phone system. Could we remove it or is this an alert that we don't have control over? If we can't or shouldn't remove it, feel free to close this one out. Thank you!

**Comment by brea11y** [comment]
Hey @mistymg – Unfortunately, we still can't do inline links. Jessica and the design system team tried to get them to work with the new link component, but they were still running into issues with them.

That makes total sense to me why it would be included in the link now. I didn't think about "Contact your VA pharmacy" being one of the options. I don't think there would be an issue with including the "Automated phone system" at the bottom of the copy and removing it from the link itself. Is this what you are thinking?

![Light](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/5230529/0d6034d0-2f8d-40eb-90a0-ef086f891ec1)

We could also bold that line of copy to help it stand out a bit more to sighted users.

**Comment by mistymg** [comment]
I think your mock up works, @brea11y! I don't have a strong stance on the "Automated phone system" being bolded. I guess let's leave it not bolded for now.

**Comment by brea11y** [comment]
That works for me! Thanks so much for your help! I'll close this ticket and issue a new one to ENG to implement these content updates. 🎉
