### ISSUE TITLE
Update the "Check your direct deposit information" Alert to Align with VADS Guidance

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#8399]
To better align with the VADS Guidance [regarding slim alerts](https://design.va.gov/components/alert#examples---slim-alert---v1), we should update the copy within the alert to be descriptive copy (not bold) instead of the bold (heading) copy that we have currently.

**Comment by brea11y** [comment]
Ticket has been reviewed and is still valid.

**Comment by TKDickson** [comment]
Confirmed changed UI in iOS and Android (using standard alert component in light/dark), and nothing changed with screen reader announcement.
