### ISSUE TITLE
Update Login Button & Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8412]
For all AC below, refer to the designs in this [Figma file](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=938-154&mode=design&t=R5OpezJUkjEviEQF-0) 

AC:

- Login, background and button, are updated to reflect new colors for light and dark mode
- VA logo SVG is updated - ask Brea for file
- Version font is updated for light and dark mode
- Ensure that background color spans entire screen in landscape mode (devices with and without bevel) for login screen, sync screen (login) and sync screen (logout)
- **Send to Ryan for VQA prior and get his okay before release**

**Comment by TKDickson** [comment]
Fresh installs for iOS and Android are not showing the VA logo & name component on screen, sending back to @dumathane 
<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHpHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac2e9cbaa34980be5a60beee81cf1dff94b72a96/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Passed QA and internal VQA; putting the 'blocked-external' label on, awaiting PO VQA.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
