### ISSUE TITLE
Push notifications: Discovery sprint for consent/opt in

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8419]
## Description 
As a content designer, I want to get up to speed on the work that's been done on a new consent/opt-in flows and the strategy behind our recommendations so that I can provide copy support where needed.

## Acceptance Criteria
  

-  [x] All documentation in Resources section of this ticket is reviewed
-  [x] Open questions are documented in this ticket and addressed with PM/UX

## Resources

- [Holly's ticket on this work](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8297) 
- [Figma board of opt-in flows](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=1243-4986&mode=design&t=DNMcCdPck56PIMGM-4)
- [Consent use cases](https://docs.google.com/spreadsheets/d/15II0OsOnKQrqr-5DQiCNa5MQq9qN2vhANVpU0yOzGf0/edit#gid=1420628209)
- [Recommended approach to consent for push in mobile app - GitHub](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/product/Push%20Notification%20Consent%20-%20recommendation.md)
- [Phase 1: Current Status & Next Steps](https://docs.google.com/presentation/d/10ZIBfry_pFeBu-XgXfz7zMdAQVahSXxvAPf45mYQkSA/edit#slide=id.g1e78b87c057_0_135): UX/PM presented to POs on 4/24 and got OK with our approach

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Met with Holly today to chat how PO meeting went and discuss next steps. Notes from meeting:

**Comment by mistymg** [comment]
Met with Holly today to chat about remaining open questions. Notes from meeting:

**Comment by htcollier** [comment]
Updated links to Figma
