### ISSUE TITLE
Backend: Remove complex ErrorDetails that causes React-Native hang

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8421]
#### Description

Detailed in bug ticket [7746](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7746), there's an issue with some react-native code that causes the app to hang while a json response is being processed. One easy way around this problem for now is to remove the object array response in meta:{errors:[{...,errorDetails:[{}] and replace it with just a concatenated list of errorDetails: detail strings.

This would be specific to the /v0/claims-and-appeals-overview endpoint.

## Acceptance Criteria

- [ ] ...
- [ ] It logs its progression through the 'happy path' or helpful error details.
- [ ] I tested the feature on staging and could demo it if asked.
- [ ] Public Ruby API methods have [Yardoc](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md) comments.
- [ ] The [OpenAPI](https://swagger.io/specification/) documentation is up-to-date.

**Comment by TKDickson** [comment]
User who has access & info for both (+54) worked well, as did a user who gets errors back for both (karsyn).

I used +54 to mock states where you get info for one half and an error for the other with the new error formatting; both of those were fine (showed the claims data & appeals error; as well as the inverse).

_I was also noticing WAY faster resolution/no screen freeze (a la #7746) - I'm not officially signing off on that one just yet, but I have a good feeling about this change :)_

**Comment by TKDickson** [comment]
Example response for what I mocked, in case we need it at some point:

> {
> 	"data": [{
> 		"id": "A1113",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "appeal",
> 			"completed": false,
> 			"dateFiled": "2023-02-01",
> 			"updatedAt": "2024-02-01",
> 			"displayTitle": "disability compensation appeal",
> 			"decisionLetterSent": false
> 		}
> 	}, {
> 		"id": "A3827",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "appeal",
> 			"completed": false,
> 			"dateFiled": "2023-10-16",
> 			"updatedAt": "2023-10-16",
> 			"displayTitle": "disability compensation appeal",
> 			"decisionLetterSent": false
> 		}
> 	}, {
> 		"id": "A1112",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "appeal",
> 			"completed": false,
> 			"dateFiled": "2023-01-01",
> 			"updatedAt": "2023-02-10",
> 			"displayTitle": "disability compensation appeal",
> 			"decisionLetterSent": false
> 		}
> 	}, {
> 		"id": "SC6028",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "supplementalClaim",
> 			"completed": false,
> 			"dateFiled": "2023-02-02",
> 			"updatedAt": "2023-02-02",
> 			"displayTitle": "supplemental claim for insurance",
> 			"decisionLetterSent": false
> 		}
> 	}, {
> 		"id": "SC6303",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "supplementalClaim",
> 			"completed": false,
> 			"dateFiled": "2023-02-02",
> 			"updatedAt": "2023-02-02",
> 			"displayTitle": "supplemental claim for education",
> 			"decisionLetterSent": false
> 		}
> 	}, {
> 		"id": "SC6560",
> 		"type": "appeal",
> 		"attributes": {
> 			"subtype": "supplementalClaim",
> 			"completed": false,
> 			"dateFiled": "2023-02-02",
> 			"updatedAt": "2023-02-02",
> 			"displayTitle": "supplemental claim for loan guaranty",
> 			"decisionLetterSent": false
> 		}
> 	}],
> 	"meta": {
> 		"errors": [{
> 			"service": "claims",
> 			"errorDetails": "Forbidden: User is not authorized for claims"
> 		}],
> 		"pagination": {
> 			"currentPage": 1,
> 			"perPage": 10,
> 			"totalPages": 1,
> 			"totalEntries": 5
> 		},
> 		"activeClaimsCount": 5
> 	}
> }
