### ISSUE TITLE
Style update: Screen headings for the Subtask template

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8428]
### Description
As part of [the new homescreen work](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8308), we updated the style for the "H1" headings on all Feature and Child templates, but not the Subtasks. 

This ticket covers the outstanding work that needs to be done on the Subtasks. This will result in visual consistency with the new work. These updates should show up in Profile, Messages, and anywhere else we use the Subtask template.

### ACs

- [x] Change 'BitterBoldHeading' to 'BitterHeading' in the Subtask template. New style should be: Bitter 400; 22px
- [x] Reach out to @wavelaurenrussell for VQA of affected areas when finished.

**Comment by alexandec** [comment]
@wavelaurenrussell I've created [a PR with example screens](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8489) on iOS and Android.

**Comment by alexandec** [comment]
Full list of affected screens:

- VAMobile/src/screens/auth/LoaGate/LoaGate.tsx
- VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/AskForClaimDecision/AskForClaimDecision.tsx
- VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/SelectFile.tsx
- VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/SelectFile/UploadFile/UploadFile.tsx
- VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/TakePhotos.tsx
- VAMobile/src/screens/BenefitsScreen/ClaimsScreen/ClaimDetailsScreen/ClaimStatus/ClaimFileUpload/TakePhotos/UploadOrAddPhotos/UploadOrAddPhotos.tsx
- VAMobile/src/screens/HealthScreen/Appointments/UpcomingAppointments/CheckIn/ConfirmContactInfo.tsx
- VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillRequestSummary.tsx
- VAMobile/src/screens/HealthScreen/Pharmacy/RefillScreens/RefillScreen.tsx
- VAMobile/src/screens/HealthScreen/Pharmacy/RefillTrackingDetails/RefillTrackingDetails.tsx
- VAMobile/src/screens/HealthScreen/SecureMessaging/EditDraft/EditDraft.tsx
- VAMobile/src/screens/HealthScreen/SecureMessaging/ReplyMessage/ReplyMessage.tsx
- VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/StartNewMessage.tsx
- VAMobile/src/screens/HealthScreen/SecureMessaging/StartNewMessage/Attachments/Attachments.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditAddressScreen/EditAddressScreen.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditEmailScreen/EditEmailScreen.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/ContactInformationScreen/EditPhoneNumberScreen/EditPhoneNumberScreen.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/GenderIdentityScreen/GenderIdentityScreen.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/PersonalInformationScreen/PreferredNameScreen/PreferredNameScreen.tsx
- VAMobile/src/screens/HomeScreen/ProfileScreen/SettingsScreen/DeveloperScreen/WaygateEditScreen.tsx
- VAMobile/src/screens/PaymentsScreen/DirectDepositScreen/EditDirectDepositScreen/EditDirectDepositScreen.tsx

**Comment by alexandec** [comment]
@wavelaurenrussell question on this, should it go into the feature-xl branch along with all the homescreen work? Or should it go into the normal develop branch?

**Comment by alexandec** [comment]
Chatting with Lauren at standup. She'd like this change to go into the `feature-xl/HomeScreenPersonalization2` branch so it gets merged along with all the other homescreen changes.  I updated [the PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8489) accordingly. FYI @dumathane @theodur

**Comment by alexandec** [comment]
Merged into the feature-xl/HomeScreenPersonalization2 branch

**Comment by rbontrager** [comment]
Verified that subtask template headings match the headings on feature and child templates. Approved by QA.
