### ISSUE TITLE
Fix appointments schema contract errors

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#8440]
These three schema errors are still occurring when running the appointments schema contract validations.

`The property '#/data/0/practitioners/0/identifier/0/value' of type null did not match the following type: string`
This one is occurring because hsrm_task_id is misspelled in the schema:
`The property '#/data/33/extension' contains additional properties [\\\"hsrm_task_id\\\"] outside of the schema when none are allowed in schema`
`The property '#/data/132' did not contain a required property of 'location_id'`

**Comment by StacyB2023** [comment]
@kpethtel Added to the contract testing epic. Let me know if you agree.
