### ISSUE TITLE
BUG - sev-2 - All - All of the personal/contact info analytics broke in the v1 -> v2 user release

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8443]
## What happened?

_So.... the QA team just found out today that the personal info slice was migrated to react query during [the v1 -> user migration](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/6847) (v2.14 release, mid October 2023), which we didn't know about. Or probably that. But anyways._

The personal info/contact info events have been broken since then. Here's an example:
<img width="762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1CQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a2870f2c0308e863db2173035a0a155c3b13ac3/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by dumathane** [comment]
https://github.com/department-of-veterans-affairs/va-mobile-app/commit/6521804f5f754beb015253f92c1817587015f82f#diff-23fe18dcdda181bfb4eb9f594bd41c1fdde8f6a912d4497d7e091815f5c6cb92

Looks like mistakenly removed by Theo in this PR. @theodur want to work on adding this one back?

**Comment by theodur** [comment]
Nothing for QA to test on this ticket since it's just analytics, but I'll let @TKDickson close this one just to be sure

**Comment by TKDickson** [comment]
Yeah, can't test - closing
