### ISSUE TITLE
BUG - Sev-3 - All - Wrong error screen being shown with RQ

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8447]
## What happened?

If you block the api call before RQ you would get a 'the app can't be loaded.  You aren't connected to the internet...' error screen on at least disability ratings, military info, vaccines, messages (probably all).  Now its defaulting to the default 'The VA mobile app isn't working right now' error screen. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. With charles proxy block the api call for one of the recent RQ updates
2. Navigate to the feature in the app. Notice that the default error page is displayed instead of the '

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

After RQ:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHlGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab46082d4e953e067a14ceb78620fd66a0b0f5d8/IMG_0071.PNG" alt="IMG_0071.PNG" />

Before RQ: 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDJGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bca404198264181f5f9078993311041e25f567f/IMG_0072.PNG" alt="IMG_0072.PNG" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
@Sparowhawk I've gone through all the screens (or I think I've gone through all the screens) and the only discrepancy that I've found is with appointments. 

Old:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2EwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59e41f40ec92e1680e15d26d98ea339032231c66/IMG_0052.PNG" alt="IMG_0052.PNG" />

New: 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2UwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61fd7c16d5d5d1f310d23978b2c55f6ba4d2ad64/IMG_0077.PNG" alt="IMG_0077.PNG" />

**Comment by Sparowhawk** [comment]
for that discrepancy I believe the issue is you mocked a network error meaning they don’t have internet access that returns this error type
case CommonErrorTypesConstants.NETWORK_CONNECTION_ERROR:
          return <NetworkConnectionError onTryAgain={tryAgain} />
12:25
other errors that are not network issues would return this one
case CommonErrorTypesConstants.APP_LEVEL_ERROR_APPOINTMENTS:
          return <ErrorAlert text={t(‘appointments.errorText’)} onTryAgain={tryAgain} />
12:26
so I technically think this fixes a bug lol

**Comment by rbontrager** [comment]
Verified that screens go to the app can't be loaded screens when an error occurs. Verified that if you remove the error, hitting refresh will cause the data to reappear correctly. Verified that loading screens are appearing while waiting for refetch of the api calls to happen and while waiting for the data to reappear after hitting refresh.  This was verified on the following screens:
-Message inbox/drafts/my folders 
-Review Message
-Review Message with threads
-Contact Info
-Disability Ratings
-Letters
-Personal Info
-Military Info
-Payment History
-Direct Deposit
-Vaccines
-Appointments
-Claims history
-Claim/Appeal details
-Decision Letters
-Prescriptions
-Prescription refill tracking

Approved by QA.
