### ISSUE TITLE
Sev - 2 - Crashes are spiking for an issue in version 2.25.0

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#8448]
## Description

- [Crash details](https://console.firebase.google.com/project/va-mobile-app/crashlytics/app/android:gov.va.mobileapp/issues/563face619fe9d59414b774e903573e8?time=last-seven-days)
- [Slack thread for more details](https://adhoc.slack.com/archives/C063KLSMVAR/p1713883456106099)]

**Other Info:**

- Binny notified VA on 4/23 and got Don's approval to disable in-app updates for andriod users -[ Slack Thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1713905194081079)
- Per Tim 4/23 bug not deemed critical / sev-1 given its turned off 

QA/Dev Notes
--------------
We are fixing this issue by removing the inAppUpdates android code all together, and replacing it with very similar code that iOS has that simply notifies the user they are leaving the app and then throws them to the app store with the update available.

This will let us have less dependency requirements, and allow detox to appropriately test encouraged update for us.

**Comment by TKDickson** [comment]
Reassigning to @DJUltraTom because I am out two of the next three days; if this requires a hotfix (or pushing back RC testing, or anything else), Tom's your QA.

**Comment by DJUltraTom** [comment]
Verified using Binny's branch "testing TheoChanges" on a samsung galaxy S21 5G on android 14 that we can get the "Encouraged Upgrade" prompt in Demo mode with no crash and user successfully directed to the VA Health and benefits page on the app store.
QA Approves this fix.

**Comment by bischoffa** [comment]
@DJUltraTom can you close this ticket?

**Comment by DJUltraTom** [comment]
Closing!
