### ISSUE TITLE
Update copy on Direct Deposit page

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8452]
Update copy on the Direct Deposit page to read, 

"Manage your direct deposit information for disability compensation, pension, and Post-9/11 GI Bill benefits."

A mockup is available here: https://dsva.slack.com/archives/C06JV0KHZNF/p1713872509450219?thread_ts=1713211656.845489&cid=C06JV0KHZNF

**Comment by alexandec** [comment]
@mistymg here's a local simulator screenshot with the updated text:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb044c604e597ace2ab44cc8d49598c25df5f50d/Simulator%20Screenshot%20-%20iPhone%2013%20-%202024-04-23%20at%2011.07.37.png" alt="Simulator Screenshot - iPhone 13 - 2024-04-23 at 11.07.37.png" />

**Comment by mistymg** [comment]
@alexandec Perfect! For the alt text, can you also make sure not only that 9/11 is read out as "nine eleven" but also that GI is read out as "G-I"?

**Comment by rbontrager** [comment]
Verified that the text has changed to "Manage your direct deposit information for disability compensation, pension, and Post-9/11 GI Bill benefits." and that talkback/voice over reads out 9/11 as "nine eleven" and GI as "G-I".  Approved by QA.

**Comment by bischoffa** [comment]
Per PO Rachel this ticket should not be release. The migration of related APIs is on hold indefinitely. 

<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ=
=--3cf262f17ab30e4eadf58e3c998722eaa3793062/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Moving ticket to blocked as change was not implemented as it was removed per PO request

**Comment by bischoffa** [comment]
@ala-yna, @rachelhanster is asking about this ticket in DSVA Slack. I mentioned in you that[ Slack thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1722622670955049).

**Comment by TKDickson** [comment]
Same testing as before - verified that the text has changed to "Manage your direct deposit information for disability compensation, pension, and Post-9/11 GI Bill benefits." and that talkback/voice over reads out 9/11 as "nine eleven" and GI as "G-I" (and V-A dot gov), iOS and Android. 
Approved by QA.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop, closing.
