### ISSUE TITLE
Verify there are no edge cases for stuff that was transition to react query during the v1 -> v2 api migration

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8453]
We learned that some things like personal info/contact info were migrated to react query without informing QA during the v1 -> v2 api migration. While it's been out for a while with no complaints QA needs to go through and verify the edge cases to make sure that nothing was broken.  

Things to recheck include:
- All testRail cases
- Authorization works
- Analytics works

**Comment by TKDickson** [comment]
[TestRail run](https://dsvavsp.testrail.io/index.php?/runs/view/5578&group_by=cases:section_id&group_order=asc)
