### ISSUE TITLE
BUG - Sev-2 - All - Error screen being shown over you don't have permissions for this specific feature screen in some cases

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8465]
## What happened?

Missed this originally because of how I was mocking my data. With RQ it looks the feature's api is called even when the authorizedServices for that feature is set to false.  This is causing the default error screen to appear instead of the various you don't have permission for this specific feature screen. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by bischoffa** [comment]
Severity label missing so added it

**Comment by bischoffa** [comment]
Slack Thread for Dylan's question. Need PM to weigh in, in order to proceed https://adhoc.slack.com/archives/C0212B872MT/p1715700144924079 

RQ, Global, and H&B PMs tagged for insight. 

Moving this ticket to blocked given PM direction needed.

**Comment by Sparowhawk** [comment]
I think it makes since that if the user isn’t authorized on the home screen that an error component isn’t displayed, but once you get to the actual feature if there is an error in the auth services api then I think the error component needs to be displayed with the option to refresh

**Comment by rbontrager** [comment]
Verified that an error screen is no longer been shown over the unauthorized screen for the following features:
Claims, Military Info, Appointments, Letters, Secure Messaging, and Prescriptions. Approved by QA.
