### ISSUE TITLE
Incorporate Design System Alert Component - Global

### ISSUE THREAD

**Issue by TimRoe** [department-of-veterans-affairs/va-mobile-app#8468]
## Description 
As a veteran, I want to have a consistent visual experience interacting with the VA between web and mobile.

As part of this story we want to:   
- Upgrade the Global areas of the app to use the design system Alert component
- Reach out to the design system team if encountering issues or to provide other feedback if appropriate

## Acceptance Criteria
  

-  [ ] If not already done within the app, update `@department-of-veterans-affairs/mobile-component-library` package to version 0.15.0 or higher so the Alert component is available
-  [ ] If not already done within the app, update `@department-of-veterans-affairs/eslint-config-mobile` package to version 0.14.0 and run `yarn nodes` to install it so linting will issue warnings for outdated Alert components
-  [ ] With prior AC complete, run `yarn lint` and you'll get a list in the console of Alertbox and CollapsibleAlert components that need to be updated
   -  [ ] Parse through the list of 33 Alertbox warnings and update all within Global code to use the design system Alert
   - [ ] Parse through the list of 5 CollapsibleAlert warnings and update all within Global code to use the design system Alert

**Accessibility Requirements**
- [ ] Validate Alert component accessibility functionality works as expected

## Notes & Open Questions
- Does this require QA? Yes
    
Dev Notes: 
- The design system Alert component opted to not include haptics or scroll-to/focus behavior as not inherently relevant to the component itself for all mobile use cases
   - Code-wise, it is expected haptics should be capable of being handled at the app-level since it is a non-visual action and can be added alongside the Alert
   - Code-wise, it was unclear if the scroll-to/focus behavior can be fully mimicked without integration into the component--evaluate as part of this ticket and reach out to the design system team to determine a solution if it cannot adequately meet expectations

## Ticket Checklist

- [ ] Linked to an Epic

**Comment by TimRoe** [comment]
Hello @ajsarkar28 , giving a heads up that this ticket was created for incorporating the Alert component into the app from the Global side. I added all details I thought relevant, but may have missed something not being familiar with Global team processes so feel free to update as you see fit to fit it into the roadmap.

**Comment by theodur** [comment]
It actually looks like the global portion of this was done in [PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9022). @alexandec Since it looks like you removed all instances of `AlertBox` in the repo, I'm going to attach this ticket to your PR also.

**Comment by theodur** [comment]
Not sure if this means Rachel and Therese will split up the QA work for Chris's PR, or if Rachel will handle all the QA for this. I'm assuming the latter, but just a heads-up @TKDickson

**Comment by rbontrager** [comment]
Verified that the alert component follows the design in the storybook given by the design system.  Verified that the new alert component works like it previously did from an a11y perspective.  Verified that all issues with spacing in my comment above were fixed and that all alerts given in the list by Chris have been updated to use the new alert component.  Approved by QA.
