### ISSUE TITLE
Investigate Caseflow Maintenance Window not taking affect

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8470]
https://vagov.ddog-gov.com/apm/error-tracking/issue/84818ca4-862a-11ee-86f6-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&fromUser=true&refresh_mode=paused&view=spans&from_ts=1713472980074&to_ts=1713562980074&live=false

This error shows that calls were being made to Caseflow even though it was down. Investigate if there was a maintenance window active during any of these errors and see if there is any reason it was ignored in the event there was a maintenance window

**Comment by aherzberg** [comment]
went through maintenance windows and didn't find a caseflow or upstream window that could be related to appeals. Also confirmed that FE does key off of the correct appeals window if it was hit. I think this was a case of either an unexpected service outage or caseflow not putting in a maintenance window
