### ISSUE TITLE
JSON Serialization error on post_create_message_reply_with_attachment

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8472]
https://vagov.ddog-gov.com/apm/error-tracking/issue/d396e12c-a029-11ee-8a25-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&refresh_mode=paused&view=spans&from_ts=1713890037797&to_ts=1713980037797&live=false

We're getting an error on post_create_message_reply_with_attachment. Investigate if we're providing invalid JSON any where

**Comment by aherzberg** [comment]
after adding the response body to the error that was raised, found that it was returning "no value present". reported to MHV and they are looking into it.

**Comment by aherzberg** [comment]
MHV confirmed the issue has been fixed. I'm not seeing any more instances of the error pop up. Created ticket to guard against nameless files: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9018.

See related convo: https://dsva.slack.com/archives/C05TU9FPZU0/p1720551615312799?thread_ts=1720459064.552039&cid=C05TU9FPZU0
