### ISSUE TITLE
Get Appointments 400 Bad Request

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8475]
https://vagov.ddog-gov.com/apm/error-tracking/issue/8059221e-f68b-11ee-a05f-da7ad0900007?query=pod_name%3Avets-api-mobile-%2A&refresh_mode=sliding&view=spans&from_ts=1713978348764&to_ts=1714064748764&live=true

Several errors have popped up with the message `Your browser sent an invalid request`. Investigate if the issue is on our end or if we're out of luck

**Comment by aherzberg** [comment]
this error is on the upstream call to VAOS. comparing examples of a successful call to this error, I can't find any differences/malforming of parameters. see below: 
```
success: 

https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/5dabaace6a31e655d78756e7985990f8c4ffe3acc81807c5fad02a82a0f20d37/appointments?end=2025-06-22T23%3A59%3A59Z&pageSize=0&start=2023-01-01T00%3A00%3A00Z&statuses=proposed%2Ccancelled%2Cbooked%2Cfulfilled%2Carrived

failure: 

https://internal-dsva-vagov-prod-fwdproxy-2075821597.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/316df8496db88f693405d200bf5fc93a059b152b733db815ab98c17e3d5ea197/appointments?end=2025-06-25T23%3A59%3A59Z&pageSize=0&start=2023-01-01T00%3A00%3A00Z&statuses=proposed%2Ccancelled%2Cbooked%2Cfulfilled%2Carrived
```
This just the leaves the user to be the problem or an upstream issue. We do have a future ticket that will use the enrollement status api to ensure the user is enrolled in VA healthcare so this should help root out any bad user calls. Closing issue.
