### ISSUE TITLE
Content for Home Screen Availability Framework with update button to replace currently broken in-app updates

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8492]
## Description 
As an android user, I want to be notified of updates available to me, so that I can stay up to date with the VA Mobile App content and bug fixes.
As a result of [8448](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8448), in-app updates broke for Android. Because of this, the only way to alert previous versions of the app to the new available update is with availability framework. 

As part of this story we want to:   

- Create content for an availability framework alert for Android users prior to release 2.27 that a problem arose and we suggest they take the most recent update to regain functionality lost to a bug. The AF function being used is 'allowedFunction' and will result in a yellow alertbanner. V2 of body composition (with spacing) is available for use.
- Ensure that the content in the AF is not misleading to users, and does not result in a poor customer service experience.

**Constraints:** 
- The phone number/TTY in AF module cannot be removed (the # is hard coded in old app versions—and that is who will see this AF module), so we need to work with it being present.
    - We don't know if folks at the general VA number will be informed enough to provide support to folks that call in regard to this issue in the app. 

**Open questions:**
 - Is there another number that would work better than the general VA number?

## AC

- [ ] Copy for yellow alert box that:
- Addresses Android users with versions older than 2.27
- Explains there's a bug that impedes some functionality of the app
- Prompts them to update the app for the best experience
- Includes language to accompany the phone number, ideally that connects it to the subject of the AF (or at least is not misleading)

## Final copy for AF

Header: Update app to fix issue
Body: We found an issue with older versions of the app on Android devices. To fix this issue, update the app. If you need more help getting your VA health and benefits information, call us.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by mistymg** [comment]
Met with Binny + Eng/QA yesterday to understand issue. Bug is just for Android users using versions older than 2.27 and involves our Encouraged Update function not working. Eng put in a fix that will fix this issue with the newest release. But older versions it will still be a problem. We're going to use AF and it will only show to these Android users with older versions. Best to not over-explain the bug but prompt them to update.

**Comment by mistymg** [comment]
Per Binny, phone number is hardcoded in AF. With Ameet out, we need to discuss as a team whether using AF is the right call. If so, we also need to make PO aware of the possible implications of needing to include a phone/tty in the alert. I suggested discussing at grooming today.

**Comment by mistymg** [comment]
Example of AF with update button (phone/tty hardcoded):
![AF with update-now button](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/102106810/52526a17-0d9c-4c98-9eb3-7a7c541b4313)

**Comment by htcollier** [comment]
During cross-functional team discussion, it was determined that aside from just displaying nothing (and allowing users to stay on old versions without displaying anything), AF is the only solution we have to inform users that they're on an old version of the app without risking crash. 

Team has agreed that finding a way to use copy to explain the presence of the general VA phone number (without misleading the user) is the best path forward. Copy TBD

**Comment by mistymg** [comment]
@dumathane Per [this thumbs up from Rachel on a screenshot](https://dsva.slack.com/archives/C018V2JCWRJ/p1714661848197169?thread_ts=1713905194.081079&cid=C018V2JCWRJ), I'm assuming we're good to go with this copy. So here it is:

Header: Update app to fix issue
Body: We found an issue with older versions of the app on Android devices. To fix this issue, update the app. If you need more help getting your VA health and benefits information, call us.
Hardcoded phone/tty
Update now button

**Comment by mistymg** [comment]
Got approval from PO. Handed off to Eng. Closing ticket.
