### ISSUE TITLE
Create a ticket template for Breaking RC/Code freeze

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8494]
We should have a SOP for breaking a code freeze or deviating from our standard RC process, Having a ticket template will make this a consistent process.

AC:
Ticket is user readable for what needs to be filled out (AKA, non-technical users can fill this out)
Ticket has appropriate information for:
- Qualifying reasons (does this warrant breaking the code freeze?)
- What actions to take (who to contact, slack channels, emails?)
- Next steps to take

**Comment by bischoffa** [comment]
When creating this ticket - this is Qart's current policy on [Chg Mgt for Adding New Code to the Release Branch.](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Change%20Management%20for%20Adding%20New%20Code%20to%20the%20Release%20Branch.md) Please make sure this ticket template aligns with that. If we need to update it we can just want to make sure they align with one another.

**Comment by DJUltraTom** [comment]
I have written a template but wasn't sure I was placing it in the correct place in github, I have it saved locally until I can confer with @bischoffa on Monday

**Comment by DJUltraTom** [comment]
https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9019

**Comment by DJUltraTom** [comment]
submitted proposed ticket after reviewing with Adam, currently the PR linked in the above comment is pending review/approval

**Comment by DJUltraTom** [comment]
merge successful and template is now available for use!
Closing ticket
