### ISSUE TITLE
Android App Store - App Support Website Update 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8498]
## Description 
As a VA, I want to Veterans on the Android App Store to be directed to the va.gov contact us page so that its similar to iOS. 

As part of this story we want to:   

- Update Android's app support drop down link "Website" to https://www.va.gov/contact-us/

## Acceptance Criteria
  

-  [ ] Go to https://play.google.com/store/apps/details?id=gov.va.mobileapp and expand App Support then click Website which will take you to https://www.va.gov/contact-us/

**Accessibility Requirements**
- [ ] Able to view and access via a screenreader 

## Notes & Open Questions
- Requested by PO on 4/30 via [Slack ](https://dsva.slack.com/archives/C018V2JCWRJ/p1712853580126059)
- Dependencies/Roadblocks: No 
- Any internal/external dependencies? No 
- Test accounts needed? None
- Does this require QA? Yes
    

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

 
<img width="1653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUtsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1cdc5ef730c1660a872946ad10c2f54163d1a93/image.png" alt="image.png" />

**Comment by bischoffa** [comment]
Android requires an email address to be displayed, so we can update the URL to contact-us, but we have to display an email.

**Comment by bischoffa** [comment]
@timwright12 apologies for the delay in getting this assigned to you from when we talked during out 1:1.

**Comment by timwright12** [comment]
made this update, will monitor https://play.google.com/store/apps/details?id=gov.va.mobileapp for when the change goes through

**Comment by timwright12** [comment]
@bischoffa this is live, closing out
