### ISSUE TITLE
Update List View for all Appointment Types

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8502]
## Description 
As an engineer, I want create and reuse different standardized components for the list view for appointments, so that it will easier for other teams to start working in appointments and the different appointment types can be more aligned.

Specific details of the changes needed to the List View can be found in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=0) ("List view" tab in spreadsheet) and the design specs can be found in [Figma](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2721-21647&mode=design&t=vC9P2gjQDJtM6fsE-4)

As part of this story we want to: 
- Create new components that are needed
- Plug in pre-existing components
- Update end to end tests
- Update headings to match [Figma](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2721-21647&mode=design&t=vC9P2gjQDJtM6fsE-4) file
- VQA with content/design

## Acceptance Criteria

-  [ ] New components have been created
-  [ ] Existing components have been brought in
-  [ ] E2E tests have been updated
-  [ ] VQA by content
-  [ ] VQA by design

**Comment by mistymg** [comment]
Note that these changes to list view are for both the upcoming and past lists.
