### ISSUE TITLE
BUG - Sev 3 - All - VoiceControl on VABulletList shows numbers for text only

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8509]
## What happened?

In various places in the app we use the component VABulletList, and when we use it, all text bullets will be mistakenly 'actionable' via voice control.

## Specs:

- Device: iphone SE
- OS: 15.7
- User Account: Demo Mode
- Accessibility State: Voice Control

## Steps to Reproduce

Go to health help, cerner SM alert, what's new, and enable voice control and see the bullets are actionable.

## Desired behavior

They shouldn't be actionable.

## Acceptance Criteria

Remove the actionableness of the bullets.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/f8610daa-585d-401c-b125-894341b91726" width="32%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/50325e82-aada-4600-9685-491c2e0b2e87" width="32%" />&nbsp;&nbsp;<img src="https://github.com/department-of-veterans-affairs/va-mobile-app/assets/46909588/98d123f3-886a-4719-ae05-c7633353cf05" width="32%" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  
</details>

## Ticket Checklist
- [x] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Extraneous voice control numbers are gone; still reading out bulleted lists with screen reader - iOS and Android.

**Comment by TKDickson** [comment]
Does not require further testing in develop; closing
