### ISSUE TITLE
BUG - Sev-3 - All - Message threads coming in with invalid date times

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8510]
## What happened?

A lot of our message threads are coming in as invalid datetime.  These date and times were originally there when the reply was first sent. I've include what I'm seeing in Charles proxy as well.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Log in to user +226
2. Click on the message sent by Bontrager, Rachael J on 4/24/2024 at 9:31 am. Scroll down through the messages in this conversation and notice that a lot of them have invalid dateTime. 

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFNxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92d06621f957ec0e714e67eaf7beca013acd663e/IMG_0076.PNG" alt="IMG_0076.PNG" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  
{
	"data": [{
		"id": "3566635",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566635,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T11:45:21.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566635"
		}
	}, {
		"id": "3559610",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3559610,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-29T18:05:34.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3559610"
		}
	}, {
		"id": "3566768",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566768,
			"body": "Test 1",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test 1",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T13:17:27.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566768"
		}
	}, {
		"id": "3565599",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3565599,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-29T19:11:07.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3565599"
		}
	}, {
		"id": "3566654",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566654,
			"body": "Test1",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test1",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T11:56:26.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566654"
		}
	}, {
		"id": "3566637",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566637,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T11:46:22.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566637"
		}
	}, {
		"id": "3566688",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566688,
			"body": "Test1",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test1",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T12:49:53.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566688"
		}
	}, {
		"id": "3566690",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566690,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-30T12:49:24.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566690"
		}
	}, {
		"id": "3565601",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3565601,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-29T19:11:21.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3565601"
		}
	}, {
		"id": "3565603",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3565603,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-29T19:11:39.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3565603"
		}
	}, {
		"id": "3565606",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3565606,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": null,
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -2,
			"draftDate": "2024-04-29T19:13:26.000+00:00",
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3565606"
		}
	}, {
		"id": "3568981",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3568981,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": "2024-04-30T18:27:03.000Z",
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -1,
			"draftDate": null,
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3568981"
		}
	}, {
		"id": "3566840",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566840,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": "2024-04-30T13:27:03.000Z",
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -1,
			"draftDate": null,
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566840"
		}
	}, {
		"id": "3566776",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3566776,
			"body": "Test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "Test",
			"attachment": null,
			"sentDate": "2024-04-30T13:21:48.000Z",
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -1,
			"draftDate": null,
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3566776"
		}
	}, {
		"id": "3553027",
		"type": "message_thread_details",
		"attributes": {
			"messageId": 3553027,
			"body": "No attachments reply test",
			"category": "OTHER",
			"subject": "General Inquiry",
			"messageBody": "No attachments reply test",
			"attachment": null,
			"sentDate": "2024-04-24T14:32:24.000Z",
			"senderId": 873433,
			"senderName": "WEAVER, JOHNNIE  LEONARD",
			"recipientId": 1766073,
			"recipientName": "VA Flagship mobile applications interface 1_DAYT29",
			"readReceipt": null,
			"triageGroupName": "VA Flagship mobile applications interface 1_DAYT29",
			"proxySenderName": null,
			"threadId": 3553021,
			"folderId": -1,
			"draftDate": null,
			"toDate": null,
			"hasAttachments": false
		},
		"links": {
			"self": "https://staging-api.va.gov/mobile/v0/messaging/health/messages/3553027"
		}
	}],
	"meta": {
		"messageCounts": {
			"unread": 15,
			"read": 1
		}
	}
}

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
@rbontrager Looking at the issue it looks like it is api error from the JSON I am seeing. We rely on the sentDate field to display the date time for the message. So since that is coming in as null there isn't a valid date time to display. I did notice that for those messages that had a null sentDate that there was a populated draftDate.

Are those messages drafts? Or were they actually sent. If they were sent then there is an error somewhere in the BE. If they are drafts then we might need to get with UX to see if those should even be displayed

**Comment by rbontrager** [comment]
@Sparowhawk It looks like they are drafts.

**Comment by Sparowhawk** [comment]
@wavelaurenrussell Should we be displaying draft messages in the messages threads on the view message/reply message screens? I feel this would be confusing to a veteran if it wasn't actually sent.

**Comment by wavelaurenrussell** [comment]
Maybe we should display the draft, and use a label tag to indicate it as such. I'm thinking about Gmail functionality, which I believe the feature concept was modeled after.. I can provide a mock if you need it.

**Comment by Sparowhawk** [comment]
Once I have that mock I can update those and use the draft date for draft messages instead of sent date

**Comment by wavelaurenrussell** [comment]
Ok! [Link to Figma](https://www.figma.com/design/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?node-id=1306-2563&t=C0SlOZi69Irw4oUK-4) and screenshot attached.

![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/156008783/d6522292-92c7-400e-947b-d9d139bf22a5)

**Comment by wavelaurenrussell** [comment]
Screenshot: 

<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUw5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aaa2608831554116cbc1d90b2381fcd6d630b7d7/image.png" alt="image.png" />

**Comment by rbontrager** [comment]
@Sparowhawk While testing I noticed this seems to have caused some issues with sending drafts again. The sent draft message is still being shown in the draft folder after sending and an error page is displayed if you tap on it. It will go away on a refresh. Can confirm this doesn't happen in the daily build from this morning.

**Comment by rbontrager** [comment]
Verified that invalid date time messages are now showing as draft messages in message threads and they follow the design Lauren gave above.  Approved by QA.
