### ISSUE TITLE
Investigate Immunization 500 errors

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8522]
Immunizations is failing at a decent rate with `Dry::Struct::Error: [Mobile::V0::LighthouseSession.new] :access_token is missing in Hash input` as the messaging. Figure out what exactly is going on here and if it's a cause for concern. 

https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=eks-prod&fromUser=false&graphType=flamegraph&groupMapByOperation=null&panels=qson%3A%28data%3A%28activePanelKey%3Atrace%2Cresource%3A%28resourceName%3AMobile%253A%253AV1%253A%253AImmunizationsController%2523index%2CresourceID%3Aa38a8036d7ba953b%29%2Ctrace%3A%28traceID%3A4300241899080462409%2CspanID%3A2529600437870677108%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&s3BucketDetails=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&shouldShowLegend=true&sort=time&spanID=2529600437870677108&summary=qson%3A%28data%3A%21f%2Cversion%3A%211%29&topGraphs=latency%3Alatency%2Chits%3Aversion_count%2Cerrors%3Aratio%2CbreakdownAs%3Aabsolute&view=spans&start=1714662948388&end=1714666548388&paused=false

**Comment by aherzberg** [comment]
saw this error get properly raised as an upstream error.
