### ISSUE TITLE
Check in on new error monitor

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#8527]
We recently created created a [datadog monitor](https://vagov.ddog-gov.com/monitors/213410?view=spans) for alerting us to new errors. It should send those errors to this [slack channel](https://dsva.slack.com/archives/C06T6ABC9MX) (this may not be publicly accessible; talk to Kris for access). So far, that has not sent any new alerts even though we have had new 500 errors since then. Try again to get this alert working.

If it's not possible to get this functionality through datadog, consider trying with sentry.

**Comment by aherzberg** [comment]
monitor configured and ready to integrate into on call process
