### ISSUE TITLE
BUG - Sev 3 - Android - After inputting text, textarea becomes miniscule and only allows you to peek at what you are writing  while you are writing; makes reviewing what one has written exceptionally challenging and could ruffle feathers for some users.

### ISSUE THREAD

**Issue by RIAEvangelist** [department-of-veterans-affairs/va-mobile-app#8531]
## What happened?
I realized that old, or crotchety vets of any age, who want to or are capable of sending messages to their teams through the mobile app may be having difficulty or even just not using the messenger due to this UX issue.

## Specs:
- Device: Flagship Big Screen
- OS: Android Latest

## Steps to Reproduce
Navigate to messenger area
Choose who to message
Start type ng them a message
Type more
And more
Scroll through what you have written to see if you said it how you want and haven't asked anyone for chemlight batteries.
Type some more 
Stop and imagine you are 80 and not an engineer, which you will be some day, how do you feel? 80 may not be a requirement; I just like to use it as a baseline.

## Desired behavior
Text area should take up remaining area of screen after keyboard is opened. Maybe on focus make it absolute or something, just a first thought.

## Acceptance Criteria
Not wanting to punt the pumpkin because the phone textarea is too small to see what you have written

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
All jokes aside it is kind of a show stopper bug for sending intelligible messages when your life is chaotic, like being a dad, or having many people that need your attention, or neighbors that interrupt your thought process when you are trying to communicate with your team.

Somebody please label this as I am filling this out on a phone, coming direct from the app, and not so familiar with the UI of GH mobile. Also Y'all prob'ly  want to talk this over since it is UX.

- Impact: High 
- Frequency: High 
- 1 - Critical

## Screen shot(s) and additional information
![Screenshot_20240502-232710.png](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/369041/15927198-4378-4389-a985-dcd9a860e756)

![Screenshot_20240502-232859.png](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/369041/b6b83fbd-bd52-4c05-9101-fb811995b5ac)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
For android we can change the manifest file apparently to force these behaviors with the keyboard
android:windowSoftInputMode=
“adjustResize”
The activity’s main window is always resized to make room for the soft keyboard on screen.
“adjustPan”
The activity’s main window is not resized to make room for the soft keyboard. Rather, the contents of the window are automatically panned so that the current focus is never obscured by the keyboard and users can always see what they are typing. This is generally less desirable than resizing, because the user may need to close the soft keyboard to get at and interact with obscured parts of the window.

**Comment by bischoffa** [comment]
Thanks @Sparowhawk for looking into this. Is this an overarching change or something specifically in message?

**Comment by Sparowhawk** [comment]
@bischoffa this is likely a global change if you go the route of adjusting the Android manifest variables. If it doesn't end up with the desired behavior though it would likely become a health issue.

**Comment by bischoffa** [comment]
@Sparowhawk thanks! Removing Rachael as well.

**Comment by theodur** [comment]
Changing the `windowSoftInputMode` to `adjustResize` did the trick, nice find @Sparowhawk. Since this is a global change that impacts how the window is adjusted when the keyboard is opened, I did various tests with the keyboard open for different inputs on different screens, and everything looked good. That may be something you want to look at also when testing @TKDickson.

**Comment by TKDickson** [comment]
not currently testing (over limit)

**Comment by TKDickson** [comment]
Picking up as one of my 3

**Comment by TKDickson** [comment]
Text input for new message, preferred name, edit home address all adjusted well. Reply to message using screenreader also adjusted as expected. Still seeing #8724. Approved to merge.

**Comment by TKDickson** [comment]
No further testing required in develop, closing.

**Comment by RIAEvangelist** [comment]
> No further testing required in develop, closing.

You rock! What's the release cycle timeframe like? I'll be super happy to test on my device!

**Comment by bischoffa** [comment]
VAHB releases every other Tuesday. I suspect this fix will be be in production on Tuesday, July 2nd.
