### ISSUE TITLE
Collection of HSP issues (armadillo tail segment one)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8537]
We're starting to do holistic review on the home screen personalization feature branch. To avoid a lot of overhead writing out separate bug tickets for each issue, we're going to attempt this "collection of issues" bug ticket.

If it's awful (aka it's nearly impossible to correctly keep track of all issues & what was fixed) then I will break them out separately, overhead be d*mned.

#### One
Too much spacing in this 'min home screen' UI, doesn't match [Figma](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3094-2969&mode=design&t=yxMfKaSIZn3RcNUw-0).  
<img width="370" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWUwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75db04acddb196e7803d781da55195b3ce6a3901/image.png" alt="image.png" />

#### Two
Cerner copy on Health Category screen has unintended space from the left. Can we align that with the feature titles? Green line represents correct alignment, line it up with this. 
<img width="899" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSsxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fc62cada347a3a057ba740b052c968ca26dd40b/cerner-copy-alignment.jpg" alt="cerner-copy-alignment.jpg" />

#### Three
Bump up BitterHeading to 26px on all Category, Feature and Subtask screens (is currently 22px). Subtask work was recently merged [in this PR](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8489), so can we make sure that these updates make it over there too somehow?  See [Figma (category)](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2999-1191&mode=design&t=gzthXz5hYDJ7gV95-4). And [Figma (feature)](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3939-2479&mode=design&t=UEWL7IyygQCslRZt-4). 

#### Four
Ensure there is 30px space between the Crisis Line and the Home / Category titles (Activity / Health, Benefits, Payments).
(on Home, space looks too large; on Categories, space looks too small). See [Figma (home)](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3094-4503&mode=design&t=gzthXz5hYDJ7gV95-4) and [Figma (category)](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2999-1191&mode=design&t=gzthXz5hYDJ7gV95-4). 

#### Five
I see a floating tab bar on Android. We want to make sure that white background is bleeding down to the edge. iOS displays are ok.
<img width="360" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEsxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf3e822d0e4fa4fa8949d782a6537d5fe61db01c/tab%20bar%20float.png" alt="tab bar float.png" />

#### Six 
On Profile, the space between Veteran Status card and first row of features should be 20px (is too tall)—see [Figma](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3732-2456&mode=design&t=gzthXz5hYDJ7gV95-4)

#### Seven
On Android, the rule line in the disability rating/payment module should be a line but it isn't—it's a one pixel box w an outline. Screencap: [Figma file](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3094-4503&mode=design&t=qiFIJVqKPDdsJb1p-4) on left, Android on right.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUc1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3099e2936b5d91034d5222bfd59736ff24204ef0/image%20%288%29.png" alt="image (8).png" />

#### Eight
The nametag component on the profile doesn't accept an error from the military service history API call. On the home screen, it'll attempt calling it the regular 4 times. On the profile screen, it calls it forever - I went about 45 seconds of it calling continuously before I backed out of the screen to stop it calling.

(This doesn't happen in develop; seems to be particular to the HSP2 branch).

#### Nine: Screenreader issues
* Tapping appointments – it took an while to load up / move to the appointments screen (approximately 7 seconds). While the loading time isn't a major concern, it would have been nice if the screenreader told me what was happening. Is it possible to include an announcement (i.e "we're loading your appointments" or "taking you to the appointments screen"). If so, should we include this on all of them (messages, claims, etc.)?
* "VA Resources" – "VA" reads out as "vah"
* "Find a VA location" – "VA" reads out as "via"
* "Learn about PACT Act on VA.gov" – "VA.gov" reads out as "vah dot gov"
* "Learn about PACT Act on VA.gov" – I would recommend announcing this as an "external link" vs. just "link", if possible.

#### Ten: JWT token malformed error reintroduction
On not-the-first login session, JUST on the HSP2 branch (not develop) I'm seeing race conditions where we're calling APIs - for instance in this screenshot authorized services - before login is complete, resulting in our old friend "Access token JWT is malformed"
<img width="1647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOCs1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02037597332fe507036521258e13dcc712f9d40d/image.png" alt="image.png" />

#### 11 - Category titles (newer: from Builds 1638-ios/1572-android)
UX/FE collab needed on the Category headers/Feature entry type relationship. At the very least, the Category titles are cut off at the top. (Related to item 3 in this ticket, we executed but still need to refine)
<img width="1080" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelcvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16bacdea248c6d93f050b9bb3900761a64afec24/category-title-cutoff.png" alt="category-title-cutoff.png" />

#### 12 - Homescreen: VA Announcement (newer: from Builds 1638-ios/1572-android)
Replace current icon with the one used in the DS Link component. [Figma example](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3001-1188&mode=design&t=cjqqJA66qV6iMbRT-4)

#### 13 - SM Inbox Count Not Decreasing upon reading messages
The SM inbox count is not decreasing by 1 upon a message being read.  The count in the category screen and home screen is also not decreasing.

#### 14 - Homescreen: Heading spacing within sections (newer: from Builds 1638-ios/1572-android)
*Activity* and *About you* sections: Check spacing between the headers and the activity module. The gap on Activity looks larger. 
[Per Figma, it should be 20](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=3094-3373&mode=design&t=He4uqYUDJPZ4Oyo3-4). 
<img width="29" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZBQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02a2448c86df8823a20edb987478e4e26a04e141/activity-aboutYou-space.png" alt="activity-aboutYou-space.png" />

DO NOT ADD FURTHER ISSUES TO THIS TICKET. Add them to #8578.

**Comment by bischoffa** [comment]
Adam to chat with Therese on this ticket to see how Global is experimenting with this. Will chat during our 1:1

For now I will be tracking the individual issues as bugs in my bug tracker doc vs just 1 for this ticket. So its 14 as of this comment.

**Comment by TKDickson** [comment]
Issue two (cerner alignment on health category) was addressed in #8134, and verified.

Issue 13 was discovered to be not-HSP/pre-existing, and was moved to its own ticket #8577.

Issues 9 (screenreader pronunciation, loading) and 5 ("floating tab") are still TBD if they're going to be addressed.

All other issues have fixes (not yet verified) in the HSP2 branch.

**Comment by TKDickson** [comment]
Moved the descriptions in subissue 9 to #8578 (and split them into 3 issues - VA pronunciation, external link helper text, and loading screen).

Subissue 5 predates the home screen/is in develop, opened bug ticket #8586 FYI @htcollier 

Closing this ticket as complete.
