### ISSUE TITLE
FE: Implement Header/Description style on Appointments Detail screens

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8538]
### Description
This ticket will cover the updates to the text styles within the Appointments Detail screens. This will attempt to standardize the styles used in all the views.

As part of this story, we want to:

- Retain Mobile Body Bold (SSP 700; 20px) as the headers outlined within the detail screen (i.e. Phone appointment, Day/Date/Time, etc.). Change line height to accept the mobile body small style. [Refer to specific Figma mock for more guidance](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=2605-9728&mode=design&t=g1Ng2uzLwXXF2AtU-4).
- Create a new description text style to use for the description copy. Currently it is Mobile Body Reg (SSP 400; 20px). Proposing new text style: Mobile Body Small (SSP 400; 16px). Apply this style to all the shared components in the Appointments work.

### ACs

- [ ] Description headers outlined within the detail screen style is retained; adjust line height: Mobile Body Bold (SSP 700; 20px)
- [ ] Implement a new description text style: Mobile Body Small (SSP 400; 16px). Use for all of the shared components in the appointments work.
- [ ] Retain the existing standardMarginBetween and text line spacing; will assess in visual QA (VQA) if needed
- [ ] Conduct VQA with @wavelaurenrussell 

[Link to Figma Style Mockup](https://www.figma.com/file/o5vMnwHTJBXL37E71UjT39/Headings---Design-Debt---Working?type=design&node-id=1-1104&mode=design&t=rC1kPHu1XQGlEkds-4)

#### General example of what we mean by header/description described above. *Do not follow for specific attributes*. Use the spreadsheet for specifics: 
<img width="260" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0cxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1bd854c21b2d8856b78bf5ef0f7f3801b837995e/image.png" alt="image.png" />

**Comment by alexandec** [comment]
@wavelaurenrussell wanted run this screenshot by you to see if this matches your vision. It's an old details screen not yet updated to our new standards overall, but it's using the MobileBodySmall variant:
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzdkQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41f4e1f87c1d6c8f6f895e85b45d7e712cae65fd/Simulator%20Screenshot%20-%20iPhone%2015%20-%202024-05-14%20at%2013.52.18.png" alt="Simulator Screenshot - iPhone 15 - 2024-05-14 at 13.52.18.png" />

**Comment by wavelaurenrussell** [comment]
Thanks! Quick discussion [in Slack](https://adhoc.slack.com/archives/C067S0FRP0C/p1715722526035029).

**Comment by alexandec** [comment]
Summary of our team discussion on this today:
- Design System components are currently at 20px text and this is not yet configurable
- We are already using the Link component (see screenshot above) and will be incorporating additional components in the future
- To keep consistency in text sizes across the app, we're going to hold off on switching MobileBody (20) to MobileBodySmall (16) until we can configure the text size in Design System components to match

That means we won't be completing this ticket right now. I'll move it to the backlog, but @ala-yna or @wavelaurenrussell, feel free to close or move it however you prefer.

**Comment by wavelaurenrussell** [comment]
Closing; will not implement after VQA (as mentioned above).
