### ISSUE TITLE
BUG - sev-3 - All - AF use case 1 popups aren't displaying on category screens & home screen

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8548]
## What happened?

All of the screens on the bottom tab bar - home and category screens - use case 1 for availability framework is not working. Use case 2 and 3 are showing up fine for category screens; availability framework use case 1 (popup and prevent navigation to screen) is not. ([Video of both health and profile set up with use case 1 screen, which only shows up for profile](https://drive.google.com/file/d/1BGLu9eiOBSpzLoPuwt0HSwruUUVnHTcc/view?usp=sharing))

Pretty sure this worked at some point in the past; but 1) maybe [my notes](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Remote-Disaster-Mitigation/Framework_notes_DRAFT.md) are missing something or 2) maybe we don't care.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
The question for handoff is how this should work - do we allow use case 1 on these screens? Do we convert them to use case 2 (similarly to what we do for the prelogin screen)? Something else I'm not considering?

**Comment by dumathane** [comment]
We decided in the grooming session that we will not code use case 1 AF functionality for any tab bar/homescreen navigation options.
