### ISSUE TITLE
Additional Home Screen Metrics 

### ISSUE THREAD

**Issue by OVezeamama** [department-of-veterans-affairs/va-mobile-app#8570]
To create tracking for Home Screen 
- individual endpoint load times

**Comment by TKDickson** [comment]
Questions I have, for this ticket, for handoff:
* Would we want to log on error returns (not just success)?
* How do we deal with react query and error retries?

**Comment by dumathane** [comment]
Whoever picks up this ticket please document the new event names as a comment here.

**Comment by dumathane** [comment]
vama_hs_appts_load_time,
vama_hs_claims_load_time,
vama_hs_rx_load_time,
vama_hs_sm_load_time
