### ISSUE TITLE
CU - Use downtime constant in queries

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#8579]
## Proposed Change

Update the recently added downtime logic in queries from https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8481 to use the `DowntimeFeatureTypeConstants` constant instead of hard-coding them. Ensure the import is correct, VS Code will autocomplete the import as `store/api`, which won't cause linting errors, but will cause unit tests to fail. The full import should be `store/api/types`.

## Why Should We Prioritize?

To keep the query code easier to maintain.

## Coding Time Estimation

1
	
## Testing Considerations

Ensure unit tests pass and the `useDowntime` hook works a expected.

## Checklist
- [ ] Add the relevant team label (Health, global, etc.)
- [ ] Attach to the [Engineering Initiatives (Frontend)](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5139) epic

**Comment by TKDickson** [comment]
Did a handful of maintenance window tests (claims, appeals, messaging, Rx, disability rating, appointments) for other HSP testing; it all worked correctly. So whatever we did here, seems to have not messed up anything else. Closing as testing complete.
