### ISSUE TITLE
SPIKE - Prove (or disprove) whether RQ retries help show info, or just slow down app loading

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8582]
## What happened?

When an API call fails, if it's in the React Query migrated features, we will reattempt that call 3 more times before 'accepting' a failure (if it fails all 4 times. Obviously if it succeeds at any point the app will show the data).

We don't _currently_ have a way, front-end or back-end, to tell if these additional calls are helping veterans (aka showing them their data with a pattern like Fail-Fail-SUCCEED, instead of just showing them an error screen on the first failure) or are not helping (aka taking 4 times as long, to ultimately just show an error screen). There _might_ be information logged to the generic error data (now/since it's been on/released for a while), but that information is only available in Big Query and we haven't really dug into it yet, so it's a real head scratcher.

Also - the way the React Query migration has taken place, no one - PM, PO - actually signed off on this fairly large behavior change for error handling in the app.

Also key info - RQ slows down each retry. So: first retry is 1000ms but default is to double that length for each failure on the retry so for us it would be 1000ms, 2000ms, 4000ms
That is likely why the api would take so long is that is 7seconds right there

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Lots of options. Things like:
* Drop retries globally to 0 (old app behavior) and investigate stuff before turning retries back on again
* Adding monitoring to understand the impact of retries
* Configure retries both on a global level and an individual query level.
* Setting retry = (failureCount, error) => ... allows for custom logic based on why the request failed.
* Changing our retry timer: There is also a retry delay feature(default is 1000 ms) but we can change that to whatever we want as well

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Decision from BE/FE meeting is to drop retries to 0 (restoring prior behavior) and we can bring it back up again/explore other ideas later.

**Comment by TKDickson** [comment]
#8657 is the new bug ticket (changing retries to 0), this one will be used for spike/investigation work into what retries SHOULD be. Changing title & labels accordingly.

**Comment by theodur** [comment]
After looking at our queries, I ended up choosing the contact info query (`/v0/user/contact-info`) to test retries. I set the retry limit to `1` and added an analytic event that logs whether a retry was successful or not. The event name is `vama_react_query_retry` and it accepts a string parameter that represents the status of the retry. The status will be `fail` if the retry wasn't successful and `success` if it succeeds.

This only impacts the contact info query, all other queries still have the default retry count of `0`. Since this is an analytic change, this doesn't really need much/if any QA. Since I did update the retry count for the query, I think doing some smoke tests on the Contact information screen should be enough.

**Comment by TKDickson** [comment]
Note on the PR as well - sending back to add the analytic to the letters screen where we call contact info

**Comment by TKDickson** [comment]
Letters (where it shows mailing address) and contact info are both doing just a single retry for failure responses, and I didn't see any downsides to this particular implementation. Analytics, as always, are untested. Good to merge to develop.

**Comment by TKDickson** [comment]
Doesn't require additional in-develop testing; closing
