### ISSUE TITLE
Investigate ES API for determining if someone is enrolled in VA healtcare

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8589]
https://dsva.slack.com/archives/C018V2JCWRJ/p1715257462027469?thread_ts=1715204647.189049&cid=C018V2JCWRJ

**Comment by aherzberg** [comment]
talked with 10-10EZR team and determined which statuses we can use. created issue https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8786
