### ISSUE TITLE
BUG - sev-3 - All - More JWT errors in production

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8594]
## What happened?

The [maintenance windows fix](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8481) (ticket #8432, released 2.28) will (re-)introduce some "JWT token" errors that we've been trying to avoid/fixed in the past (ex: #7922).

We just need to make [this change](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/8559) (from the HSP branch) in develop as well.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by bischoffa** [comment]
Related to Slack Convo https://adhoc.slack.com/archives/C02N65QRRB7/p1715285183410339 

Engineering believes these should be dialed down when RQ retries are turned off as well.

**Comment by TKDickson** [comment]
JWT errors are still happening in PROD, even with filtering exclusively to the 2.33 release. As part of this sprint, I want to investigate/try to reproduce, and either update this ticket or replace with a a bug ticket that's indicative of where these are still leaking through.

**Comment by TKDickson** [comment]
Added [a comment to 8360](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8360#issuecomment-2263387352) - I'm not seeing error reports in firebase where they would have appeared previously for this. Will also be attempting various flows in the app with Charles Proxy monitoring around authentication (initial and subsequent), token refresh, and signout to attempt to manually trigger a JWT error.

**Comment by TKDickson** [comment]
Wasn't able to produce a JWT error during my testing pass either. I'm going to - tentatively - close this. And we can always reopen if we get reports of further JWTs in production.
