### ISSUE TITLE
BUG - Sev 3 - iOS/Android- Cancelling/HW back arrow out of message attachment does not give "delete message" warning

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8597]
## What happened?

When replying to a message and attaching files, but no message text, if you tap "cancel" or use the HW back arrow there is no notification that the attachments will not be saved. this could lead to frustrating situations when the veteran is attempting to respond.

## Specs:

- Device: ipad mini 10, google pixel 4a
- OS:
- User Account: +226
- Accessibility State: N/A

## Steps to Reproduce

- tap reply on a message more recent than 45 days
- attach photos either via camera, or file folder 
- tap "cancel" or on Android hit the HW back button
- observe you are returned to the message you had tapped reply on and there is no draft of the reply and there was no "delete/keep editing" option

## Desired behavior

Assumption is the user would be faced with a similar prompt to what they get when they tap cancel or the HW back button on a new message or on a reply that has text entered

## Acceptance Criteria

TBS

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by alexandec** [comment]
After initial work, I found some additional complexity around error handling so I'm increasing the estimate.

**Comment by rbontrager** [comment]
Verified that canceling/backing out of a message reply with only a message attachment now gives you the 'delete message' menu option.  Approved by QA.
