### ISSUE TITLE
BUG - Sev 3 - android - word wrapped text about attachments on "delete message?" prompt is center aligned while being left aligned

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8598]
## What happened?

on android if you are drafting or replying to a message and tap "cancel" you will get a "are you sure you want to delete.." message and the sub messaging about attachments is center aligned, while also being generally left aligned and looks "wonky" as we say in the biz.

## Specs:

- Device: google pixel 4a
- OS:
- User Account: +226
- Accessibility State: N/A

## Steps to Reproduce

- using an android device start a message, or reply to a message
- enter some text
- tap cancel
- observe the messaging

## Desired behavior

should look pretty and awesome, 

## Acceptance Criteria

TBD

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99012303fe690df66b8a37ce1f66121f5210167d/Screenshot_20240509-165557.png" alt="Screenshot_20240509-165557.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
@wavelaurenrussell 

These are the available alignments
"auto" | "left" | "right" | "center" | "justify" | undefined

We currently supply "center" to all action sheet pop ups.

If center is the desired behavior there is unfortunately nothing we can do from here to make this look better.

If we are wanting to change it we have a few options. Please let me know what is preferred.

**Comment by wavelaurenrussell** [comment]
@Sparowhawk if this change will result in changing native iOS action sheets, then no, let's not do it. We don't want to override the iOS appearance at all.

**Comment by rbontrager** [comment]
Verified that word wrapped text on android action sheets is now left aligned (see screenshot). Verified that this does not affect iOS action sheets.  Approved by QA.

<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9PQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf898d908d24500fee7b032f68e6cc40e7486e3f/Screenshot_20240625-104458.png" alt="Screenshot_20240625-104458.png" />
