### ISSUE TITLE
Componentization - Video at Home appointments - Detail View

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8608]
## Description 
As an engineer, I want create and reuse different standardized components for appointments, so that it will easier for other teams to start working in appointments and the different appointment types can be more aligned.

Specific details of the components needed can be found in [this spreadsheet ](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=402791918) (see columns R, S, T, U on "Details screen section" tab and also "Video (Home)" tab as needed) and the design specs can be found in [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?node-id=2560-9615&t=DREGEQufkX5Vcl87-4)

As part of this story we want to: 
- Create new components that are needed for confirmed, past, and canceled video at home appointments
- Plug in any pre-existing components
- Update end to end tests
- Update headings to match [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?node-id=2560-9615&t=DREGEQufkX5Vcl87-4) file
- VQA with content/design

## Acceptance Criteria

-  [ ] New components have been created
-  [ ] Existing components have been brought in
-  [ ] E2E tests have been updated
-  [ ] VQA by content
-  [ ] VQA by design

**Comment by rbontrager** [comment]
Verified that the Video (Home) detail view follows the outline given in the spreadsheet and the design from figma. Passing test case can be found [here](https://dsvavsp.testrail.io/index.php?/tests/view/1222054&group_by=cases:section_id&group_order=asc&group_id=18499&group_by=cases:section_id&group_order=asc&group_id=18499). Approved by QA.
