### ISSUE TITLE
QA: Test Plan Appointments Componentization

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8611]
## Objective 

The purpose of this ticket is to document the test plan for Componentization for Appointments.

## Reference Material:
- [Spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=106638797)
- [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?node-id=731%3A2493&t=eWH8cJ0IguoMXAxU-1)

**Epic(s)**
[8500 - Componentization for Appointments](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8500
)
## Acceptance Criteria

  

1. - [ ]  Create test plan
2. - [ ] Link to test case folder in TestRail
3. - [ ] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by rbontrager** [comment]
@DJUltraTom Would you mind doing a test case review for me? Test cases can be found [here](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=18499&group_order=asc&display_deleted_cases=0). Modeled off of figma and the spreadsheet design found in the references section above.

**Comment by DJUltraTom** [comment]
@rbontrager looking good so far couple of questions:
Is this just a cosmetic change? (if it is functional we will want to do maintenance sindows, error cases etc)
Will changes to list view be tracked on a different ticket?
Do we have the test data required for all the appointment types (EG: Atlas)?

**Comment by DJUltraTom** [comment]
List view looks good! @rbontrager thumbs up from me

**Comment by bischoffa** [comment]
@rbontrager if Tom's work on this ticket is done can he be unassigned?

**Comment by bischoffa** [comment]
Also looks like the sprint needs to be updated since its still open

**Comment by rbontrager** [comment]
@bischoffa Forgot to close this ticket 2 days ago.  Everything is done and the test plan is complete.
