### ISSUE TITLE
Migrate: Provider Name to the appointments service

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8629]
## Description 

As part of our goals to consolidate and unify appts data logic between Web and Mobile Platforms, this story serves to migrate **find_and_merge_provider_name** to the appointments service on Vets API.

**Additional Information:**
Web's vets-api controller has logic to fetch provider names from ppms & return them for cc appts. we want to move this to the service layer as well.

**Formal Steps:**

1. Identify/Review Vets API for duplicate Code for **find_and_merge_provider_name**

2. Ensure unification (Data is identical)

3. If data is not identical, address the duplicate code and ensure data is corrected.

4. Identify what will be the common field (the field that will present and be the same on both platforms)

5. Migrate the field identified in #4 to the appointments service on Vets API

## Acceptance Criteria
  

-  [ ]  Identify an Impacts (prior to migration)
-  [ ]  See Formal Steps above

**Comment by StacyB2023** [comment]
@jperk51 Just an FYI

**Comment by kpethtel** [comment]
Tested with Judy on staging. Seeing provider data in index, show, and create as expected.
