### ISSUE TITLE
Update RN to 0.74

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#8630]
Update the app from 0.73.x to latest 0.74

**Comment by timwright12** [comment]
@bischoffa Same here, adding QA back since React Native is a major dependency

**Comment by bischoffa** [comment]
Ticket needs an epic @timwright12 @Sparowhawk what epic is Global using to track RN changes like this so POs can see it? 

@TKDickson what kind of review does QA need to do before Engineering works this? I know sometimes major dependency updates are worked and it requires a lot of testing. I am assuming .73x to .74 would be minor but want QA to call out this change before FE picks it up.

**Comment by timwright12** [comment]
@bischoffa we may even want to skip these patch-level updates

**Comment by bischoffa** [comment]
@timwright12 given that it doesn't seem the ticket is ready to be worked as we do know if we want to skip it or do them. I am going to move this to blocked until Eng determines next steps and aligns that its ready to be worked.

**Comment by theodur** [comment]
Closing this since #9430 exists
