### ISSUE TITLE
BUG - Sev 2 - All - Hyperlink renders over text when punctuation is off

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8634]
## What happened?

A veteran reported that messages with hyperlinks were showing up abnormally in the app. See [thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1715712811382269).

## Specs:

- Device:  iPhone 13 Pro Max
- App version: 2.27.0

## Bug Severity - Sev 2
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 
- 2 - High

## Screen shot(s) and additional information

See [thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1715712811382269).

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
18005551234
1 800 555 1234
+1 800 555-1234
+86 800 555 1234
1-800-555-1234
1 (800) 555-1234
(800)555-1234
(800) 555-1234
(800)5551234
800-555-1234
800.555.1234
800 555 1234x5678
8005551234 x5678
800 555 1234*5678
8005551234 *5678
1 800 555-1234
1----800----555-1234
(800)698-2411,
1-800-698-2411.
+8006982411

**Comment by rbontrager** [comment]
@Sparowhawk A couple small things.  800 555 1234*5678 doesn't work on one of my iOS devices. I don't know if you want to remove that option. 8005551234 x5678 and 8005551234 *5678 are only hyperlinking the numbers before the space and removing x5678 and *5678.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWI2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--354530265157d8bff7beb5f93d254aea044c613b/IMG_0020%20%281%29.PNG" alt="IMG_0020 (1).PNG" />

**Comment by Sparowhawk** [comment]
@rbontrager I removed support for * to work across the board. Unfortunately the remaining one 8005551234 x5678 is going to remain unsupported as well. This is due to it being 2 strings separated by spaces instead of the 3. When specifically checking for 2 strings it broke a lot of instances. So i will reflect that into the ticket as well.

**Comment by rbontrager** [comment]
Verified that the hyperlink no longer renders over text when punctuation is off.  Verified that the new reqex logic works as expected and that the phone numbers listed in Dylan's PR come in as expected. Approved by QA.
