### ISSUE TITLE
Create monitor to satisfy t1 app requirements for missing/low request volume

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8650]
https://github.com/department-of-veterans-affairs/octo_watchofficer/issues/41

**Comment by timwright12** [comment]
@jperk51 any updates on this one?

**Comment by jperk51** [comment]
Still working on tuning it. It's not taking up a ton of my time but it will likely push beyond a couple sprints. I need to make changes, let it run for several days, then make more changes, and repeat.

**Comment by jperk51** [comment]
After many many tweaks I think this is in a good spot. This sprint I'll be adding it into our normal oncall process and adding the watchtower tag back.
