### ISSUE TITLE
HSP: Update section title styles on the homescreen

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8652]
### Description

When working through the visual design feedback with POs, we discussed a small change to address Rachel's initial comment: 

> my comment: please ensure spacing and font size of content on Home, Health, Benefits screens are consistent and "makes sense" to users. 
> @rtwell
>  as discussed, need your help here to provide more detailed feedback.

I worked with Ryan to determine ways to differentiate Home from Category screens, to provide further distinction that these are two separate areas conducting two separate "jobs". We opted to provide visual cues for the distinction, as its less clear that this is a true spacing issue. 

As part of this story, we want to: 
- Update the section titles on the homescreen [(Figma example)](https://www.figma.com/design/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?node-id=3090-2632&t=usSWJLfArCz6BhN9-4)
        - Activity
        - About you
        - VA resources 
- Leave the category screens alone

### ACs
- Eliminate the existing style: Bitter 400; 18px
- Use Mobile Body Bold (Source Sans Pro 700; 20px) for the section titles

**Comment by TKDickson** [comment]
Checked iOS and Android, light and dark. Many screenshots:
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2Z4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d655cbc590b215bb722d8b639fae59007e5667f7/image.png" alt="image.png" /> <img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2p4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--070b4c2c80055ee78364543b85530e7c33c6faa3/image.png" alt="image.png" /> <img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM254QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14363eec31de94fb47ee438607a9bc752f387f27/image.png" alt="image.png" />
 <img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3J4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--37b85b1da57e003d3eb50a64c2f3bc86aa692138/image.png" alt="image.png" /> 
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzN4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--983ee0c04a09ed0c295da5d3f97857f00885662c/image.png" alt="image.png" />
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzd4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c79596dc46ed96802f1a1287867b136ff523176/image.png" alt="image.png" />

**Comment by wavelaurenrussell** [comment]
Looks good!

**Comment by TKDickson** [comment]
Merged; closing.
