### ISSUE TITLE
PresentationFilter- Investigate/Merge for appts service

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8660]
## Description 

This ticket is to investigate merging the Presentationfilter field (associated with date range) to the appointments service.

Details on Presentationfilter (FE Changes needed):

- mobile FE will need to handle its own caching and pagination. (Moving to another ticket)

- web can (but does not necessarily need to) remove some of its filtering logic. This logic was copied into the **PresentationFilter** class in the backend. The web could use this filter.

- web can (but does not necessarily need to) consolidate some of its fetches. It could combine its upcoming and recently proposed/cancelled requests into a single request. **The PresentationFilter** will remove any appointments that shouldn't be shown.

- web could (but does not necessarily need to) remove the separate fetch it uses for facilties and instead fetch upcoming appointments at login. The upcoming appointments fetch is slightly more expensive because it requests more types of appointments and also fetches clinic data, but it would result in fewer total calls and could result in better load times when the user navigates to appointments.

Reference the [Investigate Date Range](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8572) Ticket for full details

- 

## Acceptance Criteria
  

-  [ ] Investigate merging to appointment service (what field should be hidden etc)
-  [ ] Test any changes on staging
-  [ ] Consider modifying this script for testing which appointments are on staging web before and after changes: modules/mobile/lib/scripts/appointments_list_validation.rb

**Comment by Tonksthebear** [comment]
Looks like the first bullet point about caching should be turned into another ticket as that work is unrelated to the PresentationFilter. Also blocking this until Kris's ticket is closed
