### ISSUE TITLE
BUG - Sev-1 - All - Profile page is infinitely loading for users who do not have militaryServiceHistory authorized

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8662]
## What happened?

The profile screen is no longer loading (which means the user can't log out of the app) if the militaryServiceHistory service is not authorized. This may have been introduced with the 8432 (the maintenance window work). Can confirm the profile screen loads on the daily build for May 2nd but does not load within the builds for 8432. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Login to user +7
2. Navigate to the profile screen. Notice that the profile screen is infinitely loading and the user can not do anything like log out of the app

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
With user +7, profile screen successfully resolves and I can do things and log out.
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1B3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd614b4fc99cbcee2a4a27cd5672d6e10693f41b/image.png" alt="image.png" />


I also used Charles to mock a 'true' response for military service history in authorized services for +7 (which returns a 403 when we then ping the military history API). In that case, +7 was still able to log out (after getting the usual error + Settings on the profile screen).
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1h3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c06b78030321b08159712fba69a2b629d248224d/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing as fixed.
