### ISSUE TITLE
Update current device pool to match OS compatibility and support standards

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8664]
We now have officially-documented (and updated) [OS support standards.](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/Compatibility) from work in #7601. Now we need to make sure we're adhering to them.

This ticket encompasses:

- [x] The coordination work to get the team's devices onto our supported (active) OS versions (unless they are currently using an older OS version for a very specific reason, of course)
- [x] The documentation work to get [whatever our device source of truth is] also updated with the correct OS versions (at least major, if not minor) for people's devices across the team
- [ ] Adding a link from the QA compatibility and support page of the doc site, to the source of truth for devices. 

_Estimated as a 'long 3' because the actual active time working on this should be 1 day or less; that ~8 hours of work will likely be spread over several days. (ex: drafting & posting initial ping telling people to update devices = 15 minutes. 3 days later, inputting the device info you've gotten into the source of truth and then following up with people you haven't heard from, another hour. 3 days later repeat, etc.)_

**Comment by TKDickson** [comment]
FYI @bischoffa that I added this to the platform prep epic (if that's the wrong epic, let me know! There are... a lot of epics to keep track of.)

Assigned to @DJUltraTom not as a "do this now", but because he's the current device owner/I haven't heard _officially_ any differently, so whatever sprint this gets pulled in, he would do the work.

**Comment by bischoffa** [comment]
@DJUltraTom thoughts on pulling this in next sprint that starts next week?

**Comment by DJUltraTom** [comment]
Wrote and sent email out soliciting OS versions of current test devices from team members who are listed as having them.

**Comment by DJUltraTom** [comment]
updated the device inventory sheet with information received, 
at 24 hours in we have 8 responses from 18 emails.

**Comment by DJUltraTom** [comment]
email sent to those who still haven't responded yet

**Comment by bischoffa** [comment]
@DJUltraTom given this is continuing into this sprint can you update the sprints to include the current one its in?

**Comment by DJUltraTom** [comment]
all devices have been reported for.
Currently we appear to have a decent spread for device Os's the last 3 android versions are in use by QA and there is a decent spread of coverage of iOS versions.
The device inventory sheet has been updated. 
Closing this ticket

**Comment by bischoffa** [comment]
@DJUltraTom where does this documentation live?
