### ISSUE TITLE
Update some link announcements to "external link" for screen readers

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8671]
UX team has discussed the using descriptive icons to indicate whether a link was external to screenreader users. 

Two places where we'd need to add this (from home screen personalization) are:
- "Learn about PACT Act on VA.gov" – I would recommend announcing this as an "external link" vs. just "link", if possible.
- the 'not enrolled in VA healthcare' announcement-style banner on the health category screen, then.

Can use the [buttons and links audit spreadsheet](https://docs.google.com/spreadsheets/d/1uOF4dn3yptsp7VnxwG7owy2p0GDHjmBq1oBR8MIVvWg/edit?usp=sharing) to determine all of the external links (plus the two above), all of which would get the new announcement.

**Comment by brea11y** [comment]
During grooming, it was discovered that this would be a much larger lift and would have to be a manual update on all external links throughout the app. Closing this for now, but in the future, we could consider creating a custom component with a descriptive icon that reads out as "external". If we did that, we would build the component in a way that could be automated in the future, then update the external links throughout the app with that component. A larger lift upfront, but would be much easier to update in the future. For now, we'll hold off on this and revisit an app-wide change down the road.
