### ISSUE TITLE
Secure Message List date field update

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8687]
### Description
When reviewing the Messages list, we discovered issues with the right-aligned date stamp that appears on the Message list item. When larger font sizes are enabled or the app is rendered on smaller displays, the date wraps in a smaller area with the current row design.

As part of this story, we want to: 
- Left align the date for patterning sake, and accessibility
- Change the date format to [Month 00, YYYY]. Align the syntax with Message Details.
- Clean up any associated code

### ACs
- [ ] Date is listed below the Sender name, and left-aligned like the rest of the copy
- [ ] Date format is updated
- [ ] VQA with Lauren

### Figma assets
[Link to mockup](https://www.figma.com/design/10G0dWvxIv3qzVdU3uRiQU/%F0%9F%94%8D-Messages-2.0---Working---VAMobile?node-id=1309-2018&t=C0SlOZi69Irw4oUK-4)

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlA5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02392280d6a55b3c5a1d07da9dfae04c639dcc58/image.png" alt="image.png" />

**Comment by alexandec** [comment]
Approved by Lauren: https://adhoc.slack.com/archives/C067S0FRP0C/p1718054517409069

**Comment by rbontrager** [comment]
@alexandec  The read receipt bubble is not left aligned with the rest of the text (see picture).  There are multiple instances of it in the sent folder in SM for user +226 if you need it for verification purposes. 

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVJyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c33a540cf4a0a04d2263e7f5c0614b92fe933b1/IMG_0079.PNG" alt="IMG_0079.PNG" />

**Comment by alexandec** [comment]
@rbontrager thanks, I've fixed it

**Comment by rbontrager** [comment]
Verified that messages follow the figma design outline above where the date format has changed to Month DD, YYYY.  Verified that everything is left aligned including the read receipt.  Verified that no screen reader changes have occurred and that everything looks good in landscape, dark mode, and large text. Approved by QA.
