### ISSUE TITLE
BUG - sev-2 - All - Messages: can't send messages from draft (only new)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8689]
## What happened?

When attempting to open a draft and send the messagee, I can't. The UI in the app is just a generic error snackbar, but the API responses are giving an error back that it doesn't have a recipient (it does, so there's something else afoot). 

See the charles proxy section for the reponses I got for +226, with the second draft in the list of drafts (Subject: Test: Test Inquiry, 1pm timestamp).

Have reproduced on the 5.21 develop build as well as the HSP branch.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  
`mobile/v0/messaging/health/messages/3620826`

HTTP/1.1 200 OK
Date: Tue, 21 May 2024 20:07:52 GMT
Content-Type: application/json; charset=utf-8
Etag: W/"7b0cd6334470726f3274935ff5dd14f9"
Referrer-Policy: strict-origin-when-cross-origin
Vary: Accept, Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Frame-Options: SAMEORIGIN
X-Git-Sha: a12ca244559ed07b071c8ed46c917586b7d54c55
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 52f4b9f3-ac08-4d51-964f-fa9fa7609a92
X-Runtime: 0.438598
X-Xss-Protection: 0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Cache-Control: no-cache, no-store
Pragma: no-cache
Content-Encoding: gzip
Transfer-Encoding: chunked
Connection: keep-alive

{"data":{"id":"3620826","type":"messages","attributes":{"messageId":3620826,"category":"TEST_RESULTS","subject":"Test Inquiry","body":"Test","attachment":false,"sentDate":null,"senderId":873433,"senderName":"WEAVER, JOHNNIE  LEONARD","recipientId":1766073,"recipientName":"VA Flagship mobile applications interface 1_DAYT29","readReceipt":null,"triageGroupName":"VA Flagship mobile applications interface 1_DAYT29","proxySenderName":null},"relationships":{"attachments":{"data":[]}},"links":{"self":"https://staging-api.va.gov/mobile/v0/messaging/health/messages/3620826"}},"meta":{"userInTriageTeam?":true}}

POST to mobile `v0/messaging/health/messages`
{
	"body": "Test",
	"draft_id": 3620826,
	"category": "TEST_RESULTS"
}

response back from `mobile v0/messaging/health/messages`
HTTP/1.1 422 Unprocessable Entity
Date: Tue, 21 May 2024 20:07:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 170
Referrer-Policy: strict-origin-when-cross-origin
Vary: Accept, Origin
X-Content-Type-Options: nosniff
X-Custom-Response-Header: eks-staging
X-Frame-Options: SAMEORIGIN
X-Git-Sha: a12ca244559ed07b071c8ed46c917586b7d54c55
X-Github-Repository: https://github.com/department-of-veterans-affairs/vets-api
X-Permitted-Cross-Domain-Policies: none
X-Request-Id: 98ea0fbe-bcd5-4cee-a158-4fce381bd964
X-Runtime: 0.029036
X-Xss-Protection: 0
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Frame-Options: SAMEORIGIN
Connection: keep-alive

{"errors":[{"title":"Recipient can't be blank","detail":"recipient-id - can't be blank","code":"100","source":{"pointer":"data/attributes/recipient-id"},"status":"422"}]}

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
I'm also seeing this in the 2.28 RC build

**Comment by DJUltraTom** [comment]
the on demand build fix looks good. found: [8691](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8691) while verifying, likely unrelated.

**Comment by DJUltraTom** [comment]
spot checked on RC build, looks good! closing
