### ISSUE TITLE
BUG - sev 3 - both - after sending from draft folder, Secure message is clickable and gets a "app not working" screen

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#8691]
## What happened?

Found while testing the fix for [8689](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8689) but likely pre-existing
When sending a message from the drafts folder, the user is returned to the message list view and the sent message is still present. On android you can tap the message and tecieve an "app is not working screen
On iOS you are able to access the edit screen for a short period and are able to edit the message, but unable to send. if the user returns to the message list and tape the message again they recieve the "app is not working" screen

## Specs:

- Device: ipad mini, pixel 4a
- OS:
- User Account: +226
- Accessibility State:N/A

## Steps to Reproduce

- go to the drafts folder (that has saved drafts)
- edit and send a saved draft
- observe you are returned to the messages list and the "sent" message is still present
- tap the "sent" message again
- Android: observe the "App not working" message
- iOS: observe message is editable but cannot send. on additional visits to the message the "app not working " screen will appear.

## Desired behavior

Messages should not appear in the list view once sent
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
Verified that messages are no longer in the drafts folder once sent.  Approved by QA.
