### ISSUE TITLE
2.29 Release Candidate Testing Testing

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8698]
Placeholder ticket for the work Tom does for RC testing for release 2.29

**Comment by DJUltraTom** [comment]
testrail run for RC manual testing is [here](https://dsvavsp.testrail.io/index.php?/runs/view/5533&group_by=cases:section_id&group_order=asc)

**Comment by DJUltraTom** [comment]
QA has completed its RC test runs and have updated the release ticket: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8692
