### ISSUE TITLE
BUG - sev-3 - Android - Messaging: cannot get cursor to first line of message

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8724]
## What happened?

Here's the "highest" in the new message box that I can put my cursor. I can't delete, nor move, to get it further up. Probably the same issue as in #3540, but... even worse now, because it's more lines of wasted space.

<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e91a908ed6d796d29c7e04dd6ff92756316ef70/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

There are existing reports about the size and alignment of text boxes (ex: #8531), so we should be making the best use of them in relation to the viewport as possible.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
@TKDickson I saw your comment in the other ticket that Theo fixed. Does the appearance still look the exact same as the screenshot above or did that change?

**Comment by TKDickson** [comment]
@Sparowhawk It's the same UI as that screenshot, yes.

**Comment by Sparowhawk** [comment]
@TKDickson Found the issue.

There is a Android only text input prop that we didn't set

textAlignVertical: isTextArea ? 'top' : undefined,

Creating a pr for this now

**Comment by rbontrager** [comment]
Verified that the cursor is now positioned in the first line of the message.  Approved by QA.
