### ISSUE TITLE
BUG -  Sev-3  Have generic/team email associated with App Tester (currently individual)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8725]
## What happened?

At least in my App Tester view, there's still an individual's email associated with our app + App Tester, not a team one. I know @timwright12 was trying to find and replace all of these at some point, so - here's one more.

<img width="361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlPQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0371ac770b8211ca02ccd76944aec2308d978a69/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by timwright12** [comment]
Related ticket: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5662

**Comment by TKDickson** [comment]
@timwright12 are we just/still waiting for a valid email address to sub in, is that the blocker?

**Comment by timwright12** [comment]
@TKDickson we updated it ad the app level, I guess it doesn't propagate into app tester. I'll take this on

**Comment by TKDickson** [comment]
It also very well could have come in, I didn't check yet (just looking in on bug tickets in the blocked state). So 🤞 maybe it's working

**Comment by timwright12** [comment]
I updated this to my email for the time being. Syncing with @DonMcCaugheyUSDS as well

**Comment by DonMcCaugheyUSDS** [comment]
As per @timwright12 's recommendation [here](https://dsva.slack.com/archives/C02CDKNNA2K/p1722538244228559), let's change this to VAFlagshipMobile@va.gov for now.  I have a todo item to get us a mobile dev team support email separate from the public support VAFlagshipMobile email (which also needs a better name, "VAFlagshipMobile" is kinda weird).

**Comment by timwright12** [comment]
We ended up setting this to Don's email. Closing out.
