### ISSUE TITLE
BUG - sev-3 - All - Appointments: may be showing cancel button for appointments that can't be cancelled

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8726]
## What happened?

Logged in as john.morrison, I attempted to cancel his August 9th mental health confirmed appointment at Cheyenne.

I got this error response:
```
{
	"errors": [{
		"title": "Bad Request",
		"detail": "appointment may not be cancelled",
		"code": "VAOS_400",
		"source": {
			"vamfUrl": "https://internal-dsva-vagov-staging-fwdproxy-1821450725.us-gov-west-1.elb.amazonaws.com:4463/vaos/v1/patients/33bbf6d4c69db6e794a806e7da0c6a653d981803cc0b2b5d8f183741720b2850/appointments/57d7cce5324f1c433daa53470a4736c0a521c215632381ad754acf9ff2cd8f64",
			"vamfBody": "{\"message\":\"appointment may not be cancelled\"}",
			"vamfStatus": 400
		},
		"status": "400"
	}]
}
```

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
Verified that only in person and phone appointments can be canceled and only pending VA appointments can canceled as well.
