### ISSUE TITLE
Feature Request: Refresh product page's app name and subtitle in app store

### ISSUE THREAD

**Issue by janieTC-USDS** [department-of-veterans-affairs/va-mobile-app#8736]
### Full Name

Janie Tankard Carnock

### Email

jane.carnock@va.gov

### What would you like to add as a new feature?

More descriptive info on product page in app store

### Please explain how it would work.

Slack thread here: https://dsva.slack.com/archives/C018V2JCWRJ/p1716902285792919?thread_ts=1716902265.465739&cid=C018V2JCWRJ

The Secure Messaging team on MyHeatheVet (OCC) is working towards implementing a smart app banner on the MHV Classic pages to point more users to the VAHB mobile app (and highlight this over the VA.gov experience for all mobile web users). Our OCC product stakeholder is aligned on this approach, but gave some feedback that the current wording of the banner is kind of vague and wondered if we could make it clearer that this is linking people to the native mobile app or at least some content to speak to the value prop of the mobile app?  

A from Ryan & Rachel:
- Via Ryan: i think tailoring the content would be great. right now, we’re saying “this thing exists” without mentioning why you, the user, should care.
- Via Rachel:  ...In this case, we can be better about the product page on the app store, including taglines, subtitles, etc. 

Note: This is not a blocker for the MHV Classic webpage but rather a requested enhancement.

Thank you!

**Comment by janieTC-USDS** [comment]
![image](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/126614629/0601c677-9c31-43d0-9d9c-204caf75b455)

Example of Gmail in browser pointing to the native mobile app, which has a bit more descriptive language around value proposition

**Comment by timwright12** [comment]
Kicking this over to @mistymg and @ajsarkar28 for review

**Comment by ajsarkar28** [comment]
@janieTC-USDS 
We are actively working on this in this [epic](https://github.com/orgs/department-of-veterans-affairs/projects/823/views/13?sliceBy%5BcolumnId%5D=22708126&sliceBy%5Bvalue%5D=Global&filterQuery=label%3AEpic+global&sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=33278702&pane=issue&itemId=82623627&issue=department-of-veterans-affairs%7Cva-mobile-app%7C9829) so I am going to close this ticket
