### ISSUE TITLE
BUG - Sev -3 - All - Messages aren't being updated in the message thread after you edit and save a draft message

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8744]
## What happened?

Anything added isn't being shown in the message thread after you edit a draft message and save it.  It looks to be a refresh issue because once you back out of messages and go back in the new words are being shown. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Login to user +226
2. Click on the first message in the inbox and click 'reply'
3. Add something to the message field (take not of what you typed) and tap 'more' > 'save'
4. In the drafts folder click to open the newly made draft.  Change the wording in the draft and save again
5. Navigate back to the first message and open it.  Notice that the message hasn't updated with the new edits given from step 4

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
@Sparowhawk Saving a draft still isn't updating the thread in the message card.  I've include a video of what I'm doing (though it should match the steps above). Can confirm that sending draft, or saving reply or sending a reply and deleting the draft is correctly updating the thread. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f44a87434efb3f26b3c6c2f15e01bd11ce1a938/screen-20240530-075203.mp4)

**Comment by Sparowhawk** [comment]
@rbontrager That loading screen when you re entered the message is fetching the thread. Everything else is still in the cache. That is a race condition then with the BE cache not updating yet. I have added busting the cache so it forces BE to fetch from upstream and then return to us. If that doesn't update us then there is not a whole lot I can do for this.

**Comment by Sparowhawk** [comment]
fixed

**Comment by rbontrager** [comment]
Verified that the message thread is being updated after you edit and save a draft. Verified that the message thread is being updated after sending a draft, saving a reply or sending a reply and deleting the draft.  Approved by QA.
