### ISSUE TITLE
BUG - sev-3 - All - Loading icon animation glitches on home screen

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#8746]
## What happened?

When the Activity section or About you section is loading on the home screen, the loading icon animation resets whenever the screen re-renders (which happens whenever there are changes to a query, e.g. when a query starts loading, finishes loading, etc.), which causes the icon animation to appear as if it's glitching. This primarily happens when a user

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Open the home screen with a testing user and view the loading icon glitch.

## Desired behavior

The icon animation should not reset when re-renders happen on the screen.

## Acceptance Criteria

- [ ] Prevent loading icons from resetting during screen re-renders

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

[LoadingAnimationGlitching.webm](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/9042882/8eab304e-f00c-4bec-9956-4f8f14791bec)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
@TKDickson Heads up, the actual fix for this was like 3 lines of code, but I also did some subjectively "minor" refactoring to the home screen code (mainly just condensing variables). I didn't change any functionality, but just wanted to throw that out there 😅

**Comment by TKDickson** [comment]
We removed the refactoring (from the comment immediately prior) from this PR and attached it to new ticket #8858.

The loading icon is buttery smooth now (I hadn't realized how used to the glitchy look I had gotten!). This is approved to merge to the feature branch.

**Comment by TKDickson** [comment]
Merged; closing.
