### ISSUE TITLE
Feedback Hub: Add Monthly Rating Average View

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#8748]
Rating history viewer has been added, but another higher level view has been requested. This view should just summarize the rating for the app in each month of the data we have

**Comment by StacyB2023** [comment]
Added to the feedback hub epic FYI @Tonksthebear

**Comment by StacyB2023** [comment]
Adding the analytics link here: https://feedback-hub-e659c24714b9.herokuapp.com/analytics
