### ISSUE TITLE
CU - [Preserve white space in linkified text for secure messaging]

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#8750]
## Proposed Change
It would be nice to maintain white space for users secure messaging

## Why Should We Prioritize?
Makes the message look cleaner

## Coding Time Estimation
3
	
## Checklist
- [ ] Add the relevant team label (Health, global, etc.)
- [ ] Attach to the [Engineering Initiatives (Frontend)](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5139) epic

**Comment by rbontrager** [comment]
Verified that white space in linkified text is preserved in SM.  Approved by QA.
