### ISSUE TITLE
BUG - sev-3 - All - Should reconsider our appeals access policy, as it leads to poor app behavior IRL

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8752]
## What happened?

Our current access policy for appeals (in authorizedServices) is essentially "every veteran gets access to appeals". Specifically: 
[Backend team]: 

> this is the policy for appeals: `user.loa3? && user.ssn.present?`

Trevor Bosaw:

> For the mobile app, we force all credentials to be identity proofed, so user.loa3? should be true for all users who have successfully authenticated to the mobile app
> Additionally, if you are identity proofed and have logged in through a VA web system, an MPI record will be created for you. This happens whether you are a veteran or not. So user.icn should also be true for all users who have successfully authenticated to the mobile app
> Finally, in order to be identity proofed, at least on id.me and login.gov, I'm pretty sure SSN is a requirement, so user.ssn should also be true for all users on the mobile app (edited)

So, in addition to the "should everyone have access to appeals" (probably not?) thing, the fact that everyone does have access to appeals (but for many people, who don't actually have appeals data, it will error out) is causing delays on the new home screen (where we, every time you navigate back to the page, call the claims and appeals API again in the hopes of getting actual info instead of just an error state. This re-call causes the home page to go into its loading state, where none of the HSP activity section is available until all API calls resolve)

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

As a user without claims & appeals access (basically any scheduling user OTHER than judy.morrison; I think karsyn (rx test user) is also in this state), log into the app.

## Desired behavior

Can we reassess what 'authorized' means for appeals/find a better source of truth for that, so we're not constantly throwing an error for users who just don't have access/information?

(We can't - and arguably, even if we could, shouldn't - make changes on the FE to code selectively around this particular "you don't ACTUALLY have any claims or appeals, but we're always going to treat you like you DO have appeals" state)

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
@theodur you already looked into it and discovered that it's not possible for the FE to selectively cache/not for specific API errors, right?

If yes, I can remove that portion from the writeup and then the way to fix this ticket would be to have a different access policy on the backend; I'd likely write up a new ticket for that.

**Comment by theodur** [comment]
@TKDickson It's not possible to cache errors with React Query out of the box, but since the Home screen doesn't re-render during a session (it always stays on the nav stack), technically errors will be somewhat cached since errors are only cleared when a screen gets re-rendered or the query gets refetched. So it is possible to not refetch if it's a specific error, we'd just need to take a more manual approach.

I'm still wondering if fixing this on the BE with a different access policy would be a better way to go about this though. Seems like we'd be coding around an API nuance if we solved this on the frontend.

**Comment by TKDickson** [comment]
@theodur thank you for the writeup. I agree a backend change is the better way to go here - I will modify the ticket accordingly then.

**Comment by TKDickson** [comment]
@StacyB2023 @jperk51 where should I put this ticket, to get it into the eventual backend queue? (Pending handoff....?) Thanks!

**Comment by StacyB2023** [comment]
@TKDickson yes pending handoff should work. We have estimation tomorrow. The team may come back with some questions. cc: @jperk51

**Comment by jperk51** [comment]
Removing the API tag from this ticket. @kpethtel is going to make a BE specific one for our tracking and estimating.

**Comment by TKDickson** [comment]
That ticket is #9114, which Kris also added as a blocker to this one

**Comment by TKDickson** [comment]
Still blocked, by ticket above.

**Comment by TKDickson** [comment]
The API team is doing an entire epic of "reassess every access policy" which renders this particular ticket duplicative. Closing.
