### ISSUE TITLE
Update policy for healthcare features to use Enrollment Status API and create endpoint to check enrollment status

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#8786]
The 10-10EZR form team uses an API already in vets-api called enrollment status (see `app/controllers/v0/health_care_applications_controller.rb`). on the web FE they allow any user that has a status of enrolled, pending_mt, or pending_other (see https://dsva.slack.com/archives/C05Q6411HPF/p1717431885651859). We should switch out (or at least add to) our existing healthcare features policies with this check. 

It may also be beneficial to have our own enrollment status endpoint because the FE has a "enroll for VA healthcare" banner (see related blocked issue ) that never shows and they can use that endpoint to determine if not only if they are not enrolled but if they are ineligible to enroll. The endpoint and policies could cache the response and be shared.

**Comment by jperk51** [comment]
As an update to letters there is very likely going to be need to integrate with this anyways. There is already a vets-api service integration for this.

**Comment by kpethtel** [comment]
Tested on staging with Judy.
