### ISSUE TITLE
Clean up no longer used appointment code

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#8790]
Clean up all of the no longer used code once community care and video home appts are merged

Consider the following:

translation strings
old appts components
appts util functions
unused code in upcoming appts details
unused code in past appts details

any other code no longer used in relation to appts

**Comment by rbontrager** [comment]
Re-ran the appointment tests [here:](https://dsvavsp.testrail.io/index.php?/runs/view/5649&group_by=cases:section_id&group_order=asc) and confirmed that everything still worked as expected.
