### ISSUE TITLE
Investigate BE API  (Claims Step Expansion)

### ISSUE THREAD

**Issue by StacyB2023** [department-of-veterans-affairs/va-mobile-app#8799]
**Overview **:

-  VA.gov is moving the current state of the claims functionality from a  **5 Step Claims Process to 8 Step process**
-  In order to have a seamless user journey, we would like the mobile application to reflect the same (where possible) to what is seen by the user on VA.gov. 

**Investigation Story Needed:** 

1. Confirm if any BE changes will be needed on the BE to expand steps (**From 5 step to 8 step process on mobile)**.

 **Note: As current functionality we respond with whatever data the claims API fetches to feed that data to the FE.**

**## Acceptance Criteria**
  

-  [ ] Confirm  and Note what BE Changes will be needed (if any) to expand Claims Steps From 5 step to 8 step process on mobile platform.
-  [ ] Supporting Tickets:  Add Additional Steps and Tickets Needed in order to complete any BE implementation needed

**Comment by jperk51** [comment]
Our backend expects there to be 8 phases and doesn't have any logic for simplifying them so we should be returning all of them as they are provided from EVSS/LH without modification other than some remapping from LH data structure into our previous structure that was based on evss. TLDR FE should have everything they need already provided by the API to show all 8 phases.
