### ISSUE TITLE
BUG - sev-3 - All - HSP + delay in onboarding = weird display on first login

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8811]
## What happened?

If you're on an HSP build, AND
You sit on the onboarding screen for ~5 or more minutes (long enough to get past the caching timer for the various API calls that have happened to this point), THEN
You navigate to the home screen - when you finally get to the home screen, [you get an incorrect 'empty' UI for a second or two before the loading screen stuff appears.](https://drive.google.com/file/d/1PzZM4LeX3G5abqTSAuv7BSphK2l4hTq7/view?usp=drive_link)

My hunch here is that we're displaying that empty state when we don't have a return yet for the `authorized-services` call (which gets called again because it's been long enough), then switching to loading when the authorized services return is back and we know what to call in the next group of APIs. So in production, this incorrect empty state could take longer than what I've been seeing in staging.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

See problem description, I spell it out up there.

Further notes: If I move quickly-but-reasonably through the screens (ex: reading onboarding) then typically I see the fully-loaded home screen with correct data when it's revealed. If I RUSH through screens, then I get[ the loading state (also expected) when I see the home screen ](https://drive.google.com/file/d/16CsdHF3k7b59DQZZVT8nM73K3gVvMbWP/view?usp=sharing)the first time.

## Desired behavior

Ideally we'd show the loading screen right away.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
@TKDickson This was most likely fixed in #8746, just want to confirm with you before I close this out

**Comment by TKDickson** [comment]
@theodur yep, can't reproduce with today's develop build. Closing as fixed.
