### ISSUE TITLE
BUG - Sev 3 - All - Payments query not dependent on authorized services API call 

### ISSUE THREAD

**Issue by theodur** [department-of-veterans-affairs/va-mobile-app#8839]
## What happened?

The `getPayments` query isn't blocked when the authorized services call returns the `paymentHistory` service as `false`. This should be accounted for in the query so the `/v0/payment-history` endpoint won't be called when the user isn't authorized for payment history. 

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Payments endpoint is blocked when user isn't authorized.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Blocked by lack of access to testing build; added blocking ticket & label.

**Comment by TKDickson** [comment]
Confirmed we do not call the API, and show appropriate error/messaging, for payment history authorizedServices false, and when payment history is in downtime via maintenance window.

**Comment by TKDickson** [comment]
No further testing needed in develop; closing
