### ISSUE TITLE
Enable sourcemaps for iOS

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#8843]
Our logs in firebase aren't very helpful, so we want to switch on sourcemaps.

**AC**

- [x] a sourcemap file is generating in the ios build

**Comment by TKDickson** [comment]
Made a develop build on demand with this change included; installed iOS, logged in, and sent a message.

**Comment by TKDickson** [comment]
@timwright12 I would close at this point, but are you keeping this open until after the sourcemap stuff is in the released app/you can check in firebase?

**Comment by timwright12** [comment]
no, it can be closed. I'll reopen it if needed
