### ISSUE TITLE
Add logic for setting the location from the provider address in the practitioners list for CC pending appointments

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#8852]
While verifying pending CC appointments it was noticed that the provider address is not coming in for CC pending appointments. After talking to Kris, logic needs to be added for setting the preferred community care provider location using the location given in the practitioners list. 

See conversation here for more details.

AC:
- Add logic to set the location for CC providers address from the practitioners list in the appointments data for appointments that are pending CC appointments.

**Comment by kpethtel** [comment]
Just to add a bit of extra context around this, it's not immediately clear how we should fix this. It's possible we can fix this by taking the address from the practitioners list (which appears to be where the web gets it) and putting it into "location". But that may cause other issues. Fixing this will probably require knowing more about how the web front end handles addresses.

**Comment by StacyB2023** [comment]
Added to appts epic

**Comment by kpethtel** [comment]
Tested by checking a proposed CC appointment, specifically appointment 7b21f45ff6f899127bf1e28fc557ed402a53a28c3e78fb084913aa1959a4cc5c. 
In the web response, it has this address information:
```
				"practitioners": [
					{
						"identifier": [
							{
								"system": "http://hl7.org/fhir/sid/us-npi",
								"value": "1619285160"
							}
						],
						"address": {
							"type": "physical",
							"line": [
								"918 DANNER AVE"
							],
							"city": "DAYTON",
							"state": "OH",
							"postalCode": "45417-3309",
							"text": "918 DANNER AVE,DAYTON,OH,45417-3309"
						}
					}
				],
```
And now in mobile it contains:
```
                "location": {
                    "id": null,
                    "name": null,
                    "address": {
                        "street": "918 DANNER AVE",
                        "city": "DAYTON",
                        "state": "OH",
                        "zipCode": "45417-3309"
                    },
                    "lat": null,
                    "long": null,
                    "phone": {
                        "areaCode": null,
                        "number": null,
                        "extension": null
                    },
                    "url": null,
                    "code": null
                },
```

**Comment by rbontrager** [comment]
Verified that I'm seeing the providers address for CC pending appointments and that the address matches the web. Approved by QA.
