### ISSUE TITLE
List view for Claims - add Step X of X (4) and "Moved to this step on [date]"

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8866]
## Description
As part of this story we want to specify within the list view for claims what step of the process the claim is in.

## Acceptance Criteria
- [ ] **Initial disability claim**
- Scenario: When disability claim = 8-step claim
- Copy:
     - Step [current step #] of 8: [Step # title]
- Copy variations:
    - Step 1 of 8: Claim received
    - Step 2 of 8: Initial review
    - Step 3 of 8: Evidence gathering
    - Step 4 of 8: Evidence review
    - Step 5 of 8: Rating
    - Step 6 of 8: Preparing decision letter
    - Step 7 of 8: Final review
    - Step 8 of 8: Claim decided
    
- [ ] **Other claim types**
- Scenario: When any other claim = 5-step claim
- Copy:
     - Step [current step #] of 5: [Step # title]
- Copy variations:
    - Step 1 of 5: Claim received
    - Step 2 of 5: Initial review
    - Step 3 of 5: Evidence gathering, review, and decision
    - Step 4 of 5: Preparation for notification
    - Step 5 of 5: Complete
   
- [ ] **All claim types**
    - Add "Moved to this step on [date]"

## Notes & Open Questions
- Will need to be added to Demo Mode and API types

- See link to [Figma](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1563-16994&t=GbeXxqLFv5xms2Ho-4)

**Comment by alexandec** [comment]
Just to note, new fields added by BE to the claims index endpoint are:

- phase
- phaseChangeDate
- documentsNeeded
- developmentLetterSent

**Comment by rbontrager** [comment]
Verified the following:
- Step [x] of [x]: [Information] and Moved to this step on [date] is now displayed for each claim in the claims history list
- Each claim phases (whether 5 or 8 step) Step [x] of [x]: [Information] is correct by going through the various claims on user +23 or changing the "phase" in Charles Proxy.  
- Verified that the Moved to this step on [date] is correct by spot checking that itmatches the "updatedAt" value in Charles. 

Note: A bug was found while verifying in develop for Appeals where the 'Moved to [date]' was not displaying.  This bug can be found [here](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9353).  All other changes are approved by QA.
