### ISSUE TITLE
List view for Claims - create conditional information pills (3)

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8874]
## Description
As part of this story we want to: create conditional information pills for Claims

## Acceptance Criteria

-  [ ] Added to feature flag
-  [ ] Create conditional information pills
     -  [ ] Yellow tag - Condition:When there are file requests, Copy: More information needed
     -  [ ] Blue tag - Condition: When decision letter is available for download, Copy: Decision letter ready
-  [ ] Update detox & E2E tests

## List view variations (Copied from [Figma](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1563-16994&t=GbeXxqLFv5xms2Ho-4))

<img width="424" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHVDQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b8b92cf05f798c8f36ad03344f8cd19d81be26e/image.png" alt="image.png" />

## Notes & Open Questions

**Comment by ala-yna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/8874?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by rbontrager** [comment]
According to this [thread](https://adhoc.slack.com/archives/C067S0FRP0C/p1723217298761879): we shouldn't be having the 'More information tag' appear when the file requests is "Automated 5103 Notice Response".  The 5103 form is our claim evaluation page and that response is just a reminder to fill it out and not an actual file request.

**Comment by rbontrager** [comment]
Verified that the 'more information needed' conditional tag is on a claim with file requests and not displayed when a claim has no file requests.  Verified that the 5103 form no longer causes the claim to have a 'more information needed' tag. Verified that the 'Decision letter ready' conditional tag is any closed claim that has a decision letter and is not displayed when a claim does not have a decision letter in the app.  Approved by QA.
