### ISSUE TITLE
Detail view for Claims - Overall/high level changes

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8887]
## Description
As part of this story we want to: start adjusting the detail screen for Claims

## Acceptance Criteria

- [ ] Update claim type header style [claim type]
- [ ] Show Need help section across both (Active and Closed) segments
- [ ] Typography aligns with with [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1586-1774&t=Kz9shxOuIFDRYddG-4)
- [ ] Need help section repeats across each segment, and aligns with Figma / [Copy doc](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=728579729#gid=728579729&range=A23)
- [ ] VQA with Lauren / Misty

## Notes & Open Questions

**Comment by ala-yna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/8887?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by rbontrager** [comment]
Per the conversation thread [here](https://adhoc.slack.com/archives/C067S0FRP0C/p1719422740781589) the work done needs to also apply to appeals.

**Comment by rbontrager** [comment]
Per the conversation thread [here](https://adhoc.slack.com/archives/C067S0FRP0C/p1719422740781589) the work done needs to also apply to appeals.

**Comment by Sparowhawk** [comment]
applied, screenshots are in that thread posted above

**Comment by rbontrager** [comment]
Verified the following:
- The header was updated to match the typography/style in figma for claims and appeals 
- The need help section appears in both active and closed claims in both the status and details segment
- The need help section appear in both active and closed appeals in both the status and issues segment
- A11y checks following the RC steps were run

Approved by QA.
