### ISSUE TITLE
Detail view for Claims - Active claims

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8889]
## Description
As part of this story we want to: make changes to the detail screen for active claims

## Acceptance Criteria

- [ ] Active Claim: Show a conditional primary action:
     - [ ] For open File Requests, show blue informational Alert with [Review file requests] primary button – **use the Design System Alert Component**. For no open file requests, show [Submit evidence] primary button (button can be shown as long as claim.attributes.open is true, see [#8864](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8864) for details).
     - [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1586-1774&t=oNi2ZnGJTD2vzqXa-4)
    - Link copy reads: `Find out why we sometimes combine claims` (see [copy doc for Large Panel copy](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=831099110#gid=831099110&range=B2) for content inside panel)

- [ ] Content aligns with [copy doc](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=728579729#gid=728579729)

- [ ] Include section: What you've claimed (bulleted list from current Details segment)
- [ ] VQA with Lauren / Misty

## Notes & Open Questions

**Comment by ala-yna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/8889?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by rbontrager** [comment]
@Sparowhawk A couple issues found. 

1. According to this [thread](https://adhoc.slack.com/archives/C067S0FRP0C/p1723217298761879): we shouldn't be having the 'You have [x] file requests appear' when the file requests is "Automated 5103 Notice Response".  The 5103 form is our claim evaluation page and that response is just a reminder to fill it out and not an actual file request.
2. When there is 'None noted' in the What you claimed section there is too much spacing happening after 'None noted'.

**Comment by rbontrager** [comment]
Verified the following:
- If the claim has file requests than a yellow alert box is displayed stating 'You have [x] file request' with a 'Review file requests button'
   - Verified that their even though there were no changes to how file requests work in the code that the 'You have [x] file requests decreases by 1 if you submit file a file request.  Also verified that the alert box disappears once you ask for a claim evaluation or if you don't have any file requests left
- That the 'Find out why we sometimes combine claims' link is displayed on all active claims
- That there is a 'What you've claimed' section on all active claims and that it matches the previous list given in the active claims details
   - Verified that none noted no longer has too much spacing after the text
- That claims not behind the feature flag still work and look as intended
- No a11y issues were found with the smoke tests from testRail

Note: Submit evidence has been taken out of this release.  Everything else was approved by QA.
