### ISSUE TITLE
Detail view for Claims - Closed claims

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#8890]
## Description
As part of this story we want to: make changes to the detail screen for closed claims

## Acceptance Criteria

- [ ] Closed Claim: Show blue informational Alert (see copy doc for content inside alert)
     - [ ] For digital decision letter, show Alert with primary button
     - [ ] For mailed-only decision letter, show slim Alert
   - [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1622-3594&t=oNi2ZnGJTD2vzqXa-4)
- [ ] Closed Claim: Show link to Large Panel: 

  - Link copy reads: `Learn what to do if you disagree with our decision` (see [copy doc for Large Panel copy](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=831099110#gid=831099110&range=C2) for content inside panel)

- [ ] Ensure style alignment with [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1622-3594&t=oNi2ZnGJTD2vzqXa-4)
- [ ] VQA with Lauren / Misty

## Notes & Open Questions

**Comment by rbontrager** [comment]
@Sparowhawk Detox is broken for the Claims e2e (run can be found [here](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10012418184/job/27677946707)).

**Comment by Sparowhawk** [comment]
@rbontrager Detox fixed https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10014139392/job/27683259510

**Comment by rbontrager** [comment]
@Sparowhawk It's fixed for iOS but is still failing for Android.  Looking at the failure it looks like you need to add atIndex(0) to the following lines in the 'verify what should I do if disagreement information'. Its due to a detox quirk with Android.

```
await element(by.id('Learn what to do if you disagree with our decision')).atIndex(0).tap()
await expect(element(by.text('Learn what to do if you disagree with our decision')).atIndex(0)).toExist()
```

You will also need to add 'await element(by.id(ClaimsE2eIdConstants.CLAIMS_DETAILS_SCREEN_ID)).scrollTo('top') to the first line in the 'verify details tab infomation' test because for android it scrolls down in the test before.

**Comment by Sparowhawk** [comment]
@rbontrager Thank you for that bit of help. i made those changes

**Comment by rbontrager** [comment]
Verified that if a decision letter is available an alert appears (matching the figma design) that allows the user to click on it to view their decision letter.  Verified that if a decision letter is not available an alert appears without a button stating the decision letter was mailed.  Verified that there is a 'Learn what to do if you disagree with our decision' link to a large panel for closed claims.  Verified that the smoke a11y tests passed as well as the detox tests.  Approved by QA.
