### ISSUE TITLE
Ensure maintenance windows controller respects overlapping windows 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8892]
Seems like we might not be handling overlapping windows correctly. There were two windows from June 22nd - June 23rd that overlapped by an hour and the logs indicate we didn't respect the later window.

**Comment by aherzberg** [comment]
It looks like this was another case some EVSS windows not actually bringing down the server so when the older versions of the app that don't respect windows hit server during the first window, there was drastically lower traffic but that traffic was returning 200s. When the second window came though, the servers actually went down and those older app version calls started to fail. See the following screenshot of the disability rating endpoint. <img width="1973" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDZ3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1debf6db64fccfae569af59f8d04cd248ab20e93/Screenshot%202024-07-03%20at%209.46.44%E2%80%AFAM.png" alt="Screenshot 2024-07-03 at 9.46.44 AM.png" /> (the highlighted portion is the start of the second window).
If the overlapping of the windows was causing all app versions to not respect the second window, then we'd see traffic return to around the amount we saw before the beginning of the first window. We instead see the same amount of traffic but that traffic is now failing. 

I've confirmed this in specs (didn't push a new spec, just in my local env) as well that an overlapping window does not cause the second one to disappear.

**Comment by aherzberg** [comment]
<img width="1876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW13QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51b45ca3e2067f403af8c7cfdea379e76e36ec4e/Screenshot%202024-07-03%20at%209.58.34%E2%80%AFAM.png" alt="Screenshot 2024-07-03 at 9.58.34 AM.png" />
To compare, this is traffic from the previous saturday at the same time
