### ISSUE TITLE
Update Accordion Collapsible component used in the Step timeline

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8898]
### Description
We currently use the Accordion Collapsible component within the Claims Detail screens to indicate a timeline of steps that indicate the phases that make up a given Claim. Depending on the Claim type, either 5 or 8 steps may display. There is existing logic that has become obsolete as a result of the Mobile Claims Phase Expansion, so this ticket will reflect how we'll display it in the UI.

As part of this story, we want to: 

- Update how information is visually presented within the Accordion Collapsible component.
- Affect all areas that use this component to indicate multiple steps, or phases of a Claim.

### ACs

- [ ] Remove numbering/disabled logic
- [ ] All steps: apply Header/Description type styles (Step name / Step title / Step details)
- [ ] Completed step: Use a check mark icon to indicate completion 
- [ ] Current step: Apply a label tag [Current step]
- [ ] Current step: Apply focus and auto-scroll to current step
- [ ] Current step: Expand the row, while all others are collapsed
- [ ] VQA with Lauren / Misty

### Accessibility
- Screenreader annotations are noted within the Figma section (Text is to the left, in white. Note: / indicates a swipe)

#### Resources

Link to: 
- [Figma Mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1550-516&t=nw289OgI8n3F7j8h-4)
- [Copy doc](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=728579729#gid=728579729)
- [5 steps in-process mockup](<img width="186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6663b677c17f8c914ee99dca3ce89eb621196d24/image.png" alt="image.png" />
)
- [8 step in-process mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1586-3783&t=nw289OgI8n3F7j8h-4)

**Comment by alexandec** [comment]
@wavelaurenrussell we are also removing the claim file upload button from this location, correct?

**Comment by wavelaurenrussell** [comment]
@alexandec Correct. New home will be within the Alert, displayed when applicable at the top of the screen.

**Comment by alexandec** [comment]
Confirmed with Lauren that autoscroll to current step should happen in all cases except these two:

- Current step is step 1 OR
- All steps are completed

**Comment by alexandec** [comment]
BE has [added the claimTypeCode](https://adhoc.slack.com/archives/C0206QFMXFU/p1721319284555779?thread_ts=1721047189.066829&cid=C0206QFMXFU) field we need for this ticket. They're now passing it through from upstream services.

**Comment by alexandec** [comment]
Notes for QA:

- I updated demo mode so the 4th claim shown has a claimTypeCode that makes it use the 8 step display. The other claims are still 5 steps.
- I updated the E2E tests so they continue to run correctly. I also expanded them a little, but they may need further additions for completeness when testing 8 step claims.
- The following values for the claimTypeCode field indicate disability compensation claims which show all 8 steps:

```
  '010INITMORE8',
  '010LCMPPIDES',
  '010LCOMP',
  '010LCOMPBDD',
  '010LCOMPD2D',
  '010LCOMPIDES',
  '010NADIDES8',
  '020BDDNO',
  '020CLMINC',
  '020EPDSUPP',
  '020IDESRRNAD',
  '020NADIDESNO',
  '020NEW',
  '020NEWIDES',
  '020NEWPMC',
  '020NHPNH10',
  '020NI',
  '020PNI',
  '020PREDSUPP',
  '020RRNADIDES',
  '020RSCDTH',
  '020RSCDTHPMC',
  '020SD2D',
  '020SMB',
  '020SUPP',
  '110INITLESS8',
  '110LCMP7IDES',
  '110LCOMP7',
  '110LCOMP7BDD',
  '110LCOMPD2D',
  '110LCOMPIDES',
  '110NADIDES7',
```

**Comment by rbontrager** [comment]
@alexandec Found just a couple small issues:
- The voiceOver logic is not following the logic in the figma file above.  Instead of having "Step [X] [Title]" then swiping to hear "Current Step. Step <x through y> complete. Expanded." you hear all of it at once.
- The icons are increasing in size as the text increases instead of staying at the max icon size.
- If you are using a wireless keyboard you can no longer navigate to the steps expanded description.  This used to work.
- It looks like the claims web team may have added a couple claim disability compensation types since this ticket was made ('020RCOMP', '020RI', '020RN'). You might want to double check that we don't need to include them as well.

**Comment by alexandec** [comment]
@rbontrager status update on your points above:

> The voiceOver logic is not following the logic in the figma file above. Instead of having "Step [X] [Title]" then swiping to hear "Current Step. Step complete. Expanded." you hear all of it at once.

I'm checking with Lauren on this. I'm not sure where the extra swipe would go for steps that aren't the current step. Without the "Current step" label tag, it seems like a swipe could only move focus to the next step.

> The icons are increasing in size as the text increases instead of staying at the max icon size.

I made a change to prevent scaling of the checkmark icons.

> If you are using a wireless keyboard you can no longer navigate to the steps expanded description. This used to work.

Sounds like a larger iOS 17 or 17.5 issue prevents keyboard navigation in various parts of the app. If there's anything I can do in this PR though, lmk.

> It looks like the claims web team may have added a couple claim disability compensation types since this ticket was made ('020RCOMP', '020RI', '020RN'). You might want to double check that we don't need to include them as well.

I checked the latest vets-website code, and you're correct that the `'020RCOMP', '020RI', '020RN'` codes were added. I've added them to our list as well. Thanks for the heads up, I hadn't been informed of that change.

**Comment by alexandec** [comment]
@rbontrager Update on this one:

> The voiceOver logic is not following the logic in the figma file above. Instead of having "Step [X] [Title]" then swiping to hear "Current Step. Step complete. Expanded." you hear all of it at once.

I [chatted with Lauren on Slack](https://adhoc.slack.com/archives/C067S0FRP0C/p1722971307309499) and she's good with the single announcement instead of splitting it into two pieces. So at this point everything you mention should be addressed.

**Comment by rbontrager** [comment]
Verified the following for both non disability (5 step) and disability (8 step) claims

- Verified that all steps follow the step name / step title / step details logic
For each step of the 5 step/8 step process I verified the following:
	- That all completed steps use a check mark icon to indicate completion and that there were no completed steps after the current phase
		- Verified that the icon does not grow larger when text resizing occurs
	- That the current step had a current step label tag
	- That the current step was focused, expanded, and auto-scrolled too.
		- Verified that all other steps weren't expanded
	- That the content is correct for each step
- Verified that each of the new 8 step claim code types (given above) produced an 8 step claim through a combination of Therese making them in VBMS and Charles Proxy
- Verified that if a code wasn't one of the new claim code types that a 5 step claim was displayed
- Verified the a11y cases using our smoke tested a11y test cases
	- Potential bug where we don't allow the user to keyboard over a claim decision.  Because of bug (found [here](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9288)) with iOS version 17.5 where the user can't keyboard past the header this can't be tested.
- Did a spot check of the claims between the web and mobile to make sure that no differences were displayed
- Verified that our current claim still works as intended when the feature flag is off
- Ran the relevant test rail cases from [here](https://dsvavsp.testrail.io/index.php?/tests/view/1255599&group_by=cases:section_id&group_order=asc&group_id=20702)
