### ISSUE TITLE
Android - Upgrade SDK before 8/31/24 - Backward incompatible change

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8914]
**Description**:
As VAHB, I want to make updates in order to not have SDK issues with Android App Store, so that VAHB is compatible with Android 14 (targetSDKVersion 34) and enable VAHB to release future versions. 

**Notes**: 
- [Ad Hoc, LLC Mail - Upgrade VA_ Health and Benefits to a newer com.google.android.play_core SDK version.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7fbd271e798a37f3bd222ca83c7366b92452828/Ad%20Hoc%2C%20LLC%20Mail%20-%20Upgrade%20VA_%20Health%20and%20Benefits%20to%20a%20newer%20com.google.android.play_core%20SDK%20version.pdf)
- [Slack Thread](https://adhoc.slack.com/archives/CU2Q76NPR/p1718728947716559)
- Android 14 introduces a backwards-incompatible change to improve user security 

**ACs:**

- [x] Research Android 14 information 
- [x] Determine backwards incompatible change issues
- [x] Ideas on how to handle backwards incompatible changes (communications, etc) 
- [ ] Update SDK before 8/31
- [x] Update [Compatibility document ](https://adhoc.slack.com/archives/CU2Q76NPR/p1718728947716559)if needed

**Comment by bischoffa** [comment]
@timwright12 checking in to see what you have found so far. 

Is this something that Charnelle can do?

**Comment by timwright12** [comment]
I haven't had time to look into this yet, if @IsraelleHub does, she can dig in

**Comment by bischoffa** [comment]
Tim to try to look into it this tomorrow. May pull in Charnelle after this.

**Comment by bischoffa** [comment]
Converting this issue into an Epic so it can be part of the Q3 planning process. Not sure if it needs to be an epic but needed a way to make sure its called out when discussing work at the epic level with POs, Leads and Team.

**Comment by timwright12** [comment]
The root of this issue is that the google play core dependency we use was deprecated in favor of 4 separate dependencies inside `VAMobile/android/app/build.gradle`

I opened [a pull request to remove the old dependencies and replace with the new ones](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9141/files). 

We also need to confirm that there are no sub-dependencies that use the old version of play core. [My efforts ](https://stackoverflow.com/questions/78640445/sdk-issues-com-google-android-playcore-has-added-this-note-for-core1-9-0)running the report to test that have so far failed, so I may ping others on the team to try and pull that down.

For now, the PR I have will run through an Android on demand build to make sure it still works and I'll do some spot checking, but should also get someone from QA to test.

**Comment by bischoffa** [comment]
Assigning to @DJUltraTom given his floater position in QA for Q2. Tom thoughts on reviewing this?   
  
@timwright12 with your review do you feel we will need to communicate backwards compatibility issues with Veterans? If not sounds like we do not need to pull in a Flagship team to handle this part.

**Comment by timwright12** [comment]
@bischoffa I don't think there's really a way to communicate backwards compatibility issues. Most users auto-update and those who don't have encouraged update, so feels like we should be good.

@DJUltraTom we just need a once-over for the app to make sure misc. things are working. I poked at it a bit and it (superficially) seemed fine.

**Comment by timwright12** [comment]
Attaching the dependency map to this ticket for good measure.

[dependencies.txt](https://github.com/user-attachments/files/16316113/dependencies.txt)

**Comment by DJUltraTom** [comment]
@timwright12 do you think this dependency update warrants more than a high level RC/smoke test pass?

**Comment by timwright12** [comment]
@DJUltraTom no, I think that should suffice; we just want to make sure general features work. I wouldn't worry about edge case

**Comment by bischoffa** [comment]
@DJUltraTom @TKDickson given this any thing we need to change or do different from the OS compatibility standards created in Q2?

**Comment by bischoffa** [comment]
Given comments above Flagship team will not be asked to work on communication for backwards incompatibility issues. Once high level RC / smoke test & SDK update is completed this can be closed out. Moving this from an epic back to an issue.

**Comment by bischoffa** [comment]
@DJUltraTom please add your size estimate to this ticket

**Comment by timwright12** [comment]
@DJUltraTom Theo brought up a good point in the PR, can you focus a test around in-app reviews for Android?

> You have to be logged in to the Google Play Store on the device, and then you need to do a triggering event in the app at least 7 times to get past the review count threshold. The easiest way is probably to navigate to and back from the Personal information screen 7 times

**Comment by DJUltraTom** [comment]
added QA estimate (3, which feels generous)

**Comment by bischoffa** [comment]
@timwright12 when do you prefer to update the SDK?

**Comment by timwright12** [comment]
@bischoffa as soon as @DJUltraTom signs off, we'll merge. The sooner the better just in case what we're doing here isn't enough and alerts continue to come in

**Comment by bischoffa** [comment]
Sounds good. @DJUltraTom can we proceed in QA testing on this ticket?

**Comment by DJUltraTom** [comment]
detox test pass here:
https://dsvavsp.testrail.io/index.php?/runs/view/5723&group_by=cases:section_id&group_order=asc

Manual test commencing now

**Comment by timwright12** [comment]
@DJUltraTom Did the Android tests run as well? I only see iOS, but I'm not super familiar with the TestRail UI

**Comment by DJUltraTom** [comment]
completed a high level smoke check on android using the RC test run, no new issues noticed.
https://dsvavsp.testrail.io/index.php?/runs/view/5770&group_by=cases:section_id&group_order=asc Manual test run completed.
https://dsvavsp.testrail.io/index.php?/runs/view/5723&group_by=cases:section_id&group_order=asc Detox test run completed.

@timwright12  I ran the android only e2e test, not sure why they are showing iOS, (though that is what I am seeing in github as well)

**Comment by timwright12** [comment]
@bischoffa looks like this missed the v2.34.0 release cut. I think we should add it in. Thoughts?

**Comment by bischoffa** [comment]
@timwright12 what would that entail? How would that impact RC testing for 2.34?

**Comment by timwright12** [comment]
@bischoffa at this point we could cut a new release off develop since not much else has gone in. I'll need to sync with @narin though
