### ISSUE TITLE
Creation of new detox tests for HSP - personalization

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8915]
This ticket is for creating new detox tests which should cover:
* Deeplink buttons on home screen
* Disability & payment component on home screen
* New announcements banner on home screen
* Buttons-with-info on Benefits (Claims) and Health (Appointments, Rx, Messages) screens

_This ticket is not for confirming existing tests still work; that's #8102 and #8895.
#8103 is Space Force support for new home screen._

If I need to further split out this ticket for PRs that make sense/work that's right-sized, I will.

**My notes from earlier ticket about what I might cover in these tests**
Deeplink buttons:

- Buttons exist
- Tapping buttons deep links to the correct screen --> probably split out into own thing/should be covered by Nav script?

DR/$
- Exist

Announcement banner
- Exists
- When tapped, brought to correct website (screenshot?)

Category screens

- Information exists (for ones where we've mocked)
- do NOT need to add explicit "go to correct place when tapped" because that's explicitly tested as part of getting to the features themselves for testing

**Comment by theodur** [comment]
I opened a PR for the Space Force support in the Military Information E2E test. Doesn't look like there are any others from the list I can work on that don't touch the home screen. Whenever your updates to the Home & Health related E2E tests are finished and merged, you can split some more tickets out and I'll pick them up

**Comment by TKDickson** [comment]
Not currently working on (added blocked-qa label) due to ticket limit & overall prioritzation.

**Comment by TKDickson** [comment]
OK picking this back up again, removing blocked label.

**Comment by bischoffa** [comment]
@TKDickson can you add the epic to this ticket?

**Comment by TKDickson** [comment]
@bischoffa done, thanks for the catch.

**Comment by TKDickson** [comment]
Merged to feature branch; closing.
