### ISSUE TITLE
Home Screen Baseline Metric 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8916]
Objective: Create a baseline of metrics for Pre Home-Screen Rollout. Ensure queries and documentation is correct and fit for purpose. 

- Appointments 
- Claims View Rate
- Retention 
- Overall Home Screen Load Speed and load speed by feature
- Unread Message Rate 
- Prescription refill rate 
- Home Screen Modules Clicks 
- Personalized home screen adoption

 
Acceptance Criteria: 30 day, 60 day and 90 day review of the impact of Home-Screen Rollout, ensuring queries are reviewed to ensure accuracy. Share findings with the team for further deliberation and inputs.

**Comment by OVezeamama** [comment]
[https://docs.google.com/spreadsheets/d/10p5qzDt0F6LAwzt7ptYdKLDfi3kgfNudvaX21kaOqcc/edit?gid=0#gid=0](url)

**Comment by OVezeamama** [comment]
Sprint Demo presentation 08/13/24
