### ISSUE TITLE
Determine whether to Create Custom Event for NotEnrolledSM

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8917]
Objective: Determine whether to create a custom event for tracking users who are opted out of secureMessaging as an authorized service (and try to get there)

1. Determine the importance of the request
2. Understand whether there is another way to get this data
3. If team decides to go ahead ensure metrics are attached to custom event. 

Request was made by Janie Tankard-Carnock. 

vama_notEnrolledSM for the analytic name

**Comment by timwright12** [comment]
@ajsarkar28 are we using the FE-Needs-Review label for issues now? I thought they were just for PRs

**Comment by ajsarkar28** [comment]
@timwright12 
I must have accidentally added it since I'm not sure what FE-Needs-Review for. Removing it

**Comment by OVezeamama** [comment]
[](https://dsva.slack.com/archives/C018V2JCWRJ/p1717774537900129)

**Comment by ala-yna** [comment]
Since this is such a small ask, I created a ticket to implement the new analytic https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9683
