### ISSUE TITLE
CU - Document Detox Best Practices

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#8922]
## Proposed Change

FE will begin requiring detox edits in their pull requests and before doing so we'd like some guidance on some best practices writing detox tests.

Please include the best practices on the website QA documentation and we will link to it in FE docs.

## Why Should We Prioritize?

So we can move this workload from QA to FE engineers.

## Coding Time Estimation

3?

## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by bischoffa** [comment]
Added the next sprint as this wasn't closed out.
