### ISSUE TITLE
Reproduce Biometric Login Errors 

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#8924]
AC:

- [ ] Use Charles to catch one of the biometric codes in this [google sheet](https://docs.google.com/spreadsheets/d/1iBpRH3oDQVkmhd_tEp3Hl5_Hdo_bQC7D_oM8Uqq-_gw/edit?gid=87573295#gid=87573295), which contains login errors 
- [ ] Document steps to reproduce and relevant Charles responses in the ticket

**Comment by TKDickson** [comment]
@ajsarkar28 I confirmed that Charles Proxy doesn't catch biometric login errors that happen within the app (no API calls are happening -- for instance in iOS it prompts for Face, you display the incorrect face, and then it makes the user essentially opt-out from the native prompt (screenshot below). No API calls recorded.

Failing biometrics within the webview (the only place that I can think of where I'm prompted for biometrics during login is if I am trying to use a saved UN/PW, but even that 1) didn't log API calls and 2) didn't result in an error in the webview (just me being unable to use the saved info) also isn't sending anything back from Charles that's useful.

The only other case I can think of that QA could attempt is to turn on biometrics, be in a session, wait for 45 days, and see if failing biometrics when attempting to preserve an existing session/refresh a token. But given that I didn't get anything useful from the more easily accessible workflows, I give this a :shrug: probably not worth waiting for.

I'm not sure what the next steps would be in the 'reduce login dropoffs' work, but unfortunately I don't think this ticket will turn up any leads. I think we'll just have to go with what Identity sent over, and probably working with them to attempt to better determine under what circumstances they're sending XYZ error messages back over to us.

Face ID "not the right face" eventual 'opt-out' prompt. After which point the user _has_ to log in with UN/PW during that session, or could reattempt biometrics login from scratch if they forceclose and reopen the VAHB app.
<img width="379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlVTQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b02104bfa5530e825d19c006b26f657514784245/image.png" alt="image.png" />
