### ISSUE TITLE
Claims Detail (Closed): Updates to the Status Segment

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8934]
### Description
This ticket addresses updates to the design and content of the **Status Segment for Closed claims**. This includes design updates, and content placement. 

As part of this story, we want to:

- Create and use predictable UI patterns to display information for both Open and Closed claims.
- Add or reorder content to match new UI and copy doc 

### ACs

- [ ] Create a card with associated fields; display across Closed Claim Detail screens
- [ ] Align content and design with [copy doc](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=1469156580#gid=1469156580) and [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1587-2623&t=hmtlgXbIWLyCFFic-4)
- [ ] VQA Lauren / Misty

#### Resources

- [Copy doc](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=1469156580#gid=1469156580)
- [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1587-2623&t=hmtlgXbIWLyCFFic-4)

**Comment by rbontrager** [comment]
Verified that the closed claims detail screen matches the figma design referenced above.  Approved by QA.
