### ISSUE TITLE
Claim Detail (Active): Apply New Step Timeline template to all multi-step claim/appeal types

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#8941]
### Description
We want to update all multi-step detail screens so that they match the 8-step Disability Compensation details layout. These updates will ensure consistent design/accessibility, and leverage any additional updates made for code quality.

As part of this story, we want to:

- Apply the updates and associated logic to all other claims with a multi-step process.

### ACs

- [ ] Apply the updated Accordion Collapsible component to the step timeline ([8898](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8898))
- [ ] Align design/interaction for multi-step claims with [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1586-4063&t=hmtlgXbIWLyCFFic-4)
- [ ] VQA with Lauren

#### Resources

- [Figma mockup](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1586-4063&t=hmtlgXbIWLyCFFic-4)

**Comment by rbontrager** [comment]
Verified the following for both non disability (5 step) and disability (8 step) claims

- Verified that all steps follow the step name / step title / step details logic
For each step of the 5 step/8 step process I verified the following:
	- That all completed steps use a check mark icon to indicate completion and that there were no completed steps after the current phase
		- Verified that the icon does not grow larger when text resizing occurs
	- That the current step had a current step label tag
	- That the current step was focused, expanded, and auto-scrolled too.
		- Verified that all other steps weren't expanded
	- That the content is correct for each step
- Verified that each of the new 8 step claim code types (given above) produced an 8 step claim through a combination of Therese making them in VBMS and Charles Proxy
- Verified that if a code wasn't one of the new claim code types that a 5 step claim was displayed
- Verified the a11y cases using our smoke tested a11y test cases
	- Potential bug where we don't allow the user to keyboard over a claim decision.  Because of bug (found [here](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9288)) with iOS version 17.5 where the user can't keyboard past the header this can't be tested.
- Did a spot check of the claims between the web and mobile to make sure that no differences were displayed
- Verified that our current claim still works as intended when the feature flag is off
- Ran the relevant test rail cases from [here](https://dsvavsp.testrail.io/index.php?/tests/view/1255599&group_by=cases:section_id&group_order=asc&group_id=20702)
