### ISSUE TITLE
BUG - sev-3 - iOS - Name and branch icon go off Veteran Status card screen at sufficiently large font size

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8944]
## What happened?

Something appears to have gone awry with the left margin on the Veteran Status Card screen, on iOS devices with sufficiently increased font size (this isn't anywhere near the largest-possible text resolution):
<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHViQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57e0b4cc2164a4b67b568035ef6185491cae85d7/image.png" alt="image.png" />
<img width="443" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHliQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d1d85876c550e099b988ae71455ed58b5166005/image.png" alt="image.png" />

## Specs:

- Device:
- OS: iOS phone (mine's an iPhone 12)
- User Account:
- Accessibility State: increased font size

## Steps to Reproduce

Increase font size on device (settings > display and brightness > text size)
     if needed on your specific device, turn on accessibility sizes (settings > accessibility > display & text size > larger text)
Log into app as judy.morrison (or demo mode) > scroll down and tap on the veteran status component ([army branch] Proof of veteran status >")

## Desired behavior

All icons and text should stay onscreen without cutoff

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Found on HSP branch, and also saw in develop

**Comment by timwright12** [comment]
@TKDickson can you add steps to reproduce?

**Comment by TKDickson** [comment]
@timwright12 I jotted this down quickly during HSP work so I could keep moving on that, and was planning on adding them during bug scrub/before I drop this into the ready to work column. If you need them sooner than that, just let me know!

**Comment by TKDickson** [comment]
@theodur is going to (because its quick and easy and related) limit the max size of the branch of service icon inside the VSC card, like we do on the component on home and profile screens, which will help the UI of that screen with increased font sizes significantly.

**Comment by TKDickson** [comment]
Noticed the #9054 problem on veteran status card, so updated that bug ticket.

Otherwise, the functionality for this fix (no text going out of bounds, and the seal icon not resizing) is in and working as expected. Approved to merge.

**Comment by TKDickson** [comment]
Does not require further testing in develop; closing
