### ISSUE TITLE
Qart Onboarding External Doc Review - TG

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8950]
**Description:** 
I would like QA team to review the WIP External Onboarding Document so that feedback, opinions, and changes can be gathered and considered to make the final iteration. 

**Notes:**

- Focus more on content and topics 
- Once all of that is gathered then Adam will work on using consistent language throughout the document 
- Timebox to 2 points - if you need more let Adam know 

**ACs:**

- [ ] [ Review external onboarding doc ](https://docs.google.com/document/d/1KWoGh1R0XOdnOObWLs6JtyoRrSPmmHnVLLFBp-7B4DI/edit)
- [ ] Edits, opinions can be added to the documents by inserting a comment or note

**Comment by bischoffa** [comment]
Thanks Tom for already getting a head start on this. Putting this ticket out there to finish up the review on the rest of the doc.

**Comment by DJUltraTom** [comment]
updated with more questions/comments. feel like it is at a good place to close this ticket
