### ISSUE TITLE
Qart Onboarding External Doc Review - TD

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8952]
**Description:** 
I would like QA team to review the WIP External Onboarding Document so that feedback, opinions, and changes can be gathered and considered to make the final iteration. 

**Notes:**

- Focus more on content and topics 
- Once all of that is gathered then Adam will work on using consistent language throughout the document 
- Timebox to 2 points - if you need more let Adam know 

**ACs:**

- [x] [ Review external onboarding doc ](https://docs.google.com/document/d/1KWoGh1R0XOdnOObWLs6JtyoRrSPmmHnVLLFBp-7B4DI/edit)
- [x] Edits, opinions can be added to the documents by inserting a comment or note

**Comment by TKDickson** [comment]
Added a few comments, and DM'd a question about fundamental approach. Pausing further commenting until I hear back.

**Comment by TKDickson** [comment]
Finished my review; closing.
