### ISSUE TITLE
Add pagination links to folder and message index endpoint

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#8958]
Platform Reliability Team updated some of our older endpoints do use a json api serializer and added the proper pagination links but didn't add them to the serializer to avoid changing our schema. JSON API spec does require these links so since they are there, we should add them to the serializer and update our docs. see comment here: https://github.com/department-of-veterans-affairs/vets-api/pull/17260/files#r1658962651. 

relevant PRs: https://github.com/department-of-veterans-affairs/vets-api/pull/17280
https://github.com/department-of-veterans-affairs/vets-api/pull/17260

**Comment by Tonksthebear** [comment]
Closing as it's actually valid the way it is: https://jsonapi.org/format/#document-links
