### ISSUE TITLE
QA Release Candidate Sign Off

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#8973]
## Update the Release Sign Off ticket with the following:
- [x] Check the little "QA Sign off" checkbox towards the top of the Sign off ticket

In the Comments add:
- [x] Note stating if QA "approves/does not approve" of the release candidate.
- [x] If new defects were found during the test run, include a link to the defect ticket, severity and short description
- [x] Link to completed/closed Testrail run.
- [x] Screenshot of completed "pie chart" view of the test run

## Sign Off Checklist:
- [x] Testrail test run has been completed and closed
- [x] New defects have been logged
- [x] Release Sign off ticket has been updated
- [x] Verify RC test run is under the correct sprint milestone (before closing)

**Comment by DJUltraTom** [comment]
Test rail run: https://dsvavsp.testrail.io/index.php?/runs/view/5679&group_by=cases:section_id&group_order=asc

**Comment by DJUltraTom** [comment]
test rail run completed: https://dsvavsp.testrail.io/index.php?/runs/view/5679&group_by=cases:section_id&group_order=asc

**Comment by DJUltraTom** [comment]
completed RC testing and updated the Release ticket. closing this ticket
