### ISSUE TITLE
Log vet status ICNs using PII logger

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#8984]
In order to confirm some info around vet status we need to log the ICNs of users who have any Z `honorable_service_indicator` in their military history. Since ICN is considered PII you'll need to use the special PII logger that's built into vets-api.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by jperk51** [comment]
Side note: If using the PII logger is annoying and you think it should have it's own write up on our doc site feel free to make a ticket to get it added.

**Comment by aherzberg** [comment]
continuing here: https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9036
