### ISSUE TITLE
BUG - All - Confusing display of special characters in sent messages (perceived as incorrect character insertion)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9004]
## Summary of the bug 
General overview of what happened and where it happened. 
Email in the VA Flagship Mobile app inbox:

> App has an issue of inserting numbers and symbols in a message I never put there while typing but show up after I hit send. For example on the app the word don't looks okay but after I hit send the message reflects the following after I send it.
> 
 `don&#39;t`

## Steps to Reproduce the Bug 
Step by step instructions on how to reproduce. Be as specific as possible. 
1. Login to a user with messages (+226) and reply to a message with the apostrophe character.  
2. Reopen the message and view the messages.  Notice it comes in a don&#39;t. 

## Resulting behavior
What is the current behavior / experience? 

## Expected behavior
What did you expect to happen? 

## System Information:
- Apple/Android/Other:
- Mobile Device:
- Operating System:
- App Version: 
- User Account:
- Accessibility State:

## Screen shot, recording or additional information
Add any screen shots, video, gifs, json etc that will help the engineers track down the issue. Do not include any personally identifiable information for any real person, including screenshots.

**Comment by rbontrager** [comment]
Sending this back to in progress.  Looks like the fix wasn't applied to collapsible threads (only expanded).  Can also confirm it looks correct on any of the review message screens.

**Comment by rbontrager** [comment]
Sending this back to in progress.  Looks like the fix wasn't applied to collapsible threads (only expanded).  Can also confirm it looks correct on any of the review message screens.

**Comment by rbontrager** [comment]
Verified that apostrophes come in as "'" on sent messages, drafts, collapsed/expanded threads, and new messages.  Approved by QA.
