### ISSUE TITLE
Design System QA Assessment Writeup

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9026]
**Description:** 
As VAHB Qart, I want to a write up on findings and recommendations on how QA should work with Design Systems in the future. 

**Notes:** 

- Experiment started May 8th to see if QA would benefit DS 
- QA uncertain if it makes sense to get involved in testing work that is not being implemented as it will be tested when the work gets prioritized by flagship
- DS is not using QA tools or system that are regularly used for validating work 
- Is the time / effort spent on DS work the benefit
- Can we educate DS on ways to better test or do validation if they were to own it 

**ACs:** 

- [ ] Document experience (how have you worked with them, learnings, challenges, time spent vs value) 
- [ ] Provide recommendation on how QA should work with DS moving forward

**Comment by DJUltraTom** [comment]
https://docs.google.com/document/d/1vvxYdvtjFsB_AEwxA8eQExs4e7Z8Urh1aRdylbhyp84/edit?usp=sharing
Started on write up, available at the above link.

**Comment by DJUltraTom** [comment]
concluded the write up.
closing this ticket.

**Comment by bischoffa** [comment]
@DJUltraTom I requested access to the doc you wrote up. Not sure what drive it is in but would recommend putting it in the QA drive.
