### ISSUE TITLE
QA - Tech Debt and Bug Maintenance Q3

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9029]
## Purpose of this feature:
- For Bug tickets and maintenance tasks
- Only bug tickets that have been scrubbed (reviewed by QA indicating they are ready to be reviewed by engineering)
- Prevent a large culmination of tech debt backlog
- Continuation of [8305 ](https://github.com/orgs/department-of-veterans-affairs/projects/823/views/13?filterQuery=epic%3A+Qart&pane=issue&itemId=58587074)

# Project Status Overview

### Project Objective:

Work and effort for Quality Assurance and Release Management (Qart) Team to manage team specific bugs, maintenance tasks and technical debt in order to prevent a culmination of technical / coding debt. 

Items may include:
- Qart specific bugs
- Testing Automation / Detox fixes and enhancements 
- Manual testing fixes and enhancements 
- Creating new or updating Qart specific documentation 
- Qart team knowledge / documentation / inventoring
- Preparing for rotation of roles in Q4
- Defining new Step Milestones or artifacts 

 

### Stakeholder Updates

<details>

|Date | Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|8/7/24| Green | Team preparing for Q4 rotation by documenting their learnings from their current team assignments for 2024. Updated Charles Proxy documentation. Completed RC testing for 2.34.0. Working on overnight detox test failures and trying to implement github actions to automatically create a ticket when nightly builds fail. Updated QA sign off template to include A11y checklist. | None |
|8/19/24| Green | Added a toggle to be able to turn off in-app reviews in detox (will lower false fails, and have a ticket this sprint to remove the time-adding workarounds in the scripts). Rachael found and fixed issues with the overnight detox scripts. Reorganized the QART portion of the doc site (moved accessibility, added sub-categories within QA). QA team writing a ticket (for late September) with a personal checklist of pre-rotation tasks. Starting QART-specific postmortems for the recent sev-1 and sev-2 issues.  | none | 
|9/4/24| |
|9/18/24| Green | Updated feature signoff checklist ticket template, finished removing in-app review popup workaround from detox scripts, automated ticket creation when the overnight script fails, as well as regular script maintenance.  | none | 
|10/1/24| Green | Progress on replacing text with ids in detox automation scripts. Created documentation for updating the doc site via codespaces, as well as documenting information provided to Experience teams that wasn't previously on the doc site. | none | 

</details>

# Detailed Project Scope 

### OKRs

<details>

- Stability 
    - Reduce QA, DevOps, and Accessibility bugs by 25%
    - Zero failed RC testing due to bugs
    - Zero app store rejections  

</details>

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.) Team will use their full capacity allocation for work on bugs and tech debt 
 
 2.) Work in this epic is purely for QA, anything tied to mobile app features (Global or H&B) will be part of their unique bug epics 
 
 3.) QA will be able to spend their allotted capacity on this epic vs being taken up by Flagship App / Platform teams which has happened in past quarters 

4.) App store may reject a submission but they inform the team on why and we have the ability to fix it. It should only be seen as negative if they reject it and we miss a release. 

5.) RC testing may uncover a bug or be told that a known bug is acceptable by PM or POs. When this happens RC testing will continue and account for this acceptable risk by the PM or POs. 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.) Team's capacity for bugs / tech debt is pulled off for other work (unplanned, underestimated, change in priority) 
 
 2.) Team appropriately add bug and severity labels 
 
 3.) Team adds Bug and Severity level to ticket name 

 
 
</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Qart specific work | Flagship, Design System, API, H&B, external team specific tickets | 
| | | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>
 
- Github Epic
-[ Github Qa and Release Team](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release) 
- [Github Bugs Details ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Bugs)
- [Board with Bug Label ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug)
- [Board with Sev 1 Label](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-1)
- [Board with Sev 2 Label](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-2)
- [Board with Sev 3 label ](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/board?labels=bug,sev-3)
- [Bug Tracking for Q2](https://docs.google.com/spreadsheets/d/1Uehnj7xRQIQhN_ilWobAddTYdatAyifVfXO2Tl9huww/edit#gid=0)

</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Don McCaughey

**Ad Hoc:** 
- **Mobile Team**: Qart
- **Mobile Team PM:**  Adam Kasmier 
- **FE Engineering:** None 
- **BE Engineering:** None
- **Design:** None 
- **Content** None 
- **DevOps** None
- **QA:** Therese, Tom, Rachael  
- **Mobile Teams that are involved:** Qart, may need to pull in engineering if need calls for it 

</details>

**Comment by bischoffa** [comment]
Presented on 7/24 to POs during Q3 Planning Review. POs approved to move forward with this. No questions or concerns from the POs on this epic.

**Comment by TKDickson** [comment]
Q3 epic completed, closing
