### ISSUE TITLE
QA: Test Plan Claims Phase Expansion

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9051]
## Objective 

The purpose of this ticket is to document the test plan for the claims phase expansion work.

## Reference Material:
- [Updated screens (Figma)](https://www.figma.com/design/kSlXLwTVLunM0fqCG95k5x/%F0%9F%94%8D-Claims-2.0---Working---VA-Mobile?node-id=1547-29&t=fGgIE8tsd8NUROk1-0)
- [Copy deck](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=0#gid=0)
- [Current screens](https://www.figma.com/board/i6WG4mn2BZfmXZkMbcZCvx/%F0%9F%94%8D-Claims-2.0---Figjam---VA-Mobile?node-id=16-390&t=cRc4GloICky6gc9Z-0)

**Epic(s)**
[Epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8688)

## Acceptance Criteria

  

1. - [ ]  Create test plan
2. - [ ] Link to test case folder in TestRail
3. - [ ] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by ala-yna** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9051?planning-poker) with Zenhub @rbontrager

**Comment by rbontrager** [comment]
Test steps have been written and can be found [here](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=20702&group_order=asc&display_deleted_cases=0).  @DJUltraTom If you could please review that would be great.

@ala-yna To fully test this I will need to have either a user with claims in each of the 8 steps or be told how to use VBMS so I can verify it myself.  We might want to bring it up in our next sync meeting so it doesn't become a blocker down the line.

**Comment by DJUltraTom** [comment]
The test steps look good. Are you going to include a separate section for A11y test plan or rerun the current plan using the various a11y technologies?

**Comment by rbontrager** [comment]
@DJUltraTom I was planning on using the existing a11y tests.
