### ISSUE TITLE
BUG - sev-3 - All - Misalignment of "icon then text" on most pages with certain font sizes

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9054]
## What happened?

When [the font setting is large enough that the BOX (that the text for an external link is in) needs to wrap for more lines than the text itself  (video)](https://drive.google.com/file/d/1LRIvf4Njup7pdwYRLQ45o_jr0eABI2AD/view?usp=sharing), we get visual misalignments with the external link icon, like these:
<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUxTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a789acae5585063fde78e15218c29142c7aeb4cc/image.png" alt="image.png" />
<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVBTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fcaee5bb8ef71a093f407fbfcca553a0e1c3f3d3/image.png" alt="image.png" />

<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc8b0b4788bf9599cfa05f27809c6c7333db735d/image.png" alt="image.png" />

I've also seen this with the branch of service seal + branch of service name on the Veteran Status Card screen, so it appears to be something about how we're handling 'icon then then' layouts?

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [x] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
@TKDickson I tried reproducing on a few devices (both physical and simulator) at various font sizes, and I wasn't able to. I also had Binny try, and he wasn't able to either. Are you still able to reproduce? I'm wondering if this was either fixed, or if it was a one-off thing

**Comment by TKDickson** [comment]
@theodur yes, reproduced just now. And also Brea saw it just yesterday on the develop build (she asked me if it was a known bug). I see it pretty much constantly (without trying) so it's puzzling that you all were having such difficulty. 

I think the easiest method is to find a screen with one of those external link icons, then hop over to settings and adjust the font size by 1 notch, jump back to VAHB and repeat until you find a font size that breaks that particular screen. For the Profile Help screen, for instance, 4 of the 12 possible text sizes on my iPhone break the alignment of one or both of the external links on the large panel.

**Comment by TKDickson** [comment]
Icon stayed aligned with text for external links on all links on the Profile Help (how do I change my name), Payments Help (what if I'm missing a payment) and Veterans Crisis Line screens - which were the screens I picked as a sample of external links in the app. For all font sizes, iOS and Android. (although, to be fair, I rarely saw this problem in Android anyways because they have so few text/display sizes to work with)

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
