### ISSUE TITLE
Claims: Write copy for release notes (what's new in app stores)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9063]
## Description 
Write release notes copy for claims expansion project

## Acceptance Criteria
  

-  [X] Final copy for what's new section of app stores for claims expansion project (see next section for approved copy)

## Approved copy

We updated disability compensation claims. We explain the 8-step process for these claims and show what step your claim is on. You can also now submit evidence for these claims using the mobile app.

## Notes & Open Questions

- May want to check with web on how they're communicating this change

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Asked Jacob in [DSVA thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1721310479727009) how this change in claims will be communicated. Hoping to use same/similar wording for release notes.

**Comment by mistymg** [comment]
Per Jacob in today's BMT/VAHB meeting, they should be getting something from VBA people around comms/go-to-market. May be able to use that for release notes with tweaks. Should get that by end of week hopefully.

**Comment by mistymg** [comment]
Wording I've found so far from files shared in [this DSVA Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1721315744295539?thread_ts=1721310479.727009&cid=C04KHCT3ZMY):
<img width="788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3J3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--452d0bba264d045e82424376742b969a530350a8/Screenshot%202024-07-18%20at%2012.05.01%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 12.05.01 PM.png" />

<img width="726" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3Z3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--219e14c2b528eddea43918fb0e5015535467692a/Screenshot%202024-07-18%20at%2012.06.26%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 12.06.26 PM.png" />

<img width="735" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3p3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54aaf744905002c4bf09bc893ced0b692f5e7f92/Screenshot%202024-07-18%20at%2012.08.12%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 12.08.12 PM.png" />

<img width="702" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy93QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfc6a35a43988aec8a13f826b38b3a7baffcb8ff/Screenshot%202024-07-18%20at%2012.11.27%E2%80%AFPM.png" alt="Screenshot 2024-07-18 at 12.11.27 PM.png" />

This will all likely be helpful in writing release notes.

**Comment by mistymg** [comment]
@ala-yna Here's what I'm thinking for app store release notes for claims expansion. Let me know what you think:

"We updated disability compensation claims. We explain the new 8-step process for these claims and show what step your claim is on. You can also now submit evidence for these claims using the mobile app."

**Comment by ala-yna** [comment]
@mistymg, looks good! Do we want to call it a "**new** 8-step process" though? Technically it's the same process, but with different labels. I wouldn't want a Veteran to think that any part of how a claim is adjudicated has changed.

**Comment by mistymg** [comment]
@ala-yna @bischoffa and whoever else. There have been some updates to copy for the what's new section of the app store when we release the expanded claims phase work. Apparently we might also ship out the [new Post-9/11 GI Bill direct deposit work](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8452), too. So I've updated the approved copy in the section above for multiple scenarios.

**Comment by mistymg** [comment]
[DSVA Slack thread](https://dsva.slack.com/archives/C04KHCT3ZMY/p1723128259504639) with approval of release notes from BMT team.
