### ISSUE TITLE
BUG - sev-3 - All - Calling payment history endpoint twice when navigating to payment history screen

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9065]
## What happened?

When navigating to the payment history screen (list of payments), we're calling the payment history twice (and getting the same results back twice, although with slightly different calls on our side)

First call (kicks off on initial navigation to screen): 
`mobile/v0/payment-history`

Second call (kicks off maybe ~2 seconds after the first one, restarting the loading indicator/loading sequence on screen):
 `mobile/v0/payment-history?startDate=2024-01-01T23%3A59%3A59.999-08%3A00&endDate=2024-12-31T23%3A59%3A59.999-08%3A00&page%5Bnumber%5D=1&page%5Bsize%5D=10`

This may be pagination-related? That's my guess - we're calling a "load the screen" thing, and then also have some weird "and we're on the first page of the screen so load that" thing we should be ignoring on initial load. But :shrug:

Intriguingly - if I block the first call/don't let it go through, the second one is never called & we just show an error. And if I allow the first call but block the second, all of the information will very briefly flicker onto the screen, but ultimately the page itself will also not load.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Only call whatever of those two APIs we need, the one time. To make loading faster, and avoid duplicative API calls.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
My changes are limited to the hooks related to setting the `VAModalPicker` data, so there's nothing out of the ordinary that needs to be tested with my changes. Mainly, that changing the year on the Payments history screen refreshes the screen with the payments for that year, and that navigating between pages works as expected. Another good thing to test is navigating through pages and then changing the year while on a later page.

**Comment by TKDickson** [comment]
We're calling the payments endpoint just one time on navigation to screen, then once each time again when changing year selection, and paging forwards or backwards through the activity. And all of those are loading the correct/expected data. For a user without authorization for payments, we are still correctly not calling the API at all (no regression on the other payments fix this sprint). Demo mode also is unchanged from a manual check (which is totally expected, but wanted to check so we don't break detox the day before RC).

**Comment by TKDickson** [comment]
To be extra careful, I've also kicked off payments in detox for [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10165970318) and [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/workflows/e2e_android.yml).

**Comment by TKDickson** [comment]
Both scripts passed, this is approved to merge.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
