### ISSUE TITLE
Accessibility - Tech Debt & Maintenance - Q3

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9067]
# Project Status Overview
### Project Objective:
This epic is focusing on Accessibility related work for the VAHB during Q3. This would include accessibility needs on top priority items in Design System, Flagship, and Global. While also include general technical debt and maintenance of Accessibility needs. This work will include:

- External team documentation (web vs mobile differences, how to, best practices, etc)
- Defining Accessibility needs (processes, artifacts) during project lifecycle (Step 0, Step 1, Step 2, Step 3, etc)
- Pre-emptive awareness of future accessibility impacting changes (WCAG, new OS, etc)
- Identifying and defining Accessibility bugs (including not meeting WCAG standards) and handling
- Accessibility audits - defining, implementing and handling findings
- Reviewing existing processes for accessibility gaps (ex. not an Eng standard to use focus)

At least 30% will be allocated specifically todays Accessibility Technical Debt while the other 70% can be used to support Flagship, Design System and H&B or UX floater needs. 

Accessibility work that other projects or teams require will fall under their specific project's epic and not here. This epic is specifically for internal Accessibility work. 

### Stakeholder Updates
| Date      | Project Health  | Progress & Key Accomplishments   | Issues/Risks/Blockers |                                                                                                          
|----------- | ---------------- | ------------- | ---------- |
| 9/30/2024 | **Green**     | MCAG documentation (turning presentation into official documentation) is underway. Tickets have been created and working through general documentation.  | None      |
| 9/16/2024 | **Green**     | Review of past audit tickets to update severity is complete.   | None      |
| 9/16/2024 | **Green**     | Dark / light mode color audit is complete.   | None      |
| 9/16/2024 | **Green**     | Recommended updates for alert announcements have been determined and discussed with the design system team.   | None      |
| 9/4/2024 | **Green**    | MCAG presentation complete.   | None |
| 8/19/2024 | **Green**     | Project steps have been properly outlined and accessibility artifacts have been integrated into the steps. Implementation of these steps will be covered in a future ticket.   | None      |
| 8/19/2024 | **Green**   | Project steps have been properly outlined and accessibility has been integrated into the steps. Implementation of these steps will be covered in a future ticket.   | None   |                                                                                     
| 8/19/2024 | **Green**    | Worked with Adam and Therese to integrate accessibility into our bug severity. Will create a new ticket to update the [issue severity guide](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/#issue-severity) on the documentation site with these additions. | None |
|8/6/24| **Green** | Regained access to TestFlight to test iOS accessibility issues. Defined Q3 priorities. Preparing for MCAG materials for the next Mobile Demo. Reviewing Steps process and defining artifacts and requirements Accessibility wants to have at each step. Incorporating Accessibility findings into bug severity process and documentation | None |

### OKRs

<details>

- Stability - Reduce Accessibility bugs by 25%
- Productivity - Enable teams to build faster through accessibility best practices, artifacts, and expectations 
- Retention - Improve Veteran retention amongst Veterans with Accessibility Needs (meet WCAG / MCAG standards) 
- Satisfaction - Improve Veteran satisfaction amongst Veterans with Accessibility Needs  (ensure Accessibility is MVP) 

</details>

### Risks

<details>
<summary>Risks</summary>
 
 - Capacity continues to be pulled away from Accessibility specialist toward other areas like UX 
 - Accessibility (standards, code, reviews) not being deemed a requirement or show stopper for releasing new features or changes to features 
 - Perception that Accessibility work does not need to be reviewed by an Accessibility specialist before going into production 
 
</details>

### Assumptions

<details>
<summary>Assumptions</summary>
 
 - Accessibility needs and testing is just as critical as QA 
 - Capacity will only be used for Accessibility related work 
 - Non Accessibility related work will eventually be moved to the appropriate group of people 

</details>

### Current Dependencies / Blockers

<details>
<summary>Blockers</summary>
 
|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal dependency ? |   |
| External dependency ?  |   |
</details>

### Team Members
<details>
<summary>Contact List</summary>
 
**VA:**
- **Mobile OCTO Product Leads:** Rachel Han or  Ryan Thurlwell
- **VA OCTO Product Leads:** 
- **External Team 1 & Role:**
- **External Team 1 & Role:**
- 
**Ad Hoc:** 
- **Mobile Team**: Qart
- **Mobile Team Lead:** Adam
- **FE Engineering:** NA
- **BE Engineering:** NA
- **Design:** Brea
- **Accessibility** Brea
- **Content** NA
- **QA:** Therese, Tom, Rachael
- **Mobile Teams that are involved:** Global, Health and Benefits, Design System, Qart
</details>

**Comment by bischoffa** [comment]
Presented on 7/24 to POs during Q3 Planning Review. POs approved to move forward with this. No questions or concerns from the POs on this epic.

**Comment by TKDickson** [comment]
Q3 work completed; closing epic.
