### ISSUE TITLE
BUG - Sev-3 - All - Too much spacing after bullet list

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9068]
## What happened?

I think this was brought on by WCAG paragraph spacing but maybe not.  There is a too much spacing after a bulleted list. This includes:
- Messages > The we need more information bullet list when saving a messaging, saving a reply, saving a draft etc.
- Claims > Claims History > Appeal Details > Issues Segment > The currently on appeal bullet list

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

1. Navigate to one of the areas listed in the description.  Notice the amount of spacing after the bullet list

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjdYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a50607d4fe18f2e433c3ec7251190c976183be66/Screenshot_20240712-064209.png" alt="Screenshot_20240712-064209.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
I found the issue is with the VABulletList component on this line

<Box mb={paragraphSpacing ? theme.paragraphSpacing.spacing20FontSize : undefined}>

Apparently the paragraphSpacing boolean has stopped working for whatever reason

**Comment by rbontrager** [comment]
@brea11y It looks like Dylan's fix added/kept it so all the bulleted lists have paragraph spacing outside of the ones I mentioned above.  I just want to confirm with you that from an accessibility perspective that we just need to have normal spacing correct? I can send you some screenshots if needed as well showing what it now looks like.

**Comment by brea11y** [comment]
@rbontrager – I agree with you. I know the design system team is beginning to work through typography tokens and I'm syncing with Jessica to help set them up with WCAG best practices built in. Hoping that solves a lot of these issues when that work is complete. Thanks so much for looping me in!

**Comment by Sparowhawk** [comment]
updated to have the standard margin between of 20 instead of the 40 it was

**Comment by brea11y** [comment]
@Sparowhawk Thanks so much. I agree that we'll likely need to adjust spacing around/within the lists in the future, but since it was not accounted for in the WCAG scope of work, I'll be sure to bring it up when I work with Jessica on the Typography Tokens. I'm hoping that we can ease the burden on you all and fix these issues in that work. 🤞🏼 

The initial conversations right now are about possibly having a couple different spacing options to choose from in the tokens (small/standard margin, WCAG increased margin, and margins for when links are present following longer blocks of content). Since you setup the WCAG spacing initially when we did that work, I'd love to loop you in and get your thoughts and share those with the design system team as they're working through those updates.

**Comment by rbontrager** [comment]
Over my WIP limit and focusing on claims so blocking this for now.

**Comment by rbontrager** [comment]
@Sparowhawk Just two minor changes needed.  It looks like you may have double the amount of spacing between the text and the first bullet point for both Cerner SM and Prescription help. So for instance this is what it looks like in Ask for a claims decision.
<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef3a03f1f4d67656b12348c298aceddae039733c/Screenshot_20240730-130035.png" alt="Screenshot_20240730-130035.png" />

And this is what it looks like for the SM Cerner message.
<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--639db7b5a3caf32b20c37d3fdfc29fe4596c0d12/Screenshot_20240731-100348.png" alt="Screenshot_20240731-100348.png" />

**Comment by Sparowhawk** [comment]
updated for both

**Comment by rbontrager** [comment]
Verified that the paragraph spacing has been removed from before and after the bullet list and that the spacing is consistent for the following features:
- What's new
- Appeals
- Ask for Claim Decision
- Cerner Health Screen Popup
- Prescriptions Help
- Prescription Details
- SM Cerner Alert
- SM Reply Help
- SM Errors Banner
- In App Recruitment
- Onboarding

Approved by QA.
