### ISSUE TITLE
Post RC Code Change - Inclusion of App Store Images so HSP can launch 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9118]
## Reason for new Release Candidate Build:
- [ ] Bug
- [ ] Missing Code
- [ ] Untested code merged
- [ ] User Experience Issue
- [X] Other:  App Store images that were approved where not merged in time 

## Impact if current Release build is released without proposed changes:

 - HSP would be blocked from releasing which would mean we would need to pull out HSP vs just adding in app store images that have no impact on on app functionality 

## Proposal for RC code to be changed:

- Add in app store images 

## Acceptance Criteria:
- [X] Have you reviewed the [RC change policy?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies/Policy%20-%20Change%20Management%20for%20Adding%20New%20Code%20to%20the%20Release%20Branch.md)
- [X] Have you notificed the release team? Binny to Adam 9am 7/17
- [X ] Have PO's approved of this change? Adam is assuming they are as they have talked and shared the launch date 
- [X] Will this new RC impact our planned release cadence? No
- [X] Has QA's RC testing been completed? Not yet started 
- [X] Does QA have a test strategy in place for the new RC? Yes nothing changes
- [X] Are associated tickets linked? (EG: bug, PR, UX findings)  [9046](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9046)

## Points of Contact for the new RC branch:
<!-- Please enter points of contact for the following areas that will be addressing the new RC branch --!>
PO:<br> Rachel 
PM:<br> Adam 
Dev:<br> Binny
QA: <br> Tom

**Comment by bischoffa** [comment]
Going to use this as an educational opportunity for engineering and Product to reduce this in the future. Also as an example that we allowed it but its not something we will allow in the future. 

This process is documented but seems like people are not following or aware so need to approve the awareness.

**Comment by DJUltraTom** [comment]
@bischoffa we should discuss this ticket template and course of action for its lifecycle, I already see some refinements we can make.

**Comment by bischoffa** [comment]
Images have been added. Resolving.

@DJUltraTom please add it to our 1;1 agenda so we can talk more. Feel free to make a backlog ticket with your thoughts so we can track future work. Add to Q3 Bug Epic
