### ISSUE TITLE
BUG - sev-2 - All - Not logging vama_login_token_fetch errors

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9119]
## What happened?

We have not logged a single `vama_login_token_fetch` error in production. It seems far more likely that our assumptions/logic behind how we could log that error are broken, rather than "a veteran has truly never had this problem during production login".

[More background context - we're trying to make sure that we know what errors on our side look like when veterans fail to log in for various reasons, in production. In ticket #8271, investigation of possible internal "unable to log in because browser too old/unsupported", it seemed like we SHOULD be logging a `vama_login_token_fetch` error in that case. Therefore, this ticket is currently blocking that one.]

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

We should be logging those errors, with whatever related information would also be helpful, in production.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
This will either be no QA (analytics so I can't do anything), or will be a quick regression. Marking as QA1 estimate.

**Comment by cadibemma** [comment]
@TKDickson  I likely was there but don't remember that discussion haha

**Comment by theodur** [comment]
Just approved Chika's PR. Since this is just analytic changes, there's nothing for QA to test
