### ISSUE TITLE
BUG - sev-3 - Github Actions - Logic error means QA no longer auto-assigned

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9128]
## What happened?

We wanted to auto-assign QA to tickets AFTER they were testable, so changed the logic with [PR 9076](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9076/files). However, the logic implemented is looking for both the team label, and the FE-With QA label - but one of those labels is on the PR, and the other is on the ticket. So it wasn't auto-assigning QA, ever.

We are still looking for a way to fulfill the ACs in the original ticket, via Github Actions: #8974.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by IsraelleHub** [comment]
@TKDickson As I mentioned to @bischoffa and @rbontrager. since the logic is working. For now we have to make sure that whoever is creating a PR or a ticket tag both label to it to make it easier until we figure out a better way to auto-assign. Please let me know if this work!

**Comment by TKDickson** [comment]
Closing in favor of #9398
