### ISSUE TITLE
Should Testflight access issue be a launch blocker

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9136]
Testflight access is not working for iOS for Accessibility and POs should this be a requirement for launch?

**Comment by bischoffa** [comment]
Do we pull in Don for this ? Basically need a different process cause existing month is taking ~month or PO involvedment for progress.

**Comment by bischoffa** [comment]
Do we need to consider a device backup if there is a 90 day window issue

**Comment by TKDickson** [comment]
@timwright12 do you know what this ticket is about?
