### ISSUE TITLE
Github Action to auto assign Accessibility Label to Brea 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9137]

**Comment by timwright12** [comment]
@bischoffa Do we know what the conditions are where this label would be auto-added? I feel like with the direct team assignments it's easy, but Brea will kind of do it all

**Comment by bischoffa** [comment]
Not yet. This was a placeholder ticket for the backlog until I can get to focus on it.   
  
Initial thought was simply when anyone adds the accessibility label then add Brea as an Assignee.

**Comment by TKDickson** [comment]
This work is done - #9375. Closing as duplicate
