### ISSUE TITLE
Discovery: mobile/v0/adapters/lighthouse_direct_deposit.rb New Error

### ISSUE THREAD

**Issue by Tonksthebear** [department-of-veterans-affairs/va-mobile-app#9140]
New Error Alert: https://vagov.ddog-gov.com/monitors/213410?q=%40error.file%3A%2Fapp%2Fmodules%2Fmobile%2Fapp%2Fmodels%2Fmobile%2Fv0%2Fadapters%2Flighthouse_direct_deposit.rb&event_id=7661010931675024480&source=monitor_notif&view=spans&from_ts=1720893710000&to_ts=1720894910000&eval_ts=1720894910000

```
NoMethodError: undefined method &#x60;[]&#x27; for nil
```
in `app/modules/mobile/app/models/mobile/v0/adapters/lighthouse_direct_deposit.rb`

**Comment by kpethtel** [comment]
Tom Harrison and I have been talking to other teams about this. Moving to blocked for now and will finish it up when I return from PTO.

**Comment by kpethtel** [comment]
After getting more information from an upstream team, I took another look at our code and concluded that lighthouse is not handling the upstream data correctly. I'm continuing to talk to Tom Harrison to hopefully get this fixed in the right place.

**Comment by kpethtel** [comment]
Tested on staging. Lighthouse has been informed about the issue and will hopefully fix it, in which case we can undo my changes.
