### ISSUE TITLE
QA prep work for RQ Auth migration

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9162]
Was originally intended to be done in a single ticket with the notifications migration (#9040) and then I realized auth migration is going to be a beast. So separated out here.

Copy pasted info from referenced ticket:
Auth and notifications have not yet been react query migrated. - #8253 and #7743

We're going to be doing that soon, which means the normal QA prep work (understanding what's in the changes, writing a test plan and getting review) should also happen.

This ticket is for that. 

- [ ] Understanding scope of migration changes (including implementation choices like 'is this on one branch or two? how complicated was the develop -> branch(es) merge with the amount of time lapsed?' etc)
- [ ] Writing a test plan
- [ ] Getting TPR & making changes

**Comment by TKDickson** [comment]
Work done previously on other ticket:


High-level test plan from looking at the file changes in #7743.

_For all of these case categories, will need to cover success & failure variations._

**Auth**
Login
* get auth services
* PN preference fetching
* HSP pre-fetching (should compare precisely to that HSP efficiency ticket)
* Biometric and UN/PW
* Probably need to do all credential types
* Handoff/handback to various browsers with Android
* Google SSO whatever that thing is login
* Terms & conditions (within webview) Yes/No/Future handling with handoff and handback
* MHV credential login workaround

Refreshing access token
PN with app in foreground and background
Biometrics opt in/out
* During initial login
* Also later
* Also variations: biometrics supported on device at all vs not

Cerner "first time login" and "first time in session" help popup in Health screen
Caching (across sessions, within sessions)
Logout (including multiple users on one device)
Onboarding carousel pops up (or not)
"reset to first time login" developer tool
fetching and applying maintenance windows
Native handoffs during login (permissions for biometric and PN)

Still need to investigate and then add to plan above:

- [ ] Analytics related to login/auth/sync/logout flow or screens
- [ ] Are there other dev tools that require logout/session management?
- [ ] Finding bug tickets related to auth, login/logout, credential types, etc & adding their cases to test plan
- [ ] Review of test cases in TestRail, and selecting edge/corner cases that should be included in this testing

**Comment by TKDickson** [comment]
Analytics in auth slice:
* vama_login_success
* vama_user_call error
* vama_login_token_store (true and false)
* vama_login_token_get (true and false)
* vama_login_token_refresh error
* vama_auth_completed
* vama_login_token_fetch error
* vama_login_closed
* vama_login_fail
* vama_login_start

I'll just state for the record that's a lot of analytics, so we probably also need a ticket for checking the events post-release, seeing if there are major changes in those trends as well

**Comment by TKDickson** [comment]
Relevant bugs to check they don't regress:
#7922
#7229
#6981
#6736
#5525

**Comment by TKDickson** [comment]
There appears to be only a single useful login-related case - https://dsvavsp.testrail.io/index.php?/cases/view/40800&group_by=cases:section_id&group_id=10253&group_order=asc&display_deleted_cases=0 (for custom tabs in Android). There will be a lot of writing, or re-writing, of cases for this migration.

**Comment by TKDickson** [comment]
Dev tools with session management (in addition to first time login reset):
* "apply override" on remote config flags

**Comment by TKDickson** [comment]
OK, all initial investigations complete. Now it's a matter of taking all of these notes, and turning them into a series of well-written test cases.

**Comment by TKDickson** [comment]
OK, here's the actual list of things, organized & with checkboxes so I can mark things as done as I write/edit/find cases.

- [ ] Login UI - borrow from RC testing, plus
- [ ] Login types (initial UN/PW, biometric + valid session, biometric + not valid session)
- [ ] Login with all the browsers
- [ ] Log in with all of the..... credentials people

Login 'behind the scenes'
- [ ] Maintenance windows
- [ ] Various API calls: PN preferences fetching (not first login), auth services, user, HSP preloading

- [ ] Terms and conditions - should be cases written for this already (Terms & conditions (within webview) Yes/No/Future handling with handoff and handback)

Peripherals:
- [ ] Push notifications, foreground and background
- [ ] Push notifications, multiple users cases
- [ ] Cerner "first time login" and "first time in session" help popup in Health screen
- [ ] Caching (across sessions, within sessions)
- [ ] Logout
- [ ] Reset to first login developer tool
- [ ] Remote config overrides developer tool
- [ ] Onboarding
- [ ] Analytics (existing placeholder case)
- [ ] Refreshing access token

**Comment by TKDickson** [comment]
[Test run assembled and ready for review.](https://dsvavsp.testrail.io/index.php?/runs/view/5901&group_by=cases:section_id&group_id=8943&group_order=asc)

**Comment by TKDickson** [comment]
Assigning test plan review (comment immediately prior links to test plan) to @rbontrager . This review can be done anytime during the upcoming sprint, there's no rush.

**Comment by rbontrager** [comment]
@TKDickson Everything looks good test case wise but I noticed that none of the cases feel like they accounting for/testing all the fields in the authorized services json outside of those shown during login.  It might be a good idea to check that all those features are called properly when both authorized and not authorized.

**Comment by TKDickson** [comment]
Good idea - added content to a previously blank case, and [added to my test run](https://dsvavsp.testrail.io/index.php?/tests/view/1267949&group_by=cases:section_id&group_order=asc&group_id=3442), for covering authorized services testing.

Closing ticket as complete.
