### ISSUE TITLE
Submit evidence/File request updates & interaction improvements

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9164]
### Description
As part of [Epic 8688](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/8688), we are adding a Submit evidence button, and updating the location of the Review file request button. With this, we'll need to update the copy in some areas within the user flow. 

The copy updates are conditional, meaning that what's displayed will respond to whether a user has pressed `Submit evidence` OR `Review file request`.

As part of this story we want to: 

- Use the primary button to launch each task into a Large Panel
- Add new Submit evidence copy
- Update File request copy

#### All
- [x] Launch as a Fullscreen Subtask
- [x] On completion/cancel, route user back to previous Child screen. So, either [Claim detail: Submit evidence] or [Claim detail: Review file request]
- [x] Upload Files screen: if a file is there and they remove it, keep them on same screen and pass an Upload button (secondary style)
- [x] Entire flow: Make sure it appears that we are staying within the task. So, no new screens popping up from the bottom once they’ve entered the flow. (Except for the Action Sheet / Dialogs of course)
- [x] Top Nav Action First screen / Upload files / Upload photos screens: Cancel
- [x] Top Nav All others: Back

#### Submit evidence flow
- [x] Create first screen; follow [copy deck](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=737285959#gid=737285959) and [design](https://www.figma.com/board/i6WG4mn2BZfmXZkMbcZCvx/Claims-2.0---%F0%9F%92%A1-Documentation---VA-Mobile?node-id=564-6665&t=131tYAK4dRmtgw4Y-4)
- [x] Make any copy updates to subsequent screens within the flow

#### Review File Request flow
- [x] Make any copy updates to subsequent screens within the flow 
- [x] Ensure Claim evaluation screen is included within the flow; replace [Cancel] with [Back]

**Comment by ala-yna** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9164?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by Sparowhawk** [comment]
@mistymg just confirming the copy for this cancel alert works for canceling photo/file upload

It says photo/file respectively based off which one they are in. The change is the end where instead of saying it will take them back to the file request it will take them to the claim details.

<img width="422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--432a0bd3cd99016ccd260445a7dc91ef9d535460/Screenshot%202024-08-15%20at%203.43.40%E2%80%AFPM.png" alt="Screenshot 2024-08-15 at 3.43.40 PM.png" />

**Comment by mistymg** [comment]
@Sparowhawk The PNG isn't working. Is this the same as [this Slack thread](https://adhoc.slack.com/archives/C067S0FRP0C/p1724678745249499?thread_ts=1723747857.227239&cid=C067S0FRP0C)?

**Comment by rbontrager** [comment]
@DJUltraTom Can you do a test plan review please.  New test cases can be found [here](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=22674&group_order=asc&display_deleted_cases=0).

**Comment by DJUltraTom** [comment]
- for "upload cancellation" and "Claims file request" are we displaying the destructive editing message "We'll remove your files and take you back" if so should we explicitly call that out in the steps?
- for "reupload photo after deletion" should we exercise the option to add the photo back?
- for "reupload photo/file after deletion" should additionally test the dismiss/canel options during the reupload like we do in the other upload areas or are we confident that the software mechanism is the same?
-

**Comment by rbontrager** [comment]
@Sparowhawk I noticed a couple small bugs and a couple maintenance tasks you didn't do:

- There is no space between the 'take or select photos' button and the 'select photos to upload' section. Based on the figma there should be a little space there:

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUthQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6f7279441a60d688679ec586e2ac8839b446e75/IMG_0105.PNG" alt="IMG_0105.PNG" />

- There is some wonkiness with submitting a file happening with the new flow which keeps the user on the 'upload files' screen once a file is deleted. This is happening in both the submit evidence and file requests flows. Steps to reproduce: Follow the flow to upload a file > Delete the file using the trashcan > tap 'select a file' and upload a new photo (so something different than what you originally selected) > tap 'submit file' and notice that it fails.  
- Maintenance: The submit evidence screen needs to be added to the navigation.e2e tests.  How to is found [here](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/AddingNewFeatures)
- Maintenance: The new submit evidence AF waygate needs to be added to the AvailabilityFramework.e2e tests. How to can be found above
- Maintenance: Add the new submit evidence screens to the detox mapping file [here ](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/.github/workflows/e2e_detox_mapping.yml)

**Comment by Sparowhawk** [comment]
Fixed spacing

Checked on the wonkiness with Judy and I was able to submit a different file than the one I originally selected. Maybe some network error happened outside of that and it failed temporarily. Would need a video to show it happening.

**Comment by Sparowhawk** [comment]
added maintenance stuff
