### ISSUE TITLE
Remove feature flag for claims phase expansion

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9168]
Once we're confident with the rollout of expanded claims phases on Mobile, we'd like to clean up the code and remove the feature flag that was used.

**Comment by rbontrager** [comment]
@Sparowhawk I pulled your branch up to the latest (because the submit evidence flag was still true on the original one I had) and I'm now getting a crash when trying to view claim details.

**Comment by Sparowhawk** [comment]
@rbontrager fixed, it was due to the analytic branch getting merged in and it having that check

**Comment by rbontrager** [comment]
Reran the claims phase expansion test with no issues (found [here](https://dsvavsp.testrail.io/index.php?/runs/view/5984&group_by=cases:section_id&group_order=asc)). Approved by QA.
