### ISSUE TITLE
BUG - sev-2 - iOS - New crashes in secure messaging in 2.32

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9187]
## What happened?

We're seeing [crashes in iOS in secure messaging starting July 17](https://console.firebase.google.com/project/va-mobile-app/crashlytics/app/ios:gov.va.vamobileapp/issues/953edac963b2df7c076085b7f2f54086?time=last-ninety-days&types=crash&sessionEventKey=26db8879644a49348f1b8eb4506d76e2_1973699804519916996) (seemingly just iOS, just secure messaging, and just 2.32 release - although given the volume it's not a guarantee).

Off of very first glance, these appear to be related to not having graceful enough error handling in edit draft:
<img width="889" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUlNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6b6aba4d4a495724c83dc8beabf57d4afa4dac9c/image.png" alt="image.png" />

Checked with the backend team - there's been some (but not tons) of messaging-related errors in the last month. So it's possible this is new to 2.32, or could have been introduced in an earlier release but just not had the right circumstances to trigger it.
504s for v0/messaging/health/message/##### for the last month:
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2dNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f803fd97f901314947d1b26e6a1f6ecaf03f9c7/image.png" alt="image.png" />

Errors for the last month for v0/messaging/health/recipients :
<img width="1174" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29NQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3c00b1158bbd94a2893cc76ba4c1135820f81ee3/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
Update

setTo(message?.recipientId.toString() || ‘’)

to

message?.recipientId?.toString() for safety since there are crash logs in firebase

**Comment by rbontrager** [comment]
Verified that the app no longer crashes when you change the recipientID in charles proxy to null for drafts. Approved by QA.
