### ISSUE TITLE
Not handling VBMS 502s correctly (returning 500s)

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9188]
[New Issue](https://vagov.ddog-gov.com/apm/services/mobile-app/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%2195%2CtopN%3A%215%29%2Cversion%3A%210%29&env=eks-prod&errors=qson%3A%28data%3A%28issueSort%3ATOTAL_COUNT%29%2Cversion%3A%210%29&fromUser=true&graphType=flamegraph&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&logs=qson%3A%28data%3A%28indexes%3A%5B%5D%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28activePanelKey%3Atrace%2Cresource%3A%28resourceName%3AMobile%253A%253AV0%253A%253ADecisionLettersController%2523download%2CresourceID%3A84da4bf1a9599a96%29%2Ctrace%3A%28traceID%3A869161981775510541%2CspanID%3A2222311811472067404%29%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%2Csearch%3Adecision%29%2Cversion%3A%211%29&shouldShowLegend=true&sort=time&spanID=2222311811472067404&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&timeHint=1721837505204&trace=AgAAAZDlg0q0SKtL2AAAAAAAAAAYAAAAAEFaRGxnMW1QQUFCNnJDOG84NEw4alE4TQAAACQAAAAAMDE5MGU2MmYtMDA4Ni00ZDI1LWE4OWItMjEzNzYwOTc5Y2Nh&traceID=869161981775510541&traces=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&view=spans&start=1721833054948&end=1721841761723&paused=true#summary)

**Comment by StacyB2023** [comment]
Added epic

**Comment by kpethtel** [comment]
I spoke to Sam Cormier of the health benefits team about this. He said his team will create tickets for mapping the vbms errors to vets-api errors. It may take them a while to prioritize and fix this, but I suspect it's better to have them do it than us do it.
