### ISSUE TITLE
Documentation to auto assign tickets to QA when ready for QA

### ISSUE THREAD

**Issue by IsraelleHub** [department-of-veterans-affairs/va-mobile-app#9193]
We want to auto-assign QA to tickets AFTER they were testable, so changed the logic with [PR 9076](https://github.com/department-of-veterans-affairs/va-mobile-app/pull/9076/files). However, the logic implemented is looking for both the team label, and the FE-With QA label - but one of those labels is on the PR, and the other is on the ticket. So it wasn't auto-assigning QA, ever.

The other option on how to handle the logic was going to add much more complexity and work. So we believed it was easier to use tagging practices to make this work.

So, this documentation is to communicate the new process when creating PR or tickets to make the auto assign qa workflow work while waiting to figure out a best process for it.

Connected issues: [PR 9128](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9128)

**Comment by bischoffa** [comment]
Adding the next sprint since this was not closed in the last sprint.

**Comment by IsraelleHub** [comment]
QUART team decide it will be best to go back with manual assignment. so I am closing this ticket
