### ISSUE TITLE
Investigate if we use the appts duration field on the front end

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9197]
If so create a ticket to add it to the service, otherwise we can remove the field all together

**Comment by StacyB2023** [comment]
Tagged to the Q3 epic for appts since we are entering Q3 this week

**Comment by aherzberg** [comment]
FE does use this field. created new ticket to move it. https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9208
