### ISSUE TITLE
Move minutesDuration field to shared appointment service

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#9208]
We've confirmed that Mobile FE does use the Duration field so even though VAOS does not, we will add it to the shared service and include it in only the mobile serializer.

**Comment by jperk51** [comment]
Slack comment @kpethtel was referencing. https://adhoc.slack.com/archives/C0206QFMXFU/p1722875664418999?thread_ts=1722872933.412359&cid=C0206QFMXFU
