### ISSUE TITLE
Documenting Current Rotation Information - Floater (API, DS, Release Mgt) 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#9215]
**Description:** 
As VAHB QA, I want to document my learnings, findings, and knowledge learned in my current QA assignment, so that when another is assigned here they can use this information to better prepare themselves for the work. 

**Notes:** 
 - Purpose is for the current person in the rotation is to start a knowledge document for QA that contains relevant learnings, knowledge, and other information that the next person coming into the role can use to help get comfortable with the rotation
 - [Template ](https://docs.google.com/document/d/1ZFU1C_1-1wyQVaWT-vYlIMlEdyPmy0ihPArr2vT3_Ik/edit)has been drafted for QA to use for this - empowered to tweak it
 - [Template ](https://docs.google.com/document/d/1ZFU1C_1-1wyQVaWT-vYlIMlEdyPmy0ihPArr2vT3_Ik/edit)likely will need to be duplicated for Floater given multiple areas are involved there 

**ACs:**

- Fill out this [knowledge document ](https://docs.google.com/document/d/1ZFU1C_1-1wyQVaWT-vYlIMlEdyPmy0ihPArr2vT3_Ik/edit#heading=h.9mjz3y2wiqnx)for your existing area 
- Information in the document includes
- Team information 
- Challenges faced
- Opportunities 
- Tools used 
- Verify tool information is documented and up to date 
- Processes used 
- Verify process information is documented and up to date 
- Regularly used test accounts 
- Other relevant information

**Comment by bischoffa** [comment]
I would recommend separate sections for each area. Given we aren't doing much for DS and API maybe a separate section where you can combine them. More so for both QA just needs to be informed / consulted if there is applicable QA work but its rare at the time these two teams do work.

**Comment by DJUltraTom** [comment]
copied and filled out document located here: https://docs.google.com/document/d/1OW0vYpCnhw2CvMSqu2j-xBfHXe4CucbmiTGat2re9HY/edit#heading=h.aeby96o6g52c

**Comment by DJUltraTom** [comment]
form has been updated, closing
