### ISSUE TITLE
Update Dynamic Link Fallback URL

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9220]
AC:

- Update dynamic link fallback URL from https://va.com to https://va.gov/

**Comment by theodur** [comment]
I assigned Binny to this ticket because he's the only one that can do this, since it requires admin access in the Firebase console.

**Comment by theodur** [comment]
For reference, this is the error you get when you try to create/update a Dynamic Link's `Deep link URL` (Fallback URL for desktops) to `https://va.gov`:

> An error occurred when creating a new Dynamic Link: Cannot create short durable link error: (We could not match param 'https://va.gov' with whitelisted URL patterns in this Google project.). [https://support.google.com/firebase/answer/9021429]

**Comment by dumathane** [comment]
Done!
