### ISSUE TITLE
Add automation check for app store image counts

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9224]
We recently had an issue with having too many images in our Android bundle. We should easily be able to run a check on that max image count to avoid hiccups in the release.

[Slack thread for the most recent incident](https://dsva.slack.com/archives/C018V2JCWRJ/p1722348527097669)

**Acceptance Criteria**

- [ ] An image check count runs in pull requests

This should be a very fast test to run, so I think it's fine to run on each PR as part of another workflow, probably the unit tests?

**Comment by lexicalninja** [comment]
closed with #10226
