### ISSUE TITLE
BUG - sev 3 - All - Spacing on Appointment List screen

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9225]
## What happened?

On the Appointments list screen, there is a significant amount of space above and below the copy _(Here are your appointments ...)_.

## Specs:

- Device: Any
- OS: Any
- User Account: Any; seen in demo mode
- Accessibility State: n/a

## Steps to Reproduce

Navigate to the Appointments feature screen (Health > Appointments; or if Activity module is present, use it for direct landing!)

## Desired behavior

Spacing around that copy should align with the other areas in the app. 

It should be 20px above and below to allow consistent spacing between content. ([reference link: Figma](https://www.figma.com/design/JQAoUBxvSWCzKvu2ifRRE7/Health-2.0---%F0%9F%9A%A2-Shipped---VA-Mobile?node-id=1067-32454&t=aDQvMY52JlMLgVYG-4))

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

![appts-spacing](https://github.com/user-attachments/assets/fde5c540-d3ac-42be-8c88-35e777997811)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
Verified that the spacing above and below 'Here are your appointments' has been reduced.  Approved by QA.
