### ISSUE TITLE
Onboarding Comparative Analysis

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#9227]
Put together a comparative analysis of onboarding experiences in a variety of mediums using FigJam.

**Comment by htcollier** [comment]
[Design Inspiration images collected ](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=201-1206&t=pQGrl3FCKCOJGrt8-1)
