### ISSUE TITLE
Automation - Add status checks for App Store Requirements

### ISSUE THREAD

**Issue by narin** [department-of-veterans-affairs/va-mobile-app#9228]
# Automation Ticket

## Type of Change
- [ ] Update existing automation
- [x] Add new automation functionality
- [ ] Fix automation bug

## What systems/scripts are changing?
- [x] Git Hub Actions
- [ ] Fastlane
- [x] Bash Scripts
- [ ] Issues Templates

## What is the work being done?

Both app stores have certain requirements that would cause our builds to fail if not met. We can add a status check to check these requirements and prevent PRs from being merged if unmet. Some of the requirements are documented [here](https://docs.google.com/document/d/1GuTJ1U2NASJ_dWQPeOAPgEbZTRbGHMOiS5B2tMzeRR0/edit#heading=h.o1b49rfssykx) but we should confirm the requirements in official Apple/Google docs.

1. App Store and Google Play maximum screenshots
2. What's New/App Description character limit

## Acceptability Criteria

Add a status check when there are changes to the fastlane folders to check:
- [ ] If number of images in the screenshot folders are <= maximum (8 for Android, 10 iOS)
- [ ] If character counts in What's New and app description files are <= the maximum

**Comment by lexicalninja** [comment]
@timwright12 you still want these checks in the CI?

**Comment by timwright12** [comment]
yeah, anything we can do to avoid a store rejected

**Comment by lexicalninja** [comment]
@timwright12 Can you or someone else get me the character limits for the descriptions and whats new content?

**Comment by lexicalninja** [comment]
I need apple description and release notes char limits
i need google full description, short description, and whats new limits

**Comment by timwright12** [comment]
**iOS Character Limits**

Description: 4000
"What's new in this version": 4000
Keywords: 100

**Android Character Limits**

Release notes: 500
Release name: 50
Short description: 80
Full description: 4000

**Comment by lexicalninja** [comment]
@timwright12 do you want these to be required checks when these are updated or just status checks that dont prevent merging?

**Comment by timwright12** [comment]
Noting that we caught up in zoom about this. They will be status checks and also run on merge to develop where they can alert slack if something slips through the cracks
