### ISSUE TITLE
CU - remove null option from vama_rx_filter_sel

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9229]
## Proposed Change

Make sure this analytic isn't logging a null option for filter or sortBy.

## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by rbontrager** [comment]
Verified that vama_rx_filter_sel is not logging a null option in the simulator.  Nothing else can be tested so approved by QA.
