### ISSUE TITLE
BUG - Version Mismatch Between ChromeDriver and Installed Chrome Browser

### ISSUE THREAD

**Issue by IsraelleHub** [department-of-veterans-affairs/va-mobile-app#9237]
The error we are encountering is due to a version mismatch between the ChromeDriver and the installed Chrome browser. 
We need to install a ChromeDriver version that matches our Chrome browser version (126.0.6478.182) and specify its path when running the axe command.
[Error Link](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10177268188)

**Comment by TKDickson** [comment]
@IsraelleHub if you're not using the "closes #9237" keywords in your github PRs to take advantage of the integration that will do it for you automatically, you'll need to remember to loop back and close your tickets when your PRs merge.
