### ISSUE TITLE
BUG - sev-3 - Detox - Remove use case 1 testing for home & category screens

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9241]
## What happened?

Per the decision in #8548, we do *not* support use case 1 (popup blocking access) for availablity framework on the home and category screens (anything in the bottom nav bar).

We need to update our detox scripts to remove testing those cases, as they're currently throwing fails (false negatives?).

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
@TKDickson It looks like the Detox tests for availability framework aren't failing anymore. Here are the latest nightly E2E test runs:

Android: https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10295689854
iOS: https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10295741701

Not sure if this was fixed within the past week?

**Comment by TKDickson** [comment]
@theodur - the way that the AF script works, is that if it's being called on a branch that's got [X] changes, it will use the mapping in order to run AF for [screen X & other relevant screens] (`AFNavigationForIndividual` [in script](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/e2e/tests/AvailabilityFramework.e2e.ts#L18)). And if it's being called more generally, like the overnight builds, it just runs for a selected example of each of the screen template types (`AFNavigationNoIndividual` in [script](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/develop/VAMobile/e2e/tests/AvailabilityFramework.e2e.ts#L5)).

So this change is still needed, specifically for when the mapping kicks in to run it for home and category screens. LMK if that makes sense.

**Comment by TKDickson** [comment]
(None of this was clear in my original writeup, so - glad you asked!)

**Comment by cadibemma** [comment]
Detox currently isn't testing any AF usecases for `WG_Home` `WG_Benefit` `WG_Payment` `WG_Health`. @rbontrager will be creating another ticket to add detox testing for af usecase 2 and 3 for these screens. Closing ticket
