### ISSUE TITLE
BUG - Sev 3 - All - Cancel button on direct Deposit loading screen not functional, leads to weirdness

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#9245]
## What happened?

When attempting to update direct deposit information the "cancel" button is present on screen but is not responsive for cancelling out of the loading screen, tapping the button can create interesting screens for when the loading screen dismisses (see scteenshots)

## Specs:

- Device: ios and android
- OS: n/a
- User Account: judy.morrison
- Accessibility State:n/a

## Steps to Reproduce

- go to payments > direct deposit > Account
- update direct deposit information and tap "save"
- when the loading screen appears, rapid tap the "cancel" button like you are trying to answer a question on jeopardy 
- observe what awaits you when the screen dismisses

## Desired behavior

buttons displayed on screen should demonstrate functionality

## Acceptance Criteria

tbd

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact:  Low 
- Frequency:  Low 

- 3 - Low

## Screen shot(s) and additional information

<img width="1066" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b5ff284ad8fd39931017bd88794d1247aea93b0/IMG_0185.PNG" alt="IMG_0185.PNG" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTBrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d98e744f6c89ff452671aa9b7166b50eee03c1e6/Screenshot_20240731-164755.png" alt="Screenshot_20240731-164755.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
This is a duplicate with #5583 (a while back, we decided the best way to handle this was to implement an across-the-app "abort things when pressing cancel", which has not yet made it into code). Closing and adding label.
