### ISSUE TITLE
BUG - Sev 3 - All - All of our 'screen review' type in app review events will instantly request review and obstruct users

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9253]
## What happened?

Discovered that currently 50% of our in app review events will ask for users to leave a review before they've managed to fully review the screen they've navigated too, almost certainly resulting in an automatic dismissal and invalidating a good amount of our attempts for in-app-reviews.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Go Trigger an in app review event on any of our screen reviews:

AppealDetailsScreen
ClaimDetailsScreen
DisabilityRatingScreen
PastAppointmentsDetails
UpcomingAppointmentsDetails
PrescriptionDetails
RefillTrackingDetails
ContactInformationScreen
PersonalInformationScreen
PaymentDetailsScreen

And notice how it interrupts your screen view.

## Desired behavior / Acceptance Criteria
- Screenview events that contribute to the in-app review counter only increment the counter if they would NOT result in a review surfacing. In other words, screenview events should never result in a review surfacing to Veterans

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [x] Desired behavior is added
- [x] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [x] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by dumathane** [comment]
![image](https://github.com/user-attachments/assets/14717784-9379-4fb7-ac04-33f358a6d050)

**Comment by dumathane** [comment]
Blocked awaiting Ameet's decision on how to handle these.

**Comment by TKDickson** [comment]
Starting to assemble the screens that will need testing (there are more in the files changed of the PR, will need to add to this list). The best way to document this testing is (I think) to split out the testrail case where we cover in-app reviews into "will show" and "won't show" cases

AppealDetailsScreen
ClaimDetailsScreen
DisabilityRatingScreen
PastAppointmentsDetails
UpcomingAppointmentsDetails
PrescriptionDetails
RefillTrackingDetails
ContactInformationScreen
PersonalInformationScreen
PaymentDetailsScreen

**Comment by TKDickson** [comment]
Asked @cadibemma about the feasibility of adding a counter in the developer screens for testing this

**Comment by TKDickson** [comment]
(Will be writing [this case](https://dsvavsp.testrail.io/index.php?/cases/view/101728) (basically just a name right now), and paring down [this case](https://dsvavsp.testrail.io/index.php?/cases/view/12097&group_by=cases:section_id&group_id=3468&group_order=asc&display_deleted_cases=0))

**Comment by TKDickson** [comment]
Test cases edited per plan above, and [test run](https://dsvavsp.testrail.io/index.php?/runs/view/6005&group_by=cases:section_id&group_order=asc) created for this ticket
