### ISSUE TITLE
BUG - sev-2 - All - Throwing vama_error for "JSON Parse Error: Unexpected end of input" during login, maybe other places

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9266]
## What happened?

Our most common error message associated with the `vama_error` event (in the last 28 days) is "JSON Parse Error: Unexpected end of input". To give some context, we've logged that message 6.7 *million* times in the last 28 days.

Binny and I were attempting to reproduce a different bug, and saw that error logged in staging during login, super super early on -- here's where it fell (between getting a response for v2/user and the facilities call) the first time we saw it. _Note the console logging code he added in lines 119 and 192, if you want to see the same types of info as in the screenshot._ 

Binny thinks the most likely suspect (right now) is the `mobile/v0/user-/ogged-in` POST call.

<img width="1341" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW8yQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e21380ca9f63d368352c93db450aa68ab96292f/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Should figure out why we're throwing that error, and fix it.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High 

- 3 - Low
- 
Starting this as sev-2 because it (seemingly) has no impact on veterans, kind of like all of the JWT errors that were previously logging. If we find that this is impacting veteran login somehow, it would immediately catapult to a sev-1.

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by theodur** [comment]
The issue ended up being that the response from `v0/user-/logged-in` returns a `Content-Type` of `text/html` which causes an error when we try to parse it with `response.json` because it expects it to be a content-type of `application/json`.

Ideally, the API should be returning the response as JSON instead of text/html. My solution in the app guards against parsing non JSON responses since we can't ever be too sure the API is returning a JSON response, but we should still probably see if the BE team meant to intentionally return it as a text/html response, and whether the content-type can be changed

**Comment by TKDickson** [comment]
Confirmed that initial login with UN/PW, and subsequent login with biometrics, both still get you into the app, as expected with this change. Unable to test error response (analytics/firebase limitations in staging) but this should decrease that error being thrown in production.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
