### ISSUE TITLE
Android app version v2.34.0 released too soon

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9267]
On Aug 6, 2024 the [release process started for app version 2.34.0.](https://dsva.slack.com/archives/C018V2JCWRJ/p1722951513219699). Shortly after, [slack reported that the Android version of the app (v2.34.0) was live](https://dsva.slack.com/archives/C018V2JCWRJ/p1722953365422299).

Confirmed that 2.34.0 was live in the play console.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1EyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e586a5a568fb1f431ef525a2b52bfe7a688bf3c/Screenshot%202024-08-06%20at%2010.39.14%E2%80%AFAM.png" alt="Screenshot 2024-08-06 at 10.39.14 AM.png" />

We want to know why android went live so quickly when it shouldn't have happened for another week. Find out what time the workflow runs. Did we approve the release too yearly in the day on Tuesday or did something wrong happen in the system?

- [release thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1722428026986259)
- [release issue](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9232) - approved at 9:36am ET

UPDATE: The go live worksflow runs at 10am ET, the release was approved at 9:36am ET. Google approved it very quickly, so when go live ran, it released the app

**Action items:**

- [ ] Product and DevOps need to sync on this whether it is a technical solution (changing the time) or a people solution (agreeing not to approve before 10am ET)
- [ ] Change go_live time to 8am est instead of 10 am est

**Comment by bischoffa** [comment]
added it to the devops epic
