### ISSUE TITLE
Update event: Pair File Request load event to the click event

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9277]
Tie `vama_claim_file_request` to the click event `vama_claim_review` so that we can measure these together.

**Comment by wavelaurenrussell** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9277?planning-poker) with Zenhub @alexandec @dumathane @Sparowhawk

**Comment by rbontrager** [comment]
@Sparowhawk When running this on the simulator the 'vama_claim_file_request' logging statement does not show up when you select a claim in step 3 with file requests.  It incorrectly shows up on claims in step 3 without file requests (alongside the vama_claim_submit_ev if you have submit evidence on).  If you want to test this not on demo mode I made a claim with file requests on Arfan.

**Comment by Sparowhawk** [comment]
Fixed.

**Comment by rbontrager** [comment]
@Sparowhawk That's fixed but it brought up a couple more problems. 
- I'm now seeing both the vama_claim_submit_ev and vama_claim_file_request log when selecting a claim in step 3 with file requests.  
- I'm seeing vama_claim_submit_ev logged twice for files in step 3 without file requests.
- I'm not seeing vama_claim_file_request logging when you click vama_claim_review (which is what the description implies).
- Unrelated but when you click the submit evidence button you get a vama_review_prompt undefined.  Does this need to be removed so its not logging?
