### ISSUE TITLE
CU - Remove hideArrow code from AccordionCollapsible component

### ISSUE THREAD

**Issue by alexandec** [department-of-veterans-affairs/va-mobile-app#9281]
## Proposed Change

Remove the hideArrow prop and related code from the AccordionCollapsible component. This prop is only used by the `DEPRECATED_ClaimPhase` component, so when the DEPRECATED_ClaimPhase component is removed, the prop can also be removed. This should happen when we when remove the `claimPhaseExpansion` feature flag.

## Why Should We Prioritize?

Removing unused features keeps code simpler and easier to maintain.

## Coding Time Estimation

2
	
## Testing Considerations

Ensure no regressions in existing usage of AccordionCollapsible component.

## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by timwright12** [comment]
@alexandec this is ticket still blocked? Do you think it would be a "Good First Issue" for someone to work on?

**Comment by alexandec** [comment]
@timwright12 the deprecated component has been removed so this is no longer blocked. I removed the blocker. It's a good first issue.

**Comment by TKDickson** [comment]
Checking:
- [ ] Claim phase steps
- [ ] Appts not auth screen
- [ ] message chain in message details
- [ ] waygate info on developer screen

**Comment by TKDickson** [comment]
Login is broken in staging right now; blocks testing for message chains and appts not auth. Will check back on Monday.
