### ISSUE TITLE
BUG - sev-3 - All - Viewing message details should be incrementing the in-app review counter, but doesn't

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9289]
## What happened?

Viewing the details of a message (loading the message details screen) used to increment the in-app review counter. It no longer does. We don't test this often (read: almost never) so it could have disappeared anytime in the last.... couple of years.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

If on an emulator, can be iOS or Android. If on a physical device, must be Android.

Go to Home > Profile > Settings > Developer Screen and tap "reset in-app review counter"
Go to Health > Appointments and open any 7 appointments (upcoming or past).
See the in-app review popup.
Reset the in-app review counter again (see step 1)
Go to Health > Messages and open any 7 messages.
In-app review does not appear.

## Desired behavior

Should match the "view details increments the counter" behavior elsewhere in the app (appointments, claims, medications, etc), and trigger the counter on message details.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
Verified that the in app review popup is appearing after you open any 7 messages.  Approved by QA.
