### ISSUE TITLE
Create Status endpoint from LH service history and eligibility API

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#9296]
There is an existing integration for the API in vets-api but not for the endpoint itself. It'll require having LH expand the permissions on the existing key and then adding the endpoint to the service before making the mobile endpoint. This will not need a new CCG authorization key that requires adding to the manifests and devops repos since the existing one can be expanded upon. 

This will be used in place of military information service history for the app to determine if a user is a veteran. This won't be backwards compatible with previous app versions.

**Comment by jperk51** [comment]
Closing as a duplicate as 9410 which is blocked until LH updates either endpoint.
