### ISSUE TITLE
BUG - sev-2 - All - Better error handling when claims event.Timeline is null (aka don't crash)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9307]
## What happened?

We were able to quickly address #9298 by flipping a BE feature flag. However, we should loop back around to fix the root cause of the crash as well:

Could be from this inside ClaimPhase:
`const showClaimFileUploadBtn = needItemsFromVet(attributes) && !attributes.waiverSubmitted`
Following that down eventually leads to:
```
export const itemsNeedingAttentionFromVet = (events: ClaimEventData[]): ClaimEventData[] => {
  return events.filter(
    (event: ClaimEventData) =>
      event.status === FILE_REQUEST_STATUS.NEEDED &&
      event.type === FILE_REQUEST_TYPE.STILL_NEED_FROM_YOU &&
      !event.uploaded &&
      event.uploadsAllowed,
  )
}
```
If attributes.eventsTimeline was null, that could cause the error

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

I am not sure exactly what the desired behavior should be (throw an error? show what data we can, minus the stuff from the field coming back null?), so would need @ala-yna and @wavelaurenrussell to weigh in, likely among others.

## Acceptance Criteria

For QA. In Charles change eventTimeline to null and observe the app does not crash

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by ala-yna** [comment]
Asking @dumathane to take a look at this and see if it's still happening

**Comment by rbontrager** [comment]
Verified using Charles Proxy mocking that the claim no longer crashes when the event.Timeline is null.  Approved by QA
