### ISSUE TITLE
Draft Flagship documentation: Tile component

### ISSUE THREAD

**Issue by drjecker** [department-of-veterans-affairs/va-mobile-app#9316]
## Description 
We will need to create flagship documentation for the the Tile component. This component is owned by the design system team (they will write the documentation for the master).

When documenting we will also need to note each variation of the Tile component as used in VAHB. They are:
- Category tile
- Profile tile
- Announcement tile
- Home activity tile
 
Within the following sections in the [Documentation Template](https://docs.google.com/document/d/1DJoTdwXxUrjmCv8S9XwNvn4uVbd66jyE0XUwqzgZtc4/edit#heading=h.bhvl2fy62vsv) we would likely need to be specific to each variation:
- Examples (include separate embeds for each variation)
- Choosing between variations
- Instances of this component in production

## Acceptance Criteria
  

-  [x] Draft of documentation using [Documentation Template](https://docs.google.com/document/d/1DJoTdwXxUrjmCv8S9XwNvn4uVbd66jyE0XUwqzgZtc4/edit#heading=h.bhvl2fy62vsv) including variations list above 
-  [x] Share with @drjecker to review
-  [ ] Make any edits after review
-  [x] Questions or need help? Info on the doc site on how to draft [component documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/design/About/Contributing%20to%20the%20design%20system/writing-component-documentation/). Or feel free to ask @drjecker, Brea, or Jessica.

**Accessibility Requirements**
Nothing specific other than filling out Accessibility considerations in the template if applicable. 

## Notes & Open Questions
Once draft is done we'll need to:
- Make a ticket to add new component to the doc site using the [Documentation template in Github](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/new?assignees=&labels=component-documentation%2C+ux&template=common_component.md&title=Common+Component+Ticket%3A%5BInsert+name+of+component+here%5D)
-  Remove the existing [“Large nav button” documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Layout%20and%20Organization/LargeNavButton/).
- Remove the existing [“Nametag” documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Components/Layout%20and%20Organization/Nametag/).   

- Dev Notes: 
N/A

## Ticket Checklist

- [x] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by wavelaurenrussell** [comment]
Draft located here as [pdf]([Component_ Tile_Draft-09182024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXIyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd7ab275f9f9578c0bb4f177fd0f1a0808344934/Component_%20Tile_Draft-09182024.pdf)
) and on [GDrive](https://docs.google.com/document/d/1T42NUf9u20w6J-NRYXqkzUOqSw01TZVbB3eIEEK2hIk/edit#heading=h.vj9zwf7j22yt) for editing purposes.
