### ISSUE TITLE
Implement copy changes from 9299

### ISSUE THREAD

**Issue by cadibemma** [department-of-veterans-affairs/va-mobile-app#9321]
AC: 
- [x] Add CategoryLandingAlert component to display when one of the following pieces of data can't be displayed due to issue:
- Nametag
- Disability Rating
- or Compensation

For[ cases 8A, 8B, 9C](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1704381519703/cd6d78c5824a5fb0cc8b26597f0ad271072df8f2?wid=7-1704473698580):
<img width="539" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzFVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b2af435b1901313b841a8881c5c82adc725654a/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Copy for this edge case: We can't show all your information right now. Check back later.

**Comment by TKDickson** [comment]
Edited the relevant HSP cases in TestRail, and [here's the TestRail run](https://dsvavsp.testrail.io/index.php?/runs/view/5811&group_by=cases:section_id&group_order=asc)

**Comment by TKDickson** [comment]
If I have no information for some of the About You section, and errors for the rest of the About You section, we should show an error case -- instead, we are showing the empty section message

<img width="386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd0ad30e5d3425ae02b17378f0e4ebc3b8bdd365/image.png" alt="image.png" />

We had a similar logic miss previously for the Activity section, but that was resolved, so should be able to see how we're stacking errors/boxes there and do that here too.

**Comment by htcollier** [comment]
Added screen shot for expected error message treatment in ticket description.
@TKDickson is also correct that the bold red error treatment should display instead of the black empty section message if both are present in the section.

**Comment by TKDickson** [comment]
When the APIs for the About You section are a mix of error & no data (screenshot below), or a mix of maintenance window + no data, we're displaying the desired message now.
<img width="374" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f946b18969745ffc25fdd4b6235e33038af8c824/image.png" alt="image.png" />

Also completed all other testing [from test run](https://dsvavsp.testrail.io/index.php?/runs/view/5811&group_by=cases:section_id&group_order=asc) and confirmed the new error is read out appropriately by screenreader.

**Comment by TKDickson** [comment]
Doesn't require further testing in develop; closing
