### ISSUE TITLE
QART - rotation prep review (Tom)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9323]
ACs:

- [x]  Review the rotation prep documents from the QA in the area you're going into (documentation created in ticket #9217)
- [x]  Make your own list of what you'll need to successfully rotate into that area (shadow meetings for X period of time? official handoff meeting? X amount of time set aside to walk through the app in that area? etc)
- [x]  Create a ticket for yourself, which would be pulled in on Sprint 107 (9/25 - 10/8), that lists out that work & is pointed appropriately

**Comment by DJUltraTom** [comment]
for success on team transfer:
- 1:1 with PM
  - Discuss communication styles
  - Discuss team events and make sure they appear on my calendar
-   shadow meetings for one sprint.

**Comment by DJUltraTom** [comment]
https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9435
Created the above ticket with my "To-Do" list for rotation preparation

**Comment by DJUltraTom** [comment]
amended the above ticket with an additional QA knowledge transfer meeting with the outgoing QA

**Comment by DJUltraTom** [comment]
closing ticket
