### ISSUE TITLE
QART - rotation prep review (Rachael)

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9324]
ACs:

- [x]  Review the rotation prep documents from the QA in the area you're going into (documentation created in ticket #9219)
- [x]  Make your own list of what you'll need to successfully rotate into that area (shadow meetings for X period of time? official handoff meeting? X amount of time set aside to walk through the app in that area? etc)
- [ ]  Create a ticket for yourself, which would be pulled in on Sprint 107 (9/25 - 10/8), that lists out that work & is pointed appropriately

**Comment by rbontrager** [comment]
Ticket is done and can be found [here](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9483)
