### ISSUE TITLE
Onboarding: Fake Alex Smith

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9343]
### Full Name

Fake Alex Smith

### GitHub Username

@fake-alex-smith

### VA Email Address

Fake.Alex.Smith1@va.gov

### Process Documentation

- [ ] Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [ ] Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
- [ ] Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
- [ ] Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
- [ ] Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)

### System Access

- [ ] App store connect (VA Mobile will provide)
- [ ] Firebase (VA Mobile will provide)
- [ ] Write access to applicable repositories (VA Mobile will provide)
- [ ] Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

### Engineering-specific documentation

- [ ] Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
- [ ] Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
- [ ] Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
- [ ] Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
- [ ] Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
- [ ] Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
- [ ] Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
- [ ] Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
- [ ] Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
- [ ] Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
- [ ] Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
- [ ] Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
- [ ] Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)

**Comment by DJUltraTom** [comment]
for A11y information I would also include:
https://www.magentaa11y.com/
https://developer.apple.com/design/human-interface-guidelines/accessibility
https://developer.android.com/guide/topics/ui/accessibility

Thie HIG and Android A11y guide were required reading when I started in mobile, Magentaa11y and WCAG are great additional resources that should inform design and development.

**Comment by DJUltraTom** [comment]
In the linked "release overview" document, there is a "RACI" table that could use clarity for people who have never used, or encountered the term RACI or the table before.

in the "Product manager" section of the "Release overview" document the links for both of the following lead to 404 pages:
- Call Center Process Doc 
- Whats New Content Process Doc

**Comment by DJUltraTom** [comment]
release policies:
"document everything" links to a 404 page
"Test account needs" document has a list of test users that feels incomplete and slightly out of place in this section.
Typos on page "insturction". "Mist" instead of "Misty" and likely more taht didn't jump out with a high level once over.

**Comment by timwright12** [comment]
updated links for:

- Call Center Process Doc
- Whats New Content Process Doc

**Comment by timwright12** [comment]
Fixed typos

**Comment by DJUltraTom** [comment]
not likely anything we can fix,and very possibly a "Tom computer" issue but every time I launch the "how authentication works in the app" page, I need to reload the page a second time as it creates some interesting, yet unhelpful designs of the diagrams, a "not so bad" example below: 
<img width="1468" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJFQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c6db0698db000dca319cae9fcd4d6efd3effbc0/Screenshot%202024-08-23%20at%201.12.40%E2%80%AFPM.png" alt="Screenshot 2024-08-23 at 1.12.40 PM.png" />

**Comment by DJUltraTom** [comment]
All the rest of the above onboarding links look good

**Comment by DJUltraTom** [comment]
if the onboardee (lets make that a word) will need access to Testrail or other QA tools we may want to also include a link to: https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Resources

**Comment by timwright12** [comment]
I don't think they need access to TestRail unless you all (QART) want them to assemble test plans

**Comment by timwright12** [comment]
@DJUltraTom I see that auth documentation bug as well. I'll file a ticket.

Closing this one out, I think we're good
