### ISSUE TITLE
BUG - sev 3- all - Misleading screenreader recitation on Claim details (Active Claim) link focus

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9344]
## Specs:

- Device: All
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Using a screenreader, navigate to the Claim Details screen for an Active Claim. Tab to the link [Find out why we sometimes combine claims], and complete the flow. You will see that once the panel is launched, the same "Find out..." copy is reiterated. This can be misleading for a screenreader user, as they have already opted to "Find out", and then the title is repeated.

## Desired behavior

Update the header for the screenreader to just recite: “Why we sometimes combine claims”.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXBVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b1f9d9ea36b1e739f40d48308a7f9a3ce1c13c0/IMG_0014.PNG" alt="screenshot of the find out why we sometimes combine claims full panel" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by wavelaurenrussell** [comment]
Not launch-blockig

**Comment by Sparowhawk** [comment]
per standup on the large panel remove the action words "Learn" and "Find out" from the header copy

**Comment by Sparowhawk** [comment]
Misty Milliron-Grant
  Just now
@laurenrussell
Link: Find out why we sometimes combine claims
Large panel: Why we sometimes combine claims
Link: Learn what to do if you disagree with our decision
Large panel: What to do if you disagree with our decision

**Comment by rbontrager** [comment]
@Sparowhawk I don't know why the automatic process didn't run but you need to change the detox tests to account for the content changes.

**Comment by rbontrager** [comment]
Detox tests are passing for android [here ](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10811849422 )and ios [here](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/10810899145).  This was approved by Chris/Brea before I sent it back for detox changes so I'm closing this ticket.
