### ISSUE TITLE
BUG - sev 3- all - Misleading screenreader recitation on Accordion Collapse focus

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9346]
## What happened?

When testing the changes with a screnreader, we discovered some confusing/ misleading recitations that we want to clean up. 

## Specs:

- Device: All
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Using a screenreader, navigate to the Claim Details screen for any claim. Tab to a collapsed accordion. Here, it is unclear whether the accordion is expanded or collapsed.
## Desired behavior

Accessibility recommendation is to update SR text on Accordion Collapse to recite: “expand to review more details”.
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUJVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea9d3306eba4898528298fdb795c30dcf3de3088/RPReplay_Final1723567485.mov)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by wavelaurenrussell** [comment]
Not launch blocking. Slated for next sprint.

**Comment by brea11y** [comment]
@alexandec – Is this ready for review?

**Comment by alexandec** [comment]
@brea11y yep!

**Comment by brea11y** [comment]
Reviewed with iOS and Android. Screenreaders read out as expected. No additional updated and/or edits needed on my end.

**Comment by alexandec** [comment]
@brea11y thanks. @rbontrager is there any additional QA needed here?

**Comment by TKDickson** [comment]
No further testing needed in develop; closing
