### ISSUE TITLE
BUG - sev 3- all - Scroll position interaction is off

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9347]
## What happened?

When tapping the link on a scrolled screen and the large panel launches, the scroll position snaps back to the top of the screen. 

## Specs:

- Device: All
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

On Claim Details, scroll to a claim and tap the link copy. When the panel is launched, you'll notice the screen goes back to the top.
## Desired behavior

Maintain scroll position when the panel is launched
## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

https://github.com/user-attachments/assets/dacb95b9-d646-4b0d-b946-fef40c3ee67b

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by alexandec** [comment]
This bug also occurs when switching to the Files tab, then back to the Status tab. We'll need to rework the autoscroll functionality a bit. I'm increasing the estimate accordingly.

**Comment by rbontrager** [comment]
Verified that the claims details page no longer scrolls after opening the 'Find out why we sometimes combine claims' panel.  Approved by QA.
