### ISSUE TITLE
BUG - sev 3- all - Screenreader reciting 4 of X claims is unclear alongside reciting the step info

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9350]
## What happened?

During Accessibility QA, we found that on the Claims list, the screenreader announces which claim the user is on within the list. This is good, but with the addition of step X of X info, we discovered that it may be confusing so we want to add more insight.
## Specs:

- Device: All
- OS: All
- User Account:
- Accessibility State: VoiceOver / Talkback

## Steps to Reproduce

Using a screenreader, navigate to the Claims history list. When traversing the list, listen for the callout of the claim's position within the entire list (in the attached video, its "4 of 42")
## Desired behavior

We want to add [active/closed] to the overall list counter for screenreader users, context would change depending on whether it is an Active or Closed claim. 
Example: 

"...4 of 42 [active/closed] Claims"

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

https://github.com/user-attachments/assets/5bad2838-5c0d-4445-bf14-92fca308d087

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
No further testing needed in develop; closing
