### ISSUE TITLE
CU - Set Default Feature Flag for ClaimPhaseExpansion to True

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9358]
## Proposed Change

Turn on Claim Phase Expansion in develop.

## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by rbontrager** [comment]
Verified that the ClaimPhaseExpansion is set to true and all the new claims work is showing on develop.
