### ISSUE TITLE
Discovery: Organize Screenshots in UX Inspiration FigJam for Onboarding, a11y review of screenshots

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#9363]
## Description 
- [x] Organize the screenshots into smaller subgroups (i.e. accessibility settings, first-time onboarding flow, etc.) within the higher level groups
- [x] Grab phase 1 and phase 3 screenshots of the apps that I currently use (i.e. Healow) and add them to [Comparative analysis board](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=201-760&t=pQGrl3FCKCOJGrt8-1)
- [x] Clearly identify what is accessible and what is not (include why if they are not) in UI mechanisms depicted on the [Design inspiration](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=201-1206&t=pQGrl3FCKCOJGrt8-1) board
- [x] Review the [Comparative Analysis goals document](https://docs.google.com/document/d/1to1WulA7SxB2vcCuhh5KhK27qnSxwVpal_XP7Dkdx80/edit) that Holly is putting together and add any thoughts (and resolve the comments)—especially around a11y

## Notes & Open Questions
- [Product brief](https://docs.google.com/document/d/1C9Gqt5GhDniOScfyheI9lhbLsWafAGBIrKBPovjjDpQ/edit)
- [Comparative Analysis goals document](https://docs.google.com/document/d/1to1WulA7SxB2vcCuhh5KhK27qnSxwVpal_XP7Dkdx80/edit) 
- [Comparative analysis board](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=201-760&t=pQGrl3FCKCOJGrt8-1)
-  [Design inspiration board](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=201-1206&t=pQGrl3FCKCOJGrt8-1)

**Comment by htcollier** [comment]
Go ahead & close - what you've got in here is great & fulfills the ACs of the ticket.
While collecting new screenshots for additional apps is part of what will be in the CA, it's outside the scope of this ticket.

**Comment by brea11y** [comment]
Perfect! Thank you so much! I'll continue to keep those phases in mind as I am exploring / experiencing other apps moving forward and if I see something that I think we should look at further (or add to the board), I'll create a new ticket and let you know that I am adding it to the FigJam.
