### ISSUE TITLE
Update Benefits Shipped File to reflect recent work

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9389]
### Ticket to update the Benefits shipped file Figma file to reflect the recent: 

- Disability Claims work
- Areas affected by changes to HSP (mainly just the screen header style)

**Comment by wavelaurenrussell** [comment]
Merge request created for @brea11y (Figma).

**Comment by brea11y** [comment]
@wavelaurenrussell – Just a heads up that I am reviewing it. There are a couple of glitchy things happening with the semantic tokens that I am trying to work through, but have pinged Jessica to see if she can help.

**Comment by wavelaurenrussell** [comment]
Merged. Closing.
