### ISSUE TITLE
BUG - Sev 3 - iOS - Personal information > Preferred name/gender loading screen cancel button does nothing

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#9397]
## What happened?
When updating preferred name or gender options, on the loading screens after updating information the "cancel" button can be tapped leading to action sheets that tapping the "delete" or "keep editing" buttons do nothing but dismiss the overlay.

## Specs:

- Device: ipad mini
- OS: iOS
- User Account: n/a
- Accessibility State: n/a

## Steps to Reproduce

navigate to Profile > Personal information 
select "gender" or  "preferred name" edit the information and submit
tap the cancel option while the loading screen is on
observe an overlay appears
do not tap it
observe the loading screen concludes and we are on the personal information page with the option overlay (see screenshot)

## Desired behavior

functional buttons for the win

## Acceptance Criteria

TBD

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact:  Low 
- Frequency:  Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))
<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEJoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--546878fd9e61a342fa150b816b8af7809c1c026e/IMG_0187.PNG" alt="IMG_0187.PNG" />

**Comment by TKDickson** [comment]
This is a duplicate with #5583  (a while back, we decided the best way to handle this was to implement an across-the-app "abort things when pressing cancel", which has not yet made it into code). Closing and adding label.
