### ISSUE TITLE
Upgrade VAOS access policy in vets-api 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9415]
Right now this policy doesn't really check anything relevant. Work with the appts team to determine what the maximum amount of easily accessed user data makes sense to check. The idea is that we should be using this policy to stop calls for any user we can preemptively KNOW the call to VAOS will fail. As an example, Jeff [suggested](https://dsva.slack.com/archives/C018V2JCWRJ/p1723749169307449?thread_ts=1723479810.409989&cid=C018V2JCWRJ) we should check to see if the user has any facilities on record.

ACs
- [ ] Update VAOS access policy to better preempt calls we know will fail (or maybe return nothing for a user)
- [ ] Update specs and unit tests as necessary 
- [ ] Update docs if needed

**Comment by aherzberg** [comment]
no increase in error rates in prod.
