### ISSUE TITLE
Update Push Notifications Settings Screen

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#9423]
AC:
- Update screen content on the **existing states** of the Push Notifications Settings Screen: 
  -  **Opted in** version (with toggles):
     -  Remove bold subheader text "Personalized notifications"
     -  Update description body text to match [Figma file: Notifications - opted in](https://www.figma.com/design/L702ULyDKZbO2WBIHdJbyX/Global-Features-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=1458-8830&t=Nc59ChwSNMcwYqp4-4)
     -  Add a link, with the copy in the Figma file that links users to the email and text notifications management page on va.gov [https://va.gov/profile/notifications]
     - Modify tiny text to match Figma file
  - **Opted out** version: 
     - Update alert style to reflect the design in this [Figma file: Notifications - opted out](https://www.figma.com/design/L702ULyDKZbO2WBIHdJbyX/Global-Features-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=1458-8681&t=zrNvbPgATxvcNWYh-0)
       - Remove bold subheader text ('Turn on push notifications') from alert
       - Update description body text & button copy in alert to match Figma file
     -  Add a link below alert, with the copy in the Figma file that links users to the email and text notifications management page on va.gov [https://va.gov/profile/notifications]
     -  Modify tiny text to match Figma file

(New state for neither opted in or out is created on ticket #9265)

**Comment by TKDickson** [comment]
Still awaiting test plan review; added that ticket as a formal blocker. Will ping on this at the QA sync today.

**Comment by TKDickson** [comment]
Test plan review complete, so this is unblocked. [Link to TestRail run.](https://dsvavsp.testrail.io/index.php?/runs/view/5865&group_by=cases:section_id&group_order=asc)

**Comment by TKDickson** [comment]
"We;ll send these notifications to your device" is announcing a role of heading. (I'm guessing because you modified the subheading that used to be there, and forgot to remove the heading role from the box or whatever) But it should not have a heading role, according to the accessibility annotation on the design:
<img width="635" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUs0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a65b7109d949722ae15a976e80f8aa4273ff314b/image.png" alt="image.png" />

**Comment by TKDickson** [comment]
Just this one change - everything else is tested and good to go. Sending back to Eng.

**Comment by TKDickson** [comment]
Heading announcement issue from above is fixed with the latest build, and the detox changes for this screen are in place too. Good to go.

**Comment by TKDickson** [comment]
Not testing further in develop; closing
