### ISSUE TITLE
QA: Test Plan for Notifications opt-in

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9425]
## Objective 

The purpose of this ticket is to document the test plan for   
* The UI and flow changes for push notifications opt-in

Important note: right now, for upgrading users, it's not known exactly what logic will be used to display the carousel + new opt-in screen. Cases will be written *as if* shown to all users regardless of entry point (both platforms, all login methods, inclusive of users entering via push notifications). If the logic changes from that, during implementation discussions, cases will need to be rewritten.

## Reference Material:
  

- linked to epic, which includes implementation tickets (with - critically - link to [Figma](https://www.figma.com/design/L702ULyDKZbO2WBIHdJbyX/Global-Features-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=1458-8681&t=zrNvbPgATxvcNWYh-0) files)

## Known test data:
  

- will not need special users (all users can be eligible/happens in onboarding)

**Epic(s)**
  

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

  

## Acceptance Criteria
  

1. - [x]  Create test plan
2. - [x] Link to test case folder in TestRail
3. - [x] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes:

**Comment by TKDickson** [comment]
JK moving this back out of current sprint; RQ PN slice migration is ready for testing

**Comment by TKDickson** [comment]
Test plans ready for review:
* [Test run for screen changes](https://dsvavsp.testrail.io/index.php?/runs/view/5865&group_by=cases:section_id&group_order=asc) #9423
* [Test run for consent updates](https://dsvavsp.testrail.io/index.php?/runs/view/5866&group_by=cases:section_id&group_order=asc) #9265

These are the only two tickets for the epic, but the screen changes could get released independently if finished & ready before consent updates, hence the separate test runs (and the 'middle state' for onboarding in the screen updates test run)

**Comment by DJUltraTom** [comment]
@TKDickson 
Step 8 on [Notifications Opt-in (new)](https://dsvavsp.testrail.io/index.php?/runs/view/5866&group_by=cases:section_id&group_order=asc) feels strange to me, could we provide clarifying context in the the step?
Otherwise both set of tests look good to me.

**Comment by TKDickson** [comment]
Thanks @DJUltraTom - I added more context to Step 8, and also corrected a typo in step 4, so between those two hopefully it's easier to follow. Closing as complete!
