### ISSUE TITLE
Onboarding: Liz Townsend

### ISSUE THREAD

**Issue by mdewey** [department-of-veterans-affairs/va-mobile-app#9427]
### Full Name

Liz Townsend

### GitHub Username

liztownd

### VA Email Address

elizabeth.townsend4@va.gov

### Which team is this person on?

Travel Pay

### Who is the OCTO Product Owner for this person's team?

Mark Dewey

### What is the main Slack channel for this person's team primary team?

#beneficiary-travel-team

### Process Documentation

- [x] Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [x] Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
- [x] Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
- [x] Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
- [x] Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
- [x] Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)

### System Access

- [x] App store connect (VA Mobile will provide)
- [x] Firebase (VA Mobile will provide)
- [x] Write access to applicable repositories (VA Mobile will provide)
- [x] Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

### Engineering-specific documentation

- [x] Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
- [x] Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
- [x] Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
- [x] Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
- [x] Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
- [x] Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
- [x] Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
- [x] Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
- [x] Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
- [x] Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
- [x] Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
- [x] Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)

**Comment by timwright12** [comment]
Access to Appstore connect, firebase, and githuba have been granted

**Comment by timwright12** [comment]
All documentation has been confirmed by @liztownd and access has been granted. Please route future questions in to #va-mobile-app in slack.

Closing this issue.
