### ISSUE TITLE
QA - Create common resource for Charles Proxy map local files

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9437]
Charles Proxy is an important tool for mocking responses from APIs, especially when we are unable to create or update staging data to cover edge cases.

Right now each QA on the team has their own Charles Proxy methods, and local stash of files that they map to. We'd like to pool those - for instance, only the H&B QA now has the information on how to map claims calls for the new 8-step data. With a shared folder that we all pull from and update, we'd hopefully be able to easily share that information.

ACs:

- [x] Create a private folder to house Charles Proxy calls, probably with some subfolders (errors, [feature X], [feature Y], etc)
- [x] Create documentation about how to add files (ex: file format, naming convention, do the files include headers or not, etc) that can just live in the parent folder
- [x] Add your own local mapping files to the folder(s)
- [x] Share the information with the QA team

This ticket explicitly does not include 'badgering other QA to add their files' as an AC. Feel free to close the ticket once your individual work is complete.

**Comment by DJUltraTom** [comment]
started on this and the root folder is here:
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Quality%20Assurance%20and%20Testing/Charles%20Proxy

**Comment by DJUltraTom** [comment]
closing as A/C has been met
