### ISSUE TITLE
A11y: Add item count to Step timeline

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9448]
### Description
When reviewing the recent launch with BVA, they suggested to count each step on the timeline within the Claim Detail screen. We elected to add it as a screenreader-only hint to enhance the experience for blind / low vision users.

### ACs
Add a Screenreader-only hint to the Step number within the timeline. 

- Step 3 [of X]

Area in brackets is the SR hint.

**Comment by alexandec** [comment]
@brea11y @rbontrager any additional testing needed on this ticket?

**Comment by brea11y** [comment]
None needed on my end. This is great! Thank you!
