### ISSUE TITLE
FE: Create a template for multi-step tasks within the app

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9452]
### Description
In the Claims feature, we want to refine the top nav pattern used in the current iteration of the subtask so that it reflects the intended behavior defined for Flagship mobile. Currently, full screens cycle in with each advance and backtrack (use of the primary action or the back button) because they act as separate screens. 

### ACs
- [ ] Coordinate with/bring in the @liztownd work done on the top part of the Travel Pay subtask screen flow. She has a successful solution within this flow.
- [ ] Copy the behavior within Messages > Start new message
- [ ] “Freeze” top nav bar, so that screen content changes between screens, but top nav appears fixed. (See behavior on first screen on scroll)
- [ ] VQA with designer

### Additional resources

- [Slack thread describing what was done/where to reference](https://dsva.slack.com/archives/C018V2JCWRJ/p1727804121100549?thread_ts=1727802579.916389&cid=C018V2JCWRJ)
- An older [Slack thread](https://adhoc.slack.com/archives/C067S0FRP0C/p1724437843458609?thread_ts=1724432908.686789&cid=C067S0FRP0C) where @Sparowhawk assesses a potential fix to the issue.

**Comment by DJUltraTom** [comment]
according to @dumathane this is validated by successful validation of [9835](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9835)
which has been succesfully verified in an on demand build, QA approves this change

**Comment by DJUltraTom** [comment]
verified this is functioning as expected on the RC build, closing as deployed
