### ISSUE TITLE
BUG - Authentication Diagrams overlapping text

### ISSUE THREAD

**Issue by timwright12** [department-of-veterans-affairs/va-mobile-app#9486]
In the [authentication diagram](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams/) there's some text overlapping itself making the content unreadable.

<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUNWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eaf798bad870eab9508876c8b00bd9595ac58ec4/Screenshot%202024-08-28%20at%2012.39.38%E2%80%AFPM.png" alt="Auth diagram bug example of overlapping text" />

**Acceptance Criteria**

- [ ] Text doesn't overlap anymore in the diagram

**Comment by timwright12** [comment]
@jperk51 @StacyB2023 any way we can nudge this along? Seems small enough, maybe some shorter copy?

**Comment by jperk51** [comment]
@timwright12 I'm going to update this ticket or make a new one to update the all the auth stuff to be accurate to SIS since what we have now is around IAM. Between PTO and other, perceived, higher priority initiatives we hadn't pulled it in just yet, but yes we can get to it next sprint.

**Comment by timwright12** [comment]
Sounds good, thanks

**Comment by jperk51** [comment]
This will be removed as part of #9772
