### ISSUE TITLE
Discovery: Gap Analysis - current VAHB Mobile App User Journey & Onboarding

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#9498]
We want to identify gaps between the VAHB Mobile App User Journey & approach to onboarding and industry standards. We will use the content of this analysis to help inform the problem definition within the [Product Adoption Product Brief](https://docs.google.com/document/d/1C9Gqt5GhDniOScfyheI9lhbLsWafAGBIrKBPovjjDpQ/edit)

- Document VAHB Mobile App User Journey experience (including discovery entry points, App/Play store pages, first run & in-app onboarding and subsequent nudges)
- Note gaps using stickies in Figma

### ACs
- [x] Current VAHB Mobile App User Journey experience documented in Figma
- [x] Gaps noted using stickies async (based on a11y standards, best practices, heuristics)

**Comment by htcollier** [comment]
[VA: Health & Benefits Mobile App - Current App User Journey & Onboarding Experience](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=9-380&t=Yoa1eWnEoUdbpFbK-1) documented

**Comment by htcollier** [comment]
Added [gap analysis instructions to Figjam](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=293-2908&t=Yoa1eWnEoUdbpFbK-4)

**Comment by brea11y** [comment]
Updated the FigJam include accessibility considerations / analysis (the medium blue stickies).

**Comment by htcollier** [comment]
Ready for findings to be folded into [Product Adoption Product Brief](https://docs.google.com/document/d/1C9Gqt5GhDniOScfyheI9lhbLsWafAGBIrKBPovjjDpQ/edit)
