### ISSUE TITLE
Spike - investigate (and fix if possible) bug reporting for Release Candidate sign off ticket automation

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#9502]
As part of the release sign off ticket automation, a list of severe bugs is listed.
Currently this list is being populated with additional tasks, or "non-bug" tickets.

We should investigate and see why these are being included in the report. If this is an issue with changes to the automation script we should fix if possible, if it is an issue with how the tickets are tagged we should attempt to clarify what made them get picked up by the automated process.

<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZXQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca0b0d96c7df8886fbf226a6959e0f975f658c5a/Screenshot%202024-08-28%20at%202.58.59%E2%80%AFPM.png" alt="Screenshot 2024-08-28 at 2.58.59 PM.png" />
EG: in the above list the audits and updates should not be present and do not have "bug" tags

**Comment by timwright12** [comment]
@DJUltraTom I see the screenshot attached to the ticket is from [release 2.35.0](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9365). The release doesn't actually pull in "bugs" is pulls in issue with severity labels, so there are 3 listed on the ticket that are accessibility issues with the "SEV-2" label on them.

I think the decision point here is if accessibility issues are "bugs" - I would say, they are, but I think the team should make that call:

@DJUltraTom @TKDickson @rachelhanster @brea11y -- please chime in with thoughts.

**Comment by TKDickson** [comment]
Accessibility issues are bugs, and we've recently updated our severity definitions to make it even more clear how they should be prioritized. So #9104 and #9176, according to the definitions we've always used, should be in this list.

I think #9175 probably should have the severity label removed - an audit will likely uncover issues that will need the labels, but wouldn't have the severity label itself. @brea11y let me know if you disagree/if I've missed something.

**Comment by DJUltraTom** [comment]
@timwright12 thanks for the info. I think A11y issues can be bugs, while things like audits aren't. 
Perhaps this is a good time to consider "Priority" tags (which had been discussed in the past) are a different scale than "Severity". I think the audits, tasks of adding focus styling and are important and warrant having their priorities known to keep up the visibility but may not want to be surfaced and categorized in the same way that bugs are.
For the current release I manually removed any non-bugs from the reporting when updating the notes.
