### ISSUE TITLE
BUG - Sev 3 - All - With bad military history data the user gets an empty box on home screen for nametag

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9506]
## What happened?

<img src="https://github.com/user-attachments/assets/67a1f9f6-be0e-4224-9eb4-6a2e44f58314" width="48%" />&nbsp;&nbsp;

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce

Alter military history info on the fly to have service history Z and branch "".

## Desired behavior

Not have bad blank boxes.

## Acceptance Criteria

Cant create a bad black box with no data.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
For a veteran with a single period of service, in the mobile/v0/military-service-history return, if the branchOfService or endDate fields are empty, we will not show the nametag component. (Nonsense data in the branchOfService field, such as "TKD made up data", will still display but not be mapped to a specific branch of service icon, so will not display an image)

For a veteran with multiple periods of service, the nametag component will not display if the branchOfService field is empty for the most recent branch of service. Additionally, if any of the endDate fields are empty, the nametag component will display, with the most recent branch of service that has **both** end date + branch of service name. If there is no branch of service that has both end date and branch name, then the component will not display. (so for example, if a veteran has two periods of service, one without a branch name and the other without an end date, the nametag component will not display.)
*

**Comment by TKDickson** [comment]
Doesn't require further testing in develop, closing
