### ISSUE TITLE
BUG - sev 3 - android - Charles proxy no longer working with android

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#9521]
## What happened?

We used to be able to view network traffic with charles proxy, something changed (possibly with firebase 8/22 update?) and we are no longer able to see app traffic via charles or able to sign in once proxied

## Specs:

- Device: android
- OS: n/a
- User Account: n/a
- Accessibility State: n/a

## Steps to Reproduce

Connect to charles proxy with the app in a signed in state but force quit in the background
launch the app
observe no traffic appears through charles
observe error state on the device

## Desired behavior

We should be able to see network traffic

## Acceptance Criteria

TBD

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Screen shot(s) and additional information

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffc6de8c26530fc99bc679308152cabebb80af27/Screenshot_20240830-125719.png" alt="Screenshot_20240830-125719.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU9oQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ec4d581ac1bf3233951c897b1eb5f2370a04c00/Screenshot_20240830-130147.png" alt="Screenshot_20240830-130147.png" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5d1500e609ba470d8ae5452569b31627ddbabb3/Screenshot_20240830-172651.png" alt="Screenshot_20240830-172651.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b974e6d785ef7477fad99f2adfadefaa0330adb2/Screenshot_20240830-172806.png" alt="Screenshot_20240830-172806.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWFoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f675bfde8347be06dff1ec3feffc6d64b9a8d835/Screenshot_20240830-172724.png" alt="Screenshot_20240830-172724.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca3283f310b2598f85fe473421790f2beebe08ee/Screenshot_20240830-172736.png" alt="Screenshot_20240830-172736.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWloQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--452f90f3f60c0ead5532e47189d9d90b7fe26a28/Screenshot_20240830-172831.png" alt="Screenshot_20240830-172831.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1oQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a32827863d029845904bf9426d2546aef91d3ae3/Screenshot_20240830-172756.png" alt="Screenshot_20240830-172756.png" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXFoQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be8b4b811549a53f707dcef29cde4560e4ab9a11/Screenshot_20240830-172819.png" alt="Screenshot_20240830-172819.png" />

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by timwright12** [comment]
@TKDickson @DJUltraTom should this be a "bug" with a severity label? Those usually get rolled up into the release issue don't they?

**Comment by TKDickson** [comment]
@timwright12 we don't have a consistent way we label "bugs that don't impact veterans". Typically I've included the bug label, but not a severity label. Either way, only sev-2 and sev-1 issues get rolled up into the release report, so this one wouldn't be included.

**Comment by timwright12** [comment]
@TKDickson ok, might be something we need to put some thought around as the team grows

**Comment by DJUltraTom** [comment]
unable to repro on both QA build and an on demand branch build . 
closing as "cannot repro"
