### ISSUE TITLE
Move Appointments type and modality logic to appts service level 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9546]
Work with Simi to figure out how best to mimic what [web does on the FE](https://github.com/department-of-veterans-affairs/va.gov-team/issues/90109) and what we do in our adapter so that appt type and modality mapping logic can live at the service level. Note: The logic here is different enough that it might be decided we should keep these separate. 

ACs:
- [ ] If possible migrate type and modality mapping logic to the appt service level 
- [ ] Update mobile code to no longer do it's own mapping 
- [ ] Create unit tests for new type and modality class(es)

**Comment by Tonksthebear** [comment]
Blocking for now because Simi is out of office
