### ISSUE TITLE
Zero Silent Failures Evidence Upload Investigation

### ISSUE THREAD

**Issue by CorySohrakoffUSDS** [department-of-veterans-affairs/va-mobile-app#9565]
### 1.) Requestor's Name

Cory Sohrakoff

### 2.) Requestor's Email

cory.sohrakoff@va.gov

### 3.) VA Team

Benefits Portfolio

### 4.) What is the name of the project or change?

Evidence Upload Failures Investigation

### 5.) Please explain what problem you are trying to solve.

As Requested by Don:

---

### What UI screens and actions are triggering the API in question?

The "File requests" / "More information needed" screen where the user may upload a file or photos.

### What are the exact EVSS and/or LH API endpoints in question?

- EVSS Document Service
- LH Benefits Documents

### What mobile API endpoints call the EVSS/LH APIs in question (if you know this)?

- `/v0/claim/{id}/documents`
- `/v0/claim/{id}/documents/multi-image`

### What remediation is being requested?

Evidence uploaded via the claim status tool on VA.gov was handled off to the EVSS Document Service in a Sidekiq (background) job. It was discovered that upload failures and Sidekiq job exhaustion was not handled correctly, causing evidence uploads to silent fail. That is they failed without Veteran awareness that anything had gone wrong, resulting in claims potentially being decided without all of the evidence a Veteran submitted. (A similar situation can also occur if using LH Benefits Documents API without subsequently polling for the final upload status.)

The ask to investigate whether a similar situation has occurred within the mobile app. Are evidence uploads performed synchronously or asynchronously? In either case, are upload errors presented to the user, or could they fail silently without the user knowing?

If any silent failures could have occurred, we would need a list of them so that remediation (whatever that may be) could be coordinated with other teams who have similar unhandled evidence upload failures. This is part of a larger OCTO effort being tracked in #zero-silent-failures. See [channel canvas](https://dsva.slack.com/canvas/C07KTTFP308) for more details.

### An engineering contact for this remediation

- @va-albers (engineering lead for zero silent failures effort)
- @CorySohrakoffUSDS (claim status tool engineering lead)

### 6.) Please explain how this change would work.

Does not necessarily require changes if the mobile application is not a source of silent failures.

### 7.) Features Impacted

Claims history, file requests

### 8.) Please include all relevant documentation links for this change request.

Cross-team coordination and documentation in Slack channel/canvas [here](https://dsva.slack.com/archives/C07KTTFP308).

### 9.) Does your team have all the necessary materials (documents, designs, processes, analytics, APIs, etc) in place for Mobile to make these changes right now?

Yes

### 10.) Has this change been discussed with VAHB POs (Ryan or Don)?

Don - Yes

### 11.) Has this change been agreed upon by all impacted VA Stakeholders?

Yes

### 12.) What is your ideal due date for this change request?

ASAP

**Comment by DonMcCaugheyUSDS** [comment]
Thank you @CorySohrakoffUSDS for gathering all the details.

@timwright12 @jperk51 Would you please review this and flag any additional info we need.

**Comment by DonMcCaugheyUSDS** [comment]
Also for reference, there is a [related Slack thread](https://dsva.slack.com/archives/C07KTTFP308/p1725900692439199).

**Comment by jperk51** [comment]
@CorySohrakoffUSDS For EVSS, We use the exact same [upload logic](https://github.com/department-of-veterans-affairs/vets-api/blob/e2f9f75eba18006b2dff74d04473a0937c86aa8b/app/sidekiq/evss/document_upload.rb#L4) as va.gov so whatever was/is happening for them is also true for the mobile app. Afaik, up until recently there was no tracking of failures at all then the job was [wrapped with logging ](https://github.com/department-of-veterans-affairs/vets-api/blob/e2f9f75eba18006b2dff74d04473a0937c86aa8b/app/sidekiq/evss/document_upload.rb#L13) for datadog, but still I don't think that notifies the user of the failures unless EVSS sends a separate notification (email or something) to the user.

**Comment by jperk51** [comment]
For LH, we also use the same [upload service](https://github.com/department-of-veterans-affairs/vets-api/blob/e2f9f75eba18006b2dff74d04473a0937c86aa8b/lib/lighthouse/benefits_documents/service.rb), but how exactly that should work is currently in flux. There is an [async and sync version](https://github.com/department-of-veterans-affairs/vets-api/blob/e2f9f75eba18006b2dff74d04473a0937c86aa8b/lib/lighthouse/benefits_documents/service.rb#L72) of the upload process set up. In the async logic there is datadog logging, but again it doesn't look like there's anything to notify the user unless the upstream service is handling that somehow, but last I heard there is a desire, for the exact reason we are discussing here, to switch to making doc upload a sync operation so the user knows for sure if the doc got uploaded. Switching between sync and async is currently set up behind a feature flag so on the LH implementation we can swap from one to the other very easily.

**Comment by CorySohrakoffUSDS** [comment]
Thanks for confirming. The other async job that VA.gov Claim Status Tool uses is [EVSS::RequestDecision](https://github.com/department-of-veterans-affairs/vets-api/blob/master/app/sidekiq/evss/request_decision.rb). Do you happen to known if mobile does also?

**Comment by jperk51** [comment]
Are we good to close this issue? @DonMcCaugheyUSDS @CorySohrakoffUSDS
