### ISSUE TITLE
Document team schema standards

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9568]
We need to document architectural decisions that have been made to ensure that outside and future developers understand that certain standards are expected and why they matter.

AC:
- we use JSON:API and all responses must be JSON:API compliant. Our specs will enforce this, but there are some legacy endpoints that are not JSON:API. We can't fix them at this time without breaking old endpoints but should fix them when possible.
- we use DRY models to ensure data consistency even if upstream data changes
- we use serializers and models to ensure that the same attributes are present in all responses, as well as to create properly formatted JSON:API

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9568?planning-poker) with Zenhub @aherzberg @kpethtel @Tonksthebear
