### ISSUE TITLE
Onboarding: Juan Castillo

### ISSUE THREAD

**Issue by anita-halici** [department-of-veterans-affairs/va-mobile-app#9575]
### Full Name

Juan Castillo

### GitHub Username

juancstlm-a6

### VA Email Address

juan.castillomoreno@va.gov

### Which team is this person on?

Unified Appointments Experience

### Who is the OCTO Product Owner for this person's team?

Kristen Mcconnell

### What is the main Slack channel for this person's team primary team?

#unified-appointment-experience

### Process Documentation

- [x] Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [x] Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
- [x] Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
- [x] Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
- [x] Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
- [x] Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)

### System Access

- [x] App store connect (VA Mobile will provide)
- [x] Firebase (VA Mobile will provide)
- [x] Write access to applicable repositories (VA Mobile will provide)
- [x] Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

### Engineering-specific documentation

- [x] Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
- [x] Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
- [x] Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
- [x] Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
- [x] Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
- [x] Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
- [x] Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
- [x] Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
- [x] Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
- [x] Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
- [x] Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
- [x] Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)
- [x] Information about [accessing Demo Mode](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Mobile%20Demo%20Mode)

**Comment by timwright12** [comment]
@anita-halici Waiting for @juancstlm-a6 to be added into the VA Github Org before I can start assigning access. You'll need a [general/platform onboarding issue](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=&labels=onboarding&projects=&template=VA.govApplicationTeamOnboarding.md&title=VA+Team+Onboarding+-+%5Bname%5D) completed for that.

**Comment by juancstlm-a6** [comment]
@timwright12 I have now been added to the VA Github Org

**Comment by timwright12** [comment]
@juancstlm-a6 Gave you access to iOS (Appstore connect), Android (Firebase), and the va-mobile-app repo. Will get you into the slack channel once your invite into Slack is processed.

In the meantime, please read through all the documentation listed on this ticket and check them off once you do so.

**Comment by timwright12** [comment]
@juancstlm-a6 Going to close out this ticket since all the docs are checked off and you've confirmed that you have the app up and running locally. Please reach out in Slack with any questions.

Welcome!!
