### ISSUE TITLE
CU - Add testID to the components affected by the testIDProps removal

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9578]
## Proposed Change

Add testIDs to the components affected by the testIDProps removal.

**Comment by TKDickson** [comment]
[Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11034432210/job/30648044966) and [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11034435944/job/30648065457) runs, with a few fails not-caused-by these changes. I'll re-run those scripts anyways.

**Comment by TKDickson** [comment]
Running [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11038268487) again, with develop merged in (which should fix the broken home screen test)

**Comment by TKDickson** [comment]
All cases passed; approved
