### ISSUE TITLE
Investigate what letter types are available within the mobile app

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9584]
As a part of the work needed for #9466, we want to identify what claim letter types are currently available within the mobile app.

A list of all possible claim letter types can be found linked [here](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9466).

**Comment by alexandec** [comment]
I think the question of what claim letter types are available in the mobile app is more of a BE question, see discussion here: https://dsva.slack.com/archives/C018V2JCWRJ/p1720030321910509

**Comment by rtwell** [comment]
@jstrothman 
If I am reading the [spreadsheet](https://dvagov.sharepoint.com/:x:/r/sites/vaabdvro/_layouts/15/Doc.aspx?sourcedoc=%7B266D54B5-B5DB-471F-84BF-21212761BB88%7D&file=CST%20-%20Letter%20Download%20Codes%20and%20names.xlsx&nav=MTVfe0YxNDdCOTY0LUZENUItNDZGQi1CQTNFLTQ1NzczOEI2MUVCMn0&action=default&mobileredirect=true) correctly, the following doctypes need to be added to mobile:

- 34 Correspondence
- 408 VA Examination Letter
- MAP-D Development Letter
- Subsequent Development Letter
- Final Attempt Letter
- General Records Request (Medical)
- General Records Request (Non-Medical)
- 5103

@ala-yna pending Julie's confirmation, we can close this and and refer to it in #9466

**Comment by jstrothman** [comment]
@rtwell Confirmed!
As described in #9466 -- I think we should use different display names to aid user recognition

**Comment by ala-yna** [comment]
Closing this ticket; added the findings to the epic [here](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9466#issuecomment-2371109301)
