### ISSUE TITLE
Turn off Submit Evidence flag and update app store what's new

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9587]
What's new content - We added general improvements and fixed a few bugs.

**Comment by rbontrager** [comment]
Verified that submit evidence has been turned off while the rest of the files flow still works as expected. Verified that the detox tests still work as expected.  Test cases run can be found [here](https://dsvavsp.testrail.io/index.php?/runs/view/5943&group_by=cases:section_id&group_order=asc). Approved by QA.
