### ISSUE TITLE
BUG - Sev-3 - All - Change links/phone numbers in alerts to vadsColorForegroundDefault gray

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9596]
## What happened?

Change links/phone numbers in alerts to vadsColorForegroundDefault gray.  The initial list of alerts changed can be found in this [ticket](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8467).  Alerts with phone numbers/links from that list are callHelpCenter, downtimeError, Waygates, Benefits screen < take photos > accessibility alert, appts cerner alert, prescriptions history we can't refill some of your prescriptions alert, prescriptions details alert on transferred prescriptions, SM cerner alert, no payments screen alert, no vaccine records alert, and no prescriptions alert

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by TKDickson** [comment]
Note on accessibility (because grey body text, and grey text for links, is not ideal from an accessibility perspective):

> This was definitely a "yes, but" accessibility call that we made since the ask was to align with VADS wherever possible. VADS uses blue links on all alert background colors (red, yellow, green, and blue). Although they do pass color contrast minimums (at a AA level), they don't have to account for dark mode. Since we do, we would have to use the blue vivid (bright, light blue) shade for our links in dark mode if we were going to align with them fully, which weren't passing on all background colors and/or against surrounding elements.
> We tried to do a 1:1 to choose those dark mode background colors for the alerts, but the links didn't pass all of the checks and the buttons clashed with the background. We opted for white buttons on the alerts in dark mode and updated the links to match so they would all pass contrast minimums. We did keep the same blue buttons in light mode that VADS uses, but I believe the links ended up being updated to the dark gray in light mode somewhere along the way (likely to align with the white links in dark mode).
> I remember all of these calls being super tricky to make. I'd say from an accessibility standpoint, we're fine. We're underlining the links, providing proper spacing for the touchpoints, ensuring the read out as links to screen reader users, including icons to help make it clear that they are links, etc. However, I think this really comes down to being a VADS issue and not being considerate of how their components made translate to dark mode. We'll likely see them revisit the alerts at some point since they are considering adding a dark mode for VA.gov.

**Comment by TKDickson** [comment]
Need to test light mode:
- [ ] callHelpCenter, 
- [ ] downtimeError, 
- [ ] Waygates, 
- [ ] Benefits screen < take photos > accessibility alert, 
- [ ] appts cerner alert, 
- [ ] prescriptions history we can't refill some of your prescriptions alert, 
- [ ] prescriptions details alert on transferred prescriptions, 
- [ ] SM cerner alert, 
- [ ] no payments screen alert, 
- [ ] no vaccine records alert, and 
- [ ] no prescriptions alert

And dark mode: 
- [ ] callHelpCenter, 
- [ ] downtimeError, 
- [ ] Waygates, 
- [ ] Benefits screen < take photos > accessibility alert, 
- [ ] appts cerner alert, 
- [ ] prescriptions history we can't refill some of your prescriptions alert, 
- [ ] prescriptions details alert on transferred prescriptions, 
- [ ] SM cerner alert, 
- [ ] no payments screen alert, 
- [ ] no vaccine records alert, and 
- [ ] no prescriptions alert

**Comment by TKDickson** [comment]
UI as it currently stands, just for posterity:
<img width="318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVlBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8805167449ac81f8f021a4588de1a9ebccff17c8/image.png" alt="image.png" /> <img width="318" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWdBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02d1f51e165edd458482bf17f15263e791d465c2/image.png" alt="image.png" />
