### ISSUE TITLE
BUG - SEV 3 - All - Implement changes to some OH copy

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9597]
## What happened?

This bug is in relation to [this external bug ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9214#issuecomment-2349082945) filed by Kristen McConnell. In that ticket, we determined that there was some confusing language in the Oracle Health alerts. This ticket is to implement these copy changes.

Notes: While the original bug ticket found issues with OH copy on Health and Appointments screens, we're going to use this opportunity to also tweak the copy for the Messages screen to better align between all 3. We will not make any changes to the Prescriptions screen at this time.

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Steps to Reproduce
This bug affects both users who are only registered at Oracle Health facilities as well as those who are registered at both OH and Vista facilities.

## Acceptance Criteria

- [ ] Health category screen - Copy at bottom of the screen **when applicable**
<img width="422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWJaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--93346695af36df2c1f0fb727efe7825a2e27909a/Screenshot%202024-09-16%20at%2011.19.51%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.19.51 AM.png" />
</BR>

- [ ] Health category screen - Copy in large panel (after tapping link) for **Oracle Health only users, no matter # of facilities**<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWpaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d4c7bd7c863a8006f4687256ea2f9326fe0b9b1/Screenshot%202024-09-16%20at%2011.20.34%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.20.34 AM.png" />
</BR>

- [ ] Health category screen - Copy in large panel (after tapping link) for **mixed users**<img width="472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXJaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a36e6b43c771ae5005fddc35b5e668dd0694924/Screenshot%202024-09-16%20at%2011.21.01%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.21.01 AM.png" />
</BR>

- [ ] Appointments feature screen - Alert copy for **Oracle Health only users, no matter # of facilities**<img width="484" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXZaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15d6679c8c242d0e58cc3f55cf9724d43b2d2635/Screenshot%202024-09-16%20at%2011.21.28%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.21.28 AM.png" />
</br>

- [ ] Appointments feature screen - Alert copy for **mixed users**<img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTNaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--788d87093760ab82e908dcab484d2c742ee499b1/Screenshot%202024-09-16%20at%2011.22.04%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.22.04 AM.png" />
</br>

- [ ] Messages feature screen - Alert copy for **Oracle Health only users, no matter # of facilities**<img width="472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9aQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3103a05bee70344c0201efa47c39fcd015ec1ca/Screenshot%202024-09-16%20at%2011.22.38%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.22.38 AM.png" />
</br>

- [ ] Messages feature screen - Alert copy for **mixed users**<img width="494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekhaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f3ee55cb708d014950a71272c19343e68d78570c/Screenshot%202024-09-16%20at%2011.23.27%E2%80%AFAM.png" alt="Screenshot 2024-09-16 at 11.23.27 AM.png" />
</br>

- [ ] Facility names in bulleted lists in these alerts are NOT bolded.

- [ ] Content/visual/a11y QA completed by Misty, Lauren, and Brea.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: Low 

- 3 - Low

## Additional information
- We currently separate out OH user scenarios by 3 categories: (1) user with only 1 OH facility, (2) user with >1 OH facility, and (3) user with mixed facilities (OH + Vista). With these screens, we will now just have 2 scenarios for copy variations: (1) user with only OH facilities (no matter the #) and (2) user with mixed facilities (OH and Vista)
- [Link to section of Figma with approved changes](https://www.figma.com/design/pTJ90KbVDoutPIbGjQ1y7o/%F0%9F%8F%96-Misty's-Sandbox?node-id=1427-101&t=5BeDD6Y0ZLd3eoiE-4)

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [x] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [x] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by mistymg** [comment]
Added notes in Additional Information section about moving from 3 OH user scenarios to 2 in case this affects e2e testing, etc.

**Comment by rbontrager** [comment]
@Sparowhawk You didn't update the wording at the bottom of the Health category screen to the first acceptance criteria.  The detox test will also need to be updated I believe.

**Comment by rbontrager** [comment]
Verified that the cerner wording on the health category screen, the appointments screen, and the messages screen match the acceptance criteria wording above for both mixed and Oracle Health only users (no matter # of facilities).  Approved by QA.
