### ISSUE TITLE
QA: Test Plan for SSO

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9604]
## Objective 

The purpose of this ticket is to document the test plan for 
#9286

## Reference Material:
  

- 

## Known test data:
  

- 

**Epic(s)**
  

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

  

## Acceptance Criteria
  

1. - [ ]  Create test plan
2. - [ ] Link to test case folder in TestRail
3. - [ ] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes:

**Comment by TKDickson** [comment]
[Test run for the first SSO ticket](https://dsvavsp.testrail.io/index.php?/runs/view/5948&group_by=cases:section_id&group_id=10253&group_order=asc) - but I'm hoping that I can use the basics case specifically for further SSO testing when we expand to more links in the app (once I've tested the entire framework more strenuously with this first round).

Two things of note:
- I've pulled in the login cases (for testing all credentials, and a variety of browsers) without re-writing them specifically for the SSO-in-webview purposes, because that seems like a waste of time/over-documentation to me. The testing there will be using XYZ credential/ABC browser, and making sure that the SSO login to the website in the webview still works seemlessly. If you disagree and think that they need to be re-written in order to be well-understood, let me know.
- Are there further edge cases that you can think of? Other places where we deal with session management, that I should make sure to test to confirm it plays nicely with SSO? (along the lines of the app-switching stuff in the basics case, or anything in the extras section) 


This is ready for test plan review.

**Comment by rbontrager** [comment]
@TKDickson Just a couple very minor suggestions (that do or do not need to be implemented). For point number 1 I don't think they need to be rewritten but it might be good to link the SSO cases to the login cases somehow (maybe in the preconditions?).  I feel like down the road the knowledge of you need to test SSO with the multiple browsers/credentials may be missed otherwise. And I can't think of any further edge cases atm.

**Comment by TKDickson** [comment]
Added a note to the preconditions section, with links - hopefully that accomplishes the cross-linking, without the need to maintain very similar cases, for us going forward. Closing this ticket as complete.
