### ISSUE TITLE
CU - Rollback LinkWithAnalytics Code behind a feature flag

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9616]
## Proposed Change

- Create a new feature flag to flip on if we do not notice a difference in crashing with the react-native update.
- Revert code in LinkWithAnalytics to pre-design-system component implementation behind said feature flag.
- Make sure any edits since the design system implementation took place are including in the rollback code.

## Why Should We Prioritize?

ASAP due to trying to alleviate crashing in production.

## Coding Time Estimation

2
	
## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by alexandec** [comment]
QA note: this change affects all links in the app, including message attachments. We'll want to test everything with the flag on and the flag off.

**Comment by TKDickson** [comment]
@alexandec what about [ClickToCallPhoneNumber](https://github.com/department-of-veterans-affairs/va-mobile-app/blob/chore/9616-rollback-link-with-analytics-component/VAMobile/src/components/ClickToCallPhoneNumber.tsx)?

**Comment by TKDickson** [comment]
With the feature flag off (aka still using the new LinkWithAnalytics component), links should behave as expected in all of these places:

- [ ] Attachments link in messaging (received messages)
- [ ] Attachments link in messaging (sent messages)
- [ ] Attachments link in messaging (draft messages)
- [ ] Add to calendar button for Claim Exam appt details
- [ ] Add to calendar button for Community Care appt details
- [ ] Add to calendar button for in-person VA appt details
- [ ] Add to calendar button for phone VA appt details
- [ ] Add to calendar button for ATLAS video appt details
- [ ] Add to calendar button for GFE video appt details
- [ ] Add to calendar button for at home video appt details
- [ ] Add to calendar button for at VA video appt details
- [ ] All links on the Veteran Status screen work *
- [ ] if Chris says yes, then will find and add links **

(then duplicate all cases for the 'feature flag on' list)

*Picked as part of a random selection of the updates to the ClickForActionLinkDeprecated component changes, which feeds straight into ClickToCallPhoneNumberDeprecated component
**Picked as representative for ClickToCallPhoneNumber component changes

**Comment by TKDickson** [comment]
Found #9653 during testing - confirmed via reproducing in earlier builds that it's not caused by this branch's changes.

**Comment by TKDickson** [comment]
Found #9655, also not caused by this branch

**Comment by TKDickson** [comment]
The fact that the demo system has all of these appt types prepped took this from a nearly-impossible testing task to quickly turn around, to nbd. This is good to go.
