### ISSUE TITLE
Merge VAOS policy usage in both VAOS and mobile controllers into one place.

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#9617]
With the exception of the recently added facilities check, VAOS and Mobile policy usage is identical. ATM, VAOS has FE logic to check for facilities but this should be moved to the backend to help with the effort to combine as much logic as possible. VAOS has a parent controller that has their policy logic, we can't inherit since we have different grandparent controllers so it should be moved into a concern where it can be shared.

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9617?planning-poker) with Zenhub @aherzberg @kpethtel @Tonksthebear
