### ISSUE TITLE
Add translations file to vets-api

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9621]
For the first step of the CMS project, we need to move the translations json file to the vets-api. That file should also be validated in Rspec. This validation will essentially act as a CI step to prevent editors from accidentally breaking the file while editing.

AC:
- translations file is copied from the mobile app to the vets-api
- add new tests to confirm that file:
  - is valid, parseable json
  - is in alphabetical order (to improve maintainability)
  - all variable interpolation braces are closed

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9621?planning-poker) with Zenhub @aherzberg @kpethtel @Tonksthebear
