### ISSUE TITLE
Create new endpoint for exposing translations json

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9622]
We need a new endpoint for serving translations json to the mobile app.

AC:
- translations json file is exposed via endpoint
- accept an optional timestamp query param. when the param is omitted or when the timestamp does not match the timestamp of the current translations file, send the file. when the timestamp matches the current file, send success with an empty body to avoid unnecessary load on the server.
- this probably does not need to be authenticated. confirm this.
- write specs
- API documentation

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9622?planning-poker) with Zenhub @aherzberg @kpethtel @Tonksthebear

**Comment by kpethtel** [comment]
Tested the following cases on staging:
- reques without query params – responds with file and content version header
- request with current version param that does not match the file – responds with file and content version header
- request with current version param that does match the file – responds with 204 no content
