### ISSUE TITLE
BUG - Sev-3 - All - Voiceover for the pagination button is saying <previous/next> page - link - <previous/next> page instead of just <previous/next> page - link

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9636]
## What happened?

Voiceover for pagination buttons is saying <previous/next> page - link - <previous/next> page instead of just <previous/next> page - link

## Specs:

- Device: any
- OS: any
- User Account:
- Accessibility State: Voiceover/talkback on

## Steps to Reproduce

-  log into an account with pagination occurring on one of the features
- navigate to feature with pagination navigation using talkback/voiceover
- observe the screenreader announcement of the navigation buttons (arrows)
-  
## Desired behavior

voice over should read the pagination arrows as <previous/next> page - link
## Acceptance Criteria

TBD

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency:  Low 

- 3 - Low

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by DJUltraTom** [comment]
updated ticket description, repro steps, "what should happen" and severity sections

**Comment by DJUltraTom** [comment]
Using an on demand builds on both android and iOS I verified the pagination buttons no longer announce twice.
QA approves this build.

**Comment by DJUltraTom** [comment]
verified this was in the RC build, closing
