### ISSUE TITLE
BUG - sev-2 - All - Message attachment loading no longer has a loading indicator

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9653]
## What happened?

When a user taps on a message attachment (to view the attachment), there is [no feedback that anything is loading/happening](https://drive.google.com/file/d/19TM9T4uAWZpHIUQOwXE2zNbUebr2GWDp/view?usp=sharing), which is a WGAG violation and usability problem. _It also allows users to spam-tap the link (if it's taking longer/they're frustrated) and open the attachment more than once, see the video. That's not really the main problem though._

Previously (as recently as mid-August), we had a loading indicator inline. See [screenshot in this comment](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9304#issuecomment-2284604382) for a recent message attachments ticket. I've confirmed that this issue was present pre-recent-RN-update (it's present in today's develop build, and the Sept 12th develop build, as well as the branch I'm currently testing where I found the issue).

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Desired behavior

Have a loading indicator when loading an attachment

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High 
- Frequency: Low 

- 2 - High

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by rbontrager** [comment]
Verified that the message now display an attachment loading indicator inline before opening the attachment after a user clicks an attachment. Approved by QA.
