### ISSUE TITLE
[FE] Remove DOB from Proof of Veteran Status

### ISSUE THREAD

**Issue by mcommons10** [department-of-veterans-affairs/va-mobile-app#9660]
### Description
Currently, the Proof of Veteran Status displays the user's date of birth. To reduce the amount of personal information displayed and to be in parity with va.gov, it should be removed. This goal of this ticket is to remove Date of Birth for all user's Proof of Veteran Status in the mobile app.

### Acceptance Criteria
- [ ] DOB is removed from all user's Proof of Veteran Status as shown in the [Figma design](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=607-39280&t=9l2egNJxz6uHld9n-0)
- [ ]  Update demo mode to reflect this change
- [ ]  Update copy to "To fix an error in your disability benefits, call us" 

### Additional Info and Resources
- [Link to Figma design](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=607-39280&t=9l2egNJxz6uHld9n-0)
- For any questions, you can reach out to Megan Commons in [iir-product-teams-public](https://dsva.slack.com/archives/C05RJS5DANT)
- This work should follow the mobile app team's normal QA process. Please coordinate as usual.

**Comment by rbontrager** [comment]
Verified that the DOB is removed from Veteran Status, the copy has been updated to "To fix an error in your disability benefits, call us", and demo mode has been updated.  Verified that this change does not break our veteran status detox tests.  Approved by QA.
