### ISSUE TITLE
[FE] Add DoD ID to Proof of Veteran Status

### ISSUE THREAD

**Issue by mcommons10** [department-of-veterans-affairs/va-mobile-app#9661]
### Description
The goal of this ticket is to add a new section to the Proof of Veteran Status page in the mobile app. To meet legislative requirements and to be in parity with the va.gov experience, users' unique DoD ID number needs to be added. 

### Acceptance Criteria
- [ ] Veteran's DoD ID number is added to the Proof of Veteran Status page as shown in the [Figma design](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=607-39280&t=9l2egNJxz6uHld9n-0)
- [ ] If a user does not have a DoD ID (null value), the section should be removed entirely from the Proof of Veteran Status page
- [ ] Update demo mode to reflect this change

### Additional Info and Resources
- [Link to Figma design](https://www.figma.com/design/AobGKkBvIiDuYXR2QqkytC/IIR-Veteran-Status?node-id=607-39280&t=9l2egNJxz6uHld9n-0)
- A user's DoD ID number is called EDIPI and it exists under user profile on the back end:
https://github.com/department-of-veterans-affairs/vets-api/blob/560e166ba0b4c016a6b09270910f20c920b0e4f9/app/services/users/profile.rb#L87
- For any questions, you can reach out to Megan Commons in [iir-product-teams-public](https://dsva.slack.com/archives/C05RJS5DANT)
- This work should follow the mobile app team's normal QA process. Please coordinate as usual.

**Comment by cadibemma** [comment]
Waiting on BE to add edipi to (mobile) user endpoint. Moving to blocked

**Comment by rbontrager** [comment]
Verified that the veterans DoD ID number has been added to the veteran status card, everything looks like its coming in correctly using Charles, and that if a user does not have one the section is removed.  Verified that the DoD number has been added to demo mode and the detox tests have been updated. Approved by QA.
