### ISSUE TITLE
QA: Test Plan for Travel Pay

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9670]
## Objective 

The purpose of this ticket is to document the test plan for Simple Mileage-Only Claims within the VA Mobile App.

## Reference Material:
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product-outline-btsss.md)
- [Mobile & Experience team Collaboration doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product/initiatives/mobile_collaboration.md)
- [Original request from the Experience team](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9563)
- [Experience team epic](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/91550)

## Known test data:
  

- TBD

## Epic(s)
- [Mobile Epic](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9663)

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

  

## Acceptance Criteria
  

1. - [ ]  Create test plan
2. - [ ] Link to test case folder in TestRail
3. - [ ] List of test data (or other testing needs) for Product
4. - [ ] QA peer review of test plan & cases complete (sent out & feedback incorporated)
5. - [ ] Socialize the testing plan with relevant practices (Eng, UX, Product)
    
Notes:

**Comment by DJUltraTom** [comment]
created: https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=27097&group_order=asc&display_deleted_cases=0
@rbontrager can I get you to do a once over review before we sign off?

**Comment by DJUltraTom** [comment]
implemented @rbontrager 's suggested changes. Closing this ticket as "done"
