### ISSUE TITLE
CU - AvailabilityFramework Detox Test: Replace by.text to by.id wherever possible

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9674]
## Proposed Change

Replace by.text to by.id wherever possible in the availability framework detox test.

**Comment by TKDickson** [comment]
There are no instances of by.text in the AF script (mostly because it references the utils file for all of the heavy lifting, so all of the work for 'this' file will be done in the utils file tickets), so this ticket is complete :) Closing.
