### ISSUE TITLE
Create analytics event for NotEnrolledSM

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9683]
Per [this request](https://dsva.slack.com/archives/C018V2JCWRJ/p1717774537900129) from our PO, we want to create a new analytics event for vama_notEnrolledSM.

**Comment by Sparowhawk** [comment]
vama_sm_notenrolled is the analytic

**Comment by rbontrager** [comment]
Verified that vama_sm_notenrolled is logged when you navigate to SM on a user that is not enrolled (+119).  No other things can be verified so approved.
