### ISSUE TITLE
Backend bug: claims multi file upload missing files data

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9690]
[This](https://vagov.ddog-gov.com/apm/error-tracking?query=%40issue.age%3A%3C%3D172800000%20env%3Aeks-prod%20resource_name%3AMobile%2A&fromUser=false&issueId=d1b2e158-7a80-11ef-8e6d-da7ad0900007&refresh_mode=paused&source=all&from_ts=1727016410000&to_ts=1727189210000&live=false) bug recently popped up in datadog. Looks like the same user tried a few times around this time frame and failed each time.

Looking at the code, it's clear that the files param is needed. Unclear how it could be missing. It's plausible this could be another user who's trying to bypass the app and use our API directly, which may be causing errors that aren't possible from the app, but the request data seems to imply this is coming from an iOS device.

<img width="1522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUw3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b2752049ee028408f245feb43a91e82db68f2f0/image.png" alt="image.png" />

AC:
- ask front end if this is possible from the app
- figure out how we can prevent this if possible

**Comment by Tonksthebear** [comment]
Closing for now. FE checked and there was nothing on their end that seems out of the ordinary

**Comment by Tonksthebear** [comment]
Closing for now. FE checked and there was nothing on their end that seems out of the ordinary
