### ISSUE TITLE
VAIcon to Icon transition pt 1 - webviews

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9717]
This one covers all usage of VAIcon in webviews

**Comment by rbontrager** [comment]
Verified that the top nav bar title and refresh button icons have been updated to use the design system icons (match what is va-mobile-library/packages/assets/icons/vads).  Verified that the everything works as before (refresh button refreshes the page, etc) and that the new icons do not affect the a11y labels.  Approved by QA.
