### ISSUE TITLE
Chevron Up and Down migration to design system Icon

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9721]

**Comment by rbontrager** [comment]
Verified that the chevron up/down in all the collapsibleViews (SignIn, AppealStatus > View past events, DirectDeposit > Find these numbers) and accordianCollapsible (claimPhase, Appointments > No Match, CollapsibleMessage, RemoteConfig) match the new design system icon.  Verified that everything works as expected and that the a11y labels were not affected.  Approved by QA.
