### ISSUE TITLE
Content Work: Travel Pay

### ISSUE THREAD

**Issue by ala-yna** [department-of-veterans-affairs/va-mobile-app#9731]
## Description 
The VA Travel Pay experience team will be building functionality into the mobile app that will allow Veterans to submit Simple Mileage-Only claims. Now that we've done the research in #9666, this ticket will represent the time needed to create the content we'll need to launch SMOC (Travel Pay).

## Important Links
- [Travel Pay epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9663)
- [Travel Pay research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product-outline-btsss.md)
- [Mobile & Experience team Collaboration doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product/initiatives/mobile_collaboration.md)
- [Original request from the Experience team](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9563)
- [Experience team epic](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/91550)

## Web flow explanation/links
- Web starts simple mileage-only travel reimbursement claim from Appointments details screen - [Figma file](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2160-2072&node-type=section&t=jQlAcM7LtmKdOEgO-0) - note no mention of travel on Appointments list view
- They then take users through the claim flow [Figma file](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2111-5020&node-type=canvas&t=gyMB9P2KYAKWasGK-0)
- Users then can check list of travel reimbursements - [Figma file](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=2111-5020&node-type=canvas&t=64Fgmn7XQGduSDU7-0)
- And users can drill down into a status detail of each claim - [Figma file](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=4060-3841&node-type=canvas&t=ghmb132wGHeCGEHZ-0)

## Acceptance Criteria
  

- [X] SMOC claim content is created & documented (started but not finalized)
~- [ ] What's new content is created & documented (for when this is eventually released)~
- [X] Content-specific questions are answered by the Travel Pay team

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Yesterday: Spent a little time reviewing initial redesigns

**Comment by mistymg** [comment]
Yesterday/today: More refinement to content/designs. Shared initial thoughts with Ryan in design stand up. Will need to put down this work for rest of this sprint until after other Global priorities settle down.

**Comment by mistymg** [comment]
Asked how Liz T wants content handed off when finalized. In Figma is fine.

Meeting with Lauren R. tomorrow to regroup after feedback from Ryan last Wed. and to prep for meeting with him/Kristen this Wed.

**Comment by mistymg** [comment]
AC #2 not complete. Created [ticket 9958](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9958) to capture that copy need as it can be done closer to release.

**Comment by mistymg** [comment]
Meeting with Lauren today to refine the designs based on Ryan's feedback last week. Will spend rest of today working on copy tweaks and noting any issues with latest options or other things we need to consider. We'll be sharing with Ryan and Kristen tomorrow afternoon.
