### ISSUE TITLE
Icon Migration VAIconWithText to Design System Icon

### ISSUE THREAD

**Issue by Sparowhawk** [department-of-veterans-affairs/va-mobile-app#9733]

**Comment by TKDickson** [comment]
Passing [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11130181271/job/30929677282) detox test (the URL links is failing in develop; not just this branch); re-running several for [iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11130184298) right now.

**Comment by TKDickson** [comment]
Over my ticket capacity; not working on this.

**Comment by TKDickson** [comment]
Switching to RB - looking at my day today/tomorrow, I'm not getting to this in time this sprint. Leaving the blocked label on, @rbontrager FYI

**Comment by rbontrager** [comment]
This is currently blocked by a potential issue with the design system home icon.  More info can be found [here](https://dsva.slack.com/archives/C07KFQ3U6QH/p1728397412873069).

**Comment by dumathane** [comment]
It seems like from @rbontrager 's thread this ticket now needs app design system to decide if we want the home to be smaller or to custom resize to match? Does that sound accurate rachael? If so should we tag in @kidlaurenpeace ?

**Comment by rbontrager** [comment]
Yes that is accurate.  @wavelaurenrussell You can read the thread linked above but basically I noticed that the home icon looked smaller than the rest of the icons in the nav tab bar.  After a discussion with the design team we need to make the decision if we want to resize the icon and you are probably best to make that decision. I've attached a screenshot of what the current home icon looks like in relationship to the rest of the icons that I showed in the thread.  I can also find you the original build/give you more screenshots if that would help as well (just let me know).

<img width="389" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81e737d01ec0d58cb2ea5019a779a9bb12a9ec97/Screenshot_20241008-095011.png" alt="Screenshot_20241008-095011.png" />

**Comment by Sparowhawk** [comment]
per lauren https://adhoc.slack.com/archives/C067S0FRP0C/p1729610564809519?thread_ts=1729610470.898769&cid=C067S0FRP0C

Match the sizing as close as possible

**Comment by rbontrager** [comment]
Lauren confirmed through VQA that the updated home icon sizing is good [here](https://adhoc.slack.com/archives/C067S0FRP0C/p1729682287121099?thread_ts=1729610470.898769&cid=C067S0FRP0C). Verified that the prescriptions > help icon, edit draft > folder/trash icon,  profile icon, and navigation tab bar icons (Home, Benefits, Health, Payments) look correct and match what is in the va-mobile-design-system library.  Ran a basic a11y check (text resizing, keyboard, dark mode, landscape, voiceOver) and verified that nothing looked/sounded wrong.  Approved by QA.
