### ISSUE TITLE
BUG - Sev 3 - Android- message fails to send and then every character deletion triggers snackbar error messaging

### ISSUE THREAD

**Issue by DJUltraTom** [department-of-veterans-affairs/va-mobile-app#9737]
## What happened?

When writing a message on android that fails to send. after dismissing the "Message not sent" snackbar and text that is deleted results in the snackbar error reappearing.

## Specs:

- Device: google pixel 4a
- OS:
- User Account:n/a
- Accessibility State: N/A

## Steps to Reproduce

- attempt to send a bad message (a message with some text and emojis in it)
- Dismiss the "message not sent" snackbar
- in the text field delete an emoji or text
- observe the snackbar reappears repeatedly

## Desired behavior

snack bar should only appear when message is attempted to be sent

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact:  Low 
- Frequency:  Low 

- 3 - Low

## Screen shot(s) and additional information

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--953ee613253573a7ee825f161f083059ba309482/az_recorder_20240927_211517.mp4)

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL01MQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6617ed57822690dfd957a9e34926b2cd2fdec2b/az_recorder_20240927_211650.mp4)

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by alexandec** [comment]
Note for QA, the following actions are affected:

- Send message
- Save message draft
- Reply to message
- Save reply draft

An area of focus for me was making sure the "Try again" button works correctly after updating the message subject or message text. For example, attempting to send or save with an emoji in the message body, then removing the emoji and hitting "Try again".

**Comment by DJUltraTom** [comment]
I was able to successfully send, save, reply, and save reply, edit the messages and snackbars were no reappearing, aka, acting as expected.
QA approves this fix. PR approved

**Comment by DJUltraTom** [comment]
verified this fix is present on the daily over night QA build
Closing as deployed
