### ISSUE TITLE
BUG - Detox - Fix detox auto run per PR

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9756]
## What happened?

With the removal of the FE-Needs Review label, the github actions script that runs the detox test automatically on a PR broke. This ticket removes the logic to have it run when the PR goes out of draft and is labeled with FE-Needs Review and will instead have the relevant detox test run whenever a person commits something to a PR.

**Comment by IsraelleHub** [comment]
I think the 'what hapenned' section here should also go on the description of the PR #9757
