### ISSUE TITLE
Update Medication Wording for Appointments | In Person & Community Care & Phone

### ISSUE THREAD

**Issue by juancstlm-a6** [department-of-veterans-affairs/va-mobile-app#9759]
## Description 
As a user of the mobile app with an **In person Appointment** or a **Community Care Appointment**, I would like to see the same content for preparing for my appointment that I see in the Pre-Check-in and Appointments web applications.

As part of this story we want to: 
- Update the content in a **In person Appointment** and  **Community Care Appointment** details to include the following component. Existing content/wording relating to medication wording will be removed in favor of only the component listed below.
![Image](https://github.com/user-attachments/assets/6f3af9d8-183b-49e4-a554-cd1a146b3090)

## Acceptance Criteria
  

-  [x] Update **In person Appointment** details to include the "Medication wording" component [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3169-3474&t=lLM5zNI3XDVt5pxX-4)
- [x] Update **Community Care Appointment** details to include the "Medication wording" component [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3169-8513&t=lLM5zNI3XDVt5pxX-4)
- [x] Update **Phone Appointment** details to include the "Medication wording" component [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3169-11256&t=lLM5zNI3XDVt5pxX-4)
- [x] Update **Video At VA Appointment** details to include the "Medication wording" component [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3169-11256&t=lLM5zNI3XDVt5pxX-4)
-  [x] "Medication wording" component contains a link that opens https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/ in a in app web view

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Test accounts that have `In Person` appointment 
    - Test accounts that have a `Community Care` appointment
    - Test accounts that have a `Phone` appointment
- Does this require QA?
   - Yes
    
- Dev Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by juancstlm-a6** [comment]
Mobile app demo mode has the 3 types available to use as test data and should suffice for development.

**Comment by TKDickson** [comment]
[iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11444414091) and [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11444410018) runs of appts and appts expanded (PR only ran appts automatically, there's a ticket being worked to update the mapping script)
