### ISSUE TITLE
Update Medication Wording for Appointments | VA Video

### ISSUE THREAD

**Issue by juancstlm-a6** [department-of-veterans-affairs/va-mobile-app#9763]
## Description 
As a user of the mobile app with an **VA Video Appointment**, I would like to see the same content for preparing for my appointment that I see in the Pre-Check-in and Appointments web applications.

As part of this story we want to: 
- Update the content in a **VA Video Appointment** of type `At Home` `GFE` `Atlas` details to include the following component. Existing content/wording relating to medication wording will be removed in favor of only the component listed below.
![Image](https://github.com/user-attachments/assets/2ea6d340-08c7-46ec-aaea-6169cb8f4b7e)
- Remove the existing "How to prepare for your video appointment" link that opens the Large Pannel for Appointments help in favor of the new component above

## Acceptance Criteria
-  [x] Update **VA Video Appointment** for `At Home` `GFE` `Atlas` details to include the "Medication wording" component 
-  [x] "Medication wording" component contains a link that opens https://www.va.gov/resources/what-should-i-bring-to-my-health-care-appointments/ in a in app web view
- [x] "Medication wording" component for a Video appointment with type `At Home` `GFE` `Atlas` has a link to open a sheet that displays how to set up your device. 
  ![Image](https://github.com/user-attachments/assets/e2826886-769d-452d-b9f4-b009615a73ea)
- [x] Update PrepareForVideoVisit component to include only the updated content in the screenshot above [Figma](https://www.figma.com/design/ZIHY63cFlD7pFjqQLA5rFN/Appointments-2.0---%F0%9F%94%8D-Working---VA-Mobile?node-id=3190-2705&t=5W7oLepJvCN8iVFf-4)
- [ ] e2e Test are updated or created to cover the changes
- [ ] Unit tests are updated or create to cover the changes

## Notes & Open Questions

- Dependencies/Roadblocks:
    - Test accounts that have **VA Video Appointment** appointment of type `At Home` `GFE` `Atlas` and `At VA`
- Does this require QA?
   - Yes
    
- Dev Notes: 

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by TKDickson** [comment]
[iOS](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11520159209) and [Android](https://github.com/department-of-veterans-affairs/va-mobile-app/actions/runs/11520153058) detox - mapping on PR didn't run the expanded appts, again
