### ISSUE TITLE
CU - HomeScreen Detox Test: Replace by.text with by.id wherever possible

### ISSUE THREAD

**Issue by rbontrager** [department-of-veterans-affairs/va-mobile-app#9765]
## Proposed Change

eplace by.text with by.id in the homeScreen detox test wherever possible.

**Comment by rbontrager** [comment]
@TKDickson It looks like the mapping is looking for veteranCrisisLine and not veteransCrisisLine and the homeScreen test isn't included so yes please make a ticket if you can.

**Comment by TKDickson** [comment]
Wrote #9827 for the detox mapping changes needed (added to the Q4 work epic), and merged.
