### ISSUE TITLE
Convert appointments specs to validate against openapi docs

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9775]
This work is partly done and work in progress will be put on a branch. 

AC:
- every unique combination of VCR cassettes used in the appointments request specs should be validated against the openapi docs
- make any corrections to the docs necessary to make them match the specs
- add schema coverage for the partial error (207) case. 
- facility_id and sta6aid are listed in our docs, but are not actually included in our serializer, which means our docs are inaccurate. This is not causing issues because the front end doesn't use them. Remove references to them in the adapter, model, and docs. Confirm this with the frontend team and inform them that they can remove their references to facility_id (they do not reference sta6aid).
- the frontend also sets a practitioner attribute that is not returned by the backend or mentioned in the docs. They can remove that.
- remove existing validations against our spec json fixtures and delete the appointments fixture.

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9775?planning-poker) with Zenhub @kpethtel @Tonksthebear
