### ISSUE TITLE
Add openapi tests to specs

### ISSUE THREAD

**Issue by kpethtel** [department-of-veterans-affairs/va-mobile-app#9776]
We're converting our specs to use the committee-rails gem in order to ensure that our request specs and documentation are aligned.

AC:
- convert request specs
- timebox it
- remove old json matching specs and the fixture files
- add`additionalProperties: false` to all objects where appropriate. This will probably be all objects except maybe the meta.

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9776?planning-poker) with Zenhub @kpethtel @Tonksthebear

**Comment by StacyB2023** [comment]
@aherzberg would this be considered tech debt or documentation for future teams? Just trying to decide when we can add this into an epic.

**Comment by aherzberg** [comment]
I'd say tech debt. It'll help both spec and doc creation in the future be more accurate and quicker to make

**Comment by StacyB2023** [comment]
@aherzberg ok, thanks. I added the epic

**Comment by StacyB2023** [comment]
@aherzberg ok, thanks. I added the epic
