### ISSUE TITLE
Record current timeout time for each endpoint 

### ISSUE THREAD

**Issue by jperk51** [department-of-veterans-affairs/va-mobile-app#9778]
ACs:
- [ ] create a list of upstream timeouts for each of our endpoints

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9778?planning-poker) with Zenhub @kpethtel @Tonksthebear

**Comment by StacyB2023** [comment]
Not too sure on the background of this ticket. Let me know if we want to pull this into next sprint @jperk51

**Comment by jperk51** [comment]
The background is every once in a while we have people asking us about how long our endpoints take to timeout and they aren't all the same so I would like to document our current state so we can just link it to people in the future instead of having to dig into the code to check every time.

**Comment by aherzberg** [comment]
[Mobile Timeouts.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXZxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e1ba3d60e3e40cd55721f2f56456a0525cc96211/Mobile%20Timeouts.xlsx)
in case the spreadsheet gets lost, here is the file. biggest red flag is decision letter endpoints have a read timeout of 1200 seconds. https://docs.google.com/spreadsheets/d/1Dk1QS-VWjg-Mn33qGhqe99OrCNEGIuo_zfOMe6oC8N8/edit?usp=sharing
