### ISSUE TITLE
Documentation - testing analytics event firing in staging

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9781]
ACs:

- [x] Record a demo of the steps taken to test analytics events firing at the correct time, in staging
- [x] Add a link to that demo's recording, to the va-mobile-qart DSVA channel private bookmarks collection
- [x] Share the recording/demo/fact that this is done, with the QART team at the next team sync

**Comment by rbontrager** [comment]
Video has been made, link has been added to the va-mobile-qart DSVA channel and I shared that it was there during the QA meeting last monday (10/14/24).  Closing this ticket as complete.
