### ISSUE TITLE
QART: Update RC script & automation per postmortem

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9878]
Per [this postmortem discussion](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/products/mobile-app/qart-postmortems.md#9288-9476-and-9461), should update the RC script and automation in these ways:

- [x] exclude assistive tech cases from being pulled in that are covered by automated UI testing (large text, landscape, dark mode)
- [x] make the assistive tech rotation selection automated, instead of manual. (testRail api btw: https://support.testrail.com/hc/en-us/articles/7077292642580-Cases.  You should be able to get the run and then add a case to the run and then repost it.)
- [ ] Simplify/rewrite the existing manual RC cases to focus solely on what should be tested manually (may be fine as-is, or may have some extra steps that can be removed)

**Comment by rbontrager** [comment]
All assistive tech cases already tested by navigation (large text, landscape, dark mode) have been un-checked as a release candidate in testRail.  I glance over the manual RC test cases and they still are focusing solely on what should be tested manually.  And the attached PR randomly selects an accessibility related test (minus the ones above) and will put it into the RC.
