### ISSUE TITLE
BUG - sev-3 - All - Stop making v0/claims/decision-letters calls in claims history when decision letters are down?

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9901]
## What happened?

I was doing claims-related testing (logging in, submitting evidence, requesting a decision - on 4 claims) and nearly every navigational thing I did triggered a v0/claims/decision-letters call that returned with a 500
```
{
	"errors": [{
		"title": "Internal server error",
		"detail": "Internal server error",
		"code": "500",
		"status": "500"
	}]
}
```

The service is down/erroring, obviously - going to the decision letters page itself throws the usual error screen - but it seems like we could do a better job detecting that decision letters is down and NOT repeatedly calling it like this:
<img width="1582" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--998395dd6538174454cfaa79cf5a1b62e79ade0b/image.png" alt="image.png" />

## Specs:

- Device:
- OS:
- User Account:
- Accessibility State:

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: High Low 
- Frequency: High Low 

- 3 - Low
- 2 - High
- 1 - Critical

## Screen shot(s) and additional information

<details>
  <summary>Full JSON response for services related to issue (expand/collapse)</summary>
  

</details>

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by Sparowhawk** [comment]
@TKDickson is there a downtime window that this was during? I am just trying to figure out if that is what we could tie the calling of this api to. Otherwise anything that would trigger a refetch would call the api unless there is something that we can do to block them that we got a success from.

There might be some way for us to check the failure count and failure reason to then stop further calls from happening for a period of time, but it's hard to determine what those thresholds should also be

**Comment by TKDickson** [comment]
@Sparowhawk no, not a downtime window. It was a genuine error being returned from the server. I wrote this up because of the sheer volume of calls we're making (pretty much any navigation I made, every time I moved screens, we were sending a call that failed). I will close this one until/unless we hear from an upstream service that we need to implement a system like the one you mentioned.
