### ISSUE TITLE
QA - baseline assessment for 'we stop testing when' criteria

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9930]
- Pick a reasonable number of prior sprints (1? 2?)
- For all tickets tested within that sprint, assess if they met [when stop testing criteria](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/HowWeWork/#we-stop-testing-when)
- Give feedback (individual)
- Share overall patterns & progress (team/sync)
- Document status & findings somewhere it can be found again (not just this ticket)

**Comment by TKDickson** [comment]
@SarahHuber-AdHoc unassigning from myself, as I am unlikely to get to this ticket, this sprint. Arguably, this may be a ticket that we should just close.

**Comment by SarahHuber-AdHoc** [comment]
go ahead and close it.
