### ISSUE TITLE
Onboarding: David Formanek

### ISSUE THREAD

**Issue by oddballdave** [department-of-veterans-affairs/va-mobile-app#9957]
### Full Name

David Formanek

### GitHub Username

oddballdave

### VA Email Address

david.formanek@va.gov

### Which team is this person on?

Mobile Feature Support

### Who is the OCTO Product Owner for this person's team?

Jeff Barnes

### What is the main Slack channel for this person's team primary team?

#mobile-feature-support-public

### Process Documentation

- [x] Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [x] Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
- [x] Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
- [x] Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
- [x] Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
- [x] Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)

### System Access

- [x] App store connect (VA Mobile will provide)
- [x] Firebase (VA Mobile will provide)
- [x] Write access to applicable repositories (VA Mobile will provide)
- [x] Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

### Engineering-specific documentation

- [x] Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
- [x] Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
- [x] Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
- [x] Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
- [x] Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
- [x] Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
- [x] Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
- [x] Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
- [x] Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
- [x] Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
- [x] Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
- [x] Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)
- [x] Information about [accessing Demo Mode](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Mobile%20Demo%20Mode)

**Comment by timwright12** [comment]
Hi @oddballdave, welcome to the group! Does the Mobile Feature Support team have a [github team](https://github.com/orgs/department-of-veterans-affairs/teams/?query=) I can use for assigning repo access? If not, would to mind spinning one up for your group?

In the meantime please read through the documentation linked in this issue and check it off as you work your way through it.

**Comment by oddballdave** [comment]
> Hi [@oddballdave](https://github.com/oddballdave), welcome to the group! Does the Mobile Feature Support team have a [github team](https://github.com/orgs/department-of-veterans-affairs/teams/?query=) I can use for assigning repo access? If not, would to mind spinning one up for your group?
> 
> In the meantime please read through the documentation linked in this issue and check it off as you work your way through it.

Our program manager just created a team: [Mobile Feature Support](https://github.com/orgs/department-of-veterans-affairs/teams/mobile-feature-support)

**Comment by timwright12** [comment]
@oddballdave invites have been sent for access, will hold off on write repo access until you've had a chance to start going through the listed documentation (please check off as you complete)

**Comment by oddballdave** [comment]
> [@oddballdave](https://github.com/oddballdave) invites have been sent for access, will hold off on write repo access until you've had a chance to start going through the listed documentation (please check off as you complete)

Thank you. I have read through all of the documentation. I assume those invites went to my va.gov email? The reason I ask is I won't have my PIV card for at least 10 more days and thus cannot get into my va.gov email yet.

**Comment by timwright12** [comment]
@oddballdave yes all invites will go to your VA email (other than github), so you'll need to get in there to accept them. Once you get your card feel free to ping me in slack to make sure the invites haven't expired

**Comment by timwright12** [comment]
Once you're ready to get going (no rush), we've curated a list of [Good First Issues](https://github.com/department-of-veterans-affairs/va-mobile-app/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Good%20first%20issue%22) to help you get familiar with the app, PR processes, and the general build systems - some good lightweight tasks for onboarding. Feel free to grab some and just assign them to yourself.

**Comment by timwright12** [comment]
I can send that to you

**Comment by timwright12** [comment]
Going to close this ticket out as all the docs have been marked off and access has been send. If you need further support we can handle that in the va-mobile-app Slack channel
