### ISSUE TITLE
Consume new efolder api for claims file view

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9969]
## Proposed Change

Consume the endpoint created in [this](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9774) ticket and setup the appropriate react-query requirements.

## Why Should We Prioritize?

Making previously submitted files accessible to the user.

## Coding Time Estimation

2

## Acceptance Criteria

- [ ] Consume the new BE endpoint and have appropriate react-query components.
- [ ] Include new Demo Mode API changes options for the new endpoint.
	
## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by Sparowhawk** [comment]
not testable by QA, testable in 10066 pr

**Comment by DJUltraTom** [comment]
not testable by QA. closing as deployed
