### ISSUE TITLE
Make efolder files viewable in claims

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9970]
## Proposed Change

Now that the new BE endpoint has been consumed, make the file list in claims details pressable and launch into the retrieved files for review. Close should bring the user back to the list of files.

## Why Should We Prioritize?

Making previously submitted files accessible to the user.

## Coding Time Estimation

3

## Acceptance Criteria
File List should follow this design paradigm with the chevrons:

![Image](https://github.com/user-attachments/assets/18e306fb-aaff-4f0d-814c-a554c27f7780)

- [ ] Make file lists pressable and ensure multiple types are viewable through the native file viewer inclusion.
- [ ] Include new Demo Mode files so the file viewer can work on an in progress claim from demo mode.
- [ ] Preview for UX (Lauren) that no additional design requirements are needed on this MVP pass.
	
## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by DJUltraTom** [comment]
the AC is not very clear, are we expecting to be able to launch and view previously submitted files or just view the file names of the files that have been submitted previously. screenshot of what I currently see for submitted files is below: 
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGpLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e205f479133d27f325c3f672788442f0eec9ab2/Screenshot_20241118-181434.png" alt="Screenshot_20241118-181434.png" />

**Comment by DJUltraTom** [comment]
verified file selection is appearing as designed with chevrons and opening attached files using the prepared data in demo mode.
QA approves this change

**Comment by DJUltraTom** [comment]
verified this change is present and functioning in the RC, closing as deployed
