### ISSUE TITLE
Include new Analytic: vama_claim_file_view

### ISSUE THREAD

**Issue by dumathane** [department-of-veterans-affairs/va-mobile-app#9971]
## Proposed Change

Include an analytics log for claim_file_view when a file list item is pressed by the user.

## Why Should We Prioritize?

Making previously submitted files accessible to the user.

## Coding Time Estimation

1

## Acceptance Criteria

- [ ] Include new Analytic for claim file review.

	
## Checklist
- [ ] Add the relevant team label (Health, global, design system, API, Qa and Release etc.)
- [ ] Attach to ticket to the relevant Team Tech Debt Epic epic (old frontend engineering epic is no longer in use as each team is managing their code's technical debt and code upkeep work)

**Comment by DJUltraTom** [comment]
Tagging @rbontrager for simulator analytic goodness

**Comment by rbontrager** [comment]
I can confirm that I'm seeing the event vama_claim_file_view logged when clicking on a file in the files list in claim details.

**Comment by DJUltraTom** [comment]
closing as this has been incorporated in the RC
