### ISSUE TITLE
Create CI job to build docs in CI pipeline 

### ISSUE THREAD

**Issue by aherzberg** [department-of-veterans-affairs/va-mobile-app#9972]
this will avoid having merge conflicts on the generated html doc file

**Comment by jperk51** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Mobile-60f1a34998bc75000f2a489f/issues/department-of-veterans-affairs/va-mobile-app/9972?planning-poker) with Zenhub @aherzberg @Tonksthebear

**Comment by jperk51** [comment]
gitignore the html file
