### ISSUE TITLE
Onboarding: Alex Teal

### ISSUE THREAD

**Issue by ATeal** [department-of-veterans-affairs/va-mobile-app#9984]
### Full Name

Alex Teal

### GitHub Username

ATeal

### VA Email Address

alex.teal@va.gov

### Which team is this person on?

Mobile Feature Support

### Who is the OCTO Product Owner for this person's team?

Jeff Barnes

### What is the main Slack channel for this person's team primary team?

#mobile-feature-support-public

### Process Documentation

- [x] Read and bookmark [VA mobile general documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/)
- [x] Read about [how push notifications work in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Features/PushNotifications)
- [x] Review [accessibility information](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/AccessibilityInformation)
- [x] Read about [how the QA team works with others](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/working-with-others)
- [x] Review the [release overview](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Release%20Management)
- [x] Review the [release policies](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Teams/QA%20and%20Release/Policies)

### System Access

- [x] App store connect (VA Mobile will provide)
- [x] Firebase (VA Mobile will provide)
- [x] Write access to applicable repositories (VA Mobile will provide)
- [x] Join [#va-mobile-app slack channel](https://dsva.slack.com/archives/C018V2JCWRJ)

### Engineering-specific documentation

- [x] Familiarize yourself with the [va-mobile-app repository](https://github.com/department-of-veterans-affairs/va-mobile-app)
- [x] Review [mobile API documentation](https://department-of-veterans-affairs.github.io/va-mobile-app/api/)
- [x] Get a high level understanding about [how authentication works in the app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/BackEnd/Architecture/Auth%20Diagrams)
- [x] Read [remote configuration documentation](https://firebase.google.com/docs/remote-config/)
- [x] Get up to speed on the [Mobile Design System](https://department-of-veterans-affairs.github.io/va-mobile-app/design/Intro)
- [x] Review [how to set up deep linking in th app](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/PushNotifications/DeepLinking)
- [x] Review [development best practices](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevelopmentBestPractices)
- [x] Review [information about unit tests](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/Testing/UnitTesting)
- [x] Review [information about end-to-end testing with Detox](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/)
- [x] Review [best practice documentation around end-to-end testing](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA/QualityAssuranceProcess/Automation/Detox%20Best%20Practices)
- [x] Review [technical details around the mobile release process](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Operations/Releases/release-process)
- [x] Start [getting the app setup locally](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Engineering/FrontEnd/DevSetupProcess)
- [x] Information about [accessing Demo Mode](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/Mobile%20Demo%20Mode)

**Comment by timwright12** [comment]
@ATeal Welcome! I'll start on getting you access to start working. In the meantime please read through the documentation linked in this issue and check it off as you work your way through it.

**Comment by timwright12** [comment]
@ATeal invites have been sent for access

**Comment by timwright12** [comment]
Hi @ATeal, once you're ready to get going (no rush), we've curated a list of [Good First Issues](https://github.com/department-of-veterans-affairs/va-mobile-app/issues?q=is%3Aissue%20state%3Aopen%20label%3A%22Good%20first%20issue%22) to help you get familiar with the app, PR processes, and the general build systems - some good lightweight tasks for onboarding. Feel free to grab some and just assign them to yourself.

**Comment by timwright12** [comment]
Hi @ATeal, checking to see if you've had a chance to read through the rest of the documentation available.

**Comment by ATeal** [comment]
> Hi [@ATeal](https://github.com/ATeal), checking to see if you've had a chance to read through the rest of the documentation available.

Hey sorry yes I have definitely been reading through things and getting stuff set up locally and cross referencing the documentation as I go through things.

So far:
 - app compiling and running on android
 -  unit tests running (did have to pass maxWorkers as jest was literally eating all 32 threads which correspondingly ate all the memory I have allocated in WSL)
 - E2E tests running locally (I did set up a configuration for running via adb as thats how my local setup works with WSL and detox has support for that functionality, not sure if that's worth committing or not or if it's niche and should be kept local)
 - Now deep diving a bit more line by line to understand where things are!

**Comment by timwright12** [comment]
Closing out since all checkmarks are complete. @ATeal please reach out in #va-mobile-app if you have any questions, comments, or issues!
